### ISSUE TITLE
Cannot Download Anything from Mozilla Add-ons/Extensions FF66.0.3

### ISSUE THREAD

**Issue by GitMoMan** [mozilla/addons#1000]
Describe the problem and steps to reproduce it:
Every time I hit the "add extension/add-on" button FF 66.0.3 would come up saying "Download Failed. Please check your connection". This occurred in every instance I tried to download an extension, add-on, theme, etc. My connection is perfectly fine and working normally. 

![image](https://user-images.githubusercontent.com/50262177/57177515-d5f97500-6ea7-11e9-93b3-1cc4f00ce118.png)

What happened?
No download occurred, Just asked for the connection to be checked

What did you expect to happen?
I expected the download to happen

Anything else we should know?
All my extensions and add-ons have been added to "Legacy Extension" and deactivated. This is including all the very upto date and recent extensions that I added, such as Facebook Container, All this occurred just tonight (4/05/2019). Beforehand, my extensions and add-ons were working normally and had been for quite some time.

**Comment by willdurand** [comment]
Hi, sorry for that. We're having a certificate issue but we're working on it. More info at: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by GitMoMan** [comment]
Thanks Will. It's a pain in the butt having everything crash like that. Hope you can resolve the issue quickly.
