### ISSUE TITLE
Addons disabled as 05/04/2019

### ISSUE THREAD

**Issue by kevomac12** [mozilla/addons#1001]
### Describe the problem and steps to reproduce it: 
Ublock and Adblock Plus, GOT theme removed from my browser setup!
Opened my browser in Windows 10, ver. 1803...browser reported some addons were disabled, provided button to find alternatives, nothing was found for GOT, Ublock or Adblock plus. As these are being reported as not having been built in WebExtensions APIs.

### What happened?
No download can occur via this browser (even though I am using said browser now) to add an extension!!!

### What did you expect to happen?
Downloads of extensions to occur.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Download failed. Please check your connection.
Preview of µBlock
µBlockby uBlock, LLC

The most efficient blocker for Firefox.

No ads, no tracking, and insanely faster page loads.
Add to Firefox

**Comment by willdurand** [comment]
Hi, we are aware of this issue and we're working on a fix. Sorry for the inconvenience, more info at: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
