### ISSUE TITLE
download add on - android firefox

### ISSUE THREAD

**Issue by dascount** [mozilla/addons#1002]
![Screenshot_20190504-061248](https://user-images.githubusercontent.com/50263566/57177863-8464d200-6e36-11e9-8fa4-74cc3bbd7424.png)

Seeing attached error when attempting to download add on.
I use the add on 'dark mode' and yesterday it stopped working.  
Uninstalled add on and attempted to down load again, was then presented with this error.
Restarted device, and then uninstalled Firefox from device, and reattempted after clean install, still this error.

Attempted to add other add-ons, receiving same error

Android 6.0.1 dtek60

**Comment by willdurand** [comment]
Hi, sorry for the inconvenience. We're aware of this issue and we're working on a fix. More info at: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047.

**Comment by willdurand** [comment]
As far as I know, we do not have a hotfix for Android *right now* but FF Desktop should get fixed automatically.

**Comment by diox** [comment]
We're working on releasing a "true" update that will fix it for everyone, follow the discourse thread for more information as the situation progresses.

**Comment by Ev92** [comment]
SOLVED - A few people discovered their clock was wrong, they corrected it and the problem went away (for them).  Most people who saw those messages said their clock was right and they still had the problem.  I began to wonder if Mozilla's clock was wrong so I tried setting my clock to yesterday and it worked.  Then I set my clock back to the correct day and all is well.
