### ISSUE TITLE
Firefox disabled adblocker (ublock origin)

### ISSUE THREAD

**Issue by rradar** [mozilla/addons#1003]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?

Firefox disabled my adblock addon (ublock origin). I can't browse the web anymore! It's just full of trash (adds). The Browser is not totally unusable!

### What did you expect to happen?

Leave it where it is, enabled so I can browse the www!

### Anything else we should know?

Installed Chromium with ublock origin to be able to browse the web again...

**Comment by willdurand** [comment]
Hi, we're working on fixing this. It should be automatically fixed in the next 6 hours. More info: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by rradar** [comment]
6 hours? No joke?

**Comment by willdurand** [comment]
Yes, 6 hours... (maximum). Sorry for that. And yes, everyone wants to get an update by browsing this page :/

**Comment by rradar** [comment]
When the shit hit's the fan... Thank's for the information
