### ISSUE TITLE
Include ublock origin into Firefox

### ISSUE THREAD

**Issue by rradar** [mozilla/addons#1004]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?

As stated in my other issue #1003 I was forced to browse the www without adblocker. It was a very hard experience for me and stopped it right away. There is a lot's of things you don't want to see and some of the unfilterd contet (without active ublock origin) is probably harming people.

I don't browse the web without ad blocker since many years - but now - with the forced look into the shit hole...

### What did you expect to happen?

As there is people who browse the web without installing a proper ad blocking addon firefox should take care of these poor people by installing the ublock origin addon by default

### Anything else we should know?

You should'n be able to deactivate my ad blocking addon!!!

**Comment by willdurand** [comment]
Sorry for the inconvenience, we're aware of the issue and we've deployed a fix. That can take up to 6 hours to work but it should be fixed automatically: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047.

**Comment by rradar** [comment]
You don't reply to this issue @willdurand but to my other one here #1003 

Please reopen - thank's

**Comment by willdurand** [comment]
oh I see. Well, there is a "content blocking" feature in FF that should address that (in part), but this might not be available in FF release yet. In any case, that's not related to add-ons if it is part of FF itself.

**Comment by rradar** [comment]
So the title should be "Include ublock origin natively into Firefox" to be reopend?

**Comment by willdurand** [comment]
Not here. Probably in https://bugzilla.mozilla.org/

**Comment by rradar** [comment]
Ahh.. think I'm moving forward - there are other browsers...
