### ISSUE TITLE
No kill switch for installed addons

### ISSUE THREAD

**Issue by rradar** [mozilla/addons#1005]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?

Firefox disabled my ad blocker (#1003)
I can't browse the web anymore with firefox (installed chromium with ublock origin on the desktop for now)

### What did you expect to happen?

There should be no kill switch for my installed addon(s)

I always should be able to activate them despite big brother likes them or not. Also I should only be asked if I want to disable them.

Could be something like:

> The addon xyz could checked against the signature zyx - we think that this addon could harm your system and advise you to deactivate it
> 
> YES - deactivate
> NO - leave it like it is

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

I'm really really pissed that something like this is POSSIBLE and that it HAPPENS!

**Comment by willdurand** [comment]
Hi, sorry for the inconvenience. We're aware of this problem and we pushed a hotfix (that can take up to 6 hours to get applied though). More info at: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by rradar** [comment]
Once again @willdurand you reply to my other issue #1003 

Please reopen and reply to this one! Thank's
