### ISSUE TITLE
Add-ons won't install because file is corrupt

### ISSUE THREAD

**Issue by PhoenixFireOwl** [mozilla/addons#1006]
### Each time for both of them, I would get a pop-up saying that the download wouldn't install because the file seems corrupted. 

I would delete Firefox's cache and try again. I uninstalled Firefox and reinstalled it. I clicked to install, but get the same message for both of them. I even have uninstalled Firefox and reinstalled it. I get the same msg for both add-ons. I haven't tried any others.

### Anything else we should know? I took a screenshot, but don't know how to place it somewhere where you can access it. I can email it to you.

(Please include a link to the page, screenshots and any relevant files.)

**Comment by xicor333** [comment]
they said in a different thread to 'enable studies' to fix the issue... but there is no 'enable studies' option on android... so i'm guessing android firefox users are SOL.

**Comment by diox** [comment]
Correct, there is no fix for Android yet. See this issue: https://github.com/mozilla/addons/issues/1002

Follow the [discourse thread](https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/13) for more information for both desktop and Android.
