### ISSUE TITLE
tells me i have the wrong version of firefox

### ISSUE THREAD

**Issue by sfzombie13** [mozilla/addons#1010]
### Anything else we should know?  i tried to allow studies like suggested but it was greyed out on the page.  
(Please include a link to the page, screenshots and any relevant files.)

https://imgur.com/a/zkqx4QM

**Comment by wagnerand** [comment]
Please stay tuned while we work on a fix for older versions of Firefox. Thank you.

**Comment by sfzombie13** [comment]
did you look at the pictures?  it says i have an older unsupported version of firefox and the picture clearly shows that i have version 60, not anything under 44 like the message says.  this issue is NOT resolved.  it is NOT related to the addon issue (which did not come back to my browser since it is too old to support them).  please llok into it and tell me what you need from me to fix it.  as i said, i am using linux mint 18 and installed the firefox esr with auto updates and it says i have 60.1.0.

**Comment by sfzombie13** [comment]
The issue was not fixed and is not related to the add on issue.  That
is what caused my add ons to disappear but now I cannot add them back
because it says they are not supported by my version of Firefox when
it is clearly 60.1.0 ESR, just like the picture shows.   I added this
comment to the Github issue but since it is closed I figured I would
reply also.  What other information do you need from me to solve this
one?  I would hate to start using Chrome, even though Firefox is
slowly morphing into Chrome, just because I hate Google.

On 5/4/19, Andreas Wagner <notifications@github.com> wrote:
> Please stay tuned while we work on a fix for older versions of Firefox.
> Thank you.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla/addons/issues/1010#issuecomment-489327467


-- 
Tim Sayre
Kanawha I T Security <http://kitswv.com>

The information in this transmission may contain proprietary and
non-public information of Kanawha I T Security Ltd. or its affiliates
and may be subject to protection under the law. The message is
intended for the sole use of the individual or entity to which it is
addressed. If you are not the intended recipient, you are notified
that any use, distribution or copying of the message is strictly
prohibited. If you received this message in error, please delete the
material from your system without reading the content and notify the
sender immediately of the inadvertent transmission.

**Comment by diox** [comment]
A fix is coming for ESR, please be patient.

**Comment by sfzombie13** [comment]
As I said, this is not related to the issue you were having, as it has
been going on for a year now.  I am most patient and have waited a
long time just to file the issue.  I just want to make sure that you
know it is a separate issue and needs to not be closed saying a fix is
coming.  Surfing with ads sucks balls.  I guess I need a Pihole now.

On 5/5/19, Mathieu Pillard <notifications@github.com> wrote:
> A fix is coming for ESR, please be patient.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla/addons/issues/1010#issuecomment-489422486


-- 
Tim Sayre
Kanawha I T Security <http://kitswv.com>

The information in this transmission may contain proprietary and
non-public information of Kanawha I T Security Ltd. or its affiliates
and may be subject to protection under the law. The message is
intended for the sole use of the individual or entity to which it is
addressed. If you are not the intended recipient, you are notified
that any use, distribution or copying of the message is strictly
prohibited. If you received this message in error, please delete the
material from your system without reading the content and notify the
sender immediately of the inadvertent transmission.

**Comment by diox** [comment]
It may be that you have `privacy.resistFingerprinting` set or something else preventing us from correctly identifying your browser version. This is a known limitation of that preference.

**Comment by sfzombie13** [comment]
Nope, but thanx for the tip.  What else could be preventing it from
identifying?  What information do you need from me to solve the issue?
 I can send you the whole about:config if you want or you could just
tell me what to look for.  If I am taking too much time(it is Sunday
morning) let me know, I hate to be rude.

On 5/5/19, Mathieu Pillard <notifications@github.com> wrote:
> It may be that you have `privacy.resistFingerprinting` set or something else
> preventing us from correctly identifying your browser version. This is a
> known limitation of that preference.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla/addons/issues/1010#issuecomment-489423228


-- 
Tim Sayre
Kanawha I T Security <http://kitswv.com>

The information in this transmission may contain proprietary and
non-public information of Kanawha I T Security Ltd. or its affiliates
and may be subject to protection under the law. The message is
intended for the sole use of the individual or entity to which it is
addressed. If you are not the intended recipient, you are notified
that any use, distribution or copying of the message is strictly
prohibited. If you received this message in error, please delete the
material from your system without reading the content and notify the
sender immediately of the inadvertent transmission.

**Comment by diox** [comment]
You may have a profile in a weird state because of past add-ons, in which case resetting it or starting with a new one would help. Or you may have a weird build of ESR with some customizations that could affect our detection, I don't know. Once we release a fixed ESR version for the disabled add-ons, try that as well.
