### ISSUE TITLE
Corrupted adds-on ?

### ISSUE THREAD

**Issue by Trazul45** [mozilla/addons#1011]
hello my name is Guy
### Describe the problem and steps to reproduce it:
suddenly AdBlock, Pinterest and Qwant adds on were deactivated.

### What happened?
So i uninstall these adds-on and try to re-add them but always get something like " this add on was not installed because it seems to be corrupted"
### What did you expect to happen?
I suppose these adds-on to work and find weird they all together do not work at the same time.
### Anything else we should know?
i am using firefox under windows 10
sample link https://addons.mozilla.org/fr/firefox/addon/adblock-plus/?src=search but same problem with Pinterest and Adblock.
No software neither hardware changes to my desktop well i must say nothing known to me ;-)
sample image of adding an add-on
![qwant instal](https://user-images.githubusercontent.com/50267762/57179874-d59ab300-6e82-11e9-99bc-f3343189f99e.png)

thank you

**Comment by chunkhang** [comment]
@Trazul45 See #978
