### ISSUE TITLE
Certificate issue causing add-ons to be disabled or fail to install:

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons#1013]
An expired certificate has caused add-ons to stop working or fail to install. Developers are also currently unable to publish new or updated extensions. 

We are rolling out an update for Release, Beta, Nightly, and ESR users. The fix will be automatically applied in the background, so you don’t need to take active steps. You _can_ download the update from https://www.mozilla.org/firefox/new/ yourself to accelerate the process.

**Please do not use unofficial workarounds from untrusted sources! They can have unintended or untested side-effects or could (and have!) make things even worse.**

See the latest updates here > https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by KiranovBeck** [comment]
Hello Caitmuenster..
I just also posted #1015 I have tested on multiple computers had the same issue at the same time. and I can confirm it works...

This is good to reinstall your addons again from scratch of the user already knows what they were.

Thanks
Joe

**Comment by Turmfalke2** [comment]
Is there a ff release that includes the fix? Or can we manually replace the certificate?

**Comment by caitmuenster** [comment]
@Turmfalke2 Not yet! We've got a release with a fix in testing right now. If you're interested in a temporary hotfix, please see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

Thanks for your patience and please keep hanging tight!

**Comment by Turmfalke2** [comment]
> Data reporting is disabled for this build configuration

I can't enable that.

**Comment by caitmuenster** [comment]
@Turmfalke2 You might need to wait a bit longer for another fix. :( Sorry for the inconvenience!

**Comment by graywolf** [comment]
https://news.ycombinator.com/item?id=19826903 is fix working for me without the studies enabled.

**Comment by cup** [comment]
https://github.com/mozilla/addons/issues/1028

**Comment by PB-40** [comment]
As well as losing addons/extensions/plugins due to this bug, I have also lost languages - is this due to the same problem and is it being fixed?
"English (GB) Language Pack could not be verified for use in Firefox and has been disabled."

**Comment by diox** [comment]
It is the same issue and should be fixed the same way. See https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/ for a fix while waiting for new versions to be deployed.

**Comment by achalmoudgal** [comment]
Dear Mozilla Team, 
Thanks a Ton for the triage patch. Appreciate your response. One humble request - in future when there are short blackouts of this kind, request you to post a Banner right with in the Browser, for Patches are all in you control.
Regards, 
Achal.

**Comment by ArturFormella** [comment]
Is there any way to fix this error without enabling studies?

**Comment by cup** [comment]
@ArturFormella 

https://reddit.com/r/firefox/comments/bkspmk/addons_fix_for_5602_older

**Comment by diox** [comment]
Do *not* blindly install things manually. This sort of behavior can (and has for some people) cause some additional breakage.

If you don't want to enable studies, then wait for the official fixed releases that will be deployed soon.

**Comment by shadow42085** [comment]
![Untitled-1](https://user-images.githubusercontent.com/7533539/57197657-0852b300-6f38-11e9-81f0-5e0b0f95d2dc.jpg)
uncheck the warn button problem solved atleast for me

**Comment by cup** [comment]
@diox its been 2 days.

you cant be surprised if people are tired of waiting. this website thats been
pointed to:

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox

has comments turned off, and no updated in 12 hours. What do you expect people
to do?

**Comment by diox** [comment]
Lots of people have been working around the clock for the past 2 days, on a week-end, to solve this. It may look like a trivial problem but it's not, so there was simply no new things to add to the post.

A new release is being deployed with the fix as I type this.

**Comment by rradar** [comment]
Hardest part is that mozilla not only send their own user base to their doom but probably helped to deanonymize ten thousands of tor browser users. You don't need enemies if you have friends. :disappointed:

**Comment by Turmfalke2** [comment]
The bigger question is why is this system even in place to begin with? If as the user trust the author of an addon, why should mozilla be able to prevent me from using it? Also if the mozilla trusted the addon yesterday and the addon hasn't changed, why should they distrust it today?

I would understand a warning for installing a new addon that is signed by an expired certificate, but I don't see why it should disable already installed addons.

**Comment by rradar** [comment]
@Turmfalke2 I opened a issue for this here #1036 to **get back** the **freedom** of choice.

**Comment by DancingBear1** [comment]
@diox I think we all know that they are working hard on fixing this. But imagine this:

> A car company changes the cars of millions of customers, even though there is a massive resistance of the customers against this change. But the company says it is an 'improvement' and does it anyway.
> A few months later every car they 'improved' stops working. And the millions of customers are angrily returning their cars to the company and demanding that they fix it. Of course, the company is working very hard in that issue. But **they** f*cked up! **They** have been **warned**! I this situation the company tells its customers 'how hard they have been working on fixing it'. But that is what they should do. It is not something to brag with. It's the least they can do after creating this mess


The company is Mozilla, the car Firefox.

.

**Comment by DancingBear1** [comment]
@diox I don't want to be disrespectful to you or Mozilla in any way. I love Firefox and I'm a proud user. I think Mozilla is doing a good job. But I think the way they reacted was wrong. And pushing a fix via 'Studies' was not good. In the linked blog post they never even tell that you have to enable telemetry for that.It's just bad crisis management

**Comment by typo3ua** [comment]
I have the same problem...

**Comment by cup** [comment]
@diox its been 3 hours, is the deploy finished?

if so - do you have a link to download?

thanks.

**Comment by diox** [comment]
The update is being rolled out automatically, as described in the [updated blog post](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/). It can also be downloaded manually from https://www.mozilla.org/en-US/firefox/new/

**Comment by cup** [comment]
@diox and what about users who dont have version 66 or 60? They are out of luck?

**Comment by rradar** [comment]
Armagadd-on-2.0 over?

Guess it's time to get freedom back then! Decentralize addon signing now! #1036 :fireworks:

**Comment by cup** [comment]
https://github.com/mozilla/addons/issues/1038

**Comment by smayer97** [comment]
Solution does not address older versions that are also affected, e.g. v48 . Please address.

**Comment by PI-Victor** [comment]
downloaded the new version, have the same issue at this point

**Comment by cup** [comment]
@smayer97 

https://reddit.com/r/firefox/comments/bkspmk/addons_fix_for_5602_older

**Comment by estebanz01** [comment]
Just wondering if a fix for firefox developer version has been released. I'm on version `67.0b16 (64-bit)`.

**Comment by cup** [comment]
@estebanz01 

https://reddit.com/r/firefox/comments/bkspmk/addons_fix_for_5602_older

**Comment by wagnerand** [comment]
Please do *not* use unofficial workarounds from untrusted sources! They can have unintended or untested side-effects or could (and have!) make things even worse.

**Comment by caitmuenster** [comment]
Hey folks, if you could post any ongoing questions or concerns over on our [forum](https://discourse.mozilla.org/c/add-ons), that would be great. 

Since supported versions are back up and running, I'm going to close this thread.
