### ISSUE TITLE
Problème de connexion ?

### ISSUE THREAD

**Issue by Eltarax** [mozilla/addons#1014]
Bonjour,

En essayant d'installer un module complémentaire que je possédais déjà auparavant avant la dernière mise à jour de Firefox (Ad block), je ne parviens pas à installer ce module. Je possède bien une connexion internet mais voilà ce qu'il m'affiche.

Cordialement,
![Sans titre](https://user-images.githubusercontent.com/50269425/57180620-c15ab400-6e8a-11e9-81cb-149a2d453dcf.png)

**Comment by LaughingLove** [comment]
Il y a déjà beaucoup de discussions de ce problème. Voir ce discussion [ici ](https://github.com/mozilla/addons/issues/1013)

**Comment by caitmuenster** [comment]
Merci @LaughingLove!
