### ISSUE TITLE
Cannot download extensions for Firefox

### ISSUE THREAD

**Issue by TheFlashRon** [mozilla/addons#1016]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
When opening Firefox this morning, I find that most of the installed extensions are now disabled because they are no longer compatible. When, for example, replacing Ad Block Plus fails because the download fails.
### What happened?
From the Add-ons Manager, I click on Get More Add-ons and from the following page AD BLOCKERS is selected, then Ad Blocker Ultimate is selected from the list and finally, the +Add to Firefox button is clicked.
### What did you expect to happen?
I expected the add-on to be installed. Instead a red bar appears with Download failed. Please check your connection.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/en-US/firefox/addon/adblocker-ultimate/?src=collection

**Comment by LaughingLove** [comment]
Please see the [pinned post about this issue](https://github.com/mozilla/addons/issues/1013). TLDR Firefox devs are working on it
