### ISSUE TITLE
Firefox upgrade exes out Lastpass, Honey and others with no solutions

### ISSUE THREAD

**Issue by veragalon** [mozilla/addons#1018]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

From one hour to the next, I lost all access to Lastpass, suddenly even using the passwords when I went to their site to get them no longer work (so no access to my runbox.com which is main email...disaster..Nor Honey, and ikely I'll find others that are important to me. No warning. The early morning all worked, this afternon, all is , unh, flubbered...

So I downloaded the earlier version 56, and is still blocked--on their own site. When we click "alterntives", taken to the Firefox download page FOR Last pass, and still doesn't do it. On the 66 version or the 56..I was sent to this page from them as well to notify bugs..why here.

Please get them onto it, and if you can help, thank you kindly. Quite upset.

best GS Islwyn aka veragalon

**Comment by caitmuenster** [comment]
Hi there, this is related to  #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see  https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
