### ISSUE TITLE
Cannot install VTzilla add-on in Firefox 66.02 Android

### ISSUE THREAD

**Issue by onehandclapping** [mozilla/addons#1019]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Tried to install virus total add-on, VTzilla 2.0

### What happened?

Got "This add-on requires a newer version of Firefox (at least version 48.0). You are using Firefox 36.0." 

But actually using 66.02 on Android

### What did you expect to happen?

If add-on is not available for Android it would be better if that were the message.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
