### ISSUE TITLE
Firefox is not allowing ANY addons, even good ones

### ISSUE THREAD

**Issue by jamminjames** [mozilla/addons#1021]
### Describe the problem and steps to reproduce it:
Firefox deleted all my addons, and is not allowing any new ones, even those that are secure. For example, LastPass. 

### What happened?
I always get a "Download failed. Please check your connection." error, but my connection is fine.

### What did you expect to happen?
Should install.

### Anything else we should know?
Yeah, how about testing THOROUGHLY before rolling out new stuff like your new security check for addons? This is enough to drive people to Chrome for good. And why is this taking so long to fix? You must be getting tons of complaints, I've seen them online myself.

**Comment by J0WI** [comment]
This is a duplicate of #1013.
Please refer to https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by l-k22** [comment]
Very strange that the issue was identified yesterday, but has only affected me in the last 5minutes having used FF all day.

**Comment by jamminjames** [comment]
Okay, sorry for the duplication, and thanks for the link.
