### ISSUE TITLE
Add-ons not downloading, connection is fine

### ISSUE THREAD

**Issue by morbicae** [mozilla/addons#1023]
My existing add-ons (AdBlocker and screen colour extensions) was automatically rendered "Unsupported" when my browser updated
So I just went through the basic steps of searching for new add-ons in the search bar, which takes you to the expected app page for add-ons. However, whenever I press the "Add to Firefox" button, an error just keeps coming up saying "Download Failed: Please check connection". There is nothing wrong with my connection. This happens regardless of what add-on I try to get.

Here is screenshot

![Screen Shot 2019-05-05 at 6 10 16 AM](https://user-images.githubusercontent.com/50276270/57184348-b856fa80-6efd-11e9-82d0-ac6eb5896780.png)

This is enormously frustrating, the amount of ads I'm bombarded with is madness. I didn't realise just how much the adblock add-on was doing!

**Comment by caitmuenster** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by morbicae** [comment]
I already removed the "unsupported" add-ons, so I don't think this solution will work :(

**Comment by cup** [comment]
https://github.com/mozilla/addons/issues/1023
https://github.com/mozilla/addons/issues/1025
https://github.com/mozilla/addons-frontend/issues/7972

**Comment by cup** [comment]
as the hotfix requires submitting to an invasion of privacy, and the permanent
fix was only pushed for version 66 and 60, here is a fix for other versions:

https://support.mozilla.org/questions/1258165#answer-1218833

**Comment by wagnerand** [comment]
Please do not use unofficial workarounds from untrusted sources! They can have unintended or untested side-effects or could make things even worse. (Some already have, actually.)
