### ISSUE TITLE
problem with noscript security suite and unlock origin addons

### ISSUE THREAD

**Issue by asl3t** [mozilla/addons#1024]
When using Mozilla Firefox, browser prompted me that the unlock origin and noscript security suite addons were corrupt.  Reinstall failed with error that they could not be installed due to corruption:

Error: The add-on downloaded from addons.mozilla.org could not be installed because it appears to be corrupt.

Highly unlikely both corrupted at same time.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by caitmuenster** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
