### ISSUE TITLE
add on's nto downloading.

### ISSUE THREAD

**Issue by skullkidrae** [mozilla/addons#1025]
### Describe the problem and steps to reproduce it:
firefox has just updated on my macbook and now will not allow me to add any addons. 

### What happened?
error advising download failed when everi try to add an add on 
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
<img width="1440" alt="Screenshot 2019-05-04 at 22 53 42" src="https://user-images.githubusercontent.com/37680079/57185231-8626a800-6ebf-11e9-92ac-8781ff23de73.png">

**Comment by caitmuenster** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by skullkidrae** [comment]
@caitmuenster thanks for the update. to clarafy. this is being resolved. the post states this should be resolved whtin 6 hours however iv had this issue for more than 24 hours with no hotfix being implaimented.

**Comment by caitmuenster** [comment]
Thanks @skullkidrae, I can update that. We do have a more permanent fix in testing right now and will hopefully be deploying soon.

**Comment by skullkidrae** [comment]
ok. thank you for the update :)

**Comment by caitmuenster** [comment]
@skullkidrae just re-read the blog post; once the hotfix is enabled, it can take up to six hours to enable. Sorry about the confusion and thanks for your patience while we get a fix out! 🙏🏼

**Comment by cup** [comment]
https://github.com/mozilla/addons/issues/1023

https://github.com/mozilla/addons/issues/1025
https://github.com/mozilla/addons-frontend/issues/7972

**Comment by cup** [comment]
as the hotfix requires submitting to an invasion of privacy, and the permanent
fix was only pushed for version 66 and 60, here is a fix for other versions:

https://support.mozilla.org/questions/1258165#answer-1218833

**Comment by wagnerand** [comment]
Please do not use unofficial workarounds from untrusted sources! They can have unintended or untested side-effects or could make things even worse. (Some already have, actually.)

**Comment by cup** [comment]
@wagnerand you keep saying that - but you dont have an official fix for version other than 66 and 60.

So what youre saying comes off as disingenuous at best.

**Comment by wagnerand** [comment]
@cup please refrain from spreading unofficial workarounds. They have been causing more damage than help.

**Comment by cup** [comment]
@wagnerand it seems like a wasted exercise having a discussion with someone who hides all my comments.

The simple fact is no official fix is available for version other than 66 and 60, so it seems like your are spreading misinformation or worse actively hiding information that might be useful to these users.

**Comment by willdurand** [comment]
> The simple fact is no official fix is available for version other than 66 and 60, so it seems like your are spreading misinformation or worse actively hiding information that might be useful to these users.

Sorry for the trouble but Mozilla never said no official fix was available. We cannot provide a fix **yet** but that does not mean we will leave users of old versions in a bad situation. 250+ people around the world have been working hard over the last 96h to fix this problem for most of the users.

I am sorry that it takes more time for some users, but providing an unofficial workaround means no one cannot really verify it. What if this workaround gets changed with malicious code? Official fixes can be verified, that's why we insist on not using unofficial workarounds for the moment.
