### ISSUE TITLE
STILL unable to download ANY add-ons!!

### ISSUE THREAD

**Issue by KatjeVoo** [mozilla/addons#1028]
As of 18:20 MDT, it is still impossible to download add-ons of any variety, in spite of the fix that was supposedly rolled out this morning. I read Kev Needham's blog post, and the problem is still not resolved nor is there an update posted since the clarifications were added. I would like to know when this will be done, as I have some security sensitive things to do (read: financial) and I want to be reasonably sure that my browser is secure, beyond the usual common-sense measures.

Thank you.

**Comment by huanghe2015** [comment]
Temporary solution:https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by huanghe2015** [comment]
Dup for #1013
