### ISSUE TITLE
Extensions fail to load

### ISSUE THREAD

**Issue by CZuckerman** [mozilla/addons#1029]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

With FF version 66.0.3 (64-bit), it seems that the vast majority of my extensions are "broken" or "no longer valid". All extensions were from Mozilla.org/extensions and now when I try to reinstall, I get "Download failed. Please check your connection."

![Screenshot 2019-05-04 22 10 29](https://user-images.githubusercontent.com/18473753/57187186-891e9a00-6eb9-11e9-880e-d5fc173a824f.jpg)

Another extension: 1Password for Firefox, is a staple and used on a daily basis, now suddenly it's corrupt, and would not load, not even from the 1Password website.  I'm not using the subscription version, but the desktop app works perfectly. 

![Screenshot 2019-05-04 22 13 48](https://user-images.githubusercontent.com/18473753/57187286-1feb5680-6eba-11e9-8004-fa9ccd9ae1d7.jpg)

I use about 15 extensions on a regular basis, including Evernote Web Clipper, and several others, and they're now gone from this version of FF (66.0.3 (64-bit)).

My mac is a MacBook Pro Retina mid-2014, 2.8GHz Intel Core i7, running OSX Mojave 10.14.4. 16GB RAM, with NVIDIA GeForce GT 750M 2 GB, Intel Iris Pro 1536 MB

### What did you expect to happen?
working extensions!!
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by huanghe2015** [comment]
Dup for #978

**Comment by huanghe2015** [comment]
Temporary solution:https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by caitmuenster** [comment]
Thanks @huanghe2015! Closing this for now; it's best to follow the blog for more updates.
