### ISSUE TITLE
Unable to apply theme

### ISSUE THREAD

**Issue by eterwrd** [mozilla/addons#1030]
### Describe the problem and steps to reproduce it:
I noticed my theme at mozilla waa not being displayed so I tried installing it again but it said something it not being able to display because of unverified signature & when I tried installing other themes I got an error message saying something about the download being corrupt. I reinstalled the browser but when I tried to install a theme I got the same message.
![Screenshot_2019-05-04-21-18-19](https://user-images.githubusercontent.com/50281459/57187412-f7f8f480-6eb3-11e9-9612-3fe8d442d59a.png)

**Comment by caitmuenster** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
