### ISSUE TITLE
Firefox sync will disabled all your plugins

### ISSUE THREAD

**Issue by tonycstech** [mozilla/addons#1031]
#1 Firefox was not updated since April 10
#2 Suddenly out of nowhere both my computers started to push ads.
Then i realized add-ons were disabled.
#3 This did not happen when firefox restarted, it happened when it was running.

I opened my other laptop that was not used for few days. It had same firefox version installed BUT sync needed to  reconnect.
Once i proceeded with sync and verified it blah blah blah, instantly all addons were removed.

This is not a bug, i think this is something else because it was working fine until i reconnected the sync account.

Solution:
Delete all firefox files from appdata folders, local and roaming.
This will start new profile.
Then you can sync your data and all will work again.

**Comment by wagnerand** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox
