### ISSUE TITLE
Download failed. Please check your connection.

### ISSUE THREAD

**Issue by beefydog** [mozilla/addons#1032]
Any and all addins/extensions to Firefox Quantum version 66
 result in the error message:
Download failed. Please check your connection.
After all our major security plugins have been disabled by Firefox (leaving us vulnerable - the update is making the browser MORE vulnerable due to it disabling our security plug-ins!), I tried numerous times to install replacements. Nothing works. We're uninstalling FireFox as a result as it is now a security threat (ad tracking leads to phishing - so if we can't block ads, then this browser is vulnerable)

**Comment by wagnerand** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox
