### ISSUE TITLE
Ad block 

### ISSUE THREAD

**Issue by SubAtomicGenius** [mozilla/addons#1035]
Please fix your add ons. 

![Screenshot_20190505-075937_Firefox](https://user-images.githubusercontent.com/50294817/57194374-e00b8a00-6f20-11e9-85a0-4c838fe5689b.jpg)
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?

Unable to add ad block. 

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox
