### ISSUE TITLE
can not connect to install add ons. old add ons broken.

### ISSUE THREAD

**Issue by Cheesecakeone** [mozilla/addons#1037]
### Describe the problem and steps to reproduce it:
As of today (05.05.2019) in version  66.0.3, none of my add ons work anymore. firefox says 'Only extensions built using WebExtensions APIs will work'. 
i am not aware of a firefox update, though it might have happened without me noticing.
i can also not reinstall the add ons anymore. everytime i try, firefox says 'download failed, please check your connection'. i am using NordVPN, and have tried to download with or without active VPN connection. neither works. 
i tried this fix https://askubuntu.com/questions/1140604/firefox-66-0-3-64-bit-addons-broken
it didnt work, even though the hotfix is showing up in studies. 
i tried reseting firefox, which also didnt work. 

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by typo3ua** [comment]
I have the same problem

**Comment by wagnerand** [comment]
We have fixed the issue. Please see https://github.com/mozilla/addons/issues/1013.

**Comment by typo3ua** [comment]
I did it. Thanks!
