### ISSUE TITLE
Check certificate at install time only

### ISSUE THREAD

**Issue by cup** [mozilla/addons#1038]
addon certificates are currently checked everyday instead of just at install
time. this fact highly exacerbated the recent addon issue:

https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

if addons were only checked at install time, then people would have only had
issues with installing new addons, and not what actually happened which was
most of the userbase losing all addons.

**Comment by cup** [comment]
https://github.com/mozilla/addons/issues/1013

**Comment by wagnerand** [comment]
This is not an addons-server issue. I suggest you file an issue on bugzilla.mozilla.org. Thank you.
