### ISSUE TITLE
corrupt addons

### ISSUE THREAD

**Issue by faisljml2018** [mozilla/addons#1039]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox
