### ISSUE TITLE
corrupt addons

### ISSUE THREAD

**Issue by faisljml2018** [mozilla/addons#1040]
![Screenshot_20190506-122532_Firefox](https://user-images.githubusercontent.com/50315132/57211610-503a0e80-6ffa-11e9-9885-4a9a12b8f99c.jpg)
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox
