### ISSUE TITLE
Availability of signingca1.addons.mozilla.org as e.g. a .pem file from Mozilla

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons#1042]
Re: https://github.com/mozilla/addons/issues/1013#issuecomment-489588781 the `.pem` file offered at the VelvetBug site is very useful. The end result has (for me) an SHA-256 fingerprint that matches the fingerprint at https://bugzilla.mozilla.org/show_bug.cgi?id=1549061#c21

For users (or systems administrators) who, for any reason, can not quickly gain a suitable version of Firefox, or Firefox ESR, please: 

- will Mozilla offer a comparable file?

**Comment by grahamperrin** [comment]
https://github.com/mozilla/addons/issues/1013#issuecomment-489634740 noted with thanks. I'll begin by seeking an answer in Discourse.

**Comment by grahamperrin** [comment]
Found – @smayer97 please join me, in this topic: 

- [Add-ons not working due to certificate expiration - FireFox ESR 52.9.0 (32-bit) and older - Add-ons / Add-on Support - Mozilla Discourse](https://discourse.mozilla.org/t/thread-add-ons-not-working-due-to-certificate-expiration-firefox-esr-52-9-0-32-bit-and-older/39845?u=grahamperrin)

@estebanz01 whilst the topic is not a perfect fit for cases such as yours – 

> Just wondering if a fix for firefox developer version has been released. I'm on version `67.0b16 (64-bit)`.

– it's reasonable to assume the topic will eventually gain an answer to this issue; availability of a certificate file _from Mozilla_. 

----

@caitmuenster at your leisure, please lock this one. 

Thanks everyone.

**Comment by caitmuenster** [comment]
Thanks so much for helping triage questions, @grahamperrin! Locking this conversation now.
