### ISSUE TITLE
I'm trying to add Adblock Plus but it fails with message "Download failed. Please check your connection." My connection is fine, I watch videostream in another tab. So I try to add another anti-ad addon and it fails with the same error. If you decided to cut the anti-ad features, please stop lying that the problem is at the users side.

### ISSUE THREAD

**Issue by tumbaloro5** [mozilla/addons#1043]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
There was a problem over the weekend that caused most add-ons to be disabled. You can find the details here: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

This should be fixed by updating your Firefox to the latest version.

**Comment by tumbaloro5** [comment]
Thank you for the fast reaction!
Updating Firefox was the first thing I tried when noticing the problem a couple of days ago.
Then there was no further update.
Now it's available. And fixed the problem.
Thank You.
