### ISSUE TITLE
Update EULA tooltip in Developer Hub

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons#1044]
### Describe the problem and steps to reproduce it:

- Go to the License & Authors page of your extension
- Read the EULA tooltip
- Add and enable a EULA

### What happened?

No prompt to accept the EULA is shown when installing the extension.

### What did you expect to happen?

Either the tooltip shouldn't mention that this prompts users about the EULA before installation or the user should be prompted with the EULA before installation.

**Comment by jvillalobos** [comment]
Current text:

> Users will be required to accept the following End-User License Agreement (EULA) prior to installing your add-on. The presence of a EULA significantly affects the number of downloads an add-on receives. Please note that a EULA is not the same as a code license, such as the GPL or MPL.It is only relevant for listed add-ons.

Proposed:

> Please note that a EULA is not the same as a code license, such as the GPL or MPL. It is only relevant for listed add-ons.

/cc @caitmuenster

**Comment by caitmuenster** [comment]
LGTM!

**Comment by jvillalobos** [comment]
Mentor: @eviljeff

**Comment by assignment6** [comment]
Can I work on this?

**Comment by eviljeff** [comment]
@assignment6 sure, go ahead

**Comment by assignment6** [comment]
Thanks.  Now come the questions :-)  
1) Should I be asking questions here or IRC?

**Comment by caitmuenster** [comment]
Hey @assignment6, sorry for the late reply! You can go ahead and ask questions here. If you can be as specific as possible, that would be great. 

Also because @eviljeff will be on PTO for a bit, we are updating the mentor to @EnTeQuAk.

**Comment by rbrishabh** [comment]
I would like to take this up if it's still relevant?

**Comment by caitmuenster** [comment]
Hi @rbrishabh, go for it!

**Comment by rbrishabh** [comment]
Hi! @EnTeQuAk and @caitmuenster !

From what I am able to understand till now, this is where the tool-tip text needs to be updated --
[addons-server/blob/master/locale/en_US/LC_MESSAGES/django.po](https://github.com/mozilla/addons-server/blob/master/locale/en_US/LC_MESSAGES/django.po)

Did I get this right?

Also this tool-tip exists in 86 other files, for other languages, will I need to update them all [I can use google translate for that].

Thanks!

**Comment by eviljeff** [comment]
@rbrishabh no, you need to edit the text in the template (.html file in jinja2 format)

**Comment by rbrishabh** [comment]
> 
> 
> @rbrishabh no, you need to edit the text in the template (.html file in jinja2 format)

Which .html file are you referring to?

Thanks!

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
![image](https://user-images.githubusercontent.com/31961530/62208168-c0102900-b39e-11e9-870c-ef34d5780802.png)
