### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by viclafouch** [mozilla/addons#1047]
Everything is working on local. No error, nothing.. But errors during the submission :/

Please attach a copy of your add-on, and fill in the following information:
[PE-Center-1557262496082-firefox.zip](https://github.com/mozilla/addons/files/3154574/PE-Center-1557262496082-firefox.zip)

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
**During the submission of a new add-on**

![image](https://user-images.githubusercontent.com/23353836/57333386-fb42e900-711c-11e9-9a4c-ba1dbc1d0860.png)

* Whether your add-on is listed or unlisted.
**Listed**

* The URL where you submitted the add-on.
**[https://addons.mozilla.org/fr/developers/addon/submit/upload-listed](https://addons.mozilla.org/fr/developers/addon/submit/upload-listed)**

* The approximate time you submitted the add-on, with timezone.
**Tue May 07 2019 23:11:53 GMT+0200 (heure d’été d’Europe centrale)**

**Comment by viclafouch** [comment]
I don't know why, but I'm using a library to zip a folder ([https://www.npmjs.com/package/adm-zip](https://www.npmjs.com/package/adm-zip)), and the manifest.json appears to be corrupted on Firefox. 

It's working only when I zip manually a folder.... very strange.. 

Can be closed.

**Comment by wagnerand** [comment]
Thank you for the update!
