### ISSUE TITLE
Cannot submit details for new extension

### ISSUE THREAD

**Issue by LinusU** [mozilla/addons#1048]
### Describe the problem

I’m trying to submit a new extension to AMO, but am hitting a brick wall when trying to save the extension details. After filling everything out and pressing “Submit Version”, I’m simply taken back to the same page, with my stuff still filled in, without any error message.

I’ve tried looking at each and every field and I cannot find anything wrong… I’ve also tried multiple web browsers but that doesn’t seem to change anything at all…

This is the “Submit a New Add-on” > “Describe Add-on” page. Accessible after I’ve uploaded my extension.

####  ...and steps to reproduce it:

1. Upload an extension
2. Fill in required details for publications
3. Click submit

### What happened?

I get taken back to the same page, without any error message.

### What did you expect to happen?

I expected the required details to be saved, and the extension to be submitted.

### Anything else we should know?

I first reported this on the AMO forums: https://discourse.mozilla.org/t/cannot-submit-details-for-new-extension/40028

I cannot access any other settings page for the extension then this page. These are my only options:

![3997447d392391993a90284a332174c795968611](https://user-images.githubusercontent.com/189580/57373122-780eab00-718f-11e9-9e28-249813531660.png)

**Comment by jvillalobos** [comment]
Can you give us the ID of the extension, from the manifest?

**Comment by LinusU** [comment]
Is this the ID that you mean? ☺️ 

```json
   "applications" : {
      "gecko" : {
         "id" : "{7096a0a2-9934-4fc0-b7ce-9418ad5e9d99}"
      }
   },
```

Thanks for looking into this ❤️

**Comment by jvillalobos** [comment]
I can confirm that it is silently failing on the last step. @LinusU, if you could attach or link to the file you uploaded, that could help us identify the problem.

**Comment by LinusU** [comment]
Here you go, thanks for looking into it 👍 

[eego-19.5.7.1557.zip](https://github.com/mozilla/addons/files/3188270/eego-19.5.7.1557.zip)

**Comment by diox** [comment]
@LinusU can you retry and give the full URL that is displayed in your browser when you're submitting the last step and failing ?

**Comment by LinusU** [comment]
@diox https://addons.mozilla.org/en-GB/developers/addon/eego/submit/details

**Comment by diox** [comment]
Thanks. Sorry, I can't quite figure out what's wrong yet. I suspected something with the locale being `en-GB`, or something preventing us from considering your add-on as compatible with Firefox, but that doesn't seem to be the case...

Maybe worth trying disabling the version, deleting the add-on, re-submitting it with the same account (it should let you use the same ID)

**Comment by LinusU** [comment]
> `en-GB`

Hmm, do you know why this is set as the locale? Is it simply because I'm browsing from the UK?

**Comment by diox** [comment]
No default locale was set in your manifest and it looks like your browser is configured to prefer it, so that ended up in the submission URL, and because we didn't have a better source we used that.

**Comment by muffinresearch** [comment]
@LinusU were you able to resolve the issue through resubmission?

**Comment by LinusU** [comment]
> were you able to resolve the issue through resubmission?

Nope, and at this point I've put the Firefox extension on hold. Might revisit it in the future!

Thanks to everyone that tried to help ☺️
