### ISSUE TITLE
missing ad-on

### ISSUE THREAD

**Issue by Hashimx10** [mozilla/addons#1051]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Hashimx10** [comment]
where the fuck my ad-ons are gone? i have not updated firefox or removed any of them! there were at least more than ten of them and now there are only two left.they always restored after i synchronize(on new device or after reinstalling windows) with my firefox account but this time there are only two of my ad-ons left, why? How can i get back my collectoin of ad-ons. those were my best chosen and reliable and now i don't even remember the names of them, i thought i can rely on cloud service but you just disgusted me. i hate you mozila firefox.

**Comment by willdurand** [comment]
Hey, let's discuss your problems in #1052, no need to create multiple issues.
