### ISSUE TITLE
where are my ad-ons gone from my online firefox account?

### ISSUE THREAD

**Issue by Hashimx10** [mozilla/addons#1052]
where my ad-ons are gone? i have not updated firefox or removed any of them! there were at least more than ten of them and now there are only two left.they always restored after i synchronize(on new device or after reinstalling windows) with my firefox account but this time there are only two of my ad-ons left, why? How can i get back my all of ad-ons. those were my best chosen and reliable and now i don't even remember the names of them, i thought i can rely on cloud service but you just disgusted me. i hate you mozila firefox.

**Comment by willdurand** [comment]
> where the fuck my ad-ons are gone? i have not updated firefox or removed any of them!

Hi, sorry to hear that. Could you tell me which Firefox version you're using? And on which operating system?


> How can i get back my collectoin of ad-ons.

I am not sure to follow this part of your message. Do you mean "collection" as AMO collections, i.e. collections created on addons.mozilla.org? Or do you refer to "collection" of add-ons as the list of add-ons you normally use in Firefox?

**Comment by Hashimx10** [comment]
> 
> 
> > where the fuck my ad-ons are gone? i have not updated firefox or removed any of them!
> 
> Hi, sorry to hear that. Could you tell me which Firefox version you're using? And on which operating system?
> 
> > How can i get back my collectoin of ad-ons.
> 
> I am not sure to follow this part of your message. Do you mean "collection" as AMO collections, i.e. collections created on addons.mozilla.org? Or do you refer to "collection" of add-ons as the list of add-ons you normally use in Firefox?

FireFox version 66.0.2 eme free and windows 10 enterprise 1607
i was just normally using them, and they were automatically restored after i login with my firefox account, but this time there were only two restored.
there was one unusual thing, just try to understand the situation first:
on one normal day when i when i just opened my firefox it was showing that all of my ad-ons(expect two) are not supported anymore and it was giving me the option to find replacement, i was shocked because nothing was upgraded or downgraded then how it could be possible. then i have found that even my windows os was not working smoothly and some other things too, so i have just reinstalled the windows(after formatting C drive) and installing all stuff, when i have login with firefox account, bookmarks and history is restored but only two ad-ons are restored, how it can be possible? almost 10 ad-ons can't get unsupported at once, right?
i they were corrupted in my pc then they were suppose to all ok in cloud account right? (or whatever you name that online service)
now i have manually downloaded new ad-ons which i remember or what i need, and everything looks normal (almost) right? but that was really really bad and made me very sad and confused.

**Comment by Hashimx10** [comment]
edited my first comment just to remove bad language.

**Comment by diox** [comment]
@Hashimx10 sorry about that, this is a bug with Firefox 66.0.x that was solved with Firefox 66.0.4 (and then 66.0.5). There is an [incident summary posted on the add-ons blog](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/), but the short answer is that you should update your Firefox to restore your add-ons.

**Comment by Hashimx10** [comment]
> 
> 
> @Hashimx10 sorry about that, this is a bug with Firefox 66.0.x that was solved with Firefox 66.0.4 (and then 66.0.5). There is an [incident summary posted on the add-ons blog](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/), but the short answer is that you should update your Firefox to restore your add-ons.

i have installed 66.0.5 but it was not working for me, but well, i have manually downloaded the new tools i needed.
and knew one thing that my old method of manually making backup of firefox(making backup of user profile folder) was much better and never let me down but only when old ad-ons get unsupported by newer version of firefox.
