### ISSUE TITLE
evernote webclipper download fail

### ISSUE THREAD

**Issue by romolabucks** [mozilla/addons#1053]
Evernote webclipper download

Download fails. Told to check my connection.

It should have downloaded.

People have been reporting similar bugs for days now!

![image](https://user-images.githubusercontent.com/50568668/57663556-0ae39580-7627-11e9-8409-16eaf9f7d911.png)

**Comment by diox** [comment]
Hi,

What version of Firefox are you using ? This should have been fixed in the latest versions for 66.0.x (66.0.5) and 60.x.y (60.6.3esr).

**Comment by romolabucks** [comment]
I was using: 60.1.0esr (32-bit).
I had to manually update to 66.0.5 (64-bit).
That solved the problem.
Thank you,
Romola

Romola Bucks
+61 (0)407 140031
romolabucks@hotmail.com


________________________________

**Comment by EnTeQuAk** [comment]
Thanks for your update!
