### ISSUE TITLE
play background fix add on Doesn't work anymore

### ISSUE THREAD

**Issue by ymega** [mozilla/addons#1054]
The add on stopped working i tried to uninstall and installit again and while downloading it again it tells me the file is corrupted and cannot be installed
![Screenshot_20190515-143700](https://user-images.githubusercontent.com/21367332/57776136-fda9d200-771e-11e9-82f6-0bee1fcf334d.png)
![Screenshot_20190515-143712](https://user-images.githubusercontent.com/21367332/57776158-0a2e2a80-771f-11e9-9799-c87aed9d65d0.png)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
Please read this blog post for details about the problem and how to solve it: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
