### ISSUE TITLE
Support adding opengraph/social card images on AMO

### ISSUE THREAD

**Issue by rugk** [mozilla/addons#1055]
GitHub now supports adding OpenGraph/Twitter/social card images to GitHub repos:

![](https://discourse-paas-production-content.s3.dualstack.us-east-1.amazonaws.com/original/3X/6/3/63e7a925ef2eca527bd33386bcc7e3feaecdc21e.jpeg)

It would be great, if you could support it, too! :smiley: 

Also opened thread on Mozilla Discourse about it: https://discourse.mozilla.org/t/allow-adding-opengraph-twitter-social-card-images-to-add-on-entries-on-amo/40625?u=rugkx

**Comment by willdurand** [comment]
If I remember correctly, this is already supported. The first preview image/screenshot should be used as a social image.

**Comment by rugk** [comment]
Okay, but I may want to set it separately, don't I?

I mean, is it really so good to have such an image as the first image in your "screenshots" (well… it's no screenshot)?

**Comment by jvillalobos** [comment]
This issue and particularly this comment explain where we are with this: https://github.com/mozilla/addons-frontend/issues/3969#issuecomment-429039560

We may support selecting an image in the future, but our priorities changed so I don't know when that may be.

**Comment by rugk** [comment]
So I just checked. [Here e.g.](https://twitter.com/rugkme/status/1130751562681331712) it does use the first image yes, but not in the usual "social card" width style:
![image](https://user-images.githubusercontent.com/11966684/58128157-42e66c00-7c17-11e9-9fc3-34dd424df03c.png)

I.e., it's more text than image. (don't know how that thing is called, but it's like any link on Twitter)

**Comment by rugk** [comment]
Is this expected or does my image just need the correct sizes?

**Comment by rugk** [comment]
Contrast it to this Twitter card via GitHub e.g.:
![image](https://user-images.githubusercontent.com/11966684/58128603-53e3ad00-7c18-11e9-8898-24e98762b544.png)

**Comment by willdurand** [comment]
@rugk there is no guarantee that the social card will be displayed with a large image unfortunately, this is up to the website more or less. Usually, it's because the image dimensions don't match their expectations.

**Comment by rugk** [comment]
I've now added the same image to AMO, and no, it still is not shown correctly:

![image](https://user-images.githubusercontent.com/11966684/58204932-a89d2b80-7cdd-11e9-8921-c50da5cddee3.png)

Looking in the source code I can see differences.

AMO only has this meta tag:
```html
<meta data-react-helmet="true" property="og:image" content="https://addons.cdn.mozilla.net/user-media/previews/full/219/219700.png?modified=1558554792"/>
```

(only followed by description things)

GitHub has these:

```html
<meta name="twitter:image:src" content="https://repository-images.githubusercontent.com/175012347/6bd95680-73f8-11e9-984d-ca4722e668ea" /><meta name="twitter:site" content="@github" /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:title" content="rugk/awesome-emoji-picker" /><meta name="twitter:description" content="Add-on/WebExtension that provides a modern emoji picker that you can use to find and copy/insert emoji into the active web page. - rugk/awesome-emoji-picker" />
<meta property="og:image" content="https://repository-images.githubusercontent.com/175012347/6bd95680-73f8-11e9-984d-ca4722e668ea" /><meta property="og:site_name" content="GitHub" /><meta property="og:type" content="object" /><meta property="og:title" content="rugk/awesome-emoji-picker" /><meta property="og:url" content="https://github.com/rugk/awesome-emoji-picker" /><meta property="og:description" content="Add-on/WebExtension that provides a modern emoji picker that you can use to find and copy/insert emoji into the active web page. - rugk/awesome-emoji-picker" />
```

So possibly, maybe **twitter:image:src** is missing?

**Comment by willdurand** [comment]
Correct, we're not exposing the Twitter `meta` tags.

**Comment by rugk** [comment]
So, reopen this issue to fix this?

**Comment by willdurand** [comment]
@rugk could you open an issue in https://github.com/mozilla/addons-frontend/issues about supporting Twitter cards?

**Comment by rugk** [comment]
Done: https://github.com/mozilla/addons-frontend/issues/8066
