### ISSUE TITLE
User unable to install Video Background Play Fix on Fennec 66.0.5

### ISSUE THREAD

**Issue by wisniewskit** [mozilla/addons#1056]
A user on [Reddit is reporting](https://old.reddit.com/r/firefox/comments/br7d3r/great/) that despite running Fennec 66.0.5, they are being told that Video Background Play Fix specifically cannot be installed because it is corrupt, though the add-on is installing fine for me on my own phone (it was suggested to me on IRC to open a support request here regardless).

**Comment by jvillalobos** [comment]
Is there a way to get console output on Android? Unfortunately, that error message can appear on a number of different circumstances (like the cert error) so it's not clear what the problem is.

**Comment by wisniewskit** [comment]
The user has just reported that the problem went away for them with the Firefox 67 update, so I'll close this issue.
