### ISSUE TITLE
Google Recaptcha Issue

### ISSUE THREAD

**Issue by checho221** [mozilla/addons#1057]
One working version of my addon was asigned with url
moz-extension://b2eff48d-0298-4cf9-8f55-a8f3d183b152

google recaptcha accept it as allowed domain to use recaptcha because it starts with letter "b2eff48d"

but the next version was assigned with url 
moz-extension://4bd3af7e-e5ca-4eda-93c9-87a23adf76bd
wich starts with a number "4bd3af7e" and google recaptcha admin console does not accepted it

Actually i am submiting many versions until it is assigned with url starting with a letter

**Comment by carlosjeurissen** [comment]
Unlike extensions in chrome, the origin of a firefox addon (moz-extension://{extensionUUID}) is not constant. The reason behind this is security. One of the reasons behind this is the risk of websites being able to detect if your extension is installed.

You could either embed one of your own domains within the extension using an iframe, and implement the recaptcha on that page. You can communicate the results using PostMessage. See:
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

Alternatively, you could whitelist moz-extension://*. Tho this may not be accepted by the recaptcha admin console.

**Comment by muffinresearch** [comment]
This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services. If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
