### ISSUE TITLE
cannot install unsigned addons in firefox 67 unbranded

### ISSUE THREAD

**Issue by AsocialSurvival** [mozilla/addons#1058]
### Describe the problem and steps to reproduce it:
You told that we can use unbranded version to install unsigned addons. So I used one addon, remove it's manifest folder via winrar and tried drag and dropping it into addons window, and it says it is corrupted. I tried this with multiple addons.

### What happened?
I got disappointed. Changing any file, removing or not removing manifest folder, regardless I get information that addon is corrupted, although original one is not.

### What did you expect to happen?
I expect it to install as it succeded in developer edition once.

### Anything else we should know?
downloaded windows 64bit unbranded from here: https://wiki.mozilla.org/Add-ons/Extension_Signing

**Comment by diox** [comment]
Hi,

2 things to keep in mind to test this:
- First, unbranded builds can change the `xpinstall.signatures.required` pref, but the default is still `true`. You need to change it to false in `about:config` to allow installing unsigned add-ons
- Second, removing the `META-INF` folder that contains the signature might break some add-ons that have no id in their `manifest.json`. [Developers are encouraged to set the id](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID#When_do_you_need_an_add-on_ID) but not all do, and in that case Firefox needs *something* to guess the id from, and it uses the signature. This is something we intend to [fix by modifying the `manifest.json` and inserting the id if it's missing](https://github.com/mozilla/addons-server/issues/11559), you can follow the progress of this in that issue.

In any case, the Browser Console (not the Web Console) will contain information explaining why this happened (it's likely one of the two scenarios above). You can find it from the Web Developer menu.

**Comment by AsocialSurvival** [comment]
I did that in about config. Will try the other one. It displays:
1559425418487	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
1559425418588	addons.xpi	WARN	Invalid XPI: Error: Cannot find id for addon D:\file\group\xpi\old\(modified)\opensubtitles_pro-1.0.7-fx.xpi(resource://gre/modules/addons/XPIInstall.jsm:1296:19) JS Stack trace: loadManifest@XPIInstall.jsm:1296:19

**Comment by diox** [comment]
That confirms the second point I was talking about. Unsigned add-ons that have been developed with unbranded builds in mind, with an `id` explicitly set in their `manifest.json`, will work. Otherwise https://github.com/mozilla/addons-server/issues/11559 will fix that.
