### ISSUE TITLE
sorting of add-ons is incorrect

### ISSUE THREAD

**Issue by atomGit** [mozilla/addons#1059]
### Describe the problem and steps to reproduce it:
sort extensions by recently updated ...
https://addons.mozilla.org/en-US/firefox/search/?sort=updated&type=extension

### What happened?
extensions that were NOT recently updated may be near/at the top of the list

### What did you expect to happen?
extensions should be sorted by the date they were updated, descending order

### Anything else we should know?
for example ... 3-Jul, the add-on [HTTPZ](https://github.com/claustromaniac/httpz) is 2nd in the list with version 0.7.2, yet v0.7.2 was released 13 days ago - i'm seeing this quite often with add-ons

**Comment by diox** [comment]
Hi,

Technically, the sorting is working correctly, it's just that we have a long standing issue that causes unlisted versions to be considered when determining the last updated date for an add-on. That has been reported already as https://github.com/mozilla/addons-server/issues/6929 so I'm going to close this, thanks.
