### ISSUE TITLE
Unable to install new Waterfox theme

### ISSUE THREAD

**Issue by MonsterMistress** [mozilla/addons#1060]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by MonsterMistress** [comment]
I logged into Firefox Add-ons to change my Waterfox theme background.  I selected a new one I was interested in, but when I clicked on the Install Theme button, it put a red banner up saying "Download failed.  Please check your connection." (see screenshot below)  It did this same thing for every theme I attempted to select.  I expected to be able to select new theme backgrounds and change what I am using in Waterfox to something different.  And there is noting at all wrong with my connection - I am not experiencing any kind of connection difficulty with any other site; nor am I experiencing any issue whatsoever with my internet at all.  I'd just like to be able to change my Waterfox theme background please..........

![Ñíèìîê 1](https://user-images.githubusercontent.com/51465931/59074279-54bf4480-8890-11e9-869c-b051d5ac9552.png)

**Comment by diox** [comment]
Hi,

This is a generic error message, not necessarily a problem with your connection. If you open the Browser Console you'll see more information. 

In any case, it's working with the latest supported versions of Firefox. Try updating Waterfox. If that doesn't work, take that up to Waterfox devs.
