### ISSUE TITLE
Extension Download Link Broken

### ISSUE THREAD

**Issue by AustinGMartin** [mozilla/addons#1063]
### Describe the problem and steps to reproduce it:
When I attempt to install the Scopus Document Download Manager from an anonymous session, I am put on this page: https://addons.mozilla.org/firefox/downloads/file/1669023/scopus_document_download
If I log in to my add-on developer account, the download will execute, but an old version will be installed. (latest is 3.13, 3.11 is being installed)

### What happened?
No installation happened until I logged in. Then an old version was installed.

### What did you expect to happen?
The latest version of the addon is installed after clicking the get extension link, without having to sign in as a developer.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Intended workflow (happens when logged in as addon developer): 
![image](https://user-images.githubusercontent.com/31514734/59946695-4d27a000-9439-11e9-9812-77410e669afd.png)
![image](https://user-images.githubusercontent.com/31514734/59946714-5add2580-9439-11e9-9247-cf904378f7f4.png)

Actual workflow: 
![image](https://user-images.githubusercontent.com/31514734/59946827-a4c60b80-9439-11e9-9654-ac99b86de5d1.png)
![image](https://user-images.githubusercontent.com/31514734/59946847-b7404500-9439-11e9-8627-cd261458507c.png)
![image](https://user-images.githubusercontent.com/31514734/59947181-8ca2bc00-943a-11e9-81ac-974ed5c7e786.png)
![image](https://user-images.githubusercontent.com/31514734/59947215-9f1cf580-943a-11e9-90b8-78549c234169.png)

Is this due to the fact that a request for further information is active on the addon? 
It may be an unintended bug happening?
I can still add the correct version of the addon with this page: https://addons.mozilla.org/en-US/firefox/addon/scopus-document-download/

**Comment by wagnerand** [comment]
It seems you are the developer of that add-on.

The reason you can't install this in a private browsing window is because you are linking to file which is no longer public. This also means, no one can install your add-on from that website.

What you should be linking to is https://addons.mozilla.org/firefox/downloads/latest/scopus-document-download/

**Comment by TheArKaID** [comment]
So...Scopus Document Download Manager is no longer available? And there's neither a replacement nor manual download on the Scopus page? @AustinGMartin 

![image](https://github.com/mozilla/addons/assets/35050722/df751280-ed40-4afd-8fb8-2221c9a26ba5)

**Comment by diox** [comment]
That's up to Scopus developers to fix.

**Comment by AustinGMartin** [comment]
@TheArKaID I am no longer working in this role, if you are experiencing issues, maybe attempt to create a new issue or contact the Scopus team through the contact information available on their platform.
