### ISSUE TITLE
URL address in zone .one does not turn into a clickable link

### ISSUE THREAD

**Issue by cawa-93** [mozilla/addons#1064]
### Describe the problem and steps to reproduce it:
In the description of my add-on ([link](https://addons.mozilla.org/uk/firefox/addon/play-shikimori/#details)) two domains are used in different zones:
shikimori.org и shikimori.one.

### What happened?
The shikimori.org is converted to a clickable link. But the shikimori.one is not

![image](https://user-images.githubusercontent.com/1662812/60095924-62157380-9758-11e9-81e2-00844a6656b0.png)

**Comment by diox** [comment]
Hi,

This looks like a limitation of the default regular expression we use (which comes from [bleach](https://bleach.readthedocs.io/en/latest/linkify.html#using-bleach-linkifier-linkifyfilter)). Given that it's only a domain with a tld that could be part of a regular sentence that's not surprising and unlikely that we'll fix that, it's too dangerous, we risk adding a link where there isn't one.

I suggest you add the link HTML yourself, adding `<a href="http://shikimori.one/">shikimori.one</a>` to the summary yourself. It will get cleaned up when you save it, removing any extra attributes etc, but it should keep the link.
