### ISSUE TITLE
'Last updated' in add-on page can show date when add-on was self published.

### ISSUE THREAD

**Issue by keithx2** [mozilla/addons#1066]
It would seem to be more accurate if 'Last updated' only applied to the last listed add-on version.

For example, look at the [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) page.

Under 'More information', the version is 1.20.0 and 'Last updated' is Jun 23.

However, under the version history, 1.20.0 was released on Jun 15.

**Comment by diox** [comment]
Hi,

This was already reported as https://github.com/mozilla/addons-server/issues/6929 so I'm closing as duplicate. It's not necessarily trivial since we may want to display the date for purely unlisted add-ons, but we'll figure something out.
