### ISSUE TITLE
page title uses wrong locale

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/addons#1068]
I run the Tagalog version of Firefox (`tl`) and live in Canada. AMO is showing me page title such as `uBlock Origin – Get this Extension for 🦊 Firefox (en-CA)`, presumably because it's geolocating to determine locale?

I'm not sure if this is a bug or if it's intended.

**Comment by willdurand** [comment]
I don't think we support `tl` as a language on AMO. We use the `accept-language` header sent by the browser to determine the locale, unless the locale is already part of the URL you use to navigate to AMO. In your case, I think there is `en-CA` in the URL too.

**Comment by mozbhearsum** [comment]
Yeah, it's in the URL as well. I just looked at my request headers and indeed, en-CA is there: `Accept-Language: tl,en-CA;q=0.5`

Sorry for the noise!
