### ISSUE TITLE
Problem with page @ https://addons.mozilla.org/en-US/developers/addon/submit/agreement

### ISSUE THREAD

**Issue by Hugh-Jassole** [mozilla/addons#1069]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Hugh-Jassole** [comment]
When I attempt to upload a THEME the page tells me I am in error, even though the "error" in question is not on the page.

The section of the page that states: This field is required...
![Broken Page](https://user-images.githubusercontent.com/51089322/60754857-55ddb180-9fb5-11e9-9ddd-02c4096aa5ac.jpg)

...does not exist on the page?!?!?!

**Comment by EnTeQuAk** [comment]
On this page we are using [recaptcha](https://www.google.com/recaptcha/) to help us fight against malicious and spammy users.

Unfortunately it seems you have either blocked it or disabled JavaScript which throws the error you mentioned.

Once you unblock recaptcha you will see the check and should be able to continue.

I'm going to close this for now as it's expected, please feel free to reply / re-open at any time if your problem does not go away.

**Comment by Hugh-Jassole** [comment]
You assume I am computer savvy and know how to complete this task. Thanks for the info though. Sorry so late just got home from the hospital.
