### ISSUE TITLE
Should addons.mozilla.org continue to provide Collections for users?

### ISSUE THREAD

**Issue by designakt** [mozilla/addons#107]
[Collections](https://addons.mozilla.org/firefox/collections/) currently are groups of related add-ons that anyone can create and share. They are pictured as a tool for community to help users find the right add-ons for them. Through that they should help engage users with add-ons. Either by helping them find and install the right add-on, or by creating their own groups and sharing their knowledge with others.

Our initial data pointed towards a very limited usage of that feature which lead us to remove access to it from the add-ons details pages with the style refresh ([issue 2013](https://github.com/mozilla/addons-server/issues/2013)).
Benefit of this removal is limiting the actions a user can take on an add-on and thus simplifying and focusing the page. I also consider it as a first step towards evaluating if it is worth maintaining that feature in the next version of addons.mozilla.org
The removal of that link also resulted in a vocal group expressing the advantages of collections for the add-on ecosystem. Those are described as collections being important to the people who use them, collections help keep people who create them engaged, collections being useful in discovering relevant/related/similar add-ons.

**We will use this issue to collect arguments and especially data to decide if we should continue providing Collections for users?**

_(this issue is focusing on Collections and not considering Favorites, that should be discussed in a different issue, as both features sever different use cases - public / personal)_

**Comment by designakt** [comment]
To understand the relevancy of that feature for the add-on ecosystem, I think it helps to understand and answer the following questions:

How many people profit from the collections created by community?
    - through exploration/inspiration
    - by finding alternatives
    - by finding good add-ons 

How many popular collection creators are there?
    - has a collection with more than ?? visitors per month
    - has a collection with ?? referrals to an add-on per month

_In terms of data this would mean:_

**What percent of users installing an add-on discover it via a (non-mozilla) collection?**
    - installs from collection page, and
    - installs from details page found via a collection

**How many % of our visitors visit a collection?**

**What % of our visitors visit the most visited collections?**

**How many collections generate installs? And how many?**

**Comment by designakt** [comment]
A first idea towards answering those questions with data I got from @jvillalobos :

When looking at add-on stats, AdBlock Plus is very useful because it's the most used add-on and their stats are public. You can see the download breakdown here:
https://addons.mozilla.org/addon/adblock-plus/statistics/downloads/sources/?last=30
The top download sources are:
Add-ons Manager - 94,463 (downloads in a day)
Detail page - 37,201
Add-ons Manager Featured - 9,631

Collections are way down the list with 264.

I suspect themes would have more activity related to collections, but we don't keep the same stats for them. Google Analytics should be able to help filling that gap.

-

**[Averaging the downloads for the last 2 weeks](https://docs.google.com/spreadsheets/d/1emYxYQGi_VYXdWTcLPJ9ttvL2ygbTnZ0Apx_TsASvSs/edit#gid=0), this results in 0.14% of downloads of Addblock Plus through AMO come from Collections.**
_(This  is not including downloads that occur because users discover an add-on through a collection, but install it from its detail page. But it might give a first sense of the scale of the impact of Collections on the add-on ecosystem.)_

**Comment by tofumatt** [comment]
In terms of "vocal group", it's worth keeping a numerical count of that... from what I saw it was 3-6 users in GitHub issues, but there could have been dissent elsewhere too.

That is a low number, and I believe at least a few of those users _maintained_ collections, hence their issue with its removal. But if no one uses the collections they create, those complaints are largely moot.

**Comment by jvillalobos** [comment]
>This is not including downloads that occur because users discover an add-on through a collection,

That might be wrong. If you click from a collection to an add-on page, the URL will have source identifiers: `src=collection&collection_id=XXXXX`, and I think those will count towards the stats.

>But if no one uses the collections they create, those complaints are largely moot.

The caveat I would add here is that collections that are only used by their creators can be evidence of gaps in our search features, which I think is the case at least for themes.

**Comment by EnTeQuAk** [comment]
Just thinking loud on this topic so don't thake it too seriously.

I recently thought about collections and as @jvillalobos said

> The caveat I would add here is that collections that are only used by their creators can be evidence of gaps in our search features, which I think is the case at least for themes.

which brings me to, we're investing heavily into our search and once our search is capable of things we never even imagined we could add something like "saved search" which would allow people to save searches like "author:cgrebs" as "My Addons" or "tag:web AND tag:development ordering:created" as "Most recent Web Developemnt Addons" and internally they would execute a search and that's it.

If we keep the ability for users to favorite things the abilities for creating collections without actually having collections could be huge.

But that's basically just a replacement of collections and doesn't contribute to the idea of not having them at all.

But it could also be a way to rethink our managed collections (promos, disco pane, etc).

Again, just thinking loud...

**Comment by andymckay** [comment]
I've provided a docs to @jvillalobos and @designakt of some MySQL queries. I'm not sure how useful it is and it doesn't really answer the questions @designakt had, but hey there's some numbers there.

**Comment by designakt** [comment]
I asked our vocal part of the community to understand why the use collections:
https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/24?u=maritz
They seam to mostly be a tool to compensate for other shortcomings. (e.g. bad search, bad descriptions)
I think we could do better by addressing those rather than just keeping collections because they exist.

**Comment by pwalm** [comment]
No, we should not. User collections are being EOL'd and being replaced by "Favourites" in the new AMO design. Mozilla Collection will remain.
