### ISSUE TITLE
Addons email address does not update when Primary email address changed

### ISSUE THREAD

**Issue by maxchuquimia** [mozilla/addons#1071]
### Describe the problem and steps to reproduce it:
- I have two email addresses, A and B.
- The page https://addons.mozilla.org/en-US/firefox/users/edit#acct-notify shows email address A - this is where I receive notification about Addons
- I cannot change address A to address B as the field is disabled
- There is text that says "You can change your email address on Firefox Accounts" and a link to https://accounts.firefox.com/settings 
- After visiting Firefox Accounts, I can see that address B is my primary address and A is my secondary address (this is correct)

### What happened?
- Changing my primary email address in Firefox Accounts does not change the email address Addons uses (I tried swapping between them too to see if it would help, it did not)

### What did you expect to happen?
- Addons notifications should be sent to my primary email address

**Comment by AlexandraMoga** [comment]
I wasn't able to reproduce the issue in prod by following the steps mentioned above. I have repeated them several times, with different addresses but AMO seemed to receive the email update made in Firefox accounts.

**Comment by maxchuquimia** [comment]
Strange.. I just tried again to switch the primary and secondary addresses but it still doesn't affect what I see on the Addons site. Then I thought I'd sign out and sign back in again and now after the "Sign in to continue to Firefox Add-ons" screen I get a 500 with the response `{"detail":"Internal Server Error"}`... are you able to check on my account to see if its broken?

**Comment by maxchuquimia** [comment]
All issues have now been fixed by AMO administrators :)
