### ISSUE TITLE
Waterfox 56.2.11 Only 4 Add-ons enabled on startup?

### ISSUE THREAD

**Issue by Petros606** [mozilla/addons#1073]
I believe this is a duplicate and has already been reported.

I have 6 Add-ons installed. If all are enabled, only 4 are enabled after closing browser and restarting. The others are automatically disabled.

Add-ons:

Browser Backgrounds 0.49
Enhancer For YouTube 2.0.93
Ghostery 8.3.4
uBlock Origin 1.20.2
Dark Mode for Firefox 1.6
Video DownloadHelper 7.3.6

If you enable all 6, close browser then restart, only the first 4 Add-ons will be enabled. The others are disabled.

**Comment by wagnerand** [comment]
Can you reproduce this in Firefox? If not, this should probably be reported to Waterfox folks.

If you can, is there anything you can see in the browser console, maybe after you have set `extensions.logging.enabled` to `True` in `about:config`? Can you provide the add-on ids for the add-ons that get disabled?

**Comment by Petros606** [comment]
I am only running Waterfox from now on. extension.logging.enabled is set to false. I will change it to true and report back.

**Comment by wagnerand** [comment]
I am sorry we do not support Waterfox. Please talk to the WaterFox people instead.

**Comment by Petros606** [comment]
Changing extension.logging.enabled to true did nothing. I will post at Waterfox.
