### ISSUE TITLE
Request Accessibility review

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons#10748]
Would be good to get a review of the general accessibilty on AMO like we did for the discovery pane.

~~This can happen early Q4.~~

A few ideas of things we'd want checked out (but not limited to):

* Keyboard accessibility.
* Screenreader accessibility.
* Colour checks e.g. contrast.

**Comment by MarcoZehe** [comment]
Unsubscribing from this issue because I am now retired and no longer work on accessibility projects, Mozilla or otherwise. Please refer to the current members of the Mozilla accessibility team for reviews.
