### ISSUE TITLE
Android add-on claims Fennec is an unsupported platform

### ISSUE THREAD

**Issue by wisniewskit** [mozilla/addons#1077]
When I visit the page of my add-on ([Google Search Fixer](https://addons.mozilla.org/en-US/firefox/addon/google-search-fixer/)) on AMO in Fennec (nightly or release), it tells me that the platform is unsupported and will not allow me to install the addon.

However, I know that I selected Android when I uploaded version 1.5.1 of the add-on when asked to do so for the Recommended Add-ons program (by checking Android, un-checking desktop).

I also uploaded a new version 1.5.2 yesterday which seemed to work fine for a time, but today it is also claiming to not be supported on Android.

Note that on the Developer Hub Status page, the validation column says that they're "All platforms" while the older versions say "Android".

**Comment by wagnerand** [comment]
As @willdurand pointed out, the URL should be https://addons.mozilla.org/en-US/android/addon/google-search-fixer/. Can you try that on your Android?

**Comment by wisniewskit** [comment]
@wagnerand, ah, yes that link does work. Very interesting. I had just tapped on the first Google search result, and it gave me the wrong link. It also seems that some of my users were fooled in the same way.

Is there anything that could be done to improve that UX flow? It seems strange that the base landing URL would be for an incompatible platform, and if searches are pointing users to the wrong page, it would be good to at least make it clear that that landing is for the desktop browser only.

**Comment by muffinresearch** [comment]
@wisniewskit thanks for the report. Fixing the UX for this flow will be happening in Q4 see https://github.com/mozilla/addons-frontend/issues/8701
