### ISSUE TITLE
Do not recommend AdBlocker Ultimate and remove it from AMO

### ISSUE THREAD

**Issue by Darkspirit** [mozilla/addons#1078]
https://twitter.com/Pythux/status/1154403982342852609 (retweeted by https://twitter.com/gorhill)
> Why is @firefox recommending an extension which seems to be a copy-pasting from another extension and potentially in copyright infringement? @AdBlockUltimate claims to be open-source and GPLv3 so I installed and checked the sources using the debugger.
![EAVETSHXoAA2PLa](https://user-images.githubusercontent.com/17962859/61889960-bdc54f00-af06-11e9-93ff-178380105423.jpeg)

https://twitter.com/Pythux/status/1154403991251488770
> It's troubling how similar the code is to @AdGuard. And the fact that "adguard" name is used all over the code.  Does GPLv3 allow to replace all copyright notices with your own brand in all source files?
![EAVETtJWkAAd_DS](https://user-images.githubusercontent.com/17962859/61889949-b4d47d80-af06-11e9-8377-0d7726ef36a8.jpeg)

https://twitter.com/Pythux/status/1154404006824947713
> What's even more puzzling is that "recommended extensions" from @firefox are supposed to be manually curated before being labelled that way. Did this go under the radar? Or am I missing something?
![EAVEUS4W4AAlghp](https://user-images.githubusercontent.com/17962859/61889922-a8e8bb80-af06-11e9-9426-41ee68ce715c.png)

https://twitter.com/Pythux/status/1154404013347094530
> Ironically, @AdGuard has less Firefox users than the less up-to-date seemingly copy: @AdBlockUltimate 🤔

https://twitter.com/Pythux/status/1154404015335194625
> Last but not least, I could not find the source code anywhere. They do have a GitHub account but it does not seem to match the code shipped to the extension store: https://github.com/adblockultimate/

https://twitter.com/gorhill/status/1154409380881883137
> And I had reported it nearly two years ago: https://github.com/gorhill/uBlock/issues/3027#issuecomment-330068831

https://github.com/gorhill/uBlock/issues/3027#issuecomment-330077439
> What a scam. Here is the diff of one of the file, they changed nothing except for the header comment:
![30524154-4f0fb0dc-9bbc-11e7-8cdb-5461bf9e3ebb](https://user-images.githubusercontent.com/17962859/61890074-ffee9080-af06-11e9-8891-9741742c5dc5.png)

**Comment by Darkspirit** [comment]
https://twitter.com/gcpascutto/status/1154421965421207552
> Thanks for the heads up. Team is looking into it.

**Comment by adblockultimate** [comment]
Hi Darkspirit

AdBlocker Ultimate team here. It is true that we've built upon a few other AdBlockers, but there is nothing wrong in that. We aim to deliver highest quality, fast speed in order to remove ALL ads - most of the adblockers permit certain ads from selected networks to bypass the filters. So there is a major difference. We've transferred the GPLv3 license as required by the license itself, the statement of copyright infringement is absurd.

Please let us know if you need more information, you can always reach as at adblock@adblockultimate.net

**Comment by Kein** [comment]
`I came here to laugh at you.jpg`

Ironic how it is still recommended.
