### ISSUE TITLE
Add Ability to Group Add-ons in Firefox to Turn On/Off Simultaneously

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons#1079]
Suggestion to add ability to group add-ons in Firefox to be able to enable/disable them all at once. 

Many add-ons are useful only for a specific task but are not needed at other times, taking up precious resources (memory, cpu, etc). Some use cases include shopping, website editing, research, etc.

**Comment by jvillalobos** [comment]
That's a Firefox Add-ons Manager bug, which should be [filed on Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Add-ons+Manager).

**Comment by smayer97** [comment]
Please note this is an enhancement request, not a bug. Is Bugzilla still the right place to submit this request?

**Comment by jvillalobos** [comment]
Yes, everything in Firefox is tracked on Bugzilla.

**Comment by smayer97** [comment]
thx

**Comment by smayer97** [comment]
for reference, added here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1570168
