### ISSUE TITLE
Double spaces in strings

### ISSUE THREAD

**Issue by zelitomas** [mozilla/addons#108]
Hello, I'm just letting you know about unusual double spaces in strings in AMO server.

Affected strings are:
- src/olympia/blocklist/templates/blocklist/blocked_detail.html:33 ([Pontoon](https://pontoon.mozilla.org/cs/amo/LC_MESSAGES/django.po/?filter=suggested&string=149306))
- src/olympia/bandwagon/templates/bandwagon/edit_contributors.html:26 ([Pontoon](https://pontoon.mozilla.org/cs/amo/LC_MESSAGES/django.po/?filter=suggested&string=149275))
- src/olympia/bandwagon/templates/bandwagon/collection_detail.html:186 ([Pontoon](https://pontoon.mozilla.org/cs/amo/LC_MESSAGES/django.po/?filter=suggested&string=149265))

**Comment by zelitomas** [comment]
I hope this is the right repo to file a bug, as I can't find any code here...

**Comment by andymckay** [comment]
They are in mozilla/addons-server:

https://github.com/mozilla/addons-server/blob/master/src/olympia/blocklist/templates/blocklist/blocked_detail.html
https://github.com/mozilla/addons-server/blob/master/src/olympia/bandwagon/templates/bandwagon/edit_contributors.html
https://github.com/mozilla/addons-server/blob/master/src/olympia/bandwagon/templates/bandwagon/collection_detail.html

**Comment by eviljeff** [comment]
mentor @wagnerand

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by Revanth47** [comment]
Hi @wagnerand!  Can I take up this issue?

**Comment by eviljeff** [comment]
@Revanth47 sure!  andymckay linked to the files that need to be changed - let us know if there any difficulties.
