### ISSUE TITLE
Addon incompatiblity warning when browsing an android link to AMO addon from desktop

### ISSUE THREAD

**Issue by SaphireLattice** [mozilla/addons#1080]
### Describe the problem and steps to reproduce it:
1. Create an addon, upload it.
2. Select only `Firefox` and unselect `Firefox for Android`
2.5. Wait for approval
3. Try to install the addon on desktop Firefox (linux) via a `/<lang>/android/addon/<addon-name>/` link, e.g. https://addons.mozilla.org/en-GB/android/addon/reddit-user-tagger/

### What happened?
The addon page shows `This add-on is not available on your platform.`

### What did you expect to happen?
The addon can be installed

### Anything else we should know?
After adding Firefox for Android into Compatibility, the addon is installable on desktop.

**Comment by jvillalobos** [comment]
This is intentional. The site will try to guide clients to the right page (`/firefox/` or `/android/`), but will generally assume that you are using the kind of client indicated in the URL.

**Comment by jvillalobos** [comment]
It's also worth noting that the header has a More item with a way to switch sites.
