### ISSUE TITLE
Emailless signup, signin and access recovery

### ISSUE THREAD

**Issue by KOLANICH** [mozilla/addons#1081]
Currently AMO is vulnerable to shutting down users' email accounts.

For example a it is possible to require by a law all the email providers, including the one user is using, to require users' identification via their cellphone accounts (in order to get a phone account one has to provide operator with an ID). This is discrimination against users unwiling to do so. This way users are to be blackmailed into either identifying themselves or losing access to all their online accounts.

Including AMO one.

In fact such legislation is going to he passed in Russia.

The only way not to take part in this discrimination is to stop requiring every account to have a email.

**Comment by eviljeff** [comment]
There are many, many, free email services available on the internet that are outside of countries that require ID to operate an account, so switch to one of those.

Even if AMO decided to stop requiring an email address, FirefoxAccounts, which we use for authentication, requires an email address so it'd be dependent on that service making a change.
