### ISSUE TITLE
Invalid or corrupt add-on file when uploading

### ISSUE THREAD

**Issue by GMWS217** [mozilla/addons#1083]
Error with autoOrder.zip
100% complete · 5.75 KB of 5.75 KB
Please make sure to report any linting related issues on GitHub
Your add-on failed validation with 2 errors.

Invalid or corrupt add-on file. 
Sorry, we couldn't load your WebExtension.

File : [autoOrder.zip](https://github.com/mozilla/addons/files/3475611/autoOrder.zip)

**Comment by wagnerand** [comment]
Hello,

you are using a zip algorithm or variant that is not supported by our servers. Please use a standard zip method.
