### ISSUE TITLE
Internal Server Error api AMO

### ISSUE THREAD

**Issue by aelisya** [mozilla/addons#1084]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Internal error when i want to connect myself to AMO
### What happened?
Internal server error on the api

### What did you expect to happen?
be connected

### Anything else we should know?
this bug is also on other navigator
(Please include a link to the page, screenshots and any relevant files.)

**Comment by aelisya** [comment]
Screenshot of the problem :

![BUG](https://media.discordapp.net/attachments/534038175471894528/610583141228347598/Annotation_2019-08-12_231813.png)

**Comment by diox** [comment]
There is probably a mixup with your account, maybe you've changed email recently and we can't figure out which one is the right one. Please contact amo-admins@mozilla.com with details of what email(s) you're using and they should be able to sort you out.
