### ISSUE TITLE
Trying to download and extension

### ISSUE THREAD

**Issue by joehuber1** [mozilla/addons#1087]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Extension GiveBack.ie
### What happened?
Said it didn't exist but I download it a week or so ago on another computer
### What did you expect to happen?
to download the extension
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
Extensions are removed from the site all the time for various reasons. You can contact the developer for more information. This repository is not intended to track these issues.
