### ISSUE TITLE
[Question] Is possible to change the 'my addons' page?

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla/addons#1088]
### Describe the problem and steps to reproduce it:
In the page: https://addons.mozilla.org/en-US/developers/
The addon name is not an url, is just a text: Make the url from name to be to 'Product Page'.

In the page: https://addons.mozilla.org/en-US/developers/addons
The addon name url is for Edit page but to bottom is already a url with 'Edit Product Page': Make the url from name to be to 'Product Page'.

**Comment by jvillalobos** [comment]
The More item in the second page has a menu item pointing to the Product Page. Alternatively, you can use your developer profile page to see Product Page links to your add-ons.

Having said that, you bring up valid points. We don't have any plans to work on the Developer Hub for the time being, though, so I'm closing this until we have some time to focus on it.
