### ISSUE TITLE
Android user can install addons that are desktop only

### ISSUE THREAD

**Issue by XrXr** [mozilla/addons#1090]
### Describe the problem and steps to reproduce it:
Go to https://addons.mozilla.org/en-US/firefox/addon/youtube-subscription-checker/ on an Android device and click install.

### What happened?

It installs.

### What did you expect to happen?

It should not install

### Anything else we should know?

This addon isn't designed for Android and it doesn't work on it. Version 2.5.2 is *not* marked as compatible with Android in the add-on dashboard, but it seems that users can install it anyways.
I'm also able to install https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/ which I assume isn't supported on Android as the menu entry doesn't work.

**Comment by muffinresearch** [comment]
We added a warning for this in https://github.com/mozilla/addons-frontend/issues/6136
