### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by Jiangyiqun** [mozilla/addons#1092]
I could not submit a new add-on [Archive.zip](https://github.com/mozilla/addons/files/3569067/Archive.zip), the error message is
> Your add-on failed validation with 1 error.
Sorry, we couldn't load your WebExtension.
Error: Validation was unable to complete successfully due to an unexpected error.
Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU

___
More information:
- The add-on works in about:debugging without error
- addons-linter result
>Validation Summary:
errors          0              
notices         0              
warnings        14  
- I have tried upload-listed and upload-unlisted, the result are the same
___

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
  - could not submit a new add-on

* Whether your add-on is listed or unlisted.
  - unlisted

* The URL where you submitted the add-on.
  - https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted

* The approximate time you submitted the add-on, with timezone.
  - 8:41 pm
  - Tuesday, 3 September 2019 (AEST UTC+10)

**Comment by spoji** [comment]
Hi,

That was an interesting issue to debug. "web-ext lint" on this zip file doesn't show any warnings/errors.

File \svg\www.amazon.com..svg is causing the issue here. It would seems AMO doesn't like filenames that finishes with a "dot".

Renaming the file "www.amazon.com..svg" to "www.amazon.com.svg" should fix your issue.

**Comment by willdurand** [comment]
@Spoji could you please report this issue in addons-linter too?

**Comment by muffinresearch** [comment]
Fixed via https://github.com/mozilla/addons-server/issues/12379
