### ISSUE TITLE
"learn how to make an add-on" link from https://addons.thunderbird.net/en-US/developers/ fails

### ISSUE THREAD

**Issue by mvoorhis** [mozilla/addons#1093]
### Describe the problem and steps to reproduce it:

* Start web browser.
* browse to the add-on "developer hub" at https://addons.thunderbird.net/en-US/developers/
* click on "Learn How to Make an Add-On"
* this tries to send us to https://developer.thunderbird.net/add-ons/about-add-ons, which on my browser throws a standard Firefox "Problem Loading Page" error.

### What happened?

* unsure.  developer.thunderbird.net is an alias for fasthosting.gitbook.com and fasthosting.gitbook.com (which *does* have an IP address, 45.55.238.214) does not respond.  Perhaps a hosting problem at "gitbook.com" ...?

### What did you expect to happen?

* I expected to see a webpage explaining how to build Thunderbird add-ons; instead I got an error.

### Anything else we should know?

* Nope, this seems pretty straigitforward.  A link, the most important link on the page, is failing.  Perhaps the hosting site, gotbook.com, is only temporarily offline?  I can't imagine you'd want to keep the methods behind creation of TBird Add-Ons a secret, especially since so many of them no longer work with the update to TB v68.

Thanks, --MCV.

**Comment by diox** [comment]
Hi,

Please file issues for addons.thunderbird.net at https://github.com/thundernest/addons-server ; it's a separate entity from Firefox Add-ons now (I would transfer the issue but I don't have the relevant permissions on thundernest/addons-server to do so)
