### ISSUE TITLE
Verification keeps failing

### ISSUE THREAD

**Issue by M-Reimer** [mozilla/addons#1097]
### Describe the problem and steps to reproduce it:
See the attached XPI file. I'm unable to upload this new version of my Addon

[toggleglobalcolors-1.1.0.xpi.zip](https://github.com/mozilla/addons/files/3606912/toggleglobalcolors-1.1.0.xpi.zip)

**Comment by muffinresearch** [comment]
@M-Reimer as noted above the deploy issues have been resolved now. I'm going to close this out  but please do re-open it if you continue to experience an issue.
