### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by achyuth-krishna** [mozilla/addons#1098]
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
 [[ This is occurring on the submission of a new version of an existing addon ]]

* Whether your add-on is listed or unlisted.
 [[ Unlisted ]]

* The URL where you submitted the add-on.
 [[ Using web-ext 3.1.1 (web-ext sign --timeout=1800500 --api-key=user:10113386:208]]

* The approximate time you submitted the add-on, with timezone.
 [[ 1 PM to 1:30 PM Indian Standard Time ]]

**Comment by achyuth-krishna** [comment]
It seems that the file is too big to attach here. (29MB). Is there any other way to attach?

**Comment by achyuth-krishna** [comment]
![image](https://user-images.githubusercontent.com/55274054/64846693-dc081b00-d62a-11e9-94f9-f6111c51d30c.png)

**Comment by spoji** [comment]
Could you please attach to this bug a copy of your add-on?

Also, an important note : Please keep your API keys secret and never commit them to a public code repository or share them with anyone, including Mozilla contributors. It would seem you copy pasted yours in this bug report.

Thanks!

**Comment by spoji** [comment]
You can use https://send.firefox.com/ and paste the link here.

**Comment by spoji** [comment]
> It seems that the file is too big to attach here. (29MB). Is there any other way to attach?

You can use https://send.firefox.com/ and paste the link here.

**Comment by achyuth-krishna** [comment]
Thank you @spoji . I will revoke the credentials. Extension attached at : https://send.firefox.com/download/ec307b222c657cff/#3N7gmeUjcPTsxQt0Kv7Njg

**Comment by achyuth-krishna** [comment]
https://send.firefox.com/download/a10791dcecebfc4f/#Fl2D62joK3rzZhWcvkIczA

**Comment by spoji** [comment]
Thanks for the file.

First, this extension doesn't follow the [Add-on Policies](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Reviews). While I didn't read all the code, one issue is that the values inside manifest's content_security_policy key can create multiple security holes that are not in-line with the "Development Practices" of the policy. 

Note that Mozilla may reject or block affected versions or entire add-ons that don’t meet these policies, depending on the extent of their non-compliance.

Now regarding your issue, I was able to reproduce it. It looks like that sometimes, the linter breaks the memory limits on production. This could be related to [issue 467](https://github.com/mozilla/addons/issues/467).

**Comment by spoji** [comment]
A quick cleanup of what seems to be unused files and folders (for example folder whatfix.com/gwt-unitCache and unused libraries in whatfix.com/lib/js) changed the size of this extension from 28.1MBs to 4.04MBs. This gives on AMO proper validation message : "Your add-on was validated with no errors and 184 warnings.".

Putting aside the numerous policy issues with this extension, cleaning the package seems to be a good first step.

**Comment by achyuth-krishna** [comment]
Thank you Sylvain. I will do the necessary cleanup and update this thread to closure.

**Comment by achyuth-krishna** [comment]
Update: Removed the unused code and signing worked like you mentioned. Next steps are to sanitise the remainder of the content and fix the permissions as mentioned before.

I will proceed to close this ticket now. Thank you very much for your timely help.
