### ISSUE TITLE
Translation Tools Page Not Displaying

### ISSUE THREAD

**Issue by dylanmorroll** [mozilla/addons#1099]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Go to the website:
https://addons.mozilla.org/en-GB/firefox/collections/4757633/translation-tools/

### What happened?
Nothing properly loads.

### What did you expect to happen?
The translation tools to load.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![image](https://user-images.githubusercontent.com/9341472/65060389-0c77ee00-d978-11e9-87a1-87603115ada5.png)

**Comment by jvillalobos** [comment]
This collection was discontinued. Did you follow a link from another site to get to that page?

**Comment by dylanmorroll** [comment]
Ahhh okay no worries! Yes I followed from this page:
https://support.mozilla.org/en-US/kb/how-add-translate-feature-firefox

Cheers
