### ISSUE TITLE
Can’t sign in to AMO (500 error)

### ISSUE THREAD

**Issue by andylolz** [mozilla/addons#1102]
### Describe the problem and steps to reproduce it:

1. Open a new private window
2. Visit: https://addons.mozilla.org/en-GB/developers/
3. Click "Sign In" in the top right
4. Spinny wheel appears, but eventually 500 errors

This is maybe related to #1084.

### What happened?

I got a 500 error.

### What did you expect to happen?

I expected to reach a login screen of some sort.

### Anything else we should know?

Thanks for looking into this (and for all your hard work in general!)

**Comment by willdurand** [comment]
Hi, sorry for the inconvenience. I have just been told that FxA (our authentication service) is having issues, so that's likely why you cannot sign in and you receive 500 errors. The FxA and ops teams are working on fixing this issue.

**Comment by andylolz** [comment]
Cool – many thanks for the update.
