### ISSUE TITLE
How do I reset my RSS token for /developers/feed?

### ISSUE THREAD

**Issue by lilydjwg** [mozilla/addons#1104]
### Describe the problem and steps to reproduce it:
I've subscribed my https://addons.mozilla.org/zh-CN/developers/feed?privaterss=SOME_TOKEN and unfortunately it gets leaked when I share an exported OPML file publicly (because I was only looking for `token` lines to delete).

### What happened?
I can't find a way to reset that feed token.

### What did you expect to happen?
A link to reset the feed token should be easily discoverable.

### Anything else we should know?
I'm also concerned what that token can do. I expect it only allows to view the feed but I'm not told so.

**Comment by diox** [comment]
It's a pretty old, almost unused feature that hasn't received a lot of love so the UX around it is kinda clunky. The token can't do anything else other than accessing your feed. 

An admin should be able to delete the existing token for you, so please contact amo-admins at mozilla.com, including the token value.

**Comment by lilydjwg** [comment]
Thanks!
