### ISSUE TITLE
Firefox enterprise addons monitoring/management

### ISSUE THREAD

**Issue by AkashKrDutta** [mozilla/addons#1105]
Use-case: In our enterprise, we need support for monitoring/managing extensions on firefox browsers (chrome has google admin console for this). Firefox currently has group policies in its enterprise version but that is available only in windows and mac but that doesn't allow managing extensions centrally (like blocking or force installing extensions across hosts).

We want the feature of central management of extensions just like chrome for security management in our enterprise. We have both linux and windows desktops. Is there any way this can be acheived? I have asked this in #firefox IRC but haven't got any response on this.

**Comment by mkaply** [comment]
We have the ExtensionSettings policy on Firefox which maps pretty closely to the Chrome version:

https://github.com/mozilla/policy-templates/blob/master/README.md#extensionsettings

We have GPO available as well as a JSON file for Linux.

**Comment by AkashKrDutta** [comment]
I understand that @mkaply . Problem is there is not a central monitoring feature which is quite essential from an enterprise point of view. There is not a dashboard/API that allows us querying for the list of extensions installed in a specific host.

Is there any plan to have such a functionality in firefox? I myself is willing to work in such a usecase and contribute for it. :)

**Comment by mkaply** [comment]
We're looking into the possibility of providing something, but have no plans right now. Chrome has built out a full cloud management solution which we don't have.
