### ISSUE TITLE
How to add french dictionary for my locale after I install it from the supply list of dictionaries

### ISSUE THREAD

**Issue by haggar2019** [mozilla/addons#1107]
I used to have the French spell check available to use in message entry in hotmail, but just recently, it is no longer there other than English.  So I am trying to add the french dictionary so I can do a spell check in hotmail online again, I click Add dictionary and I get the whole supply list from which I click on French language pack and French dictionary (thinking that this will Add it.  But it just doesn't.

How do I add the French dictionary to do a spell check in hotmail?

**Comment by jvillalobos** [comment]
You can find help on our support site: https://support.mozilla.org/kb/how-do-i-use-firefox-spell-checker

**Comment by haggar2019** [comment]
> 
> 
> You can find help on our support site: https://support.mozilla.org/kb/how-do-i-use-firefox-spell-checker

I am sending you an email reply to your email to me with an attachment.  Take a look at the attached .. Do you see the button Add to Firefox?  I can't .. Please re-open the case and fix the problem .. and please don't close it until I tell you that your fix worked.

**Comment by haggar2019** [comment]
Please see attached.

Take a look at the attached .. Do you see the button Add to Firefox?  I can't .. Please re-open the case and fix the problem .. and please don't close it until I tell you that your fix worked.

The french dictionary used to be in the list of the first page and somehow .. it just only the English US dictionary is showing.

Rafik
________________________________

**Comment by jvillalobos** [comment]
This tracker is not meant for support requests. That's why I closed this and sent you to the right place instead.

**Comment by haggar2019** [comment]
What you sent me to, as you see in the attachment, does not resolve the problem because what is described in the solution is not reflective of the reality that I showed you in the attachment.

Can we please move to finding a solution as to how to add the french dictionary eventhough it is installed?!!!!
________________________________
