### ISSUE TITLE
 504 Gateway Timeout when submitting new version

### ISSUE THREAD

**Issue by lidel** [mozilla/addons#1108]
### Describe the problem and steps to reproduce it

I am geting 504 Gateway Timeout when submitting new version of ipfs-companion to AMO (bundle attached to [v2.8.6](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.8.6))

### What happened?

Server returned HTTP 504 `GATEWAY_TIMEOUT` during upload of new version.

Tried multiple times between 5:30-6:20 PM, October 1, 2019 (UTC) 

### What did you expect to happen?

Work? :upside_down_face: 

### Anything else we should know?

![2019-10-01--19-32-45](https://user-images.githubusercontent.com/157609/65985922-1ffc7c00-e483-11e9-8b1b-012960915023.png)

(this issue is blocking bugfix release for https://github.com/ipfs-shipyard/ipfs-companion/issues/761)

**Comment by diox** [comment]
Hi,

Sorry about that, 2-3 people seem to be affected by this according to our logs, and you're one of the unlucky ones :(

It might be caused by a migration we're running in the background, that will take a few hours to finish. We'll monitor the situation and keep you posted.

**Comment by mihai-chezan** [comment]
Just want to say I was also hit by this while trying to upload a new version of `outlook-web-app-notifications`. I've also tried several times to upload it and each time I got the `504 GATEWAY_TIMEOUT`.
I've rebuilt the addon  with the latest version of web-ext@3.2.0 and tried again but got the same problem.

**Comment by mihai-chezan** [comment]
FYI: Upload works for me now

**Comment by lidel** [comment]
Tried again today and was able to submit new version :tada: 
Closing as fixed, thanks!
