### ISSUE TITLE
GB English Language pack - Corrupt? 

### ISSUE THREAD

**Issue by greenasil** [mozilla/addons#1112]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I tried to install the GB English Language pack and got the error in the screenshot: Installation aborted because the add-on appears to be corrupt. 

### What happened?

I tried to install the GB English Language pack and got the error in the screenshot: Installation aborted because the add-on appears to be corrupt. 

### What did you expect to happen?

expected the pack to install 

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![image](https://user-images.githubusercontent.com/9914210/66558357-530dd200-eb4b-11e9-87c4-32ccc1a0f9fe.png)

**Comment by jvillalobos** [comment]
I just gave it a try and it worked for me. Which version of Firefox are you using? Does this happen for other language packs too?

**Comment by greenasil** [comment]
Hi,
I checked the Spanish language pack and got the same error message.
I am using version 60.2.2esr (32-bit) - the version is managed by my
company IT department so I cannot just update it.

Thanks in advance for any further assistance,

Lisa

**Comment by jvillalobos** [comment]
In that case you'll want to look for the "See all versions" link in the "More information" box in the add-on page. Language packs are tied to specific Firefox versions, and you'll need to look for the version compatible with 60.

The corrupt message is wrong, however, so maybe there's still an issue to investigate here.
