### ISSUE TITLE
Addon for Android shown as not compatible.

### ISSUE THREAD

**Issue by alexs20** [mozilla/addons#1114]
When i uploaded my addon i checked the "Firefox for Android"  check box only, but when i open it on Android version of Firefox it shows "This add-on is not available on your platform." message.
I tried to re-upload the addon and again selected "for Android" option, but nothing was changed.

My addon url: "https://addons.mozilla.org/en-CA/firefox/addon/flingcast/

**Comment by jvillalobos** [comment]
The correct URL for mobile is [https://addons.mozilla.org/**android**/addon/flingcast/](https://addons.mozilla.org/android/addon/flingcast/). There are some mobile / desktop issues that we're going to address soon in https://github.com/mozilla/addons-frontend/issues/8701 and other related issues.
