### ISSUE TITLE
Can't remove "Stale" from persistent bugs

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/addons#1115]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I posted about an accessibility problem, link below.

### What happened?

It has not been solved, so it is hidden as stale.

### What did you expect to happen?

I kinda expected it to go unsolved indefinitely, like most accessibility problems, but not to be hidden away.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

There doesn't seem to be any way to remove the status tag.

https://github.com/mozilla/addons/issues/824

**Comment by diox** [comment]
Stale label is applied to issues that are, well, stale. Nobody has been working on them for a while, they are unlikely to get fixed, they are clogging up our backlog, so we decided to automatically label them as stale after a long period, and close them after a second shorter period of inactivity once the label has been set.

If you had replied during the second period, the label would have been removed, though the same thing would have likely happened again a few months later when the bot came back if nobody had picked the issue in the meantime.

Ultimately it comes down to this: We don't think issues that are unsolved indefinitely are worth keeping open. They are still there though, and can be re-opened if someones decides to work on them.

**Comment by eyalroz** [comment]
I disagree that bugs with no comments are "clogging" back-logs, they're just in back-logs. Sometimes they are actually stale, sometimes they've just been unduly ignored. There should be an option to de-stale them. 

This is doubly important if, for some reason, notifications about upcoming staleness aren't sent to / don't reach stakeholders in the issue/bug.

**Comment by diox** [comment]
Replying when the bot leaves its initial comment un-stales it. So does re-opening. But, again, in the end if nobody picks up the issue then it doesn't matter much, it will eventually go stale again.

**Comment by eyalroz** [comment]
> Replying when the bot leaves its initial comment un-stales it ... So does re-opening. 

But one needs appropriate privileges to reopen...
