### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by milolo2** [mozilla/addons#1116]
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
In new submission 

* Whether your add-on is listed or unlisted.

* The URL where you submitted the add-on.
https://addons.mozilla.org/es/developers/addon/submit/upload-listed

* The approximate time you submitted the add-on, with timezone.
aprox 14:00 

CEST: Central European Summer TimeActualmente en servicio | UTC+2
[ImageViewer.zip](https://github.com/mozilla/addons/files/3762354/ImageViewer.zip)

**Comment by diox** [comment]
Hi,

This is not a valid [webextension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions).
