### ISSUE TITLE
 “Access your data for all websites” permission

### ISSUE THREAD

**Issue by panderlad** [mozilla/addons#1117]
An extension that has the “Access your data for all websites” permission, can transmit all the data from all websites visited on my browser to their server so to know what credit card I entered on a website or what type of porn do I watch? 

How can I check and be sure that it transfer the data or not?

**Comment by jvillalobos** [comment]
The only way to be sure is to monitor all your web traffic and/or inspect the add-on code in detail. Unfortunately that's a risk that is really difficult to mitigate. If you don't fully trust an add-on that requires those permissions, it's best that you don't install it. We can only assure that Recommended extensions are being code reviewed, so they shouldn't put users at risk.
