### ISSUE TITLE
Homepage broken in production because of "invalid" hero URLs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#1121]
After yesterday's push (2019.10.24), we had to fix two issues:

- https://github.com/mozilla/addons-frontend/issues/8828
- https://github.com/mozilla/addons-server/issues/12717

Both are related to URLs returned by the API and manually added in the Django admin.

When we enter an absolute URL in the admin, the frontend parses it (if the domain matches the amo domain) and constructs a relative URL so that we have **client-side navigation**. It automatically prepends both the `locale` and `app`. That is why `a.m.o/extensions/` works, but `a.m.o/firefox/extension/` outputs `a.m.o/en-US/firefox/firefox/extensions/`, which is an invalid URL. It does not matter if a URL entered in the admin is absolute or relative because the server will "absolute-ify" it anyway (i.e. the API always returns absolute URLs in the `/hero/` responses).

**Comment by willdurand** [comment]
In Slack, @eviljeff said:

> I still think it would be "best" if frontend could handle all valid AMO urls, including urls that include the app and/or locale.  (so addons-frontened). But if that's not possible/feasible then just label the admin with descriptive text (so addons-server).  A possible longer term (better) addons-server fix would be to automatically strip the app and locale from relative urls and restrict absolute urls to non-AMO urls.

**Comment by eviljeff** [comment]
to rephrase myself, 3 options are:
1) addons-frontend could handle all valid AMO urls, including urls that include the app and/or locale. 
2) label the admin in addons-server with descriptive text 
3) in addons-server would be to automatically strip the app and locale from relative urls and restrict absolute urls to non-AMO urls.

(3) is the most complete though it would possibly partially negate (1) - and make it harder to test it handles all urls.  It would also add restrictions to what URLs Scott could use, and the requirement from the PRD was it was any urls (e.g. maybe there would be a need to specially link to the /android/ version of the addon, or a specific locale.)
