### ISSUE TITLE
Bots downgraded my extension

### ISSUE THREAD

**Issue by thomaslane373** [mozilla/addons#1122]
Hello, within one minute 6 negative ratings (1 star) from different accounts came to my extension (https://addons.mozilla.org/en-US/firefox/addon/you-tube-download-hd/reviews/), which, judging by their name, were registered at the same time (Firefox user 15366885, Firefox user 15366884, Firefox user 15366882, Firefox user 15366881,  Firefox user 15366880, 15 hours ago Rated 1 out of 5 by Firefox user 15366868). I think that these are ordinary bots. Please remove these ratings and understand the situation. Thank.
![bots downgrade](https://user-images.githubusercontent.com/57039756/67621091-960cbc80-f850-11e9-9305-44455a85fa79.png)

**Comment by jvillalobos** [comment]
Please email amo-admins AT mozilla DOT com with the details and we'll help you there.
