### ISSUE TITLE
Add Filter for thunderbird 68+ on addons.thunderbird.net

### ISSUE THREAD

**Issue by gom-sh** [mozilla/addons#1126]
### Describe the problem and steps to reproduce it:
Visit addons.thunderbird.net and try to filter for Thunderbird version 68 or higher. This is not possible. Since Thunderbird 68 had major changes in regards of addons (introduce web extension, disable most of the old xul addons) this would be very helpful.

### What happened?
No option to filter for Thunderbird 68+ to search for compatible addons

### What did you expect to happen?
Having a option to filter for Thunderbird 68+

### Anything else we should know?
The Documentation for Thunderbird 68 within developer.mozilla.org is outdated, informations are taken from: https://www.ghacks.net/2019/05/21/not-all-extensions-will-be-supported-in-thunderbird-68/

**Comment by wagnerand** [comment]
Please file this issue at https://github.com/thundernest/addons-server/
