### ISSUE TITLE
Discovery pane background colour doesn't match other panels

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons#113]
The discovery pane mocks have the background colour as `#f5f5f5` but the other panels are using `#fbfbfb`. We might need to update our mocks to reflect this.

![screenshot 2016-05-18 11 17 28](https://cloud.githubusercontent.com/assets/211578/15369230/587861a4-1cf7-11e6-89a1-cab3fa35282d.png)
> Screenshot showing the background colour of the other panes on the left (padding will be removed in [bug 1273974](https://bugzilla.mozilla.org/show_bug.cgi?id=1273974).

![screenshot 2016-05-18 12 39 59](https://cloud.githubusercontent.com/assets/211578/15369264/7ff57ec4-1cf7-11e6-9219-6ee4af298108.png)
> Screenshot with lighter background colour on the disco pane to match (contrast is reduced on the add-on boxes)

**Comment by pwalm** [comment]
ok, let's make the add-on icon background white. So it'll be one big white block on light grey.

**Comment by muffinresearch** [comment]
Fixed
