### ISSUE TITLE
Broken pagination on addons.mozilla.org

### ISSUE THREAD

**Issue by noleakseu** [mozilla/addons#1132]
### Describe the problem and steps to reproduce it:
Pagination does not work on https://addons.mozilla.org/en-US/firefox/user/4757633/

### What happened?
https://addons.mozilla.org/en-US/firefox/user/4757633/?page_t=1
and
https://addons.mozilla.org/en-US/firefox/user/4757633/?page_t=4
and any other page_t return the same content.

### What did you expect to happen?
Browse all 197 addons.

### Anything else we should know?
No

**Comment by diox** [comment]
Pagination does work, it shows different themes on each page - If you look closely, the pagination is for the themes section, not the extensions one. There is only one page worth of extensions.
