### ISSUE TITLE
Addon doesn't apply tabs.insertCSS randomly, Windows only

### ISSUE THREAD

**Issue by kiboke** [mozilla/addons#1134]
### Describe the problem and steps to reproduce it:

tabs.insertCSS is randomly not applied, only in Windows 10, in both the latest FF Dev Edition or FF 70.0.1, and only when error `Unchecked lastError value: Error: No matching message handler` occurs and points to the line which calls tabs.insertCSS

Test URL: https://www.paypal.com/uk/signin
Please reload it many times (from 3 to 15 in my case, every time it happens differently) in order for the issue to occur.

### What happened?
The sticky (originally blue) warning about cookies on the bottom of the page sometimes remains blue, while the inserted CSS should paint it red every time.

### What did you expect to happen?
The sticky (originally blue) warning about cookies on the bottom of the page should always be red.

### Anything else we should know?
Simple test extension is attached.
[plugin.zip](https://github.com/mozilla/addons/files/3883396/plugin.zip)

This bug made many users of my "I don't care about cookies" extension to report a visible cookie warning which can't be reproduced in Firefox for Linux or even Chrome/Opera equivalent extensions which use the same code. Some of them use FF 68, so it may be a much older bug.

**Comment by jvillalobos** [comment]
Firefox bugs need to be reported on https://bugzilla.mozilla.org/
