### ISSUE TITLE
 got an error when trying to access my firefox developer account

### ISSUE THREAD

**Issue by azteffaps** [mozilla/addons#1137]
### Describe the problem and steps to reproduce it:
try to manage my addons

### got this message:
You do not have permission to perform this action.

### What did you expect to happen?
to be able to manage my addons
### Anything else we should know?
this is a link for an addon I have which is no longer avaliable
https://addons.mozilla.org/firefox/downloads/file/2999528/search4musix_for_firefox-1.0.841.498-fx.xpi?src=dp-btn-primary

the developer hub account email is azte.ffaps@gmail.com

**Comment by jvillalobos** [comment]
Please send an email to amo-admins AT mozilla DOT com with the details.
