### ISSUE TITLE
please provide AMO filter for webextensions

### ISSUE THREAD

**Issue by gregrwm** [mozilla/addons#1140]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Try to find a webextension extension that has a particular feature.

### What happened?
You find scads of extensions that aren't implemented using webextensions.

### What did you expect to happen?
There should be a way to specify i only want to see extensions implemented as webextension, whether searching or browsing, in AMO.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by bobsilverberg** [comment]
You can specify "extension" for "Add-on Type" when searching for add-ons on AMO:

<img width="1255" alt="Screenshot 2019-12-06 13 40 05" src="https://user-images.githubusercontent.com/142755/70347192-fae30b80-182d-11ea-98f0-40d31ed64e52.png">

Does this not satisfy what you need to do? If not, can you be more specific, and/or perhaps attach a screenshot showing the problem?

**Comment by gregrwm** [comment]
Starting with firefox 57, extensions implemented using XUL and XPCOM, ie most of the extensions currently on AMO, won't work.  Firefox 57 and newer can only run extensions implemented as webextensions.  So when browsing or searching for extensions on AMO, we want to be able to specify that we only want to see extensions implemented as webextensions.

**Comment by diox** [comment]
Non-Webextensions have been removed from AMO over a year ago. There are only WebExtensions left now.
