### ISSUE TITLE
Addon Validation Error - Possible issue with spread operator

### ISSUE THREAD

**Issue by siefkenj** [mozilla/addons#1141]
Please attach a copy of your add-on, and fill in the following information:

[mailmergep@example.net-latest.zip](https://github.com/mozilla/addons/files/3935673/mailmergep%40example.net-latest.zip)

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
*submission of a new addon*

* Whether your add-on is listed or unlisted.
*listed*

* The URL where you submitted the add-on.
https://addons.thunderbird.net/en-US/developers/addon/submit/upload-listed

* The approximate time you submitted the add-on, with timezone.
*Sat Dec 07 2019 18:30 GMT-0500 (Eastern Standard Time)*

I get a message `Error: Validation was unable to complete successfully due to an unexpected error.` when I try to upload my extension. I am not sure why the message is appearing...the only thing in common with the three errors I receive is that they all seem to reference javascript lines with the spread `...` operator used for destructuring.

**Comment by muffinresearch** [comment]
Please re-file this issue on https://github.com/thundernest/addons-server since this site is unrelated to add-ons for thunderbird.
