### ISSUE TITLE
Yahoo! Mail requires verification every time in container.

### ISSUE THREAD

**Issue by kwazel** [mozilla/addons#1143]
### Describe the problem and steps to reproduce it:
Log in to Yahoo! Mail
Enable"Yahoo Account Key" under "Account info". This removes usage of passwords and makes logging in only possible with either an sms, of an activation code on another device (e.g. iOS Y!Mail app, or Android Y!Mail app).
Close the browser.
Open the browser again.
Go to mail.yahoo.com, you will be logged in.
Log out completely, maybe reset all browser data.
Open Yahoo Mail in an container.
Log into Yahoo mail. You will need an activation code (e.g. on phone).
Close the browser.
Open the brower.
Open Yahoo Mail in the same container: you will need an activation code, _again_.

### What happened?
I need an activation code every time I open https://mail.yahoo.com

### What did you expect to happen?
I only need my activation key once, or once every so many weeks.

### Anything else we should know?
This used to work without Firefox Containers. I however decided to move all sensitive accounts to their own container.

**Comment by jvillalobos** [comment]
For issues with container extensions, please go to https://github.com/mozilla/multi-account-containers/#readme
