### ISSUE TITLE
Customize Firefox Assistant Widget for Android

### ISSUE THREAD

**Issue by syemvlis** [mozilla/addons#1144]
### Anything else we should know?
Hi, I'm looking for a possibility to customize the Android widget (transparenz, color, shape [ellipsoid, rectangular]).

Like the Google Widget.
![Screenshot_20191214-194824](https://user-images.githubusercontent.com/6274819/70853179-cb29a880-1eaa-11ea-9a29-98c6a222e2db.png)

That's would be fine.
Regards, simey

**Comment by jvillalobos** [comment]
This repository is for addons.mozilla.org, not specific add-ons or Firefox for Android. I don't know what Firefox Assistant is, but it's out of scope for this issue tracker.
