### ISSUE TITLE
No addon popups in Debian Bullseye

### ISSUE THREAD

**Issue by Igorgro** [mozilla/addons#1145]
### Describe the problem and steps to reproduce it:
I have just installed Firefox on my laptop (Lenovo G50-45) with Debian Bullseye KDE.
When I'm trying to use any addon, it shows me a zero-sized popup.
Also, I have another pc (with different hardware configuration) with the same os and Firefox version, but there are no problems on that pc.

### What happened?
Any addon shows empty popup.

### What did you expect to happen?
I expected to see addon settings dialog.

### Anything else we should know?
Cannot take screenshot, because popup closes when I press PrtScr key.

**Comment by jvillalobos** [comment]
Please report add-on bugs to the developer of the add-on. This repository is for the add-ons website, not individual add-ons.
