### ISSUE TITLE
Feature request: Sort add-ons by last disabled for faster self troubleshooting

### ISSUE THREAD

**Issue by Jinkiesz** [mozilla/addons#1146]
Could we have this feature? sometimes one of my addons keeps breaking some functionality in the web, prompting me to disable the addons one by one to find the faulty addon.

It would help us to work faster in this task if we already find the faulty addon we can enable the rest of recently disabled addons

**Comment by jvillalobos** [comment]
Bugs and feature requests for the Firefox Add-ons Manager [should be filed here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Add-ons+Manager).
