### ISSUE TITLE
Auto rotation of PR assignments under github is broken

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons#1150]
Now that github has integrated pull request review assignments via a team we've move off of using Pull Panda to using this feature directly in github.

## How it's configured

The auto assignment is configured via team settings.

<img width="1035" alt="addons-engineering_Team_·_Edit_·_Code_Review_Assignment_-_Firefox_Nightly" src="https://user-images.githubusercontent.com/1514/72173424-63924a80-33cf-11ea-8bcb-940cece5ecb3.png">

If this team is assigned a review a member of the team should be picked and assigned the review and the original team assignment is deleted.

We also use a `CODEOWNERS` file in each repo to point to that team. This should result in new PRs being assigned a member of the team based on the `Code review assignment` settings.

Having set this up there are several problems:

## Issue 1: Load balancing is broken

This is supposed to do the exact same thing, and should load balance across the team with new PRs. However, trying this manually (after changing `CODEOWNERS` because the proxy team hack isn’t needed in github) this seems to keep assigning everything to a single user.

The Round Robin algorithm works

## Issue 2: Bots that update or raise PRs just assign the team and it's never updated

When a PR is filed the team should be automatically assigned and the team assignment should be removed. What actually happens is the team is assigned and it's never updated.

## Issue 3: Existing assignments are ignored and bots re-assign the team

If assignment has already been set-up using the code review assignment feature, when a bot updates the PR it will simply add the team assignment.

**Comment by muffinresearch** [comment]
The current plan is to disable `CODEOWNERS` reference to the team until these issues are ironed out on Github.

**Comment by KarthikNayak** [comment]
We've noticed this issue too, it only assigns CR to two members of a 8 member team.

**Comment by kik-o** [comment]
Noticed this as well. No team member is ever assigned on a 19 person team.

**Comment by oerp-odoo** [comment]
Same here
