### ISSUE TITLE
Reddit Enhancement Suite Addon site.

### ISSUE THREAD

**Issue by oneofseven** [mozilla/addons#1151]
### Describe the problem and steps to reproduce it:
try to install that addon and say :"Este complemento requiere una versión más reciente de Firefox (al menos la versión 69.0). Estás usando Firefox 68.0."

That's not true. About:support says i'm using 72.0.1 in Windows 10. Revised and reinstalled Firefox. Other Addons works right.

### What happened?

Don't know.

### What did you expect to happen?

Install the addon.

### Anything else we should know?

Include a screenshot
(Please include a link to the page, screenshots and any relevant files.)
![reddit](https://user-images.githubusercontent.com/3510700/72666126-15043200-3a07-11ea-9c54-05e93a69d67f.png)

**Comment by jvillalobos** [comment]
You probably have the preference `privacy.resistFingerprinting` set to true, or have installed some other extension or software that masks Firefox as a different version. AMO won't work correctly under those circumstances.
