### ISSUE TITLE
Update "Get the Add-on" button image 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons#1157]
We [offer](https://blog.mozilla.org/addons/2015/11/10/promote-your-add-ons-with-the-get-the-add-on-button/) a branded "Get the Add-on" button for extension developers to use on their web properties. It comes in two sizes: **172 x 60 pixels** and **129 x 45 pixels**. 

It would be great to have these buttons updated with the current Firefox browser logo (which is available on https://mozilla.design/firefox/logos-usage/). 

![Firefox Logo](https://user-images.githubusercontent.com/23342476/72829374-80324c00-3c33-11ea-9c16-bddc7bd88dd8.png)

**Comment by jvillalobos** [comment]
I'd be good to look at current badges (Apple store, Chrome store, etc.) and re-evaluate the available sizes.

**Comment by Sav22999** [comment]
I think the badge should be updated, maybe using the same model of others (size, style, ect.).

**Comment by ManishAradwad** [comment]
I'd love to do this...
But where should I upload the updated badges??

**Comment by jvillalobos** [comment]
I think attaching them to this issue should be good enough.

**Comment by ManishAradwad** [comment]
![AMO-button_1-1](https://user-images.githubusercontent.com/29497701/74786214-24122480-52d2-11ea-94df-e1a02695ac3e.png)
![AMO-button_2-1](https://user-images.githubusercontent.com/29497701/74786218-25dbe800-52d2-11ea-95ef-805430d15a03.png)
Will these do??

**Comment by caitmuenster** [comment]
Thank you, @ManishAradwad! 😻 These are lovely! I'll update the post to include these.

**Comment by eviljeff** [comment]
@caitmuenster is this issue fixed?

**Comment by caitmuenster** [comment]
@eviljeff Yeah, I think we can close it. I know some other folks were interested in other sizes/styles of badges. If people want to submit those to https://github.com/mozilla/extension-workshop, I'm happy to review and make them available to a wider audience.
