### ISSUE TITLE
Update references from IRC to Matrix

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#1161]
Files that probably need updating:

```
addons/docs/server/push-duty.rst
```

Marking as P2 because IRC is going away in a few weeks.

**Comment by ManishAradwad** [comment]
Would love contributing to this issue...
Just a question though,
I should only change IRC to matrix, right? or is there something else I'm missing??

**Comment by muffinresearch** [comment]
Unfortunately the changes require information that isn't readily availble. See the label `contrib: good first bug` for good first bugs.
