### ISSUE TITLE
Let Users Vote Helpful reviews

### ISSUE THREAD

**Issue by HattinGokbori87** [mozilla/addons#1164]
Feature request:- 
Please consider letting user's vote helpful reviews and prioritize most voted reviews on review page.
It is an alternative proposal for the problem described in [issue no. 1111](https://github.com/mozilla/addons/issues/1111)
Thanks.

**Comment by jvillalobos** [comment]
We want to do this in https://github.com/mozilla/addons-frontend/issues/5462, but don't have a concrete timeline to implement it. Closing because it's a duplicate request.
