### ISSUE TITLE
Install switch revisions

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons#117]
@mstriemer @muffinresearch 
Was just reviewing [Stuart's JSBin](http://jsbin.com/tamure/edit?html,css,output) and came across a few things that need to change with the switch:
- "off inactive" should not have a roll over state
- "on inactive should not have a rollover state
- "active un-installing" should be inactive
- "active installing should be inactive
- "downloading" should be active (the user should be able to cancel a download)
- new checkmark svg for "installed" is [here](https://github.com/mozilla/addons/blob/master/docs/ux/assets/switch-checkmark.svg)

**Comment by andymckay** [comment]
Is this still valid?

**Comment by mstriemer** [comment]
I filed https://github.com/mozilla/addons-frontend/issues/552 review this so we don't miss it. We definitely don't support cancelling a download right now. The rest I'm unsure of.

**Comment by pwalm** [comment]
Moved this over to addons-frontend, sorry
