### ISSUE TITLE
Unable to install add ons on the AMO web site

### ISSUE THREAD

**Issue by learn-help** [mozilla/addons#1170]
### Describe the problem and steps to reproduce it:
我在未登录 AMO 网站，但登录 Firefox 浏览器的情况下，访问 AMO 网站，找到附加组件[百度翻译](https://addons.mozilla.org/zh-CN/firefox/addon/%E7%99%BE%E5%BA%A6%E7%BF%BB%E8%AF%91/)，然后点击按钮 “添加到 Firefox”，但是 Firefox 告诉我 “Firefox 已阻止此网站安装未通过验证的附加组件”。这是为什么呢？
而且，只有附加组件[百度翻译](https://addons.mozilla.org/zh-CN/firefox/addon/%E7%99%BE%E5%BA%A6%E7%BF%BB%E8%AF%91/)出现了此问题，其他附加组件（包括未被推荐的附加组件）都没有发生这种情况。
  
### What happened?
Firefox 告诉我 “Firefox 已阻止此网站安装未通过验证的附加组件”

### What did you expect to happen?
Firefox 提示用户“要安装百度翻译吗”，用户同意后安装百度翻译

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![image](https://user-images.githubusercontent.com/53334669/75139470-aa41c700-5727-11ea-9fc6-53e9ac951ab6.png)

**Comment by jvillalobos** [comment]
Yes, it looks like there's a signature problem with the latest version of the extension.

**Comment by wagnerand** [comment]
Can you please submit a new version? It should be fixed as soon as it gets approved. Thanks!
