### ISSUE TITLE
running total gone missing

### ISSUE THREAD

**Issue by jalvo2014** [mozilla/addons#1172]
use ynab daily. Today running total wasgone. Checked toolkit and it was turned on. Logged out of ynab and rebooted. Running total still missing.. Firefox by the way, up to date.

went back and removed toolkit and then reinstalled it on firfox while ynab was not running. cHECKED OPTIONS and made sure I had running total on.

started ynab but running total still missing in accounts.

[ynab tookit prob;lem.docx](https://github.com/mozilla/addons/files/4258114/ynab.tookit.prob.lem.docx)

**Comment by muffinresearch** [comment]
We are unable to provide support for individual add-ons.

This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services.  

Please look at the add-on details page and see if the add-on author has provided support information. If supplied you'll find it in the "More information" section.

<img width="509" alt="facebook_container_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/41969476-6de12c9e-79ff-11e8-9df5-45a79bb70975.png">
