### ISSUE TITLE
Translations being abused to hijack search results

### ISSUE THREAD

**Issue by p4t44** [mozilla/addons#1173]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

The top result of a [search on AMO for uBlock](https://addons.mozilla.org/en-GB/firefox/search/?q=ublock) is an extension called "Amazon" (it is literally a button which opens amazon) which has no relation to uBlock (Origin) but has the following tags: "amazon","ublock","亚马逊". Scrolling down the 3rd and 4th results are made by the same developer as the "Amazon" one, Booking.com and Reddit (both also pseudo-bookmarks) also feature "ublock" in there tags. It seems like there is a flawed search system if an add-on which is reccomended, has millions of users and the search term in it's title is featured below an add-on with a different name and litter over 1k users?

### What happened?

Spam unrelated addons are appearing at the top on searches for popular addons.

### What did you expect to happen?

The more popular, reputable and reccomended addon to show up first 

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Definitely an issue, [also reproducible in en-US](https://addons.mozilla.org/en-US/firefox/search/?q=ublock), though I don't think it's related to tags (which are no longer used in the search algorithm) 
.
[That add-on](https://addons.mozilla.org/en-US/firefox/addon/amazon-open-button/?src=search) has the string "ublock" in `summary`, `description` and `name` for `gu`, `dsb`, `en-CA`, `ka`.

![search-ublock](https://user-images.githubusercontent.com/187006/75433741-bceb1480-5950-11ea-9888-34c874d72763.png)

**Comment by diox** [comment]
I filed https://github.com/mozilla/addons-server/issues/13591 for a long-term fix, in the meantime we're going to look through those results and remove those who look out of place. We've built a query to monitor weirdness in translations like this in the future.

**Comment by p4t44** [comment]
Using different languages, that is a sneaky way to hijack search results.

Trying out different common search terms, the same developer seems to be using the same technique to spam different searches. [A search a for AdBlock](https://addons.mozilla.org/en-GB/firefox/search/?q=adblock) has 2/4 top results coming from "50 Amber's Toolbar Buttons" which [have predictable titles and descriptions in other languages](https://addons.mozilla.org/en-CA/firefox/addon/maps-button/).

Infact look at this [list of add-ons in canadian english](https://addons.mozilla.org/en-CA/firefox/user/5556019/), they all seem to have the names of other popular extensions (adblock, ublock, block, grammarly, lastpass, noscript, duckduckgo). Seems to be complete spam.

**Comment by wagnerand** [comment]
Thank you for this report @p4t44. In the future, please file security sensitive issues at https://bugzilla.mozilla.org/enter_bug.cgi?product=addons.mozilla.org&component=Security and make sure to check the box **Restrict access to this bug to members of the "Security-Sensitive Client Services Bug" group.** at the bottom of the page.
