### ISSUE TITLE
Consider a different error message for old browsers to account for privacy resistance users

### ISSUE THREAD

**Issue by Caspy7** [mozilla/addons#1179]
Over the years in helping with support on IRC there's been a fair number of users coming in complaining that AMO isn't allowing them to install addons because their browser is too old (despite that not being the case).

Can we consider adding text to the effect:
> If you are on release later than 68.0, you may need to temporarily disable your fingerprint resistance setting.  

And perhaps add a (?) at the end that on hover elaborate further.

**Comment by jvillalobos** [comment]
The resist fingerprinting setting points to the current ESR branch. This means that we would be showing this message to a big chunk of users, and the majority of them wouldn't be using this setting. I think it's bound to cause more confusion than help, so I'd rather not do this.
