### ISSUE TITLE
no link to Games collection from carousel

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons#118]
Apologies if I wasn't clear in the original issue filed, but the Games collection that was recently added to the Disco Pane module manager is missing any CTA to take you to the Games collection itself. 

If you go to the AMO Homepage now you'll find the collection promoted in the carousel. You can click to three of the games featured in the carousel image, but not the collection itself. 

https://addons.mozilla.org/en-US/firefox/collections/mozilla/games/

Is there a relatively quick and easy fix to this? Is there any way we can link to the collection landing page itself? 

@diox

**Comment by andymckay** [comment]
Adding a link is easy and can go out in the next push, do you just want to link up some text or do you want us to add something specific to it?

**Comment by devaneymoz** [comment]
Linking up the title and/or text that's already there would be excellent. Thanks, Andy!

In the meantime I'll take it out of the Disco Pane.

**Comment by andymckay-limited-access** [comment]
Well I had a quick look and there really isn't an easy to do that on the
code we've got right now.

**Comment by devaneymoz** [comment]
Hmm... so there's no feasible way to get a collection link anywhere in the promo image? A creative workaround perhaps? 

If not it's not the end of the world (the collection is being promoted via email and social campaigns as well). But let me know and if it's the best we can do I'll still put it in the carousel.

In the future, is there no simple way to promote collections from the Disco Pane that lead directly to the collection landing page?

**Comment by diox** [comment]
There used to be an option to "linkify" the title of the promo module, but it went away when I removed the obsolete modules in https://github.com/mozilla/addons-server/pull/2533 as the only module using it was a super old Firefox 4 (!) Promo. I can bring it back and use that.

**Comment by devaneymoz** [comment]
That would be fantastic, thank you!
