### ISSUE TITLE
Revise add-on submission policies to forbid opening changelogs in un-prompted popups without opt-in

### ISSUE THREAD

**Issue by ssokolow** [mozilla/addons#1182]
### Describe the problem and steps to reproduce it:

In the last two weeks, I've had two extension updates steal focus from what I'm doing with unwanted changelog popups that couldn't be disabled. 

* [Cookie AutoDelete](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/661)
* [HTTPS Everywhere](https://github.com/EFForg/https-everywhere/issues/19030)

### What happened?

In one case ([Cookie AutoDelete](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/661)), the author acknowledged that he had misjudged his user base's reaction and prepared a patch to allow it to be opt-in beyond first install.

However, in the other case ([HTTPS Everywhere](https://github.com/EFForg/https-everywhere/issues/19030)), the developers were worryingly reluctant to move away from forcing all users to suffer through the behaviour intended for users too tech non-savvy to find the toggle before settling on a more reasonable solution.

### What did you expect to happen?

Such intrusive self-advertisement should be forbidden without an opt-in. Instead, being limited to something similar to how Firefox itself handles these sorts of notifications, with no more than a change to the associated UI element (eg. browser action or page action icon).

In the past, I've had my non-tech-savvy mother encounter this sort of thing from previous violators, and she called me, worried that she'd been hacked.

### Anything else we should know?

The Cookie AutoDelete update happened too many days ago for me to easily pull up and screenshot the popup, but this is the egregious thing that showed up in a new tab from HTTPS Everywhere a few minutes ago, replacing the page I was looking at and filling my screen without warning:

![Screenshot_20200327_045614](https://user-images.githubusercontent.com/46915/77739230-12c2e300-7009-11ea-8fa7-7128e2bcbefd.png)

**Comment by momozor** [comment]
Confirmed on my side.

**Comment by kewisch** [comment]
Thank you for the report, we'll consider this for a future policy update. A new tab with changelog information seems somewhat reasonable under current policies. You are welcome to review the add-ons in the meanwhile.

**Comment by teohhanhui** [comment]
OK: Opening a new tab with changelog in the background.

Not OK: Silently opening a new tab that steals focus from the user.

**Comment by marmarek** [comment]
Exactly, opening a foreground tab that steal the focus is a very disruptive thing to do, almost like popup ads (and more recently - "subscribe for updates/newsletter" popups). The policy should not allow this behavior.

**Comment by ssokolow** [comment]
Tree Style Tab just did it in response to an un-prompted update.

It switched me away from what I was actively working on in the process.
