### ISSUE TITLE
Duplicate, possibly malicious addon "umatrix"

### ISSUE THREAD

**Issue by vonshednob** [mozilla/addons#1185]
### Describe the problem and steps to reproduce it:
Searching for "umatrix" shows two plugins by the same name:

 * https://addons.mozilla.org/en-US/firefox/addon/umatrix/
 * https://addons.mozilla.org/en-US/firefox/addon/umatrixins/

The only difference being, apparenty, that the latter requires more rights.

Seems suspicious, but I don't have the competence to investigare myself.

**Comment by wagnerand** [comment]
Thank you for reporting it to us. We'll take a look.
