### ISSUE TITLE
Translation mistake for ukrainian at addons reviews page

### ISSUE THREAD

**Issue by who0ps** [mozilla/addons#1189]
### Describe the problem and steps to reproduce it:
Open reviews  [page ](https://addons.mozilla.org/uk/firefox/addon/facebook-container/reviews/)to any addon.
Switch languagee to ukrainian

### What happened?
![зображення](https://user-images.githubusercontent.com/17404606/78761555-6deec100-798b-11ea-8905-1e8087ccb732.png)
5, 4, 3, 2, 2
### What did you expect to happen?
5, 4, 3, 2, 1
### Anything else we should know?
`<select class="Select AddonReviewList-filterByScoreSelector">`
Wrong:
`<option value="1">Показати лише відгуки з оцінкою 2 зірки</option>`
Correct:
`<option value="1">Показати лише відгуки з оцінкою 1 зірка</option>`

**Comment by willdurand** [comment]
@who0ps thanks for reporting this issue. Did you know that you could contribute to our localized content? You can see the uktrainian strings here: https://pontoon.mozilla.org/uk/amo-frontend/LC_MESSAGES/amo.po/

Would you like to give it a try and fix this issue?

**Comment by who0ps** [comment]
@willdurand, thanks, didn't know.
[Here](https://pontoon.mozilla.org/uk/amo-frontend/LC_MESSAGES/amo.po/?string=194955). Someone need to review it.
