### ISSUE TITLE
Feature request: Beyond Recommended (discussion)

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#1190]
Building on the success of Recommended add-ons, I have always thought that there are other possibilities that are worthy of consideration.

Additional (but limited) badges can encourage developers to improve other aspects of their add-ons, as well as inform users of such quality & excellence.

Some criteria ideas for possible consideration:

- User-Interface
- Included Help/Documentation
- ??

**Comment by wagnerand** [comment]
It's an idea worth talking about, but since this hasn't gotten much traction, I recommend starting a discussion on discourse and see if you get more feedback there. I'm closing this issue, since we can't do much at this point and discussions are more suitable on discourse.

**Comment by erosman** [comment]
@wagnerand Which section of discourse.mozilla.org would be best for this topic?
