### ISSUE TITLE
fonts are not loading properly. Can't read the text in some areas.

### ISSUE THREAD

**Issue by tina37-max** [mozilla/addons#1192]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by tina37-max** [comment]
Hi. The issue is often on credit card accounts so I can't send you a link. The numbers are not visible. I tried the same site with Chrome and it worked fine. I'm not sure what needs to be updated with the fonts in firefox. Can you suggest what to change in preferences from the default font set up?

**Comment by jvillalobos** [comment]
This repository is for the Mozilla Add-ons website. For general Firefox help, please go to https://support.mozilla.org/
