### ISSUE TITLE
Install button disabled, requires refresh to work

### ISSUE THREAD

**Issue by digitarald** [mozilla/addons#1198]
### Describe the problem and steps to reproduce it:

1. Open https://darkreader.org/help/en/
2. Click through to Firefox AMO

### What happened?

Install button stays disabled.

### What did you expect to happen?

Install button works. It does work after refresh.

### Anything else we should know?

![ScreenFlow](https://user-images.githubusercontent.com/8599/81753995-ea346280-9469-11ea-815c-cc51f18472f3.gif)

**Comment by diox** [comment]
It's working for me. Could you paste the console output separately ? It's hard to make out from the gif. Also, which version of Firefox were you using? Any specific settings ? Do you reproduce with a fresh profile ?

**Comment by digitarald** [comment]
Fresh profile doesn't reproduce. Still trying to see which addons might cause this.

**Comment by wagnerand** [comment]
@digitarald Any updates on this? If not, let's close this issue and we can reopen once we have more information.

**Comment by digitarald** [comment]
So far I could not find which addon causes this.
