### ISSUE TITLE
Downloaded file hash did not match provided hash

### ISSUE THREAD

**Issue by rkent** [mozilla/addons#12]
In trying to download my extension, the following error occurs (tried in both Windows and OSX and both show this):

1450131310950	addons.xpi	WARN	Download of https://addons.mozilla.org/thunderbird/downloads/file/317904/exquilla_for_microsoft_exchange-38.0.1159-tb-windows.xpi?src=api failed: Downloaded file hash (e4d37fc12bd11cde81584c1d5de76cca9a8bd5dac3c065490040bc6812b50cd5) did not match provided hash (d1bc6f3cf1777cf860398f13ceb01c8fe17e54344b39212a5232b9d6608a2e94)

The addon was recently update on Dec 4 automatically with this message:

"Your add-on, ExQuilla for Microsoft Exchange, has been automatically fixed for future versions of
Firefox (see https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/). The fixing process involved repackaging the add-on files and adding the string
'.1-let-fixed' to their versions numbers." 

It is likely that the hash mismatch occurred during that automatic update.

**Comment by wagnerand** [comment]
Let's handle this in olympia. See referenced issue.
