### ISSUE TITLE
Make the addon search smarter

### ISSUE THREAD

**Issue by dave0s** [mozilla/addons#1200]
uBlock origins shouldn't show up first when I type "to do list" on the addon search bar, even if the word "list" is in uBlock's description.

Please make it smarter, and thanks for all the good work!

**Comment by diox** [comment]
Hi,

Short words searches are tricky. We do a much better job for "todo list", FWIW. This is a valid issue, but unlikely to be fixed on the short term as we are short on resources.

**Comment by dave0s** [comment]
Even a recently updated search for "todo list" shows mostly irrelevant results.
