### ISSUE TITLE
When trying to download new Add-ons, the site (https://addons.mozilla.org) isn't recognizing my browser as Firefox so I can't download

### ISSUE THREAD

**Issue by djfang1** [mozilla/addons#1201]
When I search for a new add-on, the site isn't recognizing my browser as Firefox for some reason so there's no way I can DL any add-on.

I expected the browser to recognize the browser as Firefox.

In the past, I DL'd an add-on that spoofs the operating system like to Linux but I turned that off and other Add-ons to make sure there's nothing interfering. I'm also running the latest Firefox: 76.0.1 and have restarted my browser.

Any add-on I search for shows "Only with Firefox—Get Firefox Now" instead of a download button.
https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/?src=search

Thanks for the help

**Comment by jvillalobos** [comment]
It's likely that you still have something altering your user agent string, like [the `resistfingerprinting` preference](https://github.com/mozilla/addons/issues/716).
