### ISSUE TITLE
Use Creative Commons v4 licenses instead of v3 for new AMO themes

### ISSUE THREAD

**Issue by mhxion** [mozilla/addons#1203]
From [Mozilla discourse](https://discourse.mozilla.org/t/is-there-any-legal-reason-amo-creative-commons-licenses-is-offered-on-3-0-but-not-on-the-latest-4-0/60150) and @jvillalobos 

### Reproduce
For a new theme [submission](https://addons.mozilla.org/en-US/developers/addon/submit/distribution) on the add-ons site, the Creative Commons licenses that are offered to select are 
![license screenshot](https://discourse.mozilla.org/uploads/short-url/8GmEYB9ivQGQM5yNHb5euiJ0H5C.png)
All of them are available in only [v3.0](https://creativecommons.org/2006/08/09/version30publicdiscussionlaunched/)

### Expected outcome
[v4.0](https://creativecommons.org/2006/08/09/version30publicdiscussionlaunched/) licenses in addition to or instead v3.0. V4.0 was released in 2013, and seems to have some [improvements over 3.0](https://wiki.creativecommons.org/wiki/License_Versions#License_Suite_Versions).

I realize this copyright versioning might be different than how an application versioning works. I was wondering **if Mozilla has legal reasons to only extend it to 3.0?** Or maybe an upgrade is due?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-999)

**Comment by willdurand** [comment]
I suppose we only need to add v4 to this file: https://github.com/mozilla/addons-server/blob/d2158a83c4fd61bd2ab9be0954f0e7b26a5a99eb/src/olympia/constants/licenses.py

**Comment by jvillalobos** [comment]
@eviljeff mentioned this might be more involved.

**Comment by eviljeff** [comment]
_Adding_ the v4 licenses would be trivial-ish*.  But then we'd end up with an extra 6 licenses that are (to 99% of users) identical to the existing 6 licenses and be a very confusing experience imo, so we need to replace them.  If there is a difference between v3 and v4 (and I assume there is or this would be an entirely pointless request) then we can't "upgrade" the license on behalf of the owner of the content though.

*the theme wizard has different UI (partially implemented in javascript) that only support the existing 6 licenses.

What we'd need to do is to deprecate the existing 6 licenses - keep them for existing themes, but not have them available for new submissions.  This would need code changes in the devhub edit page, and potentially the upload page and theme wizard.  

An edge case for themes would be a new version of an existing theme - we could decide the theme developer can't continue to use v3 licenses and must re-license the new version under v4, but we'd need to signal that to the developer clearly.

**Comment by jvillalobos** [comment]
For the edit page and new version page I suggest showing the previously-selected 3.0 license at the bottom, as the default option. Something like:

- [ ] All Rights Reserved
- [ ] CC 4.0
...
- [ ] CC Share-Alike 4.0 
- [ ] Previously-selected 3.0 license

**Comment by mhxion** [comment]
I like both of the ideas, an adaptive rollout and an option for downgrade to v3. Thanks for looking into this. 

As `@eviljeff` mentioned about the differences between v4.0 and v3.0, Creative Commons wiki described [many points](https://creativecommons.org/version4/), but this excerpt would suffice the most important change I think
> Prior to version 4.0, Creative Commons granted permission to legal experts around the world to adapt (or “port”) the licenses where necessary to more fully align the text with the laws of different legal jurisdictions, and to translate the licenses to the local language(s). For the 4.0 suite, every effort has been made to avoid the need to port (though we will support official language translations).

**Comment by diox** [comment]
IMHO we don't need to worry too much about new versions of existing themes, as most theme developers don't submit new versions anyway. So it would use the license from the previous version as usual and developers would be free to change it later to 4.0 if they want to.

What's important to do is what @eviljeff pointed out: add the 4.0 licenses, drop the 3.0 from the built-in list, make sure everything still works properly.

**Comment by abyrne-moz** [comment]
I agree with this approach.

**Comment by ioanarusiczki** [comment]
At submission or in dev hub , there's 2 licenses which have been doubled

![twice in dev hub](https://github.com/user-attachments/assets/179db40d-0344-44b9-a8f1-108208401f1f)
![twice on submission](https://github.com/user-attachments/assets/cc23cb82-78de-4729-8157-71b8c095420d)

When I tried to choose another license from dev hub , when picking one of these 2 licenses I've a 500 

![500 server error](https://github.com/user-attachments/assets/5f34a41c-8d5e-4b42-aad4-a173b44b3c26)

Also if I tried with Creative Commons Attribution-NonCommercial 4.0 at submission I also hit a 500

![500 server error at submission](https://github.com/user-attachments/assets/4dafb4d9-3946-4450-a7c1-7bd9db978f97)

**Comment by diox** [comment]
@ioanarusiczki dev had some weird data I cleaned up

**Comment by ioanarusiczki** [comment]
I don't see any errors , looks good.

Checked this with api submissions for each [license](https://mozilla.github.io/addons-server/topics/api/licenses.html), been using v4 instead of v3. 

I can also use  v3 licenses, checking dev hub I see the old v3 lincense added at the end of the v4 list:

![with the api](https://github.com/user-attachments/assets/50494cad-2edf-4731-ad6d-e0f581e9b413)

**Comment by ioanarusiczki** [comment]
I've checked this on -stage. Noticed there's been something modified for the other add-on types. The "BSD License" is now "The 2-Clause BSD License" , looking on prod it's the same url as before https://opensource.org/license/bsd-2-clause. This should be fine.

![Stage 2-Clause BSD](https://github.com/user-attachments/assets/3cce7d24-8921-4901-98e3-ffa8d119443c)

**Comment by diox** [comment]
Yeah, the renaming of the BSD license was done separately as part of https://github.com/mozilla/addons/issues/14976 (which is not closed yet, more things to do there)
