### ISSUE TITLE
Addon statistics  - data problem (0 daily users)

### ISSUE THREAD

**Issue by villesinternet** [mozilla/addons#1205]
Addon statistics seem to have no "daily users" data after May 23.
However, "downloads" data seem to work.

For example, AdBlock Plus shows 0 daily users on May 23, 24 & 25 : https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30

**Comment by diox** [comment]
Hi, 

This should be solved later today and tomorrow (we'll backfill missing data) - see https://github.com/mozilla/addons/issues/510#issuecomment-634329910
