### ISSUE TITLE
"Daily Users" statistics stopped working

### ISSUE THREAD

**Issue by nicoth-in** [mozilla/addons#1206]
Stat page started reporting 0 daily users 1 week ago. The average daily user score also goes down.

![Stats](https://user-images.githubusercontent.com/35273601/83148477-ae53fb00-a101-11ea-9ae4-f5e585e20733.png)

**Comment by nicoth-in** [comment]
Same for other extensions. 
![Stats](https://user-images.githubusercontent.com/35273601/83149874-4f8f8100-a103-11ea-9ea9-3f0ad3c71607.png)

**Comment by diox** [comment]
Hi,

This should be solved later today and tomorrow (we'll backfill missing data) - see https://github.com/mozilla/addons/issues/510#issuecomment-634329910
