### ISSUE TITLE
Self-signed addon is currently stuck at “Awaiting Review”

### ISSUE THREAD

**Issue by Georgia77** [mozilla/addons#1208]
I am copying the ticket below. I have exactly the same issue right now. Thanks.

Hi, I had to do an emergency update to my self-signed addon. I uploaded the new version to addons.mozilla.org 1 but unlike before where usually I receive an email within 5 minutes, it’s been almost 30 minutes now and it’s still stuck at “Awaiting review”.

**Comment by diox** [comment]
We're dealing with a complex deployment issue right now and this is causing auto-approvals to be slowed down. This will be resolved soon.

**Comment by Georgia77** [comment]
Thanks for the speedy response.

**Comment by quinguyenhuu** [comment]
I have the same problem. Please help. 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/9970827/113823714-2de23a00-97a9-11eb-83ac-1eba13398eb5.png">
