### ISSUE TITLE
Removal of review doesn't decrease the number of reviews and doesn't update the rating

### ISSUE THREAD

**Issue by jorgk3** [mozilla/addons#121]
https://addons.mozilla.org/en-US/thunderbird/addon/thunderhtmledit/

No reviews, yet is says: Two stars, one user review.

**Comment by wagnerand** [comment]
I have seen this before, debugged the code and couldn't spot anything. We don't update the stats right away but use celery's `delay` iirc. However that shouldn't take two days, as the review was deleted on May 29. Maybe a dupe of https://github.com/mozilla/addons-server/issues/1618 ?

**Comment by jorgk3** [comment]
Surely a dupe.
