### ISSUE TITLE
Can't include or exclude search terms on addons.mozilla.org

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/addons#1210]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I tried to search addons.mozilla.org to see if it had tools to work around some issues with itch.

### What happened?

I searched itch, and got a bunch of results about twitch. So itch NOT twitch. More twitch. itch -twitch. More twitch.

### What did you expect to happen?

I expoected to get a bunch of useless results, from past experience, I don't know why I keep trying to use search here.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by MarjaE2** [comment]
By "can't include ... search terms" I mean I'm getting results which don't include my search terms as whole words, only as fragments.

**Comment by muffinresearch** [comment]
Can you provide more details on what itch is? I think this might just be because there's no content. 

You getting results with partial matches because the search sees them as the most relevant for the terms provided. This is likely to be correct assuming there's not an exact match.

**Comment by MarjaE2** [comment]
itch.io.

After buying a charity bundle, I was having trouble navigating my library there. I figured I should look for add-ons. You're right that there probably wouldn't be any results, but I can't see whether there are any when there are all these twitch results in the way.

**Comment by smayer97** [comment]
Still needs a solution. Current Search produces VERY POOR and irrelevant results too often.

**Comment by smayer97** [comment]
Still needs a good solution.

**Comment by smayer97** [comment]
WHy was the state changed back to stale after that state was removed? This force the automatic closure of this issue WITHOUT NOTICE and WITHOUT resolution!

Please RE_OPEN this ticket as this is STILL and ISSUE that needs to be addressed.
