### ISSUE TITLE
Irrelevant search results

### ISSUE THREAD

**Issue by helperman** [mozilla/addons#1211]
### Describe the problem and steps to reproduce it:
- I search the keyword: sqlite
- some addons in a list do not include this keyword

![00000125](https://user-images.githubusercontent.com/8351863/84564222-95864f00-ad69-11ea-8115-2b9fc95a5466.png)

### What happened?
Amidst the list of addons, there is a "JSON Lite" addon.
I open its page thinking that it contains my search keyword and try to find "sqlite" on the web page using Ctrl + F.
But there is no matches.
Then why does this addon was found and shown to me?

### What did you expect to happen?
In search results, there are only addons that include the search keyword.
In search results, there is no addons that do not include the search keyword.

**Comment by smayer97** [comment]
I see the same thing all the time too...lots of seemingly irrelevant results not even remotely matching the search criteria.

**Comment by jvillalobos** [comment]
The search breaks the query into individual terms like "lite" and uses it to look for additional results. Exact matches should appear closer to the top.

**Comment by MarjaE2** [comment]
If there are any matches, it's going to take a lot of sifting through the other results.

I tried search for "barometer" or "barometric" and guess what, too many results including "bar" or "metric" and no sign of my search terms. What is the point of search terms if the search function is going to chop them up to create its own terms, for more results?

**Comment by MarjaE2** [comment]
Similar issue reports: 1210, 1200, 905, 821, 818, 792, 783, 779, 729, 724, 695, 613, 355.

**Comment by smayer97** [comment]
Still needs a solution. Current Search produces VERY POOR and irrelevant results too often.

**Comment by smayer97** [comment]
Still need change for better solution.

**Comment by smayer97** [comment]
WHy was the state changed back to stale after that state was removed? This force the automatic closure of this issue WITHOUT NOTICE and WITHOUT resolution!

Please RE_OPEN this ticket as this is STILL and ISSUE that needs to be addressed.

**Comment by helperman** [comment]
Obviously, they're not gonna fix the issue.
Firefox is dead, Chrome killed it, we must accept it and make use of alternatives.
