### ISSUE TITLE
Enable gzip/br response compression on website

### ISSUE THREAD

**Issue by janakaud** [mozilla/addons#1217]
+++ This bug was initially created as a clone of Bug #1631252 +++

### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

User Agent: Firefox

Steps to reproduce:

1. Open the Network tab on Web Console of an already loaded page
2. Visit https://addons.mozilla.org/en-US/about
3. Inspect the network requests/responses

### What happened?

Responses are not compressed ("Transferred" size is almost the same (slightly larger) than "Size").
Confirmed by the absence of a 'Content-Encoding' header.

Headers observed (copied using Copy -> Copy ... Headers option of Firefox's network panel):

Request:

```
GET /en-US/about HTTP/1.1
Host: addons.mozilla.org
User-Agent: Firefox
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: _ga=GA1.2.1155137201.1539985720
Upgrade-Insecure-Requests: 1
```

Response:

```
HTTP/1.1 200 OK
amo-request-id: 277d81ac-2cb4-4755-b014-29cbff2991d9
Cache-Control: no-store
Content-Security-Policy: default-src https://addons-amo.cdn.mozilla.net; base-uri 'self'; child-src 'none'; connect-src https://www.google-analytics.com https://addons.mozilla.org https://sentry.prod.mozaws.net; form-action 'self'; frame-src 'none'; img-src 'self' data: https://addons.cdn.mozilla.net https://addons-amo.cdn.mozilla.net; manifest-src 'none'; media-src 'none'; object-src 'none'; script-src https://addons-amo.cdn.mozilla.net https://www.google-analytics.com/analytics.js; style-src https://addons-amo.cdn.mozilla.net; worker-src 'none'; report-uri /__cspreport__; font-src https://addons-amo.cdn.mozilla.net; prefetch-src https://addons-amo.cdn.mozilla.net
Content-Type: text/html; charset=utf-8
Date: Sun, 19 Apr 2020 12:08:30 GMT
ETag: W/"68b7-Ohiq0qHD7tU3iUB/1/uRnOzMgwg"
Public-Key-Pins: max-age=5184000; includeSubDomains; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="
Strict-Transport-Security: max-age=31536000
Vary: DNT, User-Agent
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Content-Length: 26807
Connection: keep-alive
```

### What did you expect to happen?

Since the browser is sending an `Accept-Encoding: gzip, deflate, br` header, a compressed response should be returned.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Similar issues were reported for [WMO](https://bugzilla.mozilla.org/show_bug.cgi?id=1631252) and [SUMO](https://bugzilla.mozilla.org/show_bug.cgi?id=1650610); first one's already fixed (thanks to [@agibson](https://bugzilla.mozilla.org/user_profile?user_id=468279)!).

**Comment by diox** [comment]
This was actually disabled on purpose a while back, to avoid [BREACH](https://en.wikipedia.org/wiki/BREACH). Since then, a lot of time have passed and notably all our important cookies should be set with `SameSite`, preventing authenticated cross site requests, so we could consider re-enabling compression.

**Comment by diox** [comment]
- addons-frontend side will be handled by ops in https://bugzilla.mozilla.org/show_bug.cgi?id=1687277
- addons-server side will be handled by https://github.com/mozilla/addons-server/pull/16337

Note: it was already enabled for static files and API, this is for HTML content.
