### ISSUE TITLE
store page indexing in google

### ISSUE THREAD

**Issue by RomanistHere** [mozilla/addons#1218]
### Describe the problem and steps to reproduce it:

I'm searching for "PopUpOFF" extension in Google. The extension is in the store for about a month. 
My search string is <<"popupoff" firefox>> - there are some results about Poper Blocker, but not the given extension. [Link to it](https://addons.mozilla.org/en-US/firefox/addon/popupoff/). it's indexing in Yandex. But not in Google and Bing. 
It is complete description of my problem. It's not very important, but I'm just creating this ticket because it's possible that there is a bug, so I would like to point on it.

### What happened?

I type in google next string:
"popupoff" firefox
press search button and see link to Poper Blocker

### What did you expect to happen?

I expected to be able to see the link to PopUpOFF in Firefox store

### Anything else we should know?
[Link to Google search](https://www.google.com/search?q=%22popupoff%22+firefox&oq=%22&aqs=chrome.0.69i59j69i57j69i59l2.3998j0j7&sourceid=chrome&ie=UTF-8)
[Bing one](https://www.bing.com/search?q=%22popupoff%22+firefox&qs=n&form=QBRE&sp=-1&pq=%22popupoff%22+firefox&sc=1-18&sk=&cvid=5571541A34E446E4B0DA5F86C733E0EA)
I would like to know why it's taking so much time to get indexed in Google search, usually it takes less time. Thank you

**Comment by muffinresearch** [comment]
This looks to be working:

<img width="847" alt="popupoff_firefox_-_Google_Search" src="https://user-images.githubusercontent.com/1514/94915158-485af400-04a4-11eb-9d07-4cbab78437e2.png">
