### ISSUE TITLE
Signing API (PUT /api/v3/addons/) - cannot specify platform (windows, mac). At least if I can it is not documented.

### ISSUE THREAD

**Issue by demaeyer** [mozilla/addons#122]
I have found no way to specify a platform with the signing API. Using a form parameter didn't work.

**Comment by EnTeQuAk** [comment]
This is true, it's not a lack of documentation, this isn't implemented currently.

Note to whoever might have to implement it: `olympia.signing.views:VersionView.handle_upload` currently uses `Addon.create_addon_from_upload_data` to create the add-on but probably should use `Addon.from_upload` or a mix of both to make it easier to pass on plattforms in case this will be implemented.
