### ISSUE TITLE
Cannot open rebatesme cashback add-on button for firefox

### ISSUE THREAD

**Issue by sphf** [mozilla/addons#1221]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
When I log on to the rebatesme.com, it directs me to download the rebatesme cashback add-on button for firefox. After I click that link, it directs me to a non found page

### What did you expect to happen?
I expect to download the rebatesme cashback add-on button for firefox, so that next time when I shop, it make my life easier.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
If that site is pointing you to a page on addons.mozilla.org that is no longer available, it means either the developer took the add-on down or the add-on was taken down due to code review issues. Either way, you need to contact the add-on developer for information about this.
