### ISSUE TITLE
Internal server error when logging in addons.mozilla.org

### ISSUE THREAD

**Issue by mystiquewolf** [mozilla/addons#1225]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Trying to login to addons.mozilla.org gives Internal server error
### What happened?
Cannot login because of "Internal server error"
### What did you expect to happen?
Expected to login
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![image](https://user-images.githubusercontent.com/16529989/89717623-08eeba80-d9c1-11ea-893d-1b915b20ee88.png)

**Comment by willdurand** [comment]
The API throws an internal server error because it found multiple users for the same email address according to Stackdriver.

**Comment by mystiquewolf** [comment]
@willdurand Is it going to be fixed eventually? Is there anything i can do?

**Comment by eviljeff** [comment]
email amo-admins@mozilla.com with details of the account/email address and someone will work with you to fix the accounts.
