### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by nschloe** [mozilla/addons#1229]
I just wanted to submit an updated version of [Green Pi](https://github.com/nschloe/green-pi), really only a dependency update. Unfortunately, I'm now getting a validation error.

> Error: Validation was unable to complete successfully due to an unexpected error.

[green-pi.zip](https://github.com/mozilla/addons/files/5129655/green-pi.zip)

The addon is listed here:
https://addons.mozilla.org/en-US/firefox/addon/green-pi/

> * The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/upload/5ca9b531312541e8b86d39ae30131d5c

> * The approximate time you submitted the add-on, with timezone.

Just now, i.e., 2020-08-26, 2pm CET.

**Comment by wagnerand** [comment]
Thank you for the report, we are looking into it.

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/9469386/events/ed65b44a63fd498fbf462f507eb86276/

/cc @smarnach @eviljeff

**Comment by wagnerand** [comment]
@nschloe Could you try again, please?

**Comment by nschloe** [comment]
It works now, thank you.
