### ISSUE TITLE
Your add-on failed validation and could not be signed

### ISSUE THREAD

**Issue by noorulhussain** [mozilla/addons#1230]
* **Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.**
This is an existing extension
Error I got :
**Your add-on failed validation and could not be signed
FAIL
o: The extension could not be signed
    at /usr/local/lib/node_modules/web-ext/dist/webpack:/src/cmd/sign.js:141:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)**

* Whether your add-on is listed or unlisted.
***https://addons.mozilla.org/en-US/developers/upload/e5ae99282c8d4bab9799304e1dbb4cc6**

* The approximate time you submitted the add-on, with timezone.*
August 3.30PM to 4.30 PM(IST)

**Comment by wagnerand** [comment]
@noorulhussain Thanks for the report. Can you try again, please?

**Comment by noorulhussain** [comment]
@wagnerand  Thank you so much. Seems its works fine now. May I know the root cause of the issue? Is something is required from our side to prevent this issue in nearby future.

**Comment by wagnerand** [comment]
There was an internal issue and no special actions need to be taken from your side.
