### ISSUE TITLE
Intermittent addon validation error on XPIs containing very large JavaScript files

### ISSUE THREAD

**Issue by thomasguillory** [mozilla/addons#1231]
Hi there,

I'm working at Dashlane where we have been editing a Firefox add-on (self-hosted, unlisted) for a few years now. We are running run into issues when signing our extension (`web-ext sign`) as the AMO validator is giving us this error

```
Sorry, we couldn't load your WebExtension.

Error: Validation was unable to complete successfully due to an unexpected error.

Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU
```
https://addons.mozilla.org/en-US/developers/upload/c0d99eef3cfb4bb09d6115282a830b07

We tested our extension locally with `web-ext lint --self-hosted` and it came back with 0 errors.

We tried to sign several times today (August 26th) between 4.30pm and 5pm CEST, same error everytime.

**Comment by jvillalobos** [comment]
We had temporary outage earlier today which should be fixed now. Please try submitting again and let us know if the problem persists.

**Comment by thomasguillory** [comment]
Hi @jvillalobos, thanks for your quick answer. Unfortunately, the error is still happening today August 27th around 10.45am CEST :/

**Comment by jvillalobos** [comment]
I see one version that came through today correctly (Version 6.2035.0). Can you confirm? We're investigating the error.

**Comment by thomasguillory** [comment]
It did, after several tries, I confirm. Thanks for investigating!

**Comment by thomasguillory** [comment]
Hello @jvillalobos,

We are still experimenting the same issue on this week version. Any news on your side?

**Comment by diox** [comment]
Could you attach the failing file in this issue, if it's not a problem for it to be public ?

**Comment by thomasguillory** [comment]
Hi @diox,
Thanks for your quick reply. No problem to give your the file for which `web-ext sign` is failing:
[firefox.zip](https://github.com/mozilla/addons/files/5151026/firefox.zip)

**Comment by diox** [comment]
(Sentry traceback: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/9351575/?query=is%3Aunresolved)

So, at first glance it appears that one of our (private) scanners is having trouble processing this file in a timely manner, and that's causing the failure - we're recently made the switch to consider all such failures as fatal, to ensure the safety of our users. I'll need to dig into the logs more to figure the actual source of the error, but I suspect it's because of one of the big minified javascript files in the package.

**Comment by denishowew** [comment]
Our https://github.com/mozilla/addons/issues/1232 also involves large JS files (one is 3MB) but that doesn't explain why validation fails intermittently on exactly the same set of files.

**Comment by thomasguillory** [comment]
Hi @jvillalobos @diox,

It seems that the "Intermittent" addon validation error is becoming a permanent error. We've done 20 attempt this morning to sign our extension and the it's been failing systematically. Is there any chance to raise the priority of this issue higher?

**Comment by diox** [comment]
Sorry for not getting back to this issue sooner. Although extremely large JavaScript files are always something we'd recommend developers to avoid, we believe the recent intermittent failures were caused mostly by network issues, and we have mitigations being deployed later today in our weekly push (around 18:00 CEST).

**Comment by thomasguillory** [comment]
@diox Thanks for your fast response. It doesn't seem better yet, but we will retry in 24h
For reference if you need to investigate, here are the results of the last signing attempt: https://addons.mozilla.org/en-US/developers/upload/44b4f2e152294dcf98922398f3dd97e9

**Comment by diox** [comment]
Have you seen this again since ?

**Comment by thomasguillory** [comment]
@diox Thanks for checking in. We managed to sign our extension 6 days ago and didn't have to do it again yet, so I can't tell if it's more stable now.

**Comment by diox** [comment]
Ok. I'm keeping this issue opened for now, please comment if you see it again. Hopefully our mitigations will hold until we can implement a more robust fix - we do have some medium-term plans to address one of the causes of this problem, but I don't know when that'll happen yet.
