### ISSUE TITLE
Prime Video

### ISSUE THREAD

**Issue by silentbill200** [mozilla/addons#1233]
### Describe the problem and steps to reproduce it: Widevine Content Decryption Module not available on Firefox and can't install it.  Tried to download and it failed.  
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
This repository is for the Add-ons website. For Firefox help, please visit our [support center](https://support.mozilla.org). If you can't find help there, please [file a bug here](https://bugzilla.mozilla.org/).
