### ISSUE TITLE
Not Found api search page has unclosed link html tag

### ISSUE THREAD

**Issue by theultramage** [mozilla/addons#1234]
XML Parsing Error: mismatched tag. Expected: </link>.
    Location: https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/whatever
    Line Number 20, Column 125:

    <noscript><link rel="stylesheet" href="https://addons.cdn.mozilla.net/static/css/legacy/nojs.css?b=11c6f27b-5f352a8a"></noscript>

That 'link' tag is missing a closing slash. The ones right above it have it. Even though the page doesn't declare itself as a proper xml document, the firefox addon checking code assumes so. The easiest solution would be to fix this one small detail.

**Comment by muffinresearch** [comment]
@theultramage - thanks for the report. Can you explain in more detail how you are getting to this 404 page? What is the "firefox addon checking code" that you're referencing?

**Comment by theultramage** [comment]
Setting 'browser.selfsupport.url' contains that path and is used at startup for heartbeat. I was checking the console for addon loading issues, that's how I noticed it by accident. Several other 'extensions.getAddons.' settings also have that path.
