### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by Akiv1965** [mozilla/addons#1235]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
The extension (Fases Lunares) has approved and published however  I install it and it doesn't load the images.

### What happened?
I don't know but when I try it in about:debbugin It works correctly. I don't know if the error is mine or yours.
### What did you expect to happen?
I expected  it worked. :-)
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

What I see.
![Sin título](https://user-images.githubusercontent.com/45926470/91677556-5afba980-eb43-11ea-97dd-e82a0476daf1.png)

What I'd must see.
![capturaFases3Blog](https://user-images.githubusercontent.com/45926470/91677585-78307800-eb43-11ea-963a-4e25da8b9503.png)

At the moment the extension isn't public
https://addons.mozilla.org/es/firefox/addon/fases-lunares/

**Comment by jvillalobos** [comment]
This repository is for the add-ons website, not for developer support. For help, you can start here: https://extensionworkshop.com/

**Comment by Akiv1965** [comment]
Sorry if I had done wrong, but I'm not asking for developer support, I'm 
asking why the approved and published extension dosen't work when I 
install it from add-ons website. The extension works fine in local mode 
and Chrome. For this reason I think the problem is in the  add-ons website.

Anyway, sorry one more time if I am doing anything wrong. I am a newbie 
and my english is ver very bad... How you can see... :-)

Sorry again and thank you.

**Comment by jvillalobos** [comment]
I suggest you download the signed XPI and try that locally. It sounds like you may have a problem related to packaging. In any case, that's most likely a developer support issue and not a website issue.

**Comment by Akiv1965** [comment]
still doesn't work and I don't know why. I'm going crazy.
  Thank you anyway for your help.
