### ISSUE TITLE
ATN screenshots are too small

### ISSUE THREAD

**Issue by marcoagpinto** [mozilla/addons#1236]
I have updated the screenshots of Proofing Tool GUI in
AMO:
https://addons.mozilla.org/addon/british-english-dictionary-2

ATN:
https://addons.thunderbird.net/addon/british-english-dictionary-2

ATN displays a tiny image of the screenshots.

Can't it be improved to show in a full screen like AMO does?

Thanks!

**Comment by diox** [comment]
Hi,

Please file addons.thunderbird.net issues at https://github.com/thundernest/addons-server/issues/new - it's a completely separate project now, handled by different people. Thanks.
