### ISSUE TITLE
No error message is rendered when adding a new add-on author fails

### ISSUE THREAD

**Issue by Steven-Wagner** [mozilla/addons#1238]
### Describe the problem and steps to reproduce it:
When an author is viewing an add-on using the developer hub and is on the "manage authors and license" page and attempts to add a new author, if it fails, a red triangle appears indicating an error, but no error message is rendered.

Reproduce:
1. Navigate to the developer hub and view a published add-on
2. Go to the "manage authors and license" page
3. In the input under "authors pending confirmation" add an invalid email that should cause an error
4. Click "save changes"

### What happened?
A red triangle appears on the input but there is no error message rendered to describe the reason for the error.

### What did you expect to happen?
A red triangle to appear along with a message that describes the error and how I can fix the situation.

### Anything else we should know?
If I inspect the input element it seems that the error message might be included in the title attribute. For me, the title attribute is `title="no user with that email"`
<img width="1919" alt="Screen Shot 2020-09-11 at 2 16 27 PM" src="https://user-images.githubusercontent.com/45648168/92969070-75822c80-f439-11ea-91c5-99774bb68969.png">

**Comment by diox** [comment]
I agree it's not optimal UX, but if you hover the red triangle the title should be displayed.

**Comment by hugolpz** [comment]
My remote coworker gave me `developer` role 22 hours ago but still nothing to see on my side. 
According to my coworker he was able :
- to add my email address 
- to see my correct addon.mozilla.org's 6-digit user ID.
After doing this, my remote co-worker left for few days. 
It's ok for us, but this confusing situation makes an opportunity for improvement.

The UI in your screenshot shows 
> Authors pending confirmation

But what does this means ? 
What is this process ? 
Is there a review delay ? 
Should I look for an email ? 
For an invitation ribbon ? 
Get automatically added ?
Clarification please !
