### ISSUE TITLE
Link to french dictionary is broken

### ISSUE THREAD

**Issue by RobSiklos** [mozilla/addons#124]
On [this page](https://addons.mozilla.org/en-US/firefox/language-tools/), the link to "Install Dictionary" for French points here: https://addons.mozilla.org/en-US/firefox/addon/dictionnaires-fran%C3%A7ais/

Unfortunately, when I go to that page, I get a "Not Found" error.

This worked a few days ago.

**Comment by jvillalobos** [comment]
Dupe of https://github.com/mozilla/addons-server/issues/2823
