### ISSUE TITLE
Feature request: Add an email subscription to the update in the add-ons collection

### ISSUE THREAD

**Issue by deevroman** [mozilla/addons#1241]
I keep an eye on a few large sets of extensions and each time I manually check for new additions. It would be convenient to subscribe to update the collections by email.

**Comment by jvillalobos** [comment]
We don't intend to implement messaging features for end users like the one you suggested, so I'm closing this issue.

One way to keep track of add-on updates is to use the [AMO API](https://addons-server.readthedocs.io/en/latest/index.html) to monitor the extensions you're interested in. You could probably use the collections API too, to decide which add-ons to check. This of course would require coding the solution yourself, but I don't expect us to implement something like this.

**Comment by deevroman** [comment]
AMO API, wow!
