### ISSUE TITLE
Unlisted extension stuck in "awaiting approval"

### ISSUE THREAD

**Issue by Valodim** [mozilla/addons#1242]
Hey folks, :wave:

### Describe the problem and steps to reproduce it:

We ran into an issue with uploading and signing our unlisted, self-deployed extension:

> web-ext sign --source-dir build --channel "unlisted" --artifacts-dir dist/firefox --id "firefox@heylogin.com"

### What happened?

The command uploads the extension, and receives a validation report, but then times out. On AMO the version is listed as "Awaiting Review", which hasn't changed in several days now. This happened consistently in a couple of attempts, including one with the exact same code submitted that was auto-approved before.

### What did you expect to happen?

This command produced a signed xpi within ~5 minutes from an automatic validation. This worked well for several months.

### Anything else we should know?

This command was being called as part of our CI pipeline, sometimes up to a couple of times per day. The `web-ext sign` documentation included no specifics about whether that's a legitimate use, using it in this way worked for several months without issues for us.

I don't know if this is a rate limiting issue or not, but it would be good to include a paragraph about the expected use of the API so developers can use it with confidence that they are not overstepping some unknown boundaries.

**Comment by wagnerand** [comment]
Sorry about, it should be fixed now.
