### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by CookiBytes** [mozilla/addons#1243]
Hi,

I was uploading a to-do extension to Firefox, and an error occured:

[This](https://github.com/CookiBytes/fuse) is my project I'm trying to upload.

The error happened after the upload of my build.crx file. It said:

```
Invalid or corrupt add-on file.

Error: Validation was unable to complete successfully due to an unexpected error.

Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your web extension is valid or file a bug at http://bit.ly/1POrYYU
```

I submitted the add-on [here.](https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed)

This happened at **10:34 PM**, _AEST_.

Help is very much appreciated,
- C.B

**Comment by CookiBytes** [comment]
Can someone help me please? I still have this problem. I can't zip my React project up as it won't allow me to, and the .crx file still gives me the error.

**Comment by AlexandraMoga** [comment]
We are aware that some `.crx` archives might trigger a validation error and we have an issue opened to track this problem- see https://github.com/mozilla/addons-server/issues/14036

**Comment by CookiBytes** [comment]
Okay, thanks @AlexandraMoga!

**Comment by CookiBytes** [comment]
@AlexandraMoga I tried downloading the zip from my repository and then uploaded it on the same place again. It gave me six errors and two warnings.

> **❌ manifest.json was not found**

> Error: No manifest.json was found at the root of the extension. The package file must be a ZIP of the extension's files themselves, not of the containing directory. See: https://mzl.la/2r2McKv for more on packaging.

> **❌ JavaScript syntax error**

> Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
fuse-master/src/index.js line 1 column 1

> ** ❌ JavaScript syntax error**

> Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
fuse-master/src/components/Form.js line 1 column 1

> **❌ JavaScript syntax error**

> Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
fuse-master/src/App.js line 1 column 1

> **❌ JavaScript syntax error**

> Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
fuse-master/src/components/TodoList.js line 1 column 1

> **❌ JavaScript syntax error**

> Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
fuse-master/src/components/Todo.js line 1 column 1

> **⚠ Unsafe assignment to innerHTML**

> Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
fuse-master/build/static/js/2.1364e5ae.chunk.js line 2 column 23161

> **⚠ Unsafe assignment to innerHTML**

> Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
fuse-master/build/static/js/2.1364e5ae.chunk.js line 2 column 23184

**Comment by willdurand** [comment]
should be fixed by https://github.com/mozilla/addons-server/issues/15849
