### ISSUE TITLE
n(d).white.fresh theme preview is wrong or is being poorly generated

### ISSUE THREAD

**Issue by perrocochino666** [mozilla/addons#1244]
### Describe the problem and steps to reproduce it:
Preview of https://addons.thunderbird.net/es/thunderbird/addon/nd-white-fresh/?src=cb-dl-created is wrong

### What happened?
![image](https://user-images.githubusercontent.com/63485080/93915919-56ec2300-fcce-11ea-9fb4-f76f26f8eeab.png)

### What did you expect to happen?
This is Theme in Thunderbird
![image](https://user-images.githubusercontent.com/63485080/93915995-76834b80-fcce-11ea-92e2-f06af11a4347.png)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Please file addons.thunderbird.net issues over at https://github.com/thundernest/addons-server/issues/new, thanks.

**Comment by perrocochino666** [comment]
Thank you, I have just done it
