### ISSUE TITLE
Review section. Notification on review/reply edit or adding new comments.

### ISSUE THREAD

**Issue by RomanistHere** [mozilla/addons#1245]
Let's talk about https://addons.mozilla.org/

Sometimes you face the situation when user give you feedback, you (as a developer) get email notification about it, reply to it and that's it.

But sometimes you are having a discussion. And it's not friendly at all. You can't reply to a comment. You can only edit your old reply. And it gives us the two problems:
- you have no notifications about it;
- you can't understand what is going on there because of the structure;

I'm sure it's easy to refactor - it will be tremendous bonus to the website.

Thank you and have a nice day:)

**Comment by jvillalobos** [comment]
The review section is not meant for discussions. We've intentionally avoided adding more threading or notification features for that reason. If you need to follow up on a review I suggest that you use the reply function to point the user to the right feedback channels you have available for this.
