### ISSUE TITLE
Facebook Container and MAC are not shown as "Recommended" in AMO, but they should be/were

### ISSUE THREAD

**Issue by Fanolian** [mozilla/addons#1246]
### Describe the problem and steps to reproduce it:
[Firefox Multi-Account Containers by Mozilla Firefox](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)    
[Facebook Container by Mozilla Firefox](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/)

Steps to reproduce:
1. Visit the above links.
2. Install the extensions.
3. Go to `about:addons`.
4. Compare the Recommendation info between their AMO pages and `about:addons`.

### What happened?
AMO and `about:addons` show conflicting info.
The above extensions were both recommended extensions iirc. Now they are neither "Recommended" nor "By Firefox" in AMO.    
In `about:addons` they still have the little trophy icons next to their names when installed, and they are still recommended as "recommended extensions".

I suspect AMO is in the wrong here since they should be both Recommended, or at least they are made by Firefox, unless something major regarding the extensions has changed.
On the other hand if the info shown in Firefox is wrong/outdated, I can file a bug in BMO (but I don't know which component I should file the bug in.)

### What did you expect to happen?
Both AMO and `about:addons` should show consistent information.

### Anything else we should know?
Screenshot showing the issue: (I didn't install Facebook Container so as to show the issue in the "recommended extensions" section.)
![Recommended extensions](https://user-images.githubusercontent.com/771216/94375014-1ca5da00-0143-11eb-83f2-a3c85d206af7.png)

Web Archive shows that they were both Recommended about a week ago:
https://web.archive.org/web/20200922074517/https://addons.mozilla.org/en-US/firefox/addon/facebook-container/
https://web.archive.org/web/20200923092527/https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

And I saved the current state of AMO:
https://web.archive.org/web/20200927204841/https://addons.mozilla.org/en-US/firefox/addon/facebook-container/
https://web.archive.org/web/20200927205616/https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

**Comment by jvillalobos** [comment]
We're making some changes in badging on AMO, and that's the reason they weren't showing one. MAC now has the By Firefox badge, and Facebook Container will do the same soon. A new version needs to be uploaded for the changes to fully apply, so we're coordinating with the owners to have this done quickly.

**Comment by maxxcrawford** [comment]
New versions for both add-ons have been submitted and MAC is already updated. 

- FBC ([v2.1.2](https://github.com/mozilla/contain-facebook/releases/tag/2.1.2))
- MAC ([v7.1.0](https://github.com/mozilla/multi-account-containers/releases/tag/7.1.0))

---



![image](https://user-images.githubusercontent.com/2692333/94463805-25b69b80-0183-11eb-962f-eadffbc33c87.png)

**Comment by Fanolian** [comment]
> 
> 
> New versions for both add-ons have been submitted and MAC is already updated.
> 
>     * FBC ([v2.1.2](https://github.com/mozilla/contain-facebook/releases/tag/2.1.2))
> 
>     * MAC ([v7.1.0](https://github.com/mozilla/multi-account-containers/releases/tag/7.1.0))

Thank you. Now I see the new By Firefox badge in `about:addons`.
