### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by noorulhussain** [mozilla/addons#1247]
Please attach a copy of your add-on, and fill in the following information:
[Response] The compressed file size is more than 10 mb. Please advise how to upload

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

[ Response] New Addon

* Whether your add-on is listed or unlisted.

[ Response] Unlisted

* The URL where you submitted the add-on.
[Response] https://addons.mozilla.org/en-US/developers/upload/54606288b69b446a8e0a89838af2c331#general-tests
* The approximate time you submitted the add-on, with timezone.
[Response] Sep 28, 2020. 2.55 PM IST

**Comment by NiharRanjanBisaria** [comment]
Please address this issue at the earliest.Also please explain the issue why it is hapnning

**Comment by diox** [comment]
Extremely large file size are difficult and costly for our linter and scanners to parse, not to mention browsers. The limit is currently at 4MB. See also https://github.com/mozilla/addons/issues/1237

**Comment by NiharRanjanBisaria** [comment]
by 4MB do you mean uncompressed package size or the compressed?.

**Comment by noorulhussain** [comment]
@diox Is there any limit on number of js files and their sizes?
