### ISSUE TITLE
Download Statistics seem to have stopped working for my add-on on Sept 18th

### ISSUE THREAD

**Issue by st333v** [mozilla/addons#1248]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
The download graph goes down to zero from sept 18th 20202 onwards

### What did you expect to happen?
it definitely shouldn't be zero.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![image](https://user-images.githubusercontent.com/165368/94496957-b88c2000-01ed-11eb-9a66-42e463ff37cc.png)

**Comment by willdurand** [comment]
Hi, thanks for your report, which confirms the problem documented in https://github.com/mozilla/addons-server/issues/15560. We identified the issue and we're going to fix it.
