### ISSUE TITLE
Enhanced Tracking protection feature (ETP) - Firefox Beta 82.0b6

### ISSUE THREAD

**Issue by kartselv6** [mozilla/addons#1260]
### Describe the problem and steps to reproduce it:

We own an extension and when testing the extension in the upcoming new version Firefox Beta 82.0b6, one of our primary feature was broken in Enhanced Tracking protection feature (ETP) “standard” mode due to the storage access policy block . We need to change the ETP settings to “Custom” and Cookies setting to “Cookies from unvisited websites” for the feature to work.  We continued our testing in FireFox beta 82.0b8 and the feature is working in the “Standard” mode without changing the cookie setting.  At this point, we are not sure if this was a bug in Firefox Beta 82.0b6 that got fixed in FireFox beta 82.0b8. 

### What happened?
One of our primary customer facing feature in the extension broke in the  Firefox Beta 82.0b6

### What did you expect to happen?
The feature should work without any error.

### Anything else we should know?
![StandardMode_Error](https://user-images.githubusercontent.com/51381305/95408248-e9e2ab00-08d3-11eb-9fa9-5d0b3bc3a8b9.png)

(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
This repository is for the add-ons website, so we can't help you with this here. For developer help you can ask on our [Discourse forum](https://discourse.mozilla.org/c/add-ons) or the [Add-ons channel on Matrix](https://wiki.mozilla.org/Matrix#Specific_areas).
