### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by madhuramehendalewhatfix** [mozilla/addons#1271]
Please attach a copy of your add-on, and fill in the following information:

Error-

**The extension could not be signed
    at /usr/local/lib/node_modules/web-ext/dist/webpack:/src/cmd/sign.js:141:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)**

Validation Results-

https://addons.mozilla.org/en-US/developers/upload/815e7091deec4af19609d9c77a4f3b1b

* The approximate time you submitted the add-on, with timezone.
November 12:40AM (IST)

Link for the extension- https://drive.google.com/file/d/1rfskFZZ5JO0V9PZs9sBt3Fl-tTbmlOOX/view?usp=sharing

**Comment by NiharRanjanBisaria** [comment]
Same issue is happening with me as well since two months ,i am not getting any specific reason for failure in the validation results.
Can someone please provide the root cause for the issue.
