### ISSUE TITLE
Firefox sign request was throttled 

### ISSUE THREAD

**Issue by madhuramehendalewhatfix** [mozilla/addons#1272]
Any idea why the request for firefox adddon got throttled- 
Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/46787700-2693-11eb-94bf-2a8342861064-prod%40whatfix.com/versions/2020.11.14.1606/
status: 429
response: {"detail":"Request was throttled. Expected available in 18 seconds."}

at n.bind.then (/usr/local/lib/node_modules/web-ext/node_modules/sign-addon/dist/webpack:/src/amo-client.js:264:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

What's the exact limit on the number of requests in a time frame? Any other scenarios due to which it might be throttled.

**Comment by eviljeff** [comment]
there are a number of different throttle limits you might be hitting:
https://github.com/mozilla/addons-server/blob/master/src/olympia/signing/views.py#L79:L100
