### ISSUE TITLE
Unable to rate an add-on on AMO

### ISSUE THREAD

**Issue by Signe-19** [mozilla/addons#1276]
Hi there,
Each time I try to rate and give feedback on an add-on, I just hit a wall.
First I get to the add-on page, then I log in since I see no button offering me to rate the extension, and then I see that logging in doesn't bring any sort of benefits in the form of a button allowing me to rate and comment on the add-on. What do I have to do to get a very simple right that everyone else seems to have?
I'm very happy to try again and post screenshots when I'm told what and where to look for.
Thanks in advance.
Signe

**Comment by bobsilverberg** [comment]
Hi Signe. Can you post a screenshot of the Add-On Detail page after you have signed in? It *should* look something like this, with the area surrounded with a red box being the spot where you would rate the add-on.

Note that the way to rate an add-on is to click on one of the stars, and that records the rating.

<img width="1385" alt="Screen Shot 2020-12-13 at 5 46 10 PM" src="https://user-images.githubusercontent.com/142755/102026351-629a3380-3d6b-11eb-9215-473cebdd253a.png">

**Comment by Signe-19** [comment]
Hi Bob,
Thanks for your message. I definitely don't get what you posted. This is what I get, ie no change from before I logged in. I even tried the stars I could see, but they're not the same as yours, obviously.

![AMO add-on rating](https://user-images.githubusercontent.com/74837618/102026609-1a950400-3d9f-11eb-907b-4a86afea86e2.jpg)

**Comment by bobsilverberg** [comment]
> Hi Bob,
> Thanks for your message. I definitely don't get what you posted. This is what I get, ie no change from before I logged in. I even tried the stars I could see, but they're not the same as yours, obviously.
> 

Hi again Signe. Your screenshot isn't of the add-on detail page, but rather the reviews page. Try clicking on the add-on's name in the box above the yellow stars, where it says "Auto Tab Discard". That will take you to the details page, which should look like my screenshot above, and from there you can click on a star to record your review.

**Comment by Signe-19** [comment]
OK thanks Bob, got it, and it works.
But, the thing is,, the add-on itself redirected me to the reviews page, I had no particular reason to doubt that the page was relevant, especially since it's the ratngs page, it would have made sense to enter a rating on the ratings page... Couldn't the developer be made aware of this flaw in his add-on? Unless Mozilla decides to change the page on which ratings are entered, but i guess that would be considered an unneeded extra-click.
Thanks anyway.

**Comment by bobsilverberg** [comment]
Hi Signe. I'm glad you got it working. Yes, it seems less than ideal for the developer to link to the reviews page as opposed to the add-on detail page. Perhaps you would like to inform them of that?

**Comment by jvillalobos** [comment]
Signe might be referring to the link in about:addons that says "XX Reviews", which points to the reviews page.

**Comment by Signe-19** [comment]
Hi Julia,
Thanks for your input. I was actually referring to a link that's on a settings page of the add-on, this page appears once you hit the add-on button in the address bar.
