### ISSUE TITLE
Yahoo home page on Firefox 

### ISSUE THREAD

**Issue by jrm271** [mozilla/addons#1280]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Yahoo keeps asking to set itself as the homepage on FF even though its already the home page
### What did you expect to happen?
It wont ask to be set as homepage since already set as homepage
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
This repository is only for the add-ons website. For help with Firefox, please visit https://support.mozilla.org
