### ISSUE TITLE
Dictionary keeps changing to US

### ISSUE THREAD

**Issue by efAston** [mozilla/addons#1286]
I've noticed that the spellcheck dictionary on Firefox keeps changing to US English. I'd like to be able to remove the US English dictionary so this can't happen, but there's no option for it (even though UK English is the selected language and not US English). 

Using Mozilla for Ubuntu Version 78.0.2 (64-bit) on Kubuntu

**Comment by jvillalobos** [comment]
This repository is for the Mozilla Add-ons website. This sounds like a bug in Firefox, so [please file it here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Add-ons+Manager).
