### ISSUE TITLE
Problem with server location

### ISSUE THREAD

**Issue by BeBop4000** [mozilla/addons#1287]
#1174 ## Describe the problem and steps to reproduce it:
(PlI ease include as many details as possible.) I am a resident of Cold Spring, New York, U.S.A. 

### Anything else we should know? I would like you to explain what is going on here, and how can I over-ride or change completely, my location (New York, USA)  from "International (Singapore, I think). Is there a server I can attach to near me on the East Coast of the USA? preferable New York?
(Please include a link to the page, screenshots and any relevant files.)https://spectrum.pch.com/Path/VIPSmartExit/Start.aspx?tid=05301e49-1bc0-4b46-9198-ac0959a9f1ee&utm_source=05301e49-1bc0-4b46-9198-ac0959a9f1ee&utm_medium=20200504&utm_campaign=20TR2060&e=B2F33C00-B3BA-4A8D-A5E4-F902515795E2&edid=EXP258905|2021-01-28T09&tp=i-1NGB-8l-15Lt-QVpuxd-1r-2gPsQM-1c-Q7FFtc-l5deRiHfvd-1tYRI&emh=6C156AA223EAD05F75071444650CFDD644AEA650F966CC88EDFEFC872EA9BBA7&sc=OBP2X&submeta=PCHCOM    Thank You. Gregory Bochow
                                                      Cold Spring, NY 10516  USA

**Comment by eviljeff** [comment]
Hi, 
what you're describing sounds like a problem with a VPN or proxy (or your ISP).  It's possible it's something add-on related - have you installed any add-ons recently?

**Comment by BeBop4000** [comment]
Thank you for your prompt response. No Add Ons recently, but a new VPN has appeared as a pop up that I am using, which could be the source of the problem. Thanks again for your response ! NOW PUT THAT MASK ON, DAMMIT !!

Gregory W. Bochow
 

    On Thursday, January 28, 2021, 1:16:23 PM EST, Andrew Williamson <notifications@github.com> wrote:  
 
 


Hi,
what you're describing sounds like a problem with a VPN or proxy (or your ISP). It's possible it's something add-on related - have you installed any add-ons recently?
