### ISSUE TITLE
Search Secure Pro

### ISSUE THREAD

**Issue by latack** [mozilla/addons#1288]
### Describe the problem and steps to reproduce it:When I do a search, instead of going to Google this page "Search Secure Pro pops up & I get a Yahoo search page
(Please include as many details as possible.)

### Anything else we should know?I found another path to "extensions" also produced a blank page.
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
I forgot to follow up here. We don't know what add-on exactly your report is about, but we took action on some related add-ons. If the add-on is still active for you, can you please provide the exact add-on ID? You can find it by visiting about:support in Firefox. Thank you.
