### ISSUE TITLE
Previos session not restored!

### ISSUE THREAD

**Issue by Daveteauk** [mozilla/addons#1289]
### Describe the problem and steps to reproduce it: 
Following a PC crash/freeze, I turned off the PC, and once it booted back up I was given a completely new Firefox window, and all my c30 tabs, plus my important 'Pinned tabs' too, which I can't duplicate, were gone! It's, the freeze, has happened before, but this Firefox not restoring problem didn't.
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
FF v85.0
W10 v20H2 build 19042.746

**Comment by jvillalobos** [comment]
This repository is for the Mozilla Add-ons website. Please visit https://support.mozilla.org/ for Firefox help.
