### ISSUE TITLE
Installing a theme triggers warning banners

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons#129]
- Click on the install switch for a theme. It downloads and "installs."
- A warning banner appears and will not show the theme until the user clicks "Allow":
<img width="1147" alt="screen shot 2016-06-03 at 8 00 34 am" src="https://cloud.githubusercontent.com/assets/6797635/15783010/45a42434-2961-11e6-8e29-0114974f312c.png">
- Turning off the theme via the switch triggers this warning (and "Undo" doesn't do anything):
<img width="1138" alt="screen shot 2016-06-03 at 8 01 31 am" src="https://cloud.githubusercontent.com/assets/6797635/15783057/739e611a-2961-11e6-9c19-23d4ea463aad.png">

Ideally, these banners would not appear at all on Disco Pane. This is a safe place where warnings don't appear!

**Comment by muffinresearch** [comment]
This would be better filed in addons frontend.

In any case this is because you don't have the xpinstall permission - I'm add some instructions how to fix it on the wiki page.

**Comment by muffinresearch** [comment]
Short answer is: add an exception in about:preferences#security
