### ISSUE TITLE
Investigate reducing JavaScript bundle size

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1298]
Since we do Server Side Rendering and our JavaScript bundle is at the bottom of the pages, its size doesn't seem to have a huge negative impact on Core Web Vitals, but still, reducing that size would help performance in general - make the site more reactive for things that do depend on client-side JavaScript. So let's look at what we can do.

**Comment by diox** [comment]
Duplicate of https://github.com/mozilla/addons-frontend/issues/6192

**Comment by eviljeff** [comment]
closing as dupe rather than transferring to addons-frontend
