### ISSUE TITLE
API data is outdated by weeks (overeager caching?)

### ISSUE THREAD

**Issue by palant** [mozilla/addons#13]
Please have a look at these URLs:

https://services.addons.mozilla.org/en-US/firefox/api/1/addon/adblock-plus
https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/adblock-plus

If you are logged in on AMO these will correctly show Adblock Plus 2.7 as the latest version. In Private Browsing mode (or when requested by `wget`) these will currently claim that Adblock Plus 2.6.13 is the latest release. Indeed, the second link will claim that Adblock Plus 2.6.12.4060-beta is the latest version in the beta channel - yet it has been superseded by version 2.6.13.4079-beta on November 30.

This seems to be a case of overeager caching, the data hasn't been updated in weeks.

**Comment by andymckay** [comment]
Thanks for the report, we found an issue with cache invalidation at the SAMO endpoint. Our tests now show that these are reporting version 2.7 and users should get the new updates.

**Comment by palant** [comment]
Confirmed, our consumer is working correctly now.
