### ISSUE TITLE
Addon Validation Error When Using Numeric Seperators

### ISSUE THREAD

**Issue by michaelts1** [mozilla/addons#1301]
When I am trying to upload an addon that contains numeric separators, I get the following error:
>**Sorry, we couldn't load your WebExtension.
Error**: Validation was unable to complete successfully due to an unexpected error.

I expect my addon to validate, since numeric separators are supported since [addons-linter version 2.17.0](https://github.com/mozilla/addons-linter/releases/tag/2.17.0)

#

>Please attach a copy of your add-on, and fill in the following information:

>* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

This error happens when I am trying to submit a new addon 

>* Whether your add-on is listed or unlisted.

Unlisted

>* The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted

>* The approximate time you submitted the add-on, with timezone.

10:36 AM, GMT+2

#

### More Information
It seems this error is caused by using numeric separators. To test this, I uploaded a minimal addon with only manifest and one js file.
I tried to upload this addon two times:
* Without numeric separators (test.js only contains the following line: `10`): [noSeparator.zip](https://github.com/mozilla/addons/files/6121489/noSeparator.zip)
* With numeric separators (test.js only contains the following line: `1_0`): [Separator.zip](https://github.com/mozilla/addons/files/6121490/Separator.zip)

The error only happens when I am trying to upload the addon with numeric separators.
Furthermore, running both `addons-linter ./` and `web-ext lint` return no errors at all for both versions of the addon (with and without numeric separators).

**Comment by diox** [comment]
Looks like an issue on our side, yeah. Likely https://sentry.prod.mozaws.net/operations/olympia-prod/issues/10378322/

**Comment by willdurand** [comment]
This should be fixed now, sorry!
