### ISSUE TITLE
The email address used in your account is not accepted for sending extensions.

### ISSUE THREAD

**Issue by yuriteixeiraa** [mozilla/addons#1307]
### Describe the problem and steps to reproduce it: f
I tried to send an extension to AMO and immediately upon accepting the terms this message appeared, and it is not possible to send:

The email address used in your account is not accepted for sending extensions.
### What happened?
Whenever I try to send an extension it says that my email is not accepted for sending extensions.
### What did you expect to happen?
I should be able to send an extension to AMO with email from gmail.
![Screenshot_13](https://user-images.githubusercontent.com/81858909/113477147-57702e00-9456-11eb-81df-97538e372a9d.png)

**Comment by diox** [comment]
Hi,

You'll need to contact amo-admins@mozilla.org with the email in question.

**Comment by yuriteixeiraa** [comment]
> Hi,
> 
> You'll need to contact [amo-admins@mozilla.org](mailto:amo-admins@mozilla.org) with the email in question.

they don't respond, I sent an email several and several days ago.
