### ISSUE TITLE
https://addons.mozilla.org/firefox/addon/docs-online-viewer/ does not show Permissions

### ISSUE THREAD

**Issue by def00111** [mozilla/addons#1308]
### What happened?
See bug title.

### What did you expect to happen?
The page should show the **Permissions**.

### Anything else we should know?
On the **Link Alert** [page](https://addons.mozilla.org/en-US/firefox/addon/link-alert/) it will show the **Permissions**:
![firefox_Rl0D2KVosA](https://user-images.githubusercontent.com/10849366/113508357-dbf2a780-954f-11eb-801e-8c3cadf1990d.png)

How it looks like on **Docs Online Viewer** [page](https://addons.mozilla.org/en-US/firefox/addon/docs-online-viewer/):
![firefox_QPgCTboLoO](https://user-images.githubusercontent.com/10849366/113508671-98993880-9551-11eb-95fa-d2af0eb95dd7.png)

Here is the **manifest.json** of **Docs Online Viewer**:
```
{
  "name": "Docs Online Viewer",
  "version": "5.5.5",
  "manifest_version": 2,
  "description": "Open documents and files online directly in your browser using online services like Google Docs Viewer, etc.",
  "homepage_url": "http://www.deekshith.in/p/docs-online-viewer.html",
  "icons": {
    "32": "images/brand/dov-brand-32.png",
    "48": "images/brand/dov-brand-48.png",
    "64": "images/brand/dov-brand-64.png"
  },
  "applications": {
    "gecko": {
      "id": "{bfb54675-2fd9-4e22-949d-c36333aff6b5}"
    }
  },
  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "exclude_matches": ["*://*/*.pdf",
                          "*://*.facebook.com/*",
                          "*://www.messenger.com/*",
                          "*://mail.google.com/*",
                          "*://docs.google.com/*",
                          "*://www.mediafire.com/*"],
      "js": ["js/content/insert-link-icons.js"]
    }
  ],
  "web_accessible_resources": [
    "images/beside-link-icon.png",
    "images/beside-link-icon.svg"
  ],
  "permissions": [
    "storage"
  ],
  "default_locale": "en"
}
```

And for **Link Alert**:
```
{
 "manifest_version": 2,
 "name": "Link Alert",
 "version": "2.0.1",
 "author": "Conlan Wesson",
 "homepage_url": "https://www.cwesson.net/projects/LinkAlert/",
 "default_locale": "en",
 "description": "Changes the cursor to indicate the target of a link.",
 "icons": {
  "48": "icons/linkalert-32.png"
 },
 "content_scripts": [
  {
   "matches": ["<all_urls>"],
   "js": ["src/defaults.js", "src/linkalert.js", "src/mousebox.js"],
   "run_at": "document_start"
  }
 ],
 "options_ui": {
  "page": "src/options.html"
 },
 "permissions": ["storage"],
 "web_accessible_resources": [
  "icons/small/*-icon.png",
  "icons/large/*-icon.png",
  "icons/none-icon.png"
 ]
}
```

**Comment by diox** [comment]
This looks like a server-side issue, the API isn't returning `<all_urls>` for `Docs Online Viewer` (`storage` is ignored but that's expected):
```
 curl -s https://addons.mozilla.org/api/v4/addons/addon/docs-online-viewer/ | jq '.current_version.files[0] | .permissions'
[
  "storage"
]
```

The add-on hasn't been updated in years so maybe the initial permissions extraction somehow missed that one.

**Comment by bobsilverberg** [comment]
There was a task we ran to extract these permissions, and it was verified, but I guess we should check to make sure it didn't ignore `<all_urls>` for all extensions (and that this is just some kind of fluke).
