### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by Wuemeli** [mozilla/addons#1310]
Please attach a copy of your add-on, and fill in the following information:
[textures.zip](https://github.com/mozilla/addons/files/6262364/textures.zip)

They say: "Sorry, we couldn't load your WebExtension.

**Comment by willdurand** [comment]
Hi, we have identified an issue on our servers, which prevents the submission process to complete. We are working on fixing it. Sorry.

**Comment by diox** [comment]
@Wuemeli this should be fixed now, can you please try again ?

**Comment by Wuemeli** [comment]
yes it worked now thank you
