### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by adam-roth** [mozilla/addons#1312]
> Please attach a copy of your add-on

[pb-comments-plugin-firefox-0.8.14.zip](https://github.com/mozilla/addons/files/6262599/pb-comments-plugin-firefox-0.8.14.zip)

> Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

New version.  Also tried reuploading previous version, which received the same error.

The change for the new version is literally a one-liner (and a version bump).

> Whether your add-on is listed or unlisted.

Listed/approved.

> The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/addon/pb-comments-plugin/versions/submit/

> The approximate time you submitted the add-on, with timezone.

4:30pm AEST

**Comment by willdurand** [comment]
Hi, we have identified an issue on our servers, which prevents the submission process to complete. We are working on fixing it. Sorry.

**Comment by diox** [comment]
@adam-roth this should be fixed now, can you please try again ?

**Comment by adam-roth** [comment]
@diox Fix confirmed.  All good now. 👍
