### ISSUE TITLE
Addon Validation Error - Revert Site

### ISSUE THREAD

**Issue by st333v** [mozilla/addons#1313]
addon zip file: [12.0.zip](https://github.com/mozilla/addons/files/6262628/12.0.zip)

The error occured when updating an existing extension.

The addon is listed at https://addons.mozilla.org/en-US/developers/addon/revert-site/

Addon submitted via https://addons.mozilla.org/en-US/developers/addon/95fd811acb4d4517bbc1/versions/submit/

Approx time 7.35am GMT

**Comment by willdurand** [comment]
Hi, we have identified an issue on our servers, which prevents the submission process. We are working on fixing it. Sorry.

**Comment by diox** [comment]
@st333v this should be fixed now, can you please try again ?

**Comment by st333v** [comment]
Yes it submitted when i tried it this time, and has been published, thanks very much! :)
