### ISSUE TITLE
Self-assigned addon is stuck at "Awaiting Review" status.

### ISSUE THREAD

**Issue by quinguyenhuu** [mozilla/addons#1314]
### Describe the problem and steps to reproduce it:
I uploaded a new version of my addon last 2 days, and waited one day to get approved, but It was still in "Awaiting Review" status. So i deleted the uploaded one and uploaded a new one, but It still has been in "Awaiting Review" status. Can someone please check and help me? Thank you.

url: https://addons.mozilla.org/en-US/developers/addon/ef051963de3d491b8572/versions

### What happened?
My new version is stuck at "Awaiting Review" status.

### What did you expect to happen?
Please help to get my new version got approved.

### Anything else we should know?
<img width="793" alt="image" src="https://user-images.githubusercontent.com/9970827/113824976-a0074e80-97aa-11eb-901c-6263d29c035e.png">

**Comment by wagnerand** [comment]
You should have received an email explaining that approval can take longer sometimes. We will take a look soon.

**Comment by quinguyenhuu** [comment]
> You should have received an email explaining that approval can take longer sometimes. We will take a look soon.

Please check again my reply. Thank you.

**Comment by quinguyenhuu** [comment]
Can you please check again? I uploaded new version. Thank you.

**Comment by diox** [comment]
Please don't use GitHub issues for discussions and checking up with reviewers, as this notifies a bunch of people that have nothing to do with this conversation.
