### ISSUE TITLE
Can't log in to AMO if I decline required 2FA enrollment; no explanation given

### ISSUE THREAD

**Issue by timmc** [mozilla/addons#1319]
When I try to log in to a developer account that hasn't had 2FA enabled, and I decline enrollment, I am dumped back out of the login flow with no explanation.

Original issue:

I can't log in -- I get as far as entering my password, and then I am prompted to enroll a second factor. I don't want to, so I click "cancel setup", and I am returned to AMO -- but not signed in.

This is my first time in a while trying to log in, and I first had to enter a code from my email account. So I do think my account is recognized.

I'm on Firefox 78.9.0esr.

**Comment by diox** [comment]
Hi,

Are you an extension developer ? Add-on developers have to enroll for 2FA as part of our efforts to improve security. You can read more about that on https://blog.mozilla.org/addons/2021/03/11/two-factor-authentication-required-for-extension-developers/ - all developers should also have received an email about it.

**Comment by timmc** [comment]
Hmm! That does work.

I believe that once upon a time I _tried_ to sign up for a developer account, but was refused for some reason having to do with my IP address being untrusted. But maybe my account got marked as a developer account?

OK, so change of scope on this issue, then: The login fails with no explanation, dumping me out of the flow.
