### ISSUE TITLE
I can not load it normally in China

### ISSUE THREAD

**Issue by BHznJNs** [mozilla/addons#1320]
In this page: https://addons.mozilla.org/zh-CN/developers/addon/submit/agreement.
The reCAPTCHA identifying code uses resourse from Google which can not be loaded in China.

**Comment by jvillalobos** [comment]
Related: https://github.com/mozilla/addons-server/issues/13389

**Comment by BHznJNs** [comment]
> 相关： [mozilla / addons-server＃13389 ](https://github.com/mozilla/addons-server/issues/13389)

Thanks!
