### ISSUE TITLE
Addon "New Tab Homepage" disabled, responses to review comments ignored

### ISSUE THREAD

**Issue by benbasson** [mozilla/addons#1321]
### Describe the problem and steps to reproduce it:
I am the author of the add-on New Tab Homepage. It loads your homepage when you open a new tab. I've had to rework the code over the years, but it's been around since 2004 and has no additional functionality that isn't described in the add-on name and single sentence description.

This add-on is no longer available for use because someone disabled it in a drive-by review. I did not upload a new version or request a review.

### What happened?
This add-on has now been disabled for doing the exact thing it says it's going to do, and apparently there is no way to appeal or challenge this because my comments to the review are being ignored (which begs the question why authors can even add a reply).

The review comment is:
> Add-ons must not load or redirect to a remote new tab page. The new tab page must be contained within the add-on.

I understand that Mozilla has a duty to protect against homepage hijacking, but seriously.

1. This add-on could not have been clearer about what's going to happen if you install it.
2. It directs to the user's chosen homepage, not some arbitrary page. You can see that from the code.
3. Plenty of add-ons let users customise the New Tab behaviour to arbitrary URLs, but seemingly aren't disabled, so is this a policy violation or isn't it?

Nobody raised that there would be any concerns doing what I'm doing when the functionality to do it was added to WebExtensions in https://bugzilla.mozilla.org/show_bug.cgi?id=1234150 and Mike Kaply suggested redirecting within add-on code as a workable way forward for authors.

### What did you expect to happen?
For starters it would have been nice to be contacted before the add-on was disabled out of courtesy, to see if there is a resolution.

At the very least I would have hoped replying to the review comment would get a response.

### Anything else we should know?
I'm also unable to read reviews/see statistics while the add-on is disabled, which is pretty sad. Is there no way to extract that data?

**Comment by wagnerand** [comment]
Hi Ben,

Apologies for the delay on this. We just reached out to you via the reviewer tools which should have triggered an email. Please check your inbox if you haven't seen it already.
