### ISSUE TITLE
Wrong review date after submitting review to https://addons.mozilla.org/en-US/firefox/addon/…

### ISSUE THREAD

**Issue by arnotixe** [mozilla/addons#1322]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I just submitted a review+fix hint for a deprecated api in an extension https://addons.mozilla.org/en-US/firefox/addon/currency-converter-ff/reviews/

### What happened?
The date says "submitted a year ago"

### What did you expect to happen?
The date should likely say "submitted seconds ago" or the like

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
well https://addons.mozilla.org/en-US/firefox/addon/currency-converter-ff/reviews/
I used Firefox 88.0.1 64 bit on linux to do this, but strongly suspect the review date isn't browser supplied, right? Anyways, my system clock really is not a year ago, it is ntp synced  ;)
![image](https://user-images.githubusercontent.com/500938/118909426-9b28d500-b8e8-11eb-8142-d9b957ffee6c.png)

**Comment by diox** [comment]
What happened is that you already rated that add-on a year ago, probably without posting text - just a score. When you posted your recent review, because we only allow one rating per user, it automatically edited the existing one, adding your new comment to it.

So technically not a bug, everything working as intended, except that we might want to make the UI clearer, to explain what will happen in scenarios like these.

**Comment by bobsilverberg** [comment]
> What happened is that you already rated that add-on a year ago, probably without posting text - just a score. When you posted your recent review, because we only allow one rating per user, it automatically edited the existing one, adding your new comment to it.
> 
> So technically not a bug, everything working as intended, except that we might want to make the UI clearer, to explain what will happen in scenarios like these.

While this might be expected based on the current code, mightn't it make sense to also update the date posted when updating a rating?

**Comment by diox** [comment]
IMHO `created` date should immutable. Maybe we could expose the modified date instead, I'm not sure...

**Comment by arnotixe** [comment]
Aah he he

**Comment by bobsilverberg** [comment]
> IMHO `created` date should immutable. Maybe we could expose the modified date instead, I'm not sure...

I agree that we shouldn't change `created` date, but it seems that we should be using the `modified` date for this instead. 

@jvillalobos What are your thoughts?

**Comment by jvillalobos** [comment]
Using `modified` sounds reasonable but:
1) Could it be abused to make your review always appear on top by regularly making changes to it?
2) If, to mitigate (1), we use `modified` for display and `created` for sorting, would that even be more confusing?

Makes me think this isn't worth fixing...
