### ISSUE TITLE
Error reaching addon install page

### ISSUE THREAD

**Issue by pplcunha** [mozilla/addons#1324]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I tried to follow a link to install firefox shareaholic addon.
### What happened?
It seems that at addons.mozzilla.com it encounters a 404 error, but only display a message that something went wrong.
### What did you expect to happen?
A page with the download/install instructions for a firefox shareaholic extension.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/firefox/downloads/addon-5457-latest.xpi?src=external-website_hp_ff
![Screenshot_2021-06-01 Não encontrado](https://user-images.githubusercontent.com/71928601/120364471-a9f98980-c2e3-11eb-8e8d-64caeb706b7c.png)
![Screenshot_2021-06-01 Não encontrado](https://user-images.githubusercontent.com/71928601/120364673-eb8a3480-c2e3-11eb-8264-93496d690237.png)

**Comment by eviljeff** [comment]
You should contact shareaholic to find out the status of their add-on.   I see the screenshots on their website are _very_ old, so maybe they just stopped developing it?
