### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by mohsin429** [mozilla/addons#1325]
I am getting Addon Validation Error as failed to load WebExtension, Please help with the details.

Below is an attached copy of Addon zip
[842b7860-83b6-11eb-8dc7-32b5f385aed9.zip](https://github.com/mozilla/addons/files/6601309/842b7860-83b6-11eb-8dc7-32b5f385aed9.zip)

* Below error occurred during submission of a new version of existing extension. This occurred twice for the extension.
![image](https://user-images.githubusercontent.com/19505481/120864882-96337900-c5aa-11eb-947a-9b4cf7c8b930.png)

https://addons.mozilla.org/en-US/developers/upload/912604f33ce2451499705df30a316413

* Approximate time of submission of addon is 2:19 AM IST(Indian Standard time)

**Comment by willdurand** [comment]
Hi, sorry about that.

We noticed a few errors from one of our components and just updated it. You should be able to submit your add-on now.
