### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by danfinlay** [mozilla/addons#1328]
[metamask-firefox-9.6.1.zip](https://github.com/mozilla/addons/files/6665267/metamask-firefox-9.6.1.zip)

During update of our [listed](https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/) add-on, [submitting on this page](https://addons.mozilla.org/en-US/developers/addon/ether-metamask/versions/submit/), about 5 minutes ago, I got this error:

```
Sorry, we couldn't load your WebExtension.

Error: Validation was unable to complete successfully due to an unexpected error.

Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU
```

I think I had this the last time I tried to submit, but on re-submit it then passed, so it seemed intermittent. I suspect if I submit a few more times this will pass. Could this be the fault of our own tests being non-deterministic?

**Comment by diox** [comment]
Hi,

We don't run your tests automatically. The culprit for this kind of error is often large & complex JavaScript files that our scanners can sometimes have trouble with. You have several of them above 1 MB, so I suspect that's the issue.

**Comment by danfinlay** [comment]
Yup, 5th try was the charm this time. We'll work to split up our files longer term.
