### ISSUE TITLE
Add-on Fully Reviewed Russian Message - "Your дополнение, NAME, has been fully reviewed"

### ISSUE THREAD

**Issue by Druzion** [mozilla/addons#133]
2 days after submitting a new version of my add-on, I received an email saying this:
> Your дополнение, _Add-on Name_, has been fully reviewed.....

Normally, as you can guess, it says this:
> Your add-on, _Add-on Name_, has been fully reviewed.....

This word seems to be [Russian for add-on / addition](https://translate.google.co.uk/#auto/en/%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5)

This has never happened before, and the language for everything related to Mozilla is all English (I am not Russian, nor do I speak Russian). The only this different was I had a new reviewer who had never reviewed my add-on before, _Exclumice_. Maybe if his / her language is set to Russian, this affects the automated email?

**Comment by diox** [comment]
Yes, this is the issue. I actually fixed this bug in Marketplace 3 years ago : https://github.com/mozilla/zamboni/commit/f43430d781f0ea8e1aec534ea0d8141996eabe29

Olympia still has the issue: https://github.com/mozilla/addons-server/blob/5dfe2f756e08812b67fa3b544ddd19fa83f20dff/src/olympia/editors/helpers.py#L721

The code is very similar and the same fix should work.
