### ISSUE TITLE
Missing changelog input on French version submitting page

### ISSUE THREAD

**Issue by Kapcash** [mozilla/addons#1333]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

When submitting a new addon version, on the second step, we should be able to fill in a text input to provide the changelog of the version.
This field is not displayed anymore. Only the field for the module tester is available.

The route of the page is: https://addons.mozilla.org/fr/developers/addon/:addonName/versions/submit/:id/details

<img width="844" alt="Screenshot 2021-06-20 at 18 19 47" src="https://user-images.githubusercontent.com/10612835/122681392-6d3ef500-d1f4-11eb-8991-d0d51981de91.png">

See how the section "Author notes" is almost empty. I remember it has a text field before.

The section "Testers notes" correctly has its text field.

### What happened?

The text field for version changelog isn't displayed.
Only reproducible on the French page (/fr). On (/en-US it works).

### What did you expect to happen?

I expect to have a text field on this page to provide the version changelog.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Hi,

This is a known bug, a consequence of https://github.com/mozilla/addons-server/issues/7535, that is unfortunately tricky to fix correctly with our translation engine. We should probably keep this one opened separately to handle the devhub side of this bug, for which we have some possible workarounds...

**Comment by AlexandraMoga** [comment]
We had an issue for the DevHub part opened for a while (closed as stale sadly). The STR are relevant still - https://github.com/mozilla/addons-server/issues/4599

**Comment by Kapcash** [comment]
I'm closing this issue since it's a duplicate of the previously mentionned issued which has been reopened. I'll follow further discussions there!

Good luck with this bug!

-------

Note: By the time I opened this issue, I didn't know it was possible to edit the changelog description after submitting a version.  
I'm glad some workarounds exists for this issue. I mention them here in case someone needs it:
- moving to the `en-US` page to enable the text field while submitting the version
- editing afterward the changelog by going to https://addons.mozilla.org/en-US/developers/addon/:addon-name/versions and click on the version to update
