### ISSUE TITLE
Broken link on submitting version page

### ISSUE THREAD

**Issue by Kapcash** [mozilla/addons#1334]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Go on any page for the route : https://addons.mozilla.org/fr/developers/addon/:addonName/versions/submit/:id/details
On the footer, click on link "report a bug".
The page we land on is a "404 Page not Found" error.

Reproducible for any language of the page.

### What happened?

The link leads to a Page Not Found error page.
Url: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Contact

### What did you expect to happen?

Going to the correct url: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
This has already been reported as https://github.com/mozilla/addons-server/issues/16884
