### ISSUE TITLE
Getting request was throttled , please try again later in 26175 seconds

### ISSUE THREAD

**Issue by NiharRanjanBisaria** [mozilla/addons#1336]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
While sending, addons for signing using web-ext we are getting error response , request was throttled try again in 26175 seconds.
This we are seeing recently.
What is the root cause of the issue.? and what is the limit if any, how many addons can be signed per account within a given timeframe range.
### What did you expect to happen?
Adodn should get signed

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Your request was throttled because we detected too many submissions from your IP or user in a given time period. The response gives you an estimate of when you should be able to try again.
