### ISSUE TITLE
Custom License does not show to users

### ISSUE THREAD

**Issue by saucettv** [mozilla/addons#1337]
### Describe the problem and steps to reproduce it:
Add a custom license via Manage Authors & Licence. Set title and text, save it.

### What happened?
Custom license is not shown on custom license page, example:
https://addons.mozilla.org/en-US/firefox/addon/ad-free-but-480p-for-twitch/license/

### What did you expect to happen?
Custom license text and name should show.

### Anything else we should know?
Checked the API call in the network log and it appears that the API returns null for name and text of the custom license.
The custom license does show in the Manage Authors & Licence page.

**Comment by AlexandraMoga** [comment]
Looks like you've added a custom license while your locale was set to `en-GB`. Looking at the page in `en-GB` the license is visible - https://addons.mozilla.org/en-GB/firefox/addon/ad-free-but-480p-for-twitch/license/, but when you switch to a different locale (like `en-US`), the contents are not returned.

This is an issue we are aware of and it's tracked in https://github.com/mozilla/addons-server/issues/9963.
