### ISSUE TITLE
Can't install Emoji Everywhere

### ISSUE THREAD

**Issue by Rudloff** [mozilla/addons#134]
Hello,

When I try to install [Emoji Everywhere](https://addons.mozilla.org/fr/firefox/addon/emoji-everywhere/) 0.1.1, I get the following error in the console:
```
1465217126536	addons.xpi	WARN	Download of https://addons.mozilla.org/firefox/downloads/file/381188/emoji_everywhere-0.1.1-fx.xpi?src=dp-btn-primary failed: Downloaded file hash (ba034d5d93e0377faf2ff393550c0b0c873796a1b1f4f78d428044801ce3f94e) did not match provided hash (240e06bf24fe94a17123d47235d10b7f9473089e5d1f705e84816f83507cefd6)
```

I can reproduce with Iceweasel 38.8.0 and Firefox 46.0.1.

**Comment by wagnerand** [comment]
I just approved version 0.1.2. you submitted today. That version installs fine.

0.1.1 suffers from an edge-case bug is which very hard to fix if it's not the latest version. Also, that condition significantly reduces the impact. Especially as 0.1.1 and 0.1.2 are basically identical.
