### ISSUE TITLE
I cannot reach the theme I made, and download it

### ISSUE THREAD

**Issue by Pio55** [mozilla/addons#1342]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I received this email by mozilla:

**_Hi there,

Your add-on, Calm Green, has passed our automatic tests. Version 1.0 is now signed and ready for you to download at https://addons.mozilla.org/developers/addon/2711927/versions . Note that you need to be logged in as a developer of the add-on before downloading.

-- 
Mozilla Add-ons Team
https://addons.mozilla.org_**

### What happened?

When I click on the link in the email, I come to the page:

https://addons.mozilla.org/en-US/developers/addon/ad59d9356f67469b878c/versions

where I'm told:

__
  We're sorry, but we can't find what you're looking for.
  The page or file you requested wasn't found on our site. It's possible 
  that you clicked a link that's out of date, or typed in the address incorrectly.
    If you typed in the address, please double check the spelling.
    If you followed a link from somewhere, please file an issue. 
   Tell us where you came from and what you were looking for, and we'll do our best to fix it.
    Or you can just jump over to some of the popular pages on our website.
    Are you interested in a list of featured add-ons?
    Do you want to search for add-ons? You may go to the search page or just use the search field above.
    If you prefer to start over, just go to the add-ons front page.
__

### What did you expect to happen?

I would expect I could download my own theme.

### Anything else we should know?

I tried to click on the link, after logging in my Firefox account; but nothing changes.

(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
The page looks correct to me. Are you sure you're logging in with the same account you used to upload the file? What do you see if you go to https://addons.mozilla.org/developers/ ?
