### ISSUE TITLE
Cannot list > 1000 page on addons.mozilla.org 

### ISSUE THREAD

**Issue by Uzivatel919** [mozilla/addons#1343]
### Description
There is technical issue upon try to open page 1001 or higher on https://addons.mozilla.org/en-US/firefox/search/?sort=users&type=statictheme.

There is claimed to be 475,052 themes divided onto 19,003 pages.

Example:
https://addons.mozilla.org/en-US/firefox/search/?sort=users&type=statictheme&page=1000 ✔
https://addons.mozilla.org/en-US/firefox/search/?sort=users&type=statictheme&page=1001 ❌

### What happened?

I hit some dead end when I tried to open page 1001.

![1001](https://user-images.githubusercontent.com/26486200/125208290-d4027c00-e291-11eb-888f-5e21fd49e7a0.png)

### What did you expect to happen?
I got 1001ˢᵗ page.

**Comment by diox** [comment]
That's done on purpose (searches that far are expensive for us), though we have an issue opened to prevent the pagination from going that far (https://github.com/mozilla/addons-frontend/issues/10689).
