### ISSUE TITLE
only recommended add-ons?

### ISSUE THREAD

**Issue by Nemesis77swe** [mozilla/addons#1345]
Hi!
when pressing add-ons in the menu of Firefox, I'm directed to "recommended" add-ons, but it seems impossible to list them all?
(https://addons.mozilla.org/en-US/android/)
there is no link for the rest, (at least when browsing from my Android 6) or is it only those?

**Comment by tbertels** [comment]
> You can see all add-ons available for Android at https://addons.mozilla.org/en-US/android/search/, which shows more than the home page you listed, but it is true that there are a limited number of add-ons available on Android right now.

This page shows exactly the same extensions as in Firefox  add-ons menu.

It doesn't show https://addons.mozilla.org/en-US/android/addon/traduzir-paginas-web/ (TWP - Translate Web Pages) between others also compatible with Firefox for Android and [installable on Nigthly thanks to Collections](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/).

There should be a way to show all Firefox for Android extensions on the website, even the non recommended ones.

By the way, where can we suggest new extensions to be added to recommended ones?
