### ISSUE TITLE
Exact matches are listed below 'recommended' matches in search

### ISSUE THREAD

**Issue by bwoodruff** [mozilla/addons#1346]
### Describe the problem and steps to reproduce it:

Do a search for "1Password - Password Manager": https://addons.mozilla.org/en-US/firefox/search/?q=1Password%20-%20Password%20Manager

### What happened?

![202107298l0Sbcul](https://user-images.githubusercontent.com/553522/127534619-956559d9-a93f-4c53-8920-b49dd8de2a16.png)

1Password is listed 5th...

### What did you expect to happen?

There is an exact match... an extension called "1Password - Password Manager." It should be at the top of the list.

### Anything else we should know?

Would also be great to have 1Password be a recommended extension, since it seems to meet all the criteria listed: https://support.mozilla.org/en-US/kb/add-on-badges?utm_content=promoted-addon-badge&utm_medium=referral&utm_source=addons.mozilla.org, but that's a separate issue.

**Comment by diox** [comment]
> There is an exact match... an extension called "1Password - Password Manager." It should be at the top of the list.

We boost recommended add-ons on purpose (precisely because we recommend them over extensions that we are not monitoring as closely, given our limited resources).

> Would also be great to have 1Password be a recommended extension, since it seems to meet all the criteria listed: https://support.mozilla.org/en-US/kb/add-on-badges?utm_content=promoted-addon-badge&utm_medium=referral&utm_source=addons.mozilla.org, but that's a separate issue.

AFAIK it doesn't: there is no free version available for everyone anymore so it no longer matches the `Is the extension relevant to a general, international audience?` criteria.

**Comment by diox** [comment]
Adding to that: we do boost exact matches higher than recommended. If you search for "1Password – Password Manager" with the same hyphen character they used in their name, it will be on top. It would also be on top of the name was just "1Password" and you searched for exactly that.

**Comment by bwoodruff** [comment]
My opinion only, of course, but I'd say this is a stretch on that rule:

> there is no free version available for everyone anymore so it no longer matches the Is the extension relevant to a general, international audience? 

Software has to be free (as in beer?) in order to be relevant to a general, international audience? 🤔 

> Adding to that: we do boost exact matches higher than recommended. If you search for "1Password – Password Manager" with the same hyphen character they used in their name, it will be on top. It would also be on top of the name was just "1Password" and you searched for exactly that.

Ah, thank you! That is helpful.

**Comment by diox** [comment]
> Software has to be free (as in beer?) in order to be relevant to a general, international audience? 

Arguing the fine points of our policy is not my area of expertise, nor is it relevant for a bugtracker. You can head over to [discourse](https://discourse.mozilla.org/c/add-ons/35) if you want to discuss that further.

Note that there used to be a free 1Password version, and that add-on used to be recommended.
