### ISSUE TITLE
Add-on fails to install due to `signature verification failed`

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#135]
https://addons.mozilla.org/en-US/firefox/addon/fakespot-fake-amazon-reviews/ v0.2 which was approved on May 22, 2016, 2:25:59 PM UTC fails to install:

 1465230327244	addons.xpi	DEBUG	Download started for https://addons.mozilla.org/firefox/downloads/latest/fakespot-fake-amazon-reviews/addon-703766-latest.xpi?src=dp-btn-primary to file /Users/awagner/Library/Caches/TemporaryItems/tmp-k0e.xpi
1465230327249	addons.xpi	DEBUG	Download of https://addons.mozilla.org/firefox/downloads/latest/fakespot-fake-amazon-reviews/addon-703766-latest.xpi?src=dp-btn-primary completed.
1465230327265	addons.xpi	WARN	Download of https://addons.mozilla.org/firefox/downloads/latest/fakespot-fake-amazon-reviews/addon-703766-latest.xpi?src=dp-btn-primary failed: signature verification failed
1465230327272	addons.xpi	DEBUG	downloadFailed: removing temp file for https://addons.mozilla.org/firefox/downloads/latest/fakespot-fake-amazon-reviews/addon-703766-latest.xpi?src=dp-btn-primary
1465230327272	addons.xpi	DEBUG	removeTemporaryFile: https://addons.mozilla.org/firefox/downloads/latest/fakespot-fake-amazon-reviews/addon-703766-latest.xpi?src=dp-btn-primary removing temp file /Users/awagner/Library/Caches/TemporaryItems/tmp-k0e.xpi

The files does contain signature files though.

Could we investigate why this happened?

**Comment by andymckay** [comment]
So if the file contains signatures and is valid, is the problem in Firefox or in AMO?

**Comment by wagnerand** [comment]
I don't know if the signature is valid, as I currently lack the environment to check that. All I'm saying is that the signature files are there.

**Comment by andymckay-limited-access** [comment]
I think this might be a problem in Firefox and annoyingly needs moving to
bugzilla in add-ons manager and attaching the signed add-ons, if you've
still got them.

**Comment by wagnerand** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1278295.

**Comment by eviljeff** [comment]
copied from bugzilla comment: add-on ID on amo is `contact@fakespot.com` but `@fakespot` in the install.rdf so we're signing with the wrong key.  
The dev should upload a new version with contact@fakespot as the guid, or we can change AMO (up to them really).

**Comment by andymckay** [comment]
This add-on has both a manifest.json and install.rdf, with differing ids:

```
  ff $ cat install.rdf | grep fakespot
          <em:id>@fakespot</em:id>
  ff $ cat manifest.json | grep fakespot
      "id": "contact@fakespot.com",
```

This now fails with "Both install_rdf and manifest.json found" which is a change made in another bug somewhere.

**Comment by wagnerand** [comment]
https://www.youtube.com/watch?v=GI5kwSap9Ug

**Comment by wagnerand** [comment]
Confirmed on master:
![screen shot 2016-06-07 at 14 00 38](https://cloud.githubusercontent.com/assets/873258/15856813/4f5d1c6a-2cb8-11e6-8065-4c5b04583937.png)
