### ISSUE TITLE
NoScript causes Access Denied error on certain web sites

### ISSUE THREAD

**Issue by drbuggolo** [mozilla/addons#1351]
### Describe the problem and steps to reproduce it:
1. Enable NoScript
2. Visit e.g. https://www.autozone.com or https://www.oreillyauto.com
3. Page loads correctly without JavaScript
4. Left-click on NoScript icon and select "set all on this page to temporarily trusted"

### What happened?

On reload, usually but not always, Firefox throws the following error:

Access Denied
You don't have permission to access "http://www.autozone.com/" on this server.
Reference #...

Note: This also happens if I select "disable restrictions globally" instead.

### What did you expect to happen?

Page should reload with JavaScript enabled.

### Anything else we should know?

Firefox 91.0 64-bit
Ubuntu 20.04.2
NoScript 11.2.11

This occasionally happens with NoScript disabled, but NoScript makes it worse.

The commonly solutions, such as using HTTPS instead of HTTP and clearing the cookies, do not work.

**Comment by diox** [comment]
Hi,

This issue tracker is to report bugs against addons.mozilla.org, not individual add-ons. We encourage you to file bug reports for a specific add-on through their own support channels - In the case of Noscript, they have a forum over at https://forums.informaction.com/viewforum.php?f=3.

If you think you've found a problem in Firefox itself, then head over to https://bugzilla.mozilla.org/ instead. Thank you.

**Comment by drbuggolo** [comment]
Oops! Thank you.
