### ISSUE TITLE
Addon Validation/SignIn Error

### ISSUE THREAD

**Issue by spadala8** [mozilla/addons#1355]
When we are trying to submit a addon for signing(self distribution) it is throwing error:

**The extension could not be signed\n    at /.nvm/versions/node/v12.18.2/lib/node_modules/web-ext/dist/web-ext.js:1:11642\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at R.execute (//.nvm/versions/node/v12.18.2/lib/node_modules/web-ext/dist/web-ext.js:1:64436)\n\n"**

**Comment by willdurand** [comment]
Could you provide more information please?

**Comment by spadala8** [comment]
@willdurand  we always upload addons as self-distribution using web-ext library in firefox
                web-ext sign --api-key=user:***:*** --api-secret=*********;
                   but after enabling two factor authentication which is mandatory for addon account our addons are not submitting for self-ditribution it is throwing error:
  **The extension could not be signed\n at /.nvm/versions/node/v12.18.2/lib/node_modules/web-ext/dist/web-ext.js:1:11642\n at processTicksAndRejections (internal/process/task_queues.js:97:5)\n at R.execute (//.nvm/versions/node/v12.18.2/lib/node_modules/web-ext/dist/web-ext.js:1:64436)\n\n**

**Comment by spadala8** [comment]
@willdurand  i tried to sign  it by disabling two factor authentication but it is throwing same error

**Comment by willdurand** [comment]
@spadala8 do you see anything in [DevHub](https://addons.mozilla.org/en-US/developers/)?

**Comment by spadala8** [comment]
@willdurand  No. But when we run our web-ext command we find our version uploaded in DevHub.This time it is not showing up

**Comment by spadala8** [comment]
@willdurand i can try again and let you know the exact time if you want

**Comment by diox** [comment]
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

* Whether your add-on is listed or unlisted.

* The URL where you submitted the add-on (if you tried submitting it from DevHub)

* The approximate time you submitted the add-on, with timezone.

**Comment by spadala8** [comment]
@diox 

Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
     **This error occured during submission of a new add-on**
Whether your add-on is listed or unlisted.
  **unlisted**
The approximate time you submitted the add-on, with timezone.
  **09/24/2021----10:30am CST 
  10/04.2021-9:20 am CST**

**Comment by diox** [comment]
Could you please attach a copy of your add-on ?

**Comment by spadala8** [comment]
@diox 
[bgas-1.0.0.1.zip](https://github.com/mozilla/addons/files/7279098/bgas-1.0.0.1.zip)

**Comment by spadala8** [comment]
@diox  please let me know when you download it i need to remove it because of security reasons

**Comment by diox** [comment]
I didn't find anything in your add-on that could trigger an error and I couldn't find anything in our logs either, but maybe I missed it. Please try submitting it via devhub, and see if it uploads and validates correctly.

**Comment by spadala8** [comment]
@diox  i tried that too when i am trying to upload through developerhub it says geckoid is not valid which is usually generated after addon is signed and xpi file is downloaded but i gave sample id and uploaded it and now it says no manifest.json found 
<img width="1128" alt="Screen Shot 2021-10-04 at 4 01 18 PM" src="https://user-images.githubusercontent.com/91715705/135924357-01b020e7-024d-4b5e-88bc-fdce202a167d.png">

**Comment by diox** [comment]
The zip you uploaded earlier had an empty string for the `id`, which is invalid. I'm assuming the new one you built wasn't generated properly in a different way if `manifest.json` wasn't found. In either case, it doesn't look like a bug on our side.

**Comment by spadala8** [comment]
@diox  actually we activated two factor authentication for our account after that we are facing the above error, before activation the same addon signed perfectly.

**Comment by diox** [comment]
Two Factor Auth has nothing to do with it. The fact of the matter the zip you shared is clearly invalid, and the error you pasted looks like a different issue, but also tied to the zip being built incorrectly. I encourage you to double-check your build, maybe validate it locally with `web-ext lint`.

To answer your other question, yes you can have both listed and unlisted add-ons in one account. You can also have unlisted and listed versions of the same add-on as well, you need to choose at upload time (this is also possible through `web-ext`).
