### ISSUE TITLE
Unable to access extension management page

### ISSUE THREAD

**Issue by IvanSop** [mozilla/addons#1356]
### Describe the problem and steps to reproduce it:
I want to access the page for extension management.

Prerequisites: Don't have 2 factor authentication enabled.

Steps:
1. Go to https://addons.mozilla.org/en-US/developers/
2. Click on 'Submit or manage extensions' blue button on top right.
3. Enter the username, then password
4. It asks me to set up 2 factor authentication with a QR code
5. Click on 'Cancel setup' (I don't want goddamn 2FA)
6. Get returned to https://addons.mozilla.org/en-US/developers/

### What happened?
I get redirected back to https://addons.mozilla.org/en-US/developers/ instead of proceeding to extension management page.

### What did you expect to happen?
I expected to be let through to developers console/extension management page instead being stuck on 2FA setup.

### Anything else we should know?
Screenshots will be included, to reproduce start from here
https://addons.mozilla.org/en-US/developers/

Start here:
![image](https://user-images.githubusercontent.com/8205518/135727900-3c9a324d-566c-4f2b-aebc-0a813892d30d.png)

Click on blue button 'Submit or manage extensions' to see the following
![image](https://user-images.githubusercontent.com/8205518/135727936-9ae62184-cf0e-4c62-811c-86bd1d5a8d2b.png)

Enter username, proceed to password
![image](https://user-images.githubusercontent.com/8205518/135727953-d90f50c6-bb09-4bd7-bbb3-5f9606bda6bc.png)

Enter password, and now the issue:
![image](https://user-images.githubusercontent.com/8205518/135727971-1b7e065e-02f7-413c-a181-a70c156d9c82.png)

If I click 'cancel' I will be returned to https://addons.mozilla.org/en-US/developers/
If I click 'Continue' it will show me this:
![image](https://user-images.githubusercontent.com/8205518/135728018-7fd113d5-27fb-4498-af32-0c31b315c911.png)

I don't want to install any 2FA apps and cancel is my only option ...

**Comment by caitmuenster** [comment]
Hi @ivansop, [2FA is required](https://blog.mozilla.org/addons/2021/03/11/two-factor-authentication-required-for-extension-developers/) for add-on developers to log into AMO. I understand that you don't want to install any 2FA apps; some password managers will provide 2FA services, and some will do it without requesting your phone number.
