### ISSUE TITLE
Add compatibility information

### ISSUE THREAD

**Issue by Kleisli** [mozilla/addons#1357]
### Describe the problem and steps to reproduce it:
When I want to install an add-on for firefox, I have no idea if it will work with the current version or not. Now, the add-ons often are outdated and do not work anymore.

### What did you expect to happen?
I expected an information, for what versions of firefox the add-on has been tested by the developer, like the add-on repository of Thunderbird has it already.

### Anything else we should know?
An example https://addons.thunderbird.net/de/thunderbird/addon/provider-for-google-calendar

**Comment by diox** [comment]
Do you have examples of add-ons that do not work in recent versions of Firefox ? This should be a rare exception rather than the norm - extensions backwards-compatibility is quite important to us.
