### ISSUE TITLE
Awesome Screenshot Plus not working under e10s

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#136]
There are multiple reports that Awesome Screenshot Plus doesn't actually work when you turn e10s on. If that's the case we probably shouldn't list it in the disco pane or get the developer to update it.

**Comment by muffinresearch** [comment]
Fwiw: I got this "as-ff:Error: cross-process JS call failed" and turning off e10s off made it work.

**Comment by devaneymoz** [comment]
What version of Awesome Screenshot has this issue? I see on its version history that 3.0.7 just released on June 7. Perhaps this is no longer an issue?

https://addons.mozilla.org/en-US/firefox/addon/awesome-screenshot-capture-/versions/?page=1#version-2.4.11

**Comment by muffinresearch** [comment]
I've just tried that on NIghtly 50.0a1 (2016-06-09) and it still doesn't work with e10s enabled but does start working when e10s is off.

**Comment by andymckay** [comment]
There's been some chat with the developers and there's been a new version that @shell15 and others have played with. I think its now passing and all is good, so closing. If that's not the case @shell15, can you re-open please?
