### ISSUE TITLE
Firefox extension got corrupted after signing

### ISSUE THREAD

**Issue by shirshak55** [mozilla/addons#1361]
I uploaded my dist file it works perfectly on about:debugging but trying to install same extension after signing shows some sort of corruption error?

My question:
1. Why can't i sign it myself like that of chromium? Why should I be in mercy for some firefox server? I am not distributing my extension to https://addons.mozilla.org/en-US/firefox/extensions/ so where is my freedom? 
2. It takes like 5mins to do trivial things and webext command frequently fails ... Why no simply follow chrome here and make it easy on developer drag and drop manifest folder and its good to go? 

When I google search I don't find any valid reason why signing extension is essential which are not even going to addons.mozilla.org? Why Mozilla even wants to waste their resource their hardware? 

I understand nightly might have some support but I don't want to update browser every night and stability might suck too.

I have no malign towards any firefox tools. Its just sad to see some degradation in firefox .

**Comment by willdurand** [comment]
Can you share which extension you're talking about? Which URL are you browsing when you click on a link to download it?

**Comment by willdurand** [comment]
> The url looks like this: [addons.mozilla.org/firefox/downloads/file/xxxxxxx/tmm-8-fx.xpi](https://addons.mozilla.org/firefox/downloads/file/xxxxxxx/tmm-8-fx.xpi) . After 2 hour it doesn't show corrupted. Idk what happened.

Are you saying this is working now?

**Comment by willdurand** [comment]
Great, thanks.
