### ISSUE TITLE
Unlisted extension stuck in "awaiting approval"

### ISSUE THREAD

**Issue by VDRY** [mozilla/addons#1362]
### Describe the problem and steps to reproduce it:

Problem like https://github.com/mozilla/addons/issues/1242#issue-705463240
add-on: kaspersky-protection-se

### What happened?

On AMO last several versions are listed as "Awaiting Review", which hasn't changed in more month.

**Comment by derjanb** [comment]
The same applies to [Tampermonkey's BETA version](https://addons.mozilla.org/en-US/developers/addon/5ff7ad16183743acbe23). 😔
3 versions are stuck since Sept. 27, 2021. Comments in the Review History didn't help.

**Comment by kewisch** [comment]
Hi folks. Your add-ons should be back to automatic approvals soon. Thanks for reaching out!

**Comment by derjanb** [comment]
It's working fine now again. Thanks.

**Comment by kewisch** [comment]
I'm not doing add-ons things these days, next time this happens please respond to the review email :)
