### ISSUE TITLE
FireFox Addon Site does not recognize Firefox Browser

### ISSUE THREAD

**Issue by 4saykin** [mozilla/addons#1363]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I have been using Firefox for many years and recently I started having trouble obtaining "Privacy Pass hCapture Passes" [I am still able to obtain the Cloudflare Passes].
I thought perhaps the problem would be resolved by reinstalling "Privacy Pass" but when I went to the "Privacy Pass" extensions/addons page I received a message directly above the addon link which stated:
        "You'll need Firefox to use this extension"
and in place of the "Add this extension to firefox" button there was a "Download Firefox" button.
I then checked all my other addon extensions and everyone of them told me the exact same thing.
For whatever reason all the addons in Firefox do not recognize the Firefox Browser.
According to the "About Firefox" banner my version of Firefox is: 94.0.1 (64-bit) and it states it is up to date.
I have tried to uninstall and reinstall Firefox and I still have the same problem but even made worse by the fact I cannot reinstall any of my usual addons.
I am currently using the portable version of Firefox version 94.0.1 (64-bit) as my portable version already has the addons I use installed (although the addons page still give the same message as the installed version of Firefox).
Is there a fix for this problem?
See below for Network Manager Results

### What happened?
The "Addon Site" did not recognize my Firefox browser.

### What did you expect to happen?
I expected to obtain addons for my browser.

### Anything else we should know?
I opened the Network Manager and obtained the following results:
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). search:2:1
Do Not Track is enabled browser.js:202:17
[GA] Do Not Track Enabled; Google Analytics not loaded and tracking disabled undefined browser.js:202:17
adding event listener for "onDisabled" browser.js:202:17
adding event listener for "onEnabled" browser.js:202:17
adding event listener for "onInstalling" browser.js:202:17
adding event listener for "onInstalled" browser.js:202:17
adding event listener for "onUninstalling" browser.js:202:17
adding event listener for "onUninstalled" browser.js:202:17
adding event listener for "onEnabling" browser.js:202:17
adding event listener for "onDisabling" browser.js:202:17
Global change event listeners have been initialized browser.js:202:17

**Comment by eviljeff** [comment]
@4saykin what is your "User Agent" from about:support?
