### ISSUE TITLE
    Received an empty response from the server; status: 504 while submitting extension

### ISSUE THREAD

**Issue by keinagae** [mozilla/addons#1366]
### Describe the problem and steps to reproduce it:
I am trying to submit new add-on on [here](https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed) but i am getting received empty response from server status 504.  

![image](https://user-images.githubusercontent.com/43607374/142438048-e9d4d169-98e3-4c2f-814e-f785dc91ef2b.png)

i have tried submitting on different times but error is still same

### What happened?
Unable to upload new addon
### What did you expect to happen?
be able to upload add-on
### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

**Comment by djpecot** [comment]
+1 also getting this issue

**Comment by keinagae** [comment]
Closing it as its working now but still getting Sorry, we couldn't load your WebExtension
