### ISSUE TITLE
Upload New Version + Validation Result in 504

### ISSUE THREAD

**Issue by djpecot** [mozilla/addons#1369]
### Describe the problem and steps to reproduce it:
While trying to validate or upload my extension to the Firefox, upload errors out with following message:
```
Your add-on failed validation with 1 error.
Received an empty response from the server; status: 504
```

Other Details:
- [Add-on is listed ](https://addons.mozilla.org/en-US/firefox/addon/inkah/)
- Validation URL [Submission link](https://addons.mozilla.org/en-US/developers/addon/validate)
- Uploads occur during working hours for UTC +8:00

### Full build attempt (30.2 MB) 
❌ Validate Add-on: 504
❌ Submit a New Version: 504

### Trimmed build attempt (28.9 MB)
✅ Validate Add-on: successful
❌ Submit a New Version: 504

### What happened?

Uploading full build to both the add-on validator and new version submission caused the upload to 504, as seen here: 
![image](https://user-images.githubusercontent.com/8185181/143148385-260cda48-5767-4b35-bcb9-4d1eaa71aca3.png)

### What did you expect to happen?
Successful upload for both validation and new version submission.

### Anything else we should know?
[Full version of build (30.2MB)](https://drive.google.com/file/d/1N9P0UkUnZohSY6moxdP54hA3rj2WvLxk/view?usp=sharing)
[Lite version of build (28.9MB)](https://drive.google.com/file/d/19x88pK8QLWREV0bsR8VmE9lRr1p6ilcF/view?usp=sharing)

**Comment by willdurand** [comment]
This looks a lot like: https://github.com/mozilla/addons-server/issues/18105, we're working on it.

**Comment by djpecot** [comment]
Cheers! I'll close to de-clog the issues feed.
