### ISSUE TITLE
2FA activation doesnt work

### ISSUE THREAD

**Issue by TonyFord** [mozilla/addons#1370]
### Describe the problem and steps to reproduce it:
2FA activation doesnt work!

### What happened?
I have scanned the 2FA qr code successfully in GoogleAuth or 2FAS Auth but the generated OTP is invalid. 
I also have entered the code string manually in the GoogleAuth but it also didn't work. 

### What did you expect to happen?
Normally scanning the qr code by popular 2FA apps should work.

**Comment by AlexandraMoga** [comment]
I was able to successfully enable 2FA on addons.mozilla.org by scanning the QR code with the Google Authenticator app on my phone. The code provided by the app was accepted in the 2FA validation form. 

Could you please try again?

**Comment by diox** [comment]
Hi, I suggest reporting that in https://github.com/mozilla/fxa as it's not handled by AMO directly.

**Comment by TonyFord** [comment]
My problem was that the systime of my computer was not synchronized ( ~1 minute earlier ).
I have enabled the sync and not it works.
