### ISSUE TITLE
Firefox web-ext sign api not giving response 

### ISSUE THREAD

**Issue by NiharRanjanBisaria** [mozilla/addons#1372]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
We are using web-ext sign --api-key=$API_KEY --api-secret=$API_SECRET to sign addons. But since last three days we are not getting any response from the api, it just keeps on running and when we again run the api it says 
**Server response: Version already exists. Latest version is: 2021.12.2.854.**

### What happened?
We Use web-ext to sign addons, but not getting and successful response first time when we call the api, it takes forever and second time when we try it says
**Server response: Version already exists. Latest version is: 2021.12.2.854.**
Also some times we see throttling error
status: 429
response: {"detail":"Request was throttled. Expected available in 55666 seconds."}

### What did you expect to happen?
Addons should be successfully signed.

We are also seeing this as well
![Screenshot from 2021-12-02 16-59-52](https://user-images.githubusercontent.com/42336052/144417557-26a6f638-f8f1-4b49-b30a-64f6485d2827.png)

**Comment by NiharRanjanBisaria** [comment]
Any update?

**Comment by AlexandraMoga** [comment]
Could you please attach a copy of the addon that you weren't able to sign?

**Comment by NiharRanjanBisaria** [comment]
The addons are still showing, Awaiting review in the Addons Developer Hub.

**Comment by AlexandraMoga** [comment]
I've managed to sign this extension with `web-ext sign` without any issues.  Could you try to sign it again, but be sure to increment the version number, otherwise you will run into the "Version already exists" error. 
Alternatively, have you tried to upload a new version in developer hub directly - https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted?

**Comment by NiharRanjanBisaria** [comment]
@AlexandraMoga thanks for the quick response 
i tried signing it again it with web-ext showed me this error 
![Screenshot from 2021-12-14 22-18-47](https://user-images.githubusercontent.com/42336052/146042445-bac86b0a-ee5a-4e9a-99d6-f4b8071b7079.png)
and in addons dashboard it is showing awaiting review
![Screenshot from 2021-12-14 22-18-42](https://user-images.githubusercontent.com/42336052/146042511-59066f86-b08d-48d2-84a7-2ed5311a5fdf.png)

is there anything to do with the api keys which we are using ?Any difference? Any settings which we have to change in our profile?

**Comment by AlexandraMoga** [comment]
Your API keys shouldn't be the problem. If they were, you would have received a 404 status from the server. 

Just a question: are you using the latest `web-ext` version? If not, could you try to upgrade it and see if the signing error still reproduces?

Also, as suggested in my previous comment,  have you tried to upload your addon version directly through the developer hub interface?

**Comment by NiharRanjanBisaria** [comment]
@AlexandraMoga  i updated the web-ext to latest version 6.60
after received this error
![Screenshot from 2021-12-15 22-59-04](https://user-images.githubusercontent.com/42336052/146235840-ec6d6dc4-7f50-4fe3-8518-d67b6405f5f2.png)

Also i have not tried uploading the addon to new version.

**Comment by NiharRanjanBisaria** [comment]
@AlexandraMoga Still facing same issue with web-ext please see the screenshot.
Also tried uploading directly to the developer portal but did not work it went in pending state and is not passing review.
We are not getting any reply also when we are adding comment in developer dashboard.This has a business impact as we our not able to update / create new extension for our customer.
Please have a look at this problem as soon as possible 
![Screenshot from 2022-03-03 12-51-01](https://user-images.githubusercontent.com/42336052/156530260-a32e6b1e-b833-4473-9fe7-bc9d21d592e2.png)
