### ISSUE TITLE
mouse-on-keyboard

### ISSUE THREAD

**Issue by duptabuser** [mozilla/addons#1374]
FIREFOX turns win10 mouse-on-keyboard's secondary button to be simultaneously primary, with precedence over the 2ary. [no problem with chrome and edge]
Specifically it is impossible to open a link in a new tab.
This is already some years old.
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
This doesn't seem to be problem specifically with the addons website, or other addons related services, so closing.  I suggest trying https://support.mozilla.org/
