### ISSUE TITLE
Preferred search engine has disappeared from Firefox addons.

### ISSUE THREAD

**Issue by dinahlee64** [mozilla/addons#1375]
My preferred search engine is GoodSearch (https://www.goodshop.com/search). It used to be included in the list of availables, but no longer is, nor can I seem to add it using the link from their page. (https://addons.mozilla.org/firefox/downloads/latest/goodsearch). What gives? It's certainly the one I want - WHY??? can't I get Firefox to recognize it???

**Comment by eviljeff** [comment]
I believe it's been blocked - https://addons.mozilla.org/firefox/blocked-addon/search@goodshop.com/ - you should contact GoodSearch for more details.
