### ISSUE TITLE
Constant error when trying to create a theme collection in Firefox Color

### ISSUE THREAD

**Issue by Conriocht** [mozilla/addons#1377]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
I've filled out the form (boxes) multiple times and receive the same error message over and over. I have no idea what's going on here, or what I'm missing.
### What did you expect to happen?
??
![firefox_theme_collection_error](https://user-images.githubusercontent.com/62991396/146651624-456975cc-e35e-4177-9131-e12b05dcd266.jpg)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
Hey @Conriocht we are aware of the issue and we already have a fix for it but, sadly, this will be available in production only next year - https://github.com/mozilla/addons-server/issues/18482.

In the meantime, if you want to be able to save your collection, please edit your Custom URL to not contain upper case letters, for example: "themes-by-mad-dog".

We apologize for the inconvenience.
