### ISSUE TITLE
activing a customized devtools pannel trigger another pennel create.

### ISSUE THREAD

**Issue by g8up** [mozilla/addons#1378]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
- load this demo: https://github.com/g8up/firefox-addon-issues
- open a web page, and `F12` open devtools
- click to pick panel `test`

### What happened?
another pennel created after active the customized devtools pannel

### What did you expect to happen?
only one pennel created

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
- Firefox 95.0.2 (64 bit)
- Windows 10

**Comment by rpl** [comment]
Then devtools.js in the test extension attached is registering a devtools panel that points to the same devtools.html page and devtools.js script (which means that when the panel is abtivated and devtools.js executed, a new devtools panel will be created, and that is expected).

The extension should point the registered devtools panel to a different extension page and script to avoid this recursive behavior.

Closing as invalid.
