### ISSUE TITLE
nectar notifier

### ISSUE THREAD

**Issue by 1963ADG** [mozilla/addons#1379]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Nectar search add on which I'd had for few years, started giving error messages. I uninstalled it and tried to install their updated version called Nectar Notifier

### What happened?
Error message from Firefox as follows

'Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes, or by asking for help on our community forums.'

### Anything else we should know?
I've tried to install on several days and get same message.  Contacted Nectar who say there is no problem at their end
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
Do you have a link for the add-on you were trying to install?

**Comment by 1963ADG** [comment]
Thanks for reply,  Went through the links on the Nectar site where all my account details are still OK.  This is the address that came up when I clicked on 'Add to Browser'  or clicked on 'Install'

https://www.nectar.com/nectar-notifier#install

Some bits have got missed off the copy of message from Firefox. 
first line should end 'or have replaced it'
2nd line should end  'or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.'

Hope this helps

**Comment by AlexandraMoga** [comment]
Looks like the developer hasn't updated their install instructions to include a link to a valid installation page on addons.mozilla,org, or as the error page from the addons website says, their addon could be unavailable for various reasons. I suggest asking the developer for an updated installation link, since https://addons.mozilla.org/en-US/firefox/addon/nectar-browser-add-on/ is no longer available.

**Comment by 1963ADG** [comment]
Thanks for your advice.  I'll pass on your comments to Nectar, although when I had a long Live Chat with them 30 Dec they said there were no issues with the toolbar as far as they were concerned and I should contact Mozilla support.  I'll see what they have to say now.  
Thanks again.
