### ISSUE TITLE
Addon Validation Error - No <em:type> element found in install.rdf even though it has one in XML

### ISSUE THREAD

**Issue by lrsnider** [mozilla/addons#138]
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
submission of a new add-on

* Whether your add-on is listed or unlisted.
unlisted

* The URL where you submitted the add-on.
https://addons.mozilla.org/en-US/developers/addon/submit/2

* The approximate time you submitted the add-on, with timezone.
2pm EST

Note: I removed all references to proprietary information such as the url in the targetUrl var in add_catch.js.

[Archive-061316.zip](https://github.com/mozilla/addons/files/312466/Archive-061316.zip)

**Comment by andymckay** [comment]
Your install.rdf in that zip does not match the requirements in the documentation:

```
<?xml version="1.0" encoding="UTF-8"?>

<RDF xmlns="https://example.com"
     xmlns:em="https://example.com">
  <Description about="urn:sailfish-exchange:install-manifest">
    <!-- properties -->
	<em:id>example@theexample.com</em:id>
	<em:version>0.2</em:version>
	<em:type>2</em:type>
	<em:targetApplication>
	 <Description>
	  <em:id>example@theexample.com</em:id> <!--Firefox-->
	  <em:minVersion>1.5</em:minVersion>
	  <em:maxVersion>3.0.*</em:maxVersion>
	 </Description>
	</em:targetApplication>
  <em:name>Example</em:name>
  <em:homepageURL>"https://example.com"</em:homepageURL>

  </Description>
</RDF>
```

Specifically the RDF xmlns, xmlns:em, Description about:, Description em:id (which is not Firefox). Correct those as per:

https://developer.mozilla.org/en-US/Add-ons/Install_Manifests

And try again?

**Comment by lrsnider** [comment]
@andymckay Thanks for your reply. I got it to work finally!
