### ISSUE TITLE
No Addon's XHR/Fetch requests displayed in network devtools

### ISSUE THREAD

**Issue by mhabsaoui** [mozilla/addons#1381]
### Describe the problem and steps to reproduce it:
We are developping an addon for Firefox, and we need to be able to see our injected script's Fetch requests displayed in Devtools' Network tab.

Steps : just activate and use any Addon making fetch requests, and go to Devtools' Network tab to check for the corresponding http calls.

### What happened?
The Addon's Fetch requests aren't shown by Firefox in Devtools' network tab.
Wheras in Chrome/Edge it is displayed...

### What did you expect to happen?
Fetch requests calls made by Addon's injected script, being logged in Devtools' network tab..

### Anything else we should know?
It seems to be the same for any Addon.

**Comment by mhabsaoui** [comment]
Anyone please ?

**Comment by diox** [comment]
Hi,

I suggest you take a look at https://extensionworkshop.com/documentation/develop/browser-extension-development-tools/#testing-and-debugging-tools ; as you noted, by default the devtools doesn't show what you want, but it's possible to enable this.

If you need additional development-related help, I suggest opening a thread on `[discourse](https://discourse.mozilla.org/c/add-ons/development/108)`.

If you encounter a bug with WebExtension APIs/behavior, I suggest `[opening a bug on bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi)` in the `WebExtensions` product. This GitHub repos is more intended for issues around addons.mozilla.org.

**Comment by mhabsaoui** [comment]
Hi, thanks for Reply.

In fact, I already have looked through all documentation for web extension, and searched for it.
But impossible to find the info on how to enable requests display in devtools !
PS: documentation about debugging extension in devtools does not explain how... 

If you know exactly where, please show me !!

**Comment by rpl** [comment]
Fetch requests originated from a content scripts should be visible in the network panel of the devtools toolbox associated to the tab where the injected script is running from.

In general content scripts debugging has to be done through the devtools toolbox for the specific tab (https://extensionworkshop.com/documentation/develop/debugging/#debugging-content-scripts)

**Comment by mhabsaoui** [comment]
I agree, they should be visible !
Of course I am on Tab where our extension injects content script : we are able to debug content script code from sources tab, with break points, looking at the background examining, and so on...

But we don't really see why the script's Fetch calls aren't logged in network tab !!

On Chrome, they are directly visible...

So we'd appreciate your help on how to enable this : is there a specific setting ? Does it work only on Developer Edition on Firefox ?

Thanks for feedback.

**Comment by mhabsaoui** [comment]
Just wanted to point out another Issue where my situation was **finally understood** !

https://github.com/mdn/translated-content/issues/3749

**Comment by SphinxKnight** [comment]
Dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1442488
