### ISSUE TITLE
Replace stalebot with github stale action

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#1382]
Stalebot seem to have been [abandoned](https://github.com/probot/stale/issues), and while marking issues as stale seems to still work, closing stale issues does not. 

Reading comments in above issue tracker, it looks like https://github.com/marketplace/actions/close-stale-issues is the way go to.

Some folks have also linked their replacement PRs, for example: https://github.com/emqx/emqx/pull/6599/files which we could use as a base or inspiration.

**Comment by diox** [comment]
Looks like stalebot suddenly woke up today and closed a bunch of issues as expected.

**Comment by willdurand** [comment]
Looks like this is the official alternative: https://github.com/actions/stale

**Comment by wagnerand** [comment]
I think we did this recently?

**Comment by diox** [comment]
Only for this repos, we need to do that for all of them.
