### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by mpociot** [mozilla/addons#1384]
Hi,

as we are trying to submit a private, unlisted extension, I am unable to share the add-on copy in this GitHub issue, but I'm happy to send a link to a copy via mail/Twitter DM/whatever works.

I'm receiving the following error:

> Validation was unable to complete successfully due to an unexpected error.

When trying to lint the ZIP file locally using the latest version of `addons-linter` it is working as expected. 
I am receiving a lot of warnings locally, coming from the Webpack bundled files, but no errors:

```
Validation Summary:

errors          0              
notices         0              
warnings        852       
```

The URL I used to submit the add-on is: `https://addons.mozilla.org/de/developers/addon/07eca31c84224d4baf63/versions/submit/upload-unlisted`

The add-on was uploaded on January 12th at 1:32 PM GMT+1

**Comment by diox** [comment]
Hi,

How big are the JavaScript files in your add-on ?
