### ISSUE TITLE
Random user agent can't be installed

### ISSUE THREAD

**Issue by beambolah** [mozilla/addons#1386]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.) I've been trying to install random user agent extension for the past 48 hours and I've downloaded it like 100 times but it's not opening after downloading

### What happened?
The icon to add at the mozilla add on site can't be clicked, rather it's showing a download icon which isn't opening the file
### What did you expect to happen?
I expect to be able to click the add icon on the Mozilla add on page so as to automatically add random user agent extension to my add ons
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![Screenshot_20220113-204451](https://user-images.githubusercontent.com/97700054/149398652-ddee14ad-c88f-4d0f-95ca-7515972b8bbd.png)

**Comment by diox** [comment]
That add-on is not currently supported on Firefox for Android, which you seem to be using. See the Yellow warning in your screenshot.
