### ISSUE TITLE
Searching from /developers/ gives "Not found"

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/addons#139]
Steps to reproduce:

Go to https://addons.mozilla.org/da/developers/ and search for something in the search input in the top right corner.

Actual results:

Gets send to:
https://developer.mozilla.org/en-US/da/search?topic=addons&q=test

Says:
Not Found
We're sorry, we couldn't find what you were looking for.
...

Expected results:

Show some find of search results page.

Also i dont get why these two pages offer the same looking search box but one is for searchin extensions and the other is for searching developer docs:
https://addons.mozilla.org/da/
https://addons.mozilla.org/da/developers/

**Comment by muffinresearch** [comment]
Thanks for the bug report. That looks to be a bug in MDN. 

If you go to:

https://developer.mozilla.org/da/search?topic=addons&q=test

you get redirected to 

https://developer.mozilla.org/en-US/da/search?topic=addons&q=test

When a locale that doesn't match is found it should redirect and replace the bad locale with a fallback which would be en-US in this case.

I've filed a bug on MDN here: https://bugzilla.mozilla.org/show_bug.cgi?id=1283422

RE: the search boxes. We're looking at reworking all of the frontend for AMO so I'll label this as feedback so we can take it into consideration. I'd expect for things like this to get improved during this process.
