### ISSUE TITLE
Update Push Duty docs to include Extension Workshop

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons#1391]
We are going to add deploying Extension Workshop to the push duties. This issue is about updating `push-duty.rst` to document what's required.

**Comment by AlexandraMoga** [comment]
@bobsilverberg does this mean that Extension Workshop should be covered during sanity testing as well?

**Comment by bobsilverberg** [comment]
@AlexandraMoga What does your team usually do about testing Extension Workshop?

**Comment by AlexandraMoga** [comment]
@bobsilverberg not much, besides checking that the page is loading when accessed from links present on AMO. In the past, EW was tested by us on demand only - when there were more significant changes on the site, for example.

If this has to change, we (QA) need to decide how we should include this in our regular release and sanity testing schedules.

**Comment by bobsilverberg** [comment]
@tublitzed @diox What are your thoughts about whether we need regular sanity checking of Extension Workshop for every push, if we are going to be deploying on each push? The the push duty docs I have suggested that the person pushing should do a sanity check to make sure that any docs that have changed continue to render correctly, so maybe that is enough?

**Comment by diox** [comment]
I think what you added to the push duty doc is enough for now.

**Comment by bobsilverberg** [comment]
> I think what you added to the push duty doc is enough for now.

Thanks @diox, I agree. @AlexandraMoga there will be no additional requirements for QA for Extension Workshop.

**Comment by AlexandraMoga** [comment]
@bobsilverberg thanks!

**Comment by AlexandraMoga** [comment]
@bobsilverberg with the risk of sounding pedantic :sweat_smile:: 

>You should manually verify Extension Workshop on prod after the push has completed. Visit https://extensionworkshop.com and view any pages that have been changed since the last push to verify they exist and are rendering properly.

is this task supposed to be completed by the push hero or QA ?

**Comment by bobsilverberg** [comment]
> @bobsilverberg with the risk of sounding pedantic 😅:
> 
> > You should manually verify Extension Workshop on prod after the push has completed. Visit [extensionworkshop.com](https://extensionworkshop.com) and view any pages that have been changed since the last push to verify they exist and are rendering properly.
> 
> is this task supposed to be completed by the push hero or QA ?

The push hero.
