### ISSUE TITLE
Replace legacy convenience image in CircleCI config

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1397]
`circleci/*` legacy images are deprecated and no longer maintained, they need to be replaced by the more modern `cimg/*` images. See https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034 for more information.

https://github.com/mozilla/addons/blob/09c70a976d19c49174f54a0a973101f76875f607/.circleci/config.yml#L7

Alternatively... does this repo _needs_ to build anything ? We typically make changes to the few docs there are here directly without a PR...

**Comment by eviljeff** [comment]
I guess it's just for local building of docs?  (not that I've ever tried)

**Comment by diox** [comment]
Yeah it's really there to test that docs can be built... I guess it's trivial to update the image and keep it...

**Comment by diox** [comment]
Yeah, really not much point in building this repos... I figured we could always change our minds later if needed.
