### ISSUE TITLE
Paypal popup providing poor payment preferences

### ISSUE THREAD

**Issue by autonome** [mozilla/addons#14]
STR:

1. Go to https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/developers
2. Click "Contribute <3" button
3. Paypal popup pops up

Screenshot of problem is below. The account being shown correctly is a linked bank account. The second entry should be a valid credit card.

<img width="368" alt="screen shot 2015-12-18 at 11 51 13 am" src="https://cloud.githubusercontent.com/assets/50103/11902544/9bd5ade2-a580-11e5-9ed4-d53d709df61d.png">

**Comment by andymckay** [comment]
We just tell Paypal to start the payment flow, we don't know anything about the users account, that's all up to Paypal to handle after that. We could try bouncing this over to Paypal, but I'm not sure who to ask on that side.

**Comment by autonome** [comment]
The problem is that it is confusing to users, and also may reduce the
number of payments to authors. I tried twice and quit, before finally going
"fuck it, i'm going to try and track down what is going on'.

Maybe we shouldn't be using *only* Paypal if we're forced to use this old,
broken and confusing payment UI.

**Comment by andymckay** [comment]
At this point we are planning the rewrite of AMO. I'm not to sure if the idea of contributions will survive the rewrite and if they do, what format they'll take. So we'll see what happens in the rewrite which UX are working on now.

Based on the rewrite there's nothing actionable here other than yeah we can improve it.
