### ISSUE TITLE
Make changing UUID easier

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/addons#140]
I translate ChatZilla to my language and wanted to change the language code from "da-DK" to just "da".
But then when i upload to AMO it complains about the UUID is not allowed to be changed.
So i had to submit a new extension and edit all the information so it was the same as the old.

And now i have to find a way to make the users go from the old to the new.

I would like to be easier.

If not possible to change the UUID, then maybe make it possible to create a copy of the old extension so i don't have to enter the exact same information again.

**Comment by jvillalobos** [comment]
Why not use the old ID?

The ID is used for automatic updates, statistics gathering, etc., so it shouldn't be easy to change the add-on ID.

**Comment by scootergrisen** [comment]
Well i guess the ChatZilla makexpi.py code creates it with "da" so if i try and upload new version to the old da-DK extension on AMO i get:

    Your add-on failed validation with 1 error.

        Add-on ID doesn't match add-on.

So i would have to change the manually each time i guess.
But i would prefer the UUID to be the correct, so it should only say "da-DK" if that was the language code in use other wise that would be confusing if it says "da-DK" but its using "da" when it appear in the URL.

I would just like a more easy transition if people choose to make the change from "da-DK" to "da" and would like the UUID to match so the URL looks correct and not a old name that might confuse people.

**Comment by jvillalobos** [comment]
Right, the ID usually matches the locale. I didn't consider that in my reply. I don't think there's anything we can do at this point. When we decide what to do for these extensions in the WebExtensions API, we can make the ID independent from the locale.
