### ISSUE TITLE
Different locale in search engine than default

### ISSUE THREAD

**Issue by Tadynas** [mozilla/addons#1400]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

1. Navigate to https://www.google.com
2. Search for 'ratepunk mozilla addons'
3. It will show Ratepunk Mozilla add-ons link with Russian language

### What happened?

1. In search engine Ratepunk locale is Russian while default selected is English

### What did you expect to happen?

1. In search engine show Ratepunk Mozilla add-ons link with English language

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

![image](https://user-images.githubusercontent.com/43318503/158794616-277306ed-e44d-4fd6-88aa-f97554731e4f.png)
![image](https://user-images.githubusercontent.com/43318503/158795509-6f69d4c5-bf7c-4047-abe2-f79361ee15ba.png)
![image](https://user-images.githubusercontent.com/43318503/158795544-f4e200f5-2128-4cc1-b103-77cd94dcd7a8.png)

**Comment by eviljeff** [comment]
Looks like this is location dependant at google's end - I'm in the UK and get a link to https://addons.mozilla.org/en-GB/firefox/addon/ratepunk-compare-hotel-rates/ for example
