### ISSUE TITLE
Removing translation fuzzy matches in future PR pushes

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons#1402]
**Background**:

The l10n team is working on rolling out a pre-translation feature on Pontoon, which is done through deploying machine translated (MT) content for localizers to review before publishing (save) them.

This change will conflict with the current Fuzzy matched strings in Pontoon as they mean different  things in this new concept.

More on this:  https://github.com/mozilla/pontoon/blob/master/specs/0107-pretranslated-status.md.

**What will happen**:

The strings currently shown as fuzzy matches in Pontoon will be shown as `missing` strings, meaning, pending translation. And once the new strings landed, they will go through the MT step and the strings will appear as Fuzzy Matches.

**What do devs need to do for future code updates**:

For future PRs for l10n, please change to `no-fuzzy-match` approach as detailed in [this doc for gettext file type](https://www.gnu.org/software/gettext/manual/gettext.html#Fuzzy-Entries).

Given there are three components for add-ons. Please share this information with front-end, backend and the linter teams

**Comment by peiying2** [comment]
@eviljeff

**Comment by eviljeff** [comment]
@diox this seems straightforward (just add `--no-fuzzy-matches` to the `msgmerge` commands (in addons-server, `extract-l10n.sh`), but I might be missing something as I've not had to delve into our l10n setup much.

**Comment by diox** [comment]
Yeah that should be all we need to do. The relevant `msgmerge` calls should be:

**addons-frontend**
- https://github.com/mozilla/addons-frontend/blob/326dea49a590b646ba5c2ccef887e7b0994431be/bin/merge-locales#L20

**addons-server**
- https://github.com/mozilla/addons-server/blob/master/scripts/extract-l10n.sh#L91
- https://github.com/mozilla/addons-server/blob/ef856c7490263b8e01f486859ce06b5623c7a2c3/scripts/extract-l10n.sh#L98

**Comment by eviljeff** [comment]
@peiying2 what's the timing on this change?  Is it blocking something?  Will be blocking something in X days/weeks? Or just something we should do whenever?

**Comment by mathjazz** [comment]
Hey @eviljeff! :)

There is no rush. Support for PO Fuzzy strings remains in Pontoon.

The only thing that changes is the visibility of Fuzzy strings in Pontoon. Rather than being assigned a dedicated translation status (Fuzzy), they will now be treated as Missing, which means they will not be accessible from dashboards directly.

While developing this presentational change in Pontoon, an idea has been proposed to stop using Fuzzy strings in the projects completely. Anecdotally, Fuzzy translations are rarely useful and need to be rejected by localizers most of the time.

**Comment by diox** [comment]
We will stop generating _new_ fuzzy matches, but should anything be done about the existing ones already in the `.po` files ?

**Comment by mathjazz** [comment]
Thanks! You can keep the old fuzzy strings.

**Comment by willdurand** [comment]
Closing this issue now that all patches have landed, see:

- https://github.com/mozilla/addons-server/issues/19094
- https://github.com/mozilla/addons-linter/issues/4250
- https://github.com/mozilla/addons-frontend/issues/11462
