### ISSUE TITLE
Captcha fails to appear for some chinese users

### ISSUE THREAD

**Issue by le-guan** [mozilla/addons#1409]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![图片](https://user-images.githubusercontent.com/1277598/167324278-e5fb94c0-772b-4710-b7bb-697bf6587f09.png)
![图片](https://user-images.githubusercontent.com/1277598/167324302-40aaf9c8-130e-494e-bbfe-cbb3c47c951b.png)

**Comment by diox** [comment]
Hi,

It looks like the captcha failed to load. Any errors in the devtools console when you load the page and submit ?

**Comment by KuaiQu** [comment]
![图片](https://user-images.githubusercontent.com/1277598/167751753-805aaf5c-8d81-4b29-a7bd-14f39e525c57.png)


> Hi,
> 
> It looks like the captcha failed to load. Any errors in the devtools console when you load the page and submit ?

**Comment by diox** [comment]
Hi, we deployed some changes to the captcha last week, does that still happen for you ?

**Comment by le-guan** [comment]
Problem is solved.Thanks

**Comment by le-guan** [comment]
> Hi, we deployed some changes to the captcha last week, does that still happen for you ?
Problem is solved.Thanks
