### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by rogergr311049** [mozilla/addons#1410]
[theme - JOHN - Light - Gray - Ver. 2.zip](https://github.com/mozilla/addons/files/8667093/theme.-.JOHN.-.Light.-.Gray.-.Ver.2.zip)
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

* Whether your add-on is listed or unlisted.

* The URL where you submitted the add-on.

* The approximate time you submitted the add-on, with timezone.

**Comment by diox** [comment]
This doesn't look like a regular zip file, it looks like a `7z` file. If you try re-creating that archive as an actual `zip` file it should work.
