### ISSUE TITLE
hola addon for firefox

### ISSUE THREAD

**Issue by t1jones** [mozilla/addons#1414]
The web site at https://hola.org has a link to install the addon.
This button has the label  Get Hola.It's free.
When I click the link I am taken to https://addons.mozilla.org/firefox/downloads/latest/hola-free-vpn-proxy-unblocker/
Which gives a not "found response".
I have tried searching firefox addons for hola but only get themes not addons or extensions.

Is hola availble for firefox?

![image](https://user-images.githubusercontent.com/105576418/168458174-5c97551a-7544-46a2-b737-ba9308b91e6f.png)

**Comment by eviljeff** [comment]
You can contact the developer (Hola) for questions about the add-on availability.
