### ISSUE TITLE
define text for add-on install confirmation

### ISSUE THREAD

**Issue by designakt** [mozilla/addons#142]
With the new add-on discovery page in Firefox about:addons (#64) introduces a new install flow that features a way to tell the user that installation was successful and show where the add-on can be found in the browser.

[![138946213](https://cloud.githubusercontent.com/assets/8145891/15358442/c25d2f84-1d04-11e6-9308-bce35a92d25b.png) _or see prototype on invision_](https://invis.io/K47CLL4MP)

@devaneymoz & Michelle: What should this text say? How should it be worded?
(The first version in 48 will have a confirmation, but it will not hang from the extension itself, but off the menu button. That will be fixed hopefully by 49.)

**Comment by devaneymoz** [comment]
(question: do we have a copy style guide for Firefox UI? I just realized I'm not sure if we're referring to "toolbar" as a specific or general feature, which may affect capitalization?)

For this, what about something with a bit of conversational personality?...

**Ready to go!**
Click here to access your new add-on. _Learn more_. 

(also, where does "Learn more" link to? Is it necessary, in other words?)

**Comment by designakt** [comment]
@mstriemer Could you please provide us with an image of what the confirmation will look like in 48.

<img width="402" alt="screenshot 2016-06-09 16 55 05" src="https://cloud.githubusercontent.com/assets/211578/15947809/1461eba2-2e63-11e6-9c4a-87ad635bd391.png">
_This is the latest image I have, but is wrong as it suggest that the panel will hang from the add-ons button. Which it will not in 48. please update._

@devaneymoz Michelle is working on a copy guide for Firefox. It does not live online so far, but I will share the link as soon as it does. For now I forwarded it to you by mail.

@devaneymoz The first version should probably be different in text, as it **will not be able to hang from the add-on itself, but only from the menu button**. And I am not sure if we will be able to provide a learn more for the first version. (In future versions "learn more" should link to a page provided by the add-on dev that contains more information about the add-on. see issue https://github.com/mozilla/addons/issues/112#issuecomment-223350744)

I wonder if there is more we should tell the users on confirming the installation. Chrome for example tells users where to manage extensions.
![chrome-extension-install-confirmation](https://cloud.githubusercontent.com/assets/8145891/16302253/6b4938a2-394a-11e6-825c-24766edf333d.png)

**Comment by andymckay** [comment]
Pinging @muffinresearch instead of @mstriemer who is on PTO at the moment.

**Comment by muffinresearch** [comment]
@designakt this is what it looks like. I've discovered an issue though, in testing it. It seems having the discovery pane origin in the uiTour origin list is not enough. We need the parent page `about:addons` there for the UI tour to function.

**Comment by designakt** [comment]
@mheubusch What are your thoughts on confirmations?

**Comment by andymckay** [comment]
@designakt I guess this is relevant to permissions, want to keep this open?

**Comment by designakt** [comment]
@devaneymoz is working on that copy with all the other permission copy. (can't assign to him)
