### ISSUE TITLE
Error in themes Mozilla website

### ISSUE THREAD

**Issue by ftodd1** [mozilla/addons#1422]
When looking at ad a new theme, the website error out over page 1,000.

You can go up to page 1000, but if you try to get others an information screen stated error is shown. 

To see page 1,001

Last page accessible.

![Screenshot 2022-07-04 at 15-54-50 Trending themes – Add-ons for Firefox (en-US)](https://user-images.githubusercontent.com/14102268/177211362-cbe816bc-f67a-4b2c-9ca5-bf103d556eab.png)

error page shown on 1001

![Screenshot 2022-07-04 at 15-54-00 Add-ons for Firefox (en-US)](https://user-images.githubusercontent.com/14102268/177211521-4397be97-701f-4711-a0c7-079cdea782cb.png)

That is all, thanks for checking on the matter.

F. Todd Perzy
ftoddp@yahoo.com

**Comment by diox** [comment]
Hi,

That's done on purpose (searches that far are expensive for us), though we have an issue opened to prevent the pagination from going that far (https://github.com/mozilla/addons-frontend/issues/10689).
