### ISSUE TITLE
Self-signed addon is currently stuck at "Awaiting Review".

### ISSUE THREAD

**Issue by KAEDEAK** [mozilla/addons#1424]
### What happened?
Self-signed addon is currently stuck at "Awaiting Review" for few days.
Reproduce:
Update add-ons in the Add-on Developer Hub.
Validation: 0 errors, 3 warnings.

### What did you expect to happen?
Usually it takes less than an hour. mostly 5 minutes or so.

### Anything else we should know?
Affected to version updates and new extension creation.
I have tested both situations.

Best regards,

**Comment by diox** [comment]
Without more details we won't be able to find the add-on and investigate. That being said, note that any add-on, even self-hosted, can potentially be subjected to manual review at any time and therefore there is no guarantee an add-on will always get signed immediately.

**Comment by KAEDEAK** [comment]
Thank you for your reply.

I see.
If no one else has this problem, it's probably caused by that manual review.
I think I have to wait.

Thank you for taking the time.
