### ISSUE TITLE
Romansh spellchecker listed in the wrong place

### ISSUE THREAD

**Issue by gion-andri** [mozilla/addons#1428]
### Describe the problem and steps to reproduce it:
The Spellchecker for Rumantsch Grischun (https://addons.mozilla.org/en-US/firefox/addon/spellchecker-rumgr/) is listed on the `Dictionaries and Language Packs` page (https://addons.mozilla.org/en-US/firefox/language-tools/) under `German (Austria)` instead of `Romansh`. 

### What happened?
Apparently, when publishing the spellchecker, certain metadata in the xpi was wrong. This was fixed a long time ago in the xpi, but the listing is still wrong.

### What did you expect to happen?
The spellchecking xpi is listed under `Romansh (rm)`, as the spellchecker contained is also for rm. 

### Anything else we should know?
nope.

**Comment by wagnerand** [comment]
Thank you for reporting this, I have corrected the issue. Due to caching, it might take a bit before the changes are reflected.
