### ISSUE TITLE
Do firefox addons support service_wrokers?

### ISSUE THREAD

**Issue by sudoaugustin** [mozilla/addons#1431]
I'm not even sure I'm raising the issue in the correct repo.

`
"background": {
    "service_worker": "background.js",
  }
`

Is this declaration work in Firefox? 
In manifest v3 the background script has been turned into service_worker. But in MDN, it's still showing the doc with scripts

**Comment by willdurand** [comment]
> Is this declaration work in Firefox?

No, not at the moment. Event-driven background scripts are the way to go for now, see: https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/
