### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by q2p** [mozilla/addons#1434]
Please attach a copy of your add-on, and fill in the following information:
[BrowserHelperFirefox.zip](https://github.com/mozilla/addons/files/9484153/BrowserHelperFirefox.zip)

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
The problem happens on a `Submit a New Version` screen. The previous version was 0.0.3, the one I'm trying to upload is 0.0.4

* Whether your add-on is listed or unlisted.
Can't tell, the Devoleper Hub doesn't show if it's listed or not.

* The URL where you submitted the add-on.
https://addons.mozilla.org/en-US/developers/addon/433930709cb04fd39ca2/versions/submit/

* The approximate time you submitted the add-on, with timezone.
4 Sep 2022, 05AM GMT

**Comment by diox** [comment]
Hi,

Sorry for the delay in responding, but this should be an intermittent failure that we think we have resolved now,  so feel free to try again. Thank you.
