### ISSUE TITLE
Add-on signing complains about missing referer header

### ISSUE THREAD

**Issue by TwonkyHardware** [mozilla/addons#1438]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I go to the Developer Hub to try to submit my first add-on.
https://addons.mozilla.org/en-US/developers/addon/submit/agreement

I agree to the checkboxes and complete the CAPTCHA.

I select "Accept".

### What happened?

The page reloads with the same URL
https://addons.mozilla.org/en-US/developers/addon/submit/agreement

and a message
"""
Oops! Not allowed.

You tried to do something that you weren't allowed to.

You are seeing this message because this HTTPS site requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for 'same-origin' requests.
"""

### What did you expect to happen?

I expected to be able to get an add-on for personal use signed without an incessant stream of pointless obstacles

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Firefox 104

I have uMatrix and uBlock Origin installed, as well as other add-ons, but as far as I know none of them should do anything to my referer header.

**Comment by diox** [comment]
Hi,

If you go to `about:config` and search for `referer`, do you see any preferences appear in bold (which would indicate their current value differs from the default) ?
