### ISSUE TITLE
Deprecate and eventually reject old jQuery versions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#144]
With jQuery 3.0 released recently, 1.12 and 2.2 branches will be supported for a little while, but everything older is not maintained by jQuery anymore.

We should warn developers that we are going to accept jQuery < 1.12 and < 2.2 for a limited time only (Proposal: 3 months?) and after that, accept maintained versions only.

This requires (mostly minor) changes to addons-linter and amo-validator.

Adding @kewisch @eviljeff

**Comment by eviljeff** [comment]
How common are older versions in submissions these days?  There used to be a wide variation in versions used in the past.

**Comment by wagnerand** [comment]
Without any data to prove this (mxr is still down, and would be incomplete anyway), I think 2.0-2.1 and 1.10-1.11 are still quite popular.
And there are a few developers that never update jQuery, so we still see submissions using 1.6 or older.

**Comment by dmethvin** [comment]
Although jQuery's support for non-web-page environments has always been difficult to test for the jQuery team, [in the past we've said](https://blog.jquery.com/2013/04/18/jquery-2-0-released/) that we only support the 2.x version in those situations. So people shouldn't be using jQuery 1.x at all in addons. If you run into any 3.0 issues feel free to mention me into the issue.

**Comment by wagnerand** [comment]
Interesting, I was looking at that blog post but missed that. Thanks for the heads-up!

**Comment by wagnerand** [comment]
Fixed by https://github.com/mozilla/amo-validator/commit/1906e513e56b6fc0b1d2b5d73e51e3d767b9c6a2 and https://github.com/mozilla/addons-linter/commit/a51f94a09c6c1c6aad025f6b6ed14f4a907b0bc0.
