### ISSUE TITLE
Broken pagination links

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons#1440]
[Open the full list of extensions](https://addons.mozilla.org/firefox/search/?page=1000&sort=users&type=extension) and scroll down to get to the pagination links:

![pagination](https://user-images.githubusercontent.com/6733770/193742991-4a5c324e-7ae1-4381-bc58-35e00b3736bd.png)

If the page number is higher than 1000, it gives the `Oops! We can’t find that page` error:

![error](https://user-images.githubusercontent.com/6733770/193743997-54fc3eeb-867b-432a-828d-cc25bda036a3.png)

**Comment by AlexandraMoga** [comment]
Thanks for the report. We are aware of this issue and we have a tracking bug for it here: https://github.com/mozilla/addons-frontend/issues/10689
