### ISSUE TITLE
zh-TW page doesn't load 'svgdemo1.png' successfully

### ISSUE THREAD

**Issue by jimmyww7710** [mozilla/addons#1442]
### Describe the problem and steps to reproduce it:
visit the page:
https://developer.mozilla.org/zh-TW/docs/Web/SVG/Tutorial/Getting_Started

### What happened?
when I was reading this page, 'svgdemo1.png' is not displayed successfully.

### What did you expect to happen?
see the img 'svgdemo1.png'.

### Anything else we should know?
I checked the browser devtools panel, and it's shows  <img src="/@api/deki/files/4928/=svgdemo1.png" alt="svgdemo1.png" loading="lazy">, seems src didn't get the right path for loading file, probably cause by the processing order of lazy loading. 

I also checked English language of page, that src of image showed  'https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Getting_Started/svgdemo1.png'. Taking a guess that switching lang maybe can find the right path,
like 'https://developer.mozilla.org/zh-TW/docs/Web/SVG/Tutorial/Getting_Started/svgdemo1.png', but it's turns out page not founded.

please fix this problem, Thanks 
![img_20221029](https://user-images.githubusercontent.com/36302780/198814416-7c28ba68-fb16-4934-8322-02ea031e75b4.PNG)

**Comment by diox** [comment]
Hi,

This issue slipped past us, but it has nothing to do with add-ons and should be filed against one of the MDN repos : https://github.com/mdn/
