### ISSUE TITLE
Provide Node.js code examples for updating a WebExtension

### ISSUE THREAD

**Issue by avi12** [mozilla/addons#1446]
### Describe the problem and steps to reproduce it:
I tried to follow [this blog post](https://blog.mozilla.org/addons/2022/03/17/new-api-for-submitting-and-updating-add-ons/) and follow the [linked documentation](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-create), but I'm struggling to understand how the different endpoints work together and write code accordingly for Node.js (using [Axios](https://npm.im/axios))

### What did you expect to happen?
Have a code example in a blog post, in this repo, or both

### Anything else we should know?
For a given pair of JWT issuer & secret, my goal is to upload a WebExtension's ZIP, upload its source code and provide release notes

**Comment by willdurand** [comment]
We have code in https://github.com/mozilla/web-ext to do that, specifically here: https://github.com/mozilla/web-ext/blob/master/src/util/submit-addon.js

**Comment by avi12** [comment]
@willdurand I tried to copy some parts (replacing `this.fetchJson` with an Axios call), but it doesn't seem to work
In particular, https://github.com/mozilla/web-ext/blob/e975ab9ab29d3f47832c43d61b21153cec19a85b/src/util/submit-addon.js#L117-L124
According to the [documentation](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-create), it should return an object containing a [uuid](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-detail-object), but in practice I get back a 404 error

**Comment by diox** [comment]
You'll need to provide more details about what exact calls you made, with what parameters.

**Comment by avi12** [comment]
Eventually, I figured out what endpoints to call and what parameters pass to each, but I decided to ditch the API due to [constant throttling](https://github.com/mozilla/addons/issues/1453)
