### ISSUE TITLE
DMARC fails for emails sent from nobody@mozilla.org via socketlabs (email-od.com)

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#1447]
### Describe the problem and steps to reproduce it:
DMARC fails and the email from AMO is flagged as potentially unsafe.
- Submit a new addon for review
- Wait for the automated review to pass and a email to be sent to the developer (from `nobody@mozilla.org` via socketlabs)

### What happened?
- Email sent fails DMARC and occasionally generates a warning in Gmail web client

### What did you expect to happen?
- Email should pass all authentication checks and gmail should not show a warning on top of the email

### Anything else we should know?
- I tried password resetting and that email passes all checks, and is also sent `bugzilla-daemon@mozilla.org` so might be an issue on socketlabs.
<img width="922" alt="image" src="https://user-images.githubusercontent.com/6270406/203553965-7813ce3a-b874-4c4c-b041-ed7d0ce73fd9.png">
<img width="700" alt="image" src="https://user-images.githubusercontent.com/6270406/203554111-bae54f4c-75f1-4d1d-abf1-09ce04ca961a.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-26)

**Comment by bqbn** [comment]
> I tried password resetting and that email passes all checks, and is also sent bugzilla-daemon@mozilla.org

Where did you do "password resetting" and which email passed all checks?

How is `bugzilla-daemon@mozilla.org` related to this issue?

Thanks.

**Comment by abhn** [comment]
> Where did you do "password resetting" and which email passed all checks?
> How is bugzilla-daemon@mozilla.org related to this issue?

I could've been more explicit there. Basically I used password resetting on bugzilla and bugzilla-daemon@mozilla.org email address as an example of another `@mozilla.org` email address (sent through a different system) that passes SPF, DKIM and DMARC to help narrow it down a little to the email provider on AMO. Yes, it isn't related to the issue I'm reporting.

**Comment by diox** [comment]
https://mozilla-hub.atlassian.net/browse/IO-2807 should have fixed this for all environments.

**Comment by bqbn** [comment]
For QA: please follow the steps in the original report and see if the DMARC header still shows "FAIL" and if so, please post the complete email headers for further investigation.

**Comment by alexandruschek** [comment]
Hello,

I tested this on STAGE and I did not get the DMARC header.
<img width="1352" alt="image" src="https://github.com/mozilla/addons/assets/139126091/d6a4b8ff-66e0-4e8d-b269-093cfebee42a">

**Comment by diox** [comment]
DMARC should be seen if you expand email headers by clicking the 3 dots on the right and selecting "show original". 

I can verify it's working:

dev:
```
Authentication-Results: mx.google.com;
       dkim=pass header.i=@mozilla.org header.s=amodev header.b=SXmSmCrr;
       dkim=pass header.i=@email-od.com header.s=dkim header.b=UTiUUlgF;
       spf=pass (google.com: domain of 8fd.82.1ae19000113cd45.9382ad07bb490650f70fe1e8926ab401@email-od.com designates 142.0.177.102 as permitted sender) smtp.mailfrom=8fd.82.1ae19000113cd45.9382ad07bb490650f70fe1e8926ab401@email-od.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=mozilla.org
```
![Screenshot 2024-04-18 at 12-08-05 Original Message](https://github.com/mozilla/addons/assets/187006/22f445bd-d04d-4561-b32e-0a38d44b7ac9)

stage:
```
Authentication-Results: mx.google.com;
       dkim=pass header.i=@mozilla.org header.s=amostage header.b=iwED0x64;
       dkim=pass header.i=@email-od.com header.s=dkim header.b=JkXBGEUx;
       spf=pass (google.com: domain of 3f30.82.1ae190001149169.905003eebae252884f47fdb661200521@email-od.com designates 142.0.177.102 as permitted sender) smtp.mailfrom=3f30.82.1ae190001149169.905003eebae252884f47fdb661200521@email-od.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=mozilla.org
```
![Screenshot 2024-04-18 at 12-12-22 Original Message](https://github.com/mozilla/addons/assets/187006/a596ba31-1563-464a-98eb-5ba868e0d362)
