### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons#145]
Please attach a copy of your add-on, and fill in the following information:
- I was uploading with the uploader here - https://addons.mozilla.org/en-US/developers/addon/submit/2 - brand new addon. I tried 3 times over a span of 12 hours.
- Listed addon
- https://addons.mozilla.org/en-US/firefox/addon/screencastify/
- Submission ended at 9:33pm PST

It's a 27mb file, I had to use ff-mpeg.js for conversion from webm to mp4 and gif (needed for Twitter, Facebook, general conversion). Here is a link to my addon on dropbox - https://www.dropbox.com/s/5ktfz7h4e8ai1oi/dist.xpi?dl=0

End result: It won't upload
What should have happened: It should upload.

**Comment by andymckay** [comment]
```
/tmp ~/sandboxes/addons-linter/bin/addons-linter dist.xpi        
{"count":1,"summary":{"errors":1,"notices":0,"warnings":0},"metadata":{"guid":"Screencastify@jetpack","name":"Screencastify","type":1,"version":"1.0","restartless":true,"architecture":"extension","emptyFiles":[],"jsLibs":{}},"errors":[{"_type":"error","code":"FILE_TOO_LARGE","message":"File is too large to parse.","description":"This file is not binary and is too large to parse. Files larger than 2MB will not be parsed. If your JavaScript file has a large list, consider removing the list and loading it as a separate JSON file instead.","file":"resources/scripts/3rd/ffmpeg-all-codecs.js"}],"notices":[],"warnings":[]}
```

Did you get this error in the validator?

From: mozilla/addons-linter#730

**Comment by andymckay** [comment]
```
/tmp ls -alh resources/scripts/3rd/ffmpeg-all-codecs.js                        
-rw-r--r--  1 andy  wheel    26M 21 Jun 21:04 resources/scripts/3rd/ffmpeg-all-codecs.js
```

**Comment by Noitidart** [comment]
Thanks Andy for super quick reply. I didn't see that error, where would that be? These are the vlidation results for my most recent attempt - https://addons.mozilla.org/en-US/developers/upload/f325b4b515c64fff804e2a8750c23906

**Comment by andymckay** [comment]
Oh basically ignore everything I said. This is not a WebExtension and not being run through the addons-linter, my mistake sorry.

**Comment by Noitidart** [comment]
Oh haha, no problem.

**Comment by Noitidart** [comment]
Hey all, no rush, I just wanted to provide an update. I tried the upload today and it still failed but I got different results on the validation page, it is here:

https://addons.mozilla.org/en-US/developers/upload/e79ee4c903da494fa7820f4cfa0097f1#extension-tests

**Comment by EnTeQuAk** [comment]
ugh…

```
Error: An error in the JavaScript file prevented it from being properly read by the Spidermonkey JS engine.

InternalError: allocation size overflow
```

this is not good :-/

**Comment by EnTeQuAk** [comment]
I'll check and see what memory limits it would need to allow validation to be run of this add-on. But I suggest in the meantime to maybe check if there are other libraries you could use that aren't so massive? It might take a few days to find a proper solution here, I'll update the ticket.

**Comment by Noitidart** [comment]
Thanks very much @EnTeQuAk ! I'll start looking around for alternative lib. The lib is used for converting from .webm to .avi/.gif if anyone knows of alt to ffmpeg.js that would be awesome.

**Comment by Noitidart** [comment]
Hey there @EnTeQuAk I was just curious as to how this was looking? Is it possible I can submit my addon soon? I searched for other libs, I found one that converts to AVI, but it's missing the GIF conversion, which is a feature people requeseted of me.

**Comment by EnTeQuAk** [comment]
@Noitidart sorry, I was out on vacation the past few weeks and didn't have the chance to look at it before. I'll have a look at the issue soon though now that I'm back.

**Comment by Noitidart** [comment]
Thanks very much! :)

**Comment by Noitidart** [comment]
Hi there @EnTeQuAk I just wanted to check up on this. I was kind of eager to get this out :(

**Comment by EnTeQuAk** [comment]
I am closing this, we don't allow new submissions to be anything else but a WebExtension and this issue doesn't exist for our addons-linter.
