### ISSUE TITLE
video download helper 7.6.6 install button goes to page for VDH, but cant find download / install button/link - doesnt install...

### ISSUE THREAD

**Issue by tombr77** [mozilla/addons#1450]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by tombr77** [comment]
I have version 7.6.0 ,  and cant figure out how to update to 7.6.6 
link to page that 'install 7.6.6 ' brings up :
https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/

**Comment by tombr77** [comment]
mozilla page  with 'install' button
https://www.downloadhelper.net/install

**Comment by diox** [comment]
If you already had it installed, from Firefox menu you can navigate to `Add-ons and Themes`, click the gear icon on that page, and select `Check for updates`.

If that doesn't work, then maybe the version you already have in not the official one? You could try deleting it from that same page mentioned above, and then visiting   https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/ again. From there you should see an `Add to Firefox` button:
![Screenshot 2022-12-08 at 21-23-07 Video DownloadHelper – Get this Extension for 🦊 Firefox (en-US)](https://user-images.githubusercontent.com/187006/206559983-ac606263-4e6d-44ac-8a10-28b7da3f0d01.png)

**Comment by tombr77** [comment]
THANKS for the quick response....  I had looked and didnt see the check for
updates -- but i did see an 'automatic update' on / off -- which i turned
on.  Did not see any difference, even after restart- then i submitted my
issue.  -- then suddenly a couple minutes ago it popped up that it was
updated!. go figure.

thanks again.

**Comment by diox** [comment]
Updates are not immediate (unless using the option I mentioned) , it can take up to 24 hours in order not to overload our servers. Glad you were able to resolve it though!
