### ISSUE TITLE
Site doesn't recognize Firefox

### ISSUE THREAD

**Issue by xehpuk** [mozilla/addons#1451]
### Describe the problem and steps to reproduce it:
Visit the page of any extension.

### What happened?
The site tells me to "Download Firefox and get the extension".

### What did you expect to happen?
I expected to be able to get the extension with Firefox.

### Anything else we should know?
![image](https://user-images.githubusercontent.com/3484906/207304064-4565a967-62e4-4faf-bce0-f8e8f3357b7a.png)

Firefox 107.0.1 (64-bit) on Windows 11

**Comment by diox** [comment]
What URL were you on ? Can you reproduce with a fresh profile ?

**Comment by xehpuk** [comment]
Oops, I seem to have changed `general.useragent.override` a while ago. But user agent sniffing is discouraged anyway.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

**Comment by diox** [comment]
We unfortunately need to do user-agent sniffing on AMO, as there is no API to a) ensure the browser is compatible with Firefox add-ons b) ensure it's the correct version required by the add-on.

**Comment by xehpuk** [comment]
Does Firefox allow the installation of incompatible add-ons?

**Comment by diox** [comment]
No, it follows whatever the extension indicates as the [strict minimum version](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#firefox_gecko_properties) required.
