### ISSUE TITLE
New version of addon defaults to require minimum firefox version '109.0a1'

### ISSUE THREAD

**Issue by patxbert** [mozilla/addons#1452]
### Describe the problem and steps to reproduce it:
We recently published a new version of our firefox addon, however the end user can no longer install it.
The user sees "You need an updated version of Firefox for this extension", and a "Download the new Firefox and get the extension" button, but this downloads version 108 of Firefox.

### What happened?
Newly published version of addon defaults to minimum firefox version '109.0a1'

### What did you expect to happen?
Minimum firefox version should default to '42a1' as described [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#firefox_gecko_properties).

### Anything else we should know?
We tried publishing a version with `strict_min_version` set to '42.0', but that did not fix it either.

AMO: https://addons.mozilla.org/en-US/firefox/addon/xbert-for-xero/

**Comment by willdurand** [comment]
The latest version uses Manifest Version 3, which indeed requries Firefox 109 and above. See: https://blog.mozilla.org/addons/2022/11/17/manifest-v3-signing-available-november-21-on-firefox-nightly/

**Comment by diox** [comment]
The following warning should have been shown when uploading manifest v3 versions:

![Screenshot 2022-12-16 at 11-23-00 Upload Add-on XBert Extension Add-ons for Firefox](https://user-images.githubusercontent.com/187006/208077630-156660c0-681a-49b4-83cc-e4058f573e0d.png)

It links to https://extensionworkshop.com/documentation/publish/distribute-manifest-versions/ which explains in more details the problem and a possible workaround if you want to continue working with MV3 and MV2 in parallel.
