### ISSUE TITLE
"Request was throttled"

### ISSUE THREAD

**Issue by avi12** [mozilla/addons#1453]
### Describe the problem and steps to reproduce it:
I'm trying to make a reliable Node.js code that calls [endpoints](https://blog.mozilla.org/addons/2022/03/17/new-api-for-submitting-and-updating-add-ons/), but after many code testing, I'm getting an error of `Request was throttled. Expected available in 73975 seconds.`

### What did you expect to happen?
Not be throttled. That's why the blog post mentions waiting for [5-10 seconds](https://blog.mozilla.org/addons/2022/03/17/new-api-for-submitting-and-updating-add-ons/#:~:text=polling%20interval%20is-,5%2D10%20seconds,-%2C%20making%20sure%20your) between requests

### Anything else we should know?
This behavior makes the API unreliable, and therefore I will most likely not try to use it but instead use Puppeteer to automate accessing the dev dashboard

**Comment by diox** [comment]
This is expected. You will eventually run into similar, or even more aggressive throttling if you automate access to devhub. There are limits per minute, hour and 24h durations, both for user accounts and IP addresses/networks.

I would recommend to continue using the API instead, on our staging environment for testing (https://addons.allizom.org/en-US/firefox/), and making fewer requests in general.

**Comment by avi12** [comment]
My goal is to work with the submission API, and understand how to work with the endpoints
Is there a better way to test the API?

**Comment by diox** [comment]
We have documentation to help understand the endpoints. If you really want to test it, you could build it from the docker image locally.
