### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by tbroadley** [mozilla/addons#1454]
> Please attach a copy of your add-on,

I'd rather not attach a copy of my add-on because it contains private code from my company. The add-on is only available to my company's employees. If it's necessary to debug this issue, perhaps we could find a way to share the add-on privately?

> and fill in the following information:
>
> * Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

A new version of an existing add-on.

> * Whether your add-on is listed or unlisted.

Unlisted.

> * The URL where you submitted the add-on.

https://addons.mozilla.org/en-CA/developers/addon/faire-devtools/versions/submit/

> * The approximate time you submitted the add-on, with timezone.

December 20, 2022 at ~2:05-2:10 ET.

**Comment by tbroadley** [comment]
![image](https://user-images.githubusercontent.com/8731922/208748967-4431bfac-4daa-48e6-b130-8d0625fa3473.png)

**Comment by diox** [comment]
Hi,

Sorry for the delay in responding, but this should be an intermittent failure that we think we have resolved now,  so feel free to try again. Thank you.
