### ISSUE TITLE
Spam addon reviews with positive rating

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/addons#1455]
There have been a lot of spam lately, examples:
https://www.google.com/search?q=%22www.co2fun.com%22+site%3Aaddons.mozilla.org
https://www.google.com/search?q=%22GanJingWorld%22%20site:addons.mozilla.org

These reviews has 5 starts rating so many addon authors won't report them as spam.

Is there a limit of how many reviews can one account create (per day maybe?).
Also maybe force users to write a unique reviews, not the same spam message (simple "unique" constraint on the DB table :)).
And for tooling - writing a query like: `select count(review_message), review_message from reviews where review_message LIKE '%www%' group by review_message order by 1 desc limit 100` would print most common review messages which should make it easy to find these spams and delete them quickly even if they come from multiple accounts.

**Comment by wagnerand** [comment]
Thanks.
