### ISSUE TITLE
Hungarian Optional Accents Dictionary is in the wrong row at addons.mozilla.org

### ISSUE THREAD

**Issue by SiGe11** [mozilla/addons#1456]
### Describe the problem and steps to reproduce it:
At https://addons.mozilla.org/en-US/firefox/language-tools/ the [Hungarian Optional Accents Dictionary](https://addons.mozilla.org/en-US/firefox/addon/hu-optional-accents-dict/) entry is in the `Hindi (India) हिन्दी (भारत)` row. It should be in `Hungarian magyar` row.

**Comment by AlexandraMoga** [comment]
Looks like the author of that dictionary used an incorrect language code - `hi-IN`- for the dictionary, which is likely why the entry appears in the Hindi section on AMO. The name of the dictionary is misleading in this instance.
