### ISSUE TITLE
Addon Validation Error - timeout scanning extension that has lots of JavaScript files

### ISSUE THREAD

**Issue by davaiyo** [mozilla/addons#1458]
* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
  * new version of an existing add-on

* Whether your add-on is listed or unlisted
  * listed

* The URL where you submitted the add-on.
  * https://addons.mozilla.org/en-US/developers/addon/localcdn-fork-of-decentraleyes/versions/submit/

* The approximate time you submitted the add-on, with timezone.
  * 30.12.2022 14:14 UTC

Copy of extension: [LocalCDN v2.6.44.zip](https://github.com/mozilla/addons/files/10325083/v2.6.44.zip)

Same problem with MV3. Should I create a separate issue for this? I think the problem is the same with MV2 and MV3: The many resources in `resources/*`. Without the `resource` folder, the validation succeeds immediately.

**Comment by willdurand** [comment]
Is there any more specific error?

**Comment by davaiyo** [comment]
Thanks for your reply. I added some bigger frameworks and tested the [validator](https://addons.mozilla.org/en-US/developers/addon/validate). Unfortunately 3 attempts in a row failed (Today from 18:45 - 18:55 UTC if logfiles would be helpful).

I've tested this with an MV3 extension and as self-hosted. Does this make a difference in the background?

**Comment by diox** [comment]
It doesn't make a difference. Unfortunately your add-on is still too costly to parse with all those JavaScript files - in fact according to our logs it is the first to fail in a couple weeks since we made the upgrade (where before we'd have a few more occurrences).

We are still planning to move our scanners to a different architecture and increase the timeout, but in the meantime I'm afraid it will continue to be an issue for you.

**Comment by davaiyo** [comment]
> It doesn't make a difference

Okay, thanks for the information.

> Unfortunately your add-on is still too costly to parse with all those JavaScript files - in fact according to our logs it is the first to fail in a few weeks since we made the upgrade (where before we'd have a few more occurrences).

Oh, sorry that the extension is the only one that breaks the capacity. For the last test I had included 3 big frameworks that were actually removed a long time ago. Just now (18:15 UTC) I uploaded the current version of the extension (without the 3 big frameworks). Unfortunately there is a timeout there as well.

> We are still planning to move our scanners to a different architecture and increase the timeout, but in the meantime I'm afraid it will continue to be an issue for you.

No problem. I'm looking forward to it. Thanks for your reply :+1:
