### ISSUE TITLE
Addon Validation Error but `web-ext lint` does not show any errors (large source files, parsing timeout)

### ISSUE THREAD

**Issue by BlobbyBob** [mozilla/addons#1459]
Add-on Copy: [ga_demangle-1.0.zip](https://github.com/mozilla/addons/files/10333696/ga_demangle-1.0.zip)

Phase: During submission of a new add-on

Type: unlisted

URL: https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted

Date: 2023/01/02 23:50 UTC+1

Note: Running `web-ext lint` does not show any errors.

**Comment by willdurand** [comment]
Hi, can you tell us what the `web-ext` version is? (`web-ext --version`)

Also, could you add the error messages you're seeing on AMO? Thanks.

**Comment by BlobbyBob** [comment]
> Hi, can you tell us what the `web-ext` version is? (`web-ext --version`)

`web-ext` version is 7.4.0 for me

> Also, could you add the error messages you're seeing on AMO? Thanks.

![A single generic error in the general category](https://user-images.githubusercontent.com/13750291/210408698-6fa09db5-5a50-4f07-8ce8-d030a8f65a1c.png)

Thanks for working on the issue!

**Comment by willdurand** [comment]
Can you consistently reproduce this error? Usually such "unexpected errors" are temporary. I'll double check our logs, though.

**Comment by BlobbyBob** [comment]
Yes, it is reproducible and it persists since 2023/01/02 when I first tried to submit the extension. I've tried every day since.

**Comment by BlobbyBob** [comment]
@willdurand Are there any updates or can I help you with any additional information?  
I've just tried once again and it didn't work. The analysis terminated with the same error message as before at 2023-01-06 16:49:49 UTC+1 if this helps you checking the logs.

**Comment by diox** [comment]
Hi,

Your add-on consist of a lot of big JavaScript files that taking too long for our scanners to parse in the allocated time. We have plans to address that this year, but that is potentially several months away. I would suggest refactoring to store your "database" of replacements in a different way.

**Comment by BlobbyBob** [comment]
Thanks for the response.  
Indeed my add-on requires a large associative datastructure to work which cannot be removed. This is maybe slightly off-topic for this issue then, but is there any way to store such data without it being linted?  
In the past `web-ext` already hinted me to store this data in JSON instead of JavaScript sources, but trying this did not change anything as JSON files still got linted. Furthermore, I did not find any information on MDN how I can access such a file from my add-ons code.

**Comment by diox** [comment]
Your problem is not with the linter but with our (private) scanners. Converting to JSON would help make it faster for them.

You can use [`getURL()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getURL) with [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) to load the JSON file(s) (not sure if splitting them up would still be useful, feel free to experiment) from your content script.

```javascript
let extensionData;

window.fetch(chrome.extension.getURL('/foo.json')).then((response) => {
    response.json().then((data) => {
        extensionData = data;
        console.log(extensionData);
    })
});
```
