### ISSUE TITLE
Improve "You need an updated version of Firefox for this extension" message for MV3 extensions

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons#14658]
### Describe the problem and steps to reproduce it:
Use Firefox 108 to open the download page for a Manifest V3-only extension, for example: https://addons.mozilla.org/addon/youtube-volume-scroll/.

### What happened?
The page displays this message, even though I'm using the latest stable version: 

>You need an updated version of Firefox for this extension

### What did you expect to happen?
The message should explain that this extension will only work on future Firefox versions instead of suggesting me to update Firefox.

I know that Firefox 109 is going to be released in a few days, but this likely affects Firefox 102 ESR too, which will be supported until late August.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-193)

**Comment by nettyso** [comment]
This is the first result on search engines for "You need an updated version of Firefox for this extension" but doesn't seem to provide a way forward. For anyone else reading this just press "Download file" and it'll install automatically 👍 

![Image](https://github.com/user-attachments/assets/0c523e0b-8e7a-491f-93c6-5da050713658)

**Comment by anewuser** [comment]
>but doesn't seem to provide a way forward

That's because this report was about cases where there was *no* way forward. I was talking about extensions made for Mv3 back when the latest stable versions didn't support Mv3 extensions yet.

Your screenshot shows an Mv2 extension that is available for all Firefox versions 58 and above. This indicates that you've used something to change your User-Agent string to make websites think that you're using another version or browser.

**Comment by nettyso** [comment]
I see I see - I'm just trying to leave some breadcrumbs for other internet people who may search for this error message. Sorry to hijack your thread 🙏

The "Download file" workaround works fine so I don't need this fixed, but thank you!

If you're curious (I am, lol) I think it's related to my aarch64 Fedora build of Firefox. I don't have any extension to change my user agent, and even if I put Firefox in "Troubleshooting Mode" to disable all extensions and reload without cache, I still see my browsers sending `x86_64 ... Firefox/120.0` which is doubly incorrect since I'm on aarch64 version 138.0. My `about:config` says the `x86_64 ... Firefox/120.0` value is the default unmodified value, so I'm guessing it's baked in anti-fingerprinting by either Mozilla or Fedora? Strange.

![Image](https://github.com/user-attachments/assets/a711b50f-0ec4-41d5-ac1d-edcbcbef022d)

**Comment by anewuser** [comment]
Please go to [`about:config`](https://support.mozilla.org/kb/about-config-editor-firefox) and look up `general.useragent`. The only result I get for it is `general.useragent.compatMode.firefox`, and it's set to `false`. 

If you see `general.useragent.override` or a similar preference, delete it and then restart Firefox.

**Comment by nettyso** [comment]
For someone with that username you certainly know a lot! /j

The value cannot be deleted on my end, only "Reset". If I set it to a blank string then Firefox doesn't send the header at all (which is obvs no good).

![Image](https://github.com/user-attachments/assets/e61cef4c-da77-4800-a21c-9ee66606c8ee) 

I thought maybe it was `privacy.resistFingerprinting` but played with that and no change, plus the docs say it only rounds the agent to the nearest major version, not 18 versions back haha. I looked for user.js in all the profiles under `~/.mozilla/` and for policy templates but no dice.

If it bothers me in the future I'll try resetting my profile and maybe also try the non-Fedora version (like Flatpak) to compare. It might be set somewhere in https://src.fedoraproject.org/rpms/firefox/tree/rawhide but I'm a bit busy to go check. Also I feel bad for hijacking this thread. Thank you anyway tho!

**Comment by anewuser** [comment]
Just to make it clear for everybody else who sees that warning: *something* is making it look like you're using an older version. That's bad for your privacy, as you stand out from other Firefox users. If you can't find out what is causing this, [please file a bug report](https://bugzilla.mozilla.org/).
