### ISSUE TITLE
Not able to hide audio timestamp

### ISSUE THREAD

**Issue by shivam725** [mozilla/addons#1466]
Hi, I want to hide the elapsed timestamp of an audio tag in firefox but I am not able to do so. I was able to find a solution for chrome and edge.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/77317158/222156896-03fc16bc-2d6f-4a81-8c4e-2d625ad9bcab.png">

I want to hide the highlighted field but I am not able to access this element. Please advise on how to proceed.

**Comment by diox** [comment]
Hi,

This is not an issue with AMO/addons. Such questions would be best asked on https://discourse.mozilla.org/.
