### ISSUE TITLE
I can't reset my Password at Firefox

### ISSUE THREAD

**Issue by heidi-udo** [mozilla/addons#1467]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by heidi-udo** [comment]
I tried to reset my firefox password, it is not possible

**Comment by diox** [comment]
Hi,

I'm not sure what you are referring to, but it doesn't look like an issue on addons.mozilla.org itself. If you are having trouble with Firefox Accounts, I'd start at https://support.mozilla.org/en-US/kb/change-your-firefox-accounts-password
