### ISSUE TITLE
Error installing add-ons on Firefox for Android

### ISSUE THREAD

**Issue by hodrakir** [mozilla/addons#1468]
When I try to install any addons I get an error "failed to install..."
Have latest version of Firefox under Android 11 (110.1.0 (Build #2015936099))
![Screenshot_2023-03-04-09-48-07-254_org mozilla firefox](https://user-images.githubusercontent.com/127043859/222975094-9ea185f0-1299-49c3-8323-24ef8ff29965.jpg)

**Comment by AlexandraMoga** [comment]
I could not reproduce the issue. I'm also on Android 11 with the latest version of Firefox but addons are installing for me.
