### ISSUE TITLE
Proposal: Consider running tests on GitHub Actions in addition to Circle CI

### ISSUE THREAD

**Issue by bershanskiy** [mozilla/addons#1469]
### Describe the problem and steps to reproduce it:

This is not a bug but rather a proposal: use GitHub Actions CI _in addition_ to Circle CI.

### What happened?

1. Sign into Circle CI and grant it access to GitHub account in order to run jobs on PRs
2. Go Circle CI access settings on https://github.com/settings/connections/applications/78a2ba87f071c28e65bb
3. Observe that Circle CI requires access to private repositories on GitHub without any way to revoke this access while keeping 

![image](https://user-images.githubusercontent.com/45960703/219701935-25681f1d-3543-4b28-abf5-a6dd60807581.png)

### What did you expect to happen?

Users have a choice to run CI jobs (tests) on a CI service following follows least-privilege principle (e.g., without granting "Full control of private repositories").

### Anything else we should know?

Back in 2020 I helped BCD try out GitHub Actions for their needs (in addition to Travis CI at the time), after a while BCD switched to GitHub Actions exclusively. Here I propose to run tests on GitHub Actions in addition to Circle CI and look how it works.

**Comment by willdurand** [comment]
I moved the issue to the umbrella repo since this kind of change should be done across all our repos.
