### ISSUE TITLE
.es6 files are not syntax-highlighted and (probably) not code-analyzed

### ISSUE THREAD

**Issue by dertuxmalwieder** [mozilla/addons#147]
While trying to review Snap Links Plus whose newest version is rewritten as .es6 files, I noticed that there is no syntax highlighting, meaning that the files are not recognized properly as ECMAScript.

https://addons.mozilla.org/de/editors/review/snaplinksplus

I somehow suspect that there is no validation either for the very same reason.

**Comment by andymckay** [comment]
No validation would be a concern, can you confirm or deny that?

**Comment by wagnerand** [comment]
Yeah this is concerning. I hope fixing it is as easy as just telling the linter/validator to handle .es6 files like .js files. I'll try to get to it tomorrow if no one else does first.

**Comment by tofumatt** [comment]
Indeed that is all it would take, the relevant code would be in
src/linter.js, where there is a switch case to get scanner from filename.

- tofumatt

**Comment by andymckay** [comment]
Is .es6 a standard or special suffix? Does it mean anything? If we are relying on the file extension for validation, could i just make up a different extension like `.es-lets-slip-this-by-the-reviewer` and stuff all my JS in there?

**Comment by wagnerand** [comment]
Afaik, there is no standardized suffix for es6 specifically, although some developers use .es6 to indicate their file uses es6 features.
@andymckay I get your point about using random extensions, although in this case I don't think the developer tried to game us.

I'm fine with either adding `.es6` as it seems quite popular or WONTFIXing this, but then we'd need to require developers to use `.js` and `.jsm` only.

@kewisch @eviljeff your opinion?

**Comment by eviljeff** [comment]
In an ideal world we'd scan every file and only bail once we realised it wasn't text but I'm not sure how practical that is.  In the meantime adding `.es6` as an alternate to `.js` and `.jsm` seems a reasonable workaround.

**Comment by kewisch** [comment]
Personally I'd like to require developers just use .js instead, but I have indeed seen .es6 as a synonym for "anything that is not classical .js". I don't want to encourage developers that using .es6 is correct, especially since they might eventually switch to .es7 just because some file includes ES7 features.

**Comment by wagnerand** [comment]
Closing this as WONTFIX.

**Comment by wagnerand** [comment]
Reviewers that come across this should ask the add-on developer to rename their files to `.js`.

**Comment by erosman** [comment]
> Reviewers that come across this should ask the add-on developer to rename their files to .js.

Off-topic: Just for info, is that a rejection?
