### ISSUE TITLE
Confirmation code via email does not arrive

### ISSUE THREAD

**Issue by MoritzKa** [mozilla/addons#1472]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
I am logged in here: https://addons.mozilla.org/de/developers/addons
now I would like to log into our developer account: https://accounts.firefox.com/settings?uid=c739c3f5cd4643cb91f97cdb7db45bd6&email=extension%40getalby.com&entrypoint=addons
I see this screen and wait for the confirmation code to arrive: 

![zmcjuXIQe5](https://user-images.githubusercontent.com/13707997/224118288-446203fb-9a58-48c5-87c1-6e1f631c5ae4.png)

### What did you expect to happen?
The confirmation code should arrive in the inbox of the indicated email address. 

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Hi,

You'll find more information about this, and a way to directly contact support, over on https://support.mozilla.org/en-US/kb/im-having-problems-confirming-my-firefox-account
