### ISSUE TITLE
你们的账户一直是一个谜，使用体验很差

### ISSUE THREAD

**Issue by WangJincheng4869** [mozilla/addons#1475]
我已经有了一个账户`wangjincheng4869@vip.qq.com`，但是我使用该账户登录论坛时却让我使用此邮箱注册账户（我的浏览器就是使用此账户登录的），这就很玄学。并不会像微软、谷歌那样有统一的账户，这用起来体验非常差

**Comment by wendavid552** [comment]
直接Continue with firefox就可以了吧？

**Comment by WangJincheng4869** [comment]
> 直接Continue with firefox就可以了吧？

没有看到这个按钮啊

![动画](https://user-images.githubusercontent.com/41162158/230806658-fe4c1f9f-d5ba-46a8-bf08-13772c7d9085.png)

**Comment by wagnerand** [comment]
Firefox Accounts is a single-sign-on solution for many of Mozilla's properties.
