### ISSUE TITLE
[Task]: use new jobs/.../decision api to make decisions on job

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#14779]
### Description

resolves https://mozilla-hub.atlassian.net/browse/AMO2-723

Previously if AMO wanted to resolve a cinder job with a decision via it’s api the only option was to create a decision on the entity, and then close the job.  Now there is a new create decision on job api [endpoint](https://docs.cinder.co/reference/api_create_decision_on_job) which will allow us to do it in a single step, and associate the decision with the job correctly.

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [x] jobs/xx/decision is used for decisions on jobs
- [x] use of close job is removed
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-750)

**Comment by eviljeff** [comment]
To test this issue:
- take an action in the reviewer tools that resolves a job - e.g. a job that contains abuse reports, or an appeal
- look in cinder in the [AMO dev addon infringement](https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjI1/details) queue, and the "Jobs" tab for that queue.
- see the decision made in the reviewer tools there, resolving the job in cinder
- The decision should also be in the "Decisions" tab as resolved (as opposed to status "Cancelled" like the older jobs)

**Comment by ioanarusiczki** [comment]
I see the status "Closed" instead of "Cancelled" and in[ Decisions tab](https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjI2/details/decisions?filters=%7B%7D) the AMO reject action, I'll continue this tomorrow , try a couple more scenarios.

**Comment by ioanarusiczki** [comment]
I've added a comment into https://github.com/mozilla/addons/issues/14788#issuecomment-2115208071 so I can follow the unresolved issues there and mark this verified.
