### ISSUE TITLE
Dark Reader and Dark Mode extensions shortcut missing

### ISSUE THREAD

**Issue by thehulkisgreen** [mozilla/addons#1477]
### Describe the problem and steps to reproduce it:
previously there is a shortcut on firefox taskbar for dark reader or dark mode extension.
but now the shortcut icon is missing.

### What happened?
shortcut icon missing in firefox taskbar.

### What did you expect to happen?
to find the shortcut icon in the taskbar.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
the shortcut appears in chrome.

**Comment by diox** [comment]
Hi,

I would report this issue to the developers of the extensions - this is not something we can deal with on addons.mozilla.org.
