### ISSUE TITLE
scopus [Task]: 

### ISSUE THREAD

**Issue by ramsi1148** [mozilla/addons#14770]
### Description
i am not able to download the extension for scopus

### Acceptance Criteria
```
  ### Acceptance Criteria
  - [ ] 
```

### Checks
* [x] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-501)

**Comment by ramsi1148** [comment]
please help me in downloading the extension for scopus

**Comment by eviljeff** [comment]
what is scopus?  We're going to need a lot more details here.

**Comment by diox** [comment]
Please contact Scopus developers as they are the ones that need to fix the link to download their add-on since it's not managed by Mozilla.
