### ISSUE TITLE
Update target_locale of a couple dictionaries to match the xpi

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14774]
### Description

When running the task from https://github.com/mozilla/addons-server/issues/21996 we ran into this issue: https://mozilla.sentry.io/issues/5256019985/?project=6310819

Those 2 dictionaries don't have the right `target_locale` in the database and we couldn't resign them. They should be fixed by someone with admin rights. 

- https://addons.mozilla.org/en-US/firefox/addon/czech-spell-checking-without-d/ (Target locale is cs in database but the add-on targets cs-Cestina)
- https://addons.mozilla.org/en-US/firefox/addon/croatian-dictionary/ (Target locale is hr in database but the add-on targets hr-HR)

Once this is done we can re-run the script and that will pick them up to resign.

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [x] https://addons.mozilla.org/en-US/firefox/addon/czech-spell-checking-without-d/ `target_locale` is changed to `cs-Cestina`
- [x] https://addons.mozilla.org/en-US/firefox/addon/croatian-dictionary/ `target_locale` is changed to `hr-HR`
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-506)

**Comment by wagnerand** [comment]
Target locales have been updated

**Comment by ioanarusiczki** [comment]
Is there something I could test here ?

**Comment by diox** [comment]
All good. The dictionaries show up correctly in https://addons.mozilla.org/en-US/firefox/language-tools/
