### ISSUE TITLE
[Bug]: Searching for "Adobe" returns seemingly unrelated results

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14773]
### What happened?

- [Search for "Adobe" extensions for Firefox](https://addons.mozilla.org/en-US/firefox/search/?q=Adobe&type=extension)

### What did you expect to happen?

Actual:
- https://addons.mozilla.org/en-US/firefox/addon/dobromat/ is found in the results

Expected:
- That extension doesn't mention Adobe and shouldn't be included in the results

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-504)

**Comment by diox** [comment]
I can reproduce with just naming an add-on "Dobromat" in en-US, so I assume it's fuzzy matching being a little too aggressive.

**Comment by diox** [comment]
It's actually caused by the trigrams matching: `Adobe` is decomposed into `ado`, `dob`, `obe`, and `Dobromat.sk` is decomposed into `dob`, `obr`, `bro`, `rom`, `oma`, `mat` (we stop at punctation). We have a `minimum_should_match` of `66%`, but there are only 3 trigrams in the query, so the minimum ends up being 1.98. That number is rounded down, so we only require 1 to match, and there is exactly one...

Changing the `minimum_should_match` to `67%` solves that particular issue. We could consider bumping it higher and making it dynamic depending on the length too, but that might be enough as an incremental change.

**Comment by KevinMind** [comment]
Is there a reverse scenario we can consider. By bumping 1 percent we force 2 matches instead of 1? Is there a bucket of valid results which would only match with 1 but no longer with 2 we need to worry about? I don't have an example in mind but this is a pretty deep edge case so I wouldn't be too surprised if such a case existed?

Also, based on subjectively looking at the results the first 10 results are totally on point. I'm just wondering what caused this issue to be worth solving? Was it this one edge case in one query or is this a pattern of behavior that has been pointed out.

If so, could you link some other examples?

**Comment by diox** [comment]
I thought the match was so egregiously wrong in this case that the issue was worth solving. I don't have other examples, but users have complained in the past that we were too aggressive in trying to find misspelled content.

I considered the reverse scenario and other string lengths too. I don't see a good reason to only match with a single trigram out of 3: 66% was always an arbitrary number, the goal behind it was to have 2/3 of the trigrams, so changing 66% to 67% is exactly what we want.

As far as other string lengths go, as mentioned in the PR, bumping to 67% also impacts:
- 6 trigrams will now require at least 4 matches against 3 previously (3.96 🠂 4.02)
- 9 trigrams will now require at least 6 matches against 5 previously (5.93 🠂 6.03)
- 12 trigrams will now require at least 8 matches against 7 previously (7.92 🠂 8.04)

All these seem fine and also match the desired behavior of ensuring 2/3 of the trigrams match.

**Comment by diox** [comment]
I should add: I didn't find this, it's part of [the analysis Ed did on search results as part of the Improve search and discovery experience epic](https://docs.google.com/document/d/1G-oW16jYoefulSjdJCiBqwdAknsXmtwCGlVCTvj32rY/edit).

**Comment by diox** [comment]
There is actually another example in the analysis Ed did:
https://addons.mozilla.org/en-US/firefox/addon/extended-color-management/ is returned for a search for "Event". That's because "Event" decomposes into "eve", "ven" and "ent": we only require a single matching trigram, and "Extended Color Management" has "ent" in it. There is more we could do about that but bumping the threshold to 67% would also fix this case.

**Comment by KevinMind** [comment]
This helps a lot thanks.

**Comment by alexandruschek** [comment]
Hello @diox,

I've tried with five letter words including Adobe, I'll leave two examples:
![image](https://github.com/mozilla/addons/assets/139126091/0dcd209c-d2b3-43ee-a123-2d41aeaa8995)
![image](https://github.com/mozilla/addons/assets/139126091/eb9c36ef-3a6d-4aba-b797-6de7d70477fa)
And it works as expected now

But I've noticed something else when it comes to searching with special characters included
I noticed this on dev and i don't know if it's related to this issue:
I tried searching with:
1. $Flagçfox%ç√®å
<img width="1595" alt="image" src="https://github.com/mozilla/addons/assets/139126091/3334bc00-f2fb-44e1-98e0-e67cb0b5c1cc">
2. $casçnew%ç√®å
<img width="1595" alt="image" src="https://github.com/mozilla/addons/assets/139126091/aba43497-de89-43ec-a55d-9f886a2a1d2c">

In first case it should return at least Flagfox, which exists on dev and for the second case: there a lot of addons containing cas and new in the name

If it's a separate issue please let me know and I'll submit it

Thank you!

**Comment by alexandruschek** [comment]
Will mark this as verified fix and open a new issue for the special characters
