### ISSUE TITLE
[Task]: Allow AMO reviewers to mark abuse reports as being invalid

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#14777]
### Description
In Cinder we recently implemented some additional policies, and an associated action, AMO_IGNORE, that resolve abuse reports as invalid without making any judgement on the content they relate to, because the report doesn't contain enough information to allow us to make a decision, or are otherwise not valid.

https://github.com/mozilla/addons/issues/1787 added support in the addons-server webhook, and an appropriate email.

We also need to empower AMO reviewers to take a similar (non-)action.

### Acceptance Criteria
```
  ### Acceptance Criteria
  - [ ] AMO reviewer can resolve a job containing one or more abuse reports as invalid
  - [ ] The reason for the invalidity can be indicated as they don't contain enough information, or is actually add-on feedback that should go to the developer.
  - [ ] Emails added in https://github.com/mozilla/addons/issues/1787 are sent
  - [ ] No action is taken on the add-on and the developer(s) are not notified.
```

### Checks
* [x] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-747)

**Comment by eviljeff** [comment]
TBD how we will allow the reason to be specified.  In cinder we've implemented this with two policies, but we don't expose policies directly in the reviewer tools; and the reviewer-reasons selector pastes the policy text as review text to be sent to the developer.
@wagnerand for any bright ideas on how to cleverly get past this problem

**Comment by wagnerand** [comment]
We might be able to solve this for simple cases using "Clear needs human review", but I think it won't be very practical. It would be quite fragile and likely not sufficient, because we made the decision to resolve all abuse reports in one category at once, while in reality, we might need to ignore some and take action based on some others. We definitely cannot ignore all, and if we action based on all, all of them are eligible to appeal (in case of version approvals of course).
Also, if you clear needs human review without marking the abuse reports as resolved, there is no way to do so anymore, so the order of things and the concurrency would make this option fragile at best.

**Comment by eviljeff** [comment]
@wagnerand 
>because we made the decision to resolve all abuse reports in one category at once,

This wasn't a UX decision made for the reviewer tools - it's a cinder feature/limitation - once reports for a particular entity (add-on) are combined into a job (which we certainly need, for efficiency) they can't be resolved separately

>  while in reality, we might need to ignore some and take action based on some others. We definitely cannot ignore all, and if we action based on all, all of them are eligible to appeal (in case of version approvals of course).

Yes, if one abuse report is valid in a job we'll offer an appeal for all.

**Comment by wagnerand** [comment]
> This wasn't a UX decision made for the reviewer tools - it's a cinder feature/limitation - once reports for a particular entity (add-on) are combined into a job (which we certainly need, for efficiency) they can't be resolved separately

Oh, interesting, I thought that was a UX decision just for reviewer tools. So does that mean, even if we wanted reviewers to make a decision per individual abuse report, we can't?

**Comment by eviljeff** [comment]
> > This wasn't a UX decision made for the reviewer tools - it's a cinder feature/limitation - once reports for a particular entity (add-on) are combined into a job (which we certainly need, for efficiency) they can't be resolved separately
> 
> Oh, interesting, I thought that was a UX decision just for reviewer tools. So does that mean, even if we wanted reviewers to make a decision per individual abuse report, we can't?

correct, decisions can only be made per job (bundle of abuse reports)

**Comment by ioanarusiczki** [comment]
I've started testing, still looking around and I'll update once I'm done with it.

**Comment by ioanarusiczki** [comment]
- after setting up correctly Ignore and Approve actions on dev, I can no longer use "Clear needs human review" to resolve reports or appeals. 

![AMO dev](https://github.com/mozilla/addons/assets/33448286/6c3bdd8f-8110-48a8-b14a-e2a32454e8af)

- to give an example, I tried the scenario when: Content not taken down, reporter is notified and appeals, we confirm the decision. The content stays up, the reporter is notified can no longer appeal. This can be resolved with "Approve" which is sending the correct emails. 
- when using Approve to resolve author appeals https://github.com/mozilla/addons/issues/9485 is still reproducible 
- as mentioned into https://github.com/mozilla/addons/issues/14788#issuecomment-2122554247 Ignore could be chosen from the list but it's not intended.

**Comment by eviljeff** [comment]
>     * when using Approve to resolve author appeals [Extension is escalated to AMO , decision is confirmed after author appeals - no emails sent  #9485](https://github.com/mozilla/addons/issues/9485) is still reproducible

can you clarify?  #9485 is closed as fixed
 
>     * as mentioned into [[Bug]: All amo reviewer actions should be registered in Cinder's Decisions tab  #14788 (comment)](https://github.com/mozilla/addons/issues/14788#issuecomment-2122554247) Ignore could be chosen from the list but it's not intended.

Can you file a follow-up?  I don't think there's much we can do about ignore action coming from cinder directly, but in the reviewer tools we could do something about it before the reviewer is able to submit the form.

**Comment by ioanarusiczki** [comment]
I left a comment there https://github.com/mozilla/addons/issues/9485#issuecomment-2094369883. Also https://github.com/mozilla/addons/issues/1760 was filed for the case when there's no report. To sum up, the email is not the correct one. 

That's what I got today when I used "Approve" from rev tools

![incorrect email sent](https://github.com/mozilla/addons/assets/33448286/40053616-7729-4024-8f55-dd4cff9702ce)

When the flow is under Cinder

![Content not reinstated](https://github.com/mozilla/addons/assets/33448286/1a5c2edb-c2a3-4a7e-a61e-ac06a63b7385)

**Comment by ioanarusiczki** [comment]
I forgot to add: comment section is mandatory when resolving jobs.

![Add a comment](https://github.com/mozilla/addons/assets/33448286/7787b9d0-8a50-45c6-a170-de0ff7c38cde)
