### ISSUE TITLE
[Bug]: [DEV] Searching with special characters will not return any suggestions

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons#14780]
### What happened?

Search for an addon, for example use:
- $Flagçfox%ç√®å
- $casçnew%ç√®å
Observe that no suggestions are shown, even though Flagfox addon exists on dev and plenty of addons were submitted that include cas new
First case:
![image](https://github.com/mozilla/addons/assets/139126091/939b51cd-6d17-4dfc-ae35-14e67085256f)
Second case:
![image](https://github.com/mozilla/addons/assets/139126091/ba4271b9-6ab1-4011-b185-24cb0de4a1ef)

### What did you expect to happen?

Suggestions to be returned:
Image taken from stage:
<img width="1595" alt="image" src="https://github.com/mozilla/addons/assets/139126091/b134c487-90de-47b4-a52c-f2bd82aaf31f">

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-751)

**Comment by diox** [comment]
`$Flagfox%ç√®å` (no `ç` in the middle) would work. So would `$Flag$fox%ç√®å` or `$Flagfox%√®å`. Ultimately `ç` is a valid letter, not a special character to be ignored.
