### ISSUE TITLE
[Bug]: Send the correct email to reporters for "Developer feedback" and "Not enough information"

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14785]
Followup https://github.com/mozilla/addons/issues/1787

### What happened?

1. Send one or multiple reports for an entity 
2. From Cinder go to a specific queue depending on what's been reported and assign job for the report
3. Choose from Ignore action Developer feedback or Not enough information

### What did you expect to happen?

This [email](https://github.com/mozilla/addons/issues/1787#issuecomment-2088654704) should be sent to the reporter.

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by eviljeff** [comment]
It seems this is almost certainly not a code problem, but that the policies neededed resyncing.  I've done that on addons-dev.  Can you retest @ioanarusiczki ?

**Comment by ioanarusiczki** [comment]
For "Developer feedback" the email below is sent -> it's for collections, ratings or users too 

![developer feedback](https://github.com/mozilla/addons/assets/33448286/8bbb4cfc-982b-4bb5-89f8-8046c4af42f7)

For "Not enough information" , same as above , this email is sent for all entities:

![not enough information](https://github.com/mozilla/addons/assets/33448286/df9b426a-110f-4d35-9f51-801a32e06291)


Maybe it's been left out on purpose -> in both cases the second paragraph ends without "at this time" ,  it's "The Rating will therefore not be subject to any moderation action."

**Comment by ioanarusiczki** [comment]
This is only on -dev indeed, on -stage it's still incorrect for now.

**Comment by eviljeff** [comment]
> @eviljeff This is only on -dev indeed, on -stage it's still incorrect for now.

sync'd on stage now too.  (Policies in cinder prod are still in progress, so no sync there yet)

**Comment by eviljeff** [comment]
@wagnerand to press the sync button in django admin on prod when things are ready

**Comment by ioanarusiczki** [comment]
Working now on stage too, 👍 I should also keep in mind there's a sync for policies.
