### ISSUE TITLE
[Task]: Update copy of support options on supressed email page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#14786]
### Description

We want to update the copy for developers getting support when their email is suppressed.

Steps to reproduce:
1. The email address you logged in with should be considered suppressed. 
2. Visit `developers/verify-email`.

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [ ] Copy on the page should say: `If you encounter issues, please see our [troubleshooting suggestions](https://extensionworkshop.com/documentation/publish/developer-accounts/#email-issues?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=devhub) on Firefox Extension Workshop.` instead of `Having trouble? Please contact AMO Admins if you need help.`
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-757)

**Comment by ioanarusiczki** [comment]
I've still to test https://github.com/mozilla/addons/issues/9426#issuecomment-2094368353 properly and I'll try this again today with Kevin's help. Meanwhile I managed to see there's an EW link 

![The EW link](https://github.com/mozilla/addons/assets/33448286/506ab316-816c-4d67-a68e-f896b2df9727)

![email address verification](https://github.com/mozilla/addons/assets/33448286/f1e1bcc0-b662-47a2-b365-e7cfd704b5c2)

**Comment by ioanarusiczki** [comment]
@wagnerand 

I've noticed that "please notify [amo-admins@mozilla.com](mailto:amo-admins@mozilla.com)." is also sent into emails 

![the email sent](https://github.com/mozilla/addons/assets/33448286/069d1b88-c1a1-4904-9b9f-be8371e2b3f1)

**Comment by wagnerand** [comment]
@ioanarusiczki thank oyu for pointing that out, reopening the ticket.

**Comment by wagnerand** [comment]
I had a look at the code and it seems we are using the exact same phrasing in the [confirmation email](https://github.com/mozilla/addons-server/blob/ed62036df0d3c63b36cbf61f78e2155272cf83f2/src/olympia/devhub/templates/devhub/emails/api_key_confirmation.ltxt#L8) for requesting a new API key.

Therefore, I'd suggest we leave it in here as well for the time being and then make a decision later about both these locations @diox @abyrne-moz
