### ISSUE TITLE
[Task]: Increase caching duration of AMO pages / API

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14798]
### Description

At the moment the default caching duration for AMO pages and API is 3 minutes. This was a compromise between performance, freshness and cost we made rather arbitrarily back when we added HTTP caching and then put everything behind the CDN in 2021.

We'd like to revisit this to reduce costs, and increase the default duration to 6 minutes for all pages/API endpoints. API endpoints with a custom (generally higher) value should not be affected.

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [x] AMO pages have a default cache duration of 6 minutes instead of 3
- [x] AMO API endpoints have a default cache duration of 6 minutes instead of 3
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-775)

**Comment by ioanarusiczki** [comment]
I verified the endpoints below, non-authenticated:  `x-Cache` is "Hit from cloudfront" and max-age = 360 

search
addon detail
addon versions
primary hero shelf
Shelves api
recommendations api
account endpoint
ratings
collections list
collection add-ons detail

I've still to do some frontend checks tomorrow.

**Comment by ioanarusiczki** [comment]
Did some frontend checks on the addon detail page, collection details, all versions page, ratings and reviews, user profile with Edge, Chrome and Firefox.

I see it's taking longer than before (and definitely 3+ minutes) for an update to be displayed with  non authenticated users.

With authentication all changes are visible immediately.
