### ISSUE TITLE
[Bug]: Several pending rejections for the same version leading to using the wrong rejection message

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#14793]
### What happened?

When a version has multiple delayed-rejections pending (issues on different days), when the delay times out, we seem to use the copy of the first delayed-rejection, instead of the last.

STR (not verified, but we believe this is what happened on prod):
1. A developer submits an add-on
2. A reviewer delay-rejects with message "A"
3. A few days later, a reviewer delay-rejects with message "B" (this can happen when A was missing source code which was provided by the developer in the meantime)
4. When the delay times out, the rejection is executed with reason "A"

### What did you expect to happen?

When the delay times out, the rejection is executed with reason "B" (the copy of the _last_ delayed-rejection issued).

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-769)

**Comment by ioanarusiczki** [comment]
I tried with this[ version](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630912)

1. delay rejected with reason A 
2. sent the source code , the version shows up in the Manual Review queue
3. delay rejected with reason B
4. waited for the delay to expire (been changing it from admin to get the email today)

it's reason A in the final email (probably content is a bit different, I've the prefs for abuse reports set and it's also sending an appeal url)

![delay rejected with reason A](https://github.com/mozilla/addons/assets/33448286/f8396fc1-5637-4cc1-bcec-cb1304b6314d)

**Comment by ioanarusiczki** [comment]
I've 2 add-ons set with delayed rejections, I'll let them expire and then check the final email sent.

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/630914
and
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630916

**Comment by ioanarusiczki** [comment]
This is verified on -dev 

![reasonB when rejected](https://github.com/mozilla/addons/assets/33448286/0041e289-147d-4a1e-9ee1-c212298d36ba)

![reason B final email](https://github.com/mozilla/addons/assets/33448286/2534e318-abb5-4c7a-9e89-883d4fed44e0)
