### ISSUE TITLE
[Bug]: Fix digest not being read.

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#14790]
### What happened?
Our deployment jobs are expecting to be able to read the digest of our tagged image as a part of the deployment flow. This is so we can verify the tag has not been updated during the build/deploy workflow. (I am kind of assuming here)

### What did you expect to happen?
digest is grokable by CI

### Is there an existing issue for this?
* [x] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-766)

**Comment by eviljeff** [comment]
needs a title 😛

**Comment by KevinMind** [comment]
Fixed by https://github.com/mozilla/addons-server/pull/22273
