### ISSUE TITLE
Invalid or corrupt add-on file.

### ISSUE THREAD

**Issue by HarlemSquirrel** [mozilla/addons#14796]
### What happened?

Trying to follow [this guide](https://blog.mozilla.org/addons/2022/03/17/new-api-for-submitting-and-updating-add-ons/) to publish our add-on that was removed when the creator deleted their Firefox account several months ago.

https://github.com/keeweb/keeweb-connect/pull/55
https://github.com/keeweb/keeweb-connect/actions/runs/9162885880/job/25190819248?pr=55

```
Uploading 190.27KB file web-ext-artifacts/keeweb_connect-0.3.7.13.zip
response.status: 201
response.body: {
  uuid: '85e4db483b1b4cd1a745ff1138335dc1',
  channel: 'listed',
  processed: false,
  submitted: false,
  url: 'https://addons.mozilla.org/api/v5/addons/upload/85e4db483b1b4cd1a745ff1138335dc1/',
  valid: false,
  validation: null,
  version: null
}
Will check validation status in a 60s...
validationData {
  uuid: '85e4db483b1b4cd1a745ff1138335dc1',
  channel: 'listed',
  processed: true,
  submitted: false,
  url: 'https://addons.mozilla.org/api/v5/addons/upload/85e4db483b1b4cd1a745ff1138335dc1/',
  valid: false,
  validation: {
    errors: 1,
    warnings: 0,
    notices: 0,
    success: false,
    compatibility_summary: { notices: 0, errors: 0, warnings: 0 },
    metadata: { listed: true },
    messages: [ [Object] ],
    message_tree: {},
    ending_tier: 5
  },
  version: null
}
validationData.validation.messages [
  {
    id: [ 'validator', 'unexpected_exception' ],
    message: 'Invalid or corrupt add-on file.',
    description: [
      'Validation was unable to complete successfully due to an unexpected error.',
      'Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU'
    ],
    type: 'error',
    fatal: true,
    tier: 1,
    for_appversions: null,
    uid: '35432f419340461897aa8362398339c4'
  }
]
/home/runner/work/keeweb-connect/keeweb-connect/.github/publish-firefox-addon.js:93
            throw new Error('Extension did not validate in time.');
                  ^
Error: Extension did not validate in time.
    at /home/runner/work/keeweb-connect/keeweb-connect/.github/publish-firefox-addon.js:93:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.20.2
Error: Process completed with exit code 1.
```

### What did you expect to happen?

I am able to load the addon using Firefox Developer Edition just fine and the lint returns only a single warning so I expect the addon to publish correctly.

Uploading the same file using the web page I see the same one warning and I am not blocked from uploading and continuing to publish the addon.

![image](https://github.com/mozilla/addons/assets/6445815/11a1df45-2c67-4530-b5dc-6c14c89a2201)

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-773)

**Comment by diox** [comment]
Hi, 

Could you post the exact zip somewhere so we could investigate ?

**Comment by HarlemSquirrel** [comment]
@diox Sure! Here it is
[keeweb_connect-0.3.7.13.zip](https://github.com/mozilla/addons/files/15382864/keeweb_connect-0.3.7.13.zip)

**Comment by diox** [comment]
At first glance I don't see anything wrong with this file. The fact that it works using the Developer Hub upload is quite strange, it's the same validation code underneath.

Could you try with https://github.com/mozilla/web-ext/ instead of your custom JS code to submit an add-on ? It may be a bug in your code or our API docs (Maybe a missing `Content-Type`? Completely wrong file contents ? That error indicates we couldn't open the file as a zip file)

**Comment by HarlemSquirrel** [comment]
OK well using the submission API with `npx web-ext sign --use-submission-api --channel=listed` worked perfectly!
