### ISSUE TITLE
[Task]: Re-add abuse report metadata for abuse reports from Firefox

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#14807]
### Description

Use a new Firefox API to submit abuse reports when available.

For QA: please verify that abuse reports for _installed_ add-ons contain more information in the reviewer tools. The abuse reports should look like the old abuse reports from _before_ DSA. That means having the source URL, origin, method, etc. in the "Install origin / source" column. Please also verify that abuse reports sent with an authenticated user "link" this user to the abuse report in the reviewer tools as well.

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-793)

**Comment by willdurand** [comment]
Please also verify with Firefox for Android

**Comment by ioanarusiczki** [comment]
I've run into an error on -dev when I am authenticated and after the extension is installed. It is only reproducible when I try to send a report from addon manager or the detail page with authentication. If I check "File report anonymously" , unauthenticated on AMO , reports are sent.

![unexpected error](https://github.com/mozilla/addons/assets/33448286/76190005-86f2-43e5-9163-6bd11227befd)
![console](https://github.com/mozilla/addons/assets/33448286/0eb96790-21f5-4000-838f-d6a3d73058c7)

**Comment by willdurand** [comment]
> I've run into an error on -dev when I am authenticated and after the extension is installed. It is only reproducible when I try to send a report from addon manager or the detail page with authentication. If I check "File report anonymously" , unauthenticated on AMO , reports are sent.

I realize a pre-condition was missing in my STR above: the `extensions.addonAbuseReport.url` pref must point to the right AMO env. The pref is configured with AMO prod by default, which should explain the error you're getting.

**Comment by ioanarusiczki** [comment]
I've only set `extensions.abuseReport.amoFormEnabled` true and `extensions.abuseReport.amoFormURL` for dev
Added `extensions.addonAbuseReport.url` and it's working now 👍

**Comment by ioanarusiczki** [comment]
From Win10 I've sent reports after installing an extension, theme and then an unlisted extension. 

I see there is information about the addon name, Application and operating system, Install date, Install origin with Origin, Method, Source, Source URL. These are not present when the add-on is reported from the detail pages while the extensions are not installed. 

I tested with
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631072
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630513
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/631230

When the user is not authenticated on AMO and it's sending user information it goes to [admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/29661/change/) to "Reporter name" and "Reporter email" fields and it stays anonymous for Reporter in rev tools. Client id is also available in admin tools.  -> should be expected 

I've problems on Android, I tried to make a custom build but I could only make a quick one for 125.0a1. I had no idea all the process moved to mozilla-central until today but I found out reading https://github.com/mozilla-mobile/firefox-android

I could install an addon then from addon manager I've sent reports for https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/497311 -> there is no information but I have the feeling either I am not using correct prefs or I need a newer Nightly build.

![rev tools with android](https://github.com/mozilla/addons/assets/33448286/5c16c744-fc04-47d8-a04b-f488e2ed5490)


Tried with all prefs modified

![fenixprefs](https://github.com/mozilla/addons/assets/33448286/23d16378-95ad-48d9-8236-becdb9a9634e)

**Comment by ioanarusiczki** [comment]
@willdurand 

I've installed multiple add-ons on -dev with Fenix 128.0a1 and sent reports from the detail pages.

Some examples:
rev tools https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630510
admin tools https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/29715/change/

As you suggested I tried to use a dev and prod common GUID install the addon from Extensions manager and then send the report having all necessary prefs set for abuse reports (I also modified manually the abuse report URL to redirect to -dev. )

It worked with Ublock Origin and Decentraleyes. It's a different Origin (the amo prod detail page instead of dev's) , Method is "Other". 

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/502834
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/492486

![from Android](https://github.com/mozilla/addons/assets/33448286/c71da335-8a96-4d0f-b0c6-d14e021181f3)

**Comment by ioanarusiczki** [comment]
Also verified on AMO stage with [Firefox Relay ](https://reviewers.addons.allizom.org/en-US/reviewers/review/1004682)

![AMO stage reports](https://github.com/mozilla/addons/assets/33448286/4ece0a91-0c69-4a13-ab87-488dff8d2897)
