### ISSUE TITLE
[Task]: Remove Accessibility category from AMO

### ISSUE THREAD

**Issue by esullivan-moz** [mozilla/addons#14801]
### Description
We are going to launch an accessibility collection to replace the accessibility category. [This file](https://docs.google.com/spreadsheets/d/1eMb4C-d1YnR_tsUJyySWFscica6rVcwBew8dkau-K24/edit?usp=sharing) details the list of add-ons that only carry the Accessibility tag and would need to have a category label added. We also need to removed the Accessibility category from the options developers can select categories from.

### Acceptance Criteria
When Accessibility category has been removed from AMO and it is no longer available as an option for developers to select when submitting versions.

### Checks
* [x] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-778)

**Comment by alexandruschek** [comment]
Hello,

I finished checking this issue on -DEV and -STAGE environment and the accessibility category is removed. Any addon that was in that category is moved to "Other". Marking this as verified fix.

Thank you!
