### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by tgavron** [mozilla/addons#1480]
I am working on porting an extension to Firefox which was initially developed for Chrome. I was able to get the extension working fully from the local temporary add on debugging menu. This exact zip loads correctly and functions as expected. I read that the id for the browser specific settings needed to be set, so I did that. I also read that the standard windows zip protocol can be incorrect due to having \ in directories, so I used 7 zip. Is there any way to debug the validator and find out what the actual error is?

Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
* This was during the submission of a new add-on.

* Whether your add-on is listed or unlisted.
* unlisted

* The URL where you submitted the add-on.
* https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted

* The approximate time you submitted the add-on, with timezone.
* 11:40am CST

[COL SelectionPicker FIREFOX.zip](https://github.com/mozilla/addons/files/11161202/COL.SelectionPicker.FIREFOX.zip)

![Capture](https://user-images.githubusercontent.com/129982965/230149977-30e039f7-8a6e-4e5b-b3c9-b21ba5d1d12b.PNG)

**Comment by diox** [comment]
Hi,

It looks like this hit an issue in our private scanners because of a stray `__MACOSX/` directory pointing to a directory `SelectionPicker Test` that doesn't exist anymore. Can you remove it ?

**Comment by tgavron** [comment]
> 

Removing this worked, I believe it was left in from a previous zip version. Thank You
