### ISSUE TITLE
When sending an extension for review, an error occurred in determining the length of the name[Bug]: 

### ISSUE THREAD

**Issue by LebedevIV** [mozilla/addons#14805]
### What happened?

When sending an extension, check at the step (page) "Submit a New Add-on:Describe Add-on"
(https://addons.mozilla.org/en-US/developers/addon/ozon-wildberries-%D0%B8-simaland-%D1%81%D0%BE/submit/details)
I keep getting the error "Ensure this value has at most 50 characters (it has 67)." , but the name is shorter than 50 characters (“Ozon, Wildberries, Simaland: reviews sort by rait”), and I made the names even shorter - this does not change anything and the error will repeat itself.
![2024-05-24_16-45-13](https://github.com/mozilla/addons/assets/1265279/5ac4d89c-8ecb-4538-a815-093b910492d3)

### What did you expect to happen?

The title length must be checked correctly. In addition, after correcting the extension address in the Add-on URL and changing the name of the extension, the Add-on URL should not be reset and regenerated.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-791)

**Comment by LebedevIV** [comment]
I found the reason in the page code: when editing the name, the change affects only the locale in the Input, and the main name in English in the first Input is hidden and contains a name with an exceeding length. Apparently, you need access to both Inputs.
![2024-05-25_13-04-38](https://github.com/mozilla/addons/assets/1265279/6d817062-df4f-41dd-aa61-41fc1e0516b0)

**Comment by diox** [comment]
Hi,

This is unfortunately an old issue already reported in https://github.com/mozilla/addons/issues/1899
