### ISSUE TITLE
Infinite loop when trying to access "all versions" of a langpack

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#14815]
## STR

Go to https://addons.mozilla.org/en-US/firefox/addon/langpack-ach@firefox.mozilla.org/versions/, which is the URL to the "All versions" page for an add-on and we use the GUID in the URL instead of the slug

## Expected

The page loads and displays all the versions for that langpack.

## Actual

Infinite loop, yay. This isn't strictly related to langpacks, the page would break equally with an extension GUID in the URL.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-801)

**Comment by ioanarusiczki** [comment]
I knew it's somehow familiar https://github.com/mozilla/addons/issues/2192

I'm unable to reproduce this on dev or stage
https://addons.allizom.org/en-US/firefox/addon/Clipper@OneNote.com/versions/
https://addons-dev.allizom.org/en-US/firefox/addon/azdev1@dictionaries.addons.mozilla.org/versions/

but I can reproduce on prod with Firefox, page loads for Chrome and Edge.

**Comment by willdurand** [comment]
ah, right. Let's close this bug then. See #2192.
