### ISSUE TITLE
Add on uploader not completing

### ISSUE THREAD

**Issue by Georg7** [mozilla/addons#1481]
### Describe the problem and steps to reproduce it:
1. Go here: https://addons.mozilla.org/en-US/developers/addon/better-research/versions/submit/
2. Upload a valid zip file
3. File validation is never completing

### What happened?
Once file is uploaded it should redirect to next step. Instead nothing happens. File upload progress shows as complete but cannot proceed to next step.

### What did you expect to happen?
Expected: Automatic redirection/popup to proceed with submission.

### Anything else we should know?
Firefox v: 111.0.1 (64-bit)

<img width="1044" alt="Screenshot 2023-04-08 at 8 29 53 AM" src="https://user-images.githubusercontent.com/7827962/230695645-60f5494f-137d-4c41-a39c-7a22e9a05e7e.png">

**Comment by diox** [comment]
Hi,

Could you attach the zip to this issue ?

**Comment by grimsteel** [comment]
It seems like a lot of people are experiencing this. There's a Mozilla Discourse post:

https://discourse.mozilla.org/t/113089

Relevant details (taken from the thread):
* Neither the web interface nor web-ext works
* Neither new addons nor updates for existing addons work
* Neither MV2 nor MV3 work
* Clearing browser data and changing networks don't work
* Looking at the network requests reveals that it's polling an endpoint, which always returns a response with error as null.
* Going to the "full_report_url" field in that response shows this page:
  ![image](https://user-images.githubusercontent.com/115331356/230737354-7aa566a0-7339-4955-a4ce-03d8b456f381.png)
* Eventually, both the web interface and web ext error out, saying that the server cannot be reached
* The last successful build for an addon was the 6th. This issue has been happening for about 2 days now

I tried uploading an addon which I know has worked in the past. The same issue occurred

**Comment by PrakmO** [comment]
I also experienced this issue.

**Comment by IMGROOT2** [comment]
Same, I’d really appreciate a fix!

**Comment by bartekplus** [comment]
Same here, hangs when trying to upload my extension: https://github.com/bartekplus/FluentTyper/releases/tag/2023.4.8

**Comment by igorlogius** [comment]
https://discourse.mozilla.org/t/uploading-a-new-addon-or-updating-the-existing-addon-stucks-at-validating/113089/9?u=igorlogius

**Comment by PullRequestTimeout** [comment]
Also having this issue currently!

**Comment by lucasricci** [comment]
Same here

**Comment by razoo-choudhary** [comment]
ASAP fix is needed from the addon team.

**Comment by jfcardinal** [comment]
Same issue for me.

**Comment by carage34** [comment]
Same issue for me as well

**Comment by diox** [comment]
It looks like an issue accessing the files on our worker instances - it affects validation, but also post-processing of images.

Unfortunately because of week-end + easter holidays it might be slow to solve, but we're looking into it.

**Comment by grimsteel** [comment]
I'm able to upload new versions again. Is this fixed?

**Comment by diox** [comment]
Forgot to update this issue, the problem has been mitigated shortly after I posted my previous comment. We still need to keep an eye on it, but for now uploads have resumed as normal yes.

**Comment by diox** [comment]
I'm keeping this opened to look into why this happened and add additional alerting, as well as making sure it's properly fixed.

**Comment by gorhill** [comment]
I just got another failed signing, timed out after an hour waiting for a response.

**Comment by kikang72** [comment]
As of 2023/04/10 8:27am PDT, this is still an issue

**Comment by diox** [comment]
Yeah, it's back...

**Comment by diox** [comment]
We've once again mitigated the issue, and we'll take a proper look at it tomorrow.
