### ISSUE TITLE
[Task]: Remove obsolete references to nginx caching in addons-frontend

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14814]
### Description

We switched all HTTP caching for the frontend to being done by the CDN. nginx caching these days is only used for internal API endpoint.

That means we can remove this:
https://github.com/mozilla/addons-frontend/blob/ac9739da6bd7ffad3ec43c72117116b710bb5d6b/src/amo/server/base.js#L408-L410
```javascript
          // The following is for backwards-compatibility until we have
          // switched nginx to obey Cache-Control instead.
          res.set('X-Accel-Expires', '360');
```

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] Obsolete code is removed and caching through CDN still works
  ```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-800)

**Comment by alexandruschek** [comment]
Hello,

I checked on DEV environment after the model used on this issue: https://github.com/mozilla/addons/issues/14798
Everything worked as expected nothing unusual encountered, I'm adding the verified fix label here

Thank you!
