### ISSUE TITLE
[Task]: The "Provide more details" field in abuse report form should be mandatory

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14816]
### Description

In the abuse report form, "Provide more details" field needs to be mandatory instead of optional to ensure that we have at least some more information on the reported category.

(This is a re-file of https://mozilla-hub.atlassian.net/browse/AMOENG-613 to make it exist on GitHub side)

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] "Provide more details" label no longer indicates it's optional
  - [ ] The form can no longer be submitted if the "Provide more details" field is empty
  ```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-802)

**Comment by ioanarusiczki** [comment]
Field is mandatory , verified on AMO stage Win(10).

![provide more details](https://github.com/mozilla/addons/assets/33448286/12a2d1e5-43c9-4e4e-acfe-bb0e1188b731)

![Edge and Chrome](https://github.com/mozilla/addons/assets/33448286/dd0b1c50-86d5-47c2-a122-55765261be02)

There's an issue on [Android](https://github.com/mozilla/addons/issues/2208) , I'll update there and mark this verified.
