### ISSUE TITLE
[Bug]: Cannot access admin in local developer instance if github email does not end with mozilla.com

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#14811]
### What happened?

When setting up the default user in local instances, we take the email in the git config. This makes accessing the admin tools impossible, if the email is not a mozilla.com email (because we check for that in `UserProfile.is_staff()`. Since this is the only user with admin access, it is also not fixable without a trip to the mysql client.

### What did you expect to happen?

I should be able to access the admin tools regardless of what email I use.

Let's hard-code the user to a mozilla.com address.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-797)

**Comment by ioanarusiczki** [comment]
@wagnerand 

Not sure I understood but on AMO dev I've no problems accessing admin tools with my mozilla account which is also linked to github.
Then I tried to access admin with a gmail account but I am not allowed ( used to be the expected).

**Comment by diox** [comment]
This is purely for local development. Doesn't need QA.

**Comment by ioanarusiczki** [comment]
I suspected so.
