### ISSUE TITLE
[Bug]: Reviewer tools: Cannot distinguish human instant-rejection from automated expired delayed rejection

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#14810]
### What happened?

https://github.com/mozilla/addons/issues/8605 started attributing the expired delayed rejection to the reviewer who issued it. At the time, we were able to distinguish the two due to the distinct review message used when the delayed rejection becomes effective. With DSA, we have to use the same review message which makes them indistinguishable.

### What did you expect to happen?

A human instant-rejection should be clearly distinguishable from an automated expired delayed rejection, both on the reviewer tools pages and in the database, to generate accurate metrics.

Therefore, we should introduce new specific actions for expired delayed rejections to the activity log.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-796)

**Comment by ioanarusiczki** [comment]
I'm going to set some delayed rejections.

**Comment by ioanarusiczki** [comment]
I've tested with 

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631370
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631371
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631372

activity log in admin: 

![admin dev](https://github.com/mozilla/addons/assets/33448286/287ab972-7081-4d31-ab4d-b84c1d517048)

rev tools:

![Testing_delay rejections](https://github.com/mozilla/addons/assets/33448286/51850dc1-e927-4f91-aa56-879d31b1bf05)



For 631371 (static theme) seems like I didn't get an email , should have been sent on June 9, 2024 about the extension going to be disabled the next day.  
I found the emails sent in fakemail for the other 2 extensions: [631370](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/188031/change/) and [631372](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/188032/change/). I'll see what happens for the theme set for rejection for https://github.com/mozilla/addons/issues/14818#issuecomment-2157716290
