### ISSUE TITLE
[Bug]: In a dark style, the note font is in the background color selections and is not visible

### ISSUE THREAD

**Issue by PhoenixIndigo** [mozilla/addons#14822]
### What happened?

In a dark style, the note font is in the background color selections and is not visible
https://addons.mozilla.org/ru/firefox/collections/17366156/My-extensions/?page=1
<details><summary>Details</summary>
<p>

![](https://github.com/mozilla/addons/assets/107413021/19dbd71f-dc30-4503-9b22-fb32941e7de4)

</p>
</details> 

### What did you expect to happen?

Note visibility in dark style

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-811)

**Comment by PhoenixIndigo** [comment]
Firefox
Website appearance Dark

**Comment by diox** [comment]
mmm, I can't reproduce myself when using Dark website appearance (that preference is ignored by AMO). What version of Firefox are you using ?

**Comment by PhoenixIndigo** [comment]
127
<details><summary>Details</summary>
<p>

![](https://github.com/mozilla/addons/assets/107413021/e34f62b2-97b8-46b5-9a7e-fa2c4a29f2e6)

</p>
</details>

**Comment by diox** [comment]
Are you using an extension for Dark Mode and have bypassed restrictions preventing it from running on addons.mozilla.org ?

**Comment by PhoenixIndigo** [comment]
Firefox extensions do not work on AMO

**Comment by PhoenixIndigo** [comment]
Windows 11 23H2

**Comment by PhoenixIndigo** [comment]
I have added:
https://github.com/black7375/Firefox-UI-Fix/releases Lepton-Photon-Style.zip
https://github.com/black7375/Firefox-UI-Fix?tab=readme-ov-file#installation-guide
