### ISSUE TITLE
[Task]: Upgrade pkcs7 digest algorithm to SHA-256

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#14828]
We currently dual sign all extensions. One of the signatures is PKCS#7 + SHA-1, see: https://github.com/mozilla/addons-server/blob/8f08af88323bbb871b51dda42be39d4c1db0021f/src/olympia/lib/crypto/signing.py#L114-L125

This issue is about upgrading to SHA-256, which is supported for the last 7 years ([bug 1357815](https://bugzilla.mozilla.org/show_bug.cgi?id=1357815)). The addons pipeline (for privileged add-ons) is already using SHA-256.

While this is a minor change at first glance, it is still good to have a feature flag if things go south.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-818)

**Comment by diox** [comment]
Dupe of your own issue https://github.com/mozilla/addons/issues/14804 ?

**Comment by willdurand** [comment]
sigh, yeah. I couldn't retrieve it before filing this one :|
