### ISSUE TITLE
[Bug]: Bookworm tls handshake timeout

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#14827]
### What happened?

When building the docker image in github actions I've seen this error a few times. Re-running always fixes it but want to track this for posterity.

```
#3 ERROR: failed to do request: Head "https://registry-1.docker.io/v2/library/python/manifests/3.11-slim-bookworm": net/http: TLS handshake timeout
------
 > [internal] load metadata for docker.io/library/python:3.11-slim-bookworm:
------
Dockerfile:5
--------------------
   3 |     ####################################################################################################
   4 |     
   5 | >>> FROM python:3.11-slim-bookworm as olympia
   6 |     
   7 |     ENV OLYMPIA_UID=9500
--------------------
ERROR: failed to solve: python:3.11-slim-bookworm: failed to resolve source metadata for docker.io/library/python:3.11-slim-bookworm: failed to do request: Head "https://registry-1.docker.io/v2/library/python/manifests/3.11-slim-bookworm": net/http: TLS handshake timeout
Error: buildx bake failed with: ERROR: failed to solve: python:3.11-slim-bookworm: failed to resolve source metadata for docker.io/library/python:3.11-slim-bookworm: failed to do request: Head "https://registry-1.docker.io/v2/library/python/manifests/3.11-slim-bookworm": net/http: TLS handshake timeout
```

### What did you expect to happen?

Should just work.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-817)

**Comment by chrstinalin** [comment]
Same behaviour occurred for me while using Docker Desktop. The fix for me was logging out via `docker logout` before trying again, which succeeded.

![image](https://github.com/mozilla/addons/assets/44586776/c6d5dc00-96d5-43d0-8f2c-a7ef078799a5)

**Comment by diox** [comment]
FWIW the error is slightly different in your case since you got a 401 error - where in the original we got a TLS timeout error.

**Comment by diox** [comment]
Hasn't happened since.
