### ISSUE TITLE
[Bug]: Auto-approval is temporarily disabled erroneously 

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#14836]
### What happened?

STR:

1. Submit version v1. 
2. Delay-reject v1. (At this point, `auto_approval_disabled_until_next_approval` is set to `True`)
3. Submit v2 before the delayed rejection of v1 becomes effective.
4. Manually approve v2 (because auto-approval is disabled as per (2)) before the delayed rejection of v1 becomes effective. (`auto_approval_disabled_until_next_approval` is set to `False`)
5. The delayed rejection of v1 becomes effective. (`auto_approval_disabled_until_next_approval` is set to `True` again).

### What did you expect to happen?

At (5), `auto_approval_disabled_until_next_approval` should not be set to `True` again because a subsequent version was manually reviewed and approved in the meantime.

I _think_ what we could do here is only set `auto_approval_disabled_until_next_approval` to `True` when the delayed rejection is issued, but not when it becomes effective, but I am wary of side effects.

~Also, we probably want to set `auto_approval_disabled_until_next_approval` to `True` `False` in `clear_pending_rejection_multiple_versions`. I played this through in my head and checked that a rejection resets `VersionReviewerFlags.pending_rejection`, which could lead to another race condition otherwise, but I'd like a second pair of eyes to see if  missed another edge case.~

The above should be done analogue for `auto_approval_disabled_until_next_approval_unlisted`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-832)

**Comment by diox** [comment]
We probably want something like:
```diff
diff --git a/src/olympia/reviewers/utils.py b/src/olympia/reviewers/utils.py
index 6d19c02587..ca7fbcc9af 100644
--- a/src/olympia/reviewers/utils.py
+++ b/src/olympia/reviewers/utils.py
@@ -1338,26 +1338,27 @@ class ReviewBase:
                     ),
                 )
 
-        # A rejection (delayed or not) implies the next version should be
+        addonreviewerflags = {}
+        # A human rejection (delayed or not) implies the next version should be
         # manually reviewed.
         auto_approval_disabled_until_next_approval_flag = (
             'auto_approval_disabled_until_next_approval'
             if channel == amo.CHANNEL_LISTED
             else 'auto_approval_disabled_until_next_approval_unlisted'
         )
-        addonreviewerflags = {
-            auto_approval_disabled_until_next_approval_flag: True,
-        }
+        if self.human_review:
+            addonreviewerflags[auto_approval_disabled_until_next_approval_flag] = True
         if pending_rejection_deadline:
             # Developers should be notified again once the deadline is close.
             addonreviewerflags['notified_about_expiring_delayed_rejections'] = False
         else:
             # An immediate rejection might require the add-on status to change.
             self.addon.update_status()
-        AddonReviewerFlags.objects.update_or_create(
-            addon=self.addon,
-            defaults=addonreviewerflags,
-        )
+        if addonreviewerflags:
+            AddonReviewerFlags.objects.update_or_create(
+                addon=self.addon,
+                defaults=addonreviewerflags,
+            )
 
         if actions_to_record:
             # if we didn't record any actions we didn't do anything so nothing to notify
```

**Comment by diox** [comment]
> Also, we probably want to set auto_approval_disabled_until_next_approval to True in clear_pending_rejection_multiple_versions. I played this through in my head and checked that a rejection resets VersionReviewerFlags.pending_rejection, which could lead to another race condition otherwise, but I'd like a second pair of eyes to see if missed another edge case.

Even with my patch above we need to do this part.

**Comment by wagnerand** [comment]
> > Also, we probably want to set auto_approval_disabled_until_next_approval to True in clear_pending_rejection_multiple_versions. I played this through in my head and checked that a rejection resets VersionReviewerFlags.pending_rejection, which could lead to another race condition otherwise, but I'd like a second pair of eyes to see if missed another edge case.
> 
> Even with my patch above we need to do this part.

I crossed that out in the description above, let's skip that for now. It's wrong, I think I meant to set it to `False`, but even that has edge-cases.

**Comment by ioanarusiczki** [comment]
Waiting with these 3 

https://reviewers.addons.allizom.org/en-US/reviewers/review/1028071
https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1028072
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1028073

**Comment by ioanarusiczki** [comment]
`Auto approval disabled until next approval`  and `Auto approval disabled until next approval unlisted`  are set to `False`.

for listed https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/1028071/change/ and https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/1028073/change/

for unlisted https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/1028072/change/
