### ISSUE TITLE
[Bug]: Email template sent when a reviewer asks a developer for more information is incorrect

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#14834]
### What happened?

When an add-ons reviewer uses the review tools to communicate with a developer for a review, the email that is sent to the developer incorrectly states "A reviewer at addons.mozilla.org found an issue"

https://github.com/mozilla/addons-server/blob/3e10c2fc798800169b69493de3a916126f637626/src/olympia/activity/templates/activity/emails/from_reviewer.txt#L11

### What did you expect to happen?

The template should be updated as follows:

> Hello,
> 
> A reviewer at addons.mozilla.org is contacting you regarding version {{ number }} of the add-on {{ name }}. You are receiving this email because {{ email_reason }}.
> 
> *********
> {{ author }} wrote:
> 
> {{ comments|safe }}
> 
> *********
> 
> To respond, please reply to this email or visit {{ url }}.
> 
> 
> Thank you for your attention.
> 
> -- 
> Mozilla Add-ons
> {{ SITE_URL }}

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-830)

**Comment by wagnerand** [comment]
Note that we don't use the reviewer-reply action to ask questions, but to answer questions from the developer or send other comms that do not require review-relevant actions or information from the developer.

Questions that need to be answered in order to conclude a review are sent using a delayed rejection, so that we don't have to keep track manually of all open questions.

**Comment by abyrne-moz** [comment]
Thanks for the clarification - I've edited the ticket description to reflect this.  Do you think the template suggestion I made needs to be modified as well or is it clear enough as is?

**Comment by wagnerand** [comment]
To be honest, I believe it would best to update it with a bit more neutral phrasing. We are explicitly from refraining this action when requesting information.

Maybe something along the lines of:

> A reviewer at addons.mozilla.org is reaching out on version {{ number }} of the add-on {{ name }}. You are receiving this email because {{ email_reason }}.

Please rephrase as you see fit.

**Comment by abyrne-moz** [comment]
Got it - I've updated the text in the ticket to 

>    Hello,
> 
>     A reviewer at addons.mozilla.org is contacting you regarding version {{ number }} of the add-on {{ name }}. You are receiving this email because {{ email_reason }}.
> 
>     {{ author }} wrote:
> 
>     {{ comments|safe }}
> 
>     To respond, please reply to this email or visit {{ url }}.
> 
>     Thank you for your attention.
> 
>     --
>     Mozilla Add-ons
>     {{ SITE_URL }}

**Comment by ioanarusiczki** [comment]
Verified on stage

![listed as author](https://github.com/mozilla/addons/assets/33448286/4eeca9f9-80d8-409f-8dfe-f4f79649363d)
