### ISSUE TITLE
[Task]: Mention max allowable filesize on developer hub when uploading a new version

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#14835]
### Description

The maximum file size supported in the developer hub for submitting an add-on is 200MB, but we do not mention this on the file submission page.  This task is to update the page to mention this limit by appending this text to the upload page.

> The maximum file size accepted is 200 MB. If your add-on is larger than 200 MB, it will fail validation.

![image](https://github.com/mozilla/addons/assets/167891594/e58eb46d-8983-4c71-95e4-e724fb83d03d)

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] New text is displayed on the add-on version upload page
  ```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-831)

**Comment by abyrne-moz** [comment]
This text should also be added to the Source Code submission upload page.

> The maximum file size accepted is 200MB.

![image](https://github.com/mozilla/addons/assets/167891594/dbdf3634-d186-41ac-9628-6df841309020)

**Comment by diox** [comment]
Technically addons-server limits are more complex than that but it's not a bad limit to advertise.

**Comment by diox** [comment]
Added bonus:

Use some JS to trigger size detection when the file input is changed. In that, call [`setCustomValidity()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setCustomValidity) with a custom message if the size is over the limit, and otherwise call it to reset it to `''` if valid. The user would need to change the file if they want to continue.

If going that route though, they'd probably also need to be able to clear the input completely to start over.

**Comment by chrstinalin** [comment]
@diox That sort of sounds like its own separate issue? Or at least seems odd to include alongside this one

**Comment by diox** [comment]
Maybe, yes. We can file another issue, doesn't have to be bundled into that one.

**Comment by diox** [comment]
@chrstinalin now that the dust has settled and we are displaying it in a bunch of places I think we should fix that inconsistency between decimal vs binary format which we've ignored before - display "209.7 MB" is kinda weird. It looks like setting `MAX_UPLOAD_SIZE = 200 * 1000 * 1000` would do the trick.

**Comment by alexandruschek** [comment]
Hello,

I checked on -DEV env, on the submission page, for "on this site" , "on your own" and the "source code" submission page, and the text is now there, the only mention is that instead of 200 mb, it's 209.7 mb

Thank you!

**Comment by alexandruschek** [comment]
Hello, 

I checked again on both ENVs, on -DEV the filesize is 200, but on stage is still 209.

DEV:
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/a34591bb-bf51-4d5f-a596-f02fff14fefe">
STAGE:
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/c253e7d1-d223-477c-9430-6f38190e9b77">


Thank you!

**Comment by ioanarusiczki** [comment]
Message at upload of source code has been modified too at 200MB - on dev. Stage is still with the old numbers , probably this didn't make the stage tag. 

![matches the message at upload](https://github.com/user-attachments/assets/4ff7d920-e1fd-4c05-becc-b6966d363024)

**Comment by ioanarusiczki** [comment]
This is also on -stage now.
