### ISSUE TITLE
[Bug]: blocking accessibility feature: dark mode

### ISSUE THREAD

**Issue by i1li** [mozilla/addons#14832]
### What happened?

The website not only does not support user dark/light mode preferences, (the most basic accessibility feature possible), but even goes so far as to block addons which do provide this accessibility feature. Please stop discriminating against people with sensitive eyes. If you refuse to support accessibility, at least don't block client-side solutions (like the darkreader extension)

### What did you expect to happen?

Basic accessibility

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-826)

**Comment by diox** [comment]
Hi,

Extensions can't run on addons.mozilla.org for security reasons, but you're right that we should honor user's dark mode preferences. There is already an issue filed for this, https://github.com/mozilla/addons/issues/2193, so I'm closing yours in favor of that older one.
