### ISSUE TITLE
AdBlock[Bug]: 

### ISSUE THREAD

**Issue by gusdupont** [mozilla/addons#14837]
### What happened?

When trying to view videos, it seems there is an AdBlock installed that interferes with video playback. I've never knowingly subscribed to AdBlock, so I don't know how to fix this problem.

### What did you expect to happen?

View videos

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-833)

**Comment by gusdupont** [comment]
I am using a MacBook Air with MacOS Monterey software version 12.7.5

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions. If you need general support, visit https://support.mozilla.org. Thank you.
