### ISSUE TITLE
[Bug]: Notifications sent to developers when add-on versions are blocked are inaccurate 

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14831]
### What happened?

When add-on versions are blocked, they are rejected if they weren't already. We do that by calling the same code responsible for executing a non-human multiple rejection action. Since https://github.com/mozilla/addons/issues/9514 this results in an email being sent to the developer (the blocking action itself is hidden to developers/silent).

### What did you expect to happen?

The email being sent has four different problems:
  1. No comments are sent, the developer doesn't get a reason in the email. The email says `Our review found that your content violates the following Mozilla policy or policies:` but then that section is left blank.
  2. The email mentions `Users who have previously installed those versions will be able to continue using them` which is incorrect
  3. The email mentions `You may upload a new version which addresses the policy violation(s)` but that's incorrect if the add-on was force-disabled as part of the block. In fact, if that option was selected when blocking, the developer is not notified that the add-on has been force-disabled at all.
  4. The developer gets a link to appeal in the email. It's already going to be tricky for them because of the first point - they don't know what was the basis of our decision - but reviewers don't currently have a way to unblock an add-on. They can un-reject versions, but they would need a separate action if the add-on was also force-disabled, and it still wouldn't unblock. This could be fixed by someone with admin access though.

It was suggested to stop using the reject multiple versions actions when blocking, and instead make the blocking action send a proper notification. Alternatively we can keep using the reject multiple versions but send additional context to make sure reason are passed and the email contents tweaked accordingly. 

Notes:
 - For 1., at the moment, block reasons are public information (exposed to the outside world on the page describing the block), where as rejection reasons are not. So if we start including that reason in the email, we have to be aware that the wording might be different than for rejections, as it's potentially shown to end-users and not just the developer.
- For 4. a proper fix would have to wait until https://github.com/mozilla/addons/issues/14781 is implemented. In the meantime we could leave it as-is or remove the appeal link in that case.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-824)

**Comment by diox** [comment]
> Alternatively we can keep using the reject multiple versions but send additional context to make sure reason are passed and the email contents tweaked accordingly.

Going with this for now.

For appeals, per discussion in our stand-up meeting, if we can grant an appeal by unrejecting the versions that should be good enough for now - in the rare case where a block would be successfully appealed and would need to be overturned, this can be done separately in the admin tool for now.

**Comment by ioanarusiczki** [comment]
I verified this on AMO stage

![Contents at block](https://github.com/mozilla/addons/assets/33448286/c39274f4-df3d-4b85-93fc-6720f87a36a4)

A followup has been filed https://github.com/mozilla/addons/issues/14842
