### ISSUE TITLE
I [Bug]: home page

### ISSUE THREAD

**Issue by rustysracer** [mozilla/addons#14838]
### What happened?

I was on yahoo.com and it was asking if I would like to make yahoo.com my home page and I said yes but when I click on it it states yahoo.com is not on the list of add ons

### What did you expect to happen?

I  expected to be able to make yahoo.com my home page

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-834)

**Comment by diox** [comment]
Hi,

This issue tracker is for bugs about addons.mozilla.org, not issues with websites such as yahoo.com. I suggest you report the problem to them.
