### ISSUE TITLE
[Task]: Add JWT Authentication to Reviewer API Endpoints.

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#14833]
### Description

Currently, the reviewers endpoints (specifically [`/api/v5/reviewers/addon/(int: addon_id)/versions/(int: version_id)/`](https://mozilla.github.io/addons-server/topics/api/reviewers.html#browse)) returns a response of `"detail": "Authentication credentials were not provided."` and namely lacks the ability to support JWT auth outlined [here](https://mozilla.github.io/addons-server/topics/api/auth.html#api-auth).

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] Reviewers endpoints are able to authenticate JWT tokens as implemented in the docs.
  ```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-828)

**Comment by diox** [comment]
[`/api/v5/reviewers/addon/(int: addon_id)/versions/(int: version_id)/`](https://mozilla.github.io/addons-server/topics/api/reviewers.html#browse) will go away when code-manager is removed so it's probably not necessary to change it.

What we should do is:
- Document that `/api/v5/reviewers/addon/(int: addon_id)/file/(int: file_id)/validation/` exists
- Make sure it's covered by tests
- Add JWT authentication to it
