### ISSUE TITLE
[Task]:  Automate addons-frontend locales extraction

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14848]
### Description

In #5872 we automated addons-server l10n extraction process, we need to do the same for addons-frontend and update [the documentation](https://github.com/mozilla/addons-frontend/blob/master/docs/i18n.md#updating-locales).

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] l10n extraction process for addons-frontend is done automatically after each commit
  - [ ] docs are updated
  ```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-847)

**Comment by diox** [comment]
We can largely re-use addons-server logic, but probably don't need to depend on docker.

**Comment by KevinMind** [comment]
Considerations:
- copy the bash script from addons-server
- copy the logic to detect dependabot and fork
- use setup-node instead of docker to run the extraction
