### ISSUE TITLE
[Bug]: Help text when force enabling an add-on suggests that the comment will be sent to the developer

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#14860]
### What happened?

When force enabling an add-on that was previously force disabled, the text above the comment field says `The comments will be sent to the developer.`. Since this is the same behavior as with force disabling, it will lead to a reviewer believing the comment is sent to the developer. As clarified offline, in fact it isn't. 

<img width="1311" alt="image" src="https://github.com/mozilla/addons/assets/6270406/29aa2fbb-1ace-473c-8255-bb5f9808bcf1">

### What did you expect to happen?

Since the comments textarea content isn't sent out to the developer, we shouldn't say so in the help text to avoid any confusion.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-859)

**Comment by diox** [comment]
Side note: another inconsistency is that when we log the `FORCE_DISABLE` action, we also attach it to the latest version. We don't on `FORCE_ENABLE`, so not only is the comment not sent to the email sent to the developer, but it's also not even available on the review page - the action is in the "Add-on important changes history" section, but comments are not displayed there.

AFAICT the only place where we show the comment at the moment is in the reviewer review log.

**Comment by abhn** [comment]
I find attaching the disable version to the latest version a bit inaccurate. Actions taken on the add-on as a whole should ideally be documented globally, and not on a particular version.

**Comment by diox** [comment]
Yes - but that's a UX issue with reviewer tools in general. Its UI is mostly geared towards actions on specific versions... We don't really have a place in the review page at the moment to display global comments applying to the entire add-on, except for the whiteboards.

**Comment by eviljeff** [comment]
@wagnerand to confirm expected behaviour here.  (I expect it to be that the comments are sent in the email to the developer)

**Comment by wagnerand** [comment]
@eviljeff I think that is more of a question for Legal and T&S what kind of message we need to provide to developers.

**Comment by diox** [comment]
Note that we already do send an email to the developer, with content approved by Legal. It's just that it doesn't include reviewer comments.

**Comment by diox** [comment]
@wagnerand can you sort out expected behavior with whoever needs to validate that and then remove the assignment on you ?

**Comment by wagnerand** [comment]
@eviljeff agreed to raise it into today's meeting since I cannot join due to a conflict.

**Comment by eviljeff** [comment]
Legal says: "Legal risk very low, we should have some comms to developer that their add-on is back up, but not a blocker for DSA_RE."

**Comment by eviljeff** [comment]
I'm going to aim to address this with https://github.com/mozilla/addons/issues/14878

**Comment by eviljeff** [comment]
> I'm going to aim to address this with #14878

fix this by sending the comment to the developer

**Comment by ioanarusiczki** [comment]
Comments are sent to the developer now.  This is mentioned below the reviewer action.

Some weird chars show up but that's been filed https://github.com/mozilla/addons/issues/14901

I've also filed https://github.com/mozilla/addons/issues/14902

This is how the email sent after an appeal looks like: 

![the email sent](https://github.com/mozilla/addons/assets/33448286/276ab184-5ec9-4969-b15e-54581fbe1c79)


In rev tools: 

![rev tools page](https://github.com/mozilla/addons/assets/33448286/09a8d67d-82a2-4fd9-87b1-a6baf979d86f)
