### ISSUE TITLE
Issue regarding mandatory two-factor authentication for users

### ISSUE THREAD

**Issue by zhuzhouhao** [mozilla/addons#1486]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
When I logged into https://addons.mozilla.org/, the website prompted me to set up two-factor authentication. However, I do not need or want to go through this step. I clicked on "cancel setup," but instead of being redirected to the login page, I was logged out. This is disrespectful to the user's choice.
### What did you expect to happen?
When I click on "cancel setup," I am still able to log in to my account.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![image](https://github.com/mozilla/addons/assets/103934764/4b7e1fc8-49c9-47fd-bb00-6480e1239a55)

**Comment by wagnerand** [comment]
Two-factor authentication is required for extension developers: https://blog.mozilla.org/addons/2021/03/11/two-factor-authentication-required-for-extension-developers/
