### ISSUE TITLE
[Bug]: Escape links in <code> blocks

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons#14861]
### What happened?

Hello. Edit the description of an add-on on AMO and add this code tag:

```
<code>This is an example - Example.com News
https://example.com/</code>
```

The server parses the links and outputs:

> 
> `This is an example -` [Example.com](https://example.com/) `News`
> [https://example.com/](https://example.com/)
> 

### What did you expect to happen?

Replacing the dot (`.`) in `example.com` with its corresponding HTML entity (`&#x2E;`) is enough to fix this: `example&#x2E;com`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-860)

**Comment by diox** [comment]
We agree it's a bug but it's not on our short-term roadmap, we're unlikely to fix this. Long-term we probably will look into switching to markdown or something like that.
