### ISSUE TITLE
[Task]: Include canonical <link> for user review pages

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14873]
### Description

Currently, our add-on user review pages:
- Supports a `?score` query parameter to filter the contents
- Don't have a `<link rel=canonical>`
- Have a `<meta name="robots" content="noindex, follow" />` only when a `?review` is passed
- Don't have `<link rel=alternate>` for other languages

We should:
- Add a `<link rel=canonical>` (ignore querystring: the "first" page with no querystring should be the canonical for now)
- Add `<link rel=alternate>` for main languages like we do on other pages
- ~~Add a `<meta name="robots" content="noindex, follow" />` when score is passed~~
- Add a `rel=nofollow` to links on the add-on detail page filtering user reviews by score

Just adding this in `src/amo/pages/AddonReviewList/index.js` should probably take care of the first 2 items:
```jsx
{addon && !reviewId && (
  <HeadLinks />
)}
```

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [ ] `<link rel=canonical>` is set correctly in user review pages
- [ ] `<link rel=alternate>` is set correctly in user review pages
- [ ] `rel=nofollow` is set on links on the add-on detail page filtering user reviews by score
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-872)

**Comment by diox** [comment]
> Add a `<meta name="robots" content="noindex, follow" />` when score is passed

We actually don't need to do that if a `<link rel=canonical>` is set correctly (pointing to the page without any query string). If search engines do stumble upon the URL with the score being passed and the canonical link points them to the URL without any query string, we should be OK.

**Comment by ioanarusiczki** [comment]
I checked with https://addons-dev.allizom.org/fr/firefox/addon/ghosttext/reviews/, found:

`rel="canonical"` with `href="https://addons-dev.allizom.org/fr/firefox/addon/ghosttext/reviews/"` even when `?score` is passed
`rel="nofollow"` for the links from the add-on detail page which filter reviews by score

I don't see `<link rel=alternate>` for languages, I'm looking into html's head on reviews page.

**Comment by diox** [comment]
It see them:
```
(...)
<link data-react-helmet="true" href="https://addons-dev.allizom.org/en-US/firefox/addon/ghosttext/reviews/" hrefLang="x-default" rel="alternate"/>
<link data-react-helmet="true" href="https://addons-dev.allizom.org/en-US/firefox/addon/ghosttext/reviews/" hrefLang="en" rel="alternate"/>
<link data-react-helmet="true" href="https://addons-dev.allizom.org/pt-PT/firefox/addon/ghosttext/reviews/" hrefLang="pt" rel="alternate"/>
(...)
```

**Comment by ioanarusiczki** [comment]
I had https://addons-dev.allizom.org/en-US/firefox/addon/ghosttext/reviews/?utm_content=homepage-primary-hero&utm_medium=referral&utm_source=addons.mozilla.org because I navigated to the detail page from the primary hero suggestion, in this case I only saw the canonical link.

Once I removed `?utm_content=homepage-primary-hero&utm_medium=referral&utm_source=addons.mozilla.org` they show up.

**Comment by diox** [comment]
Yeah, that's expected.
