### ISSUE TITLE
[Task]: feedback appeal decision justification to appellant(s)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#14878]
### Description

For appeal decisions arbitrary text can be provided by moderators and reviewers to justify the decision.  This is more common with a denial decision but possible for an acceptance too.  Either way, if it's provided we need to expose it the appellant(s) in the reply email.  In most cases this is already happening but we are missing tests proving it; in some edge cases we aren't.

```[tasklist]
### Acceptance Criteria
- [x] An appeal denial from cinder with justification contains the justification in the email to the appellant(s)
- [x] An appeal denial from reviewer tools with justification contains the justification in the email to the appellant(s)
- [x] An appeal acceptance from cinder with justification contains the justification in the email to the appellant(s)
- [x] An appeal acceptance from reviewer tools with justification contains the justification in the email to the appellant(s)
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-877)

**Comment by ioanarusiczki** [comment]
From rev tools (I've still to check from Cinder):

Author appeal is denied, comment is a mandatory field so the email sent looks like this, it should be fine.

![Reporter appeal denied from rev tools](https://github.com/mozilla/addons/assets/33448286/49f78121-6ae2-45a3-9a4d-ae0ea1703c2d)

Author appeals denied look weird, it's a compact paragraph, maybe the reviewer's comment should be on a separate line. 

![Author appeal is denied form revtools](https://github.com/mozilla/addons/assets/33448286/cda16bde-0fb0-47f5-a33d-cf3bd9e53c65)

another example 

![Another example of author appeal](https://github.com/mozilla/addons/assets/33448286/c12cc4a0-2df6-48bf-8645-bd84b1973fc3)

**Comment by ioanarusiczki** [comment]
I've been looking over from Cinder too and emails sent after the appeal for disable-enable or reject-approve for extensions/themes from rev tools (without being reported) -> filed 2 followups.

What I didn't notice until now is that when "Notes" are filed in from Cinder, they'll be sent to an author together with the reason the content has been disabled. It should be fine.

![Notes from Cinder](https://github.com/mozilla/addons/assets/33448286/695f68a0-c830-4b80-97ae-7182bf0552ac)
