### ISSUE TITLE
[Bug]: Marapets - can't buy items

### ISSUE THREAD

**Issue by tilliegal** [mozilla/addons#14871]
### What happened?

Game: Marapets.com.  I can play all parts of the game, but I cannot buy items from any of the shops in the game for 2 days now.  I can "buy" items in the shops if I use Chrome, but I prefer Firefox.  Is this something you could look into?  I much prefer Firefox.  Thank you.

### What did you expect to happen?

When I click on the item to purchase it with marapoints, it just sits there and will not purchase the item.  This happens in all of the shops.  

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-870)

**Comment by eviljeff** [comment]
This issue tracker is for the addons.mozilla.org website.  For support queries with Firefox see https://support.mozilla.org/
