### ISSUE TITLE
[Task]: Add `rel=nofollow` to links pointing to add-on pages we don't want indexed

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14874]
### Description

We have a `<meta name="robots" content="noindex, follow">` on a few pages that are linked
from add-ons detail pages:
- Feedback page (link: Report this add-on)
- Privacy Policy page (link: Read the privacy policy for this add-on - if there is one for that add-on)
- EULA page (link: Read the license agreement for this add-on - if there is one for that add-on)
- License page (link: {license name})

The recommendation we got for these is to add a `rel=nofollow` to those internal links - if we don't want the page we end up to being indexed, we should tell search engines to not follow the link - there is nothing there to index (or new to crawl).

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] `rel=nofollow` added to "Report this add-on" link on add-on detail page
  - [ ] `rel=nofollow` added to "Read the privacy policy for this add-on" link on add-on detail page
  - [ ] `rel=nofollow` added to "Read the license agreement for this add-on" link on add-on detail page
  - [ ] `rel=nofollow` added to "{license name}" link on add-on detail page (custom licence only)
  ```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-873)

**Comment by alexandruschek** [comment]
Hello,

I checked on dev and for:
1. Report add-on button rel=nofollow was added
<img width="964" alt="image" src="https://github.com/mozilla/addons/assets/139126091/d5508077-efff-43a9-9e2d-6a14adab88f2">
2. Read the privacy policy
<img width="964" alt="image" src="https://github.com/mozilla/addons/assets/139126091/a2bb65eb-593c-4536-a05c-463a879b3302">
3. Read license agreement
<img width="964" alt="image" src="https://github.com/mozilla/addons/assets/139126091/d6678091-f480-4fe9-b7d4-ed2c672c84a4">
4. Custom license
<img width="964" alt="image" src="https://github.com/mozilla/addons/assets/139126091/2080cf99-f4a2-451a-8cf2-521c6a718f71">

For the other types of license the nofollow is not present

Marking this as verified fix.

Thank you!
