### ISSUE TITLE
[Task]: Add new `illegal_subcategory` field in abuse reports

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#14875]
Same as https://github.com/mozilla/addons/issues/14870 but with a subcategory field named `illegal_subcategory`. There are many values, see: https://docs.google.com/spreadsheets/d/1yPltiTKOFf2MWkCMONRWWHE4e2B3wshV/edit#gid=780262130

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-874)

**Comment by ioanarusiczki** [comment]
1 a, 1b, 1c -> reading https://github.com/mozilla/addons/issues/14879#issue-2366023660 they've been dropped

I see in the doc 5f, 9d and category 15 which are not in the form on AMO dev. I don't know if it's the same situation as for the Animal welfare subcategories.

**Comment by willdurand** [comment]
> 1 a, 1b, 1c -> reading [#14879 (comment)](https://github.com/mozilla/addons/issues/14879#issue-2366023660) they've been dropped

right, though 1c is - in fact - always sent since that's the only possible value for "animal welfare" (but we don't show the select since there would be only 1 option)

> 5f

Correct, and 5a as well, right? See: https://github.com/mozilla/addons-server/blob/8592fe4b0e0ff7489c6a7175476026938e70523b/src/olympia/constants/abuse.py#L146-L147

> 9d

Correct, see: https://github.com/mozilla/addons-server/blob/8592fe4b0e0ff7489c6a7175476026938e70523b/src/olympia/constants/abuse.py#L192

> category 15

Correct. Per andrewmcd on Slack:

> STATEMENT_CATEGORY_SCOPE_OF_PLATFORM_SERVICE is not relevant to publishing data about illegal content reports. It's only used when we're publishing data about our removal actions.

**Comment by ioanarusiczki** [comment]
Correct, it's 5a as well. 

I could send reports from -dev for "Animal welfare" category. Admin would display the subcategory as "Something else"

If I use the API I cannot send this category without it's sub-category "other"

![other](https://github.com/mozilla/addons/assets/33448286/3ee9c8fd-6693-4917-a6aa-b2723d113b3b)
