### ISSUE TITLE
[Task]: Save and expose appeal text

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#14877]
### Description

When a reporter or author submits an appeal about a decision we send the appeal justification to cinder for moderators to review, but we don't save it in the AMO models.  So we can't then subsequently expose it to add-on reviewers inline in the reviewer tools.

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] `appeal_text` from the appellant is saved on <some model field>
  - [ ] `appeal_text` is exposed in the reviewer tools
  ```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-876)

**Comment by ioanarusiczki** [comment]
When it's been disabled after being reviewed

![appeals in rev tools](https://github.com/mozilla/addons/assets/33448286/68f0c314-1f96-4c1d-80e9-b4125bad68b4)

With abuse reports, example of a developer appeal and a reporter appeal. Reasoning is text sent by a Cinder Moderator. 
Below developer appeal or reporter appeal it's the abuse report - maybe it could be added so it won't create confusion where the text is from. 

![developer and reporter appeals](https://github.com/mozilla/addons/assets/33448286/7328ff3f-5cac-4039-bb7f-fc4971894241)

**Comment by eviljeff** [comment]
> Reasoning is text sent by a Cinder Moderator.
> Below developer appeal or reporter appeal it's the abuse report - maybe it could be added so it won't create confusion where the text is from.

This issue and patch didn't change how escalations were displayed - can you file a follow-up so Andreas can detail what he'd like?

**Comment by ioanarusiczki** [comment]
Ok, I filed https://github.com/mozilla/addons/issues/14913
