### ISSUE TITLE
[Bug]: Review notification email spam for auto-disappearing 4/5 star reviews from "rating_user"

### ISSUE THREAD

**Issue by ghostwords** [mozilla/addons#14890]
### What happened?

I regularly get AMO review notification emails for https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/ for a 4/5 star review that is not a real review but appears to be something that is part of some deployment or testing infrastructure.

I just went through a bunch of pages on https://addons.mozilla.org/en-US/developers/feed and I can see these reviews there with always the same pattern: the review is created and then "edited" within the same minute.

These reviews are always from "rating_user".

They usually, but not always, happen on Thursdays.

If I manage to visit the AMO site quickly enough, I can see the review up on the site for a few seconds, after which time it disappears.

### What did you expect to happen?

I don't want to get notified about something that's not an actual review.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-895)

**Comment by ghostwords** [comment]
Also, I can't just auto-delete these on my end because the review notification emails don't contain enough information! No username, no review text (not that it would help in this case, as the review text is always empty).

**Comment by wagnerand** [comment]
We have identified the issue internally and will take steps that this Thursday event won't happen anymore. Sorry for the inconvenience!
