### ISSUE TITLE
Username problem[Bug]: Autofill Username in Firefox problem

### ISSUE THREAD

**Issue by EltonPL** [mozilla/addons#14898]
### What happened?

Recently, when I try to log on to my Wells Fargo account in Firefox I get a message that says "username is too short".  When I then type the username myself it accepts it and logs me on.  This does not happen with Safari which works as it should.  Wells Fargo tech support says it is a Firefox problem.  All programs are up to date.  Can you help?

### What did you expect to happen?

I expected to be able to log in as always with 1Password.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-903)

**Comment by eviljeff** [comment]
Hi, please see https://support.mozilla.org/ for Firefox related support.

**Comment by EltonPL** [comment]
I’ve done that.  Your reply is not helpful.

**Comment by eviljeff** [comment]
This is the issue tracker specifically for the https://addons.mozilla.org website.  If support.mozilla.org doesn't resolve your problem I suggest you reach out to the developers of 1password - https://addons.mozilla.org/firefox/addon/1password-x-password-manager/ has some support links to their support website and support email.
