### ISSUE TITLE
[Bug]: Send emails to reporters too after resolving an author appeal

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14894]
### What happened?

From https://github.com/mozilla/addons/issues/1741#issuecomment-2200264486

For an appeal sent by the author , extensions could be still reported from addon manager. While the appeal is still open, if  new reports are sent, these will be available under the appeal. No matter of the decision taken, reinstate content or keep content disabled, there is only one email sent which is going to the author. 

Reporters won't receive an email in these cases. 

This applies to the rest of the possible scenarios (2,3 or 4) in rev tools or Cinder. Not applicable for escalations from AMO. 

### What did you expect to happen?

After a decision is taken by a Cinder moderator or a rev tools reviewer, reporters should receive emails.
Currently only the authors get an email.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-899)

**Comment by eviljeff** [comment]
After speaking to Cinder Product, it seems they will be making a change to no longer attach abuse reports to appeal jobs, making this issue (and the patch that I've half written 😬) redundant.  

I'll keep this issue open until I've double-checked there isn't anything we need to do (and/or salvage from the WIP patch)

**Comment by eviljeff** [comment]
There's nothing we need to do if abuse reports will not longer be combined with appeal jobs. https://github.com/eviljeff/olympia/tree/14894-send-reporter-emails-for-reports-with-appeals is the WIP if this changes again in the future.
