### ISSUE TITLE
Thunderbird Add-on Not Passing Validation on min/max version 

### ISSUE THREAD

**Issue by 5dma** [mozilla/addons#14899]
### What happened?

I created an add-on for Thunderbird (not Firefox). You can see the source code at [https://github.com/5dma/remove_query_parameter](https://github.com/5dma/remove_query_parameter).

Uploading the .xpi file gives the following errors:

```
Your add-on failed validation with 1 error.

Cannot find min/max version. Maybe "strict_min_version" or "strict_max_version" contains an unsupported version?
```
However, the full validation results report shows 0 errors, two warnings, and 0 notices. The two warnings are not germane to version numbers.

My `browser_specific_settings` object is as follows:
```json
"browser_specific_settings": {
	"gecko": {
		"id": "mark@lautman.net",
		"strict_min_version": "115.12",
		"strict_max_version": "115.*"
	}
}
```

Perhaps the linter is checking version numbers against Firefox releases, not Thunderbird releases?

### What did you expect to happen?

I would expect one of the following:

- If I get an error message, the same error message should appear in the validation report.
- If the error messages says that I'm specifying an unsupported version, there should be a link to the versions that are supported.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-904)

**Comment by willdurand** [comment]
AMO no longer supports Thunderbird, they have their own store and linter. You should report the issue to them at https://github.com/thunderbird/addons-server
