### ISSUE TITLE
[Bug]: Add yahoo tag pls

### ISSUE THREAD

**Issue by def00111** [mozilla/addons#14903]
### What happened?

There is a tag for google, youtube etc. but not for yahoo.

### What did you expect to happen?

So the user can search the add-ons tagged with yahoo: https://addons.mozilla.org/en-US/firefox/tag/yahoo/

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-909)

**Comment by abyrne-moz** [comment]
Thank you for your feedback.  We are currently evaluating tags are used on addons.mozilla.org and are not creating new tags at this time.
