### ISSUE TITLE
[Bug]: 2 dots often show up in emails sent to developers

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14905]
### What happened?

- when content is denied (from Cinder in the example below, moderator's comment is sent in the email) 
- from rev tools when an appeal is denied

### What did you expect to happen?

The comment is sent with `.` at the end. If the moderator or reviewer adds it , there's also a default `.` which would duplicate it

![the 2 dots](https://github.com/mozilla/addons/assets/33448286/b25978d9-16d1-4b7b-a7c3-a15fd723f210)

![email sent to developer - content taken down](https://github.com/mozilla/addons/assets/33448286/46d7e317-e179-4891-8722-5b26ed9d2799)

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-911)

**Comment by wagnerand** [comment]
I am not sure where the "This is an appeal escalated from Cinder" is coming from, but it should not be part of the email sent to the developer.

**Comment by wagnerand** [comment]
Thanks. Is that supposed to be inline with the tempate text? We should probably make that its own paragraph and indicate that it is the moderator comment.

**Comment by ioanarusiczki** [comment]
Ok, I added a comment for that https://github.com/mozilla/addons/issues/14900#issuecomment-2213689876

For reporter's appeals, a comment has it's own paragraph , an example is [here](https://github.com/mozilla/addons/issues/14878#issuecomment-2208604872), it's in the first screenshot.

**Comment by eviljeff** [comment]
> Thanks. Is that supposed to be inline with the template text? We should probably make that its own paragraph and indicate that it is the moderator comment.

The DSA email templates have inline comments. Do we want all the emails to have comments in separate paragraphs?

**Comment by eviljeff** [comment]
> > Thanks. Is that supposed to be inline with the template text? We should probably make that its own paragraph and indicate that it is the moderator comment.
> 
> The DSA email templates have inline comments. Do we want all the emails to have comments in separate paragraphs?

(Though this is a different issue to the issue reported here)
