### ISSUE TITLE
[Bug]: Make an appeal from the DSA section mandatory too

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14902]
### What happened?

At force-enable - Comments is a mandatory field
With deny appeal - Comments and Deny appeal is mandatory

![force enable plus appeal](https://github.com/mozilla/addons/assets/33448286/6aefcf82-3469-48e9-aac6-ecd8a7cfc480)

![Testing_required_fields](https://github.com/mozilla/addons/assets/33448286/a5a0ce58-0dc8-4cf7-a484-78ead9655b08)

### What did you expect to happen?

Should the DSA appeals also be mandatory ? If they're not checked , emails are not sent about the final decision.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-908)

**Comment by eviljeff** [comment]
No, the reviewer tools actions can be used without resolving reports/appeals (for whatever reason the reviewer deems necessary).
