### ISSUE TITLE
[Bug]: Cannot upload addons [STAGE][DEV]

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons#14911]
### What happened?

1. Log in devhub
2. Upload an addon
3. Observe that an error appears
<img width="1131" alt="image" src="https://github.com/mozilla/addons/assets/139126091/4343f250-e03b-4a2a-9702-ae365d67e480">

Notes:
- Checked with themes, did not encounter any issues
- On prod env this issue does not reproduce

### What did you expect to happen?

Addon to be uploaded without issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-918)

**Comment by bqbn** [comment]
@alexandruschek @vcarciu 

The issue was caused by a recent change that removed the required permissions for the default compute engine service account. We believe we have fixed it in https://github.com/mozilla/addons/issues/14911.

Could you run your tests again and see how it works?

Thanks!

**Comment by alexandruschek** [comment]
Hello, 

The upload of addons works as expected now on both environmentsa and the tests are passing.

Thank you!
