### ISSUE TITLE
Firefox Web Browser 128.02 [Bug]: 

### ISSUE THREAD

**Issue by 0mdorrington** [mozilla/addons#14916]
### What happened?

I have tried to download the required software i need:

https://vidcoder.net/
https://www.youtubedownloaderhd.com/download.html

and nothing appears within the download folder i also get errors saying fail to install software
due to virus i have installed an used these software before and never had a problem i am currently
using windows 11 pro.

I am also having problems with the copy and paste function on firefox i seem to have to keep reloading the website
page to copy and paste text?

If someone please have a look into these issues i would be most highly grateful!

### What did you expect to happen?

For me to download the require software i need without any issues!

To use the copy and paste function on the web browser as normal!

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-927)

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
