### ISSUE TITLE
[Task]: Auto-close new abuse reports if the add-on is already disabled

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#14928]
### Description

Implements https://mozilla-hub.atlassian.net/browse/AMOENG-660

Email template:
```
Hello,

Thank you for your report regarding the content you found on AMO that appeared to violate our policies.

As we had already addressed this content before your report was reviewed, your report will not be processed.

Thank you for your attention.

[{{ cinder_job_id }}]

--

Mozilla Add-ons Team

https://a.m.o/
```

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] When we receive an abuse report for an add-on we already force disabled or blocked (=all existing versions have been blocked), we should auto-close the abuse report
  - [ ] An email should be sent
 ```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-945)

**Comment by alexandruschek** [comment]
Hello,

I checked on -DEV Environment:
The email is sent to the user:
<img width="1014" alt="image" src="https://github.com/user-attachments/assets/d0312d4f-e9be-4468-ac2d-5dae833b4866">
Notes:
"Thank you  for your attention." is missing from the given email template.
"Thank you for your report regarding the content you found on AMO that appeared to violate our policies." contains two ".." as seen in the screenshot.

If this needs another issue opened, please let me know and I'll mark this verified fix.

Thank you!

**Comment by eviljeff** [comment]
> Hello,
> 
> I checked on -DEV Environment: The email is sent to the user: <img alt="image" width="1014" src="https://private-user-images.githubusercontent.com/139126091/355448861-d0312d4f-e9be-4468-ac2d-5dae833b4866.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDg0MjgsIm5iZiI6MTcyMjk0ODEyOCwicGF0aCI6Ii8xMzkxMjYwOTEvMzU1NDQ4ODYxLWQwMzEyZDRmLWU5YmUtNDQ2OC1hYzJkLTVkYWU4MzNiNDg2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjQyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTI0OWQyNTc4YTE5YzZmZGFhNTQ0MWU5MTc5OTYwNzllYTBjZjU4ZDdmYzAzZWFjMjc5Nzc0ZmYyMGMxNjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4hCW0imNmRU0SDdqRTbLOdehV2iMLdHk3k9tH1_X31o"> Notes: "Thank you for your attention." is missing from the given email template. "Thank you for your report regarding the content you found on AMO that appeared to violate our policies." contains two ".." as seen in the screenshot.
> 
> If this needs another issue opened, please let me know and I'll mark this verified fix.

No, it's a quick template fix, I'll address with https://github.com/mozilla/addons-server/pull/22544

**Comment by alexandruschek** [comment]
Ok, thank you, mark this as verified fix.

**Comment by eviljeff** [comment]
@alexandruschek fixed now
