### ISSUE TITLE
[Bug]: Verified search filter option in Badging filter is not relevant

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#14926]
### What happened?

The Verified option in the Badging search filter on AMO is not relevant and returns no results.

![image](https://github.com/user-attachments/assets/ee5e0773-c5e2-452b-b53b-2fbc4e4cba9e)

### What did you expect to happen?

It should be removed from the filter list

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-943)

**Comment by alexandruschek** [comment]
Hello,

I checked on -DEV environment, the verified option has been removed.
<img width="1728" alt="Screenshot 2024-02-21 at 10 45 12 AM" src="https://github.com/user-attachments/assets/405ab3e5-b26f-4151-b644-a55e2f972793">
Marking this as verified fix.

Thank you!
