### ISSUE TITLE
[Task]: Add ability to add/update addon privacy policies

### ISSUE THREAD

**Issue by rougetimelord** [mozilla/addons#14927]
### Description

Hi! I'm a maintainer on an addon that's listed on AMO, and we (semi) recently were asked to update our privacy policy. I would like to be able to push updates to our privacy policy using our release workflow, rather than having to ping the person who's AMO account actually hosts the addon every time there's a change to our privacy policy.

So basically, I would like if there was a Privacy Policy (and probably EULA) key to the following external API endpoints:
- `PATCH /api/v5/addons/addon/(int:id|string:slug|string:guid)/`
- `PUT /api/v5/addons/addon/(string:guid)/`
- `POST /api/v5/addons/addon/(int:addon_id|string:addon_slug|string:addon_guid)/versions/` (if it would make sense to add it there?)

Another possible solution is to add push/patch/put methods to the `/api/v5/addons/addon/(int:id|string:slug|string:guid)/eula_policy/` endpoint.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Add a way to update privacy policies and/or EULAs to the external API.
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-944)

**Comment by diox** [comment]
An API already exists: https://mozilla.github.io/addons-server/topics/api/addons.html#eula-and-privacy-policy

**Comment by rougetimelord** [comment]
> An API already exists: https://mozilla.github.io/addons-server/topics/api/addons.html#eula-and-privacy-policy

From my reading of the docs this endpoint only **gets** the current policies for an addon. I want to be able to create/update the privacy policy of an addon.

I'm unable to test currently but does the endpoint accept `PUSH`/`PATCH`/`PUT` methods?

**Comment by diox** [comment]
My apologies, you're correct! It's an oversight on our part, it should be straightforward to fix, we'll try to get it done for our next release.

**Comment by diox** [comment]
`/api/v5/addons/addon/(int:id|string:slug|string:guid)/eula_policy/` will allow `PATCH` to edit eula/privacy policy. Docs will be updated soon, the patch will only land in production for our next push August 8th though.

**Comment by diox** [comment]
@ioanarusiczki yeah let's have a follow-up for this, we can prevent that from happening.

I also noticed in devhub, changing the privacy policy triggers an activity log (`{addon} policy changed`, action id 38) that is not happening through that new API, we should fix that while we're at it.

**Comment by ioanarusiczki** [comment]
@diox  I'm looking into  `models/activity/activitylog/` and added/changed eula or privacy policy for some add-ons from dev hub but I don't see an activity log (checked dev and stage).  I see an activity recorded for License only.

**Comment by diox** [comment]
You're right, I was basing that on some 15 years old code I see in the form but it doesn't look like it's doing anything...
