### ISSUE TITLE
[Task]: Always show add-on status in the top list of metadata on the review page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#14925]
### Description

At the top of the review page, there is a list with metadata about an add-on. That list shows the status of the add-on only for some values of the status, but it should be shown always.

Add-on status shown:
<img width="824" alt="Screenshot 2024-07-26 at 12 04 30" src="https://github.com/user-attachments/assets/b75540ec-58ae-4076-8714-e25666facfc5">

Add-on status not shown:
<img width="827" alt="Screenshot 2024-07-26 at 12 05 18" src="https://github.com/user-attachments/assets/99479764-8154-4104-80fa-7be19e06ccb1">

### Acceptance Criteria

```[tasklist]
  - [ ] At the top of the review page, the add-on status should always be shown in the metadata list.
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-942)

**Comment by ioanarusiczki** [comment]
I've checked on AMO stage and noticed the following below, I hope they're expected (looks good to me).

| Actions | Status on review pages |
| --- | --- |
| First version submission | awaiting review |
| The first version is approved | approved |
| When rejected by reviewers or disabled by developers | incomplete |
| When force disabled | disabled by Mozilla |
| When blocked | disabled by Mozilla |
| Deleted versions | incomplete |
| Deleted addons | deleted |
