### ISSUE TITLE
[Bug]: Reporter's country code is missing on  AMO dev - in rev tools and admin

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14929]
### What happened?

I was making some checks for https://github.com/mozilla/addons/issues/1896 and noticed that the country code is missing in rev tools pages and admin.
It is reproducible with addons installed or uninstalled , with or without authentication. 

It's not reproducible on -stage.

### What did you expect to happen?

Examples:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630148
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/621032
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/503370

![country code](https://github.com/user-attachments/assets/54cf1a8c-e3d4-421e-8738-8261480f779c)

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-946)

**Comment by willdurand** [comment]
I feel like this has something to do with Fastly, which we switched to on -dev last Friday.

**Comment by ioanarusiczki** [comment]
@willdurand thanks, then I'll mention it in [Jira](https://mozilla-hub.atlassian.net/browse/OPST-670)

**Comment by bqbn** [comment]
This should have been fixed. Please help verify it.

**Comment by ioanarusiczki** [comment]
I tried again but I didn't get lucky

![tried again](https://github.com/user-attachments/assets/0762081d-415d-45f2-892e-3b35870baff0)

**Comment by bqbn** [comment]
What do I need to do in order to generate a row in the "abuse report" in order to try to reproduce the issue?

**Comment by diox** [comment]
@bqbn : use https://addons-dev.allizom.org/en-US/firefox/feedback/addon/cas-current-addon-1/ 

I suspect the reason is that you've added the relevant header only for `GET` requests, but we need it for all HTTP verbs. (I can't test that theory easily because the test endpoints, https://addons-dev.allizom.org/services/client_info & https://addons-dev.allizom.org/api/v5/services/client_info, don't allow other verbs than `GET` easily - I need to patch them to bypass csrf protection)

**Comment by bqbn** [comment]
Well, that's a good hint. Thanks!

I filed https://github.com/mozilla-it/webservices-infra/pull/2261/commits/1108ecc0895e9b46d898c8f6e6d23e58c7792b39 for it.

@ioanarusiczki , could you try again, please?

**Comment by ioanarusiczki** [comment]
I tested some more around this. I saw that when I was sending reports from a profile with firefox release version I got the country codes but once I was trying with Nightly the country code was missing. 

So I made a new Nightly profile set all prefs I needed to install an addon from -dev and all the prefs for the abuse reporting. 
I did not install the extension and sent reports -> noticed the country code is present now 
Then I installed the extension and tried again -> country code is missing. 
Sent a report for another extension not installed -> country code missing. 

So it appears that this issue appears only after an add-on/theme install. 

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630150

![code vs nocode](https://github.com/user-attachments/assets/5e04a0db-af6e-4d45-8b99-7efd07cf5f10)

On stage it's not reproducible (I tried again to make sure it's a current regression) https://reviewers.addons.allizom.org/en-US/reviewers/review/1025065

**Comment by diox** [comment]
@ioanarusiczki I think it's purely prefs-related.

@bqbn it looks like this is working for `addons-dev.allizom.org` but NOT `services.addons-dev.allizom.org`.

**Comment by ioanarusiczki** [comment]
Confirming that. I modified extensions.addonAbuseReport.url, using `https://addons-dev.allizom.org/api/v5/abuse/report/addon/` instead of `https://services.addons-dev.allizom.org/api/v5/abuse/report/addon/` , 
sent new reports and I see the country codes being present.

**Comment by bqbn** [comment]
I just applied the same treatment to `services.addons-dev.allizom.org`.

Sorry, I should have done that in one shot.

**Comment by bqbn** [comment]
I must have not run the "apply" command to put the fix into place. 😞 

But it works for me now.

```
$ curl -s -X POST -d foo=bar https://services.addons-dev.allizom.org/api/v5/services/client_info | jq .
{
  "HTTP_USER_AGENT": "curl/8.6.0",
  "HTTP_X_COUNTRY_CODE": "US",
  "HTTP_X_FORWARDED_FOR": "redacted, 140.248.88.22, 35.227.240.185",
  "REMOTE_ADDR": "redacted",
  "SERVER_NAME": "services.addons-dev.allizom.org",
  "POST": {
    "foo": "bar"
  },
  "GET": {}
}
```

**Comment by bqbn** [comment]
Could you try it again on your end?

**Comment by diox** [comment]
All working for me now, thanks!
