### ISSUE TITLE
[Bug]: Alerabat.com

### ISSUE THREAD

**Issue by LeSzekMadry** [mozilla/addons#14932]
### What happened?

The browser doesn't see the 'alerabat' add-on at all, but it wasn't like that before
alerabat.com

### What did you expect to happen?

that it will work without any problems

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-949)

**Comment by wagnerand** [comment]
Please reach out to the developer of the add-on for questions about the availability of their add-on.
