### ISSUE TITLE
Increase max file size.

### ISSUE THREAD

**Issue by NorbertBodziony** [mozilla/addons#1494]
I am dev of https://addons.mozilla.org/en-US/firefox/addon/nightly-app/.
We are creating extension for all chromium based browsers and firefox, but recently firefox support eats huge chunk of our time because of 4mb max file support rule. Since last upgrade https://github.com/mozilla/addons/issues/181 it has been almost 7 years.
App are getting heavier and a lot of teams/startups want to SHIP code rather than satisfy "linter" rule. 

I love firefox and I use it as my main browser, but honestly this is the only reason I am considering dropping firefox.

I am not the only one there is multiple example of same issues. https://github.com/mozilla/addons/issues/1237 https://github.com/mozilla/addons/issues/662 https://github.com/oasisprotocol/oasis-wallet-ext/issues/148 

Don't make us hire a professional bundler.

Make Firefox MAX_FILE_SIZE_TO_PARSE_MB bigger !

**Comment by Nick-1979** [comment]
agreed, Make Firefox MAX_FILE_SIZE_TO_PARSE_MB bigger

**Comment by NorbertBodziony** [comment]
bumping it.

We are almost 2 months later and no one from team even responded to it. If you won't "fix it" let us know.

**Comment by diox** [comment]
We are considering it but there are blockers to solve internally first (we have private scanners that are already can have trouble parsing such huge JavaScript files).

I already started discussing it in the more-specific addons-linter repos in https://github.com/mozilla/addons-linter/issues/4942 and I can't merge the issues, so I'm closing this one.
