### ISSUE TITLE
[Bug]: "version already exists" only appears after user clicks "continue"

### ISSUE THREAD

**Issue by D4n2021** [mozilla/addons#14949]
### What happened?

upload a new version of an addon with the same version (in manifest.json), for example v1.2.

### What did you expect to happen?

warning "version 1.2 already exists" should appear automatically as soon as the upload is finished and not only when the user clicks "continue" button

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-969)

**Comment by eviljeff** [comment]
Hi, this is in artifact of how, internally, AMO handles uploads, then associates them with add-on.  Simplified, the xpi upload is handed off to a linting task to validate the xpi is okay, without considering what add-on you're attempting to add it to.  Then only when you try to submit the validated upload do we compare the details from it to the existing add-on (and discover the duplicate version number, in this case). To change this architecture would be a compex piece of work and we don't believe it worth the investment to make those changes at this time.
