### ISSUE TITLE
[Bug]: Should this not say "Extension developer" instead of "Add-ons developer"?

### ISSUE THREAD

**Issue by leoheitmannruiz** [mozilla/addons#14948]
### What happened?

At, for example, https://addons.mozilla.org/en-US/firefox/user/4757633/ it is written that Mozilla Firefox is an "Add-ons developer" and "Theme artist".

![amo](https://github.com/user-attachments/assets/a554fc75-ee36-44f7-9046-d009120de8fc)

### What did you expect to happen?

Should this not say "Extension developer" instead of "Add-ons developer"?

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-968)

**Comment by abyrne-moz** [comment]
Thank you for raising this, we appreciate the feedback. Some developer accounts create multiple types of add-ons, such as  extensions and language packs, which is why we've chosen this wording.  We will not be updating it at this time.
