### ISSUE TITLE
[Bug]: newer versions listed as older versions

### ISSUE THREAD

**Issue by D4n2021** [mozilla/addons#14942]
### What happened?

visit https://addons.mozilla.org/en-US/firefox/addon/english-us-language-pack/versions/

"Latest version" is an older version than the claimed "Older versions".

![grafik](https://github.com/user-attachments/assets/b21d0a58-8170-40cc-b26b-3e2954426fd8)

### What did you expect to happen?

Version numbering should be logical instead of highly confusing and not logical at all.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-962)

**Comment by diox** [comment]
Language packs are a little bit special - I agree it's confusing, the `Latest version` here is actually the latest version _compatible with the version of Firefox you're using_. Maybe specifically in that case the copy of that heading could be adjusted or even removed completely.

**Comment by diox** [comment]
If we remove the whole "Latest version" block, we should also:
- Change "Older versions" heading to say "Versions" or similar
- Make sure the current version is no longer excluded from that older versions list

**Comment by chrstinalin** [comment]
> the Latest version here is actually the latest version compatible with the version of Firefox you're using. 
@diox Is there no situation where the user would want to know which version this is? Being able to distinguish which latest version is compatible still seems important to know.
