### ISSUE TITLE
[Task]: expand reviewer tools flags to show _all_ the reasons a review is in the queue

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#14946]
### Description

Pre-requisite for https://github.com/mozilla/addons/issues/14921

https://github.com/mozilla/addons/issues/9520 added flags to show if a review was present because it had DSA-relevant abuse reports or appeals, but because there are only flags for a subset of the reasons an add-on may be there, it doesn't allow a reviewer to see if there were other reasons it was present - i.e. a reviewer can see the add-on was there for for a cinder job; but not it was _only_ there for a cinder job.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] flags shown in the reviewer tools manual review queue for all the reasons an add-on may have a due_date
    - [ ] manual review (auto approval disabled because manually disabled for the add-on; promoted group with pre-review, etc)
    - [ ] abuse report cinder job
    - [ ] escalated cinder job
    - [ ] appeal cinder job
    - [ ] other NeedsHumanReview flag
    - [ ] developer reply 
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-966)

**Comment by ioanarusiczki** [comment]
I'm going to keep an eye on icons but I tried scenarios and they showed up. 

I don't think there's an icon for appeals escalated from Cinder ? Should I file a followup?
