### ISSUE TITLE
[Bug]: All the screenshot addons lately are causing the Save as window Button, not to display properly, we are unable to save images in our PC folders

### ISSUE THREAD

**Issue by EuroGitCy** [mozilla/addons#14957]
### What happened?

Specifically for this addon (Awesome Screenshot & Screen Recorder) by Diigo Inc.
[](https://addons.mozilla.org/en-US/firefox/addon/screenshot-capture-annotate/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser)

The last days, every time when I capture an image, I annotate it and then I click the download button to Save it to my PC. The window explorer shows up as usual in order to Save the images into my PC folders. But the problem is there when the "window explorer" comes up. It does not display anything properly. The "Save as" button can not be displayed. The Text is missing, folders and file location are missing, etc... Just an empty window explorer.. I wait a few seconds, each time, for the (Save) button to show up and then I can save it in my folders. Making me think that my PC might got infected by a virus. But No. this is not the case.  I discovered that this is happening with other Firefox **Screenshot Addons/extensions** as well. Just recently, this last week. I didn't have that issue before with the screenshot Extensions. I was using them normally. 

I tested to save images with the microsoft's default (Snip & sketch) tool, making screenshot of an image in the browser, and it does not cause me this problem. Only the Firefox's screenshot extensions are causing this. Please fix this issue with the screenshots extensions. Thank you.

Evros

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/f9ecbcf9-bd8f-46d6-a121-7b91f5958a94)
![Problem screenshot display](https://github.com/user-attachments/assets/b966267f-66c5-4490-b991-8d1f688ed894)

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-977)

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
