### ISSUE TITLE
[Task]: Replace AMO favicon with Firefox logo

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#14951]
### Description

The Firefox add-ons logo does not have the brand recognition of the Firefox logo.  This could lead to confusion and uncertainty when a user searches for an extension in a search engine and comes across the AMO branding in their search results.

By replacing the puzzle piece favicon with the Firefox logo, it will instantly be recognizable as a Firefox web property and increase trust in the search result.

![image](https://github.com/user-attachments/assets/1d33e411-bc92-4bff-a8de-15cb3d2b0bdd)

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] The favicon for addons.mozilla.org shows the Firefox logo
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-971)

**Comment by diox** [comment]
We're planning to get a specific Add-ons+Firefox logo in the future but in the meantime we should use the generic Firefox logo.

**Comment by moregan-moz** [comment]
This is Mary from the brand team affirming this logo switch. The description above by abyrne-moz perfectly describes the problem and solution. Add-ons will benefit from the recognition of the Firefox logo. Visually associating Add-ons more closely with Firefox will help users more confidently engage with them, because they'll be able to quickly see that Add-ons are legitimately connected to Firefox.

**Comment by diox** [comment]
I've picked up the 32x32 version, merged the addons-server part of this, still needs the frontend one to also make sure to bust the cache everywhere.

**Comment by ioanarusiczki** [comment]
I see the new favicon present on frontend , dev hub and rev tools on AMO dev.
[Add-ons blog](https://addons-dev.allizom.org/blog/) is loading the old favicon.
[Dev hub ](https://addons-dev.allizom.org/en-US/developers/) has the old logo up on the left -> DevHub-Navigation-Logo. 

![favicon](https://github.com/user-attachments/assets/740f586b-e8c8-4c56-8d4e-67e085f015ac)

rev tools
![rev tools](https://github.com/user-attachments/assets/8db47008-a9e8-4086-a5af-6690e35ea4fe)

Android - dev versus stage
![Screenshot_2024-09-11-11-01-00-684_org mozilla firefox](https://github.com/user-attachments/assets/01368383-7537-4b6a-95fd-3bbf040ac6e7)

**Comment by diox** [comment]
@ioanarusiczki ah, forgot the blog. I will create a ticket on https://github.com/mozilla/addons-blog/ for that
