### ISSUE TITLE
[Task]: Log force-enable action message in add-on's review page as we do for force-disable action

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#14956]
### Description

As an add-on reviewer, I'd like to see the message sent during force-enabling of an add-on (message is entered in the comment area) on the add-on's review page so that there's a log of all the messaging sent out to the developer on the reviewer page for other reviewers and future me.

Currently the only indication of an add-on being force enabled is an entry in `Add-on important changes history` section but this doesn't contain the message sent along with the action.

### Additional question
Is the message sent with force disabling attached to the latest version submitted in either of the channels? Or is it attached to the latest version in the channel from which a force-disable action is performed? 

Either of those are a bit off given the action relates to the add-on as a whole, but still wanted to get clarity on this.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Force-enable action should leave a log in the add-on's review page with the message associated with the action sent to the developer
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-976)

**Comment by diox** [comment]
UX in the reviewer tools is... subpar. But we should be able to find a way to surface the message there. Those force-enable/force-disable activities are not tied to the versions but the add-on itself.

**Comment by ioanarusiczki** [comment]
Wfm on AMO dev

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/632457#review-actions
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/632421

![history](https://github.com/user-attachments/assets/74cc9d6d-3f46-4d72-af34-0c8dd1b417f6)
