### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by prof-botto** [mozilla/addons#14954]
### What happened?

Méliuz addon is not available anymore. I can't find it since I updated my browser to the last version.

### What did you expect to happen?

I expected mozilla to have Méliuz addon available so I could install it.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-974)

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
