### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by i-CNNN** [mozilla/addons#1496]
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
yes.
[x-mutil-pem_0.0.2.zip](https://github.com/mozilla/addons/files/11716750/x-mutil-pem_0.0.2.zip)

* Whether your add-on is listed or unlisted.
listed.

* The URL where you submitted the add-on.
https://addons.mozilla.org/zh-CN/developers/addon/x-mutil-pme/versions/submit/upload-unlisted

* The approximate time you submitted the add-on, with timezone.
9:45 UTC +8

**Comment by wagnerand** [comment]
Is this still an issue?
