### ISSUE TITLE
[Bug]: An admin can send patch requests for eula/privacy policies for extensions they don't own

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14966]
### What happened?

I've noticed that a 
PATCH on https://addons-dev.allizom.org/api/v5/addons/addon/632094/ throws a 403 forbidden for an admin session id - when the admin is not the author of the extension

then PATCH on 
https://addons-dev.allizom.org/api/v5/addons/addon/632094/eula_policy/ is allowed for an admin on any extension/theme I tried with

### What did you expect to happen?

Maybe it should throw a 403 too 

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-986)

**Comment by ioanarusiczki** [comment]
Well yes, the admin can make addon detail changes from dev hub. I don't know why there's differences with the endpoints.

**Comment by diox** [comment]
So actually, it turns out that this is a bug/accident in the eula policy endpoint, we never re-implemented admin edits in the add-on API (and I'm hoping we won't).

**Comment by ioanarusiczki** [comment]
We've discussed the details how to test this:
- an admin can't patch eula/privacy policy
- developers can't patch eula/privacy policy when add-ons are Disabled by Mozilla. 
- a banned user can't patch 
- can patch otherwise as long as they're author of the add-on

This is verified on -dev. 
I did not see the changes on -stage yet.

**Comment by ioanarusiczki** [comment]
Verified on -stage
