### ISSUE TITLE
[Bug]: No hola vpn what is going on?

### ISSUE THREAD

**Issue by JESUSISLORD552** [mozilla/addons#14963]
### What happened?

Because they wouldn't show it anymore we need it back to protect are ip address from others trying to steal it.

### What did you expect to happen?

Error not working!

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-983)

**Comment by diox** [comment]
Please reach out to the developer of the add-on for questions about the availability of their add-on.
