### ISSUE TITLE
[Bug]: Escalated appeals from Cinder - could have a different icon?

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14968]
### What happened?

When there's an escalated appeal from Cinder (report has been resolved in Cinder, only the following appeal is forwarded to rev tools) the manual review queue displays an icon as for the reports forwarded. 

![abuse report or appeal](https://github.com/user-attachments/assets/9d901579-9961-4ac8-a2fc-404f3aa9960b)

### What did you expect to happen?

Maybe it should be a different icon?

Similar to https://github.com/mozilla/addons/issues/14809 but that's in version's history
This is a followup for https://github.com/mozilla/addons/issues/14921#issuecomment-2288999361
### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-989)

**Comment by diox** [comment]
They could, but I don't think we care at this point. Will revisit if a reviewer/operations end up caring about this.
