### ISSUE TITLE
[Bug]: API responds with `is_disabled_by_mozilla` set to `false` for add-on which is effectively disabled by Mozilla

### ISSUE THREAD

**Issue by leoheitmannruiz** [mozilla/addons#14969]
### What happened?

Hey :)

I have an extension with two versions, 1.0.0 and 1.0.1. I disabled 1.0.0 before submitting it. I submitted 1.0.1, which after a day was listed at AMO. One or two days later it was now disabled by Mozilla.

I checked the API, which responded with `is_disabled_by_mozilla` set to `false`:

https://addons.mozilla.org/api/v4/addons/addon/%7BFFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF%7D/

PS: Are you supposed to be able to choose a UUID, no less the [Max UUID](https://datatracker.ietf.org/doc/html/rfc9562#section-5.10), like I did here?

I expected that you are allowed to choose the add-on ID if you use the email-like format, but that the UUID format is always generated by Mozilla. Or, otherwise, that only [valid UUIDs](https://datatracker.ietf.org/doc/html/rfc9562#table1) are allowed.

### What did you expect to happen?

I expect the API to return `is_disabled_by_mozilla` set to `true`.

It seems to me that Mozilla disabled all non-disabled versions, effectively disabling the add-on.

At least, I found the response quite surprising and unintuitive.

This seems very related https://github.com/mozilla/addons/issues/4933#issuecomment-2094125516

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-990)

**Comment by eviljeff** [comment]
An add-on with all the versions disabled (or otherwise not approved) is not the same as the add-on being disabled (as mat said in the [following comment](https://github.com/mozilla/addons/issues/4933#issuecomment-2094125518)) because you can upload a new version.

The uuid format isn't validated, and you can choose it.
