### ISSUE TITLE
[Task]: Deny URLs in add-on ratings

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#14973]
### Description

The majority of [add-on ratings with URLs](https://sql.telemetry.mozilla.org/queries/101822/source) seem to be spam or otherwise.  We should prevent ratings with URLs from being submitted.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Submitting a review/rating with a URL in it displays an error and is not posted
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-994)

**Comment by ioanarusiczki** [comment]
I could no longer add a new review or change an existing one using URLs on AMO dev.

![url not allowed](https://github.com/user-attachments/assets/cca5a306-ac63-481c-937f-27c066920720)


Verified on Win, MacOS, Chrome, Edge, Android.

**Comment by ioanarusiczki** [comment]
Oh I forgot about developer replies -> this applies to them too, developers cannot add URLs. I don't know if that's expected @diox

**Comment by diox** [comment]
I expected that to happen yeah, replies go through the same validation & restrictions.
