### ISSUE TITLE
Tampermonkey addon is stuck at "Awaiting Review" (Publicly visible and Self-signed version)

### ISSUE THREAD

**Issue by derjanb** [mozilla/addons#1497]
### Describe the problem and steps to reproduce it:

Tampermonkey is currently stuck at "Awaiting Review" for 19 days.
Tampermonkey BETA is stuck for a month now.

### What happened?

I've uploaded a new Tampermonkey version and review didn't happen within almost 3 weeks now.

Tampermonkey BETA was updated, but building from source "failed" because a random generated ID in the source was different to the uploaded extension package. I've uploaded a new source package the same day, but even though I wrote another message 21 days ago, I didn't get a response neither a review.

### What did you expect to happen?
I got a email that "high impact extensions" are subject to human review and I'm fine with this.
![image](https://github.com/mozilla/addons/assets/767504/4ee6a581-aec6-4a27-991e-6c5840edb16b)

However, review times of 3 weeks are too long. Tampermonkey was [made available to Firefox's Android versions in December](https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/) and I was asked to not make larger changes to assure a smooth process. That's why the new version now includes various fixes especially for Android. So it would be nice if someone could review both extensions.

### Anything else we should know?

https://addons.mozilla.org/en-US/developers/addon/tampermonkey/versions
https://addons.mozilla.org/en-US/developers/addon/5ff7ad16183743acbe23/versions

Thanks.

**Comment by wagnerand** [comment]
This has been resolved.
