### ISSUE TITLE
[Task]: Filter themes by color

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#14971]
### Description

Provide the ability for a user to search for a theme by color on addons.mozilla.org.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] A user is able to filter themes based on their dominant colors
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-992)

**Comment by diox** [comment]
Note: the API part of it has been implemented a while back in https://github.com/mozilla/addons/issues/6257. It's not perfect, probably need some tweaks to make it more precise, but it works.

**Comment by diox** [comment]
This is going to be shown when the user selects "Add-on Type" -> "Theme", or is browsing a Theme category. As mentioned above it's not perfect in terms of how precise the color filtering is, but should be good enough to begin with.

**Comment by ioanarusiczki** [comment]
- I see the new filter available everywhere in a search result when add-on type is "Theme" or automatically displayed when going to Theme categories.
- could navigate through with keyboard nav on win and macOS
- recommeded themes are listed above all the other 
- there is room for improvement indeed, to give examples, I tried [red color](https://addons-dev.allizom.org/en-US/firefox/themes/category/holiday/?color=ff0000&sort=recommended%2Cusers) with holiday category. Or[ white](https://addons-dev.allizom.org/en-US/firefox/search/?color=ffffff&type=statictheme) when looking at the first page with results there's some dark themes displayed above really bright ones.
- custom color menu is different on win than macOS and behaves in a different manner. Like when choosing a custom color for windows, that would be available until the profile is closed or restarted. On macOS these colors are available on every profile once they're selected and don't reset after restarting a profile. 

windows 

![on Windows](https://github.com/user-attachments/assets/fe488366-42e8-4158-af77-37c6a9247cfe)

macOS

<img width="1329" alt="onMacOS" src="https://github.com/user-attachments/assets/ab057fa7-ba04-4cf6-b6ea-2ac3fd9b2290">
