### ISSUE TITLE
[Bug]: I couldn't install the Méliuz extension on Mozilla Firefox.

### ISSUE THREAD

**Issue by infovalleysystemsolution** [mozilla/addons#14979]
### What happened?

I couldn't install the Méliuz extension on Mozilla Firefox, it opens the following URL: https://addons.mozilla.org/firefox/downloads/latest/meliuz/?utm_source=meliuz&utm_medium=barra_extensao&utm_campaign=primeiro_botao

And the first message on the page is "Sorry, but we couldn't find what you're looking for."

### What did you expect to happen?

That it be directed towards the installation of the Méliuz extension.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1003)

**Comment by infovalleysystemsolution** [comment]
That it be directed towards the installation of the Méliuz extension.

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
