### ISSUE TITLE
[Bug]: Add-on reporting form text is inaccurate

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#14988]
### What happened?

The add-on reporting form has a "More details" free form text box, which is required to be filled out.  However, the text underneath the box says `While this information is not required`, which is inaccurate.

![image](https://github.com/user-attachments/assets/6d4828a6-5a9a-43c3-befd-d07724205d4e)

### What did you expect to happen?

The text under the box should be updated to remove the incorrect information, so it says `Please provide any additional information that may help us to understand your report (including which policy you believe has been violated).` and nothing else.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1013)

**Comment by eviljeff** [comment]
@abyrne-moz when you say "remove this line", do you mean "remove the sentence", or remove the highlighted text, leaving the other half of the sentence (that continues "failure to include...") - if so, how should that be reworded?

**Comment by abyrne-moz** [comment]
Sorry if I was unclear, I meant:

Make the text under the box say `Please provide any additional information that may help us to understand your report (including which policy you believe has been violated).` and nothing else.

**Comment by ioanarusiczki** [comment]
I checked on -dev and I see that text has been removed as  [mentioned](https://github.com/mozilla/addons/issues/14988#issuecomment-2320712440) everywhere (for users, ratings, collections, add-ons).

![fixed](https://github.com/user-attachments/assets/e888bb55-e84b-4755-a801-7fb188ff3c9d)
