### ISSUE TITLE
[Task]: drop unnecessary AbuseReport.appellant_job fk

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#14984]
### Description

Since https://github.com/mozilla/addons/issues/14877 we've had a specific, per appeal, model: `CinderAppeal`, that links `AbuseReport`s from a reporter with an appeal.  Now we have this we don't need an fk directly on each AbuseReport for an appeal, so we can drop `AbuseReport.appeallant_job`.  

There should be no functional difference - I expect the main changes will be updating tests that set up appeals.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Appeal functionality works as now, but via `CinderAppeal.reporter_report` rather than `AbuseReport.appellant_job`
  - [ ] Existing instances of AbuseReport with a defined `appeallant_job` are migrated to a `CinderAppeal`, with a `reporter_report` fk set
  - [ ] Column dropped from the database via a migration (in a subsequent deploy)
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1009)

**Comment by ioanarusiczki** [comment]
Sounds like regression testing on appeals which further means all scenarios 😬

**Comment by eviljeff** [comment]
> Sounds like regression testing on appeals which further means all scenarios 😬

Yes, but focusing on the two places this reference was used - when determining if a reporter can appeal it or not; and sending out the notification emails to the reporters who appealed a decision, after the appeal decision has been made.

**Comment by ioanarusiczki** [comment]
> when determining if a reporter can appeal it or not; 

I hope that means the Approve and Ignore actions.  I tried these using Cinder (for a collection or listings) and from rev tools and I've seen the correct emails sent. 

> and sending out the notification emails to the reporters who appealed a decision, after the appeal decision has been made

that's happening for all the scenarios I've tested with today, I did not finish testing yet, but so far it looks good

**Comment by ioanarusiczki** [comment]
I did not find issues related to appeals.

Not related to this but noticed while testing and forgot to mention:

When reporting from addon manager the name of the add-on in the reporting form is the one from manifest.json. In case the name has been edited in dev hub after submission ([an example of such addon](https://addons-dev.allizom.org/en-US/firefox/addon/version-testing-2_/)) and the addon is installed there's a glitch on the report form at page refresh.

![glitch on name](https://github.com/user-attachments/assets/962b3f86-fd84-4af2-bb3f-8b529759d227)

And I still didn't figure out what's the role of the checkboxes next to fields in Cinder such as below. I can check them before submitting a report for example

![check boxes on reports](https://github.com/user-attachments/assets/3f5bfb2a-9332-42b8-8dee-9d6729b3d5dc)
