### ISSUE TITLE
[Task]: Remove caching of Denied Names

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14994]
### Description

When checking if a name chosen by a user (for their profile or collection) is denied, we are fetching the entire list of Denied Names and caching it for the default caching duration (500 seconds), and then going through the list in Python.

We could just do a `LIKE` query in the database instead, it's going to be just as fast and removes a layer of caching we don't need.

Note that `DeniedName` are partial matches: if `Foo` is in the list, we shouldn't be able to create something named `Barfoo` or `Foobar`.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] `DeniedName` continues to work as before, with caching layer removed
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1020)

**Comment by ioanarusiczki** [comment]
I tried on -dev and -stage adding some names or using some old entries and I could not edit display names or collection names, it's a warning displayed. For other fields from collections or edit profile these can be used. I hope it's all expected.


![denied names](https://github.com/user-attachments/assets/c62364ed-2abf-48bf-8278-bae50dd3b0e0)
