### ISSUE TITLE
[Task]: Reviewer tools: Support attaching a zip file to a review

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#14999]
### Description

To reduce reviewer workload by doing the same task of building an artifact for a developer to check repeatedly and to eliminate the dependency on a third-party service, the reviewer tools should support adding a zip attachment to at least rejections and reviewer replies. If it's not too much additional effort, ideally it should be supported for all actions.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] A zip file should be attachable to at least reviewer replies and rejections, ideally all reviewer actions.
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1030)

**Comment by diox** [comment]
Let's start with a 100 MB file limit to begin with and see how it goes.

**Comment by diox** [comment]
Note: zip files should also go through `SafeZip` like all our zip files.

**Comment by wagnerand** [comment]
Let's do 200MB. Several dozen versions submitted just this year have XPI files larger than 100MB and at least one of them is Notable.

**Comment by diox** [comment]
(We did 210 MB / 200 MiB)

Depends on https://github.com/mozilla/addons/issues/14997

**Comment by ioanarusiczki** [comment]
I've errors on dev with 1 + MB zip files, I tried from win and macOS. Same with a larger txt files.

![2 85 zip](https://github.com/user-attachments/assets/8109355d-47f4-4a20-bc4b-f8e7730f2525)

**Comment by eviljeff** [comment]
@ioanarusiczki large files should be working now (on dev and stage)

**Comment by ioanarusiczki** [comment]
I tried on dev and stage to make uploads. 

Tested on:
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1031481
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/633303

What passed: zip files attached to various reviewer actions (can be seen on the links above) of 3, 9, 13, 20, 26, 37 MB
Also a 9MB txt file.

I've noticed that somewhere from 40MB + , I've the 502 server error so it failed with:
44, 48, 50, 116 mb zip files

![502server error](https://github.com/user-attachments/assets/82fdc20b-fdd1-47a9-9d66-f83bd0061d61)

I tested this on both dev and stage servers.

**Comment by ioanarusiczki** [comment]
Larger uploads on dev went through for: 50, 120, 150 up to 180+ MB

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/633177#review-actions

180 plus on stage too https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1031488#review-actions

At 190 + I'm getting this error 

![at 200](https://github.com/user-attachments/assets/9ec23e67-ff97-4bd2-8f54-ec51dfbb736b)

Anything above 200 MB throws the error

![202](https://github.com/user-attachments/assets/2fe11011-478b-4c0d-88d2-c7085c865263)

**Comment by ioanarusiczki** [comment]
There's a followup filed https://github.com/mozilla/addons/issues/15093 

I'm marking this verified since large uploads are now working as mentioned above on dev and stage.
