### ISSUE TITLE
[Task]: clean-up: drop appellant_job and reporter_appeal_date from AbuseReport

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#14992]
### Description

Follow-up for https://github.com/mozilla/addons/issues/14984

https://github.com/mozilla/addons-server/pull/22610 removes those two fields from the model.  After the deploy we can generate the django migration to drop the fields from the database table.

This migration can only be merged after the tag for **2024.09.19** has been created, so it deploys to prod in a subsequent push.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] A sentence describing the first milestone/checkpoint
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1017)

**Comment by ioanarusiczki** [comment]
@eviljeff Could you add some str for qa please?
