### ISSUE TITLE
long gap of disabled page and nothing happening while waiting for Paypal popup on AMO 

### ISSUE THREAD

**Issue by autonome** [mozilla/addons#15]
STR:

1. Go to https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/developers
2. Click "Contribute <3"
3. Enter the amount and click "Make Contribution"
4. Watch the content dim, and wait for something to happen

It can be some time before *anything* visual happens. Maybe instead, the popup for the amount and comment should stay visible with some kind of progress indicator that clearly indicates that we are waiting on Paypal?

**Comment by andymckay** [comment]
As soon as we do the page dimming we've triggered the Paypal payment flow, that dimming is from their library. Agreed it could be improved.

**Comment by andymckay** [comment]
At this point we are planning the rewrite of AMO. I'm not to sure if the idea of contributions will survive the rewrite and if they do, what format they'll take. So we'll see what happens in the rewrite which UX are working on now.

Based on the rewrite there's nothing actionable here other than yeah we can improve it.
