### ISSUE TITLE
Extremely slow extension verification process

### ISSUE THREAD

**Issue by fabriziobagala** [mozilla/addons#1500]
### Describe the problem and steps to reproduce it:
The process of verifying extensions is very slow. It takes up to months to verify the integrity of an extension.

### What happened?
The verification process takes an unreasonable amount of time to verify an extension.

### What did you expect to happen?
The verification process takes a reasonable amount of time (such as a couple of days) to verify an extension.

### Anything else we should know?
For example, Bitwarden extension 2023.5.1 came out last week and is still not in the Firefox Add-ons.
As another example, the 1Password 2.12.0 extension came out on June 21 and is still not in the Firefox Add-ons.

**Comment by wagnerand** [comment]
The fact that a particular version is not available does not mean that it has not been reviewed. For specific extensions, you can reach out to the developer and ask why a version is not released yet.

To our knowledge, there are no extensions at this point that haven't been reviewed in months as you claim. If you have an extension that indeed hasn't been reviewed in more than 2 weeks, please let us know.

**Comment by fabriziobagala** [comment]
@wagnerand thank you for your response.

1Password's customer support told me that they released their extension on June 21, but it has not been reviewed yet. If I am not mistaken, it has been 18 calendar days.

**Comment by wagnerand** [comment]
@fabriziobagala I can confirm that 1Password is not pending review currently.

**Comment by wagnerand** [comment]
@fabriziobagala Correction, there is a new update pending review, which was submitted 1 business day ago.

**Comment by fabriziobagala** [comment]
@wagnerand thank you for the update.

**Comment by fabriziobagala** [comment]
@wagnerand the extension for 1Password has not yet been updated. When I was telling you about the slowness of the verification process, this is what I was referring to.

**Comment by wagnerand** [comment]
As I said before, having not been updated does not mean having not been reviewed.

**Comment by fabriziobagala** [comment]
@wagnerand sorry to post on this issue again, but I keep having problems with updating add-ons. I contacted the Bitwarden team about the newly released version, and they told me that the Mozilla team still did not validate the extension. How come it takes so long to validate extensions? Need a method to speed up this step.

**Comment by pwseo** [comment]
I second this. In Bitwarden's case, the version currently available breaks the extension for many people... and while one might think they may switch from Bitwarden to another product, it's actually easier to switch browsers for this -- Chrome Web Store has the latest version already.

I know Mozilla can't review everything instantly, of course, but it's one of their recommended addons :) Any ETA on it?
