### ISSUE TITLE
[Bug]: glob dependency is missing in addons-server

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#15009]
### What happened?

See: https://github.com/mozilla/addons-server/pull/22651

addons-linter (v7) no longer requires `glob` as a "production" dependency, which revealed a bug in the addons-server's dependencies. We're using `glob` in some scripts and it should be added to the project's list of dependencies.

### What did you expect to happen?

No error

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1044)

**Comment by ioanarusiczki** [comment]
I see addons-linter on 7.0.0 https://addons-dev.allizom.org/__version__  but I don't think this requires qa.
