### ISSUE TITLE
[Bug]: Flag for human review is not cleared after making a reviewer decision

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#15001]
### What happened?

While testing https://github.com/mozilla/addons/issues/14970

1. Report an extension for add-on policies and check that's been flagged and present in the manual review queue
2. Report again the same extension using another policy and check that the report is in Cinder Listings queue
3. Forward the report from Cinder to AMO
4. Resolve the reports with Approve

![approve](https://github.com/user-attachments/assets/eb35a12f-1d5d-4b29-b64b-894a0d765553)

### What did you expect to happen?

The abuse report flag is not cleared and the addon is still present in the manual review queue. 

Examples:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/632562
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/632560
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/632559

In cinder the job from content infringement queue is closed.
Emails were sent to all reporters (including the one who reported for add-on policies).

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1037)

**Comment by eviljeff** [comment]
Pretty sure this is a regression from the forwarded/escalation changes.  When the forwarded job is re-created in the content-infringement queue, if there is an existing non-forwarded job, then it gets combined together.  But then in AMO, because the entire job is now seen as forwarded, we don't clear any _non_-forwarded NHRs

**Comment by ioanarusiczki** [comment]
I tested with [this extension](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/632945) and it's been fixed 👍
