### ISSUE TITLE
[Task]: rm crontab.tpl and gen-cron.py

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15003]
### Description

Cron jobs running on addons-server are no longer defined by the output of gen-cron.py, they're separately defined in a deployment repo.

https://github.com/mozilla-it/webservices-infra/blob/main/amo/k8s/addons-server/values.yaml

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] obsolete files removed
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1039)

**Comment by diox** [comment]
We should reference https://github.com/mozilla-it/webservices-infra/blob/main/amo/k8s/addons-server/values.yaml somewhere in the `cron` command code.
