### ISSUE TITLE
[Bug]: Rename "Cinder policys" to "Cinder policies" in the django admin

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#15011]
### What happened?

In the django admin, we should fix the typo for the cinder policy model:

![Screenshot 2024-09-11 at 12 01 21](https://github.com/user-attachments/assets/6b3957c9-23f8-4754-800b-cfd3b14cbc83)

### What did you expect to happen?

"Cinder policies"

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1046)

**Comment by diox** [comment]
should be just a matter of setting on `CinderPolicy` model:
```python
    class Meta:
        verbose_name = 'Cinder Policy'
        verbose_name_plural = 'Cinder Policies'
```

**Comment by ioanarusiczki** [comment]
fixed on dev

![Screenshot 2024-09-20 at 14-55-40 AMO Administration Django site admin](https://github.com/user-attachments/assets/b30fcdb9-55bd-451f-877a-f895eaa5c56e)
