### ISSUE TITLE
[Bug]: Unlisted versions have NHR for add-ons with mixed versions when abuse reporting without a version

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#15010]
### What happened?

From https://github.com/mozilla/addons/issues/14985#issuecomment-2340549573

Reporting an add-on with mixed versions:

  -  when reporting the unlisted version installed, this is not present anywhere (only in admin tools), listed is ignored.
 -   when reporting the listed version installed I see it being flagged for review in rev tools, the unlisted is ignored.
 -   when reporting without a version (none of the versions is installed), both listed and unlisted versions are flagged for human review. I am not sure here, should the unlisted be ignored because of the threshold now ? (or this only applies to purely unlisted)

### What did you expect to happen?

For the third scenario on making reports without a version maybe the unlisted version should no longer get NHR. At least not until it reaches the threshold for unlisted versions.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1045)

**Comment by wagnerand** [comment]
I agree with this suggestion.
