### ISSUE TITLE
[Task]: Expose whether a version is soft or hard-blocked in the blocked page

### ISSUE THREAD

**Issue by diox** [mozilla/addons#15016]
### Description

Depends on https://github.com/mozilla/addons/issues/15015

When viewing a blocked page with the version specified in the URL (such as https://addons.mozilla.org/en-US/firefox/blocked-addon/%7Ba73cc3ed-9261-4571-94f6-3679930f0332%7D/3.0/), if the version is soft-blocked, some additional text needs to appear to indicate the version is only soft-blocked.

Copy needs to be provided by product/operations for this additional text/section.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] The blocked page has copy indicating that the version is soft-blocked when that's the case
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1051)

**Comment by abyrne-moz** [comment]
The copy as been added to Figma https://www.figma.com/design/AW8J0zfwapN2nX7DUkbtBX/Softblock-Extensions?node-id=4914-45005&node-type=section&t=TWABxs54iiTTa28h-0

**Comment by abyrne-moz** [comment]
The copy should be as per the Figma, with the exception of the blocked version list.  For both soft and hard blocked we can use the same wording

`Versions blocked or restricted: All Versions | 1.2, 1.3, 3`

**Comment by KevinMind** [comment]
Decision:

- When the version is included in the URL we get the block type for that version and display type dependent copy
- If we do not know the version or the version is not blocked we default  to the type dependent copy based on all soft all hard.
- If the add-on blocks are mixed we show the hard blocked copy
- In cases where there are no blocks for the add-on we 404

**Comment by abyrne-moz** [comment]
To simplify development, I propose we remove the `Versions Blocked` and `Blocked On` parts at the bottom of the page for all iterations of this page.  This information is unlikely to be useful to end users who are only looking for information on the version they have installed in Firefox.

**Comment by ioanarusiczki** [comment]
This is an addon with blocked and restricted versions
https://addons-dev.allizom.org/en-US/developers/addon/ublock-origin_2-versions/versions

Looking at what's been [modified in the PR ](https://github.com/mozilla/addons-frontend/pull/13285/commits/99a0d5277e2d6fbdd976faea69a77f063d4adc37) it should be fine.

 restricted version https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B21ea20de-9707-4b2a-8f8f-ca2e8c9e8bba%7D/1.52.8/

![restricted](https://github.com/user-attachments/assets/7304ed88-f4c8-4179-9b0c-dac26b6330e1)

blocked version https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B21ea20de-9707-4b2a-8f8f-ca2e8c9e8bba%7D/1.52.9/

![blocked](https://github.com/user-attachments/assets/313db255-5cc1-4612-ba1c-9836cc515c35)

without a version specified it would display the blocked copy https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B21ea20de-9707-4b2a-8f8f-ca2e8c9e8bba%7D/

when there are no blocks , it's a 404 https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B9aa4ea9a-a5e1-4a23-be18-67200b9d4923%7D/2.0/
