### ISSUE TITLE
Have used Mastercook import  add-on for years.  Suddenly within last couple of weeks, I am unable to import recipes via the addd-on.  My only option presently is to manually add information.  I've refreshed Firefox, removed and reinstalled the add-on, followed Mastercook instructions including removing cache, etc.  The add-on works fine on Edge, so the problem is with Firefox.  I really don't want to switch to Edge, so any help you can rovide to address this issue is welcoe.  

### ISSUE THREAD

**Issue by ckohut311** [mozilla/addons#1502]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Hi,

You should report this problem to the developer of the add-on.

**Comment by ckohut311** [comment]
I did.  They had me check to see if the app worked on Edge.  It works just fine on Edge which makes me believe the issue is with Firefox.
