### ISSUE TITLE
[Bug]: Automatically rejected unlisted version is still in Awaiting Review State

### ISSUE THREAD

**Issue by ialecse** [mozilla/addons#15023]
### What happened?

Unlisted version 3.5.231 of [this add-on](https://reviewers.addons.mozilla.org/en-US/reviewers/review-unlisted/2625022) was automatically rejected, but it's still in Awaiting Review state with a due date.

### What did you expect to happen?

The expectation was that the version receives the Rejected status.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1062)

**Comment by diox** [comment]
Activity history:
```
SELECT log_activity.action,
       log_activity.arguments,
       log_activity.user_id
FROM log_activity
JOIN log_activity_version ON log_activity_version.activity_log_id = log_activity.id
WHERE log_activity_version.version_id = 5795958
ORDER BY log_activity.id ASC
```

Looks like it's because the version was disabled by the developer, then automatically rejected, then re-enabled by the developer. Because it had been disabled by the developer first, we let them re-enable it.

We should look into overriding `status_disabled_reason` and `original_status` when rejecting...

**Comment by ioanarusiczki** [comment]
I've set the date in the past for delayed rejection, currently waiting for automatic rejection, I should see "Rejected" 

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/633071
https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1031115

**Comment by ioanarusiczki** [comment]
Not sure about results. So what I did is after the reject is only to try to re-enable from dev hub.

On dev:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/633071 status:0 in rev tools 
https://addons-dev.allizom.org/en-US/developers/addon/mixed-addon-auto-approved/versions I see the same on the versions page in dev hub. 

Status of the addon: incomplete

On stage:
I don't see an awaiting review state. If versions were approved previously, after re-enable the versions have status approved.

https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1031115

**Comment by eviljeff** [comment]
mozilla/addons-server#22705 missed resetting `status_disabled_reason`.

**Comment by ioanarusiczki** [comment]
I've good results on -dev https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/633148

I could no longer re-enable the version - > there is no longer such option left for a developer after the version has been automatically rejected.

**Comment by ioanarusiczki** [comment]
Verified on stage https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1031189#review-actions
