### ISSUE TITLE
[Task]: Fix dependency resolution in <your-favourite-ide>

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15034]
### Description

Previously it was possible to have vscode (or another ide) set up so all dependencies referenced in addons-server could be resolved.  This meant you could seamlessly inspect the python code for a dependency in the same way you could navigate to a file within addons-server's codebase.  Most often this would be a django .py but with all the dependencies there it could be any package.  This all "broke" when we stopped installing dependencies in a sub-directory in the addons-server directory (for startup efficiency)

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] A sentence describing the first milestone/checkpoint
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1075)

**Comment by diox** [comment]
Ugly workaround we discussed during Office Hours: install deps in a dummy virtualenv and point vscode to that.

Alternatively we could find ways to expose the docker container deps to the host, maybe through a volume like we used to, or maybe though some vscode extension that would deal with docker.

**Comment by wagnerand** [comment]
I haven't tried this, but https://stackoverflow.com/a/75560548 looks promising?

**Comment by eviljeff** [comment]
@KevinMind if #15066 will fix this (in a more comprehensive way) is it worth putting any effort into getting dependency resolution to work with the current setup?
