### ISSUE TITLE
[Task]: JS Size Detection on Input Change for Versions/Attachments

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#15039]
### Description

Follow up from #14835 --
>Use some JS to trigger size detection when the file input is changed. In that, call [setCustomValidity()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setCustomValidity) with a custom message if the size is over the limit, and otherwise call it to reset it to '' if valid. The user would need to change the file if they want to continue.
>If going that route though, they'd probably also need to be able to clear the input completely to start over. @diox 

Similarly modify [attachment uploads](https://github.com/mozilla/addons-server/pull/22670#discussion_r1768969736) to handle size detection in a similar manner.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] setCustomValidity() is called on file change for version uploads.
  - [ ] setCustomValidity() is called on file change for attachment uploads.
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1080)

**Comment by diox** [comment]
Where possible I think we should use the occasion to remove any hardcoded values in strings and make that depend on the `MAX_UPLOAD_SIZE` setting created for attachment uploads.

**Comment by diox** [comment]
QA: When clicking submit on file uploads other than the upload add-on flow (upload source, activity attachment from https://github.com/mozilla/addons/issues/14999 / https://github.com/mozilla/addons/issues/14997) you should see an error message when submitting a form with a file over 210 MB. That message should be displayed before the actual upload goes through and should prevent submission until the file is changed.

![Screenshot from 2024-09-25 15-17-39](https://github.com/user-attachments/assets/054e0452-78af-4ca5-8cf5-ff05943eee97)

**Comment by ioanarusiczki** [comment]
I get the error message for a .zip below 210 mb too, it's ~207mb (actually if I check file's properties it's 202mb) 

![at submission 207mb](https://github.com/user-attachments/assets/a23614d5-3cf8-4267-ad93-3be1f1a5dbff)

![207MB](https://github.com/user-attachments/assets/221691af-0d97-4425-9f47-ff9dcca6a1a4)

Doesn't look good on the versions page: that's only with files of 200 mb +

![versions page zip](https://github.com/user-attachments/assets/5916e2b5-6d64-4503-8c0f-157b660056a0)

Also -> I could upload 160 - 180 MB zip files. But I also got the "Uncompressed size is too large" error.
