### ISSUE TITLE
[Bug]: Block reason is a non-localizable (US) English string and should be marked as such in the page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#15051]
### What happened?

1. Navigate to https://addons.mozilla.org/fr/firefox/blocked-addon/%7Ba73cc3ed-9261-4571-94f6-3679930f0332%7D/

The block reason is an English string and the rest of the page is in French (because `/fr/` is in the URL). We cannot translate the block reason because that's provided by the reviewers and it can be any reason (free-form). It isn't marked as an `en-US` paragraph, though.

### What did you expect to happen?

Since the block reason cannot be translated, we should mark it as an `en-US` string in the markup.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1096)

**Comment by ioanarusiczki** [comment]
With https://addons-dev.allizom.org/fr/firefox/blocked-addon/%7Bae48229e-b5c6-404d-8b2a-30a358d71286%7D/ I see the `lang ="en-US"` attribute being present.

![block reason with en-US lang](https://github.com/user-attachments/assets/80617490-e7b9-434c-8327-d4edbca9cda1)
