### ISSUE TITLE
[Bug]: Firefox Adds-on cannot set different screenshots for multiple locales 

### ISSUE THREAD

**Issue by AlexTang24** [mozilla/addons#15057]
### What happened?

Developers cannot set different screenshots for multiple locales in the Firefox add-on editing page. For example, if you upload an en-us image first and then an fr image, the fr image will overwrite the en-us image, and the later uploaded image will become the default.

### What did you expect to happen?

fix the bug or add the feature

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1102)

**Comment by eviljeff** [comment]
@AlexTang24 can you expand on the bug with some steps to reproduce?  Screenshots aren't localizable - the captions are, but no the image - and when I tested switching languages I was prompted to save before switching.

**Comment by AlexTang24** [comment]
> @AlexTang24 can you expand on the bug with some steps to reproduce? Screenshots aren't localizable - the captions are, but no the image - and when I tested switching languages I was prompted to save before switching.

yes, it's can be saved when switching languages but it's not saved to different languages in fact, you can see it in the ads-on detail page, for example, https://addons.mozilla.org/fr/firefox/addon/coupert/  and https://addons.mozilla.org/en-US/firefox/addon/coupert/ shows the same images.

**Comment by eviljeff** [comment]
Screenshots are not localizable - only the optional captions you can add to the screenshots are localizable.  

Introducing localizable non-text properties would be non-trivial amount of work and isn't on our roadmap at this time, so I'm closing this issue for now.
