### ISSUE TITLE
[Bug]: Broken link to Scopus Document Download Manager extension

### ISSUE THREAD

**Issue by nick41** [mozilla/addons#15059]
### What happened?

I go to Scopus (external website) and log in. I search for an academic paper and click the title from the resultant search options. This brings up a page for the paper with a download option. I click 'Download'. A pop up is presented stating that I need to install a Firefox extension to enable downloads from Scopus. I click 'Install'. I am taken to the URL 'https://addons.mozilla.org/firefox/downloads/latest/scopus-document-download/' which presents an extension not found error.

### What did you expect to happen?

https://addons.mozilla.org/firefox/downloads/latest/scopus-document-download/ should have a working extension on it that I can install to Firefox

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1105)

**Comment by diox** [comment]
Hi,

Please report that to the developers of Scopus, that's not a bug on our side.
