### ISSUE TITLE
[Task]: Disable Attachments for Force Disable/Enable

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#15063]
### Description

RE: https://github.com/mozilla/addons/issues/15018#issuecomment-2386378653
Force disable/enable are not surfaced in review history (and so its attachment is unavailable to developers). Do not allow reviewers to upload attachments under these actions to avoid confusion.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Reviewers should not be able to include attachments on force disable/enable actions.
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1109)

**Comment by chrstinalin** [comment]
RE: https://github.com/mozilla/addons/issues/15018#issuecomment-2388634783 --
> going over abuse reports/appeals, if zip or txt files can be attached to any reviewer action, this is applied for approve/ignore actions from Resolve Reports. These would be attachments to be viewed only by reviewers (they don't go as links to any email, as it would be for a Comment).

>an author appeal could be resolved in rev tools with Deny action. The email sent has "An attachment was provided. To respond or view the file, visit https://addons.allizom.org/developers/addon/test_for_email_checks/versions." ( applied on version 4.0 in this case) but this is not an action visible for a developer in dev hub.

Since log visibility to the developer is based on the activity log's action as a constant only determined after the reviewer action is taken, it may be better to just prevent the developer from being notified an attachment was included on an action if they cannot view it and turn off attachments on an action-by-action basis separately.

**Comment by ioanarusiczki** [comment]
On dev, force disable/enable -> attachments have been removed. 
Looking over listed, unlisted, themes, the rest of the actions have the attachments. While looking over, I've noticed that unlisted have it for block multiple versions. I filed https://github.com/mozilla/addons/issues/15080 

![attachments disabled](https://github.com/user-attachments/assets/7dcfbab9-48db-4053-9a88-106f1e4da068)

![noattachment at force enable](https://github.com/user-attachments/assets/6694d462-ddd1-405c-9756-0f9142a9c063)
