### ISSUE TITLE
[Bug]: Comment associated with force-enable and force-disable actions should be logged in the same place on add-on review page

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#15067]
### What happened?

When an add-on is force-disabled, a log is added to the `Add-on important changes history` section as well as the latest version in the channel in the version review history.

However, when an add-on is force-enabled, only the log in `Add-on important changes history` is created with no mention of force-enable action in the latest version's review history. 

Apart from being inconsistent and confusing, this is creating a risk of operations/reviewers missing to follow important parts of an add-on's review history.

### What did you expect to happen?

Both force-disable and force-enable actions must create a log entry consistently in the exact same places so that the review history isn't missed by reviewers.

Ideally, I'd expect add-on wide actions such as force-enable and force-disable to not be logged on individual versions, but only logged at the add-on level (for which, `Add-on important changes history` is good). 

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by diox** [comment]
> Ideally, I'd expect add-on wide actions such as force-enable and force-disable to not be logged on individual versions, but only logged at the add-on level (for which, `Add-on important changes history` is good).

I think this is just a matter of setting `self.version = None` in `disable_addon()`, like `enable_addon()` does.

**Comment by wagnerand** [comment]
I talked with Abhi about the desired approach, he will file a new issue.
