### ISSUE TITLE
[Bug]: Correct Permissions on Attachment Download for Developers

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#15062]
### What happened?

[views.py#L184](https://github.com/chrstinalin/addons-server/blob/24ed82fa7282b38bcd4ab633006cca4ebe1bdc27/src/olympia/activity/views.py#L184) permissions were not updated with the DevHub pastebin implementation, causing a 404 when a developer attempts to download the attachment.

### What did you expect to happen?

Developers should be able to download the attachment.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1108)

**Comment by chrstinalin** [comment]
RE: https://github.com/mozilla/addons/issues/15018#issuecomment-2388634783
> I can download the attachments from rev tools as an admin, admin reviewer, addon reviewer but I get a 404 with theme and content reviewers.
Theme and content reviewers are a permission separate from addons reviewer.

**Comment by ioanarusiczki** [comment]
I tried on AMO dev to download files as a developer, theme or content reviewer and all worked for me.
