### ISSUE TITLE
[Bug]: Undocumented error in AMO API endpoint

### ISSUE THREAD

**Issue by avi12** [mozilla/addons#15079]
### What happened?

In https://mozilla.github.io/addons-server/topics/api/addons.html#upload-detail, if the endpoint response is an error, it will be returned as
```json
{
  "detail": "some error"
}
```

### What did you expect to happen?

I expected it to be documented so I can better handle errors in my project

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1133)

**Comment by diox** [comment]
What was the error exactly ? Specifically the HTTP status code and the actual error message would be useful.

We do [already document that 401/403s can have that kind of response](https://mozilla.github.io/addons-server/topics/api/overview.html#responses).

**Comment by diox** [comment]
Closing per lack of reply.
