### ISSUE TITLE
catalan language automated web translations

### ISSUE THREAD

**Issue by XOCR** [mozilla/addons#1508]
If there is the option to choose this language from the second dropdownlist (select2) , it must be in the other one.

![image](https://github.com/mozilla/addons/assets/63920862/008e13fe-ff5c-4d6c-9183-009a3ff5ee11)

![image](https://github.com/mozilla/addons/assets/63920862/930532dc-4cb7-4427-af39-4528d2464ac6)

### Describe the problem and steps to reproduce it:

Thank you,

**Comment by wagnerand** [comment]
This repository is for the add-ons platform, not Firefox. Please visit support.mozilla.org for help.
