### ISSUE TITLE
[Bug]: Cannot install add-on

### ISSUE THREAD

**Issue by besea77** [mozilla/addons#15082]
### What happened?

I clicked on the link to install the extensin for Meliuz store and I was redirected to this page: 
Sorry, but we can't find what you're looking for.

The page or file you requested was not found on our website. You may have clicked on an outdated link, or entered the address incorrectly.

    If you entered the address, check the typing.
    If you have followed a link from somewhere, [register the problem](https://github.com/mozilla/addons/issues/new). Tell us where you came from and what you sought and we will do our best to correct it. 

### What did you expect to happen?

I intend to install the extension

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1136)

**Comment by diox** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
