### ISSUE TITLE
[Bug]: https://tab.gladly.io/newtab/ no longer able to search from here

### ISSUE THREAD

**Issue by mamgusian** [mozilla/addons#15081]
### What happened?

When I open https://tab.gladly.io/newtab/ which is set as my home page, for the past few days it has not been possible to search. The search button does nothing. Also I frequently get the 'this tab is slowing down FireFox' message with the option to stop it.
I'm being forced to resort to Edge which I'm not too happy about :(
![image](https://github.com/user-attachments/assets/79c07ef2-a199-4d15-a03a-44092e730847)
If I press stop I'm still unable to search, either because it won't allow input in the search box or the search button does nothing.
I apologise if this is the wrong place to report my problem but it's the only place I've been able to find, and couldn't find a mention of it in existing issues.

### What did you expect to happen?

I've used Tab for a Cause for years on FireFox with no trouble, so I expect to be able to continue using it.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1135)

**Comment by diox** [comment]
Hi,

This repos is meant for issues about addons.mozilla.org, not individual add-ons. You should raise that over https://gladly.zendesk.com/hc/en-us/categories/201939608-Tab-for-a-Cause ("Help" link from https://tab.gladly.io/)
