### ISSUE TITLE
 [Task]: reviewer tools queue of pending Decisions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15085]
### Description

Once decisions can potentially not be carried out straight away (https://github.com/mozilla/addons/issues/15074) we need a special reviewer tools queue that shows pending decisions.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] A queue page with decisions made that haven't had their associated actions carried out yet
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1139)

**Comment by ioanarusiczki** [comment]
I checked for each entity with an example today and all of them showed up in this new queue.  -> an admin with "*" or an admin reviewer has access to it

![new queue](https://github.com/user-attachments/assets/968363f8-aad1-44cf-aa0a-71e9a962c101)

The action column:
-> cannot open details for users, collections or ratings (probably expected for now, idk)
 -> could open for extensions/themes: I did not see versions being flagged for HR or the reports presents in the DSA (idk if that's expected at this point or not )


I'll let @alexandruschek do some more exploratory:
STR:
1. report to Cinder a high profile entity (you've details about what is considered to be "high profile" [here](https://docs.google.com/document/d/1kOPhRdTuodEjjQSyLr1EB12bFQCCpp8SKtFR4wUXoIk/edit#heading=h.u265wpso4gc3))
2. go to the [Cinder queues](https://stage.cinder.nonprod.webservices.mozgcp.net/queues) (depending on what's been reported) 
3. choose an action that would disable content (list of actions [here](https://docs.google.com/spreadsheets/d/14wu7Vip25NS4iVMu3fKLz9SgDHyGEz6-2XcX-6C6vaM/edit?gid=0#gid=0))
4. go to rev tools https://reviewers.addons-dev.allizom.org/en-US/reviewers/ Admin Tools -> Held actions for 2nd Level Approval queue 
5. make sure the high level content disabled from Cinder is now present here.

**Comment by eviljeff** [comment]
Add-on page will be implemented with https://github.com/mozilla/addons/issues/15075 (I just linked to the existing review page for now); review pages for other content is out of scope for this initial tranche of work (so they don't link anywhere)
