### ISSUE TITLE
MySessions no more listed in search?

### ISSUE THREAD

**Issue by the-insulter** [mozilla/addons#1509]
### Describe the problem and steps to reproduce it:
The Addon MySessions is not listed in the list for Session Managers!

### What happened?
I get updates but it is not in List and I can not install it on my other FF-Installations.

### What did you expect to happen?
You took the addon from list without warning or reason!
A phobia?

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Put it back on Addons and contact the Developer

balyaev@gmail.com

Thanks in advance

**Comment by wagnerand** [comment]
I am not sure what exactly you refer to by "list of Session Managers". If this is about the available categories, you can choose them yourself for the add-on in the developer hub. If it is about a collection, you can contact the collection owner.

**Comment by the-insulter** [comment]
Thanks. I found it :)
