### ISSUE TITLE
[Task]: Tweak max file upload size limits

### ISSUE THREAD

**Issue by diox** [mozilla/addons#15093]
### Description

Instead of displaying that we allow file uploads up to 209.7 MB, let's round that down to 200 MB.
Also, bump max uncompressed size (the size of the zip once uncompressed, for zip/xpi uploads) to 250 MB.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Devhub shows/validates maximum allowed upload size as 200 MB
  - [ ] Zip/xpi can be uploaded if their uncompressed size is up to 250 MB (if the size of the zip is still below max upload size, 200 MB)
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1147)

**Comment by ioanarusiczki** [comment]
I checked this on stage now and I've the following:

At source code upload : at ~ 190 MB I could make uploads successfully 
Tested with https://addons.allizom.org/en-US/developers/addon/pass-addon-auto-approved/versions

Above 190 MB I've the message:

![above190](https://github.com/user-attachments/assets/f7692782-7605-48de-bfe3-f4c89b908e27)

Same results with rev tools in attachments. 
https://reviewers.addons.allizom.org/en-US/reviewers/review/1007067 -> rev tools says 198MB but on my local machine it would be 189 MB if I check the file's properties.  

I no longer have the error message about the uncompressed file is too large from https://github.com/mozilla/addons/issues/14999#issuecomment-2410325811

Looking good.
