### ISSUE TITLE
[Task]: Update Licenses available for add-on developers to choose from on AMO

### ISSUE THREAD

**Issue by diox** [mozilla/addons#15092]
### Description

Following https://github.com/mozilla/addons/issues/14976 and after discussions with Legal and Product, we have settled on doing the following:

- Update all Licenses names, slugs and urls to follow SPDX. Notably, add the "only" suffix were relevant.
- Add Apache License 2.0, ISC License, GNU Affero General Public License v3.0 only, The Unlicense
- Update API documentation to reflect those changes

Final License order in devhub should be:
- Mozilla Public License 2.0[ Details](https://www.mozilla.org/MPL/2.0/)
- Apache License 2.0 [Details](https://spdx.org/licenses/Apache-2.0.html)
- GNU General Public License v2.0 only [Details](https://spdx.org/licenses/GPL-2.0-only.html)
- GNU General Public License v3.0 only [Details](https://spdx.org/licenses/GPL-3.0-only.html)
- GNU Lesser General Public License v2.1 only [Details](https://spdx.org/licenses/LGPL-2.1-only.html)
- GNU Lesser General Public License v3.0 only [Details](https://spdx.org/licenses/LGPL-3.0-only.html)
- GNU Affero General Public License v3.0 only [Details](https://spdx.org/licenses/AGPL-3.0-only.html)
- MIT License [Details](https://spdx.org/licenses/MIT.html)
- ISC License [Details](https://spdx.org/licenses/ISC.html)
- BSD 2-Clause "Simplified" License [Details](https://spdx.org/licenses/BSD-2-Clause.html)
- The Unlicense [Details](https://spdx.org/licenses/Unlicense.html)
- All Rights Reserved
- Other

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] All Licenses names, slugs and URLs should follow [SPDX](https://spdx.org/licenses/) definition
  - [ ] New Licenses are added, with specific order in devhub
  - [ ] API docs are updated
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1146)

**Comment by abyrne-moz** [comment]
Thanks for your follow-up!

The most popular licences were selected in collaboration with our open source licensing legal consultants. As mentioned in the previous issues, adding dozens of licence options to AMO would be unwieldy and overwhelm submitters with a multitude of unnecessary options. The _Other_ option exists to provide a choice for any licence to be used, and for those users it is up to the submitter of the add-on to add the text for the licence.

The specific version of the licence was chosen, rather than the _or later_, to prevent ambiguity and ensure a specific licence is chosen.

Given that the names of the licences are proper nouns, they have not been translated at this time.

**Comment by diox** [comment]
We'll be dropping translations for all licenses as part of implementing this issue.

**Comment by abyrne-moz** [comment]
Accidentally closed

**Comment by alexandruschek** [comment]
Hello, I checked this on -DEV, and according to the milestones/checpoints you have for this issue:

New Licenses are added, with specific order in devhub - the order is the same with the one mentioned in the issue:
<img width="718" alt="image" src="https://github.com/user-attachments/assets/783bdda8-e6a1-4d88-828d-3d190415d1c6">
The links match the ones in the description of the ticket
Also, the API Documentation is update for non-themes:
<img width="743" alt="image" src="https://github.com/user-attachments/assets/90b031a1-6c39-4c32-9320-fca951c93c79">

Only question I have before I add the label: The "Other" option should be present in the API documentation?

Thank you!

**Comment by diox** [comment]
For `Other` the `slug` would actually be `null`. This is described elsewhere in the doc, `slug`s are only for non-custom licenses.

**Comment by alexandruschek** [comment]
Oke, thank you for the info! Marking this as verified.
