### ISSUE TITLE
[Task]: Submissions Waffle Flag Follow-up

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#15090]
### Description

> * The Theme Submission page (`/en-US/developers/addon/submit/theme/upload-listed`) has the `Create a theme` button still enabled when the flag is off
> 
> * The Theme Wizard page (that the aforementioned button leads to - `/en-US/developers/addon/submit/wizard-listed`) also has its submit button still enabled
> 
> * Some warning should be displayed somewhere on the upload & theme wizard pages and not just on the `title` of the disabled buttons, to make it more obvious. With the full `note` for consistency. From https://github.com/mozilla/addons-server/pull/22729#pullrequestreview-2369227172

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] `/en-US/developers/addon/submit/theme/upload-listed`'s `Create a theme` button is disabled correctly.
  - [ ] `/en-US/developers/addon/submit/wizard-listed`'s submit button is disabled correctly.
  - [ ] The warning is displayed directly on the upload & theme wizard pages alongside the flag note.
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1144)

**Comment by alexandruschek** [comment]
Hello,

I checked on DEV ENV' the submissions flag works as expected for themes and addon upload pages. Also a message is present on both upload pages when the submissions are disabled.
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/dc552558-6a35-4959-b8d2-09b3fa48309b">

Thank you!
