### ISSUE TITLE
[Question] Is there a limit to version numbers?

### ISSUE THREAD

**Issue by madprops** [mozilla/addons#15102]
### What happened?

I'm wondering if i'll run into trouble if I use big version numbers.

I like using big version numbers like 5600 etc.

Is there a hardcoded limit or is that something I shouldn't worry about?

I mean I'll soon be at 6k, 7k, 9k, etc. But in all time I don't think it'll ever go above 100k unless I work for a very long time. I just like bumping in 1s, 10s, or 100s depending on how many changes were done.

### What did you expect to happen?

Nothing happened.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1156)

**Comment by diox** [comment]
Hi,

Please don't open issues to ask questions, use [Community Forums](https://discourse.mozilla.org/c/add-ons/) or Add-ons channel on [Matrix](https://wiki.mozilla.org/Matrix).

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version#version_format should answer your question.
