### ISSUE TITLE
[Bug]: After refreshing the review page is not visible if a file was uploaded

### ISSUE THREAD

**Issue by ialecse** [mozilla/addons#15105]
### What happened?

If a file is uploaded to the review message and then the review page is refreshed there is no clear indication that the file is still attached to the message, only by clicking the "Upload" button again it's visible that the uploaded file is still present.
![After Click](https://github.com/user-attachments/assets/8929db65-291a-4cbd-89d9-68a920471fe0)
![After Refresh](https://github.com/user-attachments/assets/ea51d017-75d5-4d54-860f-c911d06e86a7)

### What did you expect to happen?

I would've expected the file to either be removed from the message at refresh or to at least have a clear indication that the file is still attached.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1159)

**Comment by ioanarusiczki** [comment]
Verified on -dev 
Confirming hard refreshes will reset. 

![with zip file zip](https://github.com/user-attachments/assets/373135f3-07bb-4c1c-bb63-cdf3907ae0ea)

![from clipboard zip](https://github.com/user-attachments/assets/8f1dd0cf-8e34-4b63-8852-b5b7f1c98277)
