### ISSUE TITLE
[Bug]: Reviewer tools doesn't recognise moved jobs as being forwarded to reviewers

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15115]
### What happened?

Follow-up for https://github.com/mozilla/addons/issues/15035

### What did you expect to happen?

A job that has been forwarded to AMO by being escalated into the AMO reviewer handled queue in Cinder would be marked as Forwarded in the reviewer tools, just as a job that has been forwarded via a decision of AMO_ESCALATE would be.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1169)

**Comment by eviljeff** [comment]
The forwarding/escalation notes aren't present either, so ideally the fix would resolve both problems.

**Comment by ioanarusiczki** [comment]
I've checked again -dev ( I don't see https://github.com/mozilla/addons/issues/15035 on stage yet)

- NHR is now removed after resolving a forwarded report or appeal
- I also see notes from Cinder present in rev tools

![cinder notes present for a report forwarded](https://github.com/user-attachments/assets/5f46b70c-09fc-4678-9296-93c208126b71)

![forwarded appeal with noted from cinder](https://github.com/user-attachments/assets/7e279f06-c565-4c7e-bc2b-9aba5b77396f)

- this is for add-ons (themes have Escalate to AMO as before , tried a scenario and I did not see issues in rev tools)
