### ISSUE TITLE
[Bug]: Uploads are failing

### ISSUE THREAD

**Issue by madprops** [mozilla/addons#15116]
### What happened?

No error message except that something went wrong.

### What did you expect to happen?

A styled html error page.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1171)

```[tasklist]
### Tasks
```

**Comment by madprops** [comment]
![addonsh34](https://github.com/user-attachments/assets/9f64085e-6ecc-4fcf-a345-193062025498)

**Comment by toydotgame** [comment]
+1. I upload the XPI, it validates, I hit next, error page:
![image](https://github.com/user-attachments/assets/6847d5c4-2a77-4fd6-95c0-83b905969610)

**Comment by zxkmm** [comment]
same issue, it's annoying

**Comment by bevinhex** [comment]
same here

**Comment by siriokun** [comment]
I also have this same issue when uploading

**Comment by indykish** [comment]
I have the same here, unable to upload a new version of my addon and distribute.

**Comment by wagnerand** [comment]
Thank you for reporting, we are acknowledging the issue and are looking into the cause and fix.

**Comment by wagnerand** [comment]
For folks following along, this github issue got close with the patch landing in the code base. It has not been rolled out yet, which is what we are preparing right now.

**Comment by wagnerand** [comment]
Update 12pm UTC: Non-production environments have been updated. Final verification is happening right now and will we will deploy to production very shortly.

Next update: 1pm UTC (or when production deploy completed).

**Comment by diox** [comment]
This is now fixed in production. Thanks for your patience.
