### ISSUE TITLE
Suspicious extensions with "AI"-generated descriptions

### ISSUE THREAD

**Issue by ghost** [mozilla/addons#15113]
### What happened?

Several suspicious extensions with very similar descriptions come up when you search for "service workers": https://addons.mozilla.org/en-US/firefox/search/?page=2&q=service%20workers&type=extension

<details>
<summary>Click to see a screenshot</summary>
<img src="https://github.com/user-attachments/assets/ed1b7db3-176e-4b28-b0e5-4823497d4ab7">
</details>

I'm reporting this here to make sure that all results will be looked into. Maybe you can improve your filters to prevent this individual/group from uploading more extensions/creating new accounts..

### What did you expect to happen?

-

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1167)

**Comment by abhn** [comment]
Addressed via ADDONSOPS-370
