### ISSUE TITLE
[Bug]: Add-on history should display whether a version is restricted or blocked

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#15125]
### What happened?

followup for https://github.com/mozilla/addons/issues/15013

### What did you expect to happen?

Rev tools pages don't expose if a version is restricted or blocked
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/633707

Dev hub is already doing that 
https://addons-dev.allizom.org/en-US/developers/addon/block-versions/versions

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1180)

**Comment by wagnerand** [comment]
Mat suggested we put the type of block into the activity details, to avoid having to update existing queries that filter on blocked versions.  On the other hand, using separate activities would make future queries much easier where we want to differentiate between soft-blocks and hard-blocks.

**Comment by ioanarusiczki** [comment]
Note:
After https://github.com/mozilla/addons/issues/15084 landed -> 
when a version is blocked, soften , blocked back the rev tools page shows only "Version blocked"
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634266

**Comment by diox** [comment]
Yeah, once this issue is fixed:
- Softening a block should result in "Version soft-blocked" (or "Version restricted")
- Hardening a block should result in "Version hard-blocked" (or "Version blocked")

**Comment by ioanarusiczki** [comment]
I see this currently on dev , it's not on stage yet

listed extension https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634546
unlisted extension https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/634547
theme https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634548

![hard blocked and soft blocked](https://github.com/user-attachments/assets/6785980b-6124-4cc1-885c-b001a40dac07)

stage now 

https://reviewers.addons.allizom.org/en-US/reviewers/review/2243385

**Comment by diox** [comment]
We're cherry-picking this for stage as we speak, should be in the next tag

**Comment by ioanarusiczki** [comment]
I see the changes on stage too.
