### ISSUE TITLE
[Bug]: "Oops! We had an error." on attempt to submit an addon

### ISSUE THREAD

**Issue by a1ois** [mozilla/addons#15122]
### What happened?

Oops! We had an error
exactly as in https://github.com/mozilla/addons/issues/1537#issue-1997478543
I tried firefox esr and devedition (without any plugins installed / no vpn/proxy usage); nothing helped.

### What did you expect to happen?

not that.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1177)

**Comment by diox** [comment]
Hi,

This was already reported as https://github.com/mozilla/addons/issues/15116 and should now be fixed. Sorry for the inconvenience.
