### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by zod808** [mozilla/addons#1512]
I started firefox and notice none of my book marks where working. Rebooted and nothing. So kept trying different things and nothing would work.
After a couple of reboots I noticed all the book marks that where on the toolbar where gone, nothing. So of the bookmarks at the top were still there, but, they were empty.
This is the first time of having this issue, I can type in address and everything works, but all bookmarks are gone.

Any suggestions will sure help.
Larry

**Comment by wagnerand** [comment]
Please general support, please visit support.mozilla.org
