### ISSUE TITLE
[Task]: Allow threaded responses to developer responses.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mozilla/addons#15130]
### Description

Conversations can already occur in reviews, because modifications to reviews and developer responses cause notifications to be sent to the relevant party. However, this requires the developer and user to constantly modify their comments, which, without review modification histories (requested in https://github.com/mozilla/addons/issues/15131#issue-2627195609), means that the discussion is ephemeral. When this is occurring on multiple reviews, this can cause the review section to appear more like a notice board to a reader, because reviews are instead misused to communicate with the development team, instead of being reviews.

Instead, I propose that threaded response support be implemented, so that a top-level review can remain a review whilst permitting the add-on author and reviewer to discuss in a way that preserves the conversation for others and themselves.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1185)

**Comment by RokeJulianLockhart** [comment]
This was originally requested at https://bugzilla.mozilla.org/show_bug.cgi?id=1648767#c0.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mozilla/addons/issues/15130#issuecomment-2452706681

@D4n2021, just a feature request. I must be spending too much time on bug trackers if I'm inventing acronyms.

**Comment by abyrne-moz** [comment]
Our goal is to keep the reviews system as simple as possible to enable users add-on users to provide detailed reviews that will be useful for others to decide if they should install the add-on, whilst not encouraging it to be used as a support forum or feature request platform.  We encourage developers to include a link to a forum or GitHub issues page to facilitate these types of discussion.  At this time we are not investing in adding more complex logic to the reviewing system.

**Comment by RokeJulianLockhart** [comment]
> We encourage developers to include a link to a forum or GitHub issues page to facilitate these types of discussion.

@abyrne-moz, irrespective, are you at least aware that for add-on authors who do not provide that, the review system is frequently misused by both reviewer and author as a method of discussion (as aforementioned)?

**Comment by abyrne-moz** [comment]
Yeah, I've occasionally seen the review system used this way.  Mandating a bug tracker adds significant overhead to extension developers and is not something we would want to impose on our developer ecosystem.

I've changed it to unplanned, thanks for pointing that out.
