### ISSUE TITLE
[Bug]: Cancel and Disable version at addon submission is greyed out on dev

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#15138]
### What happened?

I tried making submissions as an admin, as a developer and noticed Cancel and Disable Version button is greyed out

![greyedout](https://github.com/user-attachments/assets/cd08bdd0-3e5b-4e7a-8efa-7060cf989cca)

### What did you expect to happen?

This is only on dev. On stage button is active(red)

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1193)

**Comment by diox** [comment]
@chrstinalin this is probably a regression from mozilla/addons-server@7375f1e9336ee3c65dc72dff733cdeab393b27bd could you look at that ?

**Comment by ioanarusiczki** [comment]
Verified on dev

![cancel and disable](https://github.com/user-attachments/assets/4e0ebd60-dcbd-477e-960c-a7767d3d4098)
