### ISSUE TITLE
[Bug]: Broken Headers implementation with Manivest v3

### ISSUE THREAD

**Issue by klappradla** [mozilla/addons#15133]
### What happened?

When updating [our browser extension](https://github.com/bitcrowd/tickety-tick) from Manifest v2 to [Manifest v3](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/), I ran into an issue with the implementation of the [`Headers`](https://developer.mozilla.org/en-US/docs/Web/API/Headers) interface suddenly being broken in Firefox when running the web extension with Manifest v3.

The [`entries()`](https://developer.mozilla.org/en-US/docs/Web/API/Headers/entries) method was suddenly returning `undefined`. I'm using the [ky](https://github.com/sindresorhus/ky) package and the following error occurred within the package's code:

> TypeError: source.entries() is not iterable

The code I run is roughly like this:

```javascript
const source = new globalThis.Headers({
  accept: "application/json",
  "content-type": "application/json; charset=utf-8"
});
// -> Headers { accept → "application/json", "content-type" → "application/json; charset=utf-8" }

source.entries() // -> is not iterable
Array.from(source.entries())
// -> [] empty
```

The code works perfectly fine when I polyfill the `Headers` class with [this package](https://www.npmjs.com/package/headers-polyfill) or when I run the web extension with Manifest v2.

So it seems like a regression bug here.

### What did you expect to happen?

The `Headers` class works perfectly fine with Manifest v2 or when I polyfill it.

For instance turning the headers into an array works fine:

```javascript
const source = new globalThis.Headers({
  accept: "application/json",
  "content-type": "application/json; charset=utf-8"
});
Array.from(source.entries())
// -> [[ "accept", "application/json" ], [ "content-type", "application/json; charset=utf-8" ]]
​```

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1188)

**Comment by willdurand** [comment]
I'd suggest you file a bug on Bugzilla instead: https://bugzilla.mozilla.org/enter_bug.cgi?product=WebExtensions&component=Untriaged
