### ISSUE TITLE
[Task]: Remove Links to Code Manager in the Review Page

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#15149]
### Description

With code-manager being decommissioned, links to it should be removed from the review page.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [x] No links to code-manager via the review page are available.
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1207)

**Comment by alexandruschek** [comment]
Hello, 

I checked this on -DEV, links to code manager were removed.

Thank you!
