### ISSUE TITLE
[Bug]: Default waffle switches are not automatically added during local dev

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#15143]
### What happened?

When running make up with a totally fresh database

```bash
make up INIT_CLEAN=true
```

You end up with no waffle switches/flags even for the ones which we should expect for local development like those created during a migration.

### What did you expect to happen?

Any waffle switch which is created in the on state should be created during data seeding and potentially we should even create all waffle switches that are referenced (somehow) to ensure smooth local development and testing

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1198)

**Comment by willdurand** [comment]
Waffle switches/flags are created by migrations but not every switch has a migration.
