### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by Mr-A768** [mozilla/addons#1514]
Please attach a copy of your add-on, and fill in the following information:
[Seattle Seahawks Browser Theme 2.0.zip](https://github.com/mozilla/addons/files/12326694/Seattle.Seahawks.Browser.Theme.2.0.zip)
* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
New version of an existing theme.
* Whether your add-on is listed or unlisted.
Listed.
* The URL where you submitted the add-on.
[](https://addons.mozilla.org/en-US/firefox/addon/seattle-seahawks-browser-theme/)
* The approximate time you submitted the add-on, with timezone.
Around 12:45 AM CST

**Comment by wagnerand** [comment]
The attached file is not a valid zip file for me. At least I cannot extract it.
