### ISSUE TITLE
[Bug]: ogg don't work in moz-extension://

### ISSUE THREAD

**Issue by Janokisu** [mozilla/addons#15152]
### What happened?

Ogg file cannot be played in moz-extension:// but other files (wav, mp3) formats work. 
But ogg works local (file://).
```
sound = new Audio("xy.ogg");
sound.play();
```

It comes the message 

> HTTP-Content-Type "video/ogg" wird nicht unterstützt. Laden der Medienressource moz-extension://xxxxx/xy.ogg fehlgeschlagen.

> Medien konnte nicht abgespielt werden. Keine Dekoder für angefragte Formate: video/ogg

### What did you expect to happen?

All supported formats can be played in moz-extension://

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1213)

**Comment by willdurand** [comment]
Sorry, this should be reported at https://bugzilla.mozilla.org/enter_bug.cgi?product=WebExtensions&component=Untriaged
