### ISSUE TITLE
Hungarian dictionary is among Hindi (India) ones

### ISSUE THREAD

**Issue by lacavale** [mozilla/addons#1515]
### Describe the problem and steps to reproduce it:
The following alternative dictionary is among Hindi packages on your language addon [page](https://addons.mozilla.org/en-GB/firefox/language-tools/):
[Hungarian Optional Accents Dictionary](https://addons.mozilla.org/en-GB/firefox/addon/hu-optional-accents-dict/)

### What happened?
Probably only a site editing mistake happened. And Hungarian package is appear next to Hindi packages.

### What did you expect to happen?
Hungarian stuff in Hungarian row. Hindi stuff in Hindi row. :)

### Anything else we should know?
I cannot upload the screenshot, but I'm sure you will find it. Just search on page for "hungarian"
Page: https://addons.mozilla.org/en-GB/firefox/language-tools/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-24)

**Comment by wagnerand** [comment]
Hm, this seems to have been done on purpose by the developer of the dictionary. @flodolo, any ideas what we should do here?

**Comment by flodolo** [comment]
That's a pretty horrible hack :-( 

Unfortunately if you install multiple dictionaries in Firefox, only one will show up ([bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1478915)).

I'm not sure if there is much that you can do, since this isn't explicitly against policies? Could it be escluded from the language-tools page to avoid controversies?

**Comment by wagnerand** [comment]
Are the target locale fixed or validated somehow? We do have a `hu` dictionary, could this one just be set to `hu-extra` or something?

**Comment by diox** [comment]
Nowadays `target_locale` is extracted from the manifest.

**Comment by wagnerand** [comment]
ok, but that doesn't change much. I.e., we could reject the add-on and ask the developer to change the target locale in the manifest to something else, but we need to know if that's a viable option.

**Comment by flodolo** [comment]
See the bug I linked to. Having a random `hu-SOMETHING` locale won't help in Firefox, as it doesn't help if you have 3 German dictionaries installed (DE, AT, CH).

**Comment by wagnerand** [comment]
> See the bug I linked to. Having a random `hu-SOMETHING` locale won't help in Firefox, as it doesn't help if you have 3 German dictionaries installed (DE, AT, CH).

Ah, I see, thank you. So I suppose there is nothing we can do?

**Comment by flodolo** [comment]
Correct, they're aware that it's a hack, and they're working around a limitation in Firefox.

The only mitigation possible would be to hide it from the language-tools page to reduce confusion (people will still find it if they search for "hungarian").

**Comment by eviljeff** [comment]
Calling wontfix on this.  Adding a hack in AMO to workaround a firefox bug - that's affecting perhaps only one add-on - isn't worth doing.

**Comment by blfpd** [comment]
<img width="815" height="200" alt="Image" src="https://github.com/user-attachments/assets/ff28d750-42e8-4351-902c-888686853d1b" />

**Comment by beedell-roke** [comment]
@eviljeff, is this tracked on the dictionary author's side, then?

**Comment by eviljeff** [comment]
> [@eviljeff](https://github.com/eviljeff), is this tracked on the dictionary author's side, then?

No idea, you've have to ask them.  

> they're aware that it's a hack,

indicates they are aware of the problem at least

**Comment by lacavale** [comment]
It is good to see that the long lasting low prio tickets become eternal
just like in my job.

Btw. this problem is still present. :D

Üdvözlettel,
Ángyán László
