### ISSUE TITLE
[Task]: Update python to 3.12

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15165]
### Description

Python 3.13 was [released](https://www.python.org/downloads/release/python-3130/) last week, and [3.12](https://docs.python.org/3.12/whatsnew/3.12.html) is a year old, so it's plenty mature enough to upgrade to.  https://www.python.org/downloads/release/python-3127/ is the latest maintenance release at this point.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] addons-server runs python 3.12
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

**Comment by alexandruschek** [comment]
Hello, 

I did a check on -DEV environment thought the automated suite and also manual checks and everything looks ok.

Thank you!
