### ISSUE TITLE
[Bug]: Use correct waffle switch name

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#15166]
### What happened?

After landing [waffle_switch](https://github.com/mozilla/addons-server/pull/22844) this [PR](https://github.com/mozilla/addons-server/pull/22826) did not have the switch name updated and so will always be set to inactive.

### What did you expect to happen?

It should use the correct name: `enable-soft-blocking`

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1228)

**Comment by ioanarusiczki** [comment]
On dev 
![Screenshot 2024-11-15 at 11-33-23 Select Switch to change Django site admin](https://github.com/user-attachments/assets/f85b651b-7eed-4df2-971f-854cb19bdad2)
