### ISSUE TITLE
[Bug]: AMO dev emails sent are generated multiple times on fakemail and not sent into real inboxes

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#15160]
### What happened?

From https://github.com/mozilla/addons/issues/15144#issuecomment-2468096750

same email at addon submission is generated twice (as far as I've checked)
https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196169/change/
https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196173/change/

the auto-approval email is again generated at least twice
https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196174/change/
https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196179/change/

first email at approve from Cinder sent to reporter
https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196178/change/
https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196180/change/
https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196182/change/
https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196183/change/

and the emails sent after override to disable content 
reporter https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196184/change/
developer https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196185/change/
reporter https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196187/change/
developer https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196186/change/
reporter https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196189/change/
developer https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/196188/change/

-> none of these arrived into real inboxes

### What did you expect to happen?

When checking https://github.com/mozilla/addons/issues/15104 I had to do an auto-approval, block, delete block, force enable and unreject -> on stage I've received in the real inbox all emails. On dev, I did not see today emails sent for auto-approval, block or force enable.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1221)

**Comment by diox** [comment]
Looks like the SMTP account we use on dev (which should send very few emails, since it's on an allow list) has been suspended.

**Comment by ioanarusiczki** [comment]
I've emails from dev in the real inboxes, fakemail looks good too.

**Comment by diox** [comment]
Fixed by https://mozilla-hub.atlassian.net/browse/SVCSE-2326
