### ISSUE TITLE
[Task]: Add appeals to jobs completed in Cinder to a separate queue

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#15161]
### Description

Add appeals to jobs completed in Cinder to a separate queue, so that they are separated from the queue that TaskUs normally work from.  This is so that they can be reviewed by T&S in the interim.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] An appeal to a job closed in Cinder is routed to its own queue in Cinder.
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1222)

**Comment by eviljeff** [comment]
QA Note, the request was _just_ for extensions to have this special appeal handling.

**Comment by ioanarusiczki** [comment]
I tried on dev and for extensions I've noticed appeals going to https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjI3/details/jobs?filters=%7B%7D where I could resolve them or escalate to AMO with "Escalate to AMO" option.

Example of a closed appeal in T&S Escalations https://stage.cinder.nonprod.webservices.mozgcp.net/job/1f28c4a5-9da4-431b-a927-dfd4fd1f0e06
Example of escalation: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634051 

For themes, collections , users or ratings seems to be alright, the appeals go into the same queues as before.
