### ISSUE TITLE
[Task]: Change growth threshold algorithm do use percentage points increase

### ISSUE THREAD

**Issue by diox** [mozilla/addons#15178]
### Description

In https://github.com/mozilla/addons/issues/15049 the growth threshold algorithm was changed to be a percentage of the average growth: if the average growth in a tier is X (a decimal number), and the threshold is defined as Y (a percentage number), then it would flag add-ons in that tier with a `hotness` value over X * (1 + Y/100).

We want to change that to be an increase in percentage _points_ instead: with the same definitions of X and Y, it would flag add-ons in that tier with a `hotness` value over X + Y/100.

We should also add a bit more information in the admin to make it more clear what the consequences of changing that number are.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Growth threshold is a percentage point value over the average
  - [ ] The admin tools should display more information about the meaning of the threshold
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1242)

**Comment by ioanarusiczki** [comment]
The value is 0.17 (average for 5 addons , belonging to the second Tier on AMO dev)

Note: versions have to be auto-approved so when the cron task runs to be flagged

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/633520 hotness 0.1
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/633521 hotness 0.3
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/633522 hotness - 0.6
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/633523 hotness 0.8
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/616918 0.00

633621 and 633523 got flagged -> as expected 

This is also displayed now in [admin tools ](https://addons-internal.dev.mozaws.net/en-US/admin/models/reviewers/usagetier/2/change/) "Computed growth threshold before flagging" and "Computed number of addons that would be flagged for growth:"

![flagged](https://github.com/user-attachments/assets/691363e9-61e9-49c7-96a4-e5cd2ee3ac02)
