### ISSUE TITLE
[Task]: Record the number of add-ons pending a manual review on a daily basis

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#15173]
### Description

At 23:30 UTC each day, record the number of add-ons that are pending manual review in each review queue in a database so we can chart it over time.

Make this dynamic in some way so we can measure this for any new queues that we create in the future.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] As a PM, I'm able to chart the number of add-ons that are pending review each day, in each type of review queue
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1237)

**Comment by diox** [comment]
The 4 queues to consider for now are:
- Review queue
- Content review queue
- Second level approval
- Themes

And in the future if new queues are added it should be easy to add them to that table.

**Comment by abyrne-moz** [comment]
Could I propose a scope increase: Enable us to see the number of add-ons pending review by Promoted Class each day?

As this will affect the story point estimate I have re-added the Needs Info label and will update the ticket scope if the extra effort is worth the return on investment.

**Comment by wagnerand** [comment]
@abyrne-moz Should this also include which add-on and how long it has been in the queue?

**Comment by abyrne-moz** [comment]
> @abyrne-moz Should this also include which add-on and how long it has been in the queue?

I figured that info would be tracked/recorded under https://github.com/mozilla/addons/issues/15174

**Comment by wagnerand** [comment]
> > @abyrne-moz Should this also include which add-on and how long it has been in the queue?
> 
> I figured that info would be tracked/recorded under #15174

That would be retroactively per add-on, rather than proactively for the entire queue. But I am not sure we need it, hence asking.

**Comment by diox** [comment]
> Data should be exposed in a table on the AMO database accessible through redash. For this and the cronjob a SRE ticket would need to be created.

It'll probably be worth keeping that table generic for future use-cases. I'm thinking of calling the model `Metrics`, stick that in the `amo` app with `date`, `name` and `value` fields.

**Comment by diox** [comment]
I'll verify myself as the table won't be exposed in the admin, at least for now.

**Comment by diox** [comment]
Ran the command on dev:
```
mysql> SELECT * FROM reviewers_queuecount;
+----+------------+-----------------------------+-------+
| id | date       | name                        | value |
+----+------------+-----------------------------+-------+
|  1 | 2024-12-09 | queue_extension             |   245 |
|  2 | 2024-12-09 | queue_mad                   |  1286 |
|  3 | 2024-12-09 | queue_theme                 |   470 |
|  4 | 2024-12-09 | queue_moderated             |    66 |
|  5 | 2024-12-09 | queue_content_review        |  4486 |
|  6 | 2024-12-09 | queue_pending_rejection     |     2 |
|  7 | 2024-12-09 | queue_decisions             |    26 |
|  8 | 2024-12-09 | queue_extension/recommended |    23 |
|  9 | 2024-12-09 | queue_extension/line        |     1 |
| 10 | 2024-12-09 | queue_extension/spotlight   |     1 |
| 11 | 2024-12-09 | queue_extension/strategic   |     1 |
| 12 | 2024-12-09 | queue_extension/notable     |     2 |
+----+------------+-----------------------------+-------+
12 rows in set (0.01 sec)
```


![Screenshot 2024-12-09 at 14-45-23 Reviewer Tools – Add-ons for Firefox](https://github.com/user-attachments/assets/70bac054-47a7-4171-b24c-9b2cd63df41e)

It matches.

The counts for each specific promoted group also match the contents of the queue.

**Comment by diox** [comment]
The table was added to redash too, so you can check production too, for instance here is the query for yesterday:
```sql
SELECT `name`, `date`, `value` FROM reviewers_queuecount WHERE date = SUBDATE(CURDATE(), 1)
```

**Comment by abyrne-moz** [comment]
Thank you! Is there any way to retroactively populate this data any further back?  Not super urgent, but if it's easy to do that would be great.

**Comment by diox** [comment]
It would be extremely time-consuming to figure out and not reliable enough - we'd need to consider all versions in existence for each day, find if they had a reason to be in the queue at the time, and make sure it had not left it for some reason. For the same reasons we don't have https://github.com/mozilla/addons/issues/15174 yet this is difficult and error-prone with the data we have right now.
