### ISSUE TITLE
[Bug]: Add-ons erroneously in "Held Actions for 2nd Level Approval" queue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#15172]
### What happened?

An add-on (ID: {b15ba26a-103f-4788-a5d9-c7af17f4f763} that was ationed 4 years ago was added to the "Held Actions for 2nd Level Approval" queue. There were no reviewer actions (that are visible in the reviewer tools) from 2021 onwards.

### What did you expect to happen?

This add-on likely shouldn't have been added to that queue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1236)

**Comment by ioanarusiczki** [comment]
Now on dev , an email is sent to the reporter if the content has been already disabled - at reviewer's decision or based on a report 

![email to reporter](https://github.com/user-attachments/assets/8e80d1bb-62e6-4169-847f-3c2bd1375896)

There is a situation where I see something strange : when extensions are rejected in rev tools based on a report (or not)

After rejection if abuse reports are sent these will show up in Cinder. Further I moderated the reports and if Cinder decision is to take content down , DSA emails are sent to reporter and author. This sounds like a bug, it should send the email above so I filed https://github.com/mozilla/addons/issues/15201
