### ISSUE TITLE
[Bug]: Emails sent when versions are restricted should have new wording

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#15180]
### What happened?

A version is restricted such as https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634278 

Email sent is the same as for a blocked version 

![email sent for restrictions to developers](https://github.com/user-attachments/assets/109a9afc-22dd-4c65-b0a8-c320362e57cd)

### What did you expect to happen?

 change the part with "In addition, users who have previously installed those versions won't be able to continue using them."

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1244)

**Comment by diox** [comment]
@abyrne-moz and @wagnerand to agree on some copy for this.

**Comment by abyrne-moz** [comment]
I got approval from legal for the sentence to be changed to 

`In addition, in some cases, users who have previously installed those versions won't be able to continue using them`

We have a larger project scheduled for early next year to audit and revise our automated email copy.

**Comment by abyrne-moz** [comment]
This email can then apply to both soft and hard blocks

**Comment by ioanarusiczki** [comment]
It's the same content now for both , as Alan mentioned [above](https://github.com/mozilla/addons/issues/15180#issuecomment-2505550098) 

![new wording](https://github.com/user-attachments/assets/215cb6e1-a358-4ae9-a99a-3f2a94cf2ffb)

@diox I forgot to check but I  did that now -> no email is sent when versions are softened or hardened.  I hope that's expected.

**Comment by diox** [comment]
> I forgot to check but I did that now -> no email is sent when versions are softened or hardened. I hope that's expected.

This wasn't specified but it's a good call out. Given the wording is the same, just generic to apply to both kinds of blocks, I think not sending an email for hardening/softening blocks is the right thing to do.

**Comment by abyrne-moz** [comment]
I am OK with no email being sent when a block type changes.  We can re-address this in future if we discover this is an issue

**Comment by ioanarusiczki** [comment]
Ok, thanks for the replies, I was thinking the same, no point sending same email twice and it can be revisited.
