### ISSUE TITLE
please add a secure mode for child on Firefox Android

### ISSUE THREAD

**Issue by devtool15424** [mozilla/addons#1518]
Could you kindly develop a secure mode tailored for children and integrate a feature to block adult content on Android? This could be achieved by incorporating a DNS filter that leverages online services such as Family Shield. Your efforts in enhancing online safety for younger users would be greatly appreciated.

For Android Firefox

Android chrome have a mode like this

**Comment by wagnerand** [comment]
Please submit ideas to https://connect.mozilla.org/t5/ideas/idb-p/ideas
