### ISSUE TITLE
[Bug]: review page version activity box can get cut

### ISSUE THREAD

**Issue by diox** [mozilla/addons#15198]
### What happened?

STR:
- Enable `enable-activity-log-attachments` switch
- Submit an unlisted add-on (single version)
- Get it auto-approved
- Soft-Block it
- Harden the block

Look closely at the version history in the review page: there is a visual artifact where the the text of the last activity appears to go over the border of the cell

![Screenshot 2024-11-25 at 14-28-54 rabbil-rabugong-narkato – Add-ons for Firefox](https://github.com/user-attachments/assets/fc5dd764-06e4-4a93-b180-236908631197)

(There are likely faster/easier ways to reproduce - but you probably need a single version, then enough single-line activities to be higher than the left-side column)

### What did you expect to happen?

The text shouldn't go over the border like that

This is caused by `enable-activity-log-attachments` because when it's enabled, it adds another cell to each row of activity... but only those, the rest of the table only have 2 cells per row.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1262)

**Comment by ioanarusiczki** [comment]
I've seen this now on -stage at version unblocked

![unblockedversion](https://github.com/user-attachments/assets/979bc45b-3936-4f66-9837-72cfc04a1648)

**Comment by diox** [comment]
A variant I saw in production, with more history (I'm only including a partial screenshot since this is prod data):
![Screenshot 2024-12-02 at 16-52-00 TinEye Reverse Image Search – Add-ons for Firefox](https://github.com/user-attachments/assets/20df8242-bb96-4138-a460-a79a4d4c89f9)

**Comment by ioanarusiczki** [comment]
I've checked on dev that `enable-activity-log-attachments` is enabled.

I could reproduce it with:

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/634903

or with reviewer notes https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634904

**Comment by chrstinalin** [comment]
It looks like there's some OS-related trickery here, as I'm unable to reproduce those bugs on my MacOS machine (tables render as expected), but does indeed occur on my Windows machine. @ioanarusiczki Could I confirm which OS you're using?

For context, on my MacOS machine --
![image](https://github.com/user-attachments/assets/098d3db5-18fd-4e4a-8be0-6e34521f5e26)
![image](https://github.com/user-attachments/assets/93995b24-e125-401e-8c63-599e712f69ce)

**Comment by ioanarusiczki** [comment]
Yes, it looks good now on win too.

![win11_1](https://github.com/user-attachments/assets/0f2234cd-3a7a-4162-a7ff-f7fbe3c0c0eb)

![Version notes](https://github.com/user-attachments/assets/9f1d1c1a-23c2-4d1b-8d74-11f62829da3e)
