### ISSUE TITLE
please add a secure life to block porn on window

### ISSUE THREAD

**Issue by devtool15424** [mozilla/addons#1519]
I strongly urge you to develop a security mode specifically tailored for children for Windows. It would be wise to integrate a feature to block adult content using a DNS filter based on online services like Family Shield. Given the growing importance of online safety for younger users, it's imperative tat Windows take proactive measures in this area.

For windows Firefox

Chrome have a mode like this where we can change DNS

**Comment by wagnerand** [comment]
Please submit ideas to https://connect.mozilla.org/t5/ideas/idb-p/ideas
