### ISSUE TITLE
Reviewer - Developer communication

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#152]
Currently, all add-on review arrives and is answered via email. This makes it hard for AMO reviewers and editors to track communication to developers, and hard for add-on developers to contact a reviewer to ask questions.

We’d like to bring this review communication interface into AMO for developers to use.

Feature specs and plan by @jvillalobos:
https://docs.google.com/document/d/1NeIXRkarfA0RBKuo2wnCzEpgCLwvXm4SlxdSeOiPeMA/edit

Mockups:

New unread review is marked in the sidebar navigation and current version:

![new review available](https://cloud.githubusercontent.com/assets/51007/16477240/2ec88cee-3ee4-11e6-9926-7d42285cf4b4.png)

Review history will show/hide on click. For now, we can either show every review or paginate it. New/unread review is highlighted.

![review history open](https://cloud.githubusercontent.com/assets/51007/16477251/4c24c6b8-3ee4-11e6-910c-7b5d5d292efb.png)

**Comment by jvillalobos** [comment]
The doc link you want is https://docs.google.com/document/d/1NeIXRkarfA0RBKuo2wnCzEpgCLwvXm4SlxdSeOiPeMA/edit

**Comment by brampitoyo** [comment]
Updated the link to the docs. Thanks! I had overlooked it when creating the issue.

**Comment by brampitoyo** [comment]
Sounds like the implementation work on this issue has been completed, so I’m closing it.

**Comment by brampitoyo** [comment]
Sounds like the implementation work on this issue has been completed, so I’m closing it.
