### ISSUE TITLE
Not able to login firefox addon, every time it is asking for Two factor authentication even after entering code it is showing that wrong code

### ISSUE THREAD

**Issue by Veerut1** [mozilla/addons#1521]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
If this is still an issue, please file a bug at https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Firefox%20Accounts
