### ISSUE TITLE
[Bug]: Missing title in blocked pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#15221]
### What happened?

UX noticed that we're missing a title in the "blocked" pages.

### What did you expect to happen?

Copy matches the UX spec.

<details>
<summary>hard block copy</summary>

### Why did this happen?
This extension, theme, or plugin violates Mozilla’s add-on policies by [Insert reason beginning with an ‘ing’ verb; E.g. “collecting user data without permission.” ]

### What does this mean?
Until the violation is resolved, [extension name] won’t be available for download from addons.mozilla.org. It will be automatically disabled and no longer usable in Firefox.

### How does Mozilla enforce its policies?
When Mozilla becomes aware of add-ons, plugins, or other third-party software that seriously compromise Firefox security, stability, or performance and meet certain criteria, the software may be blocked or restricted from general use. For more information, please read this support article
</details>

<details>
<summary>soft block copy</summary>

### Why did this happen?
This extension, theme, or plugin violates Mozilla’s add-on policies.

[Reason for violation given in a complete sentence. May not be translated.]

### What does this mean?
Until the violation is resolved, this add-on won’t be available for download from addons.mozilla.org. If it’s already installed, it will be disabled and users will be informed about the violation. They may choose to enable the add-on again at their own risk.

### How does Mozilla enforce its policies?
When Mozilla becomes aware of add-ons, plugins, or other third-party software that seriously compromise Firefox security, stability, or performance and meet certain criteria, the software may be blocked or restricted from general use. For more information, please read this support article.
</details>

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1288)

**Comment by willdurand** [comment]
Good call. There is actually a problem with the Figma spec itself... so I asked UX for confirmation.

**Comment by willdurand** [comment]
@ioanarusiczki Per Slack conversation, iwe should use "this add-on" in both cases.

**Comment by ioanarusiczki** [comment]
Then I think it's looking good

2 more examples with the reason of the block/restriction (from admin)

![blocked with reason](https://github.com/user-attachments/assets/f40d625f-7c9e-44b2-bbb4-e727f0233b61)

![restricted with reason](https://github.com/user-attachments/assets/3e916264-cd13-4adc-877a-cee02260f0d3)
