### ISSUE TITLE
[Task]: ForeignKey (indirectly) link ContentDecision to ActivityLog

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15228]
### Description

We need to know what ContentDecision is associated with an ActivityLog so we are able to resume a held 2nd level approval at a later point with all the relevant metadata

There were complicated alternatives (see https://mozilla-hub.atlassian.net/browse/AMOENG-1230) but this is the most straightforward.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] A decision is linked to the activitylog for a decision
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1296)

**Comment by ioanarusiczki** [comment]
I've tried with a report and then appeals from Cinder for a rating or an add-on on AMO dev

Activity log is present for an add-on disabled 

![activity log1](https://github.com/user-attachments/assets/78000d4f-2a9e-4081-a7d0-f721a7111388)

or when enabled after an author appeal is sent 

![approve from Cinder](https://github.com/user-attachments/assets/08d25db4-ca5b-40aa-8127-5727a0cbab0d)


Same if repeated for a rating

rating deleted https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4593494/change/
rating undeleted https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4593495/change/

I've noticed an edge case on ratings and filed it (could be out of scope but I've tried to explain that in more detail separately so I can mark this verified) https://github.com/mozilla/addons/issues/15250
