### ISSUE TITLE
[Bug]: Hinzugefügte Browsererweiterung nicht gefunden  

### ISSUE THREAD

**Issue by Samet256** [mozilla/addons#15227]
Sehr geehrte Damen und Herren,

ich habe gestern die Browsererweiterung  Privacy Badger hinzugefügt. Als ich heute die Einstellungen vorgenommen habe, habe ich bei einer Auswahl auf das Fragezeichen geklickt um in Erfahrung zu bringen, was das zu bedeuten hat. Dann erschien auf der Erklärungseite ganz oben noch ein großer roter Button " Datenschutz Badger installieren"., woraufhin ich gelesen habe, dass diese Erweiterung durch das Trainingssystem automatisch nicht sichtbare Tracker automatisch blockiert. Als ich dann auf diesen Button geklickt hatte, kam dann ein Feld mit automatisch angeklickten Auswahlen, wie z.B. Zugriff auf meine Daten, Zugriff auf alle Tabs, Zugriff darauf , dass er auf allen Webseiten alles lesen und auch alles Mögliche verändern und manipulieren kann. Ich glaube, das waren die drei ausgewählten Punkte. Als ich dann auf Hinzufügen geklickt habe, erschien " Die Einstellungen können Sie im Anwendungsmenü vornehmen. Dennoch finde ich weder im Anwendungsmenü, noch bei den hinzugefügten Erweiterungen NICHT DIESE ERWEITERUNG. Das kann es doch nicht sein??? Im Nachhinein sind mir diese automatisch ausgewählten Auswahlen sehr kurios vorgekommen, und jetzt, wie gesagt, finde ich nicht mal diese Erweiterung. Zudem konnte ich bis zum jetzigen Zeitpunkt heute keine Support Seite bei Firefox mehr finden. Anscheinend ist wirklich an dieser Browsererweiterung etwas dran, dass diese Browsererweiterung alles manipuliert. Auch an meinem PC ist schon einiges nicht mehr so, wie es vorher war. Daher bitte ich Sie sehr um Ihre schnellstmögliche Hilfe diese Erweiterung zu finden und zu deaktivieren, bevor es ganz zu spät ist. Denn das wäre fatal. Für Ihre Bemühungen und Ihr Engagement möchte ich mich bei Ihnen jetzt schon im Voraus bedanken.

Mit freundlichen Grüßen

Dilek Beskazalioglu

**Comment by diox** [comment]
Hi,

This looks like a Firefox issue, and this tracker is about issues on addons.mozilla.org itself. Maybe look on https://support.mozilla.org or file a ticket in https://bugzilla.mozilla.org if you think you found a bug in Firefox.

**Comment by Samet256** [comment]
Sehr geehrte Damen und Herren,

ich habe am 08.12.2024 die Browsererweiterung  Privacy Badger
hinzugefügt. Als ich am 09.12.2024 die Einstellungen vorgenommen habe,
habe ich bei einer Auswahl auf das Fragezeichen geklickt um in Erfahrung
zu bringen, was das zu bedeuten hat. Dann erschien auf der
Erklärungseite ganz oben noch ein großer roter Button " Datenschutz
Badger installieren"., woraufhin ich gelesen habe, dass diese
Erweiterung durch das Trainingssystem automatisch nicht sichtbare
Tracker automatisch blockiert. Als ich dann auf diesen Button geklickt
hatte, kam dann ein Feld mit automatisch angeklickten Auswahlen, wie
z.B. Zugriff auf meine Daten, Zugriff auf alle Tabs, Zugriff darauf ,
dass er auf allen Webseiten alles lesen und auch alles Mögliche
verändern und manipulieren kann. Ich glaube, das waren die drei
ausgewählten Punkte. Als ich dann auf Hinzufügen geklickt habe, erschien
" Die Einstellungen können Sie im Anwendungsmenü vornehmen. Dennoch
finde ich weder im Anwendungsmenü, noch bei den hinzugefügten
Erweiterungen NICHT DIESE ERWEITERUNG. Das kann es doch nicht sein??? Im
Nachhinein sind mir diese automatisch ausgewählten Auswahlen sehr kurios
vorgekommen, und jetzt, wie gesagt, finde ich nicht mal diese
Erweiterung. Obendrauf kommt noch, dass ich an keinen Support mehr dran
komme, da sich jedes Mal, wenn sich eine Support Seite öffnet, diese
Seite sofort wieder ausgeblendet wird. Und auch wenn ich etwas schreibe,
wird in der Sekunde, was ich geschrieben habe, in der Sekunde
manipuliert und total anders geschrieben. Und auch einige Seiten, auf
denen ich bin, werden sofort wieder ausgeblendet, insbesondere gerade,
wenn ich auf einer Mozilla Firefox Seite etwas schreiben, oder etwas
suchen möchte, verschwindet die jeweilige Seite kurioser Weise sofort.
Heute habe ich gesehen, dass mittlerweile sogar in meine E-mails
manipuliert wird. Ich habe auch gestern noch an die Admins von Mozilla
Firefox geschrieben, habe aber bis jetzt keine Antwort erhalten. Was
auch möglich ist, dass diese Erweiterung Datenschutz Badger auch diese
E-mail manipuliert und einfach gelöscht hat. Denn es waren nämlich in
meinem Posteingang noch mehrere E-mails plötzlich weg. Das kann es doch
nicht sein??? Anscheinend ist wirklich an dieser Browsererweiterung
etwas dran, dass diese Browsererweiterung alles manipuliert. Auch an
meinem PC ist schon einiges nicht mehr so, wie es vorher war. Daher
bitte ich Sie sehr um Ihre schnellstmögliche Hilfe diese Erweiterung zu
finden und zu deaktivieren, bevor es ganz zu spät ist. Denn das wäre
fatal. Also, die Erweiterung Privacy Badger habe ich bereits entfernt,
aber diese andere Erweiterung Datenschutz Badger ist nicht auffindbar
sehr kurioser Weise,und die Manipulationen gehen immer weiter. Wenn sich
dieses Problem nicht bis spätestens morgen aufzulösen ist, dann bleibt
mir nichts anderes übrig, als dieses bei der Polizei zu melden, bevor
mein ganzer PC und alles total infiziert ist und dann gar nichts mehr zu
retten ist. Deshalb bitte ich Sie äußerst schnell hinter dieser
Angelegenheit zu gehen und das Problem am besten heute noch zu lassen
lösen.


Für Ihre Bemühungen und Ihr Engagement möchte ich mich bei Ihnen jetzt
schon im Voraus bedanken.


Mit freundlichen Grüßen


Dilek Beskazalioglu
