### ISSUE TITLE
[Task]: Make addons-frontend Compatible with Multiple Promoted Addon Groups

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#15226]
### Description

mozilla/addons-server#22888 breaks the addons-frontend as it cannot handle more than one promoted add-on group.

It should be able to handle the changes in the patch, while continuing to handle single promotions while #22888 is not merged.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Promotions are correct and do not break addons-frontend when using the current version of addons-frontend
  - [ ] Promotions are correct and do not break addons-frontend when using the version of addons-server merged with mozilla/addons-server#22888
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1293)

**Comment by ioanarusiczki** [comment]
@willdurand  @chrstinalin 

I've some questions about this:

- a partner add-on is : recommended + by firefox badge? 
- how can I set it up to get both badges on frontend ? I  tried from promoted module on dev but I don't see a way...

**Comment by chrstinalin** [comment]
> @willdurand  @chrstinalin 
> 
> I've some questions about this:
> 
> - a partner add-on is : recommended + by firefox badge? 
> - how can I set it up to get both badges on frontend ? I  tried from promoted module on dev but I don't see a way...

@ioanarusiczki  We're choosing only to show one badge, even if an add-on has multiple, based on the "importance" of the add-on. (Recommended, then line). Apologies, I forgot to update the issue.

For now (until the backend portion of this is complete), the only thing that needs to be verified is that everything still shows as expected (i.e nothing has changed), as there's no way for an add-on to have multiple groups until then.

**Comment by ioanarusiczki** [comment]
@chrstinalin np, thanks for clarifying. 

I didn't finish yet but so far I didn't find anything unusual on frontend recommended/by firefox badges. 
Definitely cannot add 2 promotions for one extensions, I could only add one of the two.

**Comment by ioanarusiczki** [comment]
I'm done with regression testing and I did not see issues:

- I could set up new badges - recommended or by firefox
- looked over search results, autocomplete, detail pages, user profile pages ->  look as before for recommended,  by firefox. 

I won't mark this issue verified yet because I've [info](https://github.com/mozilla/addons-frontend/pull/13343) about the future ux for partner add-ons.
