### ISSUE TITLE
[Bug]: [STAGE][API] License use in version create request

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons#15224]
### What happened?

Found through an automated test:

Addon File: 
[listed-addon-new-version.zip](https://github.com/user-attachments/files/18009958/listed-addon-new-version.zip)

ENVIRONMENT - STAGE: https://addons.allizom.org/

STR:
1. POST - Upload Create: /api/v5/addons/upload/
2. POST: Version Create: /api/v5/addons/addon/(int:addon_id|string:addon_slug|string:addon_guid)/versions/ (Slug used: "new_sluggish_slug")
3. Observe that: status code = 201, message = {"license":["License with slug=GPL-2.0-only does not exist."]} is present, 

The two cases in which the expected status is met is when the license is: ISC and LGPL-2.1-only

### What did you expect to happen?

Expected status code 409 and message: "Version 1.1 already exists"

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1291)

**Comment by diox** [comment]
Could you clarify which POST parameters results in what status code and message exactly ?

**Comment by alexandruschek** [comment]
Hello, I tried again for every license to reproduce the same scenario manually and it works as expected, I need to check the test in the aumation suite and update it. I will close this issue
