### ISSUE TITLE
[Bug]: Cinder overrides are broken

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15245]
### What happened?

See https://mozilla.sentry.io/issues/6131407225/?project=6310819

Overrides from Cinder were regressed with the work to allow certain add-ons to be held for 2nd level approval (specifically https://github.com/mozilla/addons-server/pull/22822/files).

https://github.com/mozilla/addons-server/pull/22917 (https://github.com/mozilla/addons-server/commit/81377915d7b0fd98efdfcd258181d13fc41ce047) would fix this, as part of a larger refactoring

### What did you expect to happen?

Overridden decisions from Cinder are carried out by the AMO webhook handler.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1314)

**Comment by ioanarusiczki** [comment]
I've left a comment into https://github.com/mozilla/addons/issues/15151#issuecomment-2538929896

I'll try make some regression testing on:
- add-on flagged for HR in rev tools for add-on policies
- report escalated to rev tools
- an appeal escalated to rev tools 
- a recommended add-on/theme that needs 2nd level approval
- a rating/collection or user reported and moderated exclusively from cinder

**Comment by ioanarusiczki** [comment]
I tried some testing and I got expected results for the above except for appeal escalations which I see being present in the review pages but were not flagged for HR , this I am sure it's been filed before but I don't remember if it got fixed 

 https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634956
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634957 

Other results were as expected:

- a scenario of an add-on reported for add-on policies in rev tools. 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/634952

- a report escalated to rev tools.
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634955

- 2nd level approval for content disabled from Cinder, applied Proceed with action from https://github.com/mozilla/addons/issues/15075#issuecomment-2498153938 
recommended extension https://addons-dev.allizom.org/en-US/firefox/addon/try-dev1/

- 2nd level approval for a mozilla collection with approve and proceed from https://github.com/mozilla/addons/issues/15086
https://addons-dev.allizom.org/en-US/firefox/feedback/collection/4757633/social_media/
https://addons-dev.allizom.org/en-US/firefox/feedback/collection/4757633/54adf6148c9e45c28a8fa35bd03fe2

- a rating moderated from Cinder - the initial decision is not to take content down, reporter is sending an appeal, second decision is to disable content, the author is sending an appeal , final decision is to reinstate content.

**Comment by eviljeff** [comment]
This is planned to be fixed on stage/prod with https://github.com/mozilla/addons-server/pull/22943 around 2024-12-16, with a out-of-band deployment;
and then properly with the fix for https://github.com/mozilla/addons/issues/15151 for the 2025.01.09 deploy.

**Comment by ioanarusiczki** [comment]
I tried some regression testing over DSA on AMO stage 

- add-on flagged for HR in rev tools for add-on policies ✅ -> reported appealed then the developer appealed 
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/2244547

- report escalated to rev tools, decision is to take content down ✅ https://reviewers.addons.allizom.org/en-US/reviewers/review/2244606

- developer appeal escalated to rev tools ❌  - known issue filed https://github.com/mozilla/addons/issues/15247. 
Working with reporter appeals ✅ -> reporter appeal denied from rev tools https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/2244548

- a recommended add-on/theme that needs 2nd level approval ✅
1. When decision is to disable content from Cinder it would show up into 2nd level approval queue 
https://reviewers.addons.allizom.org/en-US/reviewers/decision-review/1808
proceed with action -> content is disabled on AMO 
2. Another example with by firefox add-on this time it's https://reviewers.addons.allizom.org/en-US/reviewers/decision-review/1809 
approve content instead -> reporter gets an email with the right to appeal 
3. forward to reviewer tools ->  https://reviewers.addons.allizom.org/en-US/reviewers/review/2244550

- 2nd level approval for non add-on content ✅ 
Dev reply on by Firefox add-on goes into the queue https://reviewers.addons.allizom.org/en-US/reviewers/decision-review/1812

- a dev reply on a regular add-on with a decision from Cinder ✅
content is taken down as expected https://stage.cinder.nonprod.webservices.mozgcp.net/job/e0d48fd5-82e8-4846-be1b-e113fbaae734

- override feature : emails sent, old appeals have a message (no longer throw 404s) ✅
 disable with approve https://stage.cinder.nonprod.webservices.mozgcp.net/job/c8549420-4ac2-4488-a9b6-1d2fc9dccb96
approve with disable  https://stage.cinder.nonprod.webservices.mozgcp.net/job/f931cc7c-e6f5-40ee-b662-f97771725ad9a 
disable policy replaced by another https://stage.cinder.nonprod.webservices.mozgcp.net/job/ac204c98-b040-41e9-8411-e62ed2a2dc29
