### ISSUE TITLE
[Bug]: appeal link for review-blocked add-ons does not work

### ISSUE THREAD

**Issue by yoe** [mozilla/addons#15243]
### What happened?

I received a notification that my add-on was removed from addons.mozilla.org after manual review.

I think the removal was done in error, and want to click on the appeal link.

The appeal link returned a page stating "We're sorry, but we can't find what you're looking for." (and the network tab in the developer console shows that it 404s)

### What did you expect to happen?

I expected a form that allowed me to make my case as to why I think the removal was done in error.

I looked at #14939, which seemed the closest, but it's not relevant for this issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1312)

**Comment by diox** [comment]
Hi,

Could you share an identifier/URL for the add-on in question so we can investigate further ?

**Comment by yoe** [comment]
The add-on ID is "belgiumeid@eid.belgium.be"

**Comment by wagnerand** [comment]
@yoe Apologies for disabling the add-on by mistake. We have reinstated it. I'll keep this bug open for us to investigate why you couldn't appeal, because you should have been able to.

**Comment by yoe** [comment]
Thanks for the reinstatement.

We were a bit surprised that this add-on, which has existed for over 10 years and has amost 160k users, was disabled without warning. A message that this was about to happen before it happened would have made sense.

Happy to help debug the other issue if necessary.

Other than all that, issue resolved from our end.

**Comment by wagnerand** [comment]
@yoe yes, we have protections in place so that this shouldn't happen, unfortunately they have failed for your add-on. We are addressing that in https://github.com/mozilla/addons/issues/15244, so it should not happen again.

Our sincere apologies!

**Comment by yoe** [comment]
OK, that's fair. Thanks, then.

**Comment by eviljeff** [comment]
Hi, the appeal link 404'ing is addressed by https://github.com/mozilla/addons/issues/15151 - scheduled to land in January (though possibly earlier), so closing this issue in favour of that one.
