### ISSUE TITLE
[Bug]: Notable add-on was not held for 2nd level of approval

### ISSUE THREAD

**Issue by ialecse** [mozilla/addons#15252]
### What happened?

Notable add-on was automatically rejected, after the delayed rejection expired, without a 2nd level of approval and the listing was taken down.

### What did you expect to happen?

The expectation was to hold for 2nd level of approval after the pending rejection expired.

Steps to reproduce:
1. Delay reject listed versions
2. New version is uploaded days a few days before the rejection expires
3. Delay reject the "Awaiting review" version after the previous rejection expired
-> New version will be delayed reject and the others automatically rejected without 2nd level approval

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1322)

**Comment by eviljeff** [comment]
At this time only decisions originating from Cinder are able to be held for 2nd level approval.  The epic to enable that functionality for reviewer tools originated decisions is in progress.
