### ISSUE TITLE
Papaly

### ISSUE THREAD

**Issue by rbrtn** [mozilla/addons#1525]
### Describe the problem and steps to reproduce it: I clicked a link to download a browser extension called Papaly. The link was in an email about tips for using the software. 

This is the link address: https://u186931.ct.sendgrid.net/ls/click?upn=UaeS1ro-2By1VVWIzEXLK8Nn-2F2qnD2DXprg6YLncIoCHe-2Fb-2FGWUMb4KhsTcYEcW53ifE3KPPg6Nz80Fx4pai6C0qNmQ7QWQ0s9ZHFMoqVenFADQ3uQUwwR64Lse2syguINd8P6p29Op3AgzrH3GCiG80wfOfIBLqezvaEAhEEayEM-3DfQSA_EehDzUbLjtIPj-2BJrGkPb3CtRDk-2BL8vJNIlvfdvgeOwUxie90yrbRgumDqBk0hc4BQ7bASmIfBQYdbPilNy2rjdriCDPFYylz-2BMM9gOZZRs1oeoBUhJ4RnFWC5cq11X-2F4JtXmcrmdSMt6DkEK9-2FhAnJJYOeoNfQMH1XMVM5QwMqFAijwlvqVDjMCIDKjJtYw4IQZb0qluu6EJS73Ea-2BUIQw-3D-3D

This is the email, in plain text:

Papaly logo
Welcome!
Hi, trchrd1@yahoo.com. Thanks for signing up. Papaly is a powerful tool that helps you save and organize all your bookmarks. We hope you find it useful!
A few tips to get started:
1. Download the browser extension or browser bookmarklet. It lets you save and organize new bookmarks with one click.
2. Import your bookmarks from services like Delicious, Diigo, Pocket, and all major browsers.
3. Connect your social accounts to get an aggregated feed of all your links from social media.
Check out our apps.
A simple bookmarking experience with our browser extension and iOS app.
Chrome icon Firefox icon iPhone icon
 iOS app and browser extension
To unsubscribe from these emails, click here.
(Please include as many details as possible.)

### Anything else we should know? Papaly is a bookmark manager.

(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
I recommend reaching out to the developer of the add-on.
