### ISSUE TITLE
[Bug]: A reviewer cannot reply to a soft-blocked version

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#15251]
### What happened?

For an add-on, several versions were soft-blocked.
The developer replied with a question, but reviewers cannot reply, as the "Versions" select in the Review Tools page is empty.

### What did you expect to happen?

A reviewer should be able to reply to soft-blocked versions.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1321)

**Comment by ioanarusiczki** [comment]
For unlisted versions I could send reviewer replies and the un-reject multiple versions is empty - no versions available there to be selected. 

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/635030

As a reviewer (I am with an admin account) I can send replies while add-on is force-disabled but a developer cannot reply.
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/635031

Another test a theme , version blocked then softened.

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/635035

**Comment by ioanarusiczki** [comment]
Verified on -stage with 
https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/2244375
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/2244271
