### ISSUE TITLE
[Bug]: Mc Afee True Key is disabled

### ISSUE THREAD

**Issue by MissG1264** [mozilla/addons#15256]
### What happened?

I have used True Key for my passwords for quite a long time. Since recently, it seems that this add-on is blocked due to non conformity with Mozilla's add-on policy. What has happened? Is my password safe no longer safe? For me McAfee always has been one of the reliable tools in cyber safety... I'm a bit lost.
Thanks for checking and getting back to me :-)
Kind regards,
Gunda

### What did you expect to happen?

I expected True Key as an add-on on my mozilla firefox main browser page.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1327)

**Comment by wagnerand** [comment]
If you have the add-on installed, you can click on the "Learn more" button in the add-ons manager which should lead you to this page: https://addons.mozilla.org/en-US/firefox/blocked-addon/@true-key/, which contains the reason why the add-on has been restricted.

In the add-ons manager, you also have the option to re-enable the add-on at your own risk. Please also take a look at https://support.mozilla.org/en-US/kb/add-ons-cause-issues-are-on-blocklist to learn about restrictions and blocks, their impact and your choices.
