### ISSUE TITLE
Specify an MVP for DevHub

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#153]
We’d like the dev hub front page to be a place where we can direct new and existing developers, and direct them towards some clear paths towards resources and documentation:
- If I’m new
  - Why develop an add-on
  - How to get started developing
  - What technology to pick
  - How to stay up to date with news
- If I already have an add-on
  - Why WebExtensions? Why Firefox?
  - How to port/migrate
  - What’s Firefox WebExtensions API coverage

Our MDN documentation already handles most of these needs, and we simply need to point developers to the right place and ensure that it’s well organised. However, some needs are fulfilled by things that aren’t documentation, for example: blog posts, developer interviews/stories, discussion forums, etc.

While we’re talking with both MDN and Developer Marketing about where to build this dev hub, I’d like to start thinking about content and linking/syndicating strategy.

Here’s a pre-alpha strawman mockup to get us started. Everything about this mockup will change (graphic courtesy of DropBox). The only thing it’s designed to do is to help us start thinking about what kind of information we want our dev hub to have, where they will live, and how they will be linked together or syndicated:

![amo-devhub](https://cloud.githubusercontent.com/assets/51007/16477577/e8ffc09e-3ee6-11e6-8433-b91fe214d259.png)

**Comment by andymckay** [comment]
Completely drive by comment, we should think about if we want to use the term WebExtension all the time. Or perhaps just the term add-on or just extension. To me WebExtension is the underlying technology name, but at some point in the future (don't know when) there might not be any other way of writing an extension and the term WebExtension might not be relevant.

We have a habit at Mozilla of pushing our taxonomy all the way down to everyone. We might not want to do the same this time around.

**Comment by brampitoyo** [comment]
> …we should think about if we want to use the term WebExtension all the time. Or perhaps just the term add-on or just extension.

This is a good point. Maybe we should talk to other vendors here and reach some sort of an agreement (maybe this is too ambitious and lengthy). In terms of UX, I’m interested in adopting a common term that at least Chrome and us can agree on. After all, much of the underlying technology is standards-based and similar. Maybe it’s “extension”. Maybe it’s “add-on”. Then our documentation can be fully neutral, but we can have a section called something like “Firefox-flavoured add-on”, where we explain everything that we do a little differently. Just an idea.

**Comment by brampitoyo** [comment]
#### Content

I’ve started thinking about what sort of content we’d need our dev hub to have. It turned out that there are quite a lot, and development documentation represents one big part of it.

In my head, I divided it into a few buckets:

* I’m interested, I’m a business person/stakeholder, convince me that it’s a good idea. This is the page you saw on the top post
  * Why Firefox? Why WebExtensions?
  * How will it help me realise my vision?
  * What are the resources available?
  * I’m interested. Can I subscribe to news and updates?
* Before I write any code, I may design on paper. While I write my code, I want to know how to make my add-on look world class. You can argue that this section should be integrated into our technical documentation instead of separated into its own section, and you’d be right, too!
  * Style guides
  * Design articles: accessibility, design for Firefox desktop & Android form factors, localisation
  * AMO banners, recommended listing page image sizes, recommended icon sizes
  * Design templates: PSDs, Sketch files, etc.
* I am writing my code. This part already fully handled by MDN.
  * Getting started
  * Examples
  * Guides, how-to, concepts
  * API references
* I want to submit to AMO, but more than that, I also want to be successful
  * What can I learn from developers who have been successful?
  * All about AMO
    * Your AMO listing page: how to optimise it
    * Review and submission guidelines
    * How do editorials work?
  * All about business, marketing and growth
    * Choosing a business models: paid, freemium, subscription, etc.
    * Measuring success using metrics and analytics
    * How to grow userbase with every new version
* I have a problem and I need some help
  * Discourse
  * IRC
  * File a bug
* I want to know what’s new, and what’s coming
  * Developer communication: managing the impact (Amy has written a great section on this)
  * Timelines & Roadmaps
  * Are We WebExtensions Yet can possibly go here, but it’s better to integrate it with documentation
  * Add-ons Blog
  * Hacks Blog, if the content is relevant to add-ons

All the titles above are really long. They’re designed to describe what each section contains. We need short names. Here’s one set of names I’ve thought of.

* Explore
* Design
* Build
* Publish
* Community Support
* News and Updates

**Comment by brampitoyo** [comment]
#### Design

All the content is well and good, but how does everything fit together?

I think it’s a good idea to represent this structure visually and try to imagine how many different content and coexist.

Keep in mind, everything about these mockups can and will change, and your feedback will be most helpful!

##### Two caveats

1. There should of course be a register/sign in interface, a submission flow, and a management interface. But for the moment, my focus is to create a page where we can direct new and existing developers toward some clear paths.

2. You can argue that we don’t need to divide these sections so finely if there aren’t enough content in each (for example, who will write this content? I don’t have an answer to this), and that a lot of the articles on publishing, design, etc. can all go under a big section called “Documentation”. This is a great point. It’s definitely one way to organise. But for the sake of being clear, I’m separating everything into its own space.

This is just my take on the new dev hub. What’s your vision? What content do we need? How do they all fit together? I’d like to hear from you!

(Click image to maximise)

##### Explore

<img src="https://cloud.githubusercontent.com/assets/51007/16755775/2ed982f0-4854-11e6-80ce-547355121ef3.png" width="400px">

##### Design

<img src="https://cloud.githubusercontent.com/assets/51007/16755805/8f3d4f3c-4854-11e6-9928-d2914cb22667.png" width="400px">

##### Build

<img src="https://cloud.githubusercontent.com/assets/51007/16755815/9e371284-4854-11e6-8bf3-3f98d2295205.png" width="100px">

##### Publish

<img src="https://cloud.githubusercontent.com/assets/51007/16755840/ba115c9e-4854-11e6-9bf9-2231e9ebe4de.png" width="400px">

##### Community Support

<img src="https://cloud.githubusercontent.com/assets/51007/16755848/c8380b42-4854-11e6-977e-e2f3e6e1570d.png" width="400px">

##### News

<img src="https://cloud.githubusercontent.com/assets/51007/16755859/daf689ac-4854-11e6-8e42-22d2f45827c7.png" width="400px">

**Comment by designakt** [comment]
For the first version, let us focus on what is most important for an MVP.
What are the most important user questions we need to answer?

- Why is WebExtensions a great dev environment you should use?
- How can I know about important updates to WebExtensions? (Sign up with Google Account?)
- How can I build a WebExtension? (What can I do? Can I do X?)
- How can I publish my WebExtension? (if I am new or if I have a Chrome Extension)

**Comment by designakt** [comment]
What are relevant examples of other dev hubs? (To use as a reference)
- https://developer.chrome.com/extensions
- https://developer.box.com/
- https://developer.github.com/
- https://developer.uber.com/
- https://developer.spotify.com/
- https://developer.apple.com/ios/
- https://developer.apple.com/develop/
- https://developer.microsoft.com/windows/windows-apps/
- https://developers.facebook.com/
- https://developers.sparkpost.com/
- https://developers.soundcloud.com/
- https://developers.google.com/cast/
- https://www.htcvive.com/develop_portal/
- https://dev.twitter.com/
- https://www.drupal.org/

**Comment by brampitoyo** [comment]
More examples:

* https://www.youtube.com/yt/dev/
* https://developer.vimeo.com/
* http://electron.atom.io/
* https://slack.com/developers
* http://nerds.airbnb.com/

Findings:

* Naming: almost always “[Product] Developers”. Sometimes it’s “[Product] for Developers”.
* Call-to-action: almost always there. Anything from “Read documentation” to “Try for free”.
* Get started/quick publish: always leads to a tutorial, not to a tool/wizard as I had expected
* Information hierarchy: if a product-level exists, it always exists on top of documentation
* Documentation: it’s either called “Documentation” or “Docs”. Sidebar navigation is always used.
* API: often present on the front page even though it leads to a section of docs, but always named.
* News/Blogs: almost always refer to the same thing, and often have blog-like formatting.
* Subscribe to update: I thought I’d find a way to subscribe to some sort of a newsletter, but there was none. Instead, I was expected to follow the blogs via RSS (sometimes, there’s a link to subscribe by RSS)
* Support: either leads to a searchable FAQ, or a developer support forum

How will this apply to our devhub? What’s our information architecture? How should our sections be named, and where should each section lead to?

* Naming: “Firefox Add-ons Developers” or “Firefox Extensions Developers”. Or maybe use “Mozilla”?
* Call-to-action: it’s obvious that we should have this. But instead of leading readers to the first page of the documentation, it should lead to a place that clearly asks: “Who are you? What do you want to develop?” and then direct them to the right places. For example:
  * New to webextensions? [Read Getting Started]
  * Port your Chrome extension: [Link1] [Link2]
  * Rewrite your Firefox add-ons: [Link3] [Link4]
  * Ready to submit your new add-on? [Submit] --> this will lead to register/sign in flow
* Get started/quick publish: if we have a way to import from Chrome Webstore or integrate with GitHub, add it to the list of places as described above.
* Information hierarchy: if we need an item called “Product”, it should probably be called “Technology”, and under that, we have “WebExtensions”, “Add-on SDK” and “Legacy”. But this widens our scope considerably. Let’s just have an item called “Documentation”, and it leads to WebExtensions on MDN.
* Documentation: I think we should call it “Documentation”, but if the space don’t fit, “Docs” is fine. Either way, it’s not a big deal.
* API: I think we should not just call it “API”, but “WebExtensions API”.
* News/Blogs: We already have one. There’s no need to add another. Let’s call this item “Blog”, and have it link to our existing blog.
* Subscribe to update:
  * I think we should have a clear “Subscribe via RSS” link on our blog, and clearly tell users that blog is where they should watch out for news.
  * What about email newsletter? Maybe we should think of each email newsletter as the summation of a few blog posts, that gets sent every few weeks.
  * How do you subscribe to it? By signing up for an account. Of course, not everybody will register, but we can tell everybody to subscribe to our blog instead. This way, nobody is missing out on any information.
  * (I’m not sure if this is a good or a bad idea, but it’s what I’m thinking of after seeing all the devhub examples)
* Support: I think we should call it “Community Support” to emphasise our unique difference.
  * It should link to the [Developer Communication page at Mozilla Wiki](https://wiki.mozilla.org/Add-ons/developer/communication), which Amy had written and already contains a lot of good information. Think of this as a kind of FAQ: “Before you contact us on IRC or make a posting on Discourse, here’s how add-on development will evolve, and here’s what you can do about it”.
  * This Wiki page already links to our IRC, Mailing List and Discourse Forum, which is perfect

That’s my recommendations from reading other devhubs. Thoughts?

**Comment by brampitoyo** [comment]
Here’s a mockup that was designed while keeping the recommendations in mind.

![home 1x](https://cloud.githubusercontent.com/assets/51007/16971469/27be903a-4e78-11e6-9b29-2f3f8dac1602.png)

**Comment by brampitoyo** [comment]
I’ve updated the front page to reflect suggestions given at the critique two weeks ago:

* Each user group now gets their own section that expands on click
* Each section has clear call to actions:
  * If you’re new: learn, get inspired, sign up
  * If you have a Firefox add-on: test add-on, view porting guide, managing the impact
  * If you have a Chrome extension: test add-on, view porting guide, publish

What do you think?

Next on my to-do list: figure out what happens after you sign up with a new account. I’m thinking that we’d like to have some sort of an onboarding experience. Can we introduce some articles, and populate the “My submission” section with prompts/examples?

<hr>
I don’t have an add-on

![home - no add-on 1x](https://cloud.githubusercontent.com/assets/51007/17282169/598c9d9a-57f7-11e6-8e20-d9ed74484af2.png)

<hr>
I have a Firefox add-on

![home - firefox add-ons 1x](https://cloud.githubusercontent.com/assets/51007/17282172/5facfc7e-57f7-11e6-8da8-74530045c15d.png)

<hr>
I have a Chrome extension

![home - chrome add-ons 1x](https://cloud.githubusercontent.com/assets/51007/17282177/67ece200-57f7-11e6-8511-f39ada861bef.png)

**Comment by brampitoyo** [comment]
Here’s what might happen after you sign up for a new account.

First, we’ll ask you whether you’re new or already have a Chrome extension (maybe we can already determine this from where they’ve clicked the “Sign up” button?)

Second, we’ll show the right information to guide you onto the right path. If you’re new, we’ll show you some more getting started articles and tell you where they can be found. And if you have a Chrome extension, we’ll show you where to submit your ported add-on.

What do you think?

![sign up and onboarding flow](https://cloud.githubusercontent.com/assets/51007/17284576/18d4db32-5810-11e6-93b7-8760930aa4c9.png)

**Comment by brampitoyo** [comment]
Instead of having a modal window that separates new users from the interface, I’ve decided to go with something much simpler and easier to implement: a checklist, a search box and a list of documentation articles.

When you just signed up or don’t have any add-on uploaded yet, we consider you a beginner. But at the very least, you would have read an article from the documentation, so we’re going to give you a strong incentive to either 1) Upload your first add-on, or 2) Learn more about WebExtensions if you’re not ready yet.

![home - signed in - firstrun or beginner 1x](https://cloud.githubusercontent.com/assets/51007/17688539/4413cf5e-63d4-11e6-862f-e845eb94342c.png)

When you have uploaded at least one add-on, we assume that you at least already know how to publish, or have finished porting your add-on. So the same “Need Help?” area now contains more advanced topics like how-to, concepts, workflow and references.

However, if you have a legacy add-on (a lot of our existing users will have this), we should show an additional box that says “Hey. WebExtensions is coming. This is what you should do to prepare for it”. The content of this box is a rehash of the “Porting” section of the documentation. This is because existing Firefox add-on developers may skip our new front page and sign in immediately. Having the porting articles here is a chance to learn an information that they might have skipped.

![home - signed in - advanced and legacy 1x](https://cloud.githubusercontent.com/assets/51007/17688582/a9b4edb6-63d4-11e6-9913-c9cbce9c2c85.png)

These mockups are also a chance for me to play around with the visual style of the new devhub. In other words, this may be how the new devhub look like.

Thoughts? Ideas?

**Comment by brampitoyo** [comment]
Some thoughts of things to work on:

* Can we integrate the same detection that we do for legacy add-on into the submission flow? For example: “We noticed that you’re uploading a legacy add-on. Do want to do x?”
* Consider having a link to “Download a sample extension”, so if you don’t have an extension built, you can do it quickly.
* Once you upload your first add-on, the “Need help?” section topics changes from beginner to advanced. This is jarring. Is there a topic/UI transition for this inbetween state?
* It would be nice to be able to drag-and-drop add-on into the “Upload button”. Then, we can just go straight to the validation step.
* We mentioned wanting to have an inline editing of add-on listing page. If this is the case, then consider having a horizontal navigation to replace the existing sidebar. This allows us to devote the whole screen for this interface.
* You can register either from the “I don’t have an add-on” or the “I already have a Chrome extension” path. Should the green checkbox steps work any differently based on the different path you’ve taken to get there?

**Comment by brampitoyo** [comment]
The MVP has been specced out on mozilla/addons-frontend#1021, and the mockup has been posted there, too. Any additional work will happen on that bug, so I’m closing this one (plus, this one has a pretty big scope and we’re not going to do all of it immediately).
