### ISSUE TITLE
scopus

### ISSUE THREAD

**Issue by hossamems** [mozilla/addons#1530]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by fintan-ryan** [comment]
If you use the 
[wayback machine](
https://web.archive.org/web/20181016000000*/https://addons.mozilla.org/firefox/downloads/latest/scopus-document-download/addon-933162-latest.xpi)
and navigate to 16 October 2018 you can retrieve an active version of the broken link.
