### ISSUE TITLE
Confirmation E-mail from adding new author to add-on is never received

### ISSUE THREAD

**Issue by stvshw** [mozilla/addons#1532]
I am trying to add new authors (developers) to our Single Sign-on Assistant Firefox Add-on. I can "add" new authors with no problem. However, the confirmation e-mail that the system says has been sent is never received. All new authors remain in the "Authors pending confirmation" list and are unable to access the add-on.

As one of the current owners, I receive emails whenever something changes in the account, including notification that new authors have been added. I even tried creating myself a new different account and tried add it as an author with that same results as others that I have tried to add.

Submission Page:  https://addons.mozilla.org/en-US/developers/addon/netiq-basic-sso/edit
Authors and License Page:  https://addons.mozilla.org/en-US/developers/addon/netiq-basic-sso/ownership

![image](https://github.com/mozilla/addons/assets/64863620/1f3ccfa4-9c07-45b3-b43f-db3a0dd93b00)

**Comment by diox** [comment]
Hi,

Could you tell us the approximate date & time when you tried inviting new authors ?

**Comment by stvshw** [comment]
Hi Mathieu,

They have been in the last 2-3 week timeframe. However, I removed and tried
to re-add the ***@***.*** account as a test the same day I submitted
the issue.

Regards,
-Steve

**Comment by stvshw** [comment]
Hello. I just tried adding new authors again with the same results. You asked about the approx. date and time last time. This most recent attempt was conducted on Tues, Nov 8 from 2:00-2:30 PM MST.

**Comment by wagnerand** [comment]
@stvshw I took at look at our delivery logs.

For the email *varke*@..., we successfully sent the author-removal email (subject: `An author has been removed from your add-on`) on 2023-08-11 21:16:33 UTC. A second later, we tried to deliver the author-added email (subject: `Author invitation for Single Sign-on Assistant`) which failed. The error message we received is:

```
1004 Your message was rejected due to its content
```

It looks like your mail server rejected the email. Can you check that on your end?

**Comment by stvshw** [comment]
@ wagnerand
Would it be possible for you to provide the email address that is used to
send the confirmation emails? My IT dept is asking for it.

**Comment by wagnerand** [comment]
@stvshw the email goes to the email address that was invited.

**Comment by stvshw** [comment]
@wagnerand
They are requesting the email address that is used by mozilla to send the
invitations, not the email addresses of those who are invited.

For example, since I am the owner when I try to add a new author, I receive
an email with the subject "An author has been added to your add-on". The
sender of this email is from "Mozilla Add-ons" and the email address
provided is ***@***.***".
