### ISSUE TITLE
Ad Blocker add on

### ISSUE THREAD

**Issue by DannyRJW** [mozilla/addons#1535]
I have been using Firefox for many years and never had a problem. Now when I go to You Tube and try to load a video, it blocks me. I uninstalled the blocker and still receive the same message. What can I do?
![You Tube Block](https://github.com/mozilla/addons/assets/120689046/3240c503-ab7c-4216-972c-22a613e46f55)

**Comment by diox** [comment]
Hi,

This is not a Firefox/addons.mozilla.org issue. You can raise that problem with your adblocker of choice.
