### ISSUE TITLE
AMO should shows all extensions when using Fenix to visit addons.mozilla.org and able to search any extensions, the same as using Firefox

### ISSUE THREAD

**Issue by 0x391F** [mozilla/addons#1538]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
Since version 120, fenix could install arbitrary addons from AMO, but user needs to visit  https://addons.mozilla.org/en-US/firefox/, using desktop site, otherwise he/she couldn't finds out all addons. 

### What did you expect to happen?
AMO should shows all extensions when using Fenix to visit addons.mozilla.org and able to search any extensions when using mobile site, the same as using Firefox.

**Comment by willdurand** [comment]
Visiting AMO with Firefox for Android will show a new homepage with more compatible add-ons. There is no need to visit the desktop site. Firefox letting users install more add-ons is currently being rolled out so that might explain why you don't see more add-ons on AMO (for Android) yet.

**Comment by 0x391F** [comment]
> Visiting AMO with Firefox for Android will show a new homepage with more compatible add-ons. There is no need to visit the desktop site. Firefox letting users install more add-ons is currently being rolled out so that might explain why you don't see more add-ons on AMO (for Android) yet.

No, I don't think that. For example, BTools couldn't find when using mobile site https://addons.mozilla.org/en-US/android/search/?promoted=recommended&q=BTools&type=extension, but it's available when using desktop site https://addons.mozilla.org/en-US/firefox/search/?q=BTools

**Comment by willdurand** [comment]
> No, I don't think that. For example, BTools couldn't find when using mobile site [addons.mozilla.org/en-US/android/search/?promoted=recommended&q=BTools&type=extension](https://addons.mozilla.org/en-US/android/search/?promoted=recommended&q=BTools&type=extension), but it's available when using desktop site [addons.mozilla.org/en-US/firefox/search/?q=BTools](https://addons.mozilla.org/en-US/firefox/search/?q=BTools)

That's because this add-on isn't marked as compatible with Android.
