### ISSUE TITLE
Bug addon compatibility Firefox for Android

### ISSUE THREAD

**Issue by davaiyo** [mozilla/addons#1539]
Hi, on the website addons.mozilla.org there is probably a bug that freezes the minimum Firefox for Android version to 121.0a1, no matter which version is defined in the manifest.json ([current manifest.json](https://codeberg.org/nobody/LocalCDN/src/branch/main/manifest.json)).

Older versions that have already been uploaded can only be selected up to 78.0. After that, a grayed-out area is displayed up to 121.0a1. Nothing can be selected between 78.0 and 121.0a1.

This stops the addons in a collection from being updated in Firefox for Android.

![screenshot1](https://github.com/mozilla/addons/assets/100505502/e4b7cfb9-7438-4f74-9928-bf0399dd6228)
![screenshot2](https://github.com/mozilla/addons/assets/100505502/114af39e-ff60-4e06-a7c6-bdd1d71ee362)

**Comment by diox** [comment]
Hi,

This is not a bug: unless they have been selected to be part of the limited set, developers are not yet allowed to choose to make their add-on compatible with Firefox for Android release versions.

This is going to change very soon, as announced in https://blog.mozilla.org/addons/2023/11/01/is-your-extension-ready-for-firefox-for-android/.

**Comment by davaiyo** [comment]
Thanks for the quick answer. I know the blog article and have already prepared the addons (the addons is ready for Firefox on Android a long time).

Few Werks ago it was possible to install the addon in Fennix (and the forks) with the [collection workaround](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/). This is no longer possible because the version is not compatible.

**Comment by diox** [comment]
The collection workaround is meant for Nightly/Beta, and is therefore a bit obsolete for add-ons that use `gecko_android` in the manifest (or add-ons that their developers have customized compatibility in AMO), since currently Nightly/Beta are higher than 121.0a1.
