### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by dolkensp** [mozilla/addons#154]
I'm not getting any feedback on what is wrong with this add-on.

It's built around the same framework taht my other existing add-on is built upon (indeed, it's intended to expand the functionality of my other add-on, and is already listed in the chrome store...)

* occurred during the submission of a new add-on

* unlisted at the moment - intending to list publically

* https://addons.mozilla.org/en-US/developers/addon/submit/2

* 2016-07-03 20:50 GMT
[BulkXPLOR.zip](https://github.com/mozilla/addons/files/345271/BulkXPLOR.zip)

**Comment by jvillalobos** [comment]
It looks like you're uploading a zip file that contains a directory in it. You need to have the manifest in the root of the package for it to be valid. Repackaging the zip seems to fix the problem, so I'm closing this issue.

**Comment by dolkensp** [comment]
Not quite sure I follow - The manifest is in the root of the package?

![image](https://cloud.githubusercontent.com/assets/469666/16569965/0ed889e4-4235-11e6-9a7b-26acfe8ea468.png)

**Comment by dolkensp** [comment]
Hmm - never mind.

Re-packaged it as you mentioned and it fixed itself. It appears dragging an updated manifest into an existing zip using windows is not supported at your end. Not a big deal though :) Thanks!
