### ISSUE TITLE
Can't login to my addons account

### ISSUE THREAD

**Issue by ambs** [mozilla/addons#155]
Hi.

My username is Hashashin, with e-mail ambs at di.uminho.pt. I have two extensions (dictionaries for PT). But I am unable to login. Also, the recover password doesn't work.

Is there any way you could associate these two extensions to my other account, hashashin@gmail.com?

Thanks

**Comment by jvillalobos** [comment]
Please send an email to amo-admins AT mozilla DOT org with the details.
