### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by LidaMdo** [mozilla/addons#1551]
if someone can help me I'm begginer (and french), you can contact me here : mammadov.adil07@gmail.com

Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator. **_### this error occurred during the submission of a new add-on, a new version_**

* Whether your add-on is listed or unlisted. ???

* The URL where you submitted the add-on. ### [https://addons.mozilla.org/fr/developers/addon/submit/upload-listed](**_https://addons.mozilla.org/fr/developers/addon/submit/upload-listed_**)

* The approximate time you submitted the add-on, with timezone. ### **_Timezone 21:14 (French time)_**

can't upload the add-on so here is the code :

<img width="1470" alt="Screenshot 2023-12-16 at 21 17 43" src="https://github.com/mozilla/addons/assets/154021264/946f445f-c584-45aa-8a6e-c5bb5c5360fb">
let recognition;
let notes = '';
let targetElement; // Définissez ou attribuez l'élément cible

function startSpeechRecognition() {
  recognition = new SpeechRecognition(); // Utilisez l'objet SpeechRecognition standard
  recognition.continuous = true;
  recognition.interimResults = true;

  recognition.onresult = function (event) {
    const transcript = event.results[event.results.length - 1][0].transcript;
    notes += transcript;

    // Mettez à jour l'élément cible avec les nouvelles notes
    updateTargetElement();
  };

  recognition.onend = function () {
    // Réinitialisez la reconnaissance vocale après une pause
    if (isSpeechRecognitionActive) {
      startSpeechRecognition();
    }
  };

  recognition.start();
}

function stopSpeechRecognition() {
  if (recognition) {
    recognition.stop();
  }
}

function updateTargetElement() {
  // Mettez à jour l'élément cible avec les nouvelles notes
  if (targetElement) {
    targetElement.value = notes;
  }
}

// Exemple de déclenchement de la reconnaissance vocale lorsque l'utilisateur clique sur un bouton
// document.getElementById('startButton').addEventListener('click', startSpeechRecognition);

**Comment by willdurand** [comment]
which file are you trying to submit?

**Comment by LidaMdo** [comment]
I finished this project
Thanks xD
