### ISSUE TITLE
Addon icons are always screwed up on Android

### ISSUE THREAD

**Issue by zwresn453** [mozilla/addons#1552]
### Describe the problem:
Most of the addons have the wrong icons (e.g. multiple addons have the same icon)

### steps to reproduce it:
1) Open Firefox for Android
2) Install multiple addons
3) Open the addons menu (More > Addons)
4) In this view, over time, most of the extensions will have the wrong icons (for example, multiple addons will have the UBO icon instead of their own icon).
5) If they aren't screwed up yet, open multiple of the addons' menus (one after another), then go back to the menu in step 3.

### What did you expect to happen?
The icons are correct

### Anything else we should know?
Screenshot:

![20231216_211843](https://github.com/mozilla/addons/assets/121317613/b8b8aba0-a128-427f-94ab-93ccb3849522)

**Comment by willdurand** [comment]
Right, this appears to be https://bugzilla.mozilla.org/show_bug.cgi?id=1806838 (on Bugzilla, where we track Firefox bugs). Thanks!
