### ISSUE TITLE
Sort permissions by "severity", or at a very least, put `"<all_urls>"` at the top

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/addons#1555]
### Describe the problem and steps to reproduce it:
Some permissions are MUCH more dangerous then others. Most notably the `"<all_urls>"` and `"*://*/*"`.
Currently it's somewhere down, not very noticeable. [Example](https://addons.mozilla.org/firefox/addon/multi-account-containers/):

![image](https://github.com/mozilla/addons/assets/6358971/0ed1efe5-164d-49c9-9d79-126071336677)

I would suggest to put "<all_urls>" on top, then other host permissions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-25)

**Comment by diox** [comment]
Hi,

AMO's permission order/display logic was deliberately made to follow Firefox's behavior so I suggest filing a bug against Firefox itself in [bugzilla](https://bugzilla.mozilla.org/).

Note that a very large number of add-ons request `<all_urls>` or equivalent - ultimately whether or not it's the most important permission to display is highly debatable.
