### ISSUE TITLE
Unavailable RSS feed

### ISSUE THREAD

**Issue by BozoDel** [mozilla/addons#1556]
I can find and download the feed thorugh the browser (at https://addons.mozilla.org/blog/feed.xml), but feed readers can't reach it. I've tried with Akregator and Feedbro.

**Comment by diox** [comment]
The feed is [valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Faddons.mozilla.org%2Fblog%2Ffeed.xml) and works in the aggregators we tested it with (Liferea, NetNewsWire). Maybe it was a temporary problem on your end.

**Comment by BozoDel** [comment]
Huh, it does work with Liferea.
Guess I gotta report it somewhere else.
Thanks!
