### ISSUE TITLE
Not able to search for addons via about:addons

### ISSUE THREAD

**Issue by mhammond** [mozilla/addons#156]
STR:
- In desktop Firefox visit about:addons, then "Get Add-ons"

Expected:
- A way to search for addons so a user can find, eg, "ad blockers" or "youtube downloaders" etc.

Actual:
- No facility exists on the page. You can browse addons, you can install featured addons, but you can't search for addons.

I mentioned this in the #addons IRC channel and it was suggested I bring this to the attention of @designakt

**Comment by designakt** [comment]
The design intent of this page is to have a place for a very simple and understandable start with add-ons. A place where new users can discover how Firefox Add-ons can be of use to them. This page will contain an ad blocker and a tool to download videos as those are very popular choices. It will also highlight some themes as those are also a popular starter with add-ons. So those selected choices will not even require a search. 
![138946213](https://cloud.githubusercontent.com/assets/8145891/16613387/1cf891b2-436c-11e6-9a22-b62e43ffae5e.png)

For more elaborate functionality we refer users to AMO at the bottom of the page to browse or search all available add-ons, or they can search for specific add-ons via any other page in about:addons besides discovery (one click away from discovery, and if one is not a first time user, extensions is most likely the selected page in about:addons and it contains a search.)

We have thought about providing search also on the discovery page, but we feel that the introduction to Firefox Add-ons is the more important task of that page and should not be distracted from with any other actions.

What I take away from you description is that missed re-naming the page from "Get Add-ons" to "discover Add-ons" as expressed in our design intent. And I can see how this might help mislead into thinking this is a page to get all add-ons I want, when in fact that page is AMO.
And the current in-between state currently shown in Nightly probably does not help either. Hopefully this week we will switch from the old page to the implementation of the [new discovery page](https://discovery.addons-dev.allizom.org/) shown above.

**Comment by mhammond** [comment]
Thanks for the reply, but I think that's misguided. What about the user who knows what they are looking for?

> they can search for specific add-ons via any other page in about:addons besides discovery
> (one click away from discovery,
...
> We have thought about providing search also on the discovery page

A page called "discovery" without search? If someone wants to install an addon named "myaddon", they can't use "Get Add-ons" but instead must search google to find it? That sounds very wrong to me.

**Comment by designakt** [comment]
I agree that search is important for experienced users knowing what they search for, or anyone who heard the name of an add-on from a friend who hasn't shared a link.
People in search for a specific add-on can use google (probably the quickest way), but they don't need to. We still provide search access points for add-ons: People can use search on the extension and themes page or visit AMO and directly search for it there.
![discopanesearchaddon](https://cloud.githubusercontent.com/assets/8145891/16618342/2f675b86-4389-11e6-9203-4a8780f131ba.gif)

I feel this conversation comes down to ones expectations of this page:
**a)** Discover what Firefox Add-ons (the system providing all add-ons) can do for me. Aiming at people not particularly familiar with add-ons, or not knowing about the system at all.
**b)** Discover all add-ons. Aiming at everyone that somehow wants to use any add-on and anyone who is not too familiar, or not at all.
We are currently aiming at supporting **a** with the discovery page, and use AMO & search in extensions/themes to provide **b**. (The previous discovery page feels like an attempt to rebuild AMO in the browser, which we did not see a need for as we have AMO for that full exploration.)

I am happy to have a chat via Vidyo if you feel I miss your point.

**Comment by grahamperrin** [comment]
Firefox 65.0.1: 

![image](https://user-images.githubusercontent.com/192271/53637590-7c609a00-3c1b-11e9-88e9-2deb34514447.png)

**Comment by designakt** [comment]
Good point... missed closing this issue.

**Comment by grahamperrin** [comment]
Thanks. 

[about:addons' Discovery page should have a search box · Issue #756 · mozilla/addons](https://github.com/mozilla/addons/issues/756) remains open (and FWIW, I'm ambivalent).
