### ISSUE TITLE
Problem with extension to download documents from Scopus

### ISSUE THREAD

**Issue by soerme** [mozilla/addons#1562]
### Describe the problem and steps to reproduce it:

In the database Scopus there is the option to directly download scientific papers, if available. To do this in Firefox there is apparently an extension needed. When trying to download a paper from Scopus there is a pop-up indicating that I need the extension, and a button saying "get extension". When clicking the button I'm forwarded to a page saying that the page or file could not be found.

**Comment by wagnerand** [comment]
For questions about an extension's availability on Firefox you should contact the developer of that extension, thanks.
