### ISSUE TITLE
Update ubuntu image on all repos

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#1565]
### Describe the problem and steps to reproduce it:

CircleCI is deprecating some ubuntu images that we rely on. Starting in Feb we will have reduced availability and by Sept 30 they will become totally unavailable.

We should bump to a more stable version to prevent our CI from crashing.

Repos: https://docs.google.com/spreadsheets/d/16hNnnQ5wu4If5iu_JVqW7X0bcsn85fgVWS0zLqNRwPc/edit#gid=672901121
Example: github.com/mozilla/addons-server/blob/master/.circleci/config.yml#L346C14-L346C35
Update: https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-16)

**Comment by diox** [comment]
Affected repos:
- [ ] addons-code-manager
- [ ] addons-customs-scanner
- [ ] addons-frontend
- [ ] addons-server

The rest don't appear to be using specific `ubuntu` images (they're happy with the default)
