### ISSUE TITLE
Add on for Scopus download needed

### ISSUE THREAD

**Issue by LarissaPagels** [mozilla/addons#1566]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I want to download an article from scopus. After clicking the download button a window saying:  "The Scopus Document Download Manager requires an extension Help/More Information
We created a fast and lightweight solution for the Firefox browser.
Click the button below to download the extension"
appears. After clikcing on the button, a new tab opens saying "Diese Seite wurde leider nicht gefunden."

what do I have to do to get this article?

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
For questions about an extension's availability on Firefox, please contact the developer of that extension, thanks.
