### ISSUE TITLE
note tabs stacked, vertical

### ISSUE THREAD

**Issue by appsupnootherway** [mozilla/addons#1567]
Nine Notes: Since latest update ? (2022; currently 'no update found') its note tabs are laid out vertically, not horizontally.

Would uninstalling/reinstalling the add on lose the notes I already have?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-15)

**Comment by eviljeff** [comment]
Hi, you need to reach out to the developer of the Nine Notes add-on via the support or homepage.
