### ISSUE TITLE
Bugfix for adblock for youtube 

### ISSUE THREAD

**Issue by STEPEHN** [mozilla/addons#1568]
### Describe the problem and steps to reproduce it: after 10 minutes of viewing videos, the screensaver blacks out the screen completely.
(Please include as many details as possible.)

### Anything else we should know?  my version of Adblock for YouTube is dated 2022, is there a later version that perhaps has a fix for this issue?  If so how do I go about updating Adblock for YouTube to the latest version? 
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Hi,

Please report problems with a particular extension to the developer. Add-ons should update automatically, it's possible you're not on an official version, so maybe try uninstalling it and installing it again from https://addons.mozilla.org/en-US/firefox/ (if possible, use a "Recommended" extension, those have been reviewed thoroughly for quality and security).
