### ISSUE TITLE
Missing string for venetan language

### ISSUE THREAD

**Issue by mtrevisan** [mozilla/addons#157]
In the list at page https://addons.mozilla.org/en-US/firefox/language-tools/ , in the language column, the voice "Venetan dictionary (vec)" should be "Venetan" and "Vèneto". Same goes for the italian version ( https://addons.mozilla.org/it/firefox/language-tools/ ) that displays "Diŧionario de lengua vèneta - Dizionario di veneto (vec)" instead of "Venetan" and "Vèneto".
Thank you.

**Comment by andymckay** [comment]
Moved over to: https://bugzilla.mozilla.org/show_bug.cgi?id=1286019

**Comment by mtrevisan** [comment]
They tell me it can be an amo error. So I think this bug belongs here.

(NOTE: there's a bug described [here](https://github.com/mozilla/addons-server/issues/2823) that prevents non-logged-in users to view the language in the language-tools page)
