### ISSUE TITLE
The Scopus Document Download Manager requires an extension

### ISSUE THREAD

**Issue by leslieglasser** [mozilla/addons#1571]
### Describe the problem and steps to reproduce it:
Using Firefox, attempted to download a file via Scopus database and a download of extension was required
### What happened?
Reached https://addons.mozilla.org/firefox/downloads/latest/scopus-document-download/ with no such extension found
### What did you expect to happen?
Load an extension for Firefox
### Anything else we should know?
![image](https://github.com/mozilla/addons/assets/31502431/b60c953c-1f5b-482e-bca9-b9a5e105d6c7)

**Comment by diox** [comment]
For questions about an extension's availability on Firefox, please contact the developer of that extension, thanks.
