### ISSUE TITLE
Impossible to update an addon

### ISSUE THREAD

**Issue by mickaphd** [mozilla/addons#1572]
### Describe the problem and steps to reproduce it:
Impossible to update an addon

### What happened?
I cannot upload it
"Received an empty response from the server; status: 500"

**Comment by wagnerand** [comment]
We are currently investigating an issue with AMO that would affect this. Sorry for the inconvenience.
We'll update this ticket once we have more information or when the issue has been resolved.

**Comment by wagnerand** [comment]
We believe the issue is resolved. Please let us know if you are still having troubles.
