### ISSUE TITLE
All addons show: <Add-on name> "could not be verified for use in Firefox and has been disabled."

### ISSUE THREAD

**Issue by zaggynl** [mozilla/addons#1575]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
All my Firefox addons were disabled, they show:
<Add-on name> "could not be verified for use in Firefox and has been disabled."
Likely same as reported here: https://support.mozilla.org/bm/questions/1442616
I'm on Firefox 123.0.1 on OpenSUSE Tumbleweed, I'm not seeing this issue on my Windows machines.
When I attempt to install an addon I get ' Installation aborted because the add-on appears to be corrupt.'

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-3)

**Comment by willdurand** [comment]
This looks relevant: https://bugzilla.opensuse.org/show_bug.cgi?id=1221531

**Comment by willdurand** [comment]
@zaggynl could you please try to install this extension: https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/. You can uninstall it after, this is just to verify one of my assumptions.

**Comment by zaggynl** [comment]
Thanks for the reply, I was able to install the translations extension!

**Comment by willdurand** [comment]
> Thanks for the reply, I was able to install the translations extension!

Alright so that confirms my suspicion, which I described in https://bugzilla.opensuse.org/show_bug.cgi?id=1221531#c22. This is an openSUSE bug at this point.

One more thing: I would recommend you to _not_ try to uninstall/re-install your add-ons since that will clear all the extension data.

**Comment by EazyVG** [comment]
With latest NSS packages, like mozilla-nss version 3.98-2.2, addons have started working on firefox from opensuse/mozilla repos. Great.
Firefox 123.0.1, openSUSE Tumbleweed.
