### ISSUE TITLE
UX mocks/implementations for add-ons search (desktop + mobile)

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons#159]
This is somewhat related to #156, as a search box on that page could activate the search we're looking to replace. That's up to UX if they think having a "Search for more add-ons" box at the bottom would be useful.

One of our goals for this quarter (Q3) is to redo the current search page in `about:addons`. We'll need mockups/UX for how this will work.

Eventually we'll create a big tracker bug for new search, I'll add that to it eventually.

**Comment by pwalm** [comment]
Search at the bottom is super useful! Great idea. I'll mock it up.

**Comment by pwalm** [comment]
(Some background) We decided to postpone search on about:addons until search on AMO is better. That will happen later this year.
