### ISSUE TITLE
Addon Validation Error - linter takes too much time on huge files

### ISSUE THREAD

**Issue by BlueGreenMagick** [mozilla/addons#1590]
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
* Whether your add-on is listed or unlisted.
* The URL where you submitted the add-on.
* The approximate time you submitted the add-on, with timezone.

1. Submission of new add-on
1. Listed
1. https://addons.mozilla.org/en-US/developers/addon/submit/distribution
https://addons.mozilla.org/en-US/developers/upload/0df568f35e1e4dc2821d2d0c60e13db0
1. Thu Mar 21 2024 17:00:00 GMT+0900

Received a warning of 

```
Sorry, we couldn't load your WebExtension.

Error: Validation was unable to complete successfully due to an unexpected error.
Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU
```

Running latest(6.24.0) npm `addons-linter` tool on the add-on file, it runs fine with only some flagged warnings, and no errors.

Uploaded the add-on to GDrive because GitHub has a 25MB file limit:
https://drive.google.com/file/d/1kJpXDpCoYPTNXJoqWT1OBT1ntHW6gB4l/view?usp=sharing

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-21)

**Comment by diox** [comment]
Hi,

On my machine and in our production environment, with latest addons-linter running in Node 18, I can't get the validation process to finish. Production has a timeout of 6 minutes for the linter, but locally after 12 it was still going, taking a lot of CPU & memory.

https://mozilla.sentry.io/issues/4742214363/?project=6310819

**Comment by BlueGreenMagick** [comment]
Thank you for looking into it.

On my Macbook Air M1 with Node 20, it takes 203s to finish, which is still quite a lot. Profiling it shows that 95% of that time was spent on just reading the file to string, in `addons-scanner-utils.Xpi.getFileAsString()`. I suspect that it is because `getFileAsString()` builds the string by small chunks using `Buffer.concat([buf, chunk])`, and the repeated call is reallocating the buffer.

**Comment by diox** [comment]
Thanks for taking the time to investigate further, and sorry for the lack of reply, we totally missed your comment and the PR you submitted! We'll look into that right away, that seems promising.

**Comment by diox** [comment]
Side note: we have a hard limit on the size of individual files inside an add-on, which is currently at [`104857600` bytes once unzipped](https://github.com/mozilla/addons-server/blob/7c3146da1dbd602ae55959ef9e629b4c89fb292f/src/olympia/lib/settings_base.py#L1167). I would recommend splitting files to avoid hitting that in the future, even once we integrate your patch.

**Comment by BlueGreenMagick** [comment]
Confirmed that it was fixed. Thanks!

**Comment by ioanarusiczki** [comment]
I uploaded from dev hub the addon and it worked for me too with linter 6.31.0

https://addons-dev.allizom.org/en-US/firefox/addon/yomikiri_on_dev/
https://addons.allizom.org/en-US/firefox/addon/yomikiri_on-stage/
