### ISSUE TITLE
Very long delays when adding a new version

### ISSUE THREAD

**Issue by palant** [mozilla/addons#16]
Clicking "Add Version" on https://addons.mozilla.org/en-US/developers/addon/adblock-plus/versions#version-upload will very often time out. This is done automatically for our development builds and times out for at least 50% of the submissions lately. We get "HTTP Error 504: GATEWAY_TIMEOUT" back - the version is created but the file hasn't been added. Eventually the file is still added (the request is still being processed on the servers) but it takes very long. I just had this happen again with version 2.7.0.4112-beta, the file only appeared for this version after more than 20 minutes.

**Comment by andymckay** [comment]
We've got a lot of issues around this, duping this to mozilla/olympia#1244
