### ISSUE TITLE
Personas Plus - My Favorites menu doesn't always list favorites when signed in

### ISSUE THREAD

**Issue by derinb** [mozilla/addons#160]
[Original Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=920557) for this [Personas Plus](https://addons.mozilla.org/en-US/firefox/addon/personas-plus/) add-on ported here because old one is graveyard.

**Steps to reproduce:**

After signing in AMO, Personas Plus's My Favorites menu doesn't always list favorites.

**Actual results:**

> OK, so the problem is essentially that you have so many favorites that in most cases a gateway timeout occurs before the server finishes generating the response. I have a patch for Personas Plus to properly report that an error occurred rather than simply asking you to login. It might also be worth fixing this on AMO.

https://bugzilla.mozilla.org/show_bug.cgi?id=920557#c8

**Expected results:**

After signing in AMO, Personas Plus' My Favorites menu should list favorites.

Related Personas Plus [issue](https://github.com/mozilla/personas-plus/issues/22).

**Comment by diox** [comment]
@wagnerand is this still relevant?

**Comment by wagnerand** [comment]
@diox It might still exist, but Personas Plus is not affected anymore because it uses a whole different implementation now, so I close this for now.
