### ISSUE TITLE
Missing internationalization string for a language

### ISSUE THREAD

**Issue by mtrevisan** [mozilla/addons#161]
In the list at page https://addons.mozilla.org/en-US/firefox/language-tools/ , in the language column, the voice "Venetan dictionary (vec)" should be "Venetan" and "Vèneto". Same goes for the italian version ( https://addons.mozilla.org/it/firefox/language-tools/ ) that displays "Diŧionario de lengua vèneta - Dizionario di veneto (vec)" instead of "Venetan" and "Vèneto".

They tell me it can be an amo error. So I think this bug belongs here.

Thank you.
![image02](https://cloud.githubusercontent.com/assets/851903/16920179/f22a3a12-4d0c-11e6-8024-d045e44b3baf.png)

**Comment by wagnerand** [comment]
I changed the international name (first column). The local name comes from https://github.com/mozilla/django-product-details but I'm not sure how to add the locale to that. Maybe we can follow up with that later.
