### ISSUE TITLE
Add-on Mail Notifications Does not Work Anymore

### ISSUE THREAD

**Issue by derinb** [mozilla/addons#162]
For the last 2 weeks I do not get notification emails from Mozilla when my add-on update is reviewed by Mozilla editor. The mail that says "Your add-on has been fully reviewed by an editor" is not received by my account mail. I checked Spam folder and there is no trace there, too.

My account settings
    User Notifications
        ✓ an add-on developer thanks me for a contribution new
        ✓ an add-on developer replies to my review new
        ✓ new add-ons or Firefox features are available new
    Developer
        ✓ my add-on's compatibility is upgraded successfully new
        ✓ my sdk-based add-on is upgraded successfully new
        ✓ someone writes a review of my add-on new
        ✓ add-on contests or events are announced new
        ✓ my add-on's compatibility cannot be upgraded *new
        ✓ my sdk-based add-on cannot be upgraded *new
        ✓ my add-on is reviewed by an editor *new
       ✓  Mozilla needs to contact me about my individual add-on *new

I recently switched to new FxA login system from the old one, which might be the cause.

@jasonthomas Could you please look into this?

**Comment by jasonthomas** [comment]
On July 1st a spam message complaint was registered in our mail system from your email address. This caused your email address to be added to our email suppression list and any new messages were suppressed and not sent to you. I've gone ahead and removed your email address from the suppression list. Since this was a spam complaint you will receive a verification email from our mail provider to verify that you still want to receive email from our systems. You will need to follow the steps in the email before you receive any new emails. 

Let me know if you have any questions.

**Comment by derinb** [comment]
Thank you so much Jason and sorry for the trouble.

I am not sure what went wrong. I never flag Mozilla mails as Spam. Though a misclick might have happened.

Is it possible to provide feedback in Account Settings if the mail is in Spam List? Or is it possible to increase Spam Complaint threshold so that 1 time misclick does not create such an issue?

Other than that you can close the issue.

**Comment by andymckay** [comment]
We are thinking about showing all outbound messages in the developer hub, so developers can see all the messages there, even if they caught in a spam filter on the way. Closing this for now.

**Comment by derinb** [comment]
@jasonthomas Same issue again. Would you mind removing below email address from the list please?

barisderin at yahoo dot com

Thank you.

**Comment by jasonthomas** [comment]
@bqbn could you take a look?

**Comment by bqbn** [comment]
I just removed that email address from our suppression list.

@derinb our email provider sent you a verification email and your email address will not be removed from the suppression list until you click on the link in the verification email that they sent.

**Comment by derinb** [comment]
@bqbn @jasonthomas Thank you so much for your help and time. Sorry for the trouble.
