### ISSUE TITLE
The add-ons video is a bit old skool

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#1630]
Go to about:addons, click "watch the video" or "Learn more about add-ons".

A couple of things:
- It says "You can use personas", they got renamed to themes a while ago
- Two of the add-ons that it adds in "F1 by Mozilla Labs" and "Add to Amazon Wishlist" no longer exist

If we want to keep this video around, I bet we can find replacements for those add-ons and just update that.

**Comment by deadsquid** [comment]
So weird to continue to get all these bits from the past (that are closed) because they're being administratively moved around.

**Comment by jvillalobos** [comment]
Yup yup
