### ISSUE TITLE
[l10n] Untranslatable string on homepage

### ISSUE THREAD

**Issue by zelitomas** [mozilla/addons#165]
Hello,

there are some untranslatable strings in promo part of header on AMO homepage (highlighted on screenshot)

![Olympia l10n bug screenshot](http://skladobrazku.zelitomas.cf/olympial10nbug.png)

Could somebody please take a look at them?

Many thanks,
Tomáš Zelina

**Comment by devaneymoz** [comment]
How are they untranslatable? Is it that you can't find the strings to localize, or is it that the copy does not lend itself to a direct localization? If the latter, I would encourage localizers to use their best judgement in communicating the spirit of "Must-Have Media" ... which in this case could be "Photo & Video Add-ons" or "Media Tools" etc.

**Comment by muffinresearch** [comment]
Looks like the string is in the gettext files: https://github.com/mozilla/addons-server/blob/master/locale/templates/LC_MESSAGES/django.pot#L9997

**Comment by EnTeQuAk** [comment]
Actually, they are translatable since today. I forgot to run the extract after adding the new promo box. So this should be fixed now, if not please feel free to re-open anytime.
