### ISSUE TITLE
about:addons -> Get Add-ons hides 'See more add-ons!' below the viewport

### ISSUE THREAD

**Issue by smaug----** [mozilla/addons#166]
Earlier about:addons page had a way to search or at least go to AMO easily from the top of the page.
Now the 'See more add-ons!' button is at the bottom of the page[1] which meas that user easily
doesn't notice it since it requires scrolling.

[1] https://discovery.addons.mozilla.org/en-US/firefox/discovery/pane/50.0a1/Linux/normal

**Comment by andymckay** [comment]
This is covered here: https://bugzilla.mozilla.org/show_bug.cgi?id=1307386 and here mozilla/addons#159 

Marking as duplicate.
