### ISSUE TITLE
User Registration broken on addons.mozilla.org

### ISSUE THREAD

**Issue by jkerls** [mozilla/addons#167]
It appears to be impossible to register a new user on addons.mozilla.org

If you go to https://addons.mozilla.org/en-US/firefox/users/login and don't have an account, clicking either the "I don't have an account" link in the righthand sidebar or the "Register" link in the masthead should take you to https://addons.mozilla.org/en-US/firefox/users/register - however, this is immediately redirected back to the login page, making it impossible to actually create a new account.

I tried this on multiple browsers - Firefox, Chrome, and Edge, along with Mobile Firefox and Chrome, and all failed in the same way.

**Comment by diox** [comment]
Have you tried entering your email address on that page ? If you enter an email address that is not yet in the database it will proceed with registration.

**Comment by jkerls** [comment]
No, it does not. I did try that, and it did not work as a registration. I've tried it with two email addresses that have never been used on the site.

**Comment by muffinresearch** [comment]
@jkerls I've just tried this and although it might appear confusing, entering an email address on the login screen should take you to firefox accounts in order to create an account there. 

<img width="350" alt="user_login____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/17402340/b322b006-5a4a-11e6-88e4-b0fcd8b06679.png">

Followed by:

<img width="308" alt="create_a_firefox_account_to_continue_to_add-ons" src="https://cloud.githubusercontent.com/assets/1514/17403858/65dab86e-5a51-11e6-8fce-c1bee9b88443.png">

There's clearly a UX issue here but it does appear to work. If that's not happening can you show us what you're seeing?

**Comment by jkerls** [comment]
That is not what happens for me at all, but I see why. When submitting the email it makes the expected call to https://addons.mozilla.org/api/v3/accounts/source/?email=jkerls%40gmail.com and gets back a 304, so one of my prior attempts to create an account apparently added that address to whatever list is checked.

However, trying to recover the address to that account doesn't work - submitting that address on the 'forgot password' form sends a request to https://api.accounts.firefox.com/v1/password/forgot/send_code - and that returns an error 400, Unknown account.

Trying it with a different email address (jkerls+test@gmail.com) does work. So somehow my email address got logged as being associated with an account but it seems the account was never created.d

**Comment by mstriemer** [comment]
@jkerls it looks to me like that email address has an old password based account on AMO. Entering your email address into the form at https://addons.mozilla.org/en-US/firefox/users/login prompts me for a password. If you don't know the password you should try resetting it at https://addons.mozilla.org/en-US/firefox/users/pwreset. This form should still work and shouldn't be making any requests to https://api.accounts.firefox.com.

I managed to register a new account on AMO using an address that I know has not been used. The register link going to login is definitely confusing. I filed https://github.com/mozilla/addons/issues/180 to update the register page to make how it functions more clear.

**Comment by jkerls** [comment]
@mstriemer - that did indeed work, thanks. But the existing forgot password page should probably link back to that in some way to prevent other people with old accounts from getting lost in that black hole - none of the feedback provided on the forgot password page would take a user to the right place in that circumstance.

**Comment by mstriemer** [comment]
The link on the log in page goes to the Add-ons forgot password for me. It's possible you were on the Firefox Accounts site when you clicked the forgot password link.
