### ISSUE TITLE
Add link to report a bug somewhere visible in the site

### ISSUE THREAD

**Issue by sole** [mozilla/addons#168]
I have spent the last five minutes asking people and searching for where to file a bug because I got stuck on an "old addons accounts to Firefox Accounts" migration process and I wanted to report my neverending loop somewhere instead of giving up.

Except there's nowhere visible, or nowhere obvious for people who are frustrated as I am right now, to report a problem with the website.

Luckily I came to my senses and tried the obvious which is filing in Bugzilla. Which then redirected me to this repository. Which it could have happened from the beginning maybe so I would be happier 😜

**Comment by brampitoyo** [comment]
Sounds like we can have a link to “File a bug” on the footer of AMO, or at least on the footer of Developer Hub?

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48(Win 7 x64)
Postfix screenshot: 
![2016-08-25_0839](https://cloud.githubusercontent.com/assets/15685960/17958086/b237f862-6a9f-11e6-86fd-4adb26d8deba.png)

Obs: at click, page https://github.com/mozilla/addons/issues/new is opened.

**Comment by sole** [comment]
Thank you ❤️ 😄
