### ISSUE TITLE
Impossible to migrate "old" account to Firefox Account

### ISSUE THREAD

**Issue by sole** [mozilla/addons#169]
I'm stuck in a loop.

This is what I'm doing to try to migrate my account to Firefox Accounts:

1) Go to https://addons.mozilla.org/users/login
2) Login (with old account)
3) https://addons.mozilla.org/en-US/firefox/ shows a notice asking me to *Sign in now to transfer your account*
<img width="1086" alt="screen shot 2016-08-01 at 10 24 39" src="https://cloud.githubusercontent.com/assets/5609/17289571/35fff45a-57d2-11e6-9895-6c266424ca70.png">
4) Click on the *Sign in now to transfer your account* link which goes to https://addons.mozilla.org/en-US/firefox/users/login
5) This brings me to a Firefox accounts dialog to sign in. It suggests I sign in with my AMO email address which is not the same as my Firefox accounts address (it is sans the +amo bit)
<img width="390" alt="screen shot 2016-08-01 at 10 25 58" src="https://cloud.githubusercontent.com/assets/5609/17289638/7b39337e-57d2-11e6-8f01-b9b2f42345d2.png">
6) Since that is not my Firefox Accounts email I click on the "Sign in" link after the "Have an account with a different address?" link. This goes to https://accounts.firefox.com/oauth/signin
7) I try to sign in with my Firefox Account (this time it's the correct one) - I simply click on the big blue SIGN IN button
<img width="405" alt="screen shot 2016-08-01 at 10 28 01" src="https://cloud.githubusercontent.com/assets/5609/17289685/b3869406-57d2-11e6-88a2-b3a4d3ea7f1e.png">
8) We're back to the addons website
<img width="1107" alt="screen shot 2016-08-01 at 10 29 13" src="https://cloud.githubusercontent.com/assets/5609/17289716/dae4ca18-57d2-11e6-9bb5-756d87af440b.png">

It says my Firefox Account already exists on the website. The "need help?" link goes to support and doesn't help me at all.

There's that other disabled sort of faded out notice that says that "Addons is switching to Firefox accounts . Sign in to transfer your account" that is very annoying and confusing.

I keep reading and click the blue "Continue" button to see if something better happens.
9) We're back to STEP 5!!!! 😠 
<img width="390" alt="screen shot 2016-08-01 at 10 25 58" src="https://cloud.githubusercontent.com/assets/5609/17289638/7b39337e-57d2-11e6-8f01-b9b2f42345d2.png">
10) I repeat steps 6 and 7
11) BACK TO STEP 8 😡 
12) I am losing my cool, but I click on "Skip" at the bottom of the dialog and hope something, anything, can put an end to this agony
13) Aaaaaand we're back to 3

Repeat until you feel like throwing the computer through the window 😭

**Comment by diox** [comment]
This sounds like https://github.com/mozilla/addons-server/issues/3151 but it should have been fixed in production last Thursday. Any ideas, @mstriemer ?

**Comment by eviljeff** [comment]
You also have accounts with both [sole@](https://addons.mozilla.org/en-US/firefox/user/10110506/) and [sole+amo@](https://addons.mozilla.org/en-US/firefox/user/11357206/).

**Comment by eviljeff** [comment]
So you're trying to migrate the account with sole+amo@ to an FxA account of sole@, and AMO is trying to set the email to match the FxA account, and failing as there is already another account that is using sole@

**Comment by sole** [comment]
Perhaps the process needs to be able to "merge" accounts too? Or at least be more clear as to what do I actually have. I don't remember having created an account with Fx Accounts, perhaps this was accidentally created by me when trying to migrate it the first time (in which I also stumbled upon some loop and gave up)

**Comment by eviljeff** [comment]
the sole@ AMO account is really old, (created in 2013, last used in 2014) so it's not connected with FxA.  If you don't want it I can get rid of it, which should then allow you to exit the labyrinth.

**Comment by sole** [comment]
I might have created it for the Firefox Marketplace? And then there is also a Firefox add-on I published. At this point I'm not sure which account has it, probably sole.
But I don't understand why it is confusing a 'sole' account (created with sole+amo@ email) with a Firefox account that uses sole@

**Comment by eviljeff** [comment]
It could have been for Marketplace, during the period where they shared the same database.

By choosing to migrate your AMO account that now uses the email `sole+amo@` to an FxA account that uses `sole@` you will be changing your AMO account to use the email address `sole@` instead.  (Which can't happen, because there exists another user account - the one from 2013 - that already uses `sole@`).

Option A is use `sole@` for AMO - I'll delete the older account, and you can go through the migration flow above
Option B is continue to use `sole+amo@`, in which case you'll need to create a new FxA account, rather than linking it to your existing one.

**Comment by Luckz** [comment]
At least for non-Mozilla emails :> there's also self-service deletion via https://addons.mozilla.org/en-US/firefox/users/edit (login to AMO via Firefox account that you want nuked on AMO, then go there to delete it with the [cute button at the bottom](https://addons.mozilla.org/en-US/firefox/users/delete))

**Comment by mstriemer** [comment]
I added this error message to the [support article](https://support.mozilla.org/en-US/kb/access-your-add-ons-firefox-accounts) that we link to.

It looks like there is a solution for you here so I'm going to close this. Sorry for the clearly sub-optimal experience, hopefully the updated documentation helps in the future.
