### ISSUE TITLE
Describing newly submitted add-on is not possible

### ISSUE THREAD

**Issue by luckyrat** [mozilla/addons#170]
I've just tried to submit a new add-on and at step 3 I am asked to describe it but the UI is missing so I can't proceed.

![addonbug](https://cloud.githubusercontent.com/assets/1211375/17300469/6d35226e-580a-11e6-9794-b4c4c5fb8f4a.PNG)

It's a WebExtensions XPI which works fine locally in FF49 (and Chrome). It uploaded and passed validation without incident and I ticked the option to upload/sign only rather than host on AMO. I'm unable to return to any earlier stages to experiment with alternative options and narrow down the cause of the bug further.

**Comment by eviljeff** [comment]
can you attach/link to the add-on?  A minimal zip is fine - I guess something is choking on the manifest.

**Comment by luckyrat** [comment]
Yeah, here it is (extension changed for GitHub compatibility):
[YouTrack-enhancer-1.1.0-firefox.zip](https://github.com/mozilla/addons/files/401130/YouTrack-enhancer-1.1.0-firefox.zip)

**Comment by eviljeff** [comment]
It's likely connected to the localisation in the manifest.
@EnTeQuAk has been looking at other webext issues so assigning him

**Comment by eviljeff** [comment]
@luckyrat can you try changing the locale to 'en-US' or 'en-GB', both in the manifest and the folder name?

**Comment by luckyrat** [comment]
I tried but am unable to add it as a new addon because I now get the error message "Duplicate add-on ID found". I've attached the updated version I attempted to upload.

[YouTrack-enhancer-1.1.0-firefox-en-US.zip](https://github.com/mozilla/addons/files/406812/YouTrack-enhancer-1.1.0-firefox-en-US.zip)

**Comment by eviljeff** [comment]
if you look in your 'my addons' the broken submission should be there for you to delete.

**Comment by luckyrat** [comment]
Sorry, it looks like I forgot to provide an update here. I did manage to delete the addon and when I uploaded with the en-US locale it worked fine.

I'll actually have a new version ready to upload in the next day or two. It looks like you might be ready to deploy a potential fix at the end of the week. Will it be helpful for testing this issue if wait until the start of next week?

**Comment by EnTeQuAk** [comment]
I'm working on the fix right now and hope to finish it asap for the deploy on Thursday. Since you already attached your add-on to this issue I think we're good, that already helps a lot with testing. So go ahead :)
