### ISSUE TITLE
Disclose on addons.mozilla.org if an add-on enables paid whitelisting by default

### ISSUE THREAD

**Issue by dmarti** [mozilla/addons#171]
In a case where an add-on enables paid whitelisting of user tracking in its default configuration, please show a message explaining this practice on the relevant addons.mozilla.com page(s).

For example, AdBlock Plus has an "Acceptable Ads" program that does not appear to "provide users with transparency and meaningful controls over the needs it is attempting to address." ([Mozilla "Proposed Principles for Content Blocking"](https://blog.mozilla.org/blog/2015/10/07/proposed-principles-for-content-blocking/)) The paid whitelisting program is enabled by default and described only as "allow some non-intrusive advertising" in the add-on UI.

The Newspaper Association of America has called paid whitelisting a "deceptive trade practice" in a [complaint to the US Federal Trade Commission](http://www.naa.org/~/media/NAACorp/Public%20Files/PublicPolicy/GovernmentAffairs/NAA%20FTC%20Complaint_5-25-16.pdf).  Whether or not users choose to participate in paid whitelisting should be a deliberate decision of the user, not a hidden feature.

**Comment by jvillalobos** [comment]
We require transparency as a general policy, and we believe AdBlock Plus meets that bar. The description explains what the feature is, and there's a Read More link that expands on it. Whether users agree with the motivations behind that feature or not is up to them to decide. I don't think we need any specific policy for this, which would be very difficult to enforce anyway.

/cc @wagnerand @kewisch @eviljeff for other input.

**Comment by wagnerand** [comment]
I agree. That policy would be very specific, maybe even to one add-on. I haven't seen other add-ons (except ABP clones) this would apply to.

**Comment by jvillalobos** [comment]
Closing, but feel free to continue the discussion.

**Comment by dmarti** [comment]
I understand that this might not be the best place to cover this issue.

There are still problems with how Mozilla presents information on AdBlock Plus.

 * paid whitelisting is an unusual practice that can conflict with users' principles.

 * Mozilla facilitates, and sometimes appears to recommend, an add-on that does paid whitelisting.

![screenshot from 2016-08-09 09-55-21](https://cloud.githubusercontent.com/assets/48007/17702855/7ff37920-6384-11e6-9cbd-943a9da1cab8.png)

In the above screenshot from a fresh Firefox install, AdBlock Plus is described as "amazing" and it is possible to install it without ever being informed about the paid whitelisting that is turned on by default.

Mozilla may have to revisit this issue if the FTC takes action on the NAA letter and paid whitelisting is determined to be a "deceptive business practice".

**Comment by dmarti** [comment]
Another screenshot from a recent Nightly.

![screenshot from 2016-09-15 12-28-48](https://cloud.githubusercontent.com/assets/48007/18570399/655956f6-7b5e-11e6-9234-a1ffbf388c91.png)

 * ABP is "recommended"

 * The default install has "Acceptable Ads" on, and EasyPrivacy off.

 * Description says that Adblock Plus "can" mitigate tracking and malware.

If you do install, in order to get the protection claimed, you have to both add the "EasyPrivacy" filter list subscription, and turn off "Acceptable Ads" with a confusingly named "Allow some non-intrusive advertising" checkbox.  If "Acceptable Ads" is left on, it overrides the EasyPrivacy subscription, which is not clear from the UI.

**Comment by dmarti** [comment]
cc @deadsquid

**Comment by dmarti** [comment]
The EFF has recently posted on this issue:

> The Acceptable Ads whitelist allows numerous tracking domains. Content blockers like Adblock Plus and Adblock function based on both whitelists and blacklists. When there is a conflict, the whitelist wins. This means that even though EasyPrivacy is intentionally installed and Acceptable Ads is enabled by default, whitelisted domains will not be blocked from tracking the user. With more than 10,000 domains on the Acceptable Ads whitelist, that’s a lot of tracking....EasyPrivacy's protection is only effective if users disable the default Acceptable Ads whitelist, but the blockers offer no warning regarding the incompatibility of the two lists. This is despite the fact that tracker blocking was offered by ABP as an explicit option during installation until recently, and Adblock offers EasyPrivacy in the list of filters available for activation in its user settings. Because the Acceptable Ads whitelist is enabled by default, some EasyPrivacy users are likely unaware that Acceptable Ads is even enabled, never mind undermining their preferences. As a consequence, we believe millions of users have been unwittingly exposed to tracking.

Dedicated Panopticlick update to deal with it: https://www.eff.org/deeplinks/2017/11/panopticlick-30
