### ISSUE TITLE
[Bug]: Mini player pops up, even though deactivated in the preferences

### ISSUE THREAD

**Issue by brsa** [mozilla/addons#1718]
### What happened?

When going back in the browser (with back key or clicking the back button in the URL bar), I sometimes get a mini player, even though I deactivated that option in the preferences.

> [ ] Launch a mini player when scrolling down to read comments

Firefox 124.0
Ubuntu 20.04.6 LTS
Enhancer 2.0.123

### What did you expect to happen?

I don't want the mini player. And I want the software to follow my settings.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-9)

**Comment by eviljeff** [comment]
Sorry, this doesn't appear to be related to add-ons.  You can find support on Firefox at https://support.mozilla.org/
