### ISSUE TITLE
[Task]: Allow delay-rejections for unlisted versions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#1727]
### Description

In #21783 we decided not to enable delay-rejections for unlisted versions in general (I think some cases were already covered). However, since reviewers now make use of instant-rejections for issues that we'd normally relay-reject for, some rectifying paths for developers are prevented. For instance, we instant-reject for missing source code, and a rejected version cannot have the source code field changed.

Therefore, we should generally enable unlisted delay-rejections.

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] An unlisted approved version should be delay-rejectable. The conditions for delay-rejections on listed versions should probably the replicated to unlisted versions (tbc)
  ```
### STR
1. Submit an unlisted version
2. Let it auto-approve
3. Try to delay-reject the version

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label and added an assignee.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-11)

**Comment by ioanarusiczki** [comment]
@diox 

I could delay reject unlisted versions , they're displayed in [Pending Rejection](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/pending_rejection)

When a new version is submitted while the previous are pending rejection ,[ listed](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630314) have a "Pending Rejection on review of new version" in Add-on History while the [unlisted ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/630315) display another message "Scheduled for rejection in 2 days, 23 hours" 

I hope that's fine.
