### ISSUE TITLE
[Bug]: Email sent to other reporters should not mention "your appeal"

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1728]
### What happened?

Followup for https://github.com/mozilla/addons-server/issues/21811#issuecomment-1999924292
 
1. An extension is reported for addon policies 
2. Reviewer decides not to take content down 
3. Reporter appeals 
4. Now the appeal is displayed in DSA Section, the reviewer checks it and decides to delay reject the version
5. While the version is pending rejection it's being reported for add-on policies by other reporters and an email is sent to them 

it says "after reviewing your appeal" 

![email sent to other reporters](https://github.com/mozilla/addons/assets/33448286/cff0718c-ada1-43ff-a33f-dc60874079fa)

### What did you expect to happen?

This email 

![reporter mail correct](https://github.com/mozilla/addons/assets/33448286/c4e500c0-425f-4ff3-b124-7c276bd01b97)

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-12)

**Comment by eviljeff** [comment]
bug here is we shouldn't be doing ` is_appeal=cinder_job.is_appeal` for `notify_reporters` - a new report should always be emailed as if there is no appeal (because as far as the reporter is concerned, it's not an appeal.

Note there may be variants of this bug elsewhere - we didn't think new abuse reports would be combined into an outstanding appeal job.

**Comment by eviljeff** [comment]
After investigating it further, this exact scenario can no longer happen.  Post #22111 we close the cinder job immediately, so further reports would create a new, independent cinder job.  

There are other potential edge cases with new abuse reports being attached to an appeal job though, so I'm going to file a separate issue about that.

**Comment by ioanarusiczki** [comment]
I wanted to test this but I see there's a problem for step 2. which was done with "Clear needs human review" from the reviews pages. I cannot select a version to continue , I filed https://github.com/mozilla/addons/issues/1749 because it seems to be a regression.

**Comment by ioanarusiczki** [comment]
yeap ...nope... switches were not active, re-testing

**Comment by ioanarusiczki** [comment]
I tried this again on dev , attaching the appeal + delay reject, I also tried with a report + delay rejection but I am no longer getting the emails if I send new reports while the versions are pending rejection.

**Comment by eviljeff** [comment]
> I tried this again on dev , attaching the appeal + delay reject, I also tried with a report + delay rejection but I am no longer getting the emails if I send new reports while the versions are pending rejection.

Ah, that's a bug... which may not be fixable.

**Comment by ioanarusiczki** [comment]
There's a different behavior now so while testing https://github.com/mozilla/addons/issues/1741 I tried the delay rejections again

At step 4. -> while appeal is waiting to be resolved , new reports sent are gathered under the appeal from the dsa section on  reviewers pages.

After a delay rejection is set, emails are sent to the first reporter:

![the first reporter](https://github.com/mozilla/addons/assets/33448286/6672489c-52dd-4a10-94f2-cd4db2fd0bc2)

Other reporters get a different email: 

![different email](https://github.com/mozilla/addons/assets/33448286/6ca8d683-a564-4eb9-a40e-eaf3ac421eb7)
