### ISSUE TITLE
Cannot Upload New Version of Add-On Built With WebExtensions

### ISSUE THREAD

**Issue by lisaclee** [mozilla/addons#173]
I have an existing add-on that I developed a few years ago using the SDK (package.json, etc.). I rewrote the add-on using WebExtensions (manifest.json, etc.). I tested the new version successfully and everything worked fine. When I went to AMO to upload the new version, 'All Platforms' was checked by default, and I could check and uncheck that box or the boxes next to any of the other platforms (Windows, Linux, Mac, Android, etc.). I selected a file to upload and eventually was shown a message informing me that the file was uploaded and validated successfully with 0 errors. However, all of the Platform checkboxes got automatically unchecked after the file upload, and furthermore, they were all disabled. If I click the 'Add Version' button on that form to continue, I just get an error message telling me 'Need at least one platform.' Since I can't check any of the Platform checkboxes because they are now disabled, I can't continue. As a test, I went ahead and selected my older version's file to upload (the version that was developed using the SDK), and I didn't experience the unchecking and disabling of the Platform checkboxes.
![image](https://cloud.githubusercontent.com/assets/4823045/17311629/98d578c8-5801-11e6-983f-cfbc956804c3.png)
![image](https://cloud.githubusercontent.com/assets/4823045/17311643/aeb53c5a-5801-11e6-88f7-5257abdaa5ae.png)
![image](https://cloud.githubusercontent.com/assets/4823045/17311664/d0fa8518-5801-11e6-8931-875183ad9e32.png)

**Comment by lisaclee** [comment]
[TFFSiteQualityFF.zip](https://github.com/mozilla/addons/files/397399/TFFSiteQualityFF.zip)

**Comment by lisaclee** [comment]
Some additional info:  I removed the 'applications' key from the manifest.json file and was able to successfully upload the package without experiencing the unchecking/disabling of the Platform checkboxes. Since FF48 was just released today, this will work as a workaround, seeing as how FF48 no longer requires the applications key in the manifest.json file anyway.

**Comment by diox** [comment]
Thanks for your report. This platform selector has been given us lots of headaches :( We'll be looking into it.

`applications` property that was used before for reference:
```
"applications": {
		"gecko": {
			"id": "@tffsitequalityff",
			"strict_min_version": "38.0a1"
		}
	},
```

**Comment by EnTeQuAk** [comment]
Hmm, if `strict_min_version` was 38.0a1 the greyed out platforms are relatively valid since we don't support WebExtensions for versions earlier than 42.


But I assume a more verbose error message related to the version should fix any confusion. Any more ideas?

**Comment by lisaclee** [comment]
Hi!  That sounds like a good idea about the more verbose error message, and thanks so much for getting back to me!  I’m all good since I removed the applications property (with the strict_min_version entry) from my manifest.json file.

Thanks again and have a great day!
Lisa
