### ISSUE TITLE
Updates to addons issue template

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#1730]
### Description
We should keep this task as a tracker for updates we need to make to the addons repository issue template.

### Acceptance Criteria
```[tasklist]
- [x] Empty task lists are not render-able by github. Add a placeholder task
- [x] Update task template to remove the "(contributors only)" part and say Task/Feature request
- [x] Merge task templates to be non repo specific issues
- [x] Add check reminding to include repo:??? label to Tasks and Bugs if it's known to the reporter
- [x] Remove duplicate acceptance criteria header, it's getting in the way of rendering it properly
```

### Checks
* [x] If the issue is ready to work on, I have removed the "needs:info" label and added an assignee.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-20)

**Comment by eviljeff** [comment]
Done  - I just committed directly as I couldn't see what the form would look like before merging
