### ISSUE TITLE
[Task]: Usability improvements to suppressed email status page.

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#1734]
### Description

As a user I want to see more detailed and useful status information about my pending email verification so that I can understand if I am still waiting for the email from socketlabs or if something has gone wrong and I need to do something.

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] increase timeout window to 1 minute to allow socketlabs more time to process the queue
  - [ ] remove verification code snippet filter from email history table. Show previous recent attempts with a different code in case user tries again
  - [ ] Improve messaging to indicate the actual status, and what the user should expect
  - [ ] Add a refresh results button that manually refreshes the page. In case the verification timesout the user can still check if new results are in.
  ```

#### Setup

- Create a token at socketlabs (dev) <https://portal.socketlabs.com/2301/config/key-manager>
- Save the token in local_settings as `SOCKET_LABS_TOKEN`
- Save the dev server id at `SOCKET_LABS_SERVER_ID=2301`

#### Scenario 1: Create a suppressed email

There are 2 ways to create a suppressed email record.

**Via Socketlabs UI:**

- Go to the socketlabs suppression list <https://portal.socketlabs.com/2301/suppression>
- Add the email you are going to use to login to devhub to the suppression list "Add Entry"
- Run the command to sync the suppression list on your environment

```bash
./manage.py sync_suppressed_emails
```

**Via Django shell:**

```python
SuppressedEmails.objects.create(email=<your-email>)
```

You can verify your record via the django shell

```python
SuppressedEmails.objects.filter(email=<your-email>).count()
```

#### Scenario 2: Request a verification code
- **Given:** You have a suppressed email
- **When:** You request the verify-email page `/en-US/developers/verify-email` on your environment (see below)

<kbd>
<img width="1134" alt="image" src="https://github.com/mozilla/addons/assets/19595165/a97c1d56-58ce-4a2b-bc35-33477710695c">
</kbd>

- **And:** You click the "verify email" button (see above)
- **Then:** You are redirected to the same page with a pending verification status message
- **And:** If you have no email history in the last 2 days, you see an empty table message (see below)

<kbd>
<img width="1128" alt="image" src="https://github.com/mozilla/addons/assets/19595165/f722662f-6f3e-473a-84c0-df8113c423ed">
</kbd>

- **Or:** If you have email history in the last 2 days, you see the records in the table (see below)

<kbd>
<img width="1155" alt="image" src="https://github.com/mozilla/addons/assets/19595165/6232243a-f6d2-4227-b94d-30138d8e0f2f">
</kbd>

#### Scenario 3: Timeout window increased to 1 minute

- **Given:** You have a suppressed email
- **And:** You have no pending email verification
- **When:** You request a verification code (see scenario 2)
- **Then:** The page should automatically refresh every 10 seconds for 1 minute (previously was only 30 seconds)

#### Scenario 4: Status text is explicit

- **Given:** You have a suppressed email
- **And:** You have no pending email verification
- **And:** You have requested a verification code (see scenario 2)
- **And** Socketlabs does not process your email in the timeout
- **When:** You visit the verify email page
- **Then:** The text explaining what to do and what to expect is more clear and direct. (see screenshot below)

<kbd>
<img width="1143" alt="image" src="https://github.com/mozilla/addons/assets/19595165/5dd5dbe5-d070-40cd-8ec0-a939a938625d">
</kbd>

#### Scenario 5: Refresh results

- **Given:** You have a suppressed email
- **And:** You have no pending email verification
- **And:** You [requested a verification code](#request-a-verification-code)
- **And:**: There are email history records available for the user
- **And:**: You manually add a new email record. either by:
  - overriding the socketlabs response
  - by manually sending a socketlabs email via the socketlabs UI
- **When:** You click the "Refresh results" link
- **Then:** The new record is also displayed in the email table (see screenshots)

https://github.com/mozilla/addons/assets/19595165/206e1267-9460-43c6-909e-35d72d643b06

> Note: You can also see this behavior if you request multiple verifications in parallel, as each new email will be added to the socketlabs history

> Note: If you are verifying on a local environment, emails sent via addons-server will not be available via socketlabs api. You will have to manually override the response

#### Scenario 6: Support email LINK

- **Given:** You have a suppressed email
- **And:** You have no pending email verification
- **And:** You [requested a verification code](#request-a-verification-code)
- **And:** Your email verification status is one of:
  - **email_suppressed**: suppression with no verification
  - **verification_expired**: verification that is older than 30 days
  - **verification_timedout**: verification that is older than 1 minute
  - **confirmation_invalid**: invalid `code` in the url.
- **When:** You navigate to the email verification page
- **Then:** You should see the email support link above the button to verify or retry (see below)

<kbd>
<img width="623" alt="image" src="https://github.com/mozilla/addons/assets/19595165/927da3d4-0ce5-47b1-8d04-58b355601156">
</kbd>

- **When:** You click on the link
- **Then:** Your email client should open with prefilled subject/body/to fields (see below)

<kbd>
<img width="867" alt="image" src="https://github.com/mozilla/addons/assets/19595165/1babb38b-e03e-4fff-ad9a-b25b3339f55c">
</kbd>

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label and added an assignee.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-36)

**Comment by diox** [comment]
To test this locally, you can steal `EMAIL_URL` from dev settings (ssh there, launch a django shell, copy the dict you get when you type `settings.EMAIL_URL`) and stick that in your `local_settings.py` file. Then you can add the relevant users to a `Group` with `name='Force Send Mail'` and `rules='What:Ever` (just need `rules` to be set to something valid for the group to work) to send actual emails for these users.
