### ISSUE TITLE
[Task]: Expose in Cinder whether or not an add-on is considered "Notable"

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1738]
### Description

As a Cinder moderator, I want to know whether or not an add-on is considered Notable (part of the "Notable" promoted group) when looking at a job about that add-on in Cinder.

Currently we expose add-ons with a Recommended/By Firefox promoted badge in Cinder through the `promoted_badge` field. It's directly exposed in Cinder on the relevant entity page:
![Screenshot 2024-03-29 at 11-06-13 Queues Cinder](https://github.com/mozilla/addons-server/assets/187006/6cce73bd-c769-4c0e-8ad4-17bffe66819f)

However, we are not currently exposing anything for add-ons in the Notable promoted group, as these don't get a badge on AMO. This task is about plugging that gap.

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] An add-on that is part of the "Notable" promoted group should be exposed as such in Cinder
  ```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label and added an assignee.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-42)

**Comment by ioanarusiczki** [comment]
Looking at By Firefox or Verified it's the same, the badge is displayed only in the "new" field. Only recommended is present in the new and the old field. 

This is a Notable: 

![notable on stage](https://github.com/mozilla/addons/assets/33448286/bedc576e-2080-4e0d-9f92-bd93049527a8)
