### ISSUE TITLE
[Bug]: Cinder emails relating to unlisted versions, or non-public add-ons, should reference devhub urls rather than public urls

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#1739]
### What happened?

Cinder emails currently assume all add-ons are/were public, and all versions are/were publicly available and distributed via AMO.  This isn't true - add-ons have an unlisted channel in addition to the listed channel, and those unlisted versions are not available for public download from AMO - developers have to download them from devhub and distribute the files themselves.  Similarly, if an add-on only has unlisted versions it won't have a public listing page.

### What did you expect to happen?

Emails about unlisted versions and non-public add-ons include links to devhub rather than the listing page.  The wording should probably be tweaked too.  

Note for disabling add-ons we'll have take care to differentiate non-public because all the versions were unlisted, and non-public because we just disabled it in the action.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-5)

**Comment by ioanarusiczki** [comment]
Testing in progress for this one.

**Comment by ioanarusiczki** [comment]
Please take a look at the cases below.  I suspect the wrong cases where I circled with red ->

Reporter's email when it is notified that content won't be taken down 

![unlisted - reporter email](https://github.com/mozilla/addons/assets/33448286/940100c2-41f7-4651-aa9a-450174907e0a)

Final email to the reporter when it's decided that the initial decision was correct 

![unlisted - final email sent to reporter](https://github.com/mozilla/addons/assets/33448286/a4e47af9-cbac-4961-8538-222cca4ba25f)

Email sent to the reporter about initial decision being incorrect 

![email to reporter after changing decision](https://github.com/mozilla/addons/assets/33448286/8f5adfc6-d38e-439e-88a6-191dfe6de3d5)

Reporter e-mail when content is removed 

![reporter](https://github.com/mozilla/addons/assets/33448286/ce513bcc-d3c5-4774-8d44-0b6c37330f6e)

Author's email when content is rejected 

![authoremailwhenrejected](https://github.com/mozilla/addons/assets/33448286/480de028-a4e7-4fe4-b442-d32b30fa2942)

Author's email when content is disabled - here I don't see versions page from dev hub

![forcedisableauthoremail](https://github.com/mozilla/addons/assets/33448286/3e977163-051d-4540-bc4c-d7f8deb5d01e)

Author's email when content is disabled - not on the back of a report 

![disabledwithoutareport](https://github.com/mozilla/addons/assets/33448286/73a78cff-231d-418a-90ca-2d1d579adc82)


Content is reinstated after a version is rejected with a new version submitted and approved 

![finalemailwithreject](https://github.com/mozilla/addons/assets/33448286/fda348b3-9377-4f34-bb03-d8e7fa1eea0c)

Content is reinstated with force enable 

![force-enabled for author's appeal](https://github.com/mozilla/addons/assets/33448286/d37d937d-5e32-42d5-8af0-806488ff3173)

Final email sent to author when decision is to keep content disabled does not mention the name or an url for the extension 

![finalemailfromCinder](https://github.com/mozilla/addons/assets/33448286/8b506e79-a30d-49b7-be54-f798c5940196)

**Comment by ioanarusiczki** [comment]
There might be a problem for unlisted so I filed  https://github.com/mozilla/addons/issues/1763

**Comment by eviljeff** [comment]
> **later edit** emails sent to the reporter should be good because they may not have access to dev hub so only author emails have some issues at disable/enable. I'll file followups.

Can you clarify what isn't as expected now, because it's a long comment.

One thing I noticed was the urls weren't absolute - they didn't start https:// and contain the site url so they can't be clicked on by the recipient.

**Comment by ioanarusiczki** [comment]
Please look over the first 2 images from the [long comment ](https://github.com/mozilla/addons/issues/1739#issuecomment-2069693434) and tell me what you think. IMO they should be fine. 

Then if I remember well, the last image from my long comment with "will not reinstate your Extension" is the same for listed versions meaning the name of the extension is not provided, I think that should be alright too. 

> One thing I noticed was the urls weren't absolute - they didn't start https:// and contain the site url so they can't be clicked on by the recipient.

Yeah, I've noticed that for https://github.com/mozilla/addons-server/issues/22125#issuecomment-2060638854 too, filed https://github.com/mozilla/addons/issues/1764

Also filed https://github.com/mozilla/addons/issues/1765 and https://github.com/mozilla/addons/issues/1766

*I'm still wondering about an image (the 6th actually from above) because I could not reproduce it today 🤔

**Comment by ioanarusiczki** [comment]
When an unlisted version shows up in Cinder and disabled from there the email sent won't have a dev hub url 

Yet, if https://github.com/mozilla/addons/issues/1763 is valid, then this scenario should not exist. 

![unlisted disabled with Cinder](https://github.com/mozilla/addons/assets/33448286/fb9b7bea-1d89-4a10-a287-d52b6b4edbe4)
