### ISSUE TITLE
[Bug]: If an icon was uploaded before 2018 it will be missing after force-disable/force-restore

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1742]
### What happened?

Some add-ons on AMO are missing icons. This is not reproducible for everyone as the CDN still has the missing icons in cache, but they are definitely missing from the origin.

### What did you expect to happen?

The following URLs should not 404. **When checking, include a unique query string in each URL to bypass CDN caching**.
- Addon 271830: https://addons.mozilla.org/user-media/addon_icons/271/271830-64.png
- Addon 823490: https://addons.mozilla.org/user-media/addon_icons/823/823490-64.png
- Addon 805933: https://addons.mozilla.org/user-media/addon_icons/805/805933-64.png
- Addon 583250: https://addons.mozilla.org/user-media/addon_icons/583/583250-64.png
- Addon 790974: https://addons.mozilla.org/user-media/addon_icons/790/790974-64.png
- Addon 3006: https://addons.mozilla.org/user-media/addon_icons/3/3006-64.png

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-1)

**Comment by diox** [comment]
This is most likely because those add-ons were force-disabled and then re-enabled recently. Icons (amongst other content) should be deleted when the add-on is force-disabled, then restored from backup storage when force-enabled. It looks like this failed for these add-ons, despite working for others.

**Comment by diox** [comment]
Looks like all the icons we failed to restore were from add-ons that either had en empty `icon_hash` or an `icon_hash` set to `"mcrushed"` (a fake initial value we set way back in the day for a bunch of icons when we added icon hashes). This might be a coincidence but worth investigating.

**Comment by diox** [comment]
This will go to prod in the next milestone, not today.

QA:
- Submit an add-on with an icon
- Copy the URL of the icon (i.e. https://addons-dev.allizom.org/user-media/addon_icons/616/616840-64.png?modified=a48339fb)
- Force disable that add-on
- Make sure that icon URL doesn't work anymore if you change the query string part
- Force re-enable that add-on
- Make sure that icon URL works again if you change the query string part and if you use the original

**Comment by alexandruschek** [comment]
Hello, 

I've tested this on dev:
After force disabling an addon, the url for the icon with the changed query part no longer works:
<img width="1411" alt="image" src="https://github.com/mozilla/addons/assets/139126091/c737a0cb-32d6-403d-b2a5-1c235d618b36">
After force enabling and changing the query part of the icon url, the icon can be seen again:
<img width="1411" alt="image" src="https://github.com/mozilla/addons/assets/139126091/db55418c-5e53-4cd0-8ad6-a34fbf6796a5">

All looks good and works as expected on dev, marking this as verified fix

Thank you!
