### ISSUE TITLE
[Task]: Make creator names clickable links to direct to creator profile

### ISSUE THREAD

**Issue by D4n2021** [mozilla/addons#1743]
### Description

On collections (example: https://addons.mozilla.org/en-US/firefox/collections/12401225/Most-useful-addons/), currently, users cannot click on the name of the Creator on the left side of the screen. Please make the Creator names clickable and open the Creator's profile (example in this case: https://addons.mozilla.org/en-US/firefox/user/12401225/) in either a new tab or the same tab.

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-2)

**Comment by eviljeff** [comment]
We're in the process of considering the future of the collections feature and how it's linked to the rest of the addons.mozilla.org website.

**Comment by smayer97** [comment]
> We're in the process of considering the future of the collections feature and how it's linked to the rest of the addons.mozilla.org website.

Mozilla has effectively gutted the Collections feature by removing key features used to differentiate Firefox from other browsers. Removing those key features (I have several posts highlighting the missing pieces), has made it very difficult to take effective advantage of collections to help support other users within my circle of influence. It has been short-sighted to think that it is only used by superusers ignoring the fact that these superusers support many other users in the process.
