### ISSUE TITLE
[Bug]: Emails are not sent with the force send applied

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons#1748]
### What happened?

Emails are not sent with the force send applied

Emails do not get sent to the email adresses

### What did you expect to happen?

Emails to get sent to the account with force send applied

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-9)

**Comment by alexandruschek** [comment]
Email address used: aschek@mozilla.com

**Comment by diox** [comment]
Could you give more information? What are you calling "force send", what environment are you seeing this on ?

**Comment by diox** [comment]
So if I understand this correctly, it started failing on dev yesterday, and on stage today, only for mozilla.com addresses? And it's still failing on dev now?

**Comment by ioanarusiczki** [comment]
No, it started failing for gmail addressed this week. Can't tell exactly when it started failing for mozilla, was before that.

**Comment by diox** [comment]
Could you clarify when you started noticing the failure:
- on dev, for mozilla.com adresses
- on dev, for gmail.com addresses
- on stage, for mozilla.com addresses
- on stage, for gmail.com addresses

**Comment by ioanarusiczki** [comment]
> on dev, for mozilla.com adresses

can't tell, sometime after https://github.com/mozilla/addons-server/issues/21790, it was working then, btw I get emails now on irusiczki@mozilla.com

> on dev, for gmail.com addresses

April 16 for an address, April 12 for another

> on stage, for mozilla.com addresses

can't tell because I don't have mozilla addresses here 

> on stage, for gmail.com addresses

last entry 16th

**Comment by diox** [comment]
In https://github.com/mozilla/addons/issues/1447 @alexandruschek successfully received a message for a gmail address in stage though ?

**Comment by diox** [comment]
I've tried today and couldn't reproduce on dev. Received an email on both my personal and my mozilla.com addresses.

**Comment by alexandruschek** [comment]
I can confirm I also get emails on my mozilla address. As said in this issue as well: https://github.com/mozilla/addons/issues/1447
