### ISSUE TITLE
[Bug]: when version is automatically rejected the reason in version history is incorrect

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1754]
### What happened?

1. Set a delay rejection and wait for it to expire so that the addon is automatically rejected 
2. Observe the version history 

### What did you expect to happen?

Rejected: Automatic rejection after grace period ended. 

but instead it's the previous reason 

before: 

![before on stage](https://github.com/mozilla/addons/assets/33448286/7418d071-4070-4d96-a815-9bcfed228413)

now: 

![now](https://github.com/mozilla/addons/assets/33448286/9bd059f1-c4ba-4f47-b42d-d6369c594d42)

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-15)

**Comment by eviljeff** [comment]
That's expected.  The review history contains what we send to the developer; previously we didn't notify the developer on the final reject, so included some generic text for the log entry.
