### ISSUE TITLE
[Bug]: After force enable extensions/themes should be cleared from Queues

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1758]
### What happened?
str from https://github.com/mozilla/addons/issues/9502 or https://github.com/mozilla/addons/issues/9501 
Also:

1. Force disable an addon/theme
1. Send an appeal 
1. Force-enable and attach the appeal
1. Observe the Manual Review Queue or Updated queue

### What did you expect to happen?
Extensions/themes should no longer be in the queues 

Examples https://reviewers.addons.allizom.org/en-US/reviewers/queue/theme_updates
https://reviewers.addons.allizom.org/en-US/reviewers/review/1025861

### Is there an existing issue for this?
* [x] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-43)

**Comment by eviljeff** [comment]
We need to clear the needs-human-review flag (specifically for the appeal) for a force-enable.

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons/issues/14872 resolved this, as far as I can tell.  Marking as fixed; QA to verify.
