### ISSUE TITLE
[Bug]: Send correct email for keeping content disabled

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1760]
Followup https://github.com/mozilla/addons/issues/9514

Addon is rejected/disabled after being reviewed 
Developer sends an appeal
Decision is to keep content disabled , rev tool action is "clear needs human review" + Appeal checked 

Email sent is: 

![email3](https://github.com/mozilla/addons/assets/33448286/52579123-8b35-49ce-9c53-ab8d0b653315)

### What did you expect to happen?
Correct email sent about previous decision being correct

### Is there an existing issue for this?
* [x] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-45)

**Comment by eviljeff** [comment]
re-adding needs:info - it's not clear what the desired UX in the reviewer tools is for this case.

**Comment by abyrne-moz** [comment]
If we resolve [this other issue](https://github.com/mozilla/addons/issues/1759), can we use the same logic for this issue?

**Comment by abyrne-moz** [comment]
I'll set up a meeting with AMO Eng and Ops to discuss how we want the UI to work in this instance.

**Comment by eviljeff** [comment]
QA: see https://github.com/mozilla/addons-server/pull/22406 for some more detailed testing instructions - the email is corrected by reimplementing how appeals are resolved in the reviewer tools

**Comment by eviljeff** [comment]
> for awaiting review versions after the appeal is sent by a developer, versions won't be flagged for human review meaning they're not going to be in the Manual Review Queue (for extensions) or Updated (for themes). 

It's the same thing reported in https://github.com/mozilla/addons/issues/14888 (awaiting a decision on what fix)

> developer's messages from the appeals sent are not visible anywhere in rev tools. Should that be displayed somewhere, maybe under dsa section or version history?

https://github.com/mozilla/addons/issues/14877 (pr open)
