### ISSUE TITLE
[Bug]: Reviewers theme updates queue contains extra entries

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1762]
### What happened?

STR:
- Start submitting a listed theme
- Give up at the submit details step

### What did you expect to happen?

Expected results:
- The theme doesn't appear in reviewer tools queue because your add-on is incomplete. It shouldn't appear in any reviewer tools queues until submission is resumed and completed.

Actual results:
- The theme appears in reviewer tools theme updates queue

This is visible in prod in the themes Updates queue in reviewer tools: it currently contains extra entries that showed up since https://github.com/mozilla/addons-server/issues/22013 was deployed.

This is caused by the fact that the `is_theme` condition in `VersionManager.should_have_due_date()` doesn't care about the add-on status.

We need to fix the bug and remove the due date for the themes in that state that already have one.

**Note:** unlisted themes have been more or less broken for a long time, and fixing them is likely out of scope for this...

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-47)

**Comment by ioanarusiczki** [comment]
I verified with some themes on -dev and -stage. 

[Incomplete themes ](https://addons.allizom.org/en-US/developers/addon/custom-cream/submit/details) are not displayed in any queue. 

After completing the details step they're displayed in Themes - New Queue.
