### ISSUE TITLE
[Bug]: Purely unlisted versions reported should not go to Cinder Moderators 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1763]
### What happened?
 Installed and reported https://addons-dev.allizom.org/en-US/developers/addon/9365591618de4e06bde7/versions/1801039 choosing a different reason than "it violates add-on policies" 

The report is present in Cinder -[ AMO dev listings queue ](https://stage.cinder.nonprod.webservices.mozgcp.net/job/1f49bf4b-4b80-47ce-ba16-07ef35211f41)

Installed test18.xpi and theme2.xpi from https://ioanarusiczki.github.io/ and reported them with different reasons (excluding "It violates add-on policies" ) 
IDs on stage for the theme https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1007829
Id for the extension 1007895 

Reports went to Cinder in AMO Stage Listings queue or Themes queue https://stage.cinder.nonprod.webservices.mozgcp.net/job/c4782a50-b12d-49e9-896f-bc7a3300d7b6
https://stage.cinder.nonprod.webservices.mozgcp.net/job/da1a48df-06c7-4ea0-9e18-5a7eac4f6703 

### What did you expect to happen?
Unlisted versions should be moderated in rev tools only.

### Is there an existing issue for this?
* [x] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-48)

**Comment by eviljeff** [comment]
@wagnerand

**Comment by eviljeff** [comment]
> Claims about illegal content is handled by Legal, and everything else should be handled by TaskUs. I am not sure how unlisted is too different from listed here.

@wagnerand It's less about which teams, and more about the tools.  The issue describes a scenario where the abuse report is in a cinder queue but for an add-on that has no publicly listed versions there is nothing in the data sent to cinder that could be infringing - it _has_ to be in the add-on xpi itself, which can only be addressed via AMO reviewer tools.  

Maybe the assumed "fix" is that the moderator from Legal would always forward it to AMO?

**Comment by wagnerand** [comment]
@eviljeff ah, thanks. We need to discuss that scenario with Legal to determine how Operations can identify and assess illegal content. Logically (not necessarily technically), when Operations receives a report about something being illegal, we'd forward that report to Legal as they are the experts on what is legal and what is not.

**Comment by abyrne-moz** [comment]
> > Claims about illegal content is handled by Legal, and everything else should be handled by TaskUs. I am not sure how unlisted is too different from listed here.
> 
> @wagnerand It's less about which teams, and more about the tools. The issue describes a scenario where the abuse report is in a cinder queue but for an add-on that has no publicly listed versions there is nothing in the data sent to cinder that could be infringing - it _has_ to be in the add-on xpi itself, which can only be addressed via AMO reviewer tools.
> 
> Maybe the assumed "fix" is that the moderator from Legal would always forward it to AMO?

I propose this same fix. The moderator should engage with the legal team to work on the item together to identify the correct resolution.  If the frequency and complexity of these issues becomes too great we can re-visit this decision.

**Comment by wagnerand** [comment]
> > > Claims about illegal content is handled by Legal, and everything else should be handled by TaskUs. I am not sure how unlisted is too different from listed here.
> > 
> > 
> > @wagnerand It's less about which teams, and more about the tools. The issue describes a scenario where the abuse report is in a cinder queue but for an add-on that has no publicly listed versions there is nothing in the data sent to cinder that could be infringing - it _has_ to be in the add-on xpi itself, which can only be addressed via AMO reviewer tools.
> > Maybe the assumed "fix" is that the moderator from Legal would always forward it to AMO?
> 
> I propose this same fix. The AMO reviewer should engage with the legal team to work on the item together to identify the correct resolution. If the frequency and complexity of these issues becomes too great we can re-visit this decision.

@abyrne-moz I ran the numbers and I am not confident that this would scale. Will share more in private.

**Comment by wagnerand** [comment]
We are currently not planning to change this.
