### ISSUE TITLE
[Bug]: add the path to dev hub for email sent after force-enable

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1765]
### What happened?
Force disable an addon 
Send the appeal 
Force enable + check the appeal 

Email sent

![force enabled with appeal](https://github.com/mozilla/addons/assets/33448286/d2809ab2-8902-4a03-9923-076bb46819f8)

### What did you expect to happen?
https://addons-dev.allizom.org/en-US/developers/addon/630649/versions/ instead of https://addons-dev.allizom.org/

### Is there an existing issue for this?
* [x] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-50)

**Comment by eviljeff** [comment]
I think the public url is what we want (rather than devhub), but I'm not sure why it's not shown.  Might be a race-condition with the task (the add-on is enabled in the reviewer tools; then a task created where the email is sent; but if the database replica isn't up to date it might be seeing it as still disabled)

**Comment by ioanarusiczki** [comment]
Not sure why I was convinced it should be the path to dev hub for listed add-ons but checking I see

- frontend url for listed add-ons or with mixed versions

![listed add-on with frontend url](https://github.com/user-attachments/assets/ffadf948-b3c0-415b-b64d-4ab1e0796ee5)

- dev hub url for unlisted add-ons 

![force enable for unlisted addon](https://github.com/user-attachments/assets/7c7760c7-118d-4d46-8874-3cdda0fd7a9a)

@eviljeff In case the add-on has a different state than approved, it's disabled while awaiting review the email would not be quite accurate (not sure, but I think that's been discussed before).
