### ISSUE TITLE
[Bug]: Email sent at force enable (without an appeal) is missing the dev hub url and version

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1766]
### What happened?
Force enable action without attaching an appeal sends the following email 

![forceenable](https://github.com/mozilla/addons/assets/33448286/571f84f6-8aaf-400f-b370-7df224413546)

### What did you expect to happen?
version number is missing and the url should point to dev hub 

### Is there an existing issue for this?
* [x] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-52)

**Comment by eviljeff** [comment]
same as https://github.com/mozilla/addons/issues/1765 really

**Comment by ioanarusiczki** [comment]
Listed extension

![listed enabled](https://github.com/user-attachments/assets/fff387f1-f4f5-41de-9ed3-72ddac6ca77f)

Unlisted extension

![unlisted enabled](https://github.com/user-attachments/assets/89c7c96b-bb3a-40ae-8307-99363b3479fa)

Same as for https://github.com/mozilla/addons/issues/1765#issuecomment-2265228197 there would be an edge case with awaiting review state.
