### ISSUE TITLE
Always getting "This name is already in use. Please choose another."

### ISSUE THREAD

**Issue by jasonsavard** [mozilla/addons#177]
When uploading a new add-on, I'm stuck on step #3 with error saying "This name is already in use. Please choose another."

I tried the following names with same error...

Explain and Send Screenshots
Capture, Explain and Send Screenshots
Explain, Send Screenshots

I also tried with a gecko id and without a gecko id in the manifest.
I also tried changing the _locales/en/messages.json > name from Capture, Explain and Send Screenshots to Explain and Send Screenshots

Note: That my extension is translated into multiple locales with a different name for each.

**Comment by jvillalobos** [comment]
It could be because of the name string in the manifest: `"name": "__MSG_name__",`

I'm not sure if we currently support localized names like that.

**Comment by diox** [comment]
We are supposed to, yes, but there are bugs in the implementation. See also https://github.com/mozilla/addons/issues/170 and https://github.com/mozilla/addons-server/issues/3206

Assigning to @EnTeQuAk like the others because he worked on it, but also keeping an eye on it myself to see if I can figure out a solution before he gets back.

**Comment by jasonsavard** [comment]
@jvillalobos Thank you very much, that was spot on, I confirm that was the issue and have now successfully submitted my first Chrome ported addon :)

**Comment by diox** [comment]
@jasonsavard can you please attach the zip of the add-on as it was when you had the issue so that we can fix it later ? Thanks.

**Comment by jasonsavard** [comment]
@diox I'd rather keep it private, but essentially I changed:

manifest.json > "name": "__MSG_name__"
to
manifest.json > "name": "Explain and Send Screenshots"

**Comment by diox** [comment]
Can you tell me if you add a `default_locale` set in `manifest.json` (and what value was it, if you had). Also, your zip did contain a `locales` directory? With a subfolder for that `default_locale` if you had one ?

**Comment by jasonsavard** [comment]
Yes and yes. Note that I did not change these for the submission to work.

manifest.json > "default_locale": "en"
_locales\en\messages.json
_locales\fr\messages.json
(and many more)
