### ISSUE TITLE
An add-on with only unsigned versions can't be flagged for review

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1770]
I think this is quite an edge case - a version that is awaiting review is reported (guid can be used to send a report) 

1. Report goes to Dev Listings - it's escalated from there to AMO 
or it can be reported for add-on policies 

Expected result: 
The version should be displayed in the Manual Review Queue 

Actual result: 
Reviewer's pages show the reports but they're not available in the manual review queue

1. AMO reviewer rejects the version , e-mail is sent to reporter and author. Author decides to appeal 

Expected result: 
version should be in the manual review queue

Actual result:
not available 

Notes:
Flags not displayed has been reported into https://github.com/mozilla/addons/issues/9467 

Another problem is that an email is sent to author that these versions have been approved.  Perhaps in this case email should be modified as suggested https://github.com/mozilla/addons/issues/9471

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-55)

**Comment by eviljeff** [comment]
This was just fixed with https://github.com/mozilla/addons-server/pull/22857 (I _knew_ there was an issue about it, but couldn't find it before!)

**Comment by ioanarusiczki** [comment]
- listed channel flagged for abuse report escalated from cinder https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634328
- listed channel flagged for "add-on policies" https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634329
- listed channel theme escalated  https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634330
Theme is rejected with rev tools:
It is flagged because of the abuse report and present in the awaiting review queue
Reviewer rejects the version and checks the dsa report 
An email is sent to the author with an appeal url 
The appeal is sent by the author
Theme is flagged again for hr and back in the awaiting review queue
Decision is to reinstate content: a new version should be submitted and then approved + the appeal from the dsa section checked 

An email is sent that content is reinstated 

![correct email sent](https://github.com/user-attachments/assets/e06155b4-072d-48d5-a683-c2333d46ca73)

So it appears that the reject + approve would also work fine for listed unsigned reported. 

What didn't work is with unlisted so I'm going to file a followup.
