### ISSUE TITLE
[Bug]: Secondary hero shelf icons are not displayed on Chrome

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1771]
### What happened?
Open with Chrome 
 https://addons.mozilla.org/en-US/firefox/
https://addons.allizom.org/en-US/firefox/

![homepage](https://github.com/mozilla/addons/assets/33448286/5d44ab3d-5bbf-4bf3-b38d-c5bb7a5820a0)

It's not reproducible with Edge

### What did you expect to happen?
Secondary Hero module icon should be displayed 

I can see one icon on dev 

![on dev](https://github.com/mozilla/addons/assets/33448286/5fee2385-5d73-4e3e-8306-5efe6303659e)

### Is there an existing issue for this?
* [x] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-56)

**Comment by diox** [comment]
What version of Chrome ? Any errors in the devtools console ? Any errors in the devtools network tab ? I can't reproduce with Version 123.0.6312.122 (Official Build) (64-bit) on Linux.

**Comment by ioanarusiczki** [comment]
It's 124.0.6367.92 (Official Build) (64-bit) on Win(10) up to date and I don't see errors. 


There's 2 icons which are visible 
https://addons-dev.allizom.org/static-server/img/hero/icons/Mail.9a970568c203.svg 
or https://addons-dev.allizom.org/static-server/img/hero/icons/Secure.2b8fa09151af.svg 

Checking secondary hero shelf module with Chrome I see this:

![secondary hero icons admin](https://github.com/mozilla/addons/assets/33448286/6f16b821-f6eb-48d1-ae15-ee076d8e3d86)

**Comment by diox** [comment]
Looks like if I remove the `fill="context-fill"` from these svg the problem goes away... Given that we aren't using those as masks I think we should do that.

**Comment by diox** [comment]
(Not deployed yet on dev despite being closed, watch the slack channel for when deployments resume on dev)

**Comment by ioanarusiczki** [comment]
Verified on -dev, Win(10)

Homepage:

![homepage](https://github.com/mozilla/addons/assets/33448286/6d7bc444-0868-47fc-9033-cc49e5603170)

Admin:

![admin tools](https://github.com/mozilla/addons/assets/33448286/b290d44b-d214-45ce-a530-6f58d49e7a32)
