### ISSUE TITLE
[Bug]: Handle manifests containing comments when re-signing add-ons

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1782]
### What happened?

WebExtensions manifests can contain `//` style comments. When we bump and re-sign an add-on whose latest public version contains a `manifest.json` file that has comments in it, we should handle that gracefully but we're currently failing to bump them.

### What did you expect to happen?

STR:
- Create an add-on with a manifest containing a line with a `// comment`
- Upload it to AMO as listed
- Alter the `created` date of its `Version` in a shell to be dated before 2019-04-04
- Make its latest version public (in reviewer tools, or run `auto_approve` now that it has a creation date in the past)
- Run `manage.py --task=bump_and_resign_addons` command

Expected results:
- The version should have been bumped and the bumped version signed

Actual results:
- The version is not bumped.

We should use `ManifestJSONExtractor(manifest_data).data` to parse instead of `json.loads`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-66)

**Comment by diox** [comment]
https://mozilla.sentry.io/issues/5256116034/?project=6310819

**Comment by KevinMind** [comment]
> we should handle that.

Does that mean if the comments change it should or shouldn't produce a new version? I'm not understanding what exactly is the problem.

**Comment by diox** [comment]
See STR: we are currently failing to bump versions which have comments in their manifest.

**Comment by ioanarusiczki** [comment]
This has been verified on dev and stage with the following extensions with //comments added in manifest.json 

After `manage.py --task=bump_and_resign_addons` all addons have been resigned and I could install the resigned versions with FF127.0a1 

dev
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630707 extension
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630706 theme
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630708 dictionary

stage
https://reviewers.addons.allizom.org/en-US/reviewers/review/1026088
https://reviewers.addons.allizom.org/en-US/reviewers/review/1026089
https://reviewers.addons.allizom.org/en-US/reviewers/review/1026090
