### ISSUE TITLE
[Task]: handle an AMO_IGNORE action from Cinder webhook

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#1787]
### Description

On the back of the decisions in https://docs.google.com/document/d/11psnipQppOJg-cYKtyD6r9UqYOjRjfFl7Y5_YIoUats/edit cinder will have a new AMO_IGNORE enforcement_action.  AMO needs to be able to recognise that enforcement action and carry out appropriate actions.

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [x] AMO_IGNORE action implemented as a CinderDecision.action choice
- [x] A CinderAction created that doesn't result in any change to the targeted content
- [x] AMO_IGNORE shouldn't allow an appeal
- [ ] Email sent to the reporter (see template below).  No email to the content owner.
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-75)

**Comment by eviljeff** [comment]
**Subject: Mozilla Add-ons: {{ Add-on name, Collection name, User name, first-7-letters of rating }} [{{ cinder_job_id/abuse-report-id }}]**
```
Hello,

Thank you for your report about {{ Add-on name|Collection name|User name|first-7-letters of rating }}, at https://a.m.o/path/to/content/.

Based on the information you submitted, we were unable to identify a violation of Mozilla’s policies (https://extensionworkshop.com/documentation/publish/add-on-policies/). The {{ add-on|collection|user|rating}} will therefore not be subject to any moderation action at this time.

{{ If you think this is incorrect, you may submit another report. Please be as specific as possible about the violation you believe is present—including which policy was violated and where the violation is located (for example, in what section of the add-on’s code, or in which feature or element of the add-on the violation is visible)—so we can appropriately process your report.
||
Your report appears to relate to add-on functionality that is not covered by our policies. You can provide feedback directly to the developer using the contact information provided on the listing page, if available.}}

[{{ cinder_job_id }}]
--
Mozilla Add-ons Team
https://a.m.o/
```

**Comment by ioanarusiczki** [comment]
Ignore action seems to be active in [Policies tab ](https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjM5/details/policies) yet it's not displayed in the Action list. 

2 examples:
https://stage.cinder.nonprod.webservices.mozgcp.net/job/23f81b83-bc13-4b65-a303-a437b383bcb2
https://stage.cinder.nonprod.webservices.mozgcp.net/job/a44b2ff2-3565-40b9-9973-6bb7feba747e

Oh and I filed something similar on Lindie yesterday 😕

**Comment by ioanarusiczki** [comment]
2 things

1. I tried testing with extensions, themes, ratings, users but I didn't receive [this](https://github.com/mozilla/addons/issues/1787#issuecomment-2088654704) 

For all entities if I choose "Approve" this email is sent: 

![Approve into Ignore action](https://github.com/mozilla/addons/assets/33448286/433bd774-301a-40a5-85a5-69d27c256cdd)

With "Developer feedback" or "Not enough information" I get a different email - this time the appeal is not included 

![email sent for the 2 new policies from Ignore action](https://github.com/mozilla/addons/assets/33448286/9f7069be-0eee-47a7-84b7-131907ef4b9a)

and 2. I don't understand why in the [document](https://docs.google.com/document/d/11psnipQppOJg-cYKtyD6r9UqYOjRjfFl7Y5_YIoUats/edit) Select "Approve" is only available for policy D.  Right now all queues have "Approve", "Developer feedback" and  "Not enough information" attached to Ignore action.  Sub-policies can be added or removed but I'm guessing that the current setup is the expected one ?

**Comment by eviljeff** [comment]
> 2 things
> 
>     1. I tried testing with extensions, themes, ratings, users but I didn't receive [this](https://github.com/mozilla/addons/issues/1787#issuecomment-2088654704)

Mmm, the policy text should be included for Developer Feedback or not enough information.  Can you file a follow-up?

> and 2. I don't understand why in the [document](https://docs.google.com/document/d/11psnipQppOJg-cYKtyD6r9UqYOjRjfFl7Y5_YIoUats/edit) Select "Approve" is only available for policy D. Right now all queues have "Approve", "Developer feedback" and "Not enough information" attached to Ignore action. Sub-policies can be added or removed but I'm guessing that the current setup is the expected one ?

I believe its because the document is only covering the case when the report isn't sufficient - so the Approve is implied when the report is detailed enough.  But AMO engineering didn't the doc, so it's a question for Lindsay Blackwell (ping in a doc thread or slack)

**Comment by ioanarusiczki** [comment]
Meanwhile "Approve" is present in all queues as a separate action from "Ignore". This issue was about "Ignore" and if it shouldn't allow an appeal , the 2 sub-policies present there don't send the email with the right to appeal meaning I can mark this verified.

 "Approve" is the old "Ignore/Approve" which continues to send the appeal url and it makes more sense to be separate from Ignore. 

There's also "Escalate" with "Escalate to AMO" which is available for all entities (I think I could remove it from the Policies tab for Collections , Ratings, Users). I could send a theme report to rev tools (it's flagged for human review and present in Updated queue) 

Then it's "Escalate to Legal" , I sent a report but I couldn't find it in my available Cinder queues, I've no idea what's with this new policy yet.
