### ISSUE TITLE
[Bug]: Recaptcha keeps spinning

### ISSUE THREAD

**Issue by RyanHanekamp** [mozilla/addons#1788]
### What happened?

Attempting to create a new add-on here:
https://addons.mozilla.org/en-US/developers/addon/submit/agreement

The "I am not a robot" recaptcha just keeps spinning once clicked.
Using Firefox 125.0.3 (up to date), with all extensions disabled. Also attempted in 115.10.0ESR (up to date).

The error reported in the console:
Uncaught 
Object { stack: "z<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:461:46\nH<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:255:158\nuL<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:587:148\nm<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:384:223\nw_@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:707:36\nG<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:145:320\nI<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:131:156\nk<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:35:400\nk<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:36:291\nG</X/<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:171:157\nu</w.Y</w.L<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:337:325\nz<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:433:335\nH<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:244:240\nRJ.prototype.J@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:715:439\ng<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:517:292\npromise callback*ad@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:110:46\nI<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:144:296\ng<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:549:132\nH<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:221:497\nI</<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:110:345\nv@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:787:241\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:788:182\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:785:370\nz<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:428:232\nZA.prototype.dispatchEvent@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:708:317\nm<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:374:292\nCc.prototype.D@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:769:228\nw@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:438:241\nCc.prototype.A@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:770:56\nEventHandlerNonNull*@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:766:102\nI<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:111:118\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:784:340\nk<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:64:254\nY.YT@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:781:445\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:782:207\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:783:361\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:788:87\npromise callback*@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:788:63\nI<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:110:321\nRJ@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:568:157\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:787:124\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:762:460\nqR@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:655:371\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:787:52\nX@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:171:127\nG<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:171:248\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:1030:175\ng</l</<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:522:468\ng</l<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:522:440\nk<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:49:166\nz</this.next@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:444:185\nX@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:269:132\npromise callback*N@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:269:262\nH</E<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:269:283\nH<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:269:179\nk<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:28:62\ng<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:522:136\nz</z<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:451:478\nl3@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:706:500\nw@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:438:241\nD@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:518:173\nEventListener.handleEvent*H<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:223:455\nz<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:447:399\nz<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:466:337\nk<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:25:49\nz<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:451:424\noq<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:659:218\nu<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:331:19\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:1026:72\nm<@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:410:450\n@https://www.gstatic.com/recaptcha/releases/WQcDpAcHn0sjM6ZiVkU8JwNH/recaptcha__en.js:1034:384\n@https://www.recaptcha.net/recaptcha/api2/bframe?hl=en&v=WQcDpAcHn0sjM6ZiVkU8JwNH&k=6LcsBhYTAAAAAKpVTZ16Lh7nmTxVRKoKSr8e3vsV:184:30\n", message: "Error in protected function: oB is not a function", cause: TypeError, Y: true }
recaptcha__en.js:438:420
Uncaught (in promise) TypeError

### What did you expect to happen?

To be able to affirm I am not a robot, and proceed to the next page.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-76)

**Comment by NikDonovan** [comment]
![image](https://github.com/mozilla/addons/assets/133721416/faa6e081-4f97-406e-bbba-ee088194bfe9)
Same issue
![image](https://github.com/mozilla/addons/assets/133721416/d19c285b-bb4e-4b1c-81fa-a26909222391)
message: "Error in protected function: oB is not a function", cause: TypeError, Y: true }

**Comment by aeonix-eth** [comment]
I can confirm as well, this is a broad bug that will break access to many services for many users who must pass ReCaptcha. Should be high priority.

**Comment by jsdawson** [comment]
I am seeing the same in FF 125.0.3 and 126 (beta) on Windows 11, but it works fine in Mac Sonoma.

**Comment by ylemkimon** [comment]
Related: https://github.com/webcompat/web-bugs/issues/136576

**Comment by ylemkimon** [comment]
The issue only seems to affect the Windows Firefox code path of reCAPTCHA, so a temporary workaround would be to spoof the user-agent string to another browser, e.g., `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36`, using Developer Tools:

![image](https://github.com/webcompat/web-bugs/assets/888148/743f90ca-73cc-4f4d-87f9-0bc9a3c573f1)

**Comment by TokyoTF** [comment]
I had the same problem in Firefox 125.0.3 (64 bits) and changing the Useragent A Chrome already works the reCAPTCHA

**Comment by wagnerand** [comment]
This is an underlying problem with reCaptcha, which has already been reported to Google. To follow the progress, please see https://bugzilla.mozilla.org/show_bug.cgi?id=1894735.
