### ISSUE TITLE
Disco Pane: User Research Tweaks

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons#179]
A few proposed adjustments to the disco pane based on recommendations from our UR team.
**Implemented in mocks below**
- Group add-ons and themes by type
- Clearer "hover over the..." copy on the theme blocks
- More obvious links to AMO on blocks
- Social proof on blocks (# of users and star ratings)
- Developer name on blocks (req'd by legal)
- Banner at top of page directing returning users to AMO

**Needs to be implemented**
- More descriptive intro copy at top of page talking about how add-ons are free, and will have minimal space/speed impacts on a user's machine.
- Deactivation notification (We have an activation notification, but need one once a user turns the switch off).
- More descriptive copy in activation/deactivation notifications: Where does the add-on live, where can I manage, etc.)

![screen shot 2016-08-05 at 2 35 16 pm](https://cloud.githubusercontent.com/assets/6797635/17451237/2b2ebe4e-5b1a-11e6-9429-b0f9a0ed5839.png)
![screen shot 2016-08-05 at 2 35 26 pm](https://cloud.githubusercontent.com/assets/6797635/17451240/2eca480c-5b1a-11e6-98f1-e60535eba9e2.png)
![screen shot 2016-08-05 at 2 35 37 pm](https://cloud.githubusercontent.com/assets/6797635/17451242/315c86c0-5b1a-11e6-9cbd-536ce8c01cb6.png)

**Comment by designakt** [comment]
Great to see those Suggestions implemented. Totally love the idea of having an additional message for users on the 3rd visit. (currently 7% of our users in the last 7 days)
Seeing the grouping and added information makes me wonder how literal we should interpret those recommendations, as it makes the page rather crowded and grouping severely limits our possibility to re-arrange add-ons depending on individual persons usage of the browser.

**Comment by designakt** [comment]
Small things like adding tooltips to the toggles might go a long way in helping people understand what will happen if they click.
![discopaneimprovement-tooltips](https://cloud.githubusercontent.com/assets/8145891/17483304/c5137ab4-5d85-11e6-8436-ada554924f6e.gif)

**Comment by designakt** [comment]
Would users expect different information for themes and extensions. I believe social proof has only been an issue with extensions. But with Themes the biggest issue was identifying it as a theme. Could we do something visually to help people understand. (Short of grouping them.) Maybe overlaying Firefox UI would help communicate that this is a theme: 3 different options in a gif-loop
![discopaneimprovement-withtheme](https://cloud.githubusercontent.com/assets/8145891/17484423/05516204-5d8a-11e6-9ff6-eab8e9ccc9e7.gif)

**Comment by tofumatt** [comment]
Overlaying the UI is a really nice touch and makes it a lot clearer what that item is and why it looks different to the add-ons. 👍

**Comment by designakt** [comment]
Some variations on the UI I tried and showcased in last weeks design critique:

adding "free" in add-on toggles to indicate that those add-ons do not cost anything.
adding copy to add-ons explaining why they have been chosen for that list.
![discopane-improvement_mozillaproof_0001_free -proof-copy- -dev-name](https://cloud.githubusercontent.com/assets/8145891/17665653/9d9657b4-62fc-11e6-9ef7-86a36e4d3a59.png)
Feedback in critique: this suggest that other add-ons might cost something. Might be building a wrong model in peoples minds.

adding elements to support trust in the providers of disco pane (Firefox, Mozilla) for people to trust those add-ons:
![discopane-improvement_mozillaproof_0006_- -trust-mozilla-a](https://cloud.githubusercontent.com/assets/8145891/17665705/d70ba1ca-62fc-11e6-92d1-6940446a013a.png)
![discopane-improvement_mozillaproof_0007_- -trust-mozilla-b](https://cloud.githubusercontent.com/assets/8145891/17665704/d708da8a-62fc-11e6-8857-b2fc26a4d229.png)

adding elements to support social proof of individual add-ons for people to trust those add-ons:
(and experiment if performance could be visualized individually per add-on.)
![discopane-improvement_mozillaproof_0004_ -social-proof-a](https://cloud.githubusercontent.com/assets/8145891/17665656/9d99f9f0-62fc-11e6-9ed9-8af01a65f701.png)
![discopane-improvement_mozillaproof_0005_ -social-proof-b](https://cloud.githubusercontent.com/assets/8145891/17665654/9d9876d4-62fc-11e6-87c6-98dc95367f4f.png)

**Comment by jvillalobos** [comment]
This seems to overlap with the Disco Pane Q3 project, so I'm adding it for consideration.

**Comment by muffinresearch** [comment]
@pwalm @jvillalobos this is a really old issue, I think it would be good to review this alongside the other issues in https://github.com/orgs/mozilla/projects/21 and figure out what bits to keep and what we don't need. It would also help massively to break this down into a bug per actionable item.
