### ISSUE TITLE
Search: searching for "word of the day" doesn't find Disconnect highest in search results

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons#1795]
Follow up for mozilla/addons#4978 

1. Load AMO stage
1. Do the following search: https://addons.allizom.org/en-US/firefox/search/?q=word%20of%20the%20day

Expected result:
[Disconnect](https://addons.allizom.org/en-US/firefox/addon/disconnecttet/?src=homepage-collection-featured) is found highest in search results list, because it includes the "word of the day" string in its description

Actual result:
[Disconnect](https://addons.allizom.org/en-US/firefox/addon/disconnecttet/?src=homepage-collection-featured) can be found only on [page 2](https://addons.allizom.org/en-US/firefox/search/?q=word%20of%20the%20day&page=2)

![image](https://user-images.githubusercontent.com/31961530/47482939-9f7bd700-d840-11e8-97b3-c8d0d5289986.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-81)

**Comment by diox** [comment]
https://github.com/mozilla/addons/issues/1795#issuecomment-2093243321 is still accurate. https://addons.allizom.org/en-US/firefox/addon/disconnecttet/ doesn't have enough users and the terms are only showing up in the description, hence the low position in the results.
