### ISSUE TITLE
Forbidden addon from 2010 is blocking my new version upload for signing

### ISSUE THREAD

**Issue by noblescz** [mozilla/addons#18]
I am using addon info@sopr.cz_surchange for years. It is ment for limited audience of our project and I distribute it from my website. It is marked as "forbidden" since 2010. Now with the new requirement I am unable to switch to "non published addon" and upload new version - upload ends with status: 403 (forbidden). == I am stuck

I need to use id:info@sopr.cz_surchange, because with new addon I would loose user preferences.

Can you please enable option to upload new version of an addon which is "forbidden" and make available preliminary revision?

Thanks for a great browser Petr

**Comment by andymckay** [comment]
Please email amo-admins@mozilla.org with this information.
