### ISSUE TITLE
Make the registration process more clear during FxA migration

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons#180]
As noted in https://github.com/mozilla/addons/issues/167 clicking on "I don't have an account" or 
"Register" when on the login page takes you to the login page which is confusing.

The register page have some copy like "Please enter your email address to start the registration process" and the log in page should have something similar. This might be subtle but hopefully it makes it more clear.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-stage using FF48(Win 7 x64).
The message is displayed if the login/register page is accessed from everywhere (i.e. log in, register, I don't have an account, submit an Add-on, submit a new Theme, create a collection, create an Add-ons account, log in to your current account - for last five user must be logged out)
Postfix screenshot: 
![migrating](https://cloud.githubusercontent.com/assets/15685960/17550664/bae7b3d2-5efe-11e6-8384-d520894e5921.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48(Win 7 x64)
Postfix screenshot: 
![2016-08-17_1256_001](https://cloud.githubusercontent.com/assets/15685960/17732434/6b3c2954-647a-11e6-97c6-811356465625.png)
