### ISSUE TITLE
WebExtension Validation Error

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons#181]
I am getting a validation error of `Error: This file is not binary and is too large to parse. Files larger than 2MB will not be parsed. If your JavaScript file has a large list, consider removing the list and loading it as a separate JSON file instead.`

Steps to reproduce:
I download this chrome webextension: https://chrome.google.com/webstore/detail/tout-debrid-express/odeeemnkckaefjlhfjebolnkjmongejn

I converted it to a xpi, gave it a applications.gecko.id.

1. I tried signing it with the API I got an error -https://addons.mozilla.org/en-US/developers/upload/7fd131e4619d45ea92bfe8c6c8f9884b

2. Initially, I got a report that this failed with the signing API - https://github.com/Noitidart/Chrome-Store-Foxified/issues/32

3. I tried to sign the XPI manually via AMO uploader but this also failed - https://addons.mozilla.org/en-US/developers/upload/997cba086aec4afe8c3d261987d952cb &&&& http://i.imgur.com/cwYLnwv.png

I attached the unsigned XPI. I renamed the extension from XPI to ZIP as Github is not allowing upload of XPI.

[Tout Debrid Express - Version 0.0.9 - UNSIGNED.zip](https://github.com/mozilla/addons/files/407995/Tout.Debrid.Express.-.Version.0.0.9.-.UNSIGNED.zip)

**Comment by andymckay** [comment]
The error is quite clear and its this limit here: https://github.com/mozilla/addons-linter/blob/384fe86a36b95d923c07a1a105c3973306cb8f5d/src/const.js#L113-L117, the file is just over 2M in this case. 

@tofumatt we are hitting this in a few different add-ons, I with large libraries like ffmpeg (in another bug). I know we had that bug with the large array, but not all large files are large arrays. 

I think we might need to up this limit, although not sure if @wagnerand and the review team have any special feeling about a sane limit.

**Comment by tofumatt** [comment]
We started with two megs as an intentionally small limit and figured we'd
up it in response to things like this. Not a problem :-)

**Comment by bluejamesbond** [comment]
What is the appropriate action to take if the script is > 4MB i.e. 5MB?

**Comment by tofumatt** [comment]
If it’s possible we’d encourage you to split up your scripts then and see about using a module loader system.

4MB is quite a lot of JS for most add-ons. That said, we could look at upping the limit again… but eventually we will run into errors with huge files.

**Comment by Noitidart** [comment]
@bluejamesbond if you are having trouble with it, please let amo-admins@mozilla.org know - they will (1) help you bypass validation for uploading, (2) then they will give it an in-depth review.

**Comment by bluejamesbond** [comment]
@Noitidart, @tofumatt thanks for the quick response

**Comment by Noitidart** [comment]
:) - I didn't see tofumatt's response, so I removed it. But I'll add it back as I guess everyone saw it - if you are having trouble with uploading the addon reach out to amo-admins@mozilla.org and they will get you through.

**Comment by niktrix** [comment]
i am using wepack for js file, which gives me 8 mb file in future this fie size will increase, is there any way i can avoid 4mb limit error

**Comment by tofumatt** [comment]
@niktrix Well, if add-ons are routinely growing in size we'll have to deal, though there are issues scanning files that size. What are you including that's causing the file to be so large? Are there any JSON files, etc. that could be moved out? An add-on won't really benefit much from having everything in one file like a website over HTTP would.

**Comment by niktrix** [comment]
its an webpack output file, so my whole code is included in that js file

**Comment by bluejamesbond** [comment]
@niktrix I solved it by using the `webpack#import` feature to split up the code
