### ISSUE TITLE
MultiFox

### ISSUE THREAD

**Issue by iaidq** [mozilla/addons#183]
Using Firefox 48.0 + Multifox 3.2.3

When using any profile other than default, Google Drive will not load - I see a spinning coloured circle.

Help please. This is forcing me to use Chrome

**Comment by andymckay** [comment]
Please contact the author of multifox: https://addons.mozilla.org/en-US/firefox/addon/multifox/

The author of multifox doesn't look at this repository, so I'm afraid it won't help.
