### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by Peuc** [mozilla/addons#184]
Please attach a copy of your add-on, and fill in the following information:
* New addon
* Addon is unlisted (so it's not attached here)
* The file has been submitted from addons.mozilla.org website. Server filename is 3683895422124286884b83305883d966_pinao.xpi
* Tried multiple times, last try about 20 min ago

The process fails with no explicit error.

**Comment by wagnerand** [comment]
Please add a screenshot of the issue.

**Comment by wagnerand** [comment]
Also, we can't access raw files. Even if we could, filenames are renamed during upload. I am not sure your file has even been uploaded though. Is your add-on entry showing up in your developer hub?

**Comment by Peuc** [comment]
Here is the screenshot:
![capture d ecran 2016-08-16 a 16 39 36](https://cloud.githubusercontent.com/assets/1884558/17715068/8ba3f528-63d0-11e6-851d-d8a834c77d99.png)

The addon is Unlisted in my developer hub, since it's not supposed to be publicly released. I just need get it signed by Mozilla in order to it continues working in my Firefox 48.0+ browsers.

**Comment by wagnerand** [comment]
Can you link to the add-on in your developer hub, please, so we can have a look?

**Comment by Peuc** [comment]
I added a link to a copy of the xpi in the Description field of the addon, in my Developer Hub.

**Comment by wagnerand** [comment]
I meant please add a link to your add-on here. We can't know what your add-on is.

**Comment by Peuc** [comment]
I've uploaded a xpi here: http://peuc.net/pinao.xpi

**Comment by wagnerand** [comment]
For reference, the link to the add-on is https://addons.mozilla.org/en-US/developers/addon/pi%C3%B1ao/edit

`amo-validator` reports the following error:
```
./addon-validator ~/Desktop/pinao.xpi
ERROR:amo.validator:Unexpected error during validation: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/awagner/mozilla/amo-validator/validator/submain.py", line 70, in prepare_package
    test_package(err, package, path, expectation, for_appversions)
  File "/Users/awagner/mozilla/amo-validator/validator/submain.py", line 167, in test_package
    test_inner_package(err, package, for_appversions)
  File "/Users/awagner/mozilla/amo-validator/validator/submain.py", line 377, in test_inner_package
    test_func(err, xpi_package)
  File "/Users/awagner/mozilla/amo-validator/validator/testcases/content.py", line 172, in test_packed_packages
    script = _make_script_absolute(reversed_chrome_url, script)
  File "/Users/awagner/mozilla/amo-validator/validator/testcases/content.py", line 429, in _make_script_absolute
    return '/'.join(xul_path_split)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```

**Comment by wagnerand** [comment]
I assume that `amo-validator` trips over non-ascii characters in `chrome.manifest`, like
```
content				piñao			chrome/content/
```

I am not sure what a proper fix looks like.

**Comment by Peuc** [comment]
I renamed `piñao` into `pinao` in the manifest as a workaround, and the validator now works as expected.

Thanks for your help!
