### ISSUE TITLE
Bug in "Check Your Plugins"

### ISSUE THREAD

**Issue by JDP91** [mozilla/addons#185]
The mozilla functionnality  "Vérification des plugins" ( https://www.mozilla.org/fr/plugincheck/ )
or "Check Your Plugins" ( https://www.mozilla.org/en-US/plugincheck/ )
for Firefox on Windows 7 doesn't work for a few weeks.

I have no result, even after a very long time and it seem to have enter an infinite loop

Could you help me ?

**Comment by wagnerand** [comment]
This repository is about addons. Plugincheck is a different thing, you can find more information about it at https://wiki.mozilla.org/Plugins:PluginCheck
