### ISSUE TITLE
Authenticated reporter is "anonymous" in abuse-reports

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1896]
When sending abuse-reports with authentication from desktop - FF103(Win10) I've noticed that the Reporter stays anonymous (last column from abuse-reports[ page](https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/502996))

This is not reproducible with authenticated requests using the API or from an Android device (with Fenix). 
Reproducible on -dev and -stage.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-182)

**Comment by diox** [comment]
This was fixed by https://github.com/mozilla/addons/issues/14807 (note that you need to set `extensions.addonAbuseReport.url` on dev/stage, it defaults to prod)
