### ISSUE TITLE
Always getting logged in as "anonymous user d7c7dc. Please check

### ISSUE THREAD

**Issue by M-Reimer** [mozilla/addons#190]
Hello,

my mail address is manuel<dot>spam<at>nurfuerspam<dot>de
When I try to log in, I end in an "anonymous account". I had Addons in my account and want to upload a new version. Would be nice if someone could fix my account. Thanks.

**Comment by M-Reimer** [comment]
Thanks github for killing characters.
Mail address again:
manuel(dot)spam(at)nurfuerspam(dot)de

**Comment by M-Reimer** [comment]
Found the reason... Seems like your "porting code" does ugly things. I used a different mail address for logging in in the past, so probably the account with the address above never existed or was never used for AMO... My problem is fixed, but maybe it is a good idea to check why this happened.

**Comment by andymckay** [comment]
Firefox Accounts is now the only way to login, so I don't think this can happen anymore.
