### ISSUE TITLE
Can we add a feature request section on AMO?

### ISSUE THREAD

**Issue by WesleyBranton** [mozilla/addons#191]
There are so many developers in the world, but I big problem when it comes to making add-ons isn't so much developing the add-on, but rather figuring out what your add-on should do. To be a developer, you not only have to be able to execute the add-on, but you need to figure out a feature that users want added to Firefox so that you know what your add-on should be about.

In order to help developers that may lack the awareness of what Firefox users want or may just lack general creativity, we should have a section on AMO where users can put in their add-on ideas and requests. The people that would be posting the ideas would be people that are probably not savvy enough to develop the add-on, but want to see it in Firefox.

The developers can then look through the public requests and develop an add-on with the features that the users want to see. The once AMO admins can confirm that there is an add-on to satisfy that request, it can be removed or archived.

This would increase the amount of useful add-ons available on AMO and would maybe even get more developers that couldn't think of an add-on idea involved with developing on AMO.

**Comment by andymckay** [comment]
Could we fulfill this using a community discussion board like https://discourse.mozilla-community.org/c/add-ons or user voice or similar non-AMO software?

**Comment by WesleyBranton** [comment]
Could probably use Discourse, but there needs to be a topic added to the add-ons section. It would also be great to have a link on AMO which directs users to it because I don't think that there are a lot of users that know about Discourse. So adding a "Request Add-on" link to AMO would probably be ideal.

**Comment by devaneymoz** [comment]
This is a really interesting idea. I don't have anything of tremendous value to add at this time other than to say I'd be happy to support an effort like this, and I'll get to thinking about ways to do that.

**Comment by designakt** [comment]
@pwalm This could be a feature for the desktop version. Maybe not so much for the mobile one.

**Comment by pwalm** [comment]
We could build in links to a Discourse page. At the end of search results or possibly into the footer?

**Comment by wagnerand** [comment]
There is https://connect.mozilla.org/ these days.
