### ISSUE TITLE
Expand copy for content review rejection to indicate the right scope for immediate rejection

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#1915]
Add-ons may be rejected for violation of Mozilla acceptable use policies (https://www.mozilla.org/en-US/about/legal/acceptable-use/) in addition to serious security issues, but the copy on the radio button on `content review` page > `admin actions` reads  `Only use in case of serious security issues`

https://github.com/mozilla/addons-server/blob/bc8368e546e5a003378df53ef74a13e5a3d1370d/src/olympia/reviewers/forms.py#L257-L258

Should it be updated to reflect the case for content/listing rejection for violation of other policies?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-201)

**Comment by wagnerand** [comment]
Rename to "Reject immediately.".
