### ISSUE TITLE
Provide arm64 docker images

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#1919]
On Macs using the Apple Silicon arm-based architecture, Docker raises warnings for several containers about performance impact.

I can confirm that running tests on a M2 Pro are very slow. Can we provide arm64 images for Apple Silicon users?

![](https://user-images.githubusercontent.com/873258/218821946-1525c974-afd4-47b7-bba9-95fece1796cc.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-223)

**Comment by diox** [comment]
Not worth fixing for now given the constraints around MySQL client libs..
