### ISSUE TITLE
When submitting a new version, allow me to select a channel

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#192]
### User story

As a developer, I would like to manage both the listed and unlisted versions of my add-ons from one place. Whereas today, I am required to create an entirely new add-on entity for each channel.
### What this bug focuses on

When you submit a new add-on, we already ask you whether you’d like it to be listed or unlisted. But when you submit a new _version_ of that add-on, we don’t ask you this question. We need to start asking.

**Comment by brampitoyo** [comment]
In this proposal, the Add New Version interface opens in a new page instead of being displayed in a modal.

Generally, this interface is a subset of the Add New Add-on interface, with these exceptions:

* If your add-on is unlisted, we skip the “Confirm Version Information” step
* if your add-on is listed:
  * We hide all the field in the “Describe Version” step, except for:
    * Release Note
    * Note for Reviewer
  * We skip the “Add-on Image” step

The rest stays the same.

### Add new version – unlisted

![add-new-unlisted](https://cloud.githubusercontent.com/assets/51007/18298747/07bb414e-750f-11e6-98ef-a0a94a8951d6.PNG)

### Add new version – listed

![add-new-listed](https://cloud.githubusercontent.com/assets/51007/18298751/0ce9cece-750f-11e6-94f8-4bc79534510c.PNG)

**Comment by jvillalobos** [comment]
I expect the majority of add-ons to have either only unlisted versions, or only listed versions. I suggest that we drop step one. In the upload step, show "Version hosted on this site" or "Version hosted on my own", depending on the last version upload, with a "Change" link next to it. If you click on it, it takes you to step one.

**Comment by brampitoyo** [comment]
Quote:

> if an add-on only has unlisted versions and a listed version is submitted for the first time, show the “Edit listing” step from the first submission flow.

**Comment by brampitoyo** [comment]
I’ve tweaked the version update submission based on our discussion and the notes above.

Changes:

* When your last uploaded version is listed, we automatically assume that the version you’re about to upload will also be listed (the same goes for unlisted; but you can change channel any time)
* If your add-on only has unlisted versions so far, but you want to submit a listed version, we’ll show you a step to edit listing (since you haven’t added these details before)

### Add new version – unlisted

![new version - unlisted](https://cloud.githubusercontent.com/assets/51007/18456699/3565c5f0-79a7-11e6-85e4-9a92a4938634.png)

### Add new version – listed

![new version - listed](https://cloud.githubusercontent.com/assets/51007/18456709/3f26f398-79a7-11e6-88cb-ccfd3ddcd4ac.png)

**Comment by jvillalobos** [comment]
This still has a first step that most of the time will be a click-through. I'd like to start on the Upload Step, but with the Where to Host text and link at the top. The Change link would take you to the Where to Host selection step.

I know this mixes up two steps, but it will also be a more streamlined experience for most cases.

**Comment by brampitoyo** [comment]
That’s a great idea. I’ve revised step 1 so we start with Upload, but adding a “Where to Host” option that you can change.

### Add new version – unlisted
![new version - unlisted](https://cloud.githubusercontent.com/assets/51007/18493293/e271b404-7a63-11e6-9f38-0aa705212ba3.png)

### Add new version – listed
![new version - listed](https://cloud.githubusercontent.com/assets/51007/18493299/ea11c280-7a63-11e6-941b-2712d8f1006b.png)

**Comment by jvillalobos** [comment]
Merging the two steps has a bit of a caveat: if you upload first and then change the hosting mode, the add-on will need to be re-validated (since there are different validation rules). This means we need to cancel validation if it's running, and disable the continue button until the re-validation completes. It should be doable, but tricky state handling.

**Comment by brampitoyo** [comment]
Let’s check in with engineering to make sure that it’s doable in time. If it is, then great! I’d prefer this option. But if it’s not, then confirming your channel and clicking “Continue” is a small enough step to not cause a lot of annoyance.

**Comment by jvillalobos** [comment]
* The feedback is that revalidating might break some things, so let's go with plan B.
* In the case where you submit a listed version after only submitting unlisted ones, the Information step should also include the Version Notes field.

**Comment by brampitoyo** [comment]
Changes to make:

* When you click “Change”, go back to Channel selection (see earlier mockup), but select the other channel by default.

**Comment by jvillalobos** [comment]
There is one flow that's missing here that I totally forgot: if you upload a version and pick only one plaftorm (say, Windows), after you finish submitting it, you have the option to upload more files in the developer page for that version.

The flow to upload a new file is simpler, but different:
* Show the upload page _without_ the option to change the channel.
* The platform options are radiobuttons and don't show "All".
* After clicking on the Continue button, skip straight to the end (don't ask for version notes or notes to reviewer).

**Comment by brampitoyo** [comment]
Updated design based on feedback, and added a screen to Add New FIle.

#### Add New Version – Unlisted
![new version - unlisted](https://cloud.githubusercontent.com/assets/51007/19226077/c6fd6700-8f02-11e6-9459-b9ed319a43a3.png)

#### Add New Version – Listed
![new version - listed](https://cloud.githubusercontent.com/assets/51007/19226079/ca0890fa-8f02-11e6-8305-ce987f2c3a58.png)

#### Add New File
![new file](https://cloud.githubusercontent.com/assets/51007/19226080/cce1dce6-8f02-11e6-9e62-9f2e43b584fa.png)

**Comment by eviljeff** [comment]
Can you clarify the case when there are mixed unlisted & listed versions?  Should the default be the last channel chosen?  Or redirect to the choosing step?  Something else?

**Comment by jvillalobos** [comment]
The default should be the channel of the latest version submitted, yes.

**Comment by brampitoyo** [comment]
The design for this issue is finished and we’re now ready to implement it.
