### ISSUE TITLE
make changes to allow flake8-bugbear rule B904 to be enabled in ruff

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#1931]
In mozilla/addons#9160 we replaced flake8 with ruff and enabled an additional set of rules from flake8-bugbear - we needed a single rule to replicate flake8-mutable - but most of the rules were new and introduce a number of extra fails.  See https://github.com/mozilla/addons-server/pull/20652#issuecomment-1536040455 for breakdown.  Most/all are useful so we should look re-enable the B rules (the ignore section in the ruff settings in pyproject.yml)

--update
after mozilla/addons-server#20990 there is only one remaining ignored rule, [B904](https://beta.ruff.rs/docs/rules/raise-without-from-inside-except/), which occurs 94 times in our codebase (as I write)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-211)

**Comment by ioanarusiczki** [comment]
I think that's a qa not needed
