### ISSUE TITLE
In the Status & Versions page, the Listed/Unlisted/Hidden radio button switches should be replaced

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#194]
### User story

As a developer, I would like to manage both the listed and unlisted versions of my add-ons from one place. Whereas today, I am required to create an entirely new add-on entity for each channel.
### What this bug focuses on

We support _both_ listed and unlisted. This makes choosing between listed _or_ unlisted moot. Let’s remove these radio buttons and replace it with “Hidden/Not Hidden”.

Note: “Hidden/Not Hidden” is only needed if your add-on has a version that’s been marked as “Listed”. Unlisted versions can’t be hidden, obviously!

**Comment by brampitoyo** [comment]
Early design of here, but expect it to change:

![management status versions](https://cloud.githubusercontent.com/assets/51007/18299219/2666a5da-7513-11e6-9fb3-4bac526c9d87.png)

**Comment by brampitoyo** [comment]
I’ve updated the visibility control by renaming it to “<kbd>AMO</kbd> Listing visibility”, and gave the “Delete Add-on” control its own section with explanatory text.

I think this should help clarify things, but I’m curious if my “Delete” text is accurate. Can you help me check it?

![status versions](https://cloud.githubusercontent.com/assets/51007/18459255/2986cec2-79bc-11e6-8ccf-d5183442bb28.png)

**Comment by jvillalobos** [comment]
I think the Delete section should have the same border as other sections above.

I suggest this text: `Deleting your add-on will permanently delete all versions and files you have submitted for this add-on, listed or not. The add-on ID will continue to be linked to your account, so others won't be able to submit versions using the same ID.`. We might want to tweak the dialog that pops up when you click on the button, for consistency.

Nit: both explanations for Visible and Invisible should end with a period.

**Comment by brampitoyo** [comment]
I knew something about the design looked a bit off. Thanks for the suggestion.

Updated:

![listed status versions](https://cloud.githubusercontent.com/assets/51007/18494228/1b04072c-7a69-11e6-95a9-fab7aa0dd457.png)

**Comment by brampitoyo** [comment]
The design for this issue is finished and we’re now ready to implement it.
