### ISSUE TITLE
When an add-on only contains unlisted versions, some management pages should not be displayed

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#195]
### User story

As a developer, I would like to manage both the listed and unlisted versions of my add-ons from one place. Whereas today, I am required to create an entirely new add-on entity for each channel.
### What this bug focuses on

Your add-on isn’t listed on AMO, so we won’t need to bother you with showing these management pages in the sidebar:
- Manage Developer Profile
- Manage Payments
- (View Listing?)
- View Statistics Dashboard
- Compatibility Reports

**Comment by brampitoyo** [comment]
Design as shown.

![unlisted - sidebar](https://cloud.githubusercontent.com/assets/51007/18298335/ea806990-750b-11e6-9511-fca25e939017.png)

(What will happen to the “Status” sidebar on top of the navigation sidebar? I’m not sure, so it’s left blank for now. We’ll tackle this in another issue).

**Comment by jvillalobos** [comment]
Andy brought up that "Compatibility Reports" (and the green/red widget next to it) is still relevant and works for unlisted add-ons, so let's bring that one back.

**Comment by brampitoyo** [comment]
Great. Let’s re-add the “Compatibility Reports” into the sidebar of unlisted add-ons management – and of course the green/red numbers below it, too.

![unlisted sidebar](https://cloud.githubusercontent.com/assets/51007/19226796/b6f41df4-8f0c-11e6-8080-82630c73d095.png)

**Comment by brampitoyo** [comment]
The design for this issue is finished and we’re now ready to implement it.

**Comment by ValentinaPC** [comment]
@brampitoyo : If user is an admin, should the "Admin Manage" and "Editor Review" should still be displayed for unlisted add-ons, yes? Thanks.

**Comment by jvillalobos** [comment]
Yes. Note that those two options were added **after** this bug and mocks were created.

**Comment by ValentinaPC** [comment]
Based on previous checking ( https://github.com/mozilla/addons-server/issues/3472) we can mark this as verified.
