### ISSUE TITLE
Reviewer replies should be logged in add-ons review log

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#1952]
### Summary
On the `/reviewers/reviewlog` page, we currently list reviewer actions like approval, confirming auto-approval, rejection and scheduled rejections. 

We do not log reviewer replies on this page

### Proposal
* Log all reviewer replies in review log just like we do for approvals and rejections (with the content of the reply message searchable as well)

### Usecase
* Reviewers frequently look at previously handled similar cases to draft their response by searching for a keyword. Being able to search through the complete list of responses would make the search more thorough.
* Reviewers need a way to look at / find an unlisted auto-approved add-on that they previously processed and if the only action taken on it was a reviewer reply, it is hard to find it again. 

### Anything else we should know?
* The search functionality on review log page is very slow (especially for longer time span searches), and while that's an existing issue, could it amplify if we make more things searchable?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-238)

**Comment by wagnerand** [comment]
Unlisted auto-approved versions can be rejected now.
