### ISSUE TITLE
400 error when submitting a block containing more than ~1000 versions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#1953]
I tried to submit a block with 10 add-ons (~1700 versions). I get to the block details page to select versions, reason etc. When trying to submit on that page, I receive a 400.
Blocking the same add-ons worked fine when I use smaller chunks (2-4 add-ons). The add-ons were in different states, some were deleted, others not.

Block request: https://bugzilla.mozilla.org/show_bug.cgi?id=1851475

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-239)

**Comment by diox** [comment]
Ideally, if an add-on has too many versions (above a specific threshold) we would display a range instead to work around the issue. This would obviously have implications but it should be acceptable.

**Comment by diox** [comment]
An interesting workaround in the meantime: we could set `DATA_UPLOAD_MAX_NUMBER_FIELDS` to `None` in the internal instance that serves admin tools specifically. That wouldn't solve the poor UX but should make it possible to submit the form, even if it'd potentially take a long time to process server side.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/pull/22916 applies that workaround.

To ensure it's fixed, try blocking a total 1000 versions or more in a single submission through the admin.

**Comment by ioanarusiczki** [comment]
@diox 

If you can help with that ... one add-on or multiple addons (but those would need many versions too). Having 1000 different guids makes it too complicated. 

 I don't know the env. , depending on what else would land this week , I'd go with dev or stage but it's up to you.

**Comment by diox** [comment]
@ioanarusiczki try blocking `{87698f71-0bae-4d22-b64b-66bb21d10e54}` on dev

**Comment by ioanarusiczki** [comment]
I tried from "Block add-on" button , it took a little longer but I've no error
admin page with [block history](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/1091/change/?_changelist_filters=signoff_state%3Dall)


![no error zip](https://github.com/user-attachments/assets/78dc4ff7-ad9f-4a2b-9228-9822c0b9e4ef)

**Comment by ioanarusiczki** [comment]
Bad Request (400) right now on -stage with {d0ae11fe-72db-4863-87aa-468eff4b47b6} so results on dev are a good sign. I'll try this again on stage once it lands.

**Comment by ioanarusiczki** [comment]
I've tried on stage with {d0ae11fe-72db-4863-87aa-468eff4b47b6} soft block, harden block, unblock, edit reason (had a server error on Win) but then I tried on macOS and worked just fine. Repeated on win and could not reproduce the error.
