### ISSUE TITLE
When an add-on only contains unlisted versions, some fields in the Edit Listing page should not be displayed

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#196]
### User story

As a developer, I would like to manage both the listed and unlisted versions of my add-ons from one place. Whereas today, I am required to create an entirely new add-on entity for each channel.
### What this bug focuses on

Your add-on isn’t listed on AMO, so you don’t need to edit listing details such as:
- Experimental
- Categories
- Tags
- Images
- Support information
- Technical details
  - But you still want to see UUID
  - But you still want to see whiteboard

In fact, it’s probably no longer correct to call this page “Edit Listing”, since your add-on is already unlisted. We should think of a better name. For example, what if we call it “Edit Reviewer-facing Information”? It’s long, but it conveys why you might still want to see these fields.

**Comment by jvillalobos** [comment]
"Edit Info" might be good enough, and could work for listed add-ons as well. These are developers after all, so they can deal with the brevity.

**Comment by brampitoyo** [comment]
Here’s a mockup of the “Edit Listing” page for add-ons that only has unlisted versions.

Changes:

* The page title is renamed “Edit Information”. As Jorge had suggested, this new title should also be applied for listed add-ons.
* The sidebar contains only fewer links. This is addressed in another issue.
* The page itself contains much fewer sections and fields, as mentioned above.

Question: have I included the right fields, or have I gone too far in removing them, so we have to re-add a few more?

![unlisted edit info](https://cloud.githubusercontent.com/assets/51007/18461735/9a95a2e6-79d0-11e6-99c8-70bed7af4cc5.png)

**Comment by jvillalobos** [comment]
Looks very good. A couple of things to add back: the Add-on Details section, with Description and Homepage under it. Those fields could be useful for reviewers.

One more thing we can hide: the "Localize for" selector on the top right.

**Comment by brampitoyo** [comment]
Thanks for the feedback. I’ve made the update below:

![unlisted-edit-information](https://cloud.githubusercontent.com/assets/51007/18494017/d6e2248a-7a67-11e6-920a-5c9deb688e2a.png)

**Comment by eviljeff** [comment]
Do we need the Add-on Details section at all?  Description isn't shown anywhere, (it's only a separate section from Summary for editorial reasons on the listing page) and homepage similarly isn't shown anywhere.

**Comment by jvillalobos** [comment]
We're leaving those in because they can be useful for reviewers if they want/need to give the add-on a look. We aren't requiring them, but could come in handy.

**Comment by brampitoyo** [comment]
The design for this issue is finished and we’re now ready to implement it.
