### ISSUE TITLE
Stop sending approval emails for langpacks

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1968]
We are sending approval emails for langpacks like any other add-on. Releng have confirmed they don't need them though, it's flooding their inboxes for no added benefit. Let's get rid of them.

Manual approvals of langpacks, or any approval for other types of add-ons should continue to send emails as before.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-254)

**Comment by ioanarusiczki** [comment]
Lang packs don't receive an email after auto-approval on the listed channel. 

For the rest of the scenarios such as listed versions manually approved , unlisted versions auto-approved or manually approved -> email is sent. But I don't think Releng has these scenarios on prod.

Other add-on types have emails sent at auto-approval or manual approval.
