### ISSUE TITLE
During submission flow, if your add-on is listed, only ask for required fields

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#197]
### User story
As a developer, whether my add-on is listed or unlisted, I would like its submission/signing process to proceed as quickly as possible.

### What this bug focuses on
* We found that virtually every developer that doesn’t use a custom icon would pick the green puzzle icon
  * Let’s make green puzzle the default and remove the rest of the icons
  * We should still keep the “Upload a Custom Icon…” option
* The “Select a license” step is actually quite simple
  * Let’s include it in the “Describe your add-on” step
  * This way, we can remove one step from the “Submission Process” sidebar!

**Comment by jvillalobos** [comment]
> remove the rest of the icons

I don't think it hurts to have those alternative icons as options. I do think that, if the add-on doesn't have an icon in the package, the green icon is a good default and then we don't need the "Select images" step either.

**Comment by brampitoyo** [comment]
* Included the “Select a license” interface in the “Describe Add-on” step
* Modified the “Select Images” step:
  * If add-on package has an icon, we won’t show you the list of preset icons
  * If add-on package has *no* icon, we’ll show you a list of icons to choose from, but remove the “Select images…” button

### Describe add-on: select a license field

![listed describe](https://cloud.githubusercontent.com/assets/51007/18297872/491d963e-7508-11e6-96a8-960ea6a86f46.png)

### Add-on images

![listed images](https://cloud.githubusercontent.com/assets/51007/18297882/5adebeb6-7508-11e6-9192-02d846aac66d.png)

**Comment by jvillalobos** [comment]
Sorry, I think I wasn't clear. I don't think we need image selection in the submission process. We can give the add-on an icon automatically without prompting the developer, and let them change it in the add-on management pages later on.

**Comment by brampitoyo** [comment]
Great. I’ve taken out the image selection step out of the submission process.

**Comment by eviljeff** [comment]
The mockup here is different than the one for listed in #199 (https://cloud.githubusercontent.com/assets/51007/18494607/357437d8-7a6b-11e6-83cb-a6b12e3a22f5.png).  Can you close this issue if it's outdated or update this one and delete the mentions to listed in #199 if that is supposed to be unlisted based.

**Comment by brampitoyo** [comment]
Yes. This issue contains outdated mockup. Refer to #199 for the most updated one.
