### ISSUE TITLE
During submission flow, consider removing the “Submission Process” sidebar

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#198]
### User story
As a developer, whether my add-on is listed or unlisted, I would like its submission/signing process to proceed as quickly as possible.

### What this bug focuses on
Consider the “Submission Process” sidebar:
* When you submit any add-on other than your first one, you’d always start on step 2, because you’ve accepted the agreement a while back
* The “Upload your add-on” step is overloaded and could probably do with a little bit of splitting
* The “Select a license” step is short enough that we can contain it inside the “Describe your add-on” step

We should think about removing this sidebar or at least making it shorter and more accurate.

**Comment by brampitoyo** [comment]
With the “Submission Process” sidebar removed, we have two layout options:

### Widen the remaining column to 960px
![listed distribute](https://cloud.githubusercontent.com/assets/51007/18295741/25d2c6c8-74f8-11e6-89fe-1597c5160b2e.png)

### Keep the remaining column 640px wide and centre it on the page
![listed distribute narrow](https://cloud.githubusercontent.com/assets/51007/18295753/2aeb50e4-74f8-11e6-9ec9-75fbaac493a7.png)

**Comment by jvillalobos** [comment]
Personally I prefer the wider column because it all aligns with the menus on the top.

**Comment by brampitoyo** [comment]
I agree. I like the 960px wide layout, as well. The only side effect is long column width, which makes the text less readable.

**Comment by jvillalobos** [comment]
Closed since it's already covered by the mocks in the other issues (#199 in particular).
