### ISSUE TITLE
Add-on developers should be able to reply to older versions in a channel for an add-on

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#1980]
### Describe the problem and steps to reproduce it:
As an add-on developer, when trying to reply to an add-on version that's not the latest version in the channel (listed, unlisted) by clicking on the "Leave a reply" link, the input field for the latest version in the channel opens up instead of input for the version selected.

### What did you expect to happen?
Developers should be able to leave a reply on any version that can undergo a review, and not just the latest version.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-266)

**Comment by diox** [comment]
Was done in https://github.com/mozilla/addons/issues/1981 (had to ship both sides at the same time otherwise it would have led to weird situations where a reviewer would be able to post a reply to an older version but the developer wouldn't be able to do anything about it)
