### ISSUE TITLE
During submission flow, clearly separate the unlisted and listed processes

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#199]
### User story

As a developer, whether my add-on is listed or unlisted, I would like its submission/signing process to proceed as quickly as possible.
### What this bug focuses on
- Currently, the listed/unlisted selection is a checkbox. Let’s make this more explicit so there’s less chance of confusion
- We’re using a different validator for unlisted and listed add-ons, so it makes even more sense to split unlisted and listed
- The unlisted signing process is really short and not very similar to the listed submission process. It’s comprised validate --> reserve a slug --> download signed add-on

The bottomline is: we should make channel selection come first and lead to two paths: one to sign your unlisted add-on, the other to submit your listed add-on for review

**Comment by brampitoyo** [comment]
Here’s a mockup of current submission process if it were to be separated by unlisted/listed. This is the very first screen past the agreement.

Note how the sidebar has been taken out, as is the number of steps (this is addressed in a separate issue):

![distribute](https://cloud.githubusercontent.com/assets/51007/18261040/7d31d8b6-7447-11e6-94c9-8e5eecae2ab1.png)

If you select “Listed”, we’ll tweak a couple of things (also addressed in a few separate issues).

But if you select “Unlisted” (here labelled as “On my own server”), the we direct you to a different yet much simpler set of processes.

### First

Upload your file and pass validation:

![self-hosted upload](https://cloud.githubusercontent.com/assets/51007/18261070/cbed2c94-7447-11e6-8c44-0b9defe21581.png)

### Second
Reserve your slug URL. This is identical to the “Listing URL” field on the “Listed” submission process, so a URL has been automatically selected for you. All you need to do is confirm it:

![self-hosted confirm url](https://cloud.githubusercontent.com/assets/51007/18261076/e889b71e-7447-11e6-9561-76d63f4e7bec.png)

### Third

Your add-on is now signed and ready to download.

After downloading the file, you may wish to return to My Submissions, where your add-on has just been added to the list:

![self-hosted done](https://cloud.githubusercontent.com/assets/51007/18261093/0c68137e-7448-11e6-88ae-65b1eb027cad.png)

**Comment by jvillalobos** [comment]
Looking good!

Channel step:
* **On this site.** This version will be submitted for review so it can be published on this site.
* ** On my own.** This version will be immediately signed for self-distribution.
* These tweaks suggest that future versions can belong to a different channel. I also removed the reference to "my own server", because there are other forms of self-distribution.

Second step:
* I'd rather have these fields, pre-populated: name, description. We might want to drop slugs for unlisted add-ons in the future, so let's just keep the slug as being editable in the management pages but not in the submission flow.
* Add Notes to Reviewer (I think that's a separate issue).

**Comment by brampitoyo** [comment]
Thanks for the feedback, @jvillalobos!

Here are all the steps with corrected wording and form fields.

Note how I’ve changed the page heading slightly to make it more direct. What do you think of these?

* Distribute Your Add-on --> Where to Host Add-on
* Upload Your Add-on --> Upload Add-on
* Confirm Your Add-on URL --> Confirm Add-on Information
* You’re Done! --> Add-on Sign

### Distribute
![distribute](https://cloud.githubusercontent.com/assets/51007/18294668/13d226b6-74ef-11e6-99bf-a5b008216319.png)

### Upload
![self-hosted upload](https://cloud.githubusercontent.com/assets/51007/18294670/170da972-74ef-11e6-9db6-572737787045.png)

### Confirm Information
![self-hosted confirm information](https://cloud.githubusercontent.com/assets/51007/18294672/1beb6ed4-74ef-11e6-9dde-bee166f3cff9.png)

### Signed
![self-hosted done](https://cloud.githubusercontent.com/assets/51007/18294679/1eef0adc-74ef-11e6-98b1-7d3aba758933.png)

**Comment by jvillalobos** [comment]
Yeah, this looks good. Thanks!

**Comment by brampitoyo** [comment]
I’m summarising the listed and unlisted new add-on submission flow below. They’re identical as the above, but now you can see the screens side by side, and I’ve added the process for listed add-ons, too.

### Submit a new add-on – unlisted

![new add-on - unlisted](https://cloud.githubusercontent.com/assets/51007/18456885/b9fd3d60-79a8-11e6-9f20-0665562667ac.png)

### Submit a new add-on – listed

![new add-on - listed](https://cloud.githubusercontent.com/assets/51007/18457123/4a7e4c8e-79aa-11e6-9984-127bbefe9c9f.png)

**Comment by jvillalobos** [comment]
Should the Developer Agreement step be included also, to make sure we're not overlooking anything?

**Comment by brampitoyo** [comment]
Yes. Unfortunately, I can’t reset my account to snap a screenshot of the agreement, so I’m putting a placeholder text to note that.

### Submit a new add-on – unlisted

![new add-on - unlisted](https://cloud.githubusercontent.com/assets/51007/18494602/2fbb7964-7a6b-11e6-8e15-3404690178db.png)

### Submit a new add-on – listed

![new add-on - listed](https://cloud.githubusercontent.com/assets/51007/18494607/357437d8-7a6b-11e6-83cb-a6b12e3a22f5.png)

**Comment by jvillalobos** [comment]
* For unlisted, let's drop the Information step entirely. We get the name and description from the manifest, so we don't need developers to do anything there.
* For listed, in the Information step, let's drop the version number that appears next to the name.
* For listed, in the Information step, add a help tooltip for the Privacy Policy and Experimental fields.
* We'll want to promote the benefits of hosting on AMO on the first step. There are also some copy changes in the last step for both flows. I'll provide copy soon.

**Comment by jvillalobos** [comment]
Here's the suggested text for the submission flow: https://docs.google.com/document/d/1wMF2F13yfsquymQHqnjanr0vjbYF1b67kBFm6n7JqLg/edit#

**Comment by brampitoyo** [comment]
Design revised with feedback:

#### Submit a new add-on – unlisted
![new-add-on-unlisted](https://cloud.githubusercontent.com/assets/51007/19226961/31e24674-8f0f-11e6-99ab-f38ff4938fa2.png)

#### Submit a new add-on – listed
![new-add-on-listed](https://cloud.githubusercontent.com/assets/51007/19226965/360e7d1c-8f0f-11e6-9526-5095860db040.png)

**Comment by eviljeff** [comment]
btw, the unlisted flow in the revised design includes the old copy for the distribution question radio buttons.

**Comment by brampitoyo** [comment]
@eviljeff Whoops. I’ve missed that one. The mockup up above has been revised. Thanks for the keen eye.

**Comment by brampitoyo** [comment]
The design for this issue is finished and we’re now ready to implement it.
