### ISSUE TITLE
Theme reviewer emails not working

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons#2003]
When a theme creator replies to a reviewer's approval or rejection, the reviewer is not being alerted to the response. The only way the reviewer can see a theme creator's response is if they manually go back into the review page and find a note. This is problematic for a number of scenarios, but most commonly when a reviewer may have misinterpreted a theme creator as a "spammer" and rejected their submission, but the creator responds proving they're not a spammer, yet the reviewers are receiving notifications of a response and thus often miss the communication entirely. 

diox

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-271)

**Comment by devaneymoz** [comment]
@diox That should suffice, thanks!

**Comment by diox** [comment]
Thanks, closing then.
