### ISSUE TITLE
Admin tools: Slow user profile detail page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#2011]
Opening `admin/models/users/userprofile/<ID>/change/` (GET request, not changing the instance) is quite slow on prod, even profiles with very few related data takes 7 seconds to load.

Quick feedback from diox over slack:

_"...I see duplicated/useless queries ...(... I don't see assertNumQueries tests for it)"_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-299)

**Comment by alexandruschek** [comment]
Hello,

I checked this admin/models/users/userprofile/<ID>/change/ on DEV and STAGE ENV. 
I used 15 profiles for each env:
Timings were between 295 ms and 687 ms (on both env's only  one case was at 600 ms, did not notice anything out of the ordinary on the profile)

Marking this as verified fix. Thank you!
