### ISSUE TITLE
Only the most recent review for an add-on from a single account should count or be displayed

### ISSUE THREAD

**Issue by mconnormoz** [mozilla/addons#203]
Following up from e-mail.

Submitting multiple identical reviews for Ghostery (as an example) will stack (so a dozen 1-star reviews is enough to drag down the rating, as well as push all other reviews off the main page, and below the fold on the reviews page).  

This is sub-optimal, for the following reasons:
- Changes to the add-on (for good or ill) should be more immediately reflect.  Something that used to be good shouldn't be propped up by prior reviews if it's bad now.
- One user can single-handedly skew ratings through this sort of spamming
- One user can stack the front page to displace other reviews

Expected behaviour:
- Most recent review should be the only one that counts, as that reflects the user's most recent assessment of the add-on.
- Most recent review should be the only one viewable on default pages.
- Previous reviews should be viewable by users (this works correctly for some add-ons, but doesn't seem to work for the spammers hitting Ghostery), but not show up by default or be included in rating calculations.

This seems to be inconsistent, as I've seen what seems like the correct behaviour show up on other add-ons, so this may be a weakness in AMO where duplicate submissions aren't de-duped.  I'd be surprised if de-duping was a new feature.

**Comment by muffinresearch** [comment]
@jvillalobos I think this one could use product review for consideration for any future overhauls to how ratings and reviews are handled.

**Comment by diox** [comment]
> Most recent review should be the only one that counts, as that reflects the user's most recent assessment of the add-on.

That has been implemented. https://github.com/mozilla/addons-server/issues/5059

> Most recent review should be the only one viewable on default pages.
> Previous reviews should be viewable by users

That has always been the case, for a very long time. We show a link to previous reviews on this add-on by the same user in such cases.

**Comment by muffinresearch** [comment]
@diox, thanks for the updates.
