### ISSUE TITLE
Allow direct flagging of spam/abusive comments.

### ISSUE THREAD

**Issue by mconnormoz** [mozilla/addons#204]
### What did you do?

Saw a spammy review, wanted to flag it.

### What happened?

Had no way to flag that review for moderation/deletion.

### What did you expect to happen?

Have a way to report a comment without sending email with links.  If it's been flagged multiple times, it should likely be hidden until either restored or removed.

### Anything else we should know?

Maybe there should be an account flag allowing hiding for non-admins.  If you flag enough comments that get deleted, we can automatically or manually set the flag so when you flag it gets immediately hidden.

**Comment by jvillalobos** [comment]
You can flag reviews for moderation from the all reviews page: https://addons.mozilla.org/addon/ghostery/reviews/

Each review should have a "Report this review" link.

What you mention under "Anything else" should be a separate issue.
