### ISSUE TITLE
License field misattributed to Jason Savard

### ISSUE THREAD

**Issue by fwenzel** [mozilla/addons#206]
### What did you do?
Whenever I upload a new version of my add-ons I see this:

<img width="374" alt="allj" src="https://cloud.githubusercontent.com/assets/87232/18337604/df598908-7546-11e6-8115-26c4aa17e8dc.png">

### What happened?
*Copyright Jason Savard*?? I don't know who that is or why that would show up there or why I would be unable to change that.

### What did you expect to happen?
Not *Copyright Jason Savard* 😆 

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/en-US/developers/addon/copy-url-252534/versions/1929799

**Comment by fwenzel** [comment]
CC @tofumatt for general lulz

**Comment by fwenzel** [comment]
Also the Details link points to http://www.mozilla.org/MPL/MPL-1.1.html

**Comment by tofumatt** [comment]
o_O That is weird.

**Comment by diox** [comment]
We copy the license information from the current version. All your previous versions have licences in several different languages, and for each, the en-US translation is "Copyright Jason Savard", so that's what you end up with by default when creating a new version.

**Comment by diox** [comment]
Also, note that you can change this in "Manage authors & License" from the sidebar.

**Comment by fwenzel** [comment]
> All your previous versions have licences in several different languages, and for each, the en-US translation is "Copyright Jason Savard"

lolwut

**Comment by fwenzel** [comment]
Thank you I changed that for the latest version. How do we change it for all of the previous versions?

Note that I am saying this was almost certainly at some point caused by a bug in AMO. I still don't know who that is, but googling tells me he is [another extension developer](https://jasonsavard.com/).

**Comment by fwenzel** [comment]
9700 results https://www.google.com/?gws_rd=ssl#q=site:addons.mozilla.org+jason+savard

**Comment by fwenzel** [comment]
Also my crystal ball tells me that this might have happened when add-ons were licensed as MPL 1.1 and then you removed that option from the list. But that's pure speculation.

**Comment by diox** [comment]
Yeah, I suspect it's a old issue from before my time - I couldn't find such a migration in the code, but https://bugzilla.mozilla.org/show_bug.cgi?id=605423 looks related... and it's 3 years and 6 months old :(

It's clearly bad. Gotta deep deeper, not entirely sure what's going on. Hopefully at least these are different translation instances and we can remove them without any nasty consequences...

**Comment by EnTeQuAk** [comment]
This isn't fixed yet, I just merged the script that does fix it and we'll test it on dev and stage and will run it against production beginning next week once we can make sure that we don't make things worse.

**Comment by EnTeQuAk** [comment]
This is now fixed in production for all add-ons that were affected. Please feel free to re-open anytime if there are still some problems related to this.

**Comment by fwenzel** [comment]
It appears so! Thank you!
