### ISSUE TITLE
PluginContainer.exe memory leak issue? [is this the wrong place?]

### ISSUE THREAD

**Issue by MjolThor** [mozilla/addons#207]
I typically have Firefox open all of the time with multiple running tabs (large websites) and usually a tab of Netflix in the paused state.  I feel like it should be known that my computer is a beast also and should have no problem handling it, and it doesn't usually.

After firefox and the tabs are open for around 12 hours I find in task manager that the firefox.exe is like 14000000000k  and there's multiple plugin container. 

Now usually I notice the leak because the brower's basic functions (tab closing animation, idk things that are native to the BROWSER) become halted and sluggish. 

Also when I close the browser by clicking the X I find that in task manager the 1400000K number decreases slowly but doesn't always go away and I have to kill it (in task manager) to start firebox anew. 

If this actually is in the right place and someone cares PLEASE respond I'd simply like to improve my favorite web browser.

**Comment by tofumatt** [comment]
Hi there. Sadly this isn't the place to report issues in Firefox, but more in the Firefox Add-ons ecosystem. You can report bugs in the browser itself here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox, though you'll likely want to provide lots of information like which add-ons you have installed (sometimes they might be causing the slowness, not the browser itself), and your platform, specs, etc.
