### ISSUE TITLE
`blog-utils` embeds a lot of icons in the CSS

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#2088]
This is kinda expected because the webpack config is written so that images are embedded in the CSS so that it is easy to import/use in `addons-blog` but we should probably revisit this. We should investigate how to not embed icons in the CSS anymore in `blog-utils` and how that would work in `addons-blog` and its asset pipeline.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-374)

**Comment by diox** [comment]
Need to double-check but I think this was fixed by removing _all_ the embeds from the CSS, though maybe blog-utils was not touched when I did that.

**Comment by diox** [comment]
Yeah, this was done in https://github.com/mozilla/addons/issues/14611

One small nit is that blog-utils stylesheet is referencing its own copy of the icon assets, but since it's a separate build it makes sense.
