### ISSUE TITLE
 synchronization problem

### ISSUE THREAD

**Issue by RaiderHere** [mozilla/addons#209]
### What did you do?
(Please include as many details as possible.)
I use synchronization on three devices. one of them - android.
Long enough everything worked perfectly. All devices had identical tabs.

### What happened?
It began somewhere at the beginning of a year.
Tabs on each device began to lead own life. New tabs ceased to appear on other devices, and old ceased will be removed. Now at each device the personal set. Even after reinstallation of an operating system and an input in synchronization it somehow tightens that set of tabs which was before on the device.

### What did you expect to happen?
It would be desirable that everything worked according to the old diagram. And also there were more tools for control of tabs in the account of synchronization. Today they can't be controlled in any way.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by andymckay** [comment]
I think you might be talking about Firefox Sync. This repository is about add-ons, you'll probably need to add it bugzilla here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services. There's not much we can do about it here so closing. Sorry about that.
