### ISSUE TITLE
Show license of the extension in about:addons

### ISSUE THREAD

**Issue by Mte90** [mozilla/addons#211]
### Describe the problem and steps to reproduce it:
Go on about:addons and open an addon the license is not showed but on addons.mozilla.org is available.

### What happened?
An user cannot see that is the license but is very important to improve the transparency in Firefox.

### What did you expect to happen?
Under the website in the extension page inside firefox the info about the license of the extension

### Anything else we should know?
I got this issues by a meeting with John Sullivan (https://twitter.com/johns_fsf) of FSF.
I think that is also a simple issues to resolve.
I talked with @wagnerand about it.

**Comment by andymckay** [comment]
Which part of about:addons? The listing of add-ons that you've got installed, on the discovery pane, on the search or somewhere else?

**Comment by Mte90** [comment]
In the page of the addon inside about:addons, there are info about the webiste and the date of the last update, i think that here is the right place.

**Comment by andymckay** [comment]
Ah that page. Sorry to say that page is in XUL and hence inside mozilla-central. We'd need a bug filed in Bugzilla under Toolkit > Addons Manager for that.

**Comment by Mte90** [comment]
@wagnerand suggested to open a ticket here to understand what are the next steps, but I am opening now the ticket on bugzilla too.

**Comment by Mte90** [comment]
As I can see there is a bug very old about it https://bugzilla.mozilla.org/show_bug.cgi?id=624602

**Comment by muffinresearch** [comment]
Since the issues and bugs for the addons manager are handled in bugzilla I'm going to close this in favour of the existing bug linked in https://github.com/mozilla/addons/issues/211#issuecomment-247570557
