### ISSUE TITLE
My "Share Button for Pinterest" isn't Sharing

### ISSUE THREAD

**Issue by rabst** [mozilla/addons#212]
I right-click a picture online to share, select "Share on Pinterest" from the menu that pops-up, and ... nothing. (when it usually opens a window asking 'which folder to share in' and 'if I like the text the picture uses.)

Then I click the button, a grid of pictures opens, I click the "Share"-button that appears when I mouse-over the picture I want to share, and ... nothing. (again ... same expectation)

**Comment by andymckay** [comment]
The authors of that add-on aren't following this repository.

I think you might be using this add-on: https://addons.mozilla.org/en-US/firefox/addon/pinterest-pin-button/

If you are, on the right of that page there is a "Support E-mail" link  and that will get you in contact with the add-on author and they might be able to help you out. If you can tell them any additional information like the version of Firefox you are using and the operating system, that might help.

Sorry about that and I hope it can be sorted out.

**Comment by rabst** [comment]
Thanks. I think it got fixed on the next update.

Date: Thu, 15 Sep 2016 16:42:33 -0700
