### ISSUE TITLE
Theme not showing up in search

### ISSUE THREAD

**Issue by groucho7** [mozilla/addons#213]
When I open your web page at [(https://addons.mozilla.org/en-US/thunderbird/addon/fountain-pen)] in Firefox and click **+Add to Thunderbird** it adds the theme to **Firefox**, not to Thunderbird. When I go to the author's website at [(http://vanillaorchidstutorials.blogspot.co.il/p/contact.html)], fill out all the required fields and click SEND, nothing happens.

**Comment by andymckay** [comment]
Have you tried accessing the theme in Thunderbird instead of Firefox?

**Comment by groucho7** [comment]
How do you access a theme in Thunderbird?
The way I know to install a theme in TB is to download it first (see [http://www.wikihow.com/Install-Thunderbird-Themes]).
The theme page does not have a Download button (see [https://addons.mozilla.org/en-US/thunderbird/addon/fountain-pen/]).
Thanks.

**Comment by andymckay** [comment]
Open Thunderbird, got to Tools > Add-ons. Enter "Walnut" into the search box. Click install.

**Comment by groucho7** [comment]
Yeah, that works fine for the **Walnut** theme but, as you may have noticed, this page is about the **Fountain Pen** theme. Searching for "Fountain Pen" in the Add-ons Manager tab yields 0 results.

**Comment by andymckay** [comment]
Altered bug title appropriately.

**Comment by diox** [comment]
Search from add-ons manager tab directly does not work for lightweight themes, that's a limitation of the legacy API + add-ons manager search handling. 

To work around it you can use Tools -> Add-ons, then click "See All" in the Featured Themes section, which opens a page in a new tab in Thunderbird. Search in that page works correctly.
