### ISSUE TITLE
Please provide examples of renew hook RENEWED_LINEAGE and RENEWED_DOMAINS values

### ISSUE THREAD

**Issue by jwm** [mozilla/addons#216]
Thanks for all your work on Let's Encrypt, it's fantastic!

I wrote a renew hook that would only be triggered by a certain domain. Renew hooks are a little tricky to get right since they get called infrequently (only at renewal time, usually every couple of months).

I assumed the lineage directory (`RENEWED_LINEAGE`) was `/etc/letsencrypt/live`, but it's really `/etc/letsencrypt/live/$domain`.

It would be awesome if the CLI help for `--renew-hook` had example values for these environment variables. It would give hook authors more confidence that they've got their code right.

Perhaps something like this:

```
the shell variable $RENEWED_LINEAGE will point to the config live subdirectory
(for example, "/etc/letsencrypt/live/example.com") containing the new certs and
keys; the shell variable $RENEWED_DOMAINS will contain a space-delimited list
of renewed cert domains (for example, "example.com www.example.com").
```

**Comment by jwm** [comment]
I totally wrong-windowed this, sorry! :smile:

**Comment by tofumatt** [comment]
Darn I was about to jokingly say this issue was a dupe of an existing add-ons bug! 😉
