### ISSUE TITLE
Rumola does not work

### ISSUE THREAD

**Issue by GianniApps** [mozilla/addons#217]
Hello

I'm trying to install Rumola with Firefox 48.0.2 but FF tells me that it cannot be used. What is happening?

**Comment by jvillalobos** [comment]
What exactly is Firefox saying when you try to install it? Are you referring to [this add-on](https://addons.mozilla.org/addon/rumola-bypass-captcha/)?

**Comment by GianniApps** [comment]
Hola Jorge
 
Don't know what happened but now it's working well. Maybe the System
required a restart.
I'm using the add-on from rumola.com
 
Regards
Gianfranco

 
  _____

**Comment by GianniApps** [comment]
Hi

 

Is Rumola really not working anymore with Firefox?

 

It seems that my emailadress g.giudice@balcab.ch <mailto:g.giudice@balcab.ch>  has alsow been removed from your database.

 

Regards

Franco
