### ISSUE TITLE
Provide arm64 docker images

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#2183]
On Macs using the Apple Silicon arm-based architecture, Docker raises warnings for several containers about performance impact.

Can we provide arm64 images for Apple Silicon users?

![](https://user-images.githubusercontent.com/873258/218821946-1525c974-afd4-47b7-bba9-95fece1796cc.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-474)

**Comment by diox** [comment]
Wontfixing like https://github.com/mozilla/addons/issues/1919
