### ISSUE TITLE
Remove code handling categories with an application

### ISSUE THREAD

**Issue by diox** [mozilla/addons#2195]
Once https://github.com/mozilla/addons/issues/4579 is live, addon API responses will always contain a flat list of categories and categories will no longer have an application property, so we'll be able to simplify the work done in https://github.com/mozilla/addons/issues/14685, removing the compatibility hacks with the old responses we still have (`selectCategoryObject` + some conditions in the categories reducer)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-462)

**Comment by diox** [comment]
This should be transparent to end-users: categories should be displayed correctly on /en-US/firefox/extensions/ and /en-US/firefox/themes/ pages, viewing the individual category pages (which leads to a filtered search) should still work, related categories should still be displayed on add-ons detail page.

**Comment by ioanarusiczki** [comment]
Lgtm. Verified on AMO dev.
