### ISSUE TITLE
Send the name of the reported addon to abuse api if installed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#2198]
When using the feedback form the report is sent in [abuse reports admin](https://addons-internal.stage.mozaws.net/en-US/admin/models/abuse/abusereport/) without the Name being displayed 

Note:
This is not reproducible when sending from AMO abuse reports (as currently on -stage or -prod) the old form

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-459)

**Comment by diox** [comment]
https://github.com/mozilla/addons/issues/14807 should have fixed this (in Nightly only for now, since it depends on a new API in Firefox)
