### ISSUE TITLE
Error while submiting extension for review

### ISSUE THREAD

**Issue by Mevoked** [mozilla/addons#22]
I am having a browser extension which is already published in Chrome Webstore. I tried to submit the extension in Mozilla developer hub for review. The error showing while uploading the extension is 
"Your add-on failed validation with 1 error.  WebExtensions aren't allowed yet"
How can i submit the extension for review? Users can't install the extension as it is a live extension used for study purpose. Any help would be appreciated.

**Comment by jvillalobos** [comment]
Submission of WebExtensions to AMO is being tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1210037

As for installing unsigned extensions, there is some documentation here: https://wiki.mozilla.org/Addons/Extension_Signing
