### ISSUE TITLE
Regarding autocomplete in webform textfield

### ISSUE THREAD

**Issue by ravalajaya** [mozilla/addons#220]
![autocomplete](https://cloud.githubusercontent.com/assets/22330131/18686599/177bf1ce-7f9a-11e6-93d5-d298c56d3c56.png)
when i type some text in web form text field, i am getting drop down from history for re-use its ok but question is that when i will type some text in web form text field, the suggested autocomplete text will fill as auto complete in my text box just like when i type in url bar, the suggested auto complete text displayed with blue highlighted text with dropdown

benefit 
not require mouse or down arrow in drop down

**Comment by andymckay** [comment]
Sorry, not sure what this has to do add-ons? Is this a suggested feature for Firefox?

**Comment by ravalajaya** [comment]
ya suggested

**Comment by andymckay** [comment]
I'm sorry, but this repository is for add-ons and not Firefox features. I would suggest filing a bug in Bugzilla in Firefox: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox.

**Comment by ravalajaya** [comment]
thanks dear
