### ISSUE TITLE
Update wrong platform copy in add-on details pages when client app is "android"

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#2205]
### STR
1. Browse an AMO detail page, e.g. https://addons.mozilla.org/en-US/android/addon/youtube-recommended-videos/, **with Firefox Desktop** (client app in the URL must be "android", not "firefox")
1. Observe the yellow banner below the add-on summary

### Expected
Similar to what we've done in mozilla/addons#14748, we should probably allow users to download Firefox for Android from there.

### Actual
![Screenshot 2024-01-10 at 09 49 33](https://github.com/mozilla/addons-frontend/assets/217628/b52491ed-a6a1-481a-bfdb-96c30e2d1cad)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-452)

**Comment by willdurand** [comment]
Not sure why I added these labels back then. Anyway, we can reuse the copy from https://github.com/mozilla/addons/issues/14748 and get that issue fixed.

**Comment by ioanarusiczki** [comment]
Verified on AMO dev (Win10)

![correct message](https://github.com/mozilla/addons/assets/33448286/97ea0374-e42d-4cfa-936a-6546504528ad)
