### ISSUE TITLE
Show the "not actively monitored" banner on Android as well

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#2207]
### Describe the problem and steps to reproduce it:
If I am reading https://github.com/mozilla/addons-frontend/blob/dbaccfefecebb538e9ea5462c7fed9fd7c971849/src/amo/components/InstallWarning/index.js#L89 right...

### What happened?
...we are not showing the "not actively monitored" banner on android at all.

### What did you expect to happen?
...we should show that banner, under the same (other) conditions like we do on desktop.

### Anything else we should know?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-450)

**Comment by abyrne-moz** [comment]
This refers to the banner in the screenshot.  
![image](https://github.com/mozilla/addons/assets/167891594/ad9c3300-9162-4ccf-893e-c55bec84f96a)

On Desktop, this is used as a differentiator between some add-ons Add-ons Operations have pre-reviewed (for example Recommended Extensions) and the rest. That means when the banner is not shown, users know this is safe to install.
If this banner is not present for any extension on Android, users might mistakenly assume the add-on they look at has been reviewed

**Comment by diox** [comment]
Some background: back when we introduced that banner, we ran an experiment first to see the impact. At the time, we only showed recommended add-ons on Android, so this banner was not necessary there, and including Android users in the experiment was skewing the data. So we explicitly prevented it from being shown on Android in https://github.com/mozilla/addons/issues/13410.

Now that we have general availability of add-ons on Android we should show the banner here as well for consistency as explained in https://github.com/mozilla/addons/issues/2207#issuecomment-2109713581

**Comment by KevinMind** [comment]
Would have been good to include a screenshot of what you should expect to see.

<img width="889" alt="image" src="https://github.com/mozilla/addons/assets/19595165/59cc23ef-a6d9-428c-9ad2-dca429d379a2">

**Comment by ioanarusiczki** [comment]
Verified on AMO dev - I tried with UA ` Mozilla/5.0 (Android 14; Mobile; rv:128.0) Gecko/128.0 Firefox/128.0` 

From a Redmi Note 4 with Android 7.0 

![from small device](https://github.com/mozilla/addons/assets/33448286/fba18cac-f288-44df-a0d0-905ed201ba34)
