### ISSUE TITLE
Allow HTML Temp: freezes T-bird if a "mailto:" link is clicked in the displayed HTML

### ISSUE THREAD

**Issue by Marmotian** [mozilla/addons#223]
### Describe the problem and steps to reproduce it:

Allow HTML Temp v3.7.4
Thunderbird v45.3.0
XP SP3

Mail open in a separate window
click "Allow HTML Temp" button
click on "Mailto:" link
### What happened?

Main window closed
Mail window displaying HTML stays open
2 cases:
1. close Mail window, TB stays running with no windows
2. click on link in Mail window again, Mail window closes, TB stays running with no windows
### What did you expect to happen?

"Write: ..." window should have opened
### Anything else we should know?

Clicked on link "Sent by info@lifesciencesbc.ca in collaboration with" in attached email
(routing headers and names scrubbed from email)

[LSBC Weekly Events Newsletter'eml.txt](https://github.com/mozilla/addons/files/486085/LSBC.Weekly.Events.Newsletter.eml.txt)

**Comment by andymckay** [comment]
This issue tracker is for issues about the add-ons site. If you are talking about this add-on:

https://addons.mozilla.org/en-US/thunderbird/addon/allow-html-temp/?src=search

Then there is a support link on the right hand side which points to this site:

https://www.thunderbird-mail.de/lexicon/entry/14-allow-html-temp/?wiki/Allow_HTML_Temp_(English)

Unfortunately I can't spot anyway on that site of reporting an issue.
