### ISSUE TITLE
Install button overflow on theme pages

### ISSUE THREAD

**Issue by MaxZenk** [mozilla/addons#224]
![2016-09-24_19-59-11](https://cloud.githubusercontent.com/assets/20937664/18809926/abca2d74-8291-11e6-9f59-c5a2bb77a532.png)

**Comment by andymckay** [comment]
I wonder if this is similar to mozilla/addons-server#2398,  I wonder @atiqueahmedziad if you might know the answer here?

**Comment by atiqueahmedziad** [comment]
@andymckay thanks for notifying. 
well, not a regression from mozilla/addons-server#2398. But the easiest solution is to add `overflow: auto` in [.persona.hovercard:hover](https://github.com/mozilla/addons-server/blob/6ba4205e575d2184c98940187fd715a89794b701/static/css/restyle/restyle.less#L1639). That will bring the scroll bar inside the box if the daily user shows in multiple lines. @tofumatt any suggestion regarding this?

**Comment by tofumatt** [comment]
I suppose a scrollbar works but it's not a very elegant solution 🙁

@atiqueahmedziad that works for me though, if you could mock it up and send as a PR (and the scrollbars only appear when the content does overflow), I think it works.
