### ISSUE TITLE
WebDAV launcher disabled in firefox

### ISSUE THREAD

**Issue by krkredde** [mozilla/addons#225]
### Describe the problem and steps to reproduce it:
1. Go to page
2. Select > icon or within area of spreadsheet.
3. Select Lock to Edit.
4. Select Edit in Office.
Document opens.
5. Make edits.
6. Select save.
I see a status message looking like the file is saving and uploading.
A message appears at the top of the window stating something like, "We're sorry, but your document has failed to upload. Please try again."
Trying again has not worked for me.
Sometimes the upload works initially if I save right away and then stops after I make edits.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by tofumatt** [comment]
Sorry, but this sounds like a problem with Office from what I can tell, not an add-on.

If this is an add-on issue please tell us the name of the add-on, though we can't provide support for add-ons. For that you should contact the add-on author (sounds like... Microsoft?)
