### ISSUE TITLE
Filter "Works with" is not working

### ISSUE THREAD

**Issue by MTkavc** [mozilla/addons#226]
Hi,
The customizing options of FF are the only reason I've been using FF as my primary browser since its beginnings. Now, addons are the essence of it. Therefore, before updating my FF, I check for all my addons if they will work.

You've introduced the filter on the addons webpage, which is superb, but only if it would work as expected:
1. Not all versions are listed. My FF wants to update to FF 47, which is not listed.
2. If I select FF 49 in the filter, some addons are still marked "Not available for FF 45", which is the one I am using and not the one I filtered for.  I searched for "all in one sidebar" for this and some other (see attachment).
3. What is now missing altogehter now, is the FF version an addon is compatible with in the addon spec.

Thank you for keeping the greatest browser alive and in a good shape!

Regards,
Marjan

![image1](https://cloud.githubusercontent.com/assets/20720137/18836836/f8ea95be-8401-11e6-9bab-1d17058b86de.png)

**Comment by diox** [comment]
I agree it would be a nice feature (and the existing filters are confusing and not that useful) but at the same time it's quite a specific use-case. This is unlikely to get fixed before we revamp the front-end pages unless someone contributes a patch.
