### ISSUE TITLE
Trying to review version results in 500

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#228]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I tried to reject https://addons.mozilla.org/en-US/editors/review/magneton and got a 500.

### What happened?

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/352421/

### What did you expect to happen?

Sucessful review.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
The latest version (1.2) is pending review, so it shouldn't even be in the `guarded-addons` directory, if I am not mistaken.

@jasonthomas any ideas?

**Comment by jasonthomas** [comment]
The file system permissions are incorrect on this specific file. I suspect it is because of our docker changes to the 'admin' server that runs the cron tasks. We have a bug already filed to fix this https://bugzilla.mozilla.org/show_bug.cgi?id=1305462

**Comment by erosman** [comment]
I posted the bug here. Please merge.
https://github.com/mozilla/addons-server/issues/3616

**Comment by jasonthomas** [comment]
This should now be fixed. Can you please try again?

**Comment by erosman** [comment]
Yes.. it is working now
