### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by Akkuma** [mozilla/addons#229]
Please attach a copy of your add-on, and fill in the following information:
- Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
  New version of an existing unlisted add-on through `jpm sign`
- Whether your add-on is listed or unlisted.
  Unlisted
- The URL where you submitted the add-on.
  Via `jpm sign`
- The approximate time you submitted the add-on, with timezone.
  Multiple times yesterday around 6-7PM EST and multiple times from 12:00-12:30PM EST

[virtrufirefox@virtru.com-3.21.0.zip](https://github.com/mozilla/addons/files/496104/virtrufirefox.virtru.com-3.21.0.zip)

**Comment by muffinresearch** [comment]
@Akkuma - I'm closing this as I'm assuming it's no longer a problem. If that's not the case feel free to re-open. Apologies for not responding to this sooner.

**Comment by Akkuma** [comment]
@muffinresearch This is sort of not possible. Mozilla is now forward about having filesize limits, which it wasn't beforehand.
