### ISSUE TITLE
about:addons download counter stuck in uint max

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons#2304]
STR:
1) Go to about:addons
2) Log out if you're logged in
3) In the top-right panel, you should see  Add-ons downloaded: 4,294,967,295.

It's been pointed out to us that this is the max value for a 32bit unsigned integer.  We hit 4B downloads almost a year ago, so this number should be much larger.

**Comment by deadsquid** [comment]
stop fucking with closed tickets.
