### ISSUE TITLE
Installing the Emoji Keyboard hangs at the end of download

### ISSUE THREAD

**Issue by danielquinn** [mozilla/addons#232]
### Describe the problem and steps to reproduce it:

* I visited the addons page [the Emoji Keyboard](https://addons.mozilla.org/en-US/firefox/addon/emoji-keyboard-by-emojione/) and clicked `Add to Firefox`
* The page asked me for confirmation, I gave it
* The download started and while the status bar filled up, it just never completed:

![screenshot](https://cloud.githubusercontent.com/assets/218205/18934793/c7437be2-85d3-11e6-93cb-d3f18daf554d.png)

### What happened?

The addon never got to the install step.  It just stayed looking like that screenshot for over an hour.

### What did you expect to happen?

*Installation* ;-)

### Anything else we should know?

* This happened with this addon both in Firefox on Gentoo (v49.0b10) and on Ubuntu (v49).
* I've managed to install other plugins on both environments, but this one doesn't appear to be working.  The trouble is that I don't know if it's the addon specifically, or maybe how it's being downloaded as it never actually installs.

**Comment by muffinresearch** [comment]
The addon's description mentions installation issues specifically on linux - perhaps contact the developer for more information?

>-------Linux Installation Issues (as of 10-07-16)------
Due to installation issues, this Add-On is currently unavailable on Linux systems (Ubuntu/Kubuntu). We hope to resolve this within the next few weeks.

>Please take a moment to rate us. We'll release updates in response to feature requests and issues that can be resolved. Unfortunately certain technical hangups remain out of our control.
