### ISSUE TITLE
"downloadable font: kern: Too large subtable, table discarded"

### ISSUE THREAD

**Issue by SamB** [mozilla/addons#233]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

1. Go to https://addons.mozilla.org/en-US/firefox/
2. Open the Web Console
2. Hard-refresh (Hit reload button with shift down)

### What happened?

I get the messages:

> downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:normal stretch:normal src index:2) source: https://addons.cdn.mozilla.net/static/css/impala/fonts/OpenSans-Regular.ttf?629a55a  
> downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:bold stretch:normal src index:2) source: https://addons.cdn.mozilla.net/static/css/impala/fonts/OpenSans-Bold.ttf?5014568  
> downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:italic weight:normal stretch:normal src index:2) source: https://addons.cdn.mozilla.net/static/css/impala/fonts/OpenSans-Italic.ttf?c7dcce0  

### What did you expect to happen?

Well I was actually hoping that would happen, but that's only because I was trying to reproduce something I'd seen in the Browser Console so I could report it.

The actual expected behavior here is that the browser would not find it necessary to strip the kern table.

### Anything else we should know?

I don't know what's involved here, but it looks like [MDN had the same problem](https://bugzilla.mozilla.org/show_bug.cgi?id=1185685) and managed to get rid of it without dropping OpenSans (I checked; a bunch of OpenSans fonts came down but I didn't see a peep about kern tables), so I guess you could find out how they did it?

**Comment by muffinresearch** [comment]
Thanks the report. Reading around related bugs filed on this, I don't think there's any real impact to this warning. 

Since we're likely to overhaul fonts as we gradually replace the AMO front-end I don't think there's any action we are likely to take to resolve this warning so I'm going to wont-fix this for now.

**Comment by shehi** [comment]
After 4 years, this really needs addressing...

**Comment by kwoxer** [comment]
Same here, how to solve it, Just update the files?

![image](https://user-images.githubusercontent.com/1167229/76071578-c8fd5480-5f96-11ea-9295-84cde898fc8e.png)

**Comment by danger89** [comment]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1185685#c3

https://bugzilla.mozilla.org/show_bug.cgi?id=1211993#c2
