### ISSUE TITLE
Estonian language pack lacks even simple weekdays.

### ISSUE THREAD

**Issue by D33M0N** [mozilla/addons#234]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Normal weekdays in estonian are:
esmaspäev
teisipäev
kolmapäev
neljapäev
reede
laupäev
pühapäev

Obviously also the iterations or cases with those words also.
Two of them produce red wavy lines, like "esmaspäev" (Monday) and "kolmapäev" (Wednesday) without any reason.

### What happened?
I saw a wrong word indication red wavy line under common word.
![mozilla-estonian-bug](https://cloud.githubusercontent.com/assets/15782020/18943394/0817bb84-8628-11e6-805c-f65a1eaa2dd9.png)

### What did you expect to happen?
not to see that line

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
Language packs are usually maintained by external developers, so is this. https://addons.mozilla.org/en-US/firefox/addon/eesti-et-keele-pakk/ Please contact the developer directly by using the "Support E-Mail" link on the add-on listing page.
