### ISSUE TITLE
updating a webextension without bumping the version number gives confusing/irrelevant warnings

### ISSUE THREAD

**Issue by fiendish** [mozilla/addons#235]
### Describe the problem and steps to reproduce it:

Make a few changes to an existing webextension but do not update the version field in the manifest.
zip it up
go to "Upload New Version" on the addon website
choose the newly created .zip
get a pair of extremely confusing messages about "legacy add-ons" and "reversing the process" and "test usernames".
Only if you ignore those warnings and try to submit anyway do you finally get informed that the version number needs to be updated.
### What did you expect to happen?

Just tell me right away that the version number needs to be updated.
### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)
![confusing_messages](https://cloud.githubusercontent.com/assets/201996/18957479/46727b6c-862d-11e6-8937-7cdc98b3bed3.png)

**Comment by andymckay** [comment]
@EnTeQuAk assuming with the other changes, this is fixed now?

**Comment by EnTeQuAk** [comment]
Yeah, there a few confusing scenarios where warnings were raised needlessly. Should be fixed, if not please feel free to reopen anytime :)
