### ISSUE TITLE
Doesn't work initially but works on New Window

### ISSUE THREAD

**Issue by skylark42** [mozilla/addons#237]
### Describe the problem and steps to reproduce it:
I have installed Copy Real URL. When I first open Firefox and do a Google search, the right-click context menu does NOT show Copy real link. Nor is Copy real link there when I open a new tab. But when I select File\New Window, the option is there.  See screenshots.

![copyrealurl](https://cloud.githubusercontent.com/assets/22545863/18995750/7d0bb942-8725-11e6-80e8-9bc86b6f3633.jpg)
![extensions](https://cloud.githubusercontent.com/assets/22545863/18995749/7d0a046c-8725-11e6-8d2e-533c60ddf7a4.jpg)
![copyrealurl_new-window](https://cloud.githubusercontent.com/assets/22545863/18995751/7d19550c-8725-11e6-8760-a908ccc621f2.jpg)

### What happened?
See above

### What did you expect to happen?
I expect to see Copy real link in the right-click context menu for searches in all Firefox tabs and windows. Please do not tell me to use a more recent version of Firefox. I am on an old machine and severely memory-limited.

### Anything else we should know?
Windows XP, SP3, Firefox 40.0 with the extensions shown in the screenshot. My non-Microsoft plugins are: RealPlayer, RealDownloader, Acrobat, VLC web. I have Flash 22.0.0.209. Everything is on auto-update.

**Comment by wagnerand** [comment]
I assume this is about https://addons.mozilla.org/en-US/firefox/addon/copy-real-url/

This add-on is developed by an external developer, not by Mozilla. Please contact the developer directly.
As they didn't leave contact information, the best way to reach out to them would be to write a user review.

Thank you.

**Comment by skylark42** [comment]
You are correct, Wagnerand. I assume that becasue I had clicked on Report a bug, the report would give the name of the add-on. 

The Write a Review page specifically says **don't** use reviews to give a big report. Clicking on Report a bug takes you to the Github page https://github.com/mozilla/addons/issues/new, and clicking on Submit new issue posts to here. This is how I got here. See screenshots.
![report-bug1](https://cloud.githubusercontent.com/assets/22545863/18997837/196147b4-872e-11e6-8549-34635e5531f0.jpg)
![report-bug2](https://cloud.githubusercontent.com/assets/22545863/18997847/1df421f2-872e-11e6-9290-cf01b4958b39.jpg)
