### ISSUE TITLE
"Update Now" link on outdated Plugins takes you to "Blocked Add-on" page

### ISSUE THREAD

**Issue by peterbe** [mozilla/addons#238]
### Describe the problem and steps to reproduce it:

I have a plugin that is out of date. 
<img width="1741" alt="screen shot 2016-09-30 at 11 05 24 am" src="https://cloud.githubusercontent.com/assets/26739/18996781/9d40e172-86ff-11e6-9434-545fa7e1c49e.png">

Fine, I'll update it. So I click that link. But then I see this:
<img width="1062" alt="screen shot 2016-09-30 at 11 06 06 am" src="https://cloud.githubusercontent.com/assets/26739/18996790/a8f632e2-86ff-11e6-9cee-ddfb731b4405.png">

Now I don't know how to upgrade. 

(Note, because I was desperate I actually had to **read the text** (gasp!!) and later I found a link to [plugincheck](http://www.mozilla.com/plugincheck/).
### What happened?

As described above. 
### What did you expect to happen?

Take me to an actionable page. Something that matches the text on the link I clicked. 
### Anything else we should know?

People don't read text. Especially when they're worried about about big bold red sentences telling them they need to take _action_. :)

**Comment by kumar303** [comment]
One hacky way to fix this is just to put a banner at the top of the blocklist page saying "Visit the plugin check page to continue upgrading." Ideally we would land the user on a page they could use to upgrade on directly though.

**Comment by muffinresearch** [comment]
Since the better fix is likely to be the browser I wonder if we should move this over to bugzilla for discussion there?

**Comment by andymckay** [comment]
The URL that the add-ons manager tells Firefox to land on is from AMO. The page contains the text telling them what to do next. Could it be better sure, but given the expected lifespan of plugins at this stage, I'd say let's won't fix.

https://blog.mozilla.org/futurereleases/2016/07/20/reducing-adobe-flash-usage-in-firefox/
