### ISSUE TITLE
Hide Caption Titlebar Plus 3.14RC seems to break BBC Iplayer

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [mozilla/addons#239]
### Describe the problem and steps to reproduce it:
With this version of the AddOn installed and enabled, BBC Iplayer shows a blank screen instead of a video.

### What happened?
See above.
### What did you expect to happen?
I expected the video, or a still with a play button on it, to appear.
### Anything else we should know?
I am using Linux. I'll try going back to the non-beta version of the AddOn. Firefox 49.0.
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
Please contact the author of this add-on to report a problem.
