### ISSUE TITLE
[l10n] Untranslatable string on homepage

### ISSUE THREAD

**Issue by zelitomas** [mozilla/addons#244]
Hello,

there are some untranslatable strings in the Test Pilot promo on AMO homepage (see screenshot)

![Olympia l10n bug screenshot](https://pageshot.net/images/3a910685-ea24-4702-aa3a-2180fb57dcab)

I've reported [similar bug](https://github.com/mozilla/addons/issues/165) 2 months ago, so apparently there is something wrong with string extraction that should be fixed.

Could somebody please take a look at it?

Many thanks,
Tomáš Zelina

**Comment by muffinresearch** [comment]
@EnTeQuAk please could you check what happened here, I think somehow the last extraction + merge missed this.
