### ISSUE TITLE
“Reviews” link on about:addons sometimes open the site for other Mozilla products

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons#245]
When I click the "Reviews" links on the pages of my extensions on `about:addons`, sometimes they open https://addons.mozilla.org/xx/thunderbird/xxx, https://addons.mozilla.org/xx/android/xxx or https://addons.mozilla.org/xx/seamonkey/xxx instead of https://addons.mozilla.org/xx/firefox/xxx.

This happens randomly.

Firefox 49
KDE Neon/Ubuntu 16.04

**Comment by muffinresearch** [comment]
Is this randomly for all add-ons or just specific ones? Can you provide some examples of specific add-ons this occurs for (even if randomly in your case)?

**Comment by anewuser** [comment]
All add-ons. The first time this happened to me was maybe in April when an extension button pointing to its changelog (`.../versions/`)  [opened the corresponding `/thunderbird/` page](https://github.com/darktrojan/menufilter/issues/21) on Firefox for Windows. 

After that, this has been happening sporadically when I click on the "Reviews" link. It happened again with uBlock Origin today (on Linux) before I started this thread.

**Comment by diox** [comment]
I remember looking at this a while back and I think I fixed it, but can't find the commit. If it's still happening please re-open.
