### ISSUE TITLE
"Already added to Firefox/Already Downloaded"

### ISSUE THREAD

**Issue by rrkk** [mozilla/addons#246]
When I go to add add-ons, I am constantly confused about whether I may or may not have already added the add-on, because the **"Add to Firefox"** button is constant no matter what. I know I could go back to my extensions page and look, but I don't want to have to keep switching back and forth to see if I have an add-on already added.

_**Solution:**_
If an add-on is already added to our extensions, on **both** our _search results page_ and the _individual add-on page_, the **"Add to Firefox"** button should _either_ be:

1. **Replaced completely** with a note that says _"(Insert add-on name) is already added to Firefox"_ or _"(Insert add-on name) already downloaded"_.

2. **Greyed out and disabled** along with a note that says _"(Insert add-on name) is already added to Firefox"_ or _"(Insert add-on name) already downloaded"_.

This way it is easier and less confusing to add add-ons, and we wouldn't have to waste time trying to figure out if we have already added it or not.

**Comment by muffinresearch** [comment]
Hi @rrkk thanks for the feedback. We're already planning to add a feature along similar lines. The new front-end code we are working on will feature a button that's more aware of the install and enabled/disabled state of the add-on in question. The first versions of this will be avaible as mobile pages early next year, and then will be expanded to desktop after that.
