### ISSUE TITLE
Validator and Highlighter miss .htm files

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#247]
### Describe the problem and steps to reproduce it:

Example:
https://addons.mozilla.org/en-US/firefox/files/browse/514781/file/popup.htm#top

Above file is .htm and also includes `<script>` tags
(I am keeping a copy of the addon, in case it gets deleted)
### What happened?

The Syntax Highlighter does not activate on that file.
The validator may be !? working properly since the JS in that file is somehow obfuscated.

**Comment by andymckay** [comment]
The linter scans files ending in .htm as HTML. It does not linter <script> tags inside HTML as Javascript. WebExtension CSP currently blocks inline script and it can only be altered if they've specified that in manifest.json, which I believe shows up in the reviewer tools:

https://github.com/mozilla/addons-linter/issues/562

If you are expecting the linter to dig into <script> tags, please file a linter bug, that's quite a big, big, bug I expect.
