### ISSUE TITLE
Qauth Suggestion for AMO

### ISSUE THREAD

**Issue by satdav** [mozilla/addons#248]
What problem would this feature solve?
======================================
Since Persona is end of live can we look at the following for logging in 

Who has this problem?
=====================
All visitors to AMO 

How do you know that the users identified above have this problem?
==================================================================
as its end of life Nov I believe 

How are the users identified above solving this problem now?
============================================================
n/a

Do you have any suggestions for solving the problem? Please explain in detail.
===============================================================
Yes we look at the following for Mozilla https://auth0.com/pricing

Is there anything else we should know?
===============================================================
Can I suggest we look at auth0 as I know Air Mozilla is going to look at using this one

**Comment by tofumatt** [comment]
We moved to Firefox Accounts for AMO sign in awhile ago; all accounts on AMO are now authenticated with Firefox accounts, so I believe this should be closed.
