### ISSUE TITLE
FireDepot

### ISSUE THREAD

**Issue by itnervestolookforuntakennames** [mozilla/addons#249]
### Describe the problem and steps to reproduce it:
The site https://addons.mozilla.org/de/firefox/addon/firedepot/ offers a link to reviews.
This link is no longer working correctly. (I guess it is due to that I deleted  the version of the 
addon the only review was about.)

### What did you expect to happen?
Now that is a pity, it was the only review so far. Anyway if there is no possibility to restore the review I would expect the link which ends up with no review to be deleted?

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
Looking at https://addons.mozilla.org/de/firefox/addon/firedepot/ now there's no reviews visible. Can you check again and re-open this if it still a problem?
