### ISSUE TITLE
Uploading a beta add-on through the API

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#25]
..doesn't seem to make it beta. Can we check this works. According to the docs, something following the rules:

https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Maintenance#How_do_I_submit_a_Beta_add-on

Should become beta and there in are probably dragons.

**Comment by Standard8** [comment]
For some more context, I attempted to jpm sign & upload a new version of https://addons.mozilla.org/en-US/firefox/addon/firefox-hello-beta/ to the beta channel.

The version was `0.3.0-alpha1`. The output of `jpm sign` was:

```
JPM [info] Signing XPI: dist/loop@mozilla.org.xpi
Validating add-on [...............................................................................................................................................................]
JPM [info] Validation results: https://addons.mozilla.org/en-US/developers/upload/...
JPM [info] Your add-on has been submitted for review. It passed validation but could not be automatically signed because this is a listed add-on.
JPM [info] FAIL
```

However, when I looked in AMO, the new version was there, but it had been listed as an add-on awaiting full review, rather than a beta add-on.

**Comment by mstriemer** [comment]
We need to update [`devhub.tasks.create_version_for_upload`](https://github.com/mozilla/olympia/blob/96b670d3a0be3d1462182f0793d25346bef5bb56/apps/devhub/tasks.py#L101) to pass `is_beta`.

When uploading through the UI the validation results return whether it looks like a beta and then it provides a checkbox if it looks like one. We could either update the API to accept a  `beta` boolean or do the detection and automatically call it a beta.

Perhaps we could put the beta-ness in the URL and this can start looking like the new proposed listed/unlisted/beta changes but I'm not sure if that makes sense.

**Comment by mstriemer** [comment]
I merged https://github.com/mozilla/addons-server/pull/1706 which should fix this. Beta detection is done automatically and should detect the `0.3.0-alpha1` version as a beta. This should be on our development server shortly and on production February 25th.
