### ISSUE TITLE
Mozilla email (account) change

### ISSUE THREAD

**Issue by itnervestolookforuntakennames** [mozilla/addons#250]
### Describe the problem and steps to reproduce it:
I changed my mozilla account from firedepot@wicm.de to martin.berner@cablemail.de.

How did I do this?
I added my new email (martin.berner@cablemail.de) as owner to my addon https://addons.mozilla.org/de/firefox/addon/firedepot and next removed the old email.

Further I registered martin.berner@cablemail.de, username: FireDepot and deleted the account firedepot@wicm.de, username: firedepot.

### What happened?
So linked with my new account is https://addons.mozilla.org/de/firefox/user/FireDepot/
start at mozilla 13.10.2016, no review, 1 Add-on. All is true due to that I registered the 
new account 13.10.2016 and did not do any review since then and developed 1 Add-on.

Still when I open https://addons.mozilla.org/de/firefox/user/firedepot/ I can see the review I gave, 
my start at mozilla in february 2014 and 0 Add-on?

Therefore I tried to change the username within my new account martin.berner@cablemail.de
from FireDepot to firedepot. But that does not work and returns the error: username already in use!

### What did you expect to happen?
Would it be possible to link my former username firedepot to my new account?
(That would be great but only if ithe Add-on number would also change from 0 to 1.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
It is no desaster the way it is right now but it just would be nice to have back the real date when I joined mozilla and the review I made.

**Comment by jvillalobos** [comment]
It's not possible to merge accounts. One thing you could do is delete your old account, which should release the username and then you can change it in your new account. Or you could change the username in the old account and then change it in the new one.

None of this sounds like a bug, and would be better to discuss on the list amo-admins AT mozilla DOT org. Please follow up there if you have more questions.
