### ISSUE TITLE
Не могу загрузить обновление

### ISSUE THREAD

**Issue by davemodis** [mozilla/addons#251]
При попытке загрузить архив с новой версией расширения процесс зависает на этапе Валидация. Пробовал ждать несколько часов.
Не получается выгрузить обновление для расширения. Кнопка "добавить" неактивна.

Скриншот: http://prntscr.com/ctt706

**Comment by tofumatt** [comment]
Sorry about that!

Can you upload the add-on you are trying to validate to GitHub so we can test it ourselves?

**Comment by davemodis** [comment]
You can download add-on by this link: http://surfearner.com/static/SurfEarner3_chrome_ff_v3_3_0.zip

**Comment by davemodis** [comment]
Can you say something?

**Comment by davemodis** [comment]
Can you say something?
