### ISSUE TITLE
Unsupported extension displayed as a featured addon on frontpage

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons#253]
The "Featured Add-ons" block on the frontpage (after you click on the right arrow on the main banner) should only display extensions and themes that are still supported by the most recent version of Firefox. This theme was displayed to me even though it won't work on Firefox 49: https://addons.mozilla.org/firefox/addon/noia-fox/

**Comment by anewuser** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6733770/19447762/beffa6aa-947d-11e6-8acb-461e0d6b38ee.png)

**Comment by EnTeQuAk** [comment]
Some more information for decision making: This list is currently hard-coded and there isn't any variety in there so it's probably a bad idea to do any kind of compat checking on it. Imho that could be something for the new `addons-frontend` but also far far in the future.

**Comment by wagnerand** [comment]
This is relevant to @sdevaneymoz.

**Comment by muffinresearch** [comment]
I don't see the same content for Featured, so it suggests we serve different featured add-ons based on data passed in the URL.

@newuser, you were having other troubles here [1] which might also relate to data pulled from your user-agent string. Any chance you can provide your User Agent string (you should be able to find it in about:support) so we can see if we can reproduce the same issues you're seeing?

[1] https://github.com/mozilla/addons/issues/245

**Comment by anewuser** [comment]
Just to make it clear, I get suggestions for different add-ons every time I reload the page with <kbd>Shift</kbd> + clicking on the reload icon. The list isn't always the same. However, that theme did appear again to me on a different day, as you can see in the above screenshot.

My user-agent: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0` (https://launchpad.net/~plasmazilla). 

[The other bug you mentioned](https://github.com/mozilla/addons/issues/245) has affected me on Windows too before.
