### ISSUE TITLE
Uploading add-on failed with error: "/incognito" should match pattern "^spanning$"

### ISSUE THREAD

**Issue by jesperkristensen** [mozilla/addons#254]
### Describe the problem and steps to reproduce it:
I am trying to upload this add-on to addons.mozilla.org:
https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/tree/8d2110436854f77186053da11d5fb47c0d9d9747/addon

### What happened?
Uploading failed with the error message:
Your add-on failed validation with 1 error.
    "/incognito" should match pattern "^spanning$"

### What did you expect to happen?
The add-on should be uploaded without an error. I have uploaded previous versions of my add-on with the same manifest.json file, except only the version number changed, and back then addons.mozilla.org did not complain about the incognito property in the manifest.json file.

### Anything else we should know?
My manifest contains incognito:split, because the add-on cannot work in Google Chrome in their incognito mode without this value. If I set the value to incognito:spanning, then Chrome will refuse to load any tabs containing my extension pages, and will instead show an error message containing the code ERR_BLOCKED_BY_CLIENT. I know Firefox does not support incognito:split mode, but my add-on works fine in Firefox because Firefox just ignores the incognito:split property in the manifest and uses the spanning mode. My add-on code is written to work in both modes, and Firefox does not have the same limitation as Chrome where add-on tabs cannot be opened in incognito windows when using spanning mode.

addons.mozilla.org should be fixed to only warn about the incognito:split property in the manifest, and not completely block uploading the add-on, since Firefox can load the add-on just fine.

**Comment by EnTeQuAk** [comment]
Hmm, this got introduced in 40c44d0347d1b3cb6c18d0ff7a5e6e99baf23eb6 which was quite some time ago and is probably referring to https://hg.mozilla.org/mozilla-central/file/tip/toolkit/components/extensions/schemas/manifest.json#l87 though the schema in addons-linter doesn't appear to support any kind of warning while validating the schema.

cc @tofumatt @muffinresearch to get some more insight here but it seems `ajv` doesn't easily support any kind of warning mechanism but maybe I'm blind.

**Comment by andymckay** [comment]
The intention is to fail it from loading completely if I read https://bugzilla.mozilla.org/show_bug.cgi?id=1280027 correctly. Currently its a warning though. That bug just hasn't landed yet, @jesperkristensen maybe might make sense to see the comments on that bug and https://bugzilla.mozilla.org/show_bug.cgi?id=1277686. Also cc @bobsilverberg.

**Comment by jesperkristensen** [comment]
Thanks for the pointer. I have now commented in that bug.

**Comment by EnTeQuAk** [comment]
Closing this bug then if it's supposed to fail loudly. Correct me if I'm wrong though.
