### ISSUE TITLE
Toggle Word Wrap 1.10 blocks sending of email and saving composition to drafts on window close in Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 SeaMonkey/2.46; Build ID: 20161005013219 

### ISSUE THREAD

**Issue by mrmazda** [mozilla/addons#255]
### Describe the problem and steps to reproduce it:
1-Update from SM 2.40 to latest 2.46 built with GTK2
2-compose plain text message
3-try to 
a-send, or
b- close composition window aka save to drafts

### What happened?
absolutely nothing

### What did you expect to happen?
a-successful send, or
b-draft added to drafts folder

### Anything else we should know?
disabling Toggle Word Wrap 1.10 and restarting SM permits send to work as expected

**Comment by muffinresearch** [comment]
This issue tracker is for the addons website and related services.  Unfortunately we are unable to help with requests for support relating to specific add-ons. 

Unfortunately for this specific add-on there doesn't appear to be any support information provided so I can't point you towards that.
