### ISSUE TITLE
Submitting Webextension for review shows UNAUTHORIZED error

### ISSUE THREAD

**Issue by IndrekV** [mozilla/addons#256]
I've tried to submit Webextension to addons.mozilla.com 3 times. 

It always shows error:
```
We had a problem retrieving review notes
/api/v3/addons/addon/740644/versions/1955034/reviewnotes/, UNAUTHORIZED, {"detail":"Invalid Authorization header. No credentials provided."}
```

I thought it was because I didn't have demo account credentials in the correct places, but adding credentials to notes made no difference.

Screenshot of what I'm seeing:

![screen shot 2016-10-18 at 16 17 36](https://cloud.githubusercontent.com/assets/842229/19479264/8ac02b9a-954e-11e6-9e9d-f88121f7e5eb.png)

**Comment by eviljeff** [comment]
I can see notes [here](https://addons.mozilla.org/en-US/developers/addon/toggl-button-time-tracker/versions).  Does logging out and in again fix it?

**Comment by IndrekV** [comment]
Logging out and back in again revealed the review details properly. Thank you!
