### ISSUE TITLE
API credentials work

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#259]
We found some (a lot) API credentials in the wild, because developers put them where they shouldn't be.

This meta-bug is about the following tasks:
- [ ] Add an admin page that allows revocation of API credentials for a user. Extra love from admins if there is a way to enter multiple users (we'll probably use email addresses) at once and have their credentials revoked in one step.
- [x] As a v2, we'd probably want to email affected developers automatically (when we revoke credentials using the aforementioned admin page) to let them know their current credentials don't work any longer and tell them how to access new ones, with a scary warning to not share them.
- [x] Add linter warning that matches a pattern like regexp:--api-secret[\s=]+[a-zA-Z0-9]{32,} (or similar). This could even be an error if we want to be aggressive.

~~Add a validator warning/error (same as for the linter).~~

**Comment by muffinresearch** [comment]
Managment command was added in https://github.com/mozilla/addons-server/commit/e8e5977b5ee39c2fa7532c9cbc2f7650812f90e4
