### ISSUE TITLE
How do I log out of GitHub? (Firefox/Ubuntu)

### ISSUE THREAD

**Issue by I-Heart-Unicorns** [mozilla/addons#264]
This may sound like a ridiculous question, but how do I log out of GitHub?
I can't see any logout icon or text saying "logout" or anything.
Using Firefox 49.0 on Ubuntu 16.04 LTS.
Tried to upload a JPEG screenshot, but just keep getting told "Something went really wrong, and we can't process that file" - not a very helpful error message.

**Comment by I-Heart-Unicorns** [comment]
Never mind, just worked it out. The weird thing is, when I clicked on "View profile and more" earlier, I was just taken directly to my profile, whereas now (after disabling uBlock Origin, allowing GitHub in NoScript and selecting "Never" for this site's cookies in Self-Destructing Cookies) I get a drop-down menu with "Sign out" at the bottom.

**Comment by anewuser** [comment]
This repository (mozilla/addons) is only for issues related to the Mozilla site. If you need more help with Github in the future, try this page: https://help.github.com/

You can close Github issues by using the button below the form you used to post your last comment. Please do it after posting a solution to your own questions.
