### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by jtsjazz** [mozilla/addons#265]
When I click the Nimbus Icon in the toolbar, and choose "selected area", the screen goes gray, and any selection comes up the same.  Tried uninstalling and reinstalling, closing Firefox and reopening.  Both yielded the same result. Fresh restart of computer this morning. Previously, no major issues with this add on, but this is extremely frustrating.

**Comment by tofumatt** [comment]
Sorry to hear that, but this issue tracker is for the add-ons ecosystem with Firefox. Sounds like there’s an issue with the add-on itself and you’ll need to contact the add-on developer.

Their bug tracker is in their add-on description: https://fvdmedia.userecho.com/forums/4-nimbus-products/topics/?category=4926

**Comment by tofumatt** [comment]
Sorry to hear that, but this issue tracker is for the add-ons ecosystem
with Firefox. Sounds like there’s an issue with the add-on itself and
you’ll need to contact the add-on developer.

Their bug tracker is in their add-on description:
https://fvdmedia.userecho.com/forums/4-nimbus-products/topics/?category=4926
