### ISSUE TITLE
Addon Install Error - "does not match the add-on Firefox expected"

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons#266]
### Describe the problem and steps to reproduce it:
Visit https://addons.mozilla.org/en-US/firefox/addon/os-x-dock-icon-changer/ - then click "Add to Firefox"

### What happened?
We get an error that says - "This add-on could not be installed because it does not match the add-on Firefox expected" (screenshot attached below)

### What did you expect to happen?
This used to not happen. It used to install perfectly fine. I also tried download the xpi and loading it via about:debugging and it worked for me and another user - https://github.com/Noitidart/OS-X-Dock-Icon-Changer/issues/3#issuecomment-256107797

### Anything else we should know?
Link: https://addons.mozilla.org/en-US/firefox/addon/os-x-dock-icon-changer/
Screenshot: ![](http://i.imgur.com/Qc5Jcck.png)

**Comment by wagnerand** [comment]
@jasonthomas fixed this by re-hashing the file, thank you!

**Comment by Noitidart** [comment]
Thank you @wagnerand!
