### ISSUE TITLE
Launch of FireFTP causes kernel panic on OSX 10.10.5 (iMac shut off)

### ISSUE THREAD

**Issue by olivers-muc** [mozilla/addons#267]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
Installed FireFTP Add-On and when I launch it my iMac shuts off immediately.

### What did you expect to happen?
FireFTP startup

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Pls. tell me where to find such logs on OSX 10.10.

**Comment by muffinresearch** [comment]
This issue tracker is for issues related to the addons.mozilla.org website only. We are unable to provide support for individual add-ons. 

Please contact the add-on developers to ask for support. There's support information on the details page links to http://fireftp.net/developers.html if that page doesn't help there is also an issue tracker for the add-on here: https://github.com/mimecuvalo/fireftp/issues?q=is%3Aclosed
