### ISSUE TITLE
FIREFOX KULLANICI HESABI GİRİŞ HATASI

### ISSUE THREAD

**Issue by hagmwp** [mozilla/addons#268]
SAYIN: FIREFOX YÖNETİMİNİN DİKKATİNE. 

KONU: FIREFOX KULLANICI HESABI GİRİŞ HATASI

GİRİŞ EMAIL VE ŞİFRE BİLGİLERİNİ TAM VE DOĞRU GİRDİĞİM HALDE FIREFOX KULLANICI PROFİLİ HESABIMA GİRİŞ YAPAMIYORUM. 

HESAP ADI: HÜSEYİN ALTIN - ghsswa 
EMAIL: ghsswa@gmail.com
FIREFOX KULLANICI ADRESİ: https://addons.mozilla.org/en-US/firefox/user/6664238/ 

VERDİĞİM EMAIL ADRESİM DOĞRUDUR. FIREFOX KULLANICI HESABIMIN EMAIL ADRESİMİ TANIMAMIŞ OLMASI FIREFOX İŞLEMLERİNDE HATALARIN OLDUĞUNU BELİRGİN ETMEKTEDİR. 

HATANIN DÜZELTİLMESİNİ VE TARAFIMA BİLGİ VERİLMESİNİ ARZ EDERİM. 29.10.2016 = 06.09.47. SAYGILARIMLA. 

Hesap sahibi 

HÜSEYİN ALTIN - ghsswa 
ghsswa@gmail.com

**Comment by muffinresearch** [comment]
It sounds like you're having trouble accessing your account. Accounts on AMO have been replaced by Firefox Accounts and there was a period of overlap where users were prompted to migrate their accounts.

If you create a Firefox account with the email address of your old AMO account and login with that you should find things work as expected.
