### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by ks-rainer** [mozilla/addons#270]
Please attach a copy of your add-on, and fill in the following information:

* This error occurred during the submission of a new version of an existing add-on, a new file in an existing version.

* Our add-on is listed.

* The URL where you submitted the add-on: https://addons.mozilla.org/en-us/developers/addon/keeper-password-manager-digita/versions#version-upload

* The approximate time you submitted the add-on, with timezone: 3:30 PM PDT.
<img width="1130" alt="screen shot 2016-10-31 at 3 30 18 pm" src="https://cloud.githubusercontent.com/assets/9003333/19873976/3682794e-9f7f-11e6-876b-3fddc8f582bf.png">

**Comment by wagnerand** [comment]
> Please attach a copy of your add-on...

**Comment by andymckay** [comment]
@ks-rainer do you have a copy of the add-on?

**Comment by Sebazzz** [comment]
Sample (you can also [build it yourself](https://github.com/Sebazzz/fiddlerfox)):

[fiddlerfox.zip](https://github.com/mozilla/addons/files/1396116/fiddlerfox.zip)

**Comment by EnTeQuAk** [comment]
@Sebazzz are you running into the same issue, can you give us a bit more information of what's going wrong? 'cause if it's something different then I'd like to open us a new, different issue.

**Comment by Sebazzz** [comment]
Hello Christopher,
It is exactly the same issue as in the screenshots of the reporter. It appears to have something to do with the zip file. I packages the attached zip via .NET native zip capability, when I zip using Windows ZIP functionality the add-on passes the validation.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________

**Comment by wagnerand** [comment]
This sounds like https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator ?

**Comment by Sebazzz** [comment]
It certainly does and probably is.

**Comment by wagnerand** [comment]
Thanks! That page has mitigation information, so you should be able to work around this. Closing the issue...
