### ISSUE TITLE
Deleting and Re-adding a file inside a version pending review causes incorrect add-on status

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons#271]
On this listing - https://addons.mozilla.org/en-US/editors/review/epub-read-the-web-offline

There is no approve button. The addon was never rejected.

**Comment by wagnerand** [comment]
This add-on had status `Incomplete` instead of `Awaiting Review`. I correct it, but we should keep it in mind and see if it happens again.

**Comment by wagnerand** [comment]
Ah, it looks like this happened because the author 1) deleted the file inside the version and 2) uploaded a new one. We allow this while the add-on has not been reviewed yet, but it seems we forget to set the correct status in step 2.

**Comment by wagnerand** [comment]
@eviljeff Since you worked on things related to submission and file upload, could you take a look and see if there is an easy fix?

**Comment by eviljeff** [comment]
There are a lot of weird edge cases with the way we currently set add-on status.  Unless it's a common thing I'd say leave it and we'll fix when function for setting add-on status covers a more complete spectrum of scenarios.

**Comment by wagnerand** [comment]
Well, apparently we already change the status to `Incomplete` when there are no files left. Why not adding a check whether the status is `Incomplete` and if so, change it to `Awaiting Review` when a file inside a version gets uploaded?

**Comment by wagnerand** [comment]
This just happened again with another add-on.

**Comment by wagnerand** [comment]
Happened again...

**Comment by muffinresearch** [comment]
@wagnerand is this still a scenario that's possible. There's been quite a few changes since this was filed?

**Comment by wagnerand** [comment]
This got fixed in a dupe issue: https://github.com/mozilla/addons-server/issues/4066
