### ISSUE TITLE
AMO Makes Excessive Demands

### ISSUE THREAD

**Issue by RDL-github** [mozilla/addons#273]
Action: Attempted to login to AMO to add review.

Result: AMO did not accept my long-standing account and required I allow it to set up a new account where AMO would use local storage on **my** computer.

Expected Result: I would expect that AMO would respect my privacy, not attempt to invade my territory and not make such disrespectful fascistic demands. 

### Effect: no more contributions to AMO from RDL or bystander. Another lost friend. Well done.

**Comment by tofumatt** [comment]
We transitioned to Firefox Accounts many months ago, so existing accounts would be migrated to Firefox Accounts. All logins require using local storage on your computer to set cookies, etc.

In the future, you should refrain from hyperbole in your bug reports as it makes it less likely for those reading to want to help. 😢

**Comment by RDL-github** [comment]
@tofumatt commented 16 hours ago

>We transitioned to Firefox Accounts many months ago, so existing accounts would be migrated to Firefox Accounts. All logins require using local storage on your computer to set cookies, etc.

You chose to use 'local storage' instead of sticking to simply visible and manageable 'ordinary' cookies.

>In the future, you should refrain from hyperbole in your bug reports as it makes it less likely for those reading to want to help. 😢

My words are a moderate reflection of your behaviour.

I don't expect help in this case. You have already made a choice which clearly demonstrates lack of consideration for your users.

Have a look at the number of extensions which developers have provided in attempts to protect us from such attempts to override our control on our own computers.

Lastly, before you start suggesting what I should and shouldn't write, I suggest you look at how long I've been around. I meant what I said.

RDL
