### ISSUE TITLE
Cannot submit review for new addon

### ISSUE THREAD

**Issue by inDream** [mozilla/addons#274]
### Describe the problem and steps to reproduce it:
I've uploaded a zip file from my chrome extension:
https://github.com/inDream/oh-my-ig

### What happened?
It navigated to 
https://addons.mozilla.org/en-US/developers/addon/oh-my-ig/submit/details
But I cannot fill in the form as all input are hidden.
![image](https://cloud.githubusercontent.com/assets/2394866/20093355/58cd3238-a5d7-11e6-835d-fef592fc2f3b.png)

### What did you expect to happen?
I can input the form and submit the review.

### Anything else we should know?
I've uploaded another time to
https://addons.mozilla.org/zh-TW/developers/addon/oh-my-ig1/submit/details
and it cause "This name/slug is already in use"
Please help me remove the duplicated one.

**Comment by andymckay** [comment]
@inDream Is this still a problem? If so could you please contact the amo-admins@mozilla.org who can clear out the duplicated extension.

**Comment by inDream** [comment]
@andymckay I can remove the duplicate one now, but I still cannot fill in the form.

**Comment by eviljeff** [comment]
I'd put money on it being a localisation issue when parsing the xpi (no name in the default locale means no form field), but I can't see anything wrong with it vs. the spec.

**Comment by jvillalobos** [comment]
Is this related to https://github.com/mozilla/addons-server/issues/3899? If so, the timing of the fix could mean this is just a matter of deleting the original submission and uploading again.

**Comment by andymckay** [comment]
@inDream do you have a copy of the zip file you are trying to upload?

**Comment by jvillalobos** [comment]
@andymckay you can find it in the [review page](https://addons.mozilla.org/editors/review/oh-my-ig) (restricted access).

**Comment by andymckay** [comment]
I can't reproduce on dev or stage. Perhaps I'm missing something.

**Comment by inDream** [comment]
@andymckay I've uploaded this zip for chrome store directly to addons site:
https://app.box.com/s/qxek7cuhk738a5h503qx756m8jqq99yj

@jvillalobos I cannot access the review page, it shown:
"Oops! Not allowed.
You tried to do something that you weren't allowed to."

**Comment by jvillalobos** [comment]
Yeah, that page is only accessible to admins and reviewers.

I deleted the temporary entry. Can you please try submitting again, and letting us know how it goes?

**Comment by inDream** [comment]
@jvillalobos I've tried resubmit but the form is still broken.

**Comment by jvillalobos** [comment]
Okay, thanks for trying. Calling this priority one because it has been blocking a developer from submitting for over two weeks.

**Comment by eviljeff** [comment]
Has anyone attempted to replicate on dev|stage(|prod)?

**Comment by andymckay** [comment]
Yes see the comment from me several days ago.

**Comment by andymckay** [comment]
By the way, I can't download the mentioned by @inDream - I get a box error about the user being out of bandwidth. I tried the add-on @jvillalobos mentioned.

**Comment by eviljeff** [comment]
ah, I forgot to mention I tried the box link and it didn't work for me either.

**Comment by inDream** [comment]
You can try this link https://drive.google.com/file/d/0B0gdEuxBuiZLVkpMNDBYTzdRSms/view

**Comment by andymckay** [comment]
The link worked but I still cannot recreate the problem on the AMO dev server. What version of Firefox are you using? Do you have add-ons installed? Do you get any errors on the web console?

**Comment by inDream** [comment]
@andymckay I've tried Firefox 50 & Nightly 53.0a1 (2016-11-28) 64-bit without addon.
Both forms are broken with error not related:
`Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.`

**Comment by jvillalobos** [comment]
I created a new account and submitted the file in the Google Drive link. I was able to submit it without any issues. If we can't find the source of the problem, we can at least submit it ourselves and transfer the add-on to @inDream

**Comment by inDream** [comment]
@jvillalobos I've removed the old one and resubmitted now.
The bug seems fixed. Thanks everyone for your help.

**Comment by jvillalobos** [comment]
Okay, let's assume this is fixed unless/until it happens again.
