### ISSUE TITLE
"There was an error with your upload" for invalid minVersion

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#275]
### Describe the problem and steps to reproduce it:

Add-on submission fails with "There was an error with your upload. Please try again." when an add-on has an _invalid_ `minVersion`, for example `38.*` (wildcards are not allowed).

### What happened?

See above.

### What did you expect to happen?

According to @EnTeQuAk, the validation tools should give a proper error message for this.

### Anything else we should know?

Changing the `minVersion` to `38.0` (to keep the example) fixes the issue.

**Comment by EnTeQuAk** [comment]
I believe this is a duplicate https://github.com/mozilla/addons-linter/issues/931 but maybe I'm wrong. At least it's related.

**Comment by EnTeQuAk** [comment]
Also to https://github.com/mozilla/addons-linter/issues/914

**Comment by wagnerand** [comment]
Might be, but the specific example I had was a JetPack add-on, so it would rather be `amo-validator`.

**Comment by EnTeQuAk** [comment]
ah! I forgot it was a jetpack add-on, yeah, amo-validator then.

**Comment by EnTeQuAk** [comment]
I can't reproduce this anymore, both, addons-linter and addons-server seem to accept `38.*` properly. Tested on -dev and locally standalone.

![screenshot from 2017-06-23 16-11-05](https://user-images.githubusercontent.com/139033/27472639-acdc2a32-582e-11e7-9472-a0953125ba78.png)
