### ISSUE TITLE
addon download link bug

### ISSUE THREAD

**Issue by tobwithu** [mozilla/addons#276]
### Describe the problem and steps to reproduce it:
Try to download X-notifier 3.5.23 with SeaMonkey or Thunderbird in
https://addons.mozilla.org/en-US/firefox/addon/xnotifier/versions/

### What happened?
Cannot download it.
'Only with Firefox' button shows up though the version 3.5.23 is compatible with SeaMonkey and Thunderbird.

### What did you expect to happen?
Should be able to download the addon with SeaMonkey or Thunderbird.

### Anything else we should know?
X-notifier 3.5.23 is compatible with SeaMonkey and Thunderbird.
The latest version, X-notifier 4.0.1 is not compatible with SeaMonkey and Thunderbird because it is based on WebExtension API.

**Comment by Gryllida** [comment]
A subtle workaround exists, which might also help to identify the issue in the code  :) — replacing '/firefox' with '/seamonkey' as appropriate ¨fixes¨ this problem and makes the respective add-on downloadable.

**Comment by diox** [comment]
Which makes it not a bug, IMHO. If you visit a page for Firefox add-ons, you shouldn't be expected to be able to install them with Thunderbird or Seamonkey.

**Comment by Gryllida** [comment]
Well that's what I find on search engine, not my fault...

https://duckduckgo.com/html/?q=html5%20video%20everywhere

> 1. **HTML5 Video Everywhere! :: Add-ons for Firefox**
> 
> HTML5 Video Everywhere! 0.3.4 by lejenome. Replace video player with Firefox native video player. Download Now This add-on is not compatible with your ...
> 
> http://addons.mozilla.org/en-US/firefox/addon/html5-video-everywhere/
> 

And there is no easy way to switch between the firefox/ or seamonkey/ parts on the web site - do we _really_ want users to be able to guess the workaround and edit the URLs?

I even clicked the Firefox icon at http://addons.mozilla.org/en-US/firefox/addon/html5-video-everywhere/ but it didn't offer a dropdown to select another project such as SeaMonkey.

**Comment by andymckay-limited-access** [comment]
Click on the "Other Applications" link in the top.

**Comment by Gryllida** [comment]
Hi andy,

Thank you for pointing that out. I think some (perhaps a majority) users do not notice the 'other applications' link, or at least get slightly frustrated by the time they find it.

1. Can we move that link closer to the Firefox (or whatever) logo?

2. For SeaMonkey users, can we make the "Only with Frirefox' button show a 'download for Seamonkey' item in a dropdown?
