### ISSUE TITLE
Couln't install NetVideoHunter-Add-On

### ISSUE THREAD

**Issue by krawong** [mozilla/addons#277]
### Describe the problem and steps to reproduce it:
As I started my firefox 44.0.2 (on a win 7 64 bit) today, ff told me, that it has deactivated my NetVideoHunter-Add-On (cause it couldn't be verified). Other tries, with older versions of this plugin
from your website were also not successfull.

### Anything else we should know?
Verification of an add-on is nothing that I'm interested in. I need the option to allow
an add-on (yes: on my own risk), but firefox didn't let me.

**Comment by andymckay** [comment]
Details on Extension Signing are here: https://wiki.mozilla.org/Add-ons/Extension_Signing
