### ISSUE TITLE
Can not contribute : the PayPal frame is not displayed

### ISSUE THREAD

**Issue by jerome-rdlv** [mozilla/addons#278]
### Describe the problem and steps to reproduce it:

* Go to this add-on page : https://addons.mozilla.org/en-US/firefox/addon/tab-groups/
* Click *Contribute*
* Choose default contribution / type a comment
* Click *Make Contribution*
* Nothing happens, nothing appears

### What happened?

Firefox console says :

    Load denied by X-Frame-Options: https://www.paypal.com/us/cgi-bin/webscr?cmd=_dispatch-failed does not permit cross-origin framing. »

Chrome console says :

    « Refused to display 'https://www.paypal.com/us/cgi-bin/webscr?cmd=_dispatch-failed' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'. »

### What did you expect to happen?

Don’t know precisely. A Paypal popup to open ?

### Anything else we should know?

I suspected my Adblocker and tried again after disabling it, the result was the same.

It’s an old issue. I tried a first time maybe a year ago and it didn’t worked neither. That’s why I’m creating an issue here.

**Comment by muffinresearch** [comment]
@jerome-rdlv unfortunately these issue appear to be intermittent problems Paypal's end - this has happened before where they appear to serve headers that block their own iframe. Usually the problems do not persist though so I'd suggest re-trying and see if it starts working.

**Comment by andymckay** [comment]
Please see: https://bugzilla.mozilla.org/show_bug.cgi?id=896653
