### ISSUE TITLE
Signing API hangs

### ISSUE THREAD

**Issue by retorquere** [mozilla/addons#279]
I can submit a new version of my addon via the signing API and it's received without error, but when I poll the signing status I keep getting 0 files as pending signing.

**Comment by EnTeQuAk** [comment]
We saw our task queue workers crash which is why you don't see the files. We restarted them so with a bit of luck it should work shortly for you.

We're looking into why this happens.

**Comment by retorquere** [comment]
faster than ever right now.

**Comment by retorquere** [comment]
Hung again.

**Comment by EnTeQuAk** [comment]
We found the problem and are testing the fix and will deploy it to production shorty after. Please stay tuned :)

**Comment by EnTeQuAk** [comment]
This is now fixed and hopefully stays fixed.

Please feel free to reopen anytime!
