### ISSUE TITLE
When XP support officially ends, the Discovery Pane should offer a "Hotdog Stand" inspired theme.

### ISSUE THREAD

**Issue by Caspy7** [mozilla/addons#280]
After ending Firefox support for XP users, the Discovery Pane should replace the normally recommended theme with a Hotdog Stand inspired theme.
For those unfamiliar, the hotdog theme was a gaudy theme offered by Windows 3.1.
see pictures here: https://www.google.com/search?q=windows+3.1+hotdog+stand&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiWlPa276DQAhWE7yYKHQAxBx0Q_AUICCgB&biw=864&bih=439
This should only be offered to Windows XP users.

Suggested text:
Fan of outdated, insecure software?  Well then check out this blast from the past!

**Comment by tofumatt** [comment]
I think that's a bit user-hostile; not all PC users are as savvy as us tech-folks and they won't realise their software is out-of-date necessarily. There's no need to mock them.

Though a message instructing them to update their OS is an alright idea.
