### ISSUE TITLE
Review Log displays incorrect data

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#287]
### Describe the problem and steps to reproduce it:
Starting from today, the review log shows incorrect data for some entries. This issue was not present previously and I suspect has happened with the latest push on Thursday.

https://addons.mozilla.org/en-US/editors/reviewlog

### What happened?
Example:
はてブロimageTitle 0.0.1.19 was approved 	Noitidart <-- correct entry
TRAVELDoodle - URLAUBSPLANUNG 2.0 12523760: DER Traveldoodle 	DER Traveldoodle <-- incorrect data

### What did you expect to happen?
There are many such instances where the result is not posted and the name of the developer, instead of the reviewer is listed under **Editor**

### Anything else we should know?
I see 8 such incorrect entries and those started around 9 hours ago.

**Comment by eviljeff** [comment]
I think this was caused by #3914 adding logging for approval notes changes
