### ISSUE TITLE
Review Syntax highlighter Errors

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#288]
### Describe the problem and steps to reproduce it:
Previously, the syntax highlighter in review tools worked pretty reasonably. It missed some end of comment code on occasions thus sometimes extending the comments to normal code.

The code seems to be updated and now it is regularly missing the end of string, resulting in a big chunk of code showing as string (blue).

### What happened?
Incorrect highlighting which complicates the review process

### What did you expect to happen?
Correct highlighting

### Anything else we should know?
Example:
https://addons.mozilla.org/en-US/firefox/files/compare/539763...505879/file/popup.js#top

     var link = document.getElementById('ms');
	     // onClick's logic below:
	     link.addEventListener('click', function() {
	       if(document.getElementById("myText").value != "0"){
	         memVar = document.getElementById("myText").value;
	         document.getElementById("showmem").innerHTML = "M";
	       }
	     });

Highlighter interprets the apostrophe in **onClick's** as the start of the string and **link.addEventListener('** as the end.
Then it starts the next next string from **click'** and therefore the rest of the code is highlighted as string.

Furthermore, the rest of the code is reversely highlighted since the beginning and the end of the strings are swapped.

**Comment by andymckay** [comment]
@wagnerand did you change this recently?

**Comment by erosman** [comment]
New situation:

https://addons.mozilla.org/en-US/firefox/files/browse/546370/file/index.js#top

var contextMenu = require("sdk/context-menu");
	var buttons = require('sdk/ui/button/toggle');
	var Page = require("sdk/page-worker").Page;
	var panels = require("sdk/panel");

**Comment by andymckay** [comment]
This bug is closed. I'm not at all sure what your last comment is meant to address, but could you file a new bug with a description of the problem and what you expect to happen?

**Comment by erosman** [comment]
The syntax highlight code broke if there were / slashes in the strings.

However, it does not do it at the moment so it may have been fixed with the other bug.
