### ISSUE TITLE
Admin Review: Contains Editor Comment

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#289]
### Describe the problem and steps to reproduce it:
I noticed that an addon containing Editor Comment was flagged as Admin Review. 
I didn't notice any other reason present ie manual admin-flag or auto-flag due to inclusion of sources.
Is that intentional (since it does not appear to be applicable)?
ref: `https://addons.mozilla.org/en-US/editors/review/hyperocto`

**Comment by wagnerand** [comment]
Source code was uploaded for this add-on. Due to the upcoming new communication flow, we changed the behavior slightly. The log entry indicating source code submission is already in the code and will be live wit the next deployment.
