### ISSUE TITLE
problem with slug "yandex-music-fisher" during publication

### ISSUE THREAD

**Issue by egoroof** [mozilla/addons#291]
### Describe the problem and steps to reproduce it:

I am the author of open source WebExtension "Yandex Music Fisher" (https://github.com/egoroof/yandex-music-fisher).
I'm trying to add the addon to AMO with a slug "yandex-music-fisher" but see a problem "Addon with this slug already exist". I've tried to open link https://addons.mozilla.org/ru/firefox/addon/yandex-music-fisher/ but see 404 as it doesn't exist.

How can the slug be already exist? Is it some error? Could you help me please to make it free, or say which account uses this slug?

### What happened?

I see a problem "Addon with this slug already exist" during publication.

### What did you expect to happen?

Successful addon publication on AMO.

**Comment by jvillalobos** [comment]
There's an unlisted add-on that is using that slug. We can contact the developer to have them change the slug, or you can use a different slug. If you want us to contact the developer, please send an email to amo-admins AT mozilla DOT org. Since there's no issue here, I'm closing this.
