### ISSUE TITLE
Review Log links are broken for rejected versions

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#292]
### Describe the problem and steps to reproduce it:
It seems after yesterday's update, the previous issue is fixed but a new bug has appeared. 
(ref: https://github.com/mozilla/addons/issues/287)

All **rejected** addons have blank href
Examples:
```
<a href="">daoco</a> 2.0.0 <a href="/en-US/editors/review/daoco">rejected</a>

<a href="">Rite.ly</a> 0.0.1 <a href="/en-US/editors/review/ritely">rejected</a>

<a href="">Humanize</a> 1.0 <a href="/en-US/editors/review/None">rejected</a>

<a href="">Predatory Scientific Publication</a> 1.0 <a href="/en-US/editors/review/predatory-scientific-publicati">rejected</a>

<a href="">Pornolab add-on</a> 0.0.1.0 <a href="/en-US/editors/review/pornolab-add-on">rejected</a>

<a href="">Cash2viewTrafic</a> 5.0.0 <a href="/en-US/editors/review/cash2viewtrafic">rejected</a>
```

**Comment by muffinresearch** [comment]
@erosman is this still an issue?

**Comment by erosman** [comment]
I just checked ....

The reviews for May 4th still have the issue
`<a href="">Official Ice Poseidon TV</a>1.30<a href="/en-US/editors/review/official-ice-poseidon-tv">rejected</a>`

But the reviews on My 5th seems fine and fixed. 
`<a href="/en-US/firefox/addon/katorg-katcart/">KatCart</a>0.8.3<a href="/en-US/editors/review/katorg-katcart">rejected</a>`

Was there a push with a fix yesterday?
Good job..

**Comment by wagnerand** [comment]
I don't think this has been fixed.
The links are broken for add-ons where the initial version was rejected, like in the first snippet in the comment above.
