### ISSUE TITLE
Unable to submit add-on for review -- name and URL error.

### ISSUE THREAD

**Issue by rgliever** [mozilla/addons#293]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Unable to submit add-on for review. Fails at the "Submit Version for Review" stage.

Seeing "This name is already in use. Please choose another." for the add-on name, which is "vidIQ Vision for YouTube".
Also seeing "Addon with this Slug already exists."

### What happened?

Name and URL error on "Submit Version for Review" stage; unable to submit add-on.

### What did you expect to happen?

Successfully submit add-on for review.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

https://puu.sh/sFxXN/59d0aecf6b.png

**Comment by jvillalobos** [comment]
It seems an unlisted add-on was conflicting with this submission. I changed it so the name and slug should now be available. Please try submitting again.

**Comment by rgliever** [comment]
The slug seems to be fixed, but I am still having the same issue with the
name.
This also happens for variations of the name, i.e. "vidIQ Vision", "vidIQ",
etc.
[image: Inline image 1]

**Comment by jvillalobos** [comment]
Do you own [this AMO account](https://addons.mozilla.org/user/vidIQ/)? I see an incomplete submission for that account that has the name you want. I also saw a very old submission for "vidIQ", which I renamed.

**Comment by rgliever** [comment]
Yes, that's the account. I'm still trying to submit that addon for review,
but now I'm experiencing the same problem I was the first time -- the name
and slug are already taken.

-Ryan

**Comment by rgliever** [comment]
Just tried it, same result. This is exactly where I've been trying and
failing to submit the addon for review. I go to Tools > Manage my
submissions and then click 'Resume' on 'vidIQ Vision for YouTube', the only
addon in the list.

**Comment by jvillalobos** [comment]
Okay, I cleaned up a bunch of temporary and old submissions I found. Please try again.

**Comment by rgliever** [comment]
Just tried again, now I'm just getting the 'Addon with this Slug already
exists.' error

[image: Inline image 1]

**Comment by jvillalobos** [comment]
For any particular slug, or did you try different ones? Note the slug can be changed later, so getting the submission done is at least a good first step.

**Comment by rgliever** [comment]
Aha, I didn't notice I could edit the slug. I changed it to `vidiq-vision`
and I was able to successfully submit it for review. Thanks for your help!

-Ryan

On Fri, Dec 16, 2016 at 12:14 PM, Jorge Villalobos <notifications@github.com

**Comment by jvillalobos** [comment]
No problem, and sorry for this taking so long.
