### ISSUE TITLE
Thunderbird addon does not appear in search results. User review is not present.

### ISSUE THREAD

**Issue by alehro** [mozilla/addons#294]
There are two issues which look interconnected.
1. My Thunderbird addon (message notes plus) does not appear in search results in Thunderbird. That is I
open addons tab from tools menu, type "message notes plus", hit enter, search results appear but the addon is not there. But when I scroll to the bottom and click "See all 481 results" link the addon appears first in the list. I see the issue since the time I've updated addon several weeks ago. The same issue can be observed actually for old version of "message notes" addon of another author.
2. Yesterday user has left a review of the addon. I received email notification about that with a link: 
https://addons.mozilla.org/addon/messagenotesplus/reviews/833402/reply
But the link doesn't work. I see "We're sorry, but we can't find what you're looking for." page.
The review itself is not present on page https://addons.mozilla.org/en-US/thunderbird/addon/messagenotesplus

**Comment by muffinresearch** [comment]
@alehro I see this is a very old issue - is this still an issue?

**Comment by alehro** [comment]
@muffinresearch, I just tested it with my TB 45.0. The issue is still there. But I am not interested in the add-on anymore. So, I really don't care.
