### ISSUE TITLE
Daily user count dropped to zero on several days

### ISSUE THREAD

**Issue by mikel2000** [mozilla/addons#295]
Daily user count on addons.mozilla.org dropped to zero on 17/28/30th of november and 2nd of December. Please check e.g. https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30.

**Comment by jvillalobos** [comment]
@bqbn can you look into this, since Jason is out?

**Comment by jasonthomas** [comment]
The stats have been re-imported and re-indexed.
