### ISSUE TITLE
Collections Problem

### ISSUE THREAD

**Issue by VanillaOrchids** [mozilla/addons#296]
### Describe the problem and steps to reproduce it: 
I've noticed with Collections that the designs in a collection are moving around. Basically a Theme that might be on page 1 of a collection will appear on page 2 or even another page. It makes it impossible to view all the Themes available in a collection because Themes from one page show up on another. 
A Collection would have to have multiple pages in order to see it happening. 

### What did you expect to happen?
Well, the designs shouldn't keep moving around to different pages. Makes finding a design that I might be looking for difficult. I have had to go into the Edit Collection page just to view all on one page because what I was looking for wouldn't show up because of the issue.

### Anything else we should know?
I took a couple of print screens from one of my collections that showed the issue in question.
This is the collection: [Online Duplicates](https://addons.mozilla.org/en-US/firefox/collections/VanillaOrchids/z-onlineduplicates/?page=1)

Here are the print screens.
![untitdled-1](https://cloud.githubusercontent.com/assets/16947538/21122860/c58f1d42-c0a2-11e6-9c8e-053b2100303d.gif)
![undtitled-1](https://cloud.githubusercontent.com/assets/16947538/21122861/c5942954-c0a2-11e6-9c83-05f95e37fb2c.gif)

**Comment by muffinresearch** [comment]
Thanks for the report. We're in the process of overhauling the front-end and when we get to reviewing collections we'll look to bear this in mind and have collection ordering be idempotent.
