### ISSUE TITLE
Error: All add-ons require a manifest file received when one is present

### ISSUE THREAD

**Issue by holly4** [mozilla/addons#297]
### Describe the problem and steps to reproduce it:
I am trying to upload a Web Extension to addons.mozilla.org and receive an error that there is no manifest file when one is present in the archive. The manifest file passes json lint and the extension loads in development mode as a temporary Add-on.
This is a listing of the actual archive itself. I ensured that only the files are included and not the parent directory:
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2016-12-15 10:40:36 ....A         1276          570  content_script.js
2016-12-15 10:18:50 ....A         2242         2242  icon48.png
2016-12-15 08:52:36 ....A         1234          704  LICENSE
2016-12-15 11:35:06 ....A          321          207  manifest.json
2016-12-15 10:38:36 ....A          586          350  README.md
------------------- ----- ------------ ------------  ------------------------
2016-12-15 11:35:06               5659         4073  5 files

### What happened?
An error was received that there was no manifest file.

### What did you expect to happen?
That the file uploaded would be accepted.

### Anything else we should know?
Extension source https://github.com/holly4/FoxReloadBlocker
Actual zip file which I tried to upload: https://github.com/holly4/FoxReloadBlocker/blob/master/release/firefox/FoxReloadBlocker_1.0.0.zip

**Comment by andymckay** [comment]
Hmm, I've tried this add-on as linked and it worked just fine in our dev and stage instances, with no issues at all through to the end. I tried it on production (addons.mozilla.org) for the first step and it worked just fine.

So, not sure, can't reproduce any error yet.

**Comment by muffinresearch** [comment]
Based on https://github.com/mozilla/addons/issues/297#issuecomment-267441775 marking works for me. Please re-open if still an issue.

**Comment by bradhanks** [comment]
Running into the same issue https://github.com/bashvlas/zipbooks-time-tracker/tree/update

**Comment by EnTeQuAk** [comment]
@bradhanks can you link to the actual zip you tried to upload?
