### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by antonio-bakula** [mozilla/addons#298]
- add-on loads and works ok in Firefox when added as temporary add-on
- I tried to update existing add-on, it was listed, url [https://addons.mozilla.org/en-US/firefox/addon/tecaj/](https://addons.mozilla.org/en-US/firefox/addon/tecaj/)
- submitted to https://addons.mozilla.org/en-US/developers/addon/tecaj/versions#version-upload
- time was 23:12 CET 20. december 2016 
[tecaj-ext.zip](https://github.com/mozilla/addons/files/664896/tecaj-ext.zip)

**Comment by andymckay** [comment]
When trying it through the linter:

```
~/sandboxes/addons-linter/bin/addons-linter tecaj-ext.zip              
Error: invalid characters in fileName: assets\css\pure-min.css
    at /Users/andy/sandboxes/addons-linter/node_modules/yauzl/index.js:387:44
    at /Users/andy/sandboxes/addons-linter/node_modules/yauzl/index.js:517:5
    at /Users/andy/sandboxes/addons-linter/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:675:17)
```

When using the unzip command on OS X:

```
unzip tecaj-ext.zip                                                    
Archive:  tecaj-ext.zip
  inflating: manifest.json           
  inflating: README.md               
warning:  tecaj-ext.zip appears to use backslashes as path separators
```
That's probably the cause of the problem.

**Comment by andymckay** [comment]
See also #290.

**Comment by antonio-bakula** [comment]
Andy thanks for fast help ! I also used powershell call to .net method that makes the zip, changed to 7-zip and I managed to upload new version. Thanks again.
