### ISSUE TITLE
tag 'radio' becomes 'rãdio'

### ISSUE THREAD

**Issue by egoroof** [mozilla/addons#299]
### Describe the problem and steps to reproduce it:

Add a new tag 'radio' to my extension on AMO.

### What happened?

Tag 'rãdio' is added.

### What did you expect to happen?

Tag 'radio' id added.

### Anything else we should know?

I also found that there are many extensions available with tag "rãdio": https://addons.mozilla.org/ru/firefox/tag/r%C3%A3dio, but no one with tag "radio": https://addons.mozilla.org/ru/firefox/tag/radio.

**Comment by jvillalobos** [comment]
I can confirm on -dev. There must be some sort of normalization happening that matches tags regardless of letter accents. I renamed the `rãdio` tag to `radio`, so that should be fixed on the site eventually. Please confirm when this is fixed for you.

**Comment by egoroof** [comment]
It's fixed now, thanks!
