### ISSUE TITLE
Add-on rating inaccurately computed

### ISSUE THREAD

**Issue by wbt** [mozilla/addons#30]
On AMO, the average of the set containing a single 5 and no others is equal to four, with two data points:  
![average rating off](https://cloud.githubusercontent.com/assets/563406/13037571/e3b9db8e-d351-11e5-8b04-dbed41ef4842.PNG)  

And then, assuming that single rating is the only one a developer has, it averages to 3 on the [developer profile](https://addons.mozilla.org/en-US/firefox/user/wbt/):  
![overall average rating off](https://cloud.githubusercontent.com/assets/563406/13037577/22a618da-d352-11e5-963b-afe4cd146bc0.PNG)

This math seems inaccurate or at least mismatching mathematical expectations. 

Elsewhere on the page, "2 reviews" is also reported, e.g. in the upper right:
![2 reviews top right](https://cloud.githubusercontent.com/assets/563406/13037599/b8052380-d352-11e5-8793-3f6df7213bd6.PNG)  
and in the reviews box:
![2 reviews in reviews section](https://cloud.githubusercontent.com/assets/563406/13037606/dd83420e-d352-11e5-8697-e7018f58082d.PNG)  
Clicking on "[See all 2 user reviews](https://addons.mozilla.org/en-US/firefox/addon/ups-tracking/reviews/)" produces the following screenshot, which says "1 review" in one place but then just below provides a link claiming there's another:  
![1 review but previous visible](https://cloud.githubusercontent.com/assets/563406/13037612/110746b6-d353-11e5-83e5-8ab068cb875d.PNG)
and clicking on the words "[previous review](https://addons.mozilla.org/en-US/firefox/addon/ups-tracking/reviews/user:5546153)" just removes both of those sentences.  
The prior review being referred to was a misplaced support request, now removed but only partially so.  It's the "partial" bit being reported here as a bug.

**Comment by andymckay** [comment]
Duping to mozilla/addons-server#1618 which I think is the same problem.
