### ISSUE TITLE
Daily user count dropped to zero on 2016/12/19

### ISSUE THREAD

**Issue by mikel2000** [mozilla/addons#300]
Daily user count on addons.mozilla.org dropped to zero on 19th of December. Please check e.g. https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30.

**Comment by muffinresearch** [comment]
@jasonthomas @bqbn any ideas about this?

**Comment by jasonthomas** [comment]
I have re-imported and re-indexed stats for 2016-12-19.
