### ISSUE TITLE
Cannot approve addon with non-ascii id

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons#301]
### Describe the problem and steps to reproduce it:
I went here - https://addons.mozilla.org/en-US/editors/review/n%C3%A1vratn%C3%A9peniaze-sk-doplnok

Fill a message, click approve.

### What happened?
You get a Oops page

### What did you expect to happen?
It should be approved.

**Comment by wagnerand** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/375938/

**Comment by wagnerand** [comment]
Adding @bqbn. Looks like it could be an issue with trunion.

**Comment by eviljeff** [comment]
Looks like the problem is `NavratnePeniaze@NávratnéPeniaze`, i.e. its Unicode.  (I've) no idea if this is valid or not in Firefox but changing it would likely fix it.

**Comment by Anissoft** [comment]
Guys, we cannot upload new build with different ID, because "ID add-in manifest.json or install.rdf (NavratnePeniaze@NavratnePeniaze) is different than the ID supplement to the AMO (NavratnePeniaze@NávratnéPeniaze)". 
Should we create new submission?

**Comment by eviljeff** [comment]
Deleting the existing submission and creating a new one would be the easiest fix to this, yes.

**Comment by diox** [comment]
Is this still an issue with autograph ? cc @EnTeQuAk

**Comment by AlexandraMoga** [comment]
I've tried to test this by uploading an add-on with non-ascii id (similar to what was reported in the issue) and approve it afterwards  but the problem is that such ID will not pass validation:
![image](https://user-images.githubusercontent.com/31961530/37349764-ccdb3280-26df-11e8-981a-9aa163285b07.png)

@EnTeQuAk  I'm not sure how to reproduce this differently. Any suggestions?
Thank you

**Comment by EnTeQuAk** [comment]
@AlexandraMoga please try with a non ascii name instead of id, the name allows unicode characters but the ID is correctly ascii only.

**Comment by AlexandraMoga** [comment]
I've managed to submit an add-on with a unicode ID by overriding validation. I've then tried the Approve/Confirm Approval/Approve Content options and the action was successfully completed in all cases.

Here is the add-on used in my tests - https://reviewers.addons.allizom.org/en-US/reviewers/review/m%C3%A4uselein

I'm marking this as verified fixed
