### ISSUE TITLE
Signing Firefox extension update.rdf manifest file from command line, how to extract the private key from the McCoy tool

### ISSUE THREAD

**Issue by cr-nz** [mozilla/addons#306]
We still have an unlisted Firefox extension which we distribute to users via our website. Because we have a user base of several million which have installed it already, we publish updates by signing an update.rdf file with the McCoy tool which is then hosted on our servers and when the users load up their browser it checks that update file and the users get their extension automatically updated whenever there is a new version.

At the moment we have a shared build/deployment server where the developer can log in and start a build, but the signing process is a very cumbersome process with the McCoy tool GUI. First the developer must fetch the update.rdf file from the build server, then open up the tool (which doesn't work on Linux or Mac very well, so have to boot into Windows), sign the file, boot back into Linux, copy it back up to the build server. The process takes about 5 minutes and is painful.

So I have started investigating options for signing the update.rdf file from the command line. [The McCoy page](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/McCoy) lists some options. I have tried the [Uhura](http://www.softlights.net/projects/mxtools/uhura.html) tool which after installing Perl dependencies and using a random PEM file for the key and it seems to work and puts the signature in the update.rdf file. However it will be a bad signature because I really need to get the private signing key out of the McCoy profile somehow. I believe the McCoy tool creates the signing key and keeps it in there somehow and encrypts it with the password which needs to be entered on startup. The options in the McCoy tool do not seem to have a way to extract out the private key.

![keys menu](https://cloud.githubusercontent.com/assets/9664533/21785514/bac00f50-d724-11e6-97b1-afe832a3ccc3.png)
![ext menu](https://cloud.githubusercontent.com/assets/9664533/21785502/ad1d69ba-d724-11e6-9c97-212fa2ae54a9.png)
![update menu](https://cloud.githubusercontent.com/assets/9664533/21785513/babc85ec-d724-11e6-9228-f6207d2397e2.png)

So is there any way to extract out the private key as a PEM file and use it for signing?

Or do you know if there is an easier way to do signing on the command line with Linux?

Is the source code of the McCoy tool available anywhere, perhaps we can figure it out from that?

**Comment by andymckay** [comment]
The source of the McCoy tool is here: https://wiki.mozilla.org/McCoy#Source_Code

The use of the McCoy tool is out of scope for this repository, if you've got specific issues, you might be able to file them in bugzilla: https://bugzilla.mozilla.org, but I wouldn't be too hopeful in getting them fixed.

I think you know this, but just to be clear please be aware that signing with the McCoy tool is different from signing them with AMO which is needed if you want to get them runnable in Firefox.
