### ISSUE TITLE
Check for vulnerable 3rd party libs

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#308]
All AMO components make use of third party libraries. Sometimes, they contain security vulnerabilities.

For NPM modules we good pretty good coverage, as we are using Greenkeeper.
However, there are libraries not being loaded through NPM.

Ideally we would integrate a tool that does checks for us into our chain, so we don't have to do it manually.

One candidate could be [retire.js](http://retirejs.github.io/), @muffinresearch knows another one.

@psiinon might be interested in this too.

**Comment by muffinresearch** [comment]
[snyk.io](https://snyk.io/) is the one I was thinking of for node deps. I think that would work off package.json so it wouldn't help for the libs directly in the tree.

**Comment by eviljeff** [comment]
I played with retireJS https://github.com/eviljeff/olympia/tree/a308-retire-js

Somewhat mixed outcomes - it (falsely) matched the jquery-ui helper file `jquery-1-7.js` to an old version of jquery and spit out some advisories associated with that from it's [list of vunerabilities](https://github.com/RetireJS/retire.js/blob/master/repository/jsrepository.json).
That's all it finds in our code, and the modules we install from npm.  (That's good...?)

However, it says the version of jquery that DRF bundles for it's html views (that I don't believe we use anywhere), and the versions that django includes for model admin pages (in /admin) do have vulnerabilities.  Which we can't fix directly, short of monkey-patching.

Other things:
 - I couldn't tell if any generic vulnerability checking on actual code was being done - all of the matches it found were based on filename or version detection and compared against that json list.
- DRF bundles jquery-1.12.4 and package.json currently installs 1.12.0 but 1.12.0 isn't flagged as vulnerable while 1.12.4 is.  So I'm not sure if the vulnerability was only introduced between 1.12.1 and 1.12.4 or it's not correctly flagging it.

**Comment by eviljeff** [comment]
@muffinresearch does retirejs seem worthwhile including?  Either just as a make command that could be run on demand; or called in one of the travis jobs?  I'm not convinced, tbh.

**Comment by muffinresearch** [comment]
@eviljeff looks like the jquery issue is https://github.com/jquery/jquery/issues/2432 which makes it sound like the version we are using is vulnerable because anything not v3 is vulnerable to this specific issue. However, it would appear are only certain cases where that would be an issue see the bug for details.

It would be interesting to compare the output of retire with that of snyk - although I suspect some of it will be similar especially if they both use the node security data as a source.

**Comment by eviljeff** [comment]
I go at snyk a few weeks ago - it highlights a vulnerability in an upstream dependency of eslint (shelljs), but nothing in our dependencies.   I refreshed it with an up-to-date master just now and it's not complained about jquery-1.12.0 either, but I agree it's as potentially vulnerable as 1.12.4.  (Doesn't look like I can publicly share the report, but you could login with your own fork, or the owner of addons-server could enable the integration with github)

Synk has the advantage of not relying on filename matching so it's not got the false positive for jquery-1.7.js from jquery-ui, but can't notice the extra jquery files from DRF and django.
