### ISSUE TITLE
Daily user count dropped to zero on 2017/01/10

### ISSUE THREAD

**Issue by mikel2000** [mozilla/addons#309]
Daily user count on addons.mozilla.org dropped to zero on 10th of January. Please check e.g. https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30.

**Comment by EnTeQuAk** [comment]
cc @bqbn / @jasonthomas on this hoping / fearing this is an ops related problem of missing data again?

**Comment by mikel2000** [comment]
On 17th of January daily user count stats are missing too. For me there seems to be a general problem. Additionally it would be nice, if you could implement a monitoring, so these kind of problems are popping up automatically.

**Comment by mikel2000** [comment]
On 19th of January daily user count stats are missing too.

**Comment by mikel2000** [comment]
On 25th of January daily user count stats are missing too.

**Comment by mikel2000** [comment]
On 26th of January daily user count stats are missing too.

**Comment by mikel2000** [comment]
On 31th of January daily user count stats are missing too. As this happens every now and then, it would be very helpful, if somebody could solve the problem which is the root.

**Comment by jasonthomas** [comment]
This usually happens when there is a delay in processing and exporting data into AMO. I am updating the stats scripts to handle this better.

**Comment by mikel2000** [comment]
Thanks for the info. Daily user count statistics for 26th and 31th of January are still missing.

**Comment by caitmuenster** [comment]
Hi all - one of our community members in themes reported that her user count hasn't been working since February 6. 

https://discourse.mozilla-community.org/t/user-count-nit-working-since-feb-6th/13531

**Comment by wagnerand** [comment]
See also https://github.com/mozilla/addons/issues/333

**Comment by MaDonnasPersonas** [comment]
Actually it wasn't just my themes, but ALL themes.

**Comment by MaDonnasPersonas** [comment]
User count hasn't worked since sometime on Monday, Feb. 20th on all Persona themes again.

**Comment by jasonthomas** [comment]
Backfill is in progress, should be up-to-date by tomorrow.

**Comment by MaDonnasPersonas** [comment]
Thanks for update!

**Comment by KumaraMonk** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1340853
Is this the cause (which I'm also experiencing)?

**Comment by jasonthomas** [comment]
@KumaraMonk https://bugzilla.mozilla.org/show_bug.cgi?id=1340853 is unrelated to this issue. Please open another issue.

**Comment by MaDonnasPersonas** [comment]
It looks like the User Count has been down since March 14th. No one shows any users for 3 days.

**Comment by muffinresearch** [comment]
@MaDonnasPersonas is this still an issue?

**Comment by jasonthomas** [comment]
I've recently made some adjustments to stats processing and indexing which includes retrying and reindexing when there are issues. This is a short term fix.

**Comment by MaDonnasPersonas** [comment]
It seemed to be working fine now. Hopefully it will stay that way and thanks for working on this problem.
