### ISSUE TITLE
Add Dictionary & Language Pack Explanations

### ISSUE THREAD

**Issue by WesleyBranton** [mozilla/addons#31]
A user on the SUMO forums has requested that we add a a brief paragraph to the [Dictionaries & Language Packs page](https://addons.mozilla.org/en-US/firefox/language-tools/) that will explain the difference between the dictionary download and language pack download.

Can you please consider adding this to that page?

**Comment by jvillalobos** [comment]
Please file the bug in the [addons-server project](https://github.com/mozilla/addons-server/issues/new)

**Comment by andymckay** [comment]
It's fine to have bugs here, the show up in waffle and can get linked to from other repositories. This can be a good first bug if someone knows what the actual text is.

**Comment by jvillalobos** [comment]
Ah, didn't know that. Note it's also filed as [bug 1248471](https://bugzilla.mozilla.org/show_bug.cgi?id=1248471).

**Comment by WesleyBranton** [comment]
Yes, I also filed it on Bugzilla because I wasn't sure which place would get be better to file the report on.
Sorry about that.
In the future, would you rather have bug reports of this nature filed on Bugzilla or Github?

**Comment by andymckay** [comment]
Github please.

**Comment by WesleyBranton** [comment]
That's what I figured.

**Comment by jvillalobos** [comment]
Here's what could be added to that page:

> Installing a dictionary add-on will add a new language option to your $Application spell-checker, which checks your spelling when you fill out Web forms. Language pack add-ons change the language of the entire application.

`$Application` is a placeholder, in no particular syntax. If it's too much of a hassle, it's okay to drop it.

**Comment by eviljeff** [comment]
mentor @jvillalobos :)

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by Dino-Herbert** [comment]
It appears that this issue is still open.  I'll take it if that's okay.  I'm in the process of cloning source code with Mercurial.

**Comment by EnTeQuAk** [comment]
> It appears that this issue is still open. I'll take it if that's okay. I'm in the process of cloning source code with Mercurial.

Please, go for it! It's all yours. If you need any help, let us know.

**Comment by Dino-Herbert** [comment]
@jvillalobos Can you tell me more about what you're thinking in regard to the placeholder?

**Comment by jvillalobos** [comment]
@Dino-Herbert it's used in other parts of the site to refer to the application. It's replaced with Firefox, Thunderbird, SeaMonkey, etc. I think you want [something like this](https://github.com/mozilla/addons-server/blob/master/src/olympia/pages/templates/pages/faq.html#L18).

**Comment by Dino-Herbert** [comment]
@jvillalobos Okay great.  Looks like Angular

**Comment by Dino-Herbert** [comment]
@jvillalobos just to keep you updated, I'm having some issues getting my local environment set up using VirtualBox on my windows machine.  I'm getting an error using docker-machine create that states I don't have VX-T/ AMD-V enabled.   However, the VirtualBox VM has these enabled and my local machine's BIOS has virtualization enabled.  I may just create a dual boot for linux on my machine.

**Comment by jvillalobos** [comment]
Okay, remember you can talk to the developers in the #amo channel on IRC, and they can help you with environment set up questions.

**Comment by Dino-Herbert** [comment]
@jvillalobos I finally was able to resolve the issues I was having with my dev environment set up: the elasticsearch container kept exiting after only a short time period and I had to increase the vm.max_map_count.  The other issue I had related to getting a 504 Gateway timeout error on the nginx container.  I finally stumbled on a post indicating that I can load the site if I use the port number. 

I'll address issue #31 shortly.

**Comment by Dino-Herbert** [comment]
@jvillalobos  https://github.com/Dino-Herbert/addons-server/commit/b0d7a9f2b9a7aa08d59f65bdc2e5b7af5420030c

**Comment by Dino-Herbert** [comment]
@jvillalobos I was under the impression that new contributors should have the mentor do a quick code review prior to doing a PR.  Is that how you'd like to handle this or should I just do a PR?

**Comment by jvillalobos** [comment]
I gave it a look just now. Please submit the PR, thanks.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix screenshot:
![2017-08-16_1704](https://user-images.githubusercontent.com/15685960/29368387-3d4d5e94-82a8-11e7-8417-d5b34e296150.png)
