### ISSUE TITLE
Can't change description and locale for approved extension

### ISSUE THREAD

**Issue by MrOnlineCoder** [mozilla/addons#311]
Hello.
### Describe the problem and steps to reproduce it:
I can't change default locale and description for my addon (screenshot attached).

Steps I did:
1.Go to extension edit page
2.Click "Edit" in "Extension info" section
3.Change locale and description
4.Try to save it.
### What happened?
I can't change locale and description. I encounter an error that I have missed adding description in given locale, which is not true.

### What did you expect to happen?
Saved changes.
### Anything else we should know?
Extension page: https://addons.mozilla.org/ru/firefox/addon/forcecopy/
Screenshot of error (Russian): ![addon_error](https://cloud.githubusercontent.com/assets/5202478/21966088/9a9462da-db75-11e6-8096-338e692925cf.png)

Thanks and regards!

**Comment by jvillalobos** [comment]
Were you able to fix this on your own? I see you have a couple of localizations for the add-on, and I tried changing the description for English and Russian and it seemed to work for me.

If it doesn't work, can you tell us for which locale you're trying to change the description?

**Comment by MrOnlineCoder** [comment]
No, I wasn't. I am trying to set description for English locale and set it as default locale. I have 3 locales: English, Russian, Ukrainian.

**Comment by jvillalobos** [comment]
I just changed the default locale. Can you try editing the descriptions again?

**Comment by MrOnlineCoder** [comment]
Yea, I pressed Save changes button and no errors happened, but the description didn't change.

**Comment by jvillalobos** [comment]
The values on the fields may not change immediately due to caching. Give them some time (30 mins?) and let us know if the problem persists.

**Comment by MrOnlineCoder** [comment]
Yes, thanks, it changed. But why I couldn't change default locale by myself?

**Comment by MrOnlineCoder** [comment]
Ow, the description just got reset. Why?

**Comment by jvillalobos** [comment]
> Yes, thanks, it changed. But why I couldn't change default locale by myself?

I don't know why you weren't able to change the default locale. Might have been some error during submission.

> Ow, the description just got reset. Why?

You're looking at the page using the Russian locale. Did you change that description as well? I see the English description was updated correctly.

**Comment by MrOnlineCoder** [comment]
Yea, sorry, my mistake. Anyways, I couldn't change description without your help.
