### ISSUE TITLE
Remove obsolete tables not linked to django models - they prevent some users from being deleted

### ISSUE THREAD

**Issue by sanpii** [mozilla/addons#316]
### Describe the problem and steps to reproduce it:

Click on *Delete Account* link on my account page https://addons.mozilla.org/fr/firefox/users/delete

### What happened?

![screen shot 2017-01-22 at 13 36 06-fullpage](https://cloud.githubusercontent.com/assets/113045/22182543/f7ec0334-e0a7-11e6-93d8-8377507d49a3.png)

### What did you expect to happen?

Delete my account.

### Anything else we should know?

My account email: sanpi@homecomputing.fr

A created a module but I deleted it.

![screen shot 2017-01-22 at 13 35 54-fullpage](https://cloud.githubusercontent.com/assets/113045/22182547/0b07336c-e0a8-11e6-9a9f-e181ce4779ca.png)

**Comment by jvillalobos** [comment]
I tried deleting the account (ID: 6608646), but I'm getting an error. @jasonthomas or @bqbn, can you look into this?

**Comment by bqbn** [comment]
@jvillalobos what is the url did you use to delete this user? Also could you check if I have admin privilege to delete users?

**Comment by bqbn** [comment]
So the deletion via the admin web interface failed because it run into some foreign key constraint failure: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/370527/events/9509223/

However, I was able to delete the user via the management shell_plus command, using "u.anonymize()" call directly.
```
>>> uids
['6608646']
>>> for uid in uids:
...     try:
...         u = UserProfile.objects.get(pk=uid)
...     except UserProfile.DoesNotExist:
...         print "UID %s does not exist." % uid
...         continue
...     try:
...         u.anonymize()
...         print "UID %s anonymized." % uid
...     except:
...         print "UID %s failed to be anonymized." % uid
...
UID 6608646 anonymized.
```
@muffinresearch do you think it's worth figuring out if there is a bug somewhere that prevented the deletion from being done via the /admin web interface (as shown in the sentry log above)?

**Comment by jvillalobos** [comment]
I used [this URL](https://addons.mozilla.org/admin/models/users/userprofile/6608646/delete/). And no, I don't think you have that level of access on the site.

**Comment by muffinresearch** [comment]
> @muffinresearch do you think it's worth figuring out if there is a bug somewhere that prevented the deletion from being done via the /admin web interface (as shown in the sentry log above)? 

Yep I'll assign @diox to take a look in due course. It's lower priority since it's possible to workaround it. Would be good to know if this was an isolated case or if there's likely to be future problems with deletion though.

**Comment by diox** [comment]
Looks like it's a relic from... Marketplace. Somehow the users_install table is still there and preventing deletion because django does not know about it. I'll dig deeper, see if there are any other tables like that laying around.

**Comment by bqbn** [comment]
The users_install table is kinda big with close to 600K rows. Would be nice to be able to drop it if the current app doesn't need it. And for other relic tables too, if there are any. :)

**Comment by diox** [comment]
There are... surprisingly quite a few extra tables, at least on stage (I don't have prod access):

Table |
------|
addon_payment_account |
addons_excluded_regions |
addons_trending |
api_access |
app_collection_membership |
app_collections |
app_collections_curators |
auth_message |
auth_user_groups |
auth_user_user_permissions |
collection_recommendations |
django_session_old |
django_site |
favorites |
log_activity_app |
oauth_nonce |
oauth_token |
payment_accounts |
payment_assets |
payments_seller |
perf_appversions |
perf_osversions |
preload_test_plans |
prices |
submission_checklist_apps |
tag_stat |
user_inapp_keys |
users_install |
users_versioncomments |

@bqbn can you verify if those 29 tables also exist on prod ?

**Comment by bqbn** [comment]
@diox the 29 tables all exist on -prod, with oauth_nonce being the largest in size (close to 700 MB). Do you think we need a separate ticket to look into possibilities to drop these tables from the database?

**Comment by diox** [comment]
Many of these tables could block other users so we should keep it in this issue.

We should drop those tables as soon as we can, but obviously we don't want to incur too much load on the databases when doing that. Let me know how you want to proceed.

**Comment by jasonthomas** [comment]
table drop should be a very quick operation from mysql standpoint and since these tables are not being used it should not affect load much.

**Comment by bqbn** [comment]
Yeah, I just tested on a production snapshot and dropping the largest oauth_nounce table took 0.23 second. :)

Given that this operation is low risk with many benefits, I think we should remove those tables as early as we can!

**Comment by diox** [comment]
Let's schedule that for Monday, doing dev and stage first ?

**Comment by bqbn** [comment]
@diox would it be better to do this in a migration?

**Comment by diox** [comment]
Mmm, yes, why not. I had not thought about that because the tables are not even supposed to exist any more, but it makes sense, I can just use `DROP TABLE IF EXISTS`

**Comment by bqbn** [comment]
That'd be awesome! 👍

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev using FF51(Win 7) and the issue is still reproducing:
- a new registered user will not be able to delete his "no - add-ons" account, if he previously had an add-on submitted.
![cannot-delete](https://cloud.githubusercontent.com/assets/15685960/22469539/04b9f2c2-e7d5-11e6-83d1-f047efde7986.png)

It is possible that the fix is not yet in -dev?

**Comment by diox** [comment]
It's on dev.

@ValentinaPC your user on dev is attached to 2 different add-ons (causing the message to appear), was it a new one ?

**Comment by ValentinaPC** [comment]
I've tried with another account, brand new - https://addons-dev.allizom.org/en-US/firefox/user/gelato33/ but I am not able to delete it.
I've submitted an add-on and after that deleted it.
And the same message as above is displayed.

**Comment by diox** [comment]
I don't understand. That's the expected message if your account is still linked to an add-on, it's there to prevent developers from accidentally deleting their account while they still have an add-on.

The problem we were facing in this issue is that the user could not delete their account despite no longer having an add-on associated to their account.

**Comment by sanpii** [comment]
My bad account was deleted, however there is probably another problem. When I try to upload the same extension with my good account, I have an error:

> Your add-on failed validation with 1 error.
> * Duplicate add-on ID found

Extension name: `tor-everywhere`.

**Comment by diox** [comment]
@sanpii : that's actually a feature: we don't allow guids that were already used to be used by somebody else. If you want to re-use that guid, you should contact `amo-admins@` by email to solve this.

**Comment by ValentinaPC** [comment]
@diox I have **NO add-on** attached to my account.
I've submitted an **add-on**, but **delete** it!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7).
Created a new account and added 2 add-ons (listed+unlisted) for it. Deleted both add-ons and then tried to delete the account: worked like a charm.
Postfix screenshots:
![2_deleted_add-ons_account](https://cloud.githubusercontent.com/assets/15685960/22593073/89d70f38-ea25-11e6-8d87-c12cd51d83ea.png)
![banner](https://cloud.githubusercontent.com/assets/15685960/22593074/89d9824a-ea25-11e6-84ad-78f52a280100.png)
