### ISSUE TITLE
Old version addon links broken, only static link to latest available.

### ISSUE THREAD

**Issue by superkuh** [mozilla/addons#318]
### Describe the problem and steps to reproduce it:

Basically, all the links to old versions of the addon for FoxyProxy instead only point to the latest release.

I am attempting to download an older version of FoxyProxy Standard from the Mozilla Add-ons website. First I went to,
https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/?src=ss
Then I went to "see complete version history" link,
https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/versions/
From there I scrolled down to 4.5.7 and clicked "Continue to download" button,
https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/contribute/roadblock/?src=version-history&version=4.5.7
From there I attempted to download version 4.5.7. Unfortunately there is only a static link there to,
https://addons.mozilla.org/firefox/downloads/latest/foxyproxy-standard/addon-2464-latest.xpi?src=version-history

That link gives the latest version. Not 4.5.7. Upon further review I found this behavior applies to *all* older version links. No old versions can be downloaded from the Mozilla Addons site. All such links point to,
https://addons.mozilla.org/firefox/downloads/latest/foxyproxy-standard/addon-2464-latest.xpi?src=version-history

I am running FF48 with a clean profile and no extensions. I asked about this behavior on Freenode IRC in #firefox and other users confirmed my findings there.

### What happened?
I was only served links to the latest version of the addon instead of the version requested and listed on the addon page.

### What did you expect to happen?
I expected to be able to download the older version (4.5.7, or any of them) that is displayed on the old version pages.

**Comment by diox** [comment]
I think I've seen this issue filed before but can't find it at the moment. I also think it only affects add-ons that have the contribute intermediate page set up ("Ask before users can download this add-on" on payments management page in devhub).

**Comment by superkuh** [comment]
Is there a html (or even ftp) directory listing of the old versions anywhere that could be used in the meantime? Or some other mechanism to access to old xpi?

**Comment by diox** [comment]
If you know the direct link to the XPI it works :) You could use the API to find those (http://addons-server.readthedocs.io/en/latest/topics/api/addons.html) while waiting for a fix.

I'll try to tackle this issue today so that it lands in time for next Thursday's push.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50 (Win 7) for listed and beta versions.
Postfix video:
![addtofirefox](https://cloud.githubusercontent.com/assets/15685960/22303042/253eacbc-e33a-11e6-8cc0-f35e7267f764.gif)
