### ISSUE TITLE
Remove side-loading from AMO

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#32]
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1245956, we will remove the side loading requirement from AMO. This means we'll need to file a few bugs, simplify the UI quite a bit, remove the side loaded trunion instance, re-sign all side loaded add-ons as fully signed and so on.

There will be more bugs on this.

**Comment by andymckay** [comment]
I got the wrong end of the stick here, we still need preliminary and full signing to reflect the preliminary and full states.

**Comment by wagnerand** [comment]
Could you elaborate why this bug was closed?
