### ISSUE TITLE
How do I change my e-mail or grant access to other people on my team to upload extensions?

### ISSUE THREAD

**Issue by fproulx-pbox** [mozilla/addons#320]
### Describe the problem and steps to reproduce it:
Our manager created the account when we first submitted the extension. Now, our company is changing its e-mail addresses. So we will need to change the email associated with the account used to upload.

Also, it would be great to be able to invite multiple people to manage (instead of a single person). For Chrome extensions, Google allows us to create groups.google.com , invite people. That way we have backups when someone is sick, etc.... (instead of sharing the password...).

cc @olivierbeaulieu

**Comment by fproulx-pbox** [comment]
cc @ olivierbeaulieu

**Comment by jvillalobos** [comment]
In the developer pages of the add-on there's a section called Manage Authors & License where you can add multiple accounts to the add-on.
