### ISSUE TITLE
Restrict new submissions using ctypes.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#321]
As https://blog.mozilla.org/addons/2017/01/24/preventing-add-ons-third-party-software-from-loading-dlls-into-firefox/ announced, new add-on submissions using ctypes should not longer be allowed starting with Firefox 53.

@jvillalobos are new submissions accepted that have strict maxVersion < 53?

This is due for the April 18 tag, April 20 push.

**Comment by jvillalobos** [comment]
No, I don't think we need that restriction in this case.

**Comment by wagnerand** [comment]
Pinging @jvillalobos for what exactly the error message should say...

**Comment by jvillalobos** [comment]
> Starting with Firefox 53, add-ons loading binary libraries are not allowed. [Native Messaging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging) is the only allowed method to communicate with external binaries.

**Comment by wagnerand** [comment]
Thanks! Actually, I think I can do this myself...

**Comment by wagnerand** [comment]
QA information:
* Submitting a new add-on that uses js-ctypes should fail.
* Submitting an update to an already existing js-ctypes add-on should work.

**Comment by ValentinaPC** [comment]
> I uploaded test add-on to -dev so you can test submitting updates, please let me know and I'll give you access.

Can you provide me the used add-on?
Thanks!

**Comment by wagnerand** [comment]
@ValentinaPC I just added you to https://addons-dev.allizom.org/en-US/developers/addon/my-ctypes-addon

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF52(Win 7) and obtained the following results:
**- submit new add-on that uses js-ctypes** - fails, but with an multiplied error message - please see screenshot:
![multiple_errors](https://cloud.githubusercontent.com/assets/15685960/25231638/438ed4a0-25e1-11e7-8130-3a4478e6699f.png)

- submit an update to your add-on fails with the same error 

Also, for me, the error message, if this is the one is supposed to appear, is not very clear.
I've used you add-on but changed the `id`, `version` and `maxVersion`.

What are the next steps? Reopen?
Thanks!

**Comment by wagnerand** [comment]
We reverted the *amo-validator* patch because it was too restrictive. New add-on submissions using *js-ctypes* are denied either way, because we'll deny any new add-on submissions anyway (with the `restrict-legacy-submissions` waffle flag).

@ValentinaPC tested this on stage and found the edge case mentioned in the [initial comment](https://github.com/mozilla/addons/issues/321#issue-203413763) of this issue, but @jvillalobos said he is ok with keeping that.

<TheOne> jorgev: are you ok with allowing new js-ctypes add-on submissions for strict maxVersion < 53 ?
<jorgev> TheOne: yeah, I'm okay with it
<jorgev> TheOne: I think it's okay to keep it. I'm thinking some unlisted / enterprise devs might need it

Based on this, I'm marking this as verified.
