### ISSUE TITLE
Old version of extension is disabled after uploading new version as unlisted

### ISSUE THREAD

**Issue by alexesprit** [mozilla/addons#322]
### Describe the problem and steps to reproduce it:
I read about new AMO feature in this article https://blog.mozilla.org/addons/2017/01/26/mixing-listed-and-unlisted-on-amo/ and tried to test it.

I have an extension that isn't passed a review yet. So, I tried to upload new version of that extension as an unlisted one. After upload complete, the old one (that was in a review queue) has been disabled by Mozilla.

Steps to reproduce the issue:
1. Submit a new extension as a listed one.
2. Increment the extension version and upload this one as an unlisted extension.

### What happened?

After upload complete, the old version of the extension (that was in a review queue) has been disabled by Mozilla. The new version is uploaded as an unlisted extension (that's ok).

### What did you expect to happen?

The old version is in review queue; the new version is uploaded as an unlisted extension.

**Comment by diox** [comment]
Ouch, sorry, that's bad. We'll look at this asap.

**Comment by diox** [comment]
Found it. `Version.from_upload()` calls `version.disable_old_files()` at upload time, but it should only do that when you upload a listed version.

**Comment by diox** [comment]
We've deployed the fix to production. Thanks for reporting that issue!

**Comment by vcarciu** [comment]
Verified as fixed : 
![unlistlist](https://cloud.githubusercontent.com/assets/1583842/22553672/3e2a9a60-e966-11e6-94f3-a2365b1cd7d1.png)
