### ISSUE TITLE
platform detection overrides explicit search parameters

### ISSUE THREAD

**Issue by aessalle** [mozilla/addons#323]
Steps to reproduce:

0) using Windows
1) search for "tray"
2) select "Works with" "Linux" search option

Actual results:

The first two results ("MinimizeToTray revived" and "FireTray") have platform-specific versions ... the AMO platform detection JavaScript makes these point to a download for Windows (URL contains "/platform:5/") rather than Linux (which uses "/platform:2/"), even though I explicitly marked Linux in my search. I can find no way to override this behavior to download the desired Linux version, short of changing my user-agent.

Expected results:

The download links should point to the version applicable to the platform the user specified in their search.

**Comment by muffinresearch** [comment]
Seems like something of an edge case, but we shouldn't second guess the user's intent with platoform detection.

Something we need to bear in mind for future overhauls of search features.
