### ISSUE TITLE
Automatically flag add-ons using native messaging for admin review

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#325]
Add-ons that use native messaging should be automatically flagged for admin-review during submission.
This probably involves both `addons-linter` and `addons-server` work.

This is related to https://github.com/mozilla/addons-server/issues/4533. We need to expose in the linter whether the add-on uses native messaging. This is important for the auto-approval. On top of that, such add-ons should only be reviewed by admin reviewers. I think once we have the permission exposure, adding the admin-flag in `addons-server` should be fairly easy.

**Comment by muffinresearch** [comment]
@wagnerand would you have a moment to file issues on addons-linter / addons-server with the details?

**Comment by wagnerand** [comment]
I'm not sure how much of this has already been done.
I think @diox already did the addons-linter part. Is that right, @diox?

**Comment by diox** [comment]
No, I didn't. For auto-approval I just used the permission list exposed in the metadata, so I didn't need to touch addons-linter. We could probably do the same to flag add-ons for admin review, no need to modify addons-linter.
