### ISSUE TITLE
The author of an addon doesn't get an email about the reviewer editing his/her post

### ISSUE THREAD

**Issue by fluks** [mozilla/addons#326]
### Describe the problem and steps to reproduce it:

The author of the addon isn't notified about the user editing his/her review.

1. Someone reviews your addon.
2. The review is then edited.

### What happened?

Someone made a review about my addon, I got an email about it. I then answered to it. The user edited the original review after my reply, I didn't get any email, or any kind of notification about it.

### What did you expect to happen?

To get a new email.

**Comment by jvillalobos** [comment]
This sounds like a useful thing, but we should consider the complexity behind it. A user could make a bunch of edits in succession (grammar corrections or whatever) and we wouldn't want to send a notification each time. If it's possible to easily throttle the notifications so we don't send, say, more than one per hour, that would be best.
