### ISSUE TITLE
Issues requiring the attention of user are not immediately visible. 

### ISSUE THREAD

**Issue by spookyUnknownUser** [mozilla/addons#327]
For instance if a reviewer requests unsubmitted source code, AMO continues to display [the queue position of the extension](https://i.imgur.com/Xlk22P3.png), even if the reviewer requires attention from the user. 

The only way to see if a reviewer is actually waiting on anything is from the review history menu. Something that was completely invisible to me until an extension was rejected for not replying to a request.

It would be much easier for users and reviewers, I think, If the queue position could change to something like "action needed" when the reviewer has asked for something.

**Comment by jvillalobos** [comment]
This is largely solved in https://github.com/mozilla/addons-server/issues/3143, which should be deployed later this quarter.
