### ISSUE TITLE
Mozilla sites forget my login

### ISSUE THREAD

**Issue by JuzBeKind** [mozilla/addons#328]
Over the years, Mozilla sites (sites for reviewing add-ons, posting feedback or submitting bugs reports) have all had an issue with forgetting my login credentials. If I don't login for a while (seems to be around a year or so), the sites forget either my password or both my ID/e-mail _and_ my password. Yahoo is the only other site I know of which does this. 
Is this a bug or is it some kind of intentional inactive account purging system? 
**Note:** This isn't a matter of me forgetting my login credentials. My credentials are stored in a login-entry program and can't be easily modified (I also maintain login credential records in separate encrypted text documents that I can use, and have used, to confirm that my login-entry program isn't somehow malfunctioning). Also, of the hundreds of sites that I login to, Mozilla and Yahoo are the only ones that I've ever had this problem with (with exception to sites that have been shut down, of course).

**Comment by muffinresearch** [comment]
You mention not having logged in for around a year - during that time we migrated from site specific authentication to using Firefox Accounts. Users were notified about the change and asked to migrate their account, but if you missed that and didn't carry out that process during the migration window, you'll now need to create an account on Firefox Accounts with the same email address to access the Mozilla Add-ons site (AMO) as before.

**Comment by JuzBeKind** [comment]
Thanks for the info muffinresearch.
Assuming there has been more than one migration over the years, this would certainly explain everything.
