### ISSUE TITLE
Attempted XSS distorts Jan 30 statistics

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons#330]
Viewed stats for my own add-on and ABP. Download stats are exceptionally high on Jan 30.
[Firefox 2, the theme, reloaded](https://addons.mozilla.org/addon/6898/statistics/downloads/sources/?last=30) \[[JSON](https://addons.mozilla.org/addon/6898/statistics/sources-day-20170101-20170208.json)\]
[AdBlock Plus](https://addons.mozilla.org/addon/adblock-plus/statistics/downloads/sources/?last=30) \[[JSON](https://addons.mozilla.org/addon/adblock-plus/statistics/sources-day-20170101-20170208.json)\]

Examples:
`cb-btn-users<%2fscript><swffelqj>`
```cb-btn-''u''sers'$(``%3b``)`````echo%20'''''`'```

Can these be (retroactively) filtered out?

**Comment by muffinresearch** [comment]
Duplicate of https://github.com/mozilla/addons-server/issues/3510
