### ISSUE TITLE
Seemingly new validation threshold rejects extension submission

### ISSUE THREAD

**Issue by flamestream** [mozilla/addons#331]
### Describe the problem and steps to reproduce it:
Attempting to submit a jetpack addon fails validation since at least 2017-08-06.

### What happened?
An error message at the end of validation yielded a message like so:
```
General Tests
1 error, 1 warning, 0 notices
```
>Validation generated too many errors/warnings so 66 messages were truncated. After addressing the visible messages, you'll be able to see the others.

### What did you expect to happen?
```
General Tests
0 error, 1 warning, 0 notices
```

### Anything else we should know?
I believe there has been a change in the validation rules. To be sure there was such change, I resubmitted an extension that was previously approved , and this time it got rejected. The same amount of warnings were generated as the approved report.

The 1 warning we got from the General Tests was due to inclusion of binary component. Distribution mode was set to `On your own.`.

**Comment by spoji** [comment]
Could it be because of this commit?
https://github.com/mozilla/amo-validator/commit/f535570217d095ca9296ce28ad4c87bad99538ea#diff-857d056d690e49b645b5417b3bcd31b5

If so, this looks like a normal behavior.

More information here : https://mzl.la/2joSS11

**Comment by spoji** [comment]
After talking to TheOne, it would seems I'm was wrong. This commit has nothing to do with the actual error.

**Comment by wagnerand** [comment]
> Attempting to submit a jetpack addon fails validation since at least 2017-08-06.

I can't say much about the future, but can you please provide the file you are trying to upload, so we can investigate?

**Comment by flamestream** [comment]
One of the recent report can be found at
https://addons.mozilla.org/en-GB/developers/upload/dc98446ee87d4d2e92c9b683d293f454
I believe that the file attempted to be submitted can be traced from this. You may also compare the validation result of the same file at
https://addons.mozilla.org/en-GB/developers/addon/true-key-add-on/file/584539/validation

We have made progress in the conversion of the add-on to the WebExtension platform, but we'd appreciate it to be able to push one more update before the switch over.

**Comment by wagnerand** [comment]
Sorry, but that was not what I was asking for.

**Comment by wagnerand** [comment]
I got the file in private. I ran `amo-validator` in the current deployed version against it as well as the version from 2017-01-24. Both produce the exact same output.

**Comment by wagnerand** [comment]
A wild assumption: The validation run actually ends up in an error: Exception TypeError: 'super() argument 1 must be type, not None' in <bound method JSShell.__del__ of <validator.testcases.javascript.jsshell.JSShell object at 0x1069d52d0>> ignored

Maybe that caused some warnings to be swallowed in the past?

**Comment by flamestream** [comment]
A small update: I just ran the same add-on code without native components against the web validator.
The error is still present:
```
General Tests
1 error, 0 warnings, 0 notices
```
Which leads me to believe that the warning on the other sections probably actually had an effect on the full validation.
```
Extension Tests
0 errors, 363 warnings, 0 notices
```
This is odd, because the extension had the exact same amount of extension test warnings (unsurprisingly, since it's the same code) and validation passed.

**Comment by flamestream** [comment]
The issue seems to have been fixed. Thank you for your cooperation.

**Comment by flamestream** [comment]
It seems I was misinformed. The issue is still present.
Is there anything that can be done to help pushing this forward?
