### ISSUE TITLE
Daily user count dropped to zero on several days

### ISSUE THREAD

**Issue by mikel2000** [mozilla/addons#333]
Daily user count on addons.mozilla.org dropped to zero on 26th/31th of January and 7th/8th of February. Please check e.g. https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30. As this happens very often, it would be great if somebody could fix the root cause.

**Comment by jasonthomas** [comment]
Thanks for the report. I don't think we need to keep opening issues for this since we are having this tracked in https://github.com/mozilla/addons/issues/309 and it is already assigned to me. We will update with a resolution in that issue.
