### ISSUE TITLE
Unable to donate via PayPal 

### ISSUE THREAD

**Issue by gloomy-ghost** [mozilla/addons#336]
### Describe the problem and steps to reproduce it:
1. Find an extension on AMO (https://addons.mozilla.org/zh-CN/thunderbird/addon/enigmail/developers in my case).
2. Click the blue "donate" button.
3. Confirm donation amount.

### What happened?
The page went dark and stuck until reload.
Error on console: Refused to display 'https://www.paypal.com/us/cgi-bin/webscr?cmd=_dispatch-failed' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

### What did you expect to happen?
PayPal's panel should appear, or a new tab to PayPal should be opened.

**Comment by gloomy-ghost** [comment]
Just found #77 and #240. It sounds reasonable to forbid iframe for security, but it also breaks donations on AMO. 😞 Would it be possible to open a new tab rather than use an iframe?

**Comment by muffinresearch** [comment]
@gloomy-ghost when this happens it's Paypal's headers causing their own iframe to be disallowed.

**Comment by andymckay** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=896653, closing as a dupe.
