### ISSUE TITLE
Manifest.json Missing error

### ISSUE THREAD

**Issue by kyle-angus** [mozilla/addons#337]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Uploaded a zip file containing an update for my company's browser add-on.

### What happened?
After upload, the add-on parser returned an error stating the manifest.json was missing.

### What did you expect to happen?
I expected the parser not to flag any errors, as the manifest.json is at the top level of the folder.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Here's out manifest: 

```
{
  "manifest_version": 2,

  "name": "Authen2cate Secure Sign On for Browsers",
  "short_name": "A2C Browser Extension",
  "version": "1.1.1",
  "description": "The Authen2cate Secure Sign On for Browsers protects your passwords while enabling seamless access to your resources.",
  "author":"authen2cate",

  "icons": {
      "16": "img/icon16.png",
      "32": "img/icon32.png",
      "38": "img/icon48.png",
      "48": "img/icon48.png",
      "128": "img/icon128.png"
  },

  "browser_action": {
    "default_icon": "img/icon128.png",
    "default_popup": "popup.html",
    "default_title": "Authen2cate Secure Sign On"
  },

  "background": {
      "persistent": true,
      "scripts": ["js/bg_main.js","js/jquery-2.2.4.min.js"],
      "pages": ["background.html"]
  },

  "permissions": [
    "activeTab",
    "tabs",
    "background",
    "storage",
    "<all_urls>"
  ]
}

```

**Comment by eviljeff** [comment]
Can you attach the zip file here so we can try to reproduce?  (You can delete any sensitive files from the zip if it's not going to be publicly distributed)

**Comment by kyle-angus** [comment]
[A2C-REWRITE OBFUSCATED.zip](https://github.com/mozilla/addons/files/811334/A2C-REWRITE.OBFUSCATED.zip)

**Comment by eviljeff** [comment]
@kyle-angus if that's the zip you uploaded then I can see the problem -  the  manifest isn't in the root of the zip, but rather inside a folder in the root of the zip file.  (You need to zip the contents of the folder, not the folder)
