### ISSUE TITLE
404 page when downloading signed file for self-distribution 

### ISSUE THREAD

**Issue by NicolasTextingHouse** [mozilla/addons#339]
### Describe the problem and steps to reproduce it:
- Upload new version (zip file) with self-distribution option

- Automatic validation results : "Your add-on was validated with no errors and 4 warnings." Details :
Report (https://addons.mozilla.org/en-US/developers/upload/2ac699664f8e43c7b19e9f4434d28c25)
_______________
![2017-02-28_15h47_38](https://cloud.githubusercontent.com/assets/15123945/23404213/48868124-fdcd-11e6-8bae-0590da4bc0e6.png)
_______________

- Click on "Sign Add-on" : You’re done! This version is signed and ready to for self-distribution. You can download it by clicking the button below.
_______________
![2017-02-28_15h50_00](https://cloud.githubusercontent.com/assets/15123945/23404291/9fef88de-fdcd-11e6-93ba-cc6280d80c5b.png)
_______________

### What happened?
But, when I click on button "Download textinghouse-1.2.1-an+fx.xpi" (link : https://addons.mozilla.org/firefox/downloads/file/600140/textinghouse-1.2.1-an+fx.xpi?src=devhub), I have a 404 error page.
_______________
![2017-02-28_15h55_37](https://cloud.githubusercontent.com/assets/15123945/23404478/af9b5348-fdce-11e6-916d-e628d6d85c0a.png)
_______________

Same think when I go to https://addons.mozilla.org/en-US/developers/addon/textinghouse/versions in the "Manage Status & Versions" page. I can see my version 1.2.1 with status "Approved" but when I click on the file name to download it (same link : https://addons.mozilla.org/firefox/downloads/file/600140/textinghouse-1.2.1-an+fx.xpi?src=devhub), I have a 404 Not Found error served by nginx.

### What did you expect to happen?
I expect file to be downloaded :-)

**Comment by diox** [comment]
Hi,

Sorry about that, it's a complex problem linked to the fact that your add-on is set to "Invisible". It has already been reported as https://github.com/mozilla/addons/issues/324 so I'm closing yours.

The problem should automatically fix itself today as we have automated tasks that fix the files that end up in this state. Alternatively, you can switch back your add-on status to "visible" to fix this - it's confusing, but as long as you never publish a version on AMO, it should not have a public page anyway.
