### ISSUE TITLE
Remove old logins from AMO

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#34]
We are currently in a migration phase, we are trying to get users to migrate over to Firefox Accounts.

When we've reached a sufficiently large number of converted users, let's turn off the legacy logins, the migration flow and delete all that code. Users will then have to log in through Firefox Accounts. Expecting this will be at lease month or three past this date.

**Comment by jvillalobos** [comment]
This means they just need to use the same address in FxA in order to recover the old account, right?

**Comment by andymckay** [comment]
Correct.

**Comment by andymckay** [comment]
@mstriemer is all over this one.

**Comment by andymckay** [comment]
Feeling like we can probably close this one now.
