### ISSUE TITLE
accounts.firefox.com login does not autocomplete in Chrome

### ISSUE THREAD

**Issue by bfred-it** [mozilla/addons#341]
### Describe the problem and steps to reproduce it:

[accounts.firefox.com/signin](https://accounts.firefox.com/signin) does not autofill any information on Chrome. No email, no password.

1. Open Google Chrome
2. Visit https://accounts.firefox.com/signin
3. Start typing your email address

### What happened?

Issue 1: the email does not autocomplete
Issue 2: the password does not autocomplete, even if Chrome will recognize the login and save it successfully

### What did you expect to happen?

Email and password autocomplete like they do in Firefox

**Comment by muffinresearch** [comment]
@bfred-it hi, this is the issue tracker for https://addons.mozilla.org rather than https://accounts.firefox.com. If you have a moment please could you re-file this issue here [1]? 

[1] https://github.com/mozilla/fxa-content-server/issues/new

**Comment by bfred-it** [comment]
Done, thank you!
