### ISSUE TITLE
Addons.mozilla.org does not work in Firefox. Falsely claims "no cookies" when cookies are enabled.

### ISSUE THREAD

**Issue by NothingCanPlayVTT** [mozilla/addons#342]
bugzilla.mozilla.org told me to put this here for some reason and then closed my bug report.  So supposedly this is where I am supposed to report this but with your website.  Lord knows maybe you'll say this is the wrong place and send be back to the exact same place I reported it earlier and they'll send me back here.  It would make sense since the site literally doesn't work in its own browser.

Firefox version:
I am using the latest ESR 45.7.0 because each Firefox release gets slower and slower and slower like crazy so I had to switch to that until maybe Firefox fixes its slowdown.  But that's the version I'm using if you need to narrow it down.

Steps to reproduce:

I go to
https://addons.mozilla.org/
It forwards me to
https://addons.mozilla.org/en-US/firefox/
I try to "log in" and click.
It sends me to this messy URL
https://oauth.accounts.firefox.com/v1/authorization?action=signin&scope=profile&state=77adf10ec56396afc38f7eab137aec9148aaefa649c7d6bcd6834c540307858d%3AL2VuLVVTL2ZpcmVmb3gv&redirect_url=https%3A%2F%2Faddons.mozilla.org%2Fapi%2Fv3%2Faccounts%2Fauthenticate%2F&client_id=a4907de5fa9d78fc

It then gives me this page:
-----------------------------
Cookies and local storage are required.

Please enable cookies and local storage in your browser to access Firefox Accounts. Doing so will enable functionality such as remembering you between sessions.

Learn more 

-----------------------------

I checked and my cookies work just fine on every other website.  Mozilla.org is NOT blocked from cookies.  I click try again a million times.  It just refuses to work.

I tried everything and it doesn't work in Firefox.

But it does work in Google Chrome.  All these Corporate websites are all now made for Google Chrome only replacing made for MSIE only that sites were 15 years ago.  So Addons.mozilla.org is made for Google Chrome only and doesn't work in its own browser.

**Comment by muffinresearch** [comment]
This issue tracker is for addons.mozilla.org but the issue you appear to be experiencing is in accounts.firefox.com which is a distinct service to addons.mozilla.org which this issue tracker is for.

The issue tracker for the firefox accounts frontend  is here: https://github.com/mozilla/fxa-content-server.

Before reporting the same bug in their tracker please check if the problem happens using a new profile.

The error message talks about localStorage as well as cookies so if you haven't already please check localStorage is not disabled in some way. This comment may provide some pointers [1]

[1] https://github.com/mozilla/fxa-content-server/issues/3129#issuecomment-145477615
