### ISSUE TITLE
Failing to install Enigmail-Addon: wrong step-by-step Instructions in tooltip of Download-Button

### ISSUE THREAD

**Issue by rvv0z** [mozilla/addons#344]
### Describe the problem and steps to reproduce it:

The installation instructions in a tooltip showing up when clicking the download button
is wrong, because not up to date.
It points the user to the wrong menu to look for the "Add-ons" menuitem.

This problem concerns, at least, the English and German versions.
https://addons.mozilla.org/de/thunderbird/addon/enigmail/
https://addons.mozilla.org/en/thunderbird/addon/enigmail/

1. *click* on the "Jetzt herunterladen" or "Download now"
2. A tooltip appears saying:
German version:
"... 2. Öffnen Sie in Mozilla Thunderbird den Add-ons-Manager über das Menü „Extras“ ..."

English version
"... 2. In Mozilla Thunderbird, open Add-ons from the Tools menu. ..."

The German language version and the English language version is incorrect *if* the menu bar is invisible (which it is by default in a new user profile, it seems)
The "Addons" menu item is on top-level next to "Tools"/"Extras".

### What happened?

*User failed to install addon* because the instructions in the download tooltip were misleading. 

### What did you expect to happen?

Expected to see correct description of the TB menu, so I can find the correct way to the "Addons"
menuitem.

### Anything else we should know?
scrshots:
[AMO - German Tooltip SCrshot](https://gandalf.thelostone.net/owncloud/index.php/s/i1P5HLFSCv3LUHS)
[AMO - English Tooltip Scrshot](https://gandalf.thelostone.net/owncloud/index.php/s/xp4LopaHZ9LhfzO)

**Comment by jvillalobos** [comment]
The steps did work for me because I'm on Mac OS and the menu bar is always visible (also, I used the English version). The instructions to open the Add-ons Manager are a bit harder to explain without the menu bar ("click on the hamburger button"?) or screenshots.

**Comment by rvv0z** [comment]
burger button: I guess if the menu bar is not there, it seems, the menu button is being properly located by the users, but then the Addons is not in the sub menu mentioned in step 2 of the instructions. It is right in the main menu next to the top level entries.
it might be enough to just give both options: find addons right there in the main menu or in Extras/Tools if not there. Just so the hint is there and an average user does not have to deal with contradicting instructions.

**Comment by jvillalobos** [comment]
We no longer support Thunderbird add-ons on AMO.
