### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by KumaraMonk** [mozilla/addons#345]
Go to any page within https://addons.mozilla.org/
Click on "Log in"

I get

> Cookies and local storage are required.
> 
> Please enable cookies and local storage in your browser to access Firefox Accounts. Doing so will enable functionality such as remembering you between sessions.
> 
> Learn more 

As far as I can tell these ARE enabled. All other websites are working fine. No such complains, except for ths site.

**Comment by muffinresearch** [comment]
This issue tracker is for https://addons.mozilla.org. The login for amo is provided by a separate service "Firefox Accounts", to file an issue there you can use this link: https://github.com/mozilla/fxa-content-server/issues/new

**Comment by KumaraMonk** [comment]
Hmm... This is starting to feel like inefficient government departments. This is the second time I've to move this issue elsewhere. Isn't there a way for administrators to just transfer this to the relevant "department"?

**Comment by muffinresearch** [comment]
> Isn't there a way for administrators to just transfer this to the relevant "department"?

@KumaraMonk unfortunately github doesn't currently support that.
