### ISSUE TITLE
AMO Site Status link causes insecure connection

### ISSUE THREAD

**Issue by TonnesM** [mozilla/addons#346]
- Visit e.g. https://addons.mozilla.org/en-US/firefox/themes/
- Click Site Status in the footer

Result:
Page leads to https://status.mozilla.org/#addons.mozilla.org_service_history, showing SSL_ERROR_BAD_CERT_DOMAIN - Cert is only valid for *.statuspage.io and statuspage.io.

Expected:
Page loads with no certificate error.

**Comment by Smile4ever** [comment]
Not an issue for me using Nightly 54a1 2017-02-17, what Firefox version on what operating system are you using?

**Comment by TonnesM** [comment]
This happened on Windows for both FF release and Dev Edition as well as SeaMonkey Aurora, but currently no longer does. Apparently the certificate has been renewed as of today. As Eviljeff wrote on IRC, this may have had something to do with taking down the old status.m.o and not replacing it with a new one yet.

I guess this issue could be closed when the cert renewal has been verified. Perhaps related to bugs 1321337 and/or 1323355?

**Comment by andymckay** [comment]
Either way, the link is wrong.

Where's the new status page @jasonthomas ?

**Comment by muffinresearch** [comment]
Looks like this is working fine. The fragment id does nothing but it's not a blocker.
