### ISSUE TITLE
Reviewer – Developer communication: Fullstop at the end of the URL

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#347]
The fullstop at the end of the URL is picked up by the email-server/client as part of the URL and thus resulting in a wrong URL

Example:

> If you want to respond to this email please reply to this email or visit https://addons.mozilla.org/editors/review/****30. If you need to send file attachments, please include the address amo-editors@mozilla.org and mention it in your reply.

Suggestion:

> If you want to respond to this email please reply to this email or visit https://addons.mozilla.org/editors/review/****30
> If you need to send file attachments, please include the address amo-editors@mozilla.org and mention it in your reply.
>

**Comment by wagnerand** [comment]
My email client gets it right, so I assume it's a client thing.

**Comment by erosman** [comment]
I use Yahoo so it may be an issue with Yahoo.

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by erosman** [comment]
That is a simple thing to fix. I wonder why it hasnt been changed.

I realise that it is affecting Yahoo email but I see no reason not to implement it.

It has been a considerable pain to each time, copy URL, paste into address-bar, delete the fullstop at the end and load the page.

Sadly, Yahoo web-mail is JS generated and it would take a lot of code to fix it with a script or else I would have done it by now. 
Asking yahoo to fix their URL matching in emails is even more complicated that asking Mozilla to add a simple new line !!? ;)

**Comment by eviljeff** [comment]
@erosman it's still open for a contributor if you're interested :)  It's just a fix to a template in a text file if you're interested.

**Comment by erosman** [comment]
@eviljeff Where is it?
Can I contribute? How?

I have never done it.

**Comment by ValentinaPC** [comment]
Verified this using my yahoo e-mail client while submitting an add-on from AMO-dev and AMO-stage.
This is how my yahoo message looks like (same on both dev and stage):
![yahoo](https://cloud.githubusercontent.com/assets/15685960/25843593/7d40aeb6-34b0-11e7-98ff-3219627ac179.png)

I don't see any change in it. No line break down.
Link is working as expected.

**Comment by eviljeff** [comment]
It's just the reviewer reply (or developer reply from email) templates.

**Comment by erosman** [comment]
@eviljeff Is there any other file that needs to be changed?

**Comment by ValentinaPC** [comment]
Verified for developer and reviewer reply, using Fake mail logs from Admin Tools page.
Verified as fixed using FF53(Win 7).
Postfix screenshot:
![reply](https://cloud.githubusercontent.com/assets/15685960/25854114/9ca0c65c-34d7-11e7-8ba5-19c17a25598d.png)
