### ISSUE TITLE
No way to upload/create a WebExtension without Android support

### ISSUE THREAD

**Issue by Smile4ever** [mozilla/addons#348]
### Describe the problem and steps to reproduce it:

Submit a new Add-on:

1. How to Distribute this Version: On this site
2. Upload version: uncheck All and check Linux, Mac OS X and Windows
3. On the page where you can pick your categories, try NOT checking any categories for Android. It's simply impossible.
Because it's impossible to NOT check any categories for Android, I just checked a random one and continued.

### What happened?
I end up with an addon that does not support Firefox for Android, but every version states that it does support Firefox for Android, so I manually have to delete it every time from the version.

### What did you expect to happen?
- If I don't check Android as supported when uploading the first version of my WebExtension addon, the Android category selection shouldn't even be presented to me.
- Android should not be added to the version just because I selected a category for Android (that's just weird).

**Comment by muffinresearch** [comment]
@jvillalobos would be interested to hear your thoughts on this and if we should plan to make some changes here at some point. It seems like a valid issue.

**Comment by jvillalobos** [comment]
I makes sense that the default includes Android, but in this case the developer is explicitly saying they don't support Android, so this is a valid bug. #4868 is larger issue that we'll need to think about more, but I think we should fix this one soon. We don't want a bunch of broken WebExtensions on Android.

**Comment by ghostwords** [comment]
Hi, we ran into this issue with Privacy Badger: https://github.com/EFForg/privacybadger/issues/1276.

We publish Privacy Badger for Linux, macOS and Windows, but not yet Android. However, deselecting "all platforms" and "Android" and selecting the platforms above still results in [the latest Privacy Badger being made available for Android](https://addons.mozilla.org/en-US/android/addon/privacy-badger17/).

Privacy Badger should not be published for Android until we are ready to publish it for Android.

**Comment by jvillalobos** [comment]
Should have been fixed with mozilla/addons-server#4868
