### ISSUE TITLE
Investigate reducing session length

### ISSUE THREAD

**Issue by diox** [mozilla/addons#349]
To improve security, it would be interesting if we could make API tokens valid for a shorter period of time. To do that we need to investigate if we can get the client to keep the fxa assertion and re-send it as needed so that the user would not need to re-enter their password to re-authenticate and re-generate a new API token.

**Comment by diox** [comment]
cc @g-k

**Comment by g-k** [comment]
From IRC:

vbudhram> 
g-k: not 100% familiar with amo, but believe they would have to reenter their password

kumar>
g-k: I think we can use refresh tokens for this https://mail.mozilla.org/pipermail/fxacct-notices/2015-July/000000.html
g-k: that is, IIRC, the goal was to make it so an AMO user could reset their FxA password and invalidate all client connections sooner

**Comment by kumar303** [comment]
Here's another explanation of the use case for refresh tokens (I think it matches our case):
https://github.com/mozilla/fxa-oauth-server/issues/209

**Comment by diox** [comment]
(We do use refresh tokens nowadays, see https://github.com/mozilla/addons-server/issues/18149)
