### ISSUE TITLE
Can't delete own add-on reviews if they are on a deleted add-on

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla/addons#350]
If you review an add-on that is later deleted or removed by its author or an administrator, you cannot edit or delete the review from your site profile later. The delete link is unresponsive; the edit link pops a form but the submit button is unresponsive; and at no point is any error message ever shown.

Expected result: we should be able to delete reviews we have written; attempts to edit should fail with a message; and ideally, only I should be able to see my reviews of a removed add-on on my profile.

**Comment by muffinresearch** [comment]
@jvillalobos would be good to think about how this should ideally work. I wonder if reviews on deleted add-ons should simply be filtered out or indeed as the OP suggests shown only to the author.

**Comment by jvillalobos** [comment]
I think we should filter out reviews when the add-on is deleted, disabled by the dev (inactive), or disabled by Mozilla. Since some of the links and actions in the review will be broken, I think we should filter them out for the author as well.
