### ISSUE TITLE
Take English release notes if localized release notes are not filled in

### ISSUE THREAD

**Issue by Smile4ever** [mozilla/addons#352]
### What happened?
I added release notes to Translate Now 2.0.0 but they don't show up:
https://addons.mozilla.org/nl/firefox/addon/translate-now/versions/?page=1#version-2.0.0

That's probably because the Dutch translation has empty release notes.

### What did you expect to happen?
The English release notes are displayed if the localized (Dutch, in this case) release notes aren't available.

**Comment by diox** [comment]
Forward-duping to https://github.com/mozilla/addons-server/issues/7535 which explains the problem in detail.
