### ISSUE TITLE
There are addon pages with no license displayed

### ISSUE THREAD

**Issue by ian-kelling** [mozilla/addons#353]
For example: https://addons.mozilla.org/en-us/firefox/addon/feedly/

On the right side, there should be some text saying what the license of the addon is, as for most addons, but there is none.

**Comment by jvillalobos** [comment]
That add-on hasn't been updated since 2013, and we only started requiring a license until recently. Since we're phasing out most old add-ons by the end of the year, and they probably wouldn't be updated by their devs anyway, I don't think there's anything to do for them now.
