### ISSUE TITLE
Inform developer of the reason why a review was deleted

### ISSUE THREAD

**Issue by Shaxine** [mozilla/addons#354]
I think prior to a review deletion by an AMO Editor, the addon's developer should be informed the reason why the review was deleted (by user's request, abusive language, and such).

**Comment by jvillalobos** [comment]
What would the purpose of this email be? Just to inform, or do you want developers to be able to object to potential deletions?

**Comment by Shaxine** [comment]
It doesn't need to be a email I think, It can be something added to the already existing the sidebar feed, something like: 

> Review for [Addon Name] deleted. Reason: Abusive Language

And the purpose is purely informative.

The reason why I suggested this is because a few weeks ago a AMO Editor deleted what seemed to me like a good and valid review to one of my addons and I wasn't informed of the reason for such action.

**Comment by jvillalobos** [comment]
Admins and reviewers can delete reviews directly, without providing a reason. In cases reviews are flagged, we could show the reason it was flagged, though that isn't necessarily the reason for which it was deleted. While I can see this information could be useful to some developers, I don't think making the moderation UI more complex is a good price to pay.

I think that showing deleted reviews in the feed is a good idea, though. If developers want to know why they were deleted, they could then ask an admin to check for them.
