### ISSUE TITLE
Too bad extensions search results, difficult to find addon

### ISSUE THREAD

**Issue by vitaliylag** [mozilla/addons#355]
I try to find "XML Search Engines Exporter/Importer" extension.

1. Open Add-Ons.
2. Type "Search Importer". Finded many extensions with only 1 matched word but not needed extension.
3. Type "Search Engines Importer". Same result.
4. Type "XML Search Engines Importer". Same result.

And finally type full name: "XML Search Engines Exporter/Importer". Yeah, we find it! =)

Where did these many other extensions come from? I don't need it. I guess it is substring search. But I think extension with 4 matched words should be higher than extension with 1 matched word.

**Comment by muffinresearch** [comment]
It's the top result for me using step 2. 

Please re-open if you are still having trouble with this.

**Comment by vitaliylag** [comment]
Here is screenshots
![default](https://cloud.githubusercontent.com/assets/12641771/25785055/2311ccda-3380-11e7-94d2-f2852672897a.png)
![default](https://cloud.githubusercontent.com/assets/12641771/25785068/6dec52e8-3380-11e7-9798-ff921d93cf96.png)

**Comment by andymckay** [comment]
The difference between what you see in about:addons and AMO is a known issue. We intend to fix this by removing the XUL pages in about:addons and replacing them with AMO pages. That is being tracked here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1263313

**Comment by vitaliylag** [comment]
@andymckay, I don't see any difference. I tried to open AMO start page https://addons.mozilla.org/ru/firefox/ and then input the search query and I got the same result for all queries I metioned above.
