### ISSUE TITLE
Difficult to add new search plugin

### ISSUE THREAD

**Issue by vitaliylag** [mozilla/addons#356]
Step to reproduce:
1. Open search settings about:preferences#search
2. Click "Add more search engines"

Actual result:
- There's no field to type site name and find needed search plugin. If I type in global search I find not search plugins but all add-ons.

Expected result:
- I type site name in the field and find needed search plugin.

---

Also I would like to have "Create manually" button followed the "Add more search engines" button. After clicking "Create manually" I can specify name, icon and link (using {searchTerms} for query substitution). Other browsers have this feature. Maybe even allow users to edit plugins (at least manually created plugins).

**Comment by muffinresearch** [comment]
Thanks for the bug report. This is something we will look to resolve when the new frontend replaces the old one.

**Comment by jvillalobos** [comment]
We no longer support search engines on AMO.
