### ISSUE TITLE
Addon Validation Error -- for new version(s) of existing add-on

### ISSUE THREAD

**Issue by rafalyesware** [mozilla/addons#357]
Hi,

Since March 8th, we've been unable to to get the validator to accept a version of our Firefox extension, which has been available for close to 5 years (first AMO submission appears to be May 29th, 2012).  This has prevented at least 3 different versions from uploading, and possibly more.  The last failure was Mar 22nd, ~ 11:10pm EDT.

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

This was an upload of (several, different) new versions of an existing add-on.

* Whether your add-on is listed or unlisted.

Our add-on is unlisted.

* The URL where you submitted the add-on.

We attempted to submit via the APIs from a deploy script (to https://addons.mozilla.org/api/v3/addons/jid1-T5mdAATMX3urKA@jetpack/versions/2.0.551/  as well as from the AMO developer page for our addon (https://addons.mozilla.org/en-US/developers/addon/yesware/edit)

* The approximate time you submitted the add-on, with timezone.

The last failure via the script / API upload was Mar 22nd, ~ 10:55pm EDT (I don't have a more exact timestamp, since our script retries for a number of minutes... it could be up to 5-10 mins earlier).  The last attempt at uploading via AMO addon webpage was right after that, so Mar 22nd ~ 10:56pm.

**Comment by rafalyesware** [comment]
Attaching extension: 
[yesware.xpi.zip](https://github.com/mozilla/addons/files/866072/yesware.xpi.zip)

Attaching response from upload API:
[validate_response.json.zip](https://github.com/mozilla/addons/files/866075/validate_response.json.zip)

**Comment by rafalyesware** [comment]
Note that something does appear to be up with the validator, as my attempts to e.g. validate the last -accepted version (2.0.547) with the standalone `amo-validator` also causes a timeout, just as it does with the latest version I attempted to upload.  Clearly there is now some extension size that is too big for the validator to handle.

**Comment by jvillalobos** [comment]
I tried running it here: https://addons.mozilla.org/en-US/developers/addon/validate, and it finished. Does that work for you.

The add-on package is fairly large, but my money would be on the very large individual script files under `data`. I suggest splitting them into smaller scripts and giving it another try if the problem persists.

**Comment by rafalyesware** [comment]
It turns out that uploading it again via the API got it working.  I do notice that running it with the standalone {{addon-validator}} with {{--timeout -1}} takes > 3m30sec even for the previously-approved versions, so there's definitely a lot to be optimized.  Sadly, most of the large concatenated files in the data/ directory need to be injected whole into the appropriate UIs (e.g. all our GMail functionality into GMail tabs, all our Salesforce functionality into Salesforce tabs, etc.) and I am guessing breaking them up into smaller files would make the injection quite a bit more complex... but it's something to consider.

**Comment by rafalyesware** [comment]
Since I managed to upload it, my guess is this was some temporary load condition that prevented the upload... how long it takes the `addon-validator` and the fact that it doesn't complete in the standard 60sec timeout is another issue, I'm guessing.
