### ISSUE TITLE
Cannot download Add-ons for firefox on tablet

### ISSUE THREAD

**Issue by zenara** [mozilla/addons#358]
I am using a tablet of Lenovo A7600-H and I can't view sinhala fonts on my browser. So I am supposed to download and install the Add-on 'Sinhala fonts package by djmlog103'. 

When I touched the button of logging it did not work. It act as a label. 

Logging button did not show any progress of loading and there's no way of downloading the Add-on.

Also I tried this for other extensions and the result was the same.

1.Logging is not supported
2.Cannot download Add-on

https://addons.mozilla.org/en-US/android/addon/sinhala-fonts-package/

**Comment by TrishSutterPMP** [comment]
I'm also experiencing add-on down load issues.  On multiple devices and multiple connections:  On a Mac Desktop through ISP Infinity,  On a Windows desktop through Sprint Hotspot.  

Tried to install various ad blockers,  Most recently : https://addons.mozilla.org/en-US/firefox/addon/ad-aware-ad-block/?src=search

Upon clicking on "Add to Firefox" , I get the error message, "Download failed. Please check your connection."    

Should I open a new Issue for this or as this sound similar to mine does my issue belong here?  Help!

**Comment by jvillalobos** [comment]
@TrishSutterPMP You are most likely running into this: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
