### ISSUE TITLE
403 Unauthorized when attempting to download package.json

### ISSUE THREAD

**Issue by tjahjono** [mozilla/addons#360]
Attempting to right-click and download the `package.json` file for an extension returns a **403 Unauthorized** error, despite being able to download other files in the directory. I was attempting to [download this file](https://addons.mozilla.org/en-US/firefox/files/browse/519220/file/package.json) (At the bottom, there is a link to _Download package.json_) with `right-click | Save Link As ...`

**Comment by muffinresearch** [comment]
@tjahjono do you have a link to the page you're referring too that contains the link?

**Comment by tjahjono** [comment]
It used to be here https://addons.mozilla.org/en-US/firefox/files/browse/519220/, but I can't seem to browse the source files any longer.

**Comment by diox** [comment]
The file browser is no longer public by design.
