### ISSUE TITLE
[Review Tools] Missing files in the display

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#364]
There was a previous bug for this issue and I presume it was fixed.
I had to download a XPI to check and I noticed there are files in the XPI that were not displayed by the review tools.

Example:
```
Contents: https://addons.mozilla.org/en-US/firefox/files/browse/617150/
Compare: https://addons.mozilla.org/en-US/firefox/files/compare/617150...370945/
```

Previous upload is the same:
`https://addons.mozilla.org/en-US/firefox/files/browse/370947/`

At first glance, all displays fail to show `bootstrap.js` at the root level.

The file listing is actually there, but it is hidden

```
<li>
    <a class="file diff known tooltip" data-delay="0" href="/en-US/firefox/files/compare/617150...370945/file/bootstrap.js" data-short="bootstrap.js" title="Identified:
    Library: Jetpack 0.0.11

    Original path: ./data/bootstrap.js"><span>bootstrap.js</span></a>
</li>
```

**Comment by wagnerand** [comment]
I see the `bootstrap.js` file in the viewer. You don't happen to have the `Hide known files` checkbox enabled?

**Comment by erosman** [comment]
That was it.. it was selected by mistake
