### ISSUE TITLE
Leaderboard shows new reviewers with blank names

### ISSUE THREAD

**Issue by spoji** [mozilla/addons#365]
### Describe the problem and steps to reproduce it:
With the proper credentials, visit https://addons.mozilla.org/en-US/editors/leaderboard/

### What happened?
Some weeks ago, the list in there was clean and wasn't showing any reviewers with 0 points. Those with "no name" were also not showing up.

### What did you expect to happen?
A clean list, as it was before. Old and non-active reviewers were not part of this list. Reviewers with 0 point were not part of this list as well.

**Comment by eviljeff** [comment]
old reviewers is fixed with https://github.com/mozilla/addons-server/issues/5792
empty names is logged as https://github.com/mozilla/addons-server/issues/5809 now, so deferring to that issue.
