### ISSUE TITLE
Localize Discopane video with subtitles

### ISSUE THREAD

**Issue by zelitomas** [mozilla/addons#367]
Hello,

in the new AMO frontend (on about:addons), there is a video describing the
basic idea of addons. The problem is that although everything on the page
can be localized, the video is still in English.

Would it be possible to add some translatable subtitles to it, which would
be automatically shown for non-english locales?

Cheers,
Tomáš Zelina

Related mail communication:
* https://mail.mozilla.org/pipermail/dev-addons/2016-October/001994.html
* https://mail.mozilla.org/pipermail/dev-addons/2016-October/001995.html
* https://mail.mozilla.org/pipermail/dev-addons/2016-October/001998.html
* https://mail.mozilla.org/pipermail/dev-addons/2017-March/002673.html
* https://mail.mozilla.org/pipermail/dev-addons/2017-March/002687.html

**Comment by kumar303** [comment]
Thanks for filing, this sounds like a useful feature and seems doable.

From the email thread:

> According to MDN, the `<video>` elements you use can have [`<track>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track) tags which can hold subtitles in [WebVTT](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API).

**Comment by zelitomas** [comment]
Good afternoon,

I've finished Czech subtitles and English transcription, so you have something to test your implementation with - can be downloaded here [here](http://test.zelitomas.cf/subtitletest/)

Have a nice day
Tomáš Zelina

**Comment by kumar303** [comment]
Thank you @zelitomas ! This is really helpful.

I'll attach the subtitle tracks here for safe keeping: 
[video-subtitle-example.zip](https://github.com/mozilla/addons/files/1038701/video-subtitle-example.zip)


And here is an example of the video tag:

```html
<video controls>
    <source src="firefoxAddons.webm">
    <track kind="subtitles" src="addon-cs.vtt" srclang="cs" label="Čeština" default>
    <track kind="subtitles" src="addon-en-US.vtt" srclang="en" label="English" default>
</video>
```

**Comment by peiying2** [comment]
@muffinresearch I am here at a community meetup, and have the pleasure of meeting with @zelitomas who brought up this unresolved issue. Could you let us know the ETA of implementing it?

**Comment by muffinresearch** [comment]
@peiying2 It's not currently on our roadmap, so I don't have an ETA. 

It's definitely something that we'd happily review a patch for, the only other part to this is AFAIK pontoon doesn't directly support vtt files does it? 

If we did land an implementation translations would need to happen directly in our tree. This point doesn't stop this happening it's just something else to consider.

**Comment by willdurand** [comment]
#5323 removes the video.
