### ISSUE TITLE
lastpass addon

### ISSUE THREAD

**Issue by DuaneW2017** [mozilla/addons#368]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Tried to install it, clicked install button.
### What happened?
Page not found error.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/en-US/android/addon/lastpass-password-manager/

**Comment by EnTeQuAk** [comment]
The link works for me, what device are you using? It could happen that the add-on is not available for the platform you're using, in that case, please contact the add-on author.
