### ISSUE TITLE
Can not access / view source code

### ISSUE THREAD

**Issue by Pfiver** [mozilla/addons#370]
### Describe the problem and steps to reproduce it:
Following the provided link leads to a HTTP 403 kind of error message.

### What happened?
I received an error message: 
![image](https://cloud.githubusercontent.com/assets/503624/24820284/885f5d46-1be8-11e7-8d4b-f1561aaba1a4.png)

### What did you expect to happen?
I wanted to see the source code (and potentially contribute a new feature to the extension).

### Anything else we should know?
See screenshot above, taken after following the "view source" link here:
https://addons.mozilla.org/en-US/firefox/addon/copy-all-tab-urls-we/versions/

**Comment by EnTeQuAk** [comment]
Please see https://mail.mozilla.org/pipermail/dev-addons/2017-April/002713.html fore more details. This is a temporary measure to fix an ongoing performance problem we had server-side and we disabled the source-viewer for public until it's properly resolved. It will be re-enabled, we just don't have a date for that yet.

**Comment by gopat** [comment]
Oh, unfortunate indeed.

I hope it gets resolved sooner than later, i would enjoy my open source add-ons better if open source! (some of them do not publish the source outside AMO).

But i guess that with some non-trivial issues you can't really know!
Don't get discouraged and keep up the good work!

**Comment by refola** [comment]
Why is this issue closed?!? The problem is trivially reproducible **right now**, and acting as a substantial barrier to people accessing many addons' source code to which all users have the right under, e.g., the Mozilla Public License.

**Comment by jvillalobos** [comment]
The source code viewer only displays the contents of the XPI. You can download the XPI, decompress it, and inspect it. It shouldn't be such a significant barrier. Ideally, the developer should have links to a repository where it is much easier to look at the code and changes happening to it.
