### ISSUE TITLE
Cannot upload extension as unlisted one

### ISSUE THREAD

**Issue by alexesprit** [mozilla/addons#372]
### Describe the problem and steps to reproduce it:
 I'm trying to upload new version of an extension and I choose "On your own" option. After uploading and clicking on "Sign addon" button I get this error:
![image](https://cloud.githubusercontent.com/assets/1119267/24973837/e80d43be-1fc8-11e7-8383-67c9b2b60cd8.png)

There's no additional information on the page (e.g. error code, description etc).

Steps to reproduce:
1. Click on "Upload New Version" URL.
2. Choose "On your own" option and upload zip file.
3. Press "Sign add-on" button.

### What happened?

The "Oops! We had an error" error is shown.

### What did you expect to happen?

The new version is uploaded as unlisted extension successfully.

### Anything else we should know?

I reproduced this error in both Firefox and Chrome. I also tried to reauthenticate, but it didn't help.

The addon I'm trying to upload: https://addons.mozilla.org/en-US/developers/addon/web-scrobbler/
The extension UUID: `{799c0914-748b-41df-a25c-22d008f9e83f}`

I also attached the zip file I tried to upload. Perhaps, something is wrong with it, but I uploaded almost the same zip as listed and it was uploaded w/o any errors.

[web-scrobbler.zip](https://github.com/mozilla/addons/files/917521/web-scrobbler.zip)

**Comment by diox** [comment]
Hi, this has already been reported as https://github.com/mozilla/addons-server/issues/5124 ; it was fixed on our master branch, it will go in production tomorrow around 19:00 UTC.
