### ISSUE TITLE
Developer replies from amo-editors mailing list are not stripped down properly

### ISSUE THREAD

**Issue by spoji** [mozilla/addons#374]
### Describe the problem and steps to reproduce it:
With reviewer credentials, visit https://addons.mozilla.org/en-US/editors/review/jidesha-bs-os and read the first "Developer Reply" section of version 0.0.1

### What happened?
There are some email information at the end of the "Developer Reply" : "Le 13/04/2017 à 15:24, amo-editors@mozilla.org a écrit :"

### What did you expect to happen?
This last sentence after "Regards," shouldn't be there.

### Anything else we should know?
First time I'm seeing this issue. Maybe it's because the developer that replied is using a French email client and we don't strip down the message properly because of that?

**Comment by muffinresearch** [comment]
@eviljeff could you confirm if this bug is still an issue? Looks like the link in the OP is no longer working.

**Comment by spoji** [comment]
If this can help, the mailing list reply was from 

reviewreply+689303656f0f4a8dab312a99b883d724@addons.mozilla.org

received on 2017-04-19

**Comment by eviljeff** [comment]
> If this can help, the mailing list reply was from

It's not a great idea to go sharing those reply addresses or anyone on the internet will be able to send a reply and impersonate you.  (In this case the add-on is probably deleted.  Hopefully)

**Comment by spoji** [comment]
Sorry about this. I can remove it from this thread if you want me to. It would seem the add-on was deleted from the dev.

**Comment by muffinresearch** [comment]
@spoji I redacted the comment to be on the safe side. @eviljeff let me know if you need the data.

**Comment by eviljeff** [comment]
I'd be a good to get another example of this in action, but generally: the reply parsing is very basic so I can believe it wouldn't be able to handle anything particularly complicated.  And I'd like to err on the side of including text that may be a quote rather than dropping a valid reply.  
Is this a frequent and significant problem?

**Comment by spoji** [comment]
Happened to me only once. It's not a significant issue at all. It's really minor and not really important.
