### ISSUE TITLE
Unable to download self-hosted addon

### ISSUE THREAD

**Issue by mtjacobs** [mozilla/addons#375]
I'm trying to get an add-on signed for self hosting.  The process drops me at a page (in my case https://addons.mozilla.org/en-US/developers/addon/gpsio/versions/submit/2083548/finish) that says "Version Signed - You’re done! This version is signed and ready to for self-distribution. You can download it by clicking the button below."

However the download link (in my case, https://addons.mozilla.org/firefox/downloads/file/632690/gpsio-0.0.5-an+fx.xpi?src=devhub) generates a 404 error.  I tried a second time with a new version of the add-on and got the same error, as well as trying multiple browsers, so it doesn't look like a one-off hiccup.

**Comment by diox** [comment]
Hi,

This is a known problem for add-ons that are set to "Invisible" - that particular setting is not useful for purely unlisted add-ons (they should already be invisible to the outside world, if they have no listed versions), but it causes their files to 404 for a limited time after upload. Fortunately for you the problem should fix itself automatically in a matter of hours (we've got a cronjob that fixes the paths of the files that are in a wrong place)

This has already been reported as https://github.com/mozilla/addons/issues/324 so I'm closing your issue as duplicate. Thanks!
