### ISSUE TITLE
"View the source" links on addon pages lead to a 403 error page

### ISSUE THREAD

**Issue by flussence** [mozilla/addons#378]
### Describe the problem and steps to reproduce it:

* Went to (e.g.) https://addons.mozilla.org/en-GB/firefox/addon/stylrrr/?src=api
* Expanded the "Version Information" box at the bottom
* Clicked the aforementioned link (which points at https://addons.mozilla.org/en-GB/firefox/files/browse/511362/)

### What happened?

![screen shot 2017-04-24 at 20 16 57](https://cloud.githubusercontent.com/assets/409860/25354566/e345093a-2922-11e7-9a90-ec5d628d0da8.png)

Browser console says this is a 403 response.

### What did you expect to happen?

What it says on the link

### Anything else we should know?

Happens on all other addon pages I tried too. I have cookies disabled.

**Comment by diox** [comment]
Hi,

We're aware, it has been temporarily disabled for the general public because of performance issues. See https://github.com/mozilla/addons/issues/370#issuecomment-292887844
