### ISSUE TITLE
Increase maximum allowed width of Lightweight themes Add-ons Themes

### ISSUE THREAD

**Issue by heubergen** [mozilla/addons#379]
### Describe the problem and steps to reproduce it:
Use a very high screen resolution like 3440x1440 or 3840x2160
Start Firefox
Install a Lightweight theme like this one (https://addons.mozilla.org/en-US/firefox/addon/global-spirit-2/)

### What happened?
You see that on the left corner the theme background stops (because it's maximum 3000px)

### What did you expect to happen?
The theme background should across the whole width.

### Anything else we should know?
My request is specific to increase the maximum allowed width in the upload process here (https://addons.mozilla.org/en-US/developers/theme/submit)

I hope I'm here in the correct repo.

**Comment by jvillalobos** [comment]
A new themeing API is being developed which will be more flexible than what we currently support for lightweight themes. You can find some details in [this blog post](https://blog.mozilla.org/addons/2017/02/24/improving-themes-in-firefox/). We don't plan to make any changes to the existing lightweight theme support, so I'm closing this issue.
