### ISSUE TITLE
Can't view the source of open source extensions

### ISSUE THREAD

**Issue by UserNaem** [mozilla/addons#380]
### Describe the problem and steps to reproduce it:
1. Go to https://addons.mozilla.org/en-US/firefox/addon/minimizetotray-revived/versions/
2. Try to view the source code of any version, i.e. https://addons.mozilla.org/en-US/firefox/files/browse/479084/
### What happened?
Error message:

Oops! Not allowed.

You tried to do something that you weren't allowed to.

### What did you expect to happen?
I wanted to see the extension's source code.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/en-US/firefox/addon/minimizetotray-revived/versions/
![image](https://cloud.githubusercontent.com/assets/21028464/25371438/35f7e97c-29aa-11e7-9d70-544686b4def3.png)
![image](https://cloud.githubusercontent.com/assets/21028464/25371419/28f5f656-29aa-11e7-837e-e8a175d4b957.png)

Also, for some reason there is no "View the source code" button under extensions released under GPL v3.0.

**Comment by diox** [comment]
Hi,

This is a known issue, see https://github.com/mozilla/addons/issues/370#issuecomment-292887844
