### ISSUE TITLE
Message stating that  add-on has been probably damaged, but local install is fine

### ISSUE THREAD

**Issue by juozhe** [mozilla/addons#381]
### Describe the problem and steps to reproduce it:
I've published a firefox add-on, still to be reviewed, available at
https://addons.mozilla.org/en-US/firefox/addon/panlatin/
When I tested it in Developer Firefox 54, it worked fine.
I tried to test it with regular Firefox 53.0. It reported that it's not yet reviewed and allowed me to start adding it. However, after downloading, it reported an error.

### What happened?
I can't install a firefox add-on.

### What did you expect to happen?
To be able to install the add-on.

### Anything else we should know?
In Developer Firefox 54, I can install add-on locally from the same unpacked .zip file. I attach the file
[panlatin-1-1.zip](https://github.com/mozilla/addons/files/954569/panlatin-1-1.zip)

When I visited the add-on with a different browser, I saw the download address
https://addons.mozilla.org/firefox/downloads/file/636617/panlatin-1.1-an+fx.xpi?src=dp-btn-primary
that allowed me to see the probably contents sent to Firefox. When I unpacked locally this .xpi file, the add-on worked fine in Developer Firefox.

**Comment by muffinresearch** [comment]
@jvillalobos this is expected behaviour isn't it for an un-reviewed add-on?

**Comment by jvillalobos** [comment]
Yes, it's expected edge behavior if the add-on is a WebExtension, hasn't been signed, and doesn't have an ID in the manifest.
