### ISSUE TITLE
Cannot change information of addon

### ISSUE THREAD

**Issue by AykutCevik** [mozilla/addons#382]
I tried to add an addon (webextension) with l10n support but with only one locale. I then tried to add details about my addon which failed.

## Steps to reproduce
Go to the details page of your freshly uploaded addon by visting https://addons.mozilla.org/de/developers/addon/((ADDONID))/edit

Try to edit the first fields and save them:
![image](https://cloud.githubusercontent.com/assets/1965251/25395513/933a483c-29e1-11e7-972d-9fa431223231.png)

![image](https://cloud.githubusercontent.com/assets/1965251/25395238/af47befc-29e0-11e7-8688-5ed48147a07e.png)

Logs in the developer console when loading the page:

> Uncaught TypeError: z.refreshL10n is not a function
>     at devhub-min.js?build=24985b60-58f8c90d:1
>     at HTMLDivElement.addonFormSubmit (devhub-min.js?build=24985b60-58f8c90d:1)
>     at Function.each (preload-min.js?build=24985b60-58f8c90d:1)
>     at p.fn.init.each (preload-min.js?build=24985b60-58f8c90d:1)
>     at p.fn.init.<anonymous> (devhub-min.js?build=24985b60-58f8c90d:1)
>     at HTMLDivElement.<anonymous> (preload-min.js?build=24985b60-58f8c90d:4)
>     at Function.each (preload-min.js?build=24985b60-58f8c90d:1)
>     at p.fn.init.each (preload-min.js?build=24985b60-58f8c90d:1)
>     at Object.<anonymous> (preload-min.js?build=24985b60-58f8c90d:4)
>     at u (preload-min.js?build=24985b60-58f8c90d:1)
>     at Object.fireWith [as resolveWith] (preload-min.js?build=24985b60-58f8c90d:1)
>     at C (preload-min.js?build=24985b60-58f8c90d:3)
>     at XMLHttpRequest.n (preload-min.js?build=24985b60-58f8c90d:3)

Logs, when saved:

> Uncaught TypeError: z.refreshL10n is not a function
>     at devhub-min.js?build=24985b60-58f8c90d:1
>     at HTMLDivElement.addonFormSubmit (devhub-min.js?build=24985b60-58f8c90d:1)
>     at Function.each (preload-min.js?build=24985b60-58f8c90d:1)
>     at p.fn.init.each (preload-min.js?build=24985b60-58f8c90d:1)
>     at Object.<anonymous> (devhub-min.js?build=24985b60-58f8c90d:1)
>     at Object.n [as success] (common-min.js?build=24985b60-58f8c90d:1)
>     at u (preload-min.js?build=24985b60-58f8c90d:1)
>     at Object.fireWith [as resolveWith] (preload-min.js?build=24985b60-58f8c90d:1)
>     at C (preload-min.js?build=24985b60-58f8c90d:3)
>     at XMLHttpRequest.n (preload-min.js?build=24985b60-58f8c90d:3)

I tried everything which also includes setting the values of the input field with the help of the DOM inspector with no success. 

Any ideas? Thanks!

**Comment by AykutCevik** [comment]
Also fields for the description and name are missing on the "https://addons.mozilla.org/de/developers/addon/((ADDONID))/versions/submit/2088402/details" page:
![image](https://cloud.githubusercontent.com/assets/1965251/25406443/ed1f98e6-2a06-11e7-8411-3922960fc360.png)

**Comment by AykutCevik** [comment]
Anyone addressing this issue? I can't upload my new add-on. Is there a known workaround which I can use in the meanwhile?

Thank you for your help.

**Comment by muffinresearch** [comment]
@EnTeQuAk do you know of a workaround to this? Would be good to understand what's going wrong here as it seems that problems related to editing add-ons with locales come up fairly regularly.

**Comment by ValentinaPC** [comment]
Maybe is #701

**Comment by AykutCevik** [comment]
@ValentinaPC can't access #701 (not found)

**Comment by EnTeQuAk** [comment]
I'll look into this asap, I've seen the JavaScript error before but couldn't reproduce it locally for some reason. As for workarounds, do you have a default-locale set? What locale does your add-on have and what language has your browser or rather, with what language are you browsing AMO?

That'd help debugging this I think.

**Comment by AykutCevik** [comment]
@EnTeQuAk of course!
* default-locale of the add-on: *en* (add-on can be found [here](https://github.com/AykutCevik/IDN-Safe))
* It only includes "en" at the moment.
* My browser and the AMO page it set to german.

Thank you.

**Comment by AykutCevik** [comment]
@ValentinaPC sorry, didn't see your update on the post. Checked your link, thank you, but the workaround does not work on my extension since I already set the[ default_locale entry](https://github.com/AykutCevik/IDN-Safe/blob/master/manifest.json#L10). 
Any other ideas?

**Comment by AykutCevik** [comment]
Any progress on this or something I can help with? Do you need any further information? Or maybe you've another workaround which may work?

**Comment by AykutCevik** [comment]
Hi guys, I don't want to bother you but I would really appreciate a workaround for this. Still can't upload any localized extension with only english on a German developer hub.

**Comment by AykutCevik** [comment]
I was now able to upload the add-on. Deleting the "init"-fields in the inspector and renaming the localization fields from "en" to "de" did the job. Seems to be a problem with my default locale of my account (de) and the locale of the addon (en). Maybe this will help you to find the bug :)
