### ISSUE TITLE
File viewer does not properly display leading spaces in first line

### ISSUE THREAD

**Issue by scfc** [mozilla/addons#383]
When looking at a standard `COPYING` for GPL 3 at https://addons.mozilla.org/de/firefox/files/browse/636912/file/COPYING#top with Firefox 53.0, the file viewer does not properly display the leading spaces in the first line:
![liveatc-copying](https://cloud.githubusercontent.com/assets/798568/25479450/6fa268e2-2b34-11e7-9712-74d33a5d3230.png)

Leading spaces in subsequent lines seem to be marked up with `<code class="plain spaces>`, but not in the first line where then a proportional font for these spaces is selected.

**Comment by scfc** [comment]
further details

**Comment by jvillalobos** [comment]
This file viewer is going to be discontinued soon, and we removed the option for end users and developers to access the source code of extensions listed on the site. Developers should link to their code repositories if they want users to browse their code.
