### ISSUE TITLE
The view source code link is broken

### ISSUE THREAD

**Issue by abenkovskii** [mozilla/addons#384]
### Describe the problem and steps to reproduce it:
I wanted to inspect the source code of the [Smart HTTPS (revived)](https://addons.mozilla.org/en-US/firefox/addon/smart-https-revived/) add-on.
1. I navigated to [this page](https://addons.mozilla.org/en-US/firefox/addon/smart-https-revived/)
2. Scrolled to the botom
3. Clicked "version information"
4. Clicked the "View source code" link

### What happened?
I saw a page saying "Oops! Not allowed. You tried to do something that you weren't allowed to".

### What did you expect to happen?
I expected to see the source code of the add-on.

### Anything else we should know?
* I currently don't have any add-ons installed so this can't be the result of an add-on messing something up
* The result doesn't depend on whether I'm logged in to addons.mozilla.org or not
* The add-on license is Mozilla Public License, version 2.0. I might be wrong about this, but I'm pretty sure this license requires source code to be disclosed.

**Comment by refola** [comment]
This is the same as bug #370, which is perplexingly closed despite the issue not being resolved.

**Comment by diox** [comment]
It's also the same as https://github.com/mozilla/addons-server/issues/5135 which is opened.
