### ISSUE TITLE
Please clearly comply with the license for copyleft (MPL, etc) open source add-ons

### ISSUE THREAD

**Issue by refola** [mozilla/addons#385]
### Describe the problem and steps to reproduce it:
There is no obvious working way to access the source code of addons while the source viewer is broken (see issue #370). Going to any open source addon's page, clicking "version information", and then clicking "view the source" currently doesn't give access to the source.

### What happened?
> # Oops! Not allowed.
> 
> You tried to do something that you weren't allowed to.

### What did you expect to happen?
While the source viewer is broken, I expect there to be a .zip/.tar.*/.whatever archive to download the source.

### Anything else we should know?
I am not a lawyer, but I'm pretty sure that this would be the simplest way to comply with the license of copyleft (MPL, GPL, etc) licensed addons which Mozilla is distributed. Even if it's technically okay to merely honor snail-mailed requests, choosing to continue this situation is counter to the entire opensource ethos Mozilla has cultivated for over a decade.

**Comment by diox** [comment]
While I agree that the source viewer being broken is a problem, I think this is a bit of an exaggeration, and doesn't warrant an extra issue. Go to any open-source add-on page, click "save link as" on the download button, and there, you have the source code for this add-on. Alternatively, install it, look into your firefox profile folder, and you'll find the add-on, same result.

**Comment by refola** [comment]
> you have the source you have the source code for this add-oncode for this add-on

I acknowledge that this is true for add-ons written directly in JavaScript and published without further processing. However, this would not apply to any add-on which is minified or written in a language that compiles to JavaScript (e.g., CoffeScript or ClojureScript).

**Comment by wagnerand** [comment]
> However, this would not apply to any add-on which is minified or written in a language that compiles to JavaScript

The file viewer literally shows the contents of the XPI file that you'd install if you clicked "Add to Firefox", so you'd see exact same result if you followed @diox's suggestion.
Providing unprocessed source code to comply to a license that demands that is the add-on developer's responsibility.
