### ISSUE TITLE
AMO claims 1 user review, but no reviews visible

### ISSUE THREAD

**Issue by gcp** [mozilla/addons#387]
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/en-US/firefox/addon/wxif/

This shows: "1 user review". 

But also: "This add-on has not yet been reviewed."

Clicking the "1 user review" does nothing.

**Comment by diox** [comment]
This can happen sporadically when a review is deleted (because of spam, etc), the task to update the total reviews count either not fires or fires too early. It will correct itself the next time somebody reviews that add-on.
