### ISSUE TITLE
"Edit Information" screen text truncated by long words

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons#391]
Prerequisites:
User is logged with an admin account.

Steps to reproduce:
1. Click on any addon.
2. Click on the "Manage" button.
3. In the "Basic Information" section click on the "Edit" button.
4. In the "Summary" section introduce a 85+ letter word.
5. Click on the "Save Changes" button.

Expected results:
The word is wrapped.

Actual results:
The word is truncated to the right.

Notes/Issues:
Issue is  reproducing on AMO-dev. AMO-stg
Verified on FF53(Win 10 64Bit).
This issue also truncates any other fields on the page even if they do not have long word is them, ex. "Tags" field.
Before:
![before](https://cloud.githubusercontent.com/assets/28138132/25746941/5a30e292-31ae-11e7-8438-c160942d9219.PNG)

After:
![after](https://cloud.githubusercontent.com/assets/28138132/25746951/62c82618-31ae-11e7-9fa4-6cf46bae4cb6.PNG)

**Comment by muffinresearch** [comment]
@SVSanta to clarify what do the before and after screenshots relate to? Before pressing save and after?

**Comment by SVSanta** [comment]
The before is with no long words and the after has the 85 character word added in the summary section. This was done in order to show how it truncates the text in the tags section even if no changes were made to it.

**Comment by ValentinaPC** [comment]
This can degenerate in public pages.
Please see screenshot:
![2017-05-17_1649](https://cloud.githubusercontent.com/assets/15685960/26157085/ec38c3d2-3b20-11e7-8d35-88b6e355c123.png)
