### ISSUE TITLE
"View the source" does not work for other's add-ons

### ISSUE THREAD

**Issue by hckr** [mozilla/addons#392]
### Describe the problem and steps to reproduce it:
1. Open an ADO page of an add-on which has it's source set to be publicly viewable and isn't yours (e.g. [this](https://addons.mozilla.org/en-US/firefox/addon/facebook-post-screenshot/#detail-relnotes)).
2. Click on "View the source" link.

### What happened?
Error showed up:
> Oops! Not allowed.
>
>You tried to do something that you weren't allowed to.

### What did you expect to happen?
Add-on's code browser to show up.

**Comment by diox** [comment]
Hi,

The file viewer has been disabled for now because of performance issues. You can follow mozilla/addons-server/issues/513 if you want to know when it will be enabled again.

**Comment by hckr** [comment]
Shouldn't the message be more informative then? Currently it suggests the lack of privileges.

**Comment by FliegendeWurst** [comment]
@diox Did you mean to link mozilla/addons-server#5135?

**Comment by diox** [comment]
Yes thanks, I've edited my message.
