### ISSUE TITLE
Cannot submit private addon for signing using legacy apis

### ISSUE THREAD

**Issue by azhao12345** [mozilla/addons#393]
### Describe the problem and steps to reproduce it:
I have an addon that absolutely must use legacy apis that I want to distribute privately.  The amo website will not allow me to sign it.

### What happened?
Error with test.xpi
100% complete · 5.20 KB of 5.20 KB
Your add-on failed validation with 1 error.

    Starting with Firefox 53, new extensions on this site can only be WebExtensions.

See full validation report

### What did you expect to happen?
get the addon signed

### Anything else we should know?
This addon is for private distribution.  It absolutely must use legacy apis because the functionality is not available in the new apis

**Comment by jvillalobos** [comment]
This is by design and was announced [a while back](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/), with warnings on AMO for some time before making it final.

You can find ways to run unsigned add-ons in [this doc](https://wiki.mozilla.org/Addons/Extension_Signing).

**Comment by andrewzhaosc** [comment]
For the addons that will be used for private usage and not public distribution, they should not be restricted to AMO requirements.  The old api is still supported for over a year on ESR, and webextensions does not support the proper functionality.

**Comment by azhao12345** [comment]
For the addons that will be used for private usage and not public distribution, they should not be restricted to AMO requirements.  The old api is still supported for over a year on ESR, and webextensions does not support the proper functionality.

Using the old api will give a long time to evaluate other options or wait for the webextension api to improve.

Using unbranded builds is not an option unless there are unbranded builds available on the ESR branch

**Comment by jvillalobos** [comment]
ESR already has the same pref to deactivate signing enforcement, as explained in the wiki.

**Comment by andrewzhaosc** [comment]
@jvillalobos  It doesn't work on ESR 52

**Comment by andrewzhaosc** [comment]
ok my bad.  It must have been some sort of other failure.  I can verify now that 52 ESR allows unsigned addons, so this can be resolved

**Comment by andrewzhaosc** [comment]
Though it will be helpful to document this capability, as all references I can find online refer to version 45 specifically

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1424844

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
@jvillalobos yeah it doesn't work her either.

**Comment by jvillalobos** [comment]
It's possible to upload add-ons that support ESR as long as you use the `strictCompatibility` flag to restrict its compatibility to pre-57 versions of Firefox.
