### ISSUE TITLE
AMO is unstyled on Firefox on Windows 10 in a VM on Mac

### ISSUE THREAD

**Issue by autonome** [mozilla/addons#394]
### Describe the problem and steps to reproduce it:

1. Run Firefox 53.0.2 on Windows 10 in a VirtualBox VM on Mac
2. Open any AMO page

### What happened?

No CSS is applied

### What did you expect to happen?

Looks all stylish.

### Anything else we should know?

If this happens in a VM, is quite likely it also happens on super slow computers.

**Comment by eviljeff** [comment]
I've accessed AMO in my VM before and it's been styled.  Sure this isn't some random network issue?

**Comment by autonome** [comment]
No network issues for the rest of the internet*, just AMO.

(* I haven't finished testing *all* of the internet though, it's gonna take
some time...)

**Comment by autonome** [comment]
I'm in Taiwan. AMO over the same connection but *not* in a VM works fine.

I recommend testing over a throttled connection on a slow computer.

**Comment by autonome** [comment]
Rebooted the VM and everything worked. The fact that it was fine in Edge and not Firefox is weird, and probably points to a Firefox bug.
