### ISSUE TITLE
no longer able to find most recently updated/created add-ons on Android

### ISSUE THREAD

**Issue by jawz101** [mozilla/addons#395]
https://addons.mozilla.org/en-US/android/extensions/

The old mobile site let the user easily find recently maintained add-ons as it used to have the "most users", "highest rated", "recently updated" filters.  This is very helpful when trying to weed out unmaintained add-ons.

**Comment by eviljeff** [comment]
@tofumatt is this planned?

**Comment by tofumatt** [comment]
I think providing those filters would be useful. I'm not sure it's in the mocks but if not I think I'd add it.

@jawz101 Thanks for the report, we'll keep this in mind as we add to the redesign. You can sort in the main app search but not yet here. I think we should be able to fix that without too much trouble. 👍
