### ISSUE TITLE
[Enhancement] Please add Sort by Active Users to Manage My Submissions

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#396]
It would be useful to have Sort by **Active Users** in addition to:

```
https://addons.mozilla.org/developers/addons

Sort by:

    Name
    Updated
    Created
    Downloads
    Rating
```

**Comment by erosman** [comment]
Can you point me to the relevant file and I will have a look?

**Comment by EnTeQuAk** [comment]
The filtering is mostly being implemented in `devhub/views.py:addon_listing` which references `AddonFilter` or `ThemeFilter`

We don't have active users stored directly on an add-on so this is quite hard to implement. What we have is `average_daily_users` which would allow you to implement that in a similar way.

**Comment by yfdyh000** [comment]
https://github.com/mozilla/addons-server/issues/6235

**Comment by erosman** [comment]
> We don't have active users stored directly on an add-on so this is quite hard to implement. What we have is average_daily_users which would allow you to implement that in a similar way.

That is fine. In fact the reason I said "active users" was that the `https://addons.mozilla.org/en-US/developers/addons` states it as such ;)

> 797 weekly downloads
> 1,161 active users
