### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by hackademix** [mozilla/addons#397]
Since yesterday (about 8 hours now) I cannot upload a new NoScript version,

https://noscript.net/downloads/noscript-5.0.5rc1-unsigned.xpi

* It's a new file in an existing version
* Listed
* Submission https://addons.mozilla.org/en-US/developers/addon/noscript/versions/submit/
* Last upload attempt: 5:35 UTC

Tried also to re-upload the latest stable 5.0.4, already validated and published, and now I get exactly the 
same result: definitely something changed and broken on the server side.

[noscript-5.0.5rc1.zip](https://github.com/mozilla/addons/files/1006679/noscript-5.0.5rc1.zip)

**Comment by EnTeQuAk** [comment]
So I tried this locally and can verify that this is the exception we see in our system: 

```Exception: Bad GUID or version provided for version range: 6.0a1``` which is raised by our amo-validator for some reason, didn't yet figure out why this is suddenly happening.

**Comment by muffinresearch** [comment]
@wagnerand @jvillalobos any ideas on why this might be happening?

**Comment by EnTeQuAk** [comment]
So I ran this locally against amo-validator directly and now I'm getting:

The maximum version that was specified is not an acceptable version number for the Mozilla product that it corresponds with. Version "*" isn't compatible with "seamonkey". Please check the list of valid versions at: https://addons.mozilla.org/en-US/firefox/pages/appversions/

Which sounds like it's a problem in the install.rdf rather than AMO or our validator.

**Comment by EnTeQuAk** [comment]
Interestingly enough, the appversions page shows `*` but amo-validator doesn't have `*` for seamonkey in it's app_versions.json file.

**Comment by EnTeQuAk** [comment]
@hackademix so, could it be that one of the changes of the versions you're uploading is that now you have a `maxVersion` of `*` for SeaMonkey? So if you set that to whatever you used before it should work imho.

**Comment by hackademix** [comment]
Nope, and as stated in the original report, reuploading 5.0.4 stable (already approved, hence previously validated) causes the same error now. However later (AFK right now) I'll try playing with maxVersion stuff.
-- G

**Comment by wagnerand** [comment]
@hackademix We had to add a `maxVersion` of `*` to AMO for SDK add-ons. A non-SDK add-on should never use `*`.

**Comment by hackademix** [comment]
@wagnerand OK, I've put 2.53 as the Seamonkey max version in 5.0.5rc2 which I've tried to upload 5 minutes, but as expected this is not the culprit the validator bug persists (otherwise 5.0.4 wouldn't have been published).
FWIW, along with the very informative "An unexpected error has occurred" message, the validator highlights these lines:
`chrome/noscript.jar/content/noscript/Main.js
3134
3135
3136
if (win === (top || (top = win.top))) {
  sites.topSite = url;`
Does this help?

**Comment by hackademix** [comment]
I've tried to rearrange that code in a lint-friendlier way, and now I get

**Error: Validation was unable to complete successfully due to an unexpected error.**

The error has been logged, but please consider filing an issue report here: https://bit.ly/1POrYYU
chrome/noscript.jar/content/noscript/Main.js

```
3133 let domLoaded = !!this.getExpando(document, "domLoaded");
3134 if (!top) top = win.top;
3135 if (win === top) {
```

**Comment by wagnerand** [comment]
@hackademix can you provide a link to your updated build please?

**Comment by hackademix** [comment]
rc2: https://noscript.net/downloads/noscript-5.0.5rc2-unsigned.xpi

**Comment by wagnerand** [comment]
I don't get any errors when removing SeaMonkey and Palemoon from `install.rdf`.

**Comment by hackademix** [comment]
@wagnerand: are you suggesting me to remove those two long-standing install.rdf entries (the validator behavior is definitely new), or is this a hint for @EnTeQuAk to fix the bug?
If I did remove those, would Seamonkey and Palemoon users still be able to install the new NoScript version or be automatically updated to it?

**Comment by wagnerand** [comment]
My comment was merely a hint on how to find the issue.

**Comment by hackademix** [comment]
@wagnerand , @EnTeQuAk , so I've been busy with other security fixes (which need to be pushed ASAP, BTW), but finally got to try what @wagnerand suggested 4 days ago: **no Seamonkey nor Palemoon references** in install.rdf, https://noscript.net/downloads/noscript-5.0.5rc3-no-sm-pm.xpi
Unfortunately, **I still get the same validator error** :(
Any news on your side?

**Comment by wagnerand** [comment]
For some reason, we call `system_error` in the amo-validator. I was unable to debug it though. I don't know how to set a breakpoint within docker (modifying the file directly didn't halt execution) and when just calling `addon-validator` manually on the file, there is no error.

**Comment by hackademix** [comment]
OK, something definitely happens in Main.js. If I upload an empty Main.js, validation passes. I'm gonna restore the old install.rdf and try to bisect Main.js' content in order to find what breaks the validator.

**Comment by hackademix** [comment]
Arcane solved, it seems: your validator apparently chokes on the usage of a variable named "top" (maybe somewhere you assume I'm trying to rewrite a window global?).
Anyway renaming it to "topWin" did the trick. Please check this validation rule and maybe make it spit a more descriptive error message, if it's worth keeping.

**Comment by EnTeQuAk** [comment]
> Arcane solved, it seems: your validator apparently chokes on the usage of a variable named "top" (maybe somewhere you assume I'm trying to rewrite a window global?).
Anyway renaming it to "topWin" did the trick. Please check this validation rule and maybe make it spit a more descriptive error message, if it's worth keeping.

Thanks a lot for trying that out and finding the problem, that's weird that it chokes like that but I'll see what causes it. If it's a validation rule it should spit out a proper message but since it doesn't do that it seems to have another problem. I'll throw it against the validator and see what happens. I can confirm that throwing it directly against amo-validator doesn't trigger the problem we see.

Let's keep this bug open until we know more and maybe refile against amo-validator.

**Comment by EnTeQuAk** [comment]
I think I finally reproduced this in a unittest, I'll have a fix for this coming up on Monday I hope. Thanks again for everyone on solving this mystery!

**Comment by wagnerand** [comment]
Fixed in https://github.com/mozilla/amo-validator/pull/549

**Comment by wagnerand** [comment]
As always, this will be live next Thursday.
