### ISSUE TITLE
Tried to view Lightning (Addon) Source - Not Allowed

### ISSUE THREAD

**Issue by eternalbit** [mozilla/addons#398]
Went to: [https://addons.mozilla.org/en-US/thunderbird/addon/lightning/versions/](https://addons.mozilla.org/en-US/thunderbird/addon/lightning/versions/).

Clicked on: [View the source](https://addons.mozilla.org/en-US/thunderbird/files/browse/633791/).

Got Message:

> Oops! Not allowed.
> You tried to do something that you weren't allowed to.

Expected to be able to view the source (in order to look for the change log for the respective version).
Shouldn't the source be available to view since it is open source software?

**Comment by kewisch** [comment]
The file viewer has been disabled for now because of performance issues. You can follow mozilla/addons-server#5135 if you want to know when it will be enabled again.

Lightning sources are available via hg.mozilla.org or indexed via dxr.mozilla.org.
