### ISSUE TITLE
[Reviewer Tools] New Permissions displays duplicates

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#399]
ref: `https://addons.mozilla.org/en-US/editors/review/815549/`

**Display** (duplicate `http://*/*`)
`Permissions: notifications, https://*/*, http://*/*, http://*/*`

**manifest.json**

```
"permissions": [
  "notifications",
  "https://*/*",
  "http://*/*"
],
```

ref: `https://addons.mozilla.org/en-US/editors/review/715599/`
**Display**
`Permissions: contextMenus, activeTab, http://*/*, https://*/*, http://*/*, https://*/*`

**manifest.json**

```
"permissions" : [
   "contextMenus",
   "activeTab",
   "http://*/*",
   "https://*/*"
],
```

**Possible Cause:** It might be picking up "content_scripts" "matches" 
```
"content_scripts" : [
   {
      "run_at" : "document_end",
      "matches" : [
         "http://*/*",
         "https://*/*"
      ],
```

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/addons/issues/405
