### ISSUE TITLE
User interface for API-uploaded add-ons

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#40]
After an add-on has been uploaded via API – whether unlisted or listed – do we want to show it on AMO developer dashboard?

I’m inclined to say yes, but have a couple of questions.

If we want to show API-uploaded add-ons on AMO:
- Should we mark it differently from add-ons uploaded using the submission form?
- Should we allow editing, or can it only happen via the command line? For example, a developer would be able to upload new version, delete listing, edit information, etc.

cc @andymckay and @mstriemer

**Comment by andymckay** [comment]
An add-on uploaded via the API should be indistinguishable from one uploaded via a developer dashboard.
