### ISSUE TITLE
Permissions Validation error

### ISSUE THREAD

**Issue by VitalyOrbit** [mozilla/addons#403]
### Describe the problem and steps to reproduce it:
I develop a crossbrowser extension and specified some permissions (which work in Google Chrome), but when I try to add it to Mozilla Addons, I get an error and warning.
My extension is not public and use only in our company.

### What happened?
ERROR:
"/incognito" should be equal to one of the allowed values
Error: Your JSON file could not be parsed.

WARNING:
/permissions: Unknown permissions "identity.email" at 3.
Warning: See https://mzl.la/1R1n1t0 (MDN Docs) for more information.
manifest.json

### What did you expect to happen?
"incognito" key value is "split".
My extension make an ajax query to my site and should get a session id. And after with this session id does redirect to my site.

### Anything else we should know?
But, if I use incognito mode, the got session id is not correct, because ajax request is made from normal mode and the site is opened in incognito mode.
That's why I specified the "incognito" mode to "split".
I tested in Google Chome browser - evething was fine. But, when I want to check it (web-ext lint), I got this:
```
Validation Summary:

errors          1              
notices         0              
warnings        1              

ERRORS:

Code           Message                                      Description                           File   Line   Column
JSON_INVALID   "/incognito" should be equal to one of the   Your JSON file could not be parsed.                       
               allowed values                                                                                         
WARNINGS:

Code                   Message                             Description                                                   File            Line   Column
MANIFEST_PERMISSIONS   /permissions: Unknown permissions   See https://mzl.la/1R1n1t0 (MDN Docs) for more information.   manifest.json                
                       "identity.email" at 3.                                                                                                         
```

Add-ons online checker says the same.

Manifest JSON is correct, I checked it few times.
If I remove the "incognito" key from the manifest file, the error disappears.

I only want my extension works good in incognito mode too. If I miss some options, can you say what and how to fix it.

**Comment by wagnerand** [comment]
Please provide a link to your add-on file or at least the manifest.

**Comment by VitalyOrbit** [comment]
```
{
    "name"             : "Admin",
    "description"      : "Admin",
    "manifest_version" : 2,
    "version"          : "0.1.1",
    "icons"            : {
        "16"  : "icons/icon16.png",
        "32"  : "icons/icon32.png",
        "48"  : "icons/icon48.png",
        "100" : "icons/icon100.png",
        "128" : "icons/icon128.png"
    },
    "browser_action"   : {
        "default_icon"  : {
            "16"  : "icons/icon16.png",
            "32"  : "icons/icon32.png",
            "48"  : "icons/icon48.png",
            "100" : "icons/icon100.png",
            "128" : "icons/icon128.png"
        },
        "default_title" : "Admin"
    },
    "permissions"      : [
        "*://*/*",
        "tabs",
        "identity",
        "identity.email"
    ],
    "background"       : {
        "persistent" : false,
        "scripts"    : [
            "scripts/background.js"
        ]
    },
    "incognito"        : "split",
    "applications"     : {
        "gecko" : {
            "id"                 : "admin@orbitsoft.com",
            "strict_min_version" : "48.0"
        }
    }
}
```

**Comment by wagnerand** [comment]
I'm not entirely sure, but I think Firefox currently supports `spanning` only.

**Comment by VitalyOrbit** [comment]
1. Why it says "Error: Your JSON file could not be parsed."
2. When will be added support for "split" value? (planned?)
3. How can I call "incognito" ajax requests in incognito mode? Is it possible? Or they will call always in normal mode and no way to do what I want?

**Comment by jvillalobos** [comment]
> 1. Why it says "Error: Your JSON file could not be parsed."
I think that's just the error message shown when a manifest doesn't meet our schema. Doesn't necessarily mean there was a syntax error. [Here's the bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1277686) that originated the restriction.

> 2.  When will be added support for "split" value? (planned?)
I don't think there are plans to support it.

> 3.  How can I call "incognito" ajax requests in incognito mode? Is it possible? Or they will always call in normal mode and no way to do what I want?
Please use the [developer support channels](https://developer.mozilla.org/en-US/Add-ons#Contact_us) for this question.
