### ISSUE TITLE
Same permission are shown twice

### ISSUE THREAD

**Issue by gloomy-ghost** [mozilla/addons#405]
### Describe the problem and steps to reproduce it:
Go to https://addons.mozilla.org/en-US/firefox/addon/disqus-undirect/
Click "Permissions"

### What happened?
Two permissions are the same
![default](https://cloud.githubusercontent.com/assets/13086421/26294683/aec5c890-3f19-11e7-8f92-97bcc6b8a62f.png)

### What did you expect to happen?
There should only be one permission

**Comment by eviljeff** [comment]
Yeah we don't do any de-duping at the moment and `*://disqus.com/*` is in both `permissions` and `content_scripts`.

**Comment by wagnerand** [comment]
Mentor: @eviljeff 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by apoorvaeternity** [comment]
I am new to open source.
Where should I look to fix this issue?
I mean what files do I have to modify.

**Comment by eviljeff** [comment]
@apoorvaeternity  There are a few ways to solve this, but the simplest, (I think), that doesn't require lots of changes and re-parsing existing manifests is to change https://github.com/mozilla/addons-server/blob/master/src/olympia/files/models.py#L434:L435 so duplicates are filtered out.

Then it will need a test to prove it works.  One very similar to https://github.com/mozilla/addons-server/blob/master/src/olympia/files/tests/test_models.py#L312 but with some duplicates.  You could probably just add some duplicates into the `permissions` list in that test, actually.

**Comment by apoorvaeternity** [comment]
@eviljeff Okay I am working on it.

**Comment by apoorvaeternity** [comment]
@eviljeff I have made a pull request.
If it gets accepted it will be my first contribution to open source.

**Comment by vcarciu** [comment]
Verified as fixed on -dev : 
![doubleperm](https://user-images.githubusercontent.com/1583842/27484308-780c3c04-5831-11e7-88c1-b7217d3a64d6.png)
