### ISSUE TITLE
Mozilla Website Unaware I have Latest Firefox Version.

### ISSUE THREAD

**Issue by Expeditorofdreams** [mozilla/addons#406]
I noticed my Mac had an update done overnight as I had to restart it.
Since then a few things have changed

1) Lastpass no longer autofills fields when prompted, or propogates fields with possible answers like it always has. - I have contacted them regarding this.

2) I tried to make Startpage.com my search engine. But when I go to add-ons via https://addons.mozilla.org/en-US/firefox/, it keeps saying I need to get Firefox for the add on to work. But I have the latest Firefox version already!?!?

I have enclosed a screenshot to show you the problem
![screen shot 2017-05-23 at 16 41 24](https://cloud.githubusercontent.com/assets/18583913/26363007/9feb236a-3fd7-11e7-8755-ec6fcc616e7f.png)

**Comment by andymckay-limited-access** [comment]
Can you go to https://httpbin.org/get?show_env=1 and tell us the exact
value of User-Agent please? This normally occurs when the user agent sent
to firefox is incorrect.

**Comment by Expeditorofdreams** [comment]
args	
show_env	"1"
headers	
Accept	"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
Accept-Encoding	"gzip, deflate, br"
Accept-Language	"en-US,en;q=0.8"
Connect-Time	"1"
Connection	"close"
Dnt	"1"
Host	"httpbin.org"
Total-Route-Time	"0"
Upgrade-Insecure-Requests	"1"
User-Agent	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
Via	"1.1 vegur"
X-Forwarded-For	"81.136.204.177"
X-Forwarded-Port	"443"
X-Forwarded-Proto	"https"
X-Request-Id	"8e4ab73d-88e2-454c-bd19-6df0d6bb2ead"
X-Request-Start	"1495562745638"
origin	"81.136.204.177"
url	"https://httpbin.org/get?show_env=1"

**Comment by andymckay** [comment]
That user agent doesn't have the word Firefox in it. Here's mine: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

If you are using Firefox (and not Safari) something somewhere, another add-on or a proxy is changing the user agent on your behalf.
