### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by cr-nz** [mozilla/addons#41]
The validation errors out with a non descriptive reason. We think it is hanging on the .json files in the /lang/ directory. We have tried reducing the number of language strings but we need the ones in there. Maybe the timeout on the validation process needs to increase.

Please attach a copy of your add-on, and fill in the following information:
**[meganz.zip](https://github.com/mozilla/addons/files/147902/meganz.zip) (can't upload .xpi here, so renamed it)**

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
**New version of an existing addon.**

* Whether your add-on is listed or unlisted.
**Unlisted, submitted for signing only**

* The URL where you submitted the add-on.
**https://addons.mozilla.org/en-US/developers/upload/5f3828968b3b4e02ab97f6a2619c80c2**

* The approximate time you submitted the add-on, with timezone.
**February 26, 2016  10:10 pm NZST**

**Comment by andymckay** [comment]
When running locally I get:

```
* mega/js/vendor/dcraw.js
ERROR:amo.validator:Unexpected error during validation: KeyError: 'line_number'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/validator/submain.py", line 69, in prepare_package
    test_package(err, package, path, expectation, for_appversions)
  File "/usr/lib/python2.7/site-packages/validator/submain.py", line 165, in test_package
    test_inner_package(err, package, for_appversions)
  File "/usr/lib/python2.7/site-packages/validator/submain.py", line 375, in test_inner_package
    test_func(err, xpi_package)
  File "/usr/lib/python2.7/site-packages/validator/testcases/content.py", line 293, in test_packed_scripts
    testendpoint_js.test_js_file(err, script, file_data)
  File "/usr/lib/python2.7/site-packages/validator/testcases/scripting.py", line 27, in test_js_file
    tree = get_tree(data, filename=filename, err=err)
  File "/usr/lib/python2.7/site-packages/validator/testcases/javascript/jsshell.py", line 14, in get_tree
    return JSShell.get_shell().get_tree(code)
  File "/usr/lib/python2.7/site-packages/validator/testcases/javascript/jsshell.py", line 114, in get_tree
    output['line_number'])
KeyError: 'line_number'
```

**Comment by cr-nz** [comment]
I have tried removing that dcraw.js file and uploaded the extension again, but I still get the same error.

[meganz.zip](https://github.com/mozilla/addons/files/150166/meganz.zip)

<img width="632" alt="screen shot 2016-02-29 at 11 28 04 am" src="https://cloud.githubusercontent.com/assets/9664533/13382357/8eb90146-ded7-11e5-9714-7ab04127b913.png">

**Comment by andymckay-limited-access** [comment]
Adding this to @EnTeQuAk bucket of validator issues. Could this have been fixed by increasing the stack size?

**Comment by cr-nz** [comment]
We found the problem was caused by the ReactJS library which we include in a file called bundle.js. We have to run a script on it so it doesn't cause thousands of errors in the AMO validator and then fail:

https://github.com/meganz/webclient/blob/master/scripts/build.sh
