### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by toonytoontoony** [mozilla/addons#411]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by tofumatt** [comment]
Closing due to lack of information.

Please add information to your issue including the error you encountered, a URL (if applicable), and steps to reproduce.

**Comment by toonytoontoony** [comment]
Thanks
