### ISSUE TITLE
Incorrect language appears on addons.mozilla.org

### ISSUE THREAD

**Issue by adamopenweb** [mozilla/addons#412]
Originally reported: https://github.com/webcompat/web-bugs/issues/7104

### Describe the problem and steps to reproduce it:
1. Open Firefox Android or Firefox desktop with a mobile user agent 
2. Navigate to: https://addons.mozilla.org/ru/android/addon/ublock-origin/
3. Refresh page a few times

### What happened?
The text describing the add-on is changing languages between refreshes.

### What did you expect to happen?
The language is consistent. 

### Anything else we should know?
[![Screenshot Description](https://webcompat.com/uploads/2017/5/472ed255-7912-4d6c-b30f-9252193b2a13-thumb.jpg)](https://webcompat.com/uploads/2017/5/472ed255-7912-4d6c-b30f-9252193b2a13.jpg)

**Comment by EnTeQuAk** [comment]
I opened an issue at https://github.com/mozilla/addons-frontend/issues/2497 after a bit more debugging and digging it seems to be soley mobile-frontend related. Thanks a lot for the report!

**Comment by muffinresearch** [comment]
Fixed via mozilla/addons-frontend#2497 - will be released next week.
