### ISSUE TITLE
Website is displayed in fucking foreign!

### ISSUE THREAD

**Issue by C0MPAQ** [mozilla/addons#414]
1. Go to different country
2. Experience major suckage and web developer failure

Fucking foreign happened.

I expect the website to display in only right language there is in existence, which is dictated by my browser.

U suck.
![what_is_this](https://cloud.githubusercontent.com/assets/15914069/26697131/3b19a89e-4711-11e7-95c1-8a7b27ccacfd.jpg)

**Comment by C0MPAQ** [comment]
OK. It was my fault! 

I am on drugs, and am so sorry.

**Comment by tofumatt** [comment]
Lol no worries this issue made my day 😆

**Comment by caitmuenster** [comment]
Same here.  :)
