### ISSUE TITLE
Search failing

### ISSUE THREAD

**Issue by kimcosmos** [mozilla/addons#415]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Firefox 53 on Android. 
### What happened?
https://addons.mozilla.org/en-US/android/search/?q=noscript 
returns 
    AmIUnique
    DuckDuckGo (HTML SSL)
    IP Geolocator
### What did you expect to happen?
Find NoScript
https://addons.mozilla.org/en-US/android/addon/noscript/?src=ss
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![tmp_6235-screenshot_20170602-224249-9883724](https://cloud.githubusercontent.com/assets/29145145/26726058/da9b7e50-47e4-11e7-8955-17f660a6158c.png)

**Comment by kimcosmos** [comment]
I mean of course that it finds those 3 alone. Nothing more. Its not a sorting issue. The pink is a blue filter

**Comment by diox** [comment]
Hi,

noscript is not marked as compatible with Firefox for android, which is why it's not appearing in android search results.
