### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by mstewart20** [mozilla/addons#416]
Please attach a copy of your add-on, and fill in the following information:

[guru.zip](https://github.com/mozilla/addons/files/1049912/guru.zip)

Validation error:
![screenshot 2017-06-03 16 50 35](https://cloud.githubusercontent.com/assets/5881392/26756977/cc0fb778-487c-11e7-87ae-4767e655382b.png)

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

This happened while uploading a new version of an existing add-on.

* Whether your add-on is listed or unlisted.

unlisted

* The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/addon/guru/versions/submit/

* The approximate time you submitted the add-on, with timezone.

4:45pm US Eastern Time

**Comment by wagnerand** [comment]
Thanks for the report, we're tracking this issue in https://github.com/mozilla/addons/issues/397
