### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by adam-p** [mozilla/addons#417]
[firefox.zip](https://github.com/mozilla/addons/files/1059700/firefox.zip)

Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

This occurred when uploading a new version of an existing XUL extension. 

* Whether your add-on is listed or unlisted.

Listed. https://addons.mozilla.org/en-US/firefox/addon/markdown-here-xul/

* The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/addon/markdown-here-xul/versions/submit/

* The approximate time you submitted the add-on, with timezone.

9:20PM EST

---

This is the error displayed: 
```
An unexpected error has occurred.
Error: Validation was unable to complete successfully due to an unexpected error.

The error has been logged, but please consider filing an issue report here: https://bit.ly/1POrYYU

common/highlightjs/highlight.js
336  }
337  top = Object.create(mode, {parent: {value: top}});
338  }
```

Here's the [line of code](https://github.com/adam-p/markdown-here/blob/6c8949f6ae17a690e88f1aa4a04d83d5964cc0d6/src/common/highlightjs/highlight.js#L336) mentioned there. It hasn't been changed recently -- certainly not for the last few releases.

I hope this can be resolved.

**Comment by wagnerand** [comment]
Thanks for the report, we're tracking this issue in https://github.com/mozilla/addons/issues/397.
