### ISSUE TITLE
Uploading new add-on version hangs forever

### ISSUE THREAD

**Issue by jesperkristensen** [mozilla/addons#42]
I am trying to upload a new version of my add-on using https://addons.mozilla.org/da/developers/addon/salesforce-inspector/versions#version-upload , but uploading hangs forever. After I selected the XPI file from my computer, it hangs showing "Validating filename.xpi" and "100%".

I tried inspecting the page, and it seems to make a lot of requests that point to https://addons.mozilla.org/da/developers/upload/ec7651e18eb04266aba5b058556e3afe that contains "Add-on passed validation. General Tests. Error: Validation task could not complete or completed with errors"

**Comment by andymckay** [comment]
Please link to the XPI so we can try it.

**Comment by jesperkristensen** [comment]
[data.zip](https://github.com/mozilla/addons/files/148985/data.zip)

**Comment by andymckay** [comment]
It validates locally (with 26 warnings) and I've run it a couple of times on the production server and it runs fine. Perhaps you hit at a busy time? Can you retry?

**Comment by jesperkristensen** [comment]
It works now. I tried previously three times over a 15 minute interval, and it failed all three times, but when I tried now, it worked.

**Comment by andymckay** [comment]
Sorry for the problem, we'll look in the server logs, see if anything happened on our end.
