### ISSUE TITLE
Contribute donation does not work

### ISSUE THREAD

**Issue by TorKlingberg** [mozilla/addons#421]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I click "Contribute" and press "Make Donation".

### What happened?
It says "Contacting PayPal" and spins for a few seconds, then nothing.

### What did you expect to happen?
Some PayPal frame to open and let me choose how to pay.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Firefox 53.0.3 (64-bit) on Ubuntu 16.04.2.
The first time I tried it asked for PayPal login, I entered it, but it says the email or password was wrong (it wasn't).
I use PayPal 2-factor login, which is a bit broken, so I opened PayPal in a separate tab and logged in there. Then I went back to the addons tab, and this bug happens.
[addons.zip](https://github.com/mozilla/addons/files/1074230/addons.zip)

Update: It works fine if I disable PayPal 2-factor login (Security key).

**Comment by diox** [comment]
I've just tried it myself and can see the paypal frame just fine.

> Update: It works fine if I disable PayPal 2-factor login (Security key).

I'm afraid you'll have to take this to paypal, then.
