### ISSUE TITLE
Add-on managed to not have an author

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons#422]
I'm not sure how this happened, but the following add-on has no author. Is it possible that you can remove yourself as the only author of an add-on?

https://addons.mozilla.org/en-US/editors/review/zoom-plus2

**Comment by muffinresearch** [comment]
@diox @eviljeff any ideas on how this state can happen?

**Comment by jvillalobos** [comment]
It appears to a common problem with themes, but there are also lots of extensions affected by this. Looking at add-ons updated since 2015, there are 140 extensions and ~2K themes without authors.

There's one public extension without an author: https://addons.mozilla.org/addon/open-160by2/

**Comment by eviljeff** [comment]
I would say it's either:
- a problem during upload (can't see how)
- a fault in the account deletion code that allows a user to 'delete' (anonymize) their account while they have add-ons, which is supposed to be blocked.
- admins recklessly(! 😛 ) using the anonymize/full-delete function on users who have add-ons - the admin anonymize function didn't (doesn't?) check is they were a developer.

We'd need logs to dig into it.  Maybe raw logs if there were delete cascades of the activity logs.

**Comment by eviljeff** [comment]
Or, as @kewisch suggests, maybe a fault with the code that prevents you from removing yourself if you're the last remaining developer.

**Comment by muffinresearch** [comment]
More examples from https://github.com/mozilla/addons-frontend/issues/4907

* https://addons.mozilla.org/en-US/firefox/addon/minions-as-electricians/
* https://addons.mozilla.org/en-US/firefox/addon/the-pirate-bay-search-10208/
