### ISSUE TITLE
[Reviewer Tools] Information Request Canned Responses are missing

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#423]
After the latest push,  Information Request Canned Responses are missing from the 

`<select id="id_canned_response" name="canned_response"></select>`

**Comment by eviljeff** [comment]
regression caused by https://github.com/mozilla/addons-server/pull/5607#discussion_r121399106

@wagnerand or @jvillalobos can fix this by editing the canned responses in /admin - changing the sort group of the affected canned responses from `info` to `reply`

**Comment by erosman** [comment]
I noticed that too (since I have my own scripts running on those nodes)

This is the 2nd or 3rd time it has change in recent month ;)

**Comment by wagnerand** [comment]
Fixed.

**Comment by ValentinaPC** [comment]
Verified in AMO-dev FF53(Win 7) the "Information Request Canned Responses" for listed add-ons, unlisted add-ons and auto-approved add-ons and last 2 don't have canned responses.
@wagnerand : intended?
