### ISSUE TITLE
Add a search flag for web extensions/57+ compat add-ons

### ISSUE THREAD

**Issue by share3141** [mozilla/addons#424]
Don't know where to put this so...it would be nice if you put in a search feature for addons that will be compatible with FF 57 and above.  The only one I can find is when you do a keyword search.  Then you can use tabs.  Otherwise you have to go through all the addons in a category to find one that may work.

**Comment by tofumatt** [comment]
For what it's worth: I believe we elevate extensions that are 57+ compatible (eg Web Extensions) in the search results, but we don't have a flag to only show Web Extensions if I recall correctly.

**Comment by diox** [comment]
We don't advertise it much because it's more of an advanced feature, but you can search for add-ons that have the firefox57 tag, or use it to refine an existing search using the sidebar on the left: https://addons.mozilla.org/en-US/firefox/search/?tag=firefox57
