### ISSUE TITLE
Thunderbird theme gets added to Firefox not Thunderbird when using Firefox on Mozilla's addon/theme website.

### ISSUE THREAD

**Issue by deanedridge** [mozilla/addons#425]
[G6+NjQzz.html.txt](https://github.com/mozilla/addons/files/1082838/G6.NjQzz.html.txt)

### Thunderbird theme gets added to Firefox not Thunderbird when using Firefox on Mozilla's addon/theme website.
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0
Build ID: 20170617030206

Steps to reproduce:

I went to both of the following sites using Firefox and clicked on the add button of the Thunderbird theme suggestions. https://addons.mozilla.org/en-US/thunderbird/themes/?src=thunderbird 

And on this website I clicked on the "Add to Thunderbird" button.
https://addons.mozilla.org/en-US/thunderbird/addon/ladybug_red/

Here are the details of the Thunderbird install I have:
    Name: Thunderbird
    Version: 54.0b3
    Build ID: 20170531163242
    Update History: Show Update History
    Update Channel: beta
    User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Thunderbird/54.0
    OS: Darwin 16.6.0
-------

Here's the details of the Firefox install I have, in case it is relevant:

Name: Firefox
Version: 56.0a1
Build ID: 20170617030206
Update Channel: nightly
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0
OS: Darwin 16.6.0
Multiprocess Windows: 1/1 (Enabled by default)
Google Key: Found
Mozilla Location Service Key: Found
Safe Mode: true

Both Thunderbird and Firefox were running with addons disabled.

### Expected results:

The selected new theme should have been added to my Thunderbird app but was added to Firefox.

### Note: I am able to enable and disable the themes I already have installed in Thunderbird. These were installed into my profile a few weeks ago when I was using the release version of Thunderbird.

I'm not able to download the theme.
If I right click on a theme button on this page:
https://addons.mozilla.org/en-US/thunderbird/themes/?src=thunderbird
there is no download option in the right click menu.

If I right click on "Add to Thunderbird" on the following page:
https://addons.mozilla.org/en-US/thunderbird/addon/ladybug_red/
and select "save link as" I download a webpage (html file G6+NjQzz.html) for the persona plus addon.

It seems there was another person that seemed to have had a similar problem with similar quirks: https://support.mozilla.org/en-US/questions/1009011

### Note: this has already been reported on bugzilla, but since someone said it is an addon issue I was told to report it here. https://bugzilla.mozilla.org/show_bug.cgi?id=1373962

**Comment by jvillalobos** [comment]
That's just a problem with the labeling on the button. It says "Add to Thunderbird" because the URL has `/thunderbird/` in it. However, you can only install Thunderbird add-ons from Thunderbird. Firefox doesn't have a way to hand off add-on installs to Thunderbird.

We're in the process of moving Thunderbird add-ons to a separate site, so at this point I don't think there's anything we will do to fix this issue.

**Comment by AmethsytComputerTechician** [comment]
I have this problem too now on a Linux Ubuntu computer, a Windows computer and now my MacBook Pro :o

**Comment by Eksapsy** [comment]
This is still going on. Why is the issue closed? It's an open issue.
So, Themes and add-ones are useless as a feature? What to do with them?
