### ISSUE TITLE
[Validator] Wrong Warning: contextMenus.create is not supported

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#426]
Repost of: https://github.com/mozilla/amo-validator/issues/554

Example:
```
https://addons.mozilla.org/en-US/developers/addon/invert-colors/file/670527/validation
https://addons.mozilla.org/en-US/firefox/files/browse/670527/file/background.js#L59
```

> contextMenus.create is not supported
> This API has not been implemented by Firefox.
> background.js line 59
> 
> contextMenus.onClicked is not supported
> This API has not been implemented by Firefox.
> background.js line 66

```
browser.contextMenus.create({
  id: "InvertColors",
  title: "Invert Colors"
});

browser.contextMenus.onClicked.addListener(toggleColors);
```

More:
`https://addons.mozilla.org/en-US/firefox/files/compare/670891...291288/file/main.js#top`

`var id = chrome.contextMenus.create({ ...`

Also ... 
https://discourse.mozilla-community.org/t/should-i-worry-about-this-warning-warning-this-api-has-not-been-implemented-by-firefox/

**Comment by andymckay** [comment]
@mstriemer did something go wrong in the schema export? Occurs on https://github.com/mdn/webextensions-examples/tree/master/context-menu-demo.

**Comment by mstriemer** [comment]
Looks like the `contextMenus` namespace got moved to `menus` with a `$import` which I don't think our parser supports. I'll take a look.

**Comment by andymckay** [comment]
Ah that would have been: https://bugzilla.mozilla.org/show_bug.cgi?id=1333403
