### ISSUE TITLE
AdBlock Plus appears in "Privacy & Security" category

### ISSUE THREAD

**Issue by dmarti** [mozilla/addons#428]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Adblock Plus appears in the "Privacy & Security" category on "addons.mozilla.org".

### What happened?

Visit "addons.mozilla.org" and click on "Privacy & Security".

The add-on "Adblock Plus" appears on this page:

https://addons.mozilla.org/en-US/firefox/extensions/privacy-security/

### What did you expect to happen?

I expected Adblock Plus to appears on a dedicated page for ad blockers, or the "Other" page, not a page that could be interpreted as recommending this add-on for privacy or security. This add-on appears to be designed to confuse users about privacy and security choices.

### Anything else we should know?

Adblock Plus runs a paid whitelisting program called "Acceptable Ads". The "Acceptable" criteria include no rules against common user privacy and security concerns, such as malvertising and PII misuse. And configuring Adblock Plus to actually provide protection is complicated.

 * Go to "Filter Preferences" in the ABP menu.

 * Click "Add filter subscription"

 * No privacy lists appear on the main drop-down. Select "Add a different subscription".

 * Scroll down and eventually find the "EasyPrivacy" entry from a long list.

 * Click "Add subscription".

**But even after you go through the above process to find and turn on "EasyPrivacy", you're still not protected. This is not clear unless you read the fine print.** The "Acceptable Ads" paid whitelisting program actually overrides your explicit EasyPrivacy choice, to allow tracking by Google, Criteo, and other companies.

In order to make your privacy choice take effect, you also have to turn off "Acceptable Ads" using a different option, which is labeled "Allow some non-intrusive advertising." (The checkbox is not even labeled "Acceptable Ads," maybe just in case a user has heard of "Acceptable Ads" and knows about the controversial paid whitelisting program.)

**Comment by jvillalobos** [comment]
Add-on categories are chosen by the developers. Regardless of the (fair) objections people may have about specific features ABP has, blocking ads does improve privacy and security for users, so the category is appropriate.
