### ISSUE TITLE
Review count incorrect

### ISSUE THREAD

**Issue by atsay** [mozilla/addons#43]
On some add-on detail pages, the review count doesn't display the actual number of reviews. For example, in the Ratings field of https://addons.mozilla.org/firefox/addon/among-planets/, it says there are 2 reviews. But if you scroll down the page you see there are actually 3 reviews. This theme is also off by one: https://addons.mozilla.org/firefox/addon/vintage-fabric_03/

**Comment by andymckay** [comment]
Sounds the same as #87
