### ISSUE TITLE
On MacBook, on Nightly 56, "Add to Firefox" button doesn't detect trackpad tap, only click

### ISSUE THREAD

**Issue by hafta** [mozilla/addons#431]
### Describe the problem and steps to reproduce it:
With Nightly 56 (2017-06-23), on a MacBook, the "Add to Firefox" button for installing an addon doesn't detect a trackpad tap. It only detects the physical trackpad click. "Tap" refers to the "Tap to Click" setting in the macOS trackpad preferences.

### What happened?
Taps on the button are ignored.

### What did you expect to happen?
Tapping on the button should trigger the addon to be installed like a standard click does.

### Anything else we should know?
This happens for me for any addon. Axn example is
https://addons.mozilla.org/en-US/firefox/addon/tab-counter-webext/

**Comment by muffinresearch** [comment]
This happens on the old front-end I can reproduce it there with nightly, but I can't reproduce it on the new frontend. Since this only happens in nightly this could be a regression in Firefox.

**Comment by iology** [comment]
The paginator buttons are problematic too.

<img width="208" alt="" src="https://user-images.githubusercontent.com/23622455/30205505-922130ba-94bb-11e7-80c4-c2e1feb9beed.png">

**Comment by hafta** [comment]
I filed a Firefox bug here https://bugzilla.mozilla.org/show_bug.cgi?id=1398196

**Comment by muffinresearch** [comment]
I'm going to close this as wontfix since the new UI supercedes the old frontend.
