### ISSUE TITLE
Identify magic functionality in current front-end pages

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#434]
We need:
- list of pages with 'magic' (pages with extra admin-like stuff - buttons, fields, etc) functionality
- for each:
  - if we didn't have this functionality, what could we do instead?
  - how often is this used?

![magic](https://user-images.githubusercontent.com/187006/27707605-c184cae8-5cca-11e7-89cf-ddd0bf9dd4eb.gif)

**Comment by eviljeff** [comment]
- Addon detail page
  - Manage buttons for all add-ons
  - Review page button
- User profile view
  - ip address
  - manage user button
  - edit profile for all users
- manage user page

**Comment by kewisch** [comment]
For reference, when I write amoqueue I mean [the add-on I wrote](https://addons.mozilla.org/en-US/firefox/addon/amo-queue-helper/). Here is my take:

- Addon detail page
  - Manage buttons for all add-ons: 
    - used often. 
    - Alternative: browserAction button in amoqueue
  - Review page button
    - used very often. 
    - Alternative: browserAction button in amoqueue
- User profile view
  - ip address: 
    - used never
  - manage user button
    - used whenever needed to process email on amo-admins. 
    - no good idea on alternative aside from database access. Is this just the button or also the manage user functionality?
  - edit profile for all users 
    - used never
    - raw database access for the few cases where needed?
- manage user page
  - same as user edit page, but can edit email address
    - never needed to change email.

**Comment by kewisch** [comment]
Aside from those you mentioned in comment 1, can you clarify what category of items you are looking for? If you need a full list this would be hard for us to determine without spending a few weeks consciously looking for it during reviews. I am also sure there are features we use often that may be considered a given and I am not sure it is effective use of time for me to explain every button I click during reviews.

**Comment by eviljeff** [comment]
amoqueue won't work as a webextension, if I understand the restrictions correctly, so it wouldn't be available as an alternative.

We're looking for functionality you use in the user facing pages, i.e. the ones that will be replaced with addons-frontend, that isn't user functionality.  If we don't know about it, it'll definitely be removed when addons-frontend is live in Q4; if we do then we'll try to replicate it if you use it a lot, or there aren't any alternatives, etc.

**Comment by jvillalobos** [comment]
> Manage buttons for all add-ons

Used often

> Review page button

Used often

> User profile view
>  ip address

Used sometimes

> manage user button

Used often

> edit profile for all users

Used sometimes

> manage user page

Used rarely

Is this limited to user-facing pages?

**Comment by wagnerand** [comment]
For me it's mostly what @jvillalobos said.

On the user review page, I also use the "delete review" regularly to get rid of obvious spam.

**Comment by kewisch** [comment]
> amoqueue won't work as a webextension, if I understand the restrictions correctly, so it wouldn't be available as an alternative.
amoqueue will run on AMO, as long as the script that runs is not a content script. This should be fine in the browser action button, which is a UI page and will only need access to tabs.query() to get the URL.

**Comment by muffinresearch** [comment]
I think we're generally on the same page for this stuff now. Closing this out. Feel free to re-open it if you think there's still more discussion that needs to be had.
