### ISSUE TITLE
AMO frontend: the trailing quote a bug?

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons#436]
In this string: 
https://pontoon.mozilla.org/bg/amo-frontend/LC_MESSAGES/amo.po/?string=168266

%(count)s add-on found"
#: src/amo/components/SearchContextCard/index.js:45
Resource path LC_MESSAGES/amo.po

### What happened?
May not be severe but this should be an easy fix. 

### What did you expect to happen?
Remove the quote.

**Comment by muffinresearch** [comment]
Re-filed under https://github.com/mozilla/addons-frontend/issues/2698
