### ISSUE TITLE
Firefox for Android add-on website, unable to see development versions

### ISSUE THREAD

**Issue by jawz101** [mozilla/addons#437]
https://addons.mozilla.org/en-US/android/addon/ublock-origin/

I no longer see the option to use development versions of add-ons on the Firefox for Android AMO site

**Comment by tofumatt** [comment]
(I'm pretty sure) this is on the roadmap for Q3. Thanks for voicing your interest; that will help us prioritise which features to ship first. 👍

**Comment by jawz101** [comment]
I can see the option in the desktop version of the same Android page but the mobile-formatted version doesn't show the development channel

**Comment by pwd-github** [comment]
Nightly users are being forced to jump through hoops to get development versions which means that the testing isn't as effective or easy as it should be for 57.

**Comment by muffinresearch** [comment]
This should be covered by this issue: https://github.com/mozilla/addons-frontend/issues/2770 please follow along there.
