### ISSUE TITLE
Don't show IP in user-profile

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/addons#438]
https://addons.mozilla.org/de/firefox/user/[username] shouldn't show last IP!
I have a fixed IP and this can be a security problem!

**Comment by tofumatt** [comment]
Does it only show the last IP address for the currently signed in user or for any user? Knowing where the last sign in on your own account was from is a decent security tool...

**Comment by wagnerand** [comment]
@kewisch said he can't see the last IP even for his own account.

**Comment by kewisch** [comment]
To clarify, I can see it for the reviewer account, but not one that has normal user access.

**Comment by wagnerand** [comment]
And by reviewer, you probably mean "admin" :)

**Comment by diox** [comment]
Relevant code:
```python
    edit_any_user = acl.action_allowed(request, amo.permissions.USERS_EDIT)
    own_profile = (request.user.is_authenticated() and
                   request.user.id == user.id)
```
```html
{% if own_profile or edit_any_user %}
    {% if profile.last_login %}
        <tr class="last-login-time">
            <th>{{ _('Time of last login') }}</th>
            <td>{{ profile.last_login|datetime('%B %e, %Y %H:%M:%S') }}</td>
        </tr>
    {% endif %}
    {% if profile.last_login_ip %}
        <tr class="last-login-ip">
            <th>{{ _('IP address of last login') }}</th>
            <td>{{ profile.last_login_ip }}</td>
        </tr>
    {% endif %}
{% endif %}
```

**Comment by diox** [comment]
It seems to be working as intended for me, I can see my own IP, or any other user IP as long as I have admin access. Otherwise I see nothing.

**Comment by Tobias-B-Besemer** [comment]
Sorry, then I was to fast with filling an issue if I can only see my own IP!

**Comment by Tobias-B-Besemer** [comment]
Whats about adding a note like "* Only visible for you!" behind the IP?
