### ISSUE TITLE
Allow staring without writing a review

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/addons#439]
Please allow staring without writing a review (like Google Play Store does).
Else the user don't vote so much of fill just "useless" reviews.

**Comment by tofumatt** [comment]
I believe we already have this feature. Is it not working for you?

Matthew Riley MacPherson (sent from mobile)

**Comment by Tobias-B-Besemer** [comment]
No, there are a check for a required field for a comment.

**Comment by diox** [comment]
The check is still there for desktop, it has only been removed in the new frontend, which is mobile-only for now.

**Comment by Tobias-B-Besemer** [comment]
When will the new frontend for desktop be released?
Is there a other URL for the mobile version of does it work with the user agent?

**Comment by muffinresearch** [comment]
@Tobias-B-Besemer it is planned to be released in Q4 - you can use the site today if you click "view mobile site" in the footer of the regular desktop site.

**Comment by Tobias-B-Besemer** [comment]
Thanks for the info!
