### ISSUE TITLE
redesign AMO Developer Hub

### ISSUE THREAD

**Issue by designakt** [mozilla/addons#44]
Help developers in all phases of an add-ons life cycle.
To do that we want to understand developers needs and other stakeholders interests in the developer hub, map out the core functions for a new hub, and create the developer hub as a creative developer outlet to take their ideas to realization.

[Ideation and Preparation Document (The AMO Experience - Google Docs)](https://docs.google.com/document/d/147RZidwIOkDwT2G6mlI8BkOk1GLqSOmX7_GX17FB3Vk/edit)

**Comment by brampitoyo** [comment]
![amo-devhub](https://cloud.githubusercontent.com/assets/51007/13658752/e94187fa-e6de-11e5-816a-1f8f577f6034.png)

Current state of proposal:

The AMO Developer Hub is designed to:

* Help new developers get started with building and uploading their first add-ons
* Help most developers access documentation more quickly
* Help seasoned existing XUL developers to rewrite/migrate to newer technologies

Befitting its name, the Developer Hub will syndicate and link to many other parts of the add-on ecosystem:

* My add-ons and themes
  * If empty, link to tutorial
* Developer News, taken from multiple sources
  * Addons Team blog
  * Hacks blog
* Documentation and learning materials
  * Step-by-step guide if user hasn’t uploaded any add-on
    * Getting started with WebExtensions
    * Getting started with Add-on SDK
    * Guide to choosing the right technology
  * MDN links if user has uploaded an add-on
    * Search
    * Popular articles
  * e10s/WebExtensions resources if user has a XUL add-on
    * How to port/rewrite
    * Deployment timeline
    * Where to give feedback
* Tools
  * Add-on validator
  * etc.
* Community and support
  * Discourse
  * UserVoice
  * etc.

**Comment by designakt** [comment]
@brampitoyo could you please create issues for parts of this as you see them emerge so that we have a bit more granularity.

**Comment by brampitoyo** [comment]
This bug is currently being worked on in another issue, so I’m closing this one.
