### ISSUE TITLE
can't filter add-ons for Android mobile only

### ISSUE THREAD

**Issue by scheinercc** [mozilla/addons#440]
### Describe the problem and steps to reproduce it:
- search for "duplicate tab Firefox" https://duckduckgo.com/?q=duplicate+tab+firefox+android&t=fpas&ia=web
- click on #3 "Duplicate tab in context menu"
https://addons.mozilla.org/en-US/android/addon/duplicate-in-tab-context-menu/reviews/540457/

- search for "duplicate tab" on AMO page

### What happened?
Many results show up, all of seem not to be suitable for FF on a phone.

### What did you expect to happen?
A list of Addons all installable, suitable for my device type & ff version.

### Anything else we should know?
AMO not usable for novice users if addons are not all relevant for their device (and listing has no indication about this shortcoming).

**Comment by tofumatt** [comment]
I'm thinking this could be related to (or the same issue as) https://github.com/mozilla/addons-frontend/issues/2087.

I'll work on getting a fix for that out ASAP, hopefully this week! Sorry about that!

**Comment by eviljeff** [comment]
closing this as a duplicate to https://github.com/mozilla/addons-frontend/issues/2087
