### ISSUE TITLE
Log out message in my account

### ISSUE THREAD

**Issue by zati81** [mozilla/addons#441]
In Mozilla my account @ https://addons.mozilla.org/nn-NO/firefox/user/USERNAME
when you press on your username on top right corner, then select log out, the message says "Logg ut"

Wrong log out button description, the English language selected.

Log out button not to be " Logg ut"

Check attached file for more info.
![mozilla_log_ut](https://user-images.githubusercontent.com/10505239/28290739-e3f1ecc4-6b47-11e7-9b08-2bba463350c0.png)

**Comment by EnTeQuAk** [comment]
You're not using the english language, see the URL, it's showing that you're using Norweigian, did you click in the Language Selector at the very bottom right "English"? I checked and that works properly for me. If you replace `nn-no` with `en-US` it'll show the correct thing.

I'm closing as invalid for now, please let me know if there's anything else we can do.

**Comment by zati81** [comment]
silly me...I didn't even check that obvious thing.
but the funny thing is that I just clicked on a link from add-ons and it directed me there.
and I also don't have anything to do with the Norwegian language.
so...anyways, thanks for the feedback.
