### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by spacilv** [mozilla/addons#442]
* Error appears during the submission of a new add-on,
* The URL where the add-on was sumbitted is: [https://addons.mozilla.org/cs/developers/addon/submit/upload-listed](url),
* The add-on should be listed,
* Tha add-on was submitted on 2017/07/18 at 11:39:30 (UTC+01:00), with timezone.

[CryptoWebExtension.zip](https://github.com/mozilla/addons/files/1155347/CryptoWebExtension.zip)

**Comment by wagnerand** [comment]
Something went wrong when the zip file was created. Instead of creating a __locales_ directory, it created a file called __locales\cs\messages.json_ (same for _en_).

**Comment by spacilv** [comment]
That should not be a problem according to [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization).

**Comment by wagnerand** [comment]
I'm not sure what makes you think that. The documentation says
> In extensions, these are contained within a directory called _locales, placed inside the extension root. Each individual locale has its strings (referred to as messages) contained within a file called messages.json, which is placed inside a subdirectory of _locales, named using the language subtag for that locale's language.

So, `_locales` and `cs` need to be directories, not part of a filename.

**Comment by spacilv** [comment]
I am a little bit confused because structure of uploaded zip archive (Crypto Web Extension for Firefox) is all right according to what you wrote. Uploaded zip archive contains directory called _locales, directory _locales contains directory en/cs and directory en/cs contains file called manifest.json.

**Comment by wagnerand** [comment]
It does **not** for me when I download and extract your zip file. See my https://github.com/mozilla/addons/issues/442#issuecomment-316019660 above.

**Comment by spacilv** [comment]
That is weird, see screenshot below. That is what I see on my PC (Windows 10), directories are fine before and even after extraction of zip archive.

![extension](https://user-images.githubusercontent.com/30258900/28319313-cf5ce17a-6bcd-11e7-96ae-d6da66abd21d.png)

**Comment by wagnerand** [comment]
This is what I see on Mac:

<img width="793" alt="screen shot 2017-07-18 at 15 32 22" src="https://user-images.githubusercontent.com/873258/28320685-c3c2e704-6bc0-11e7-9eb0-cf30cade1c36.png">

**Comment by spacilv** [comment]
The problem is in creating zip archive by using powershell script on PC. Zip archive created by 7Zip application is ok. I am closing the issue.
