### ISSUE TITLE
AMO message contains grammatical error

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons#443]
### Describe the problem and steps to reproduce it:
English text has grammar error

### What happened?
"This add-on is doesn't require any additional payments, paid services or software or additional hardware."
### What did you expect to happen?
"This add-on doesn't require any additional payments, paid services or software or additional hardware."
### Anything else we should know?
LC_MESSAGES/django.po
src/olympia/devhub/templates/devhub/addons/edit/basic.html:95

**Comment by muffinresearch** [comment]
Repo link https://github.com/mozilla/addons-server/blob/3725414dcde295bbc143a154b572928dc5a34383/src/olympia/devhub/templates/devhub/addons/edit/basic.html#L95

**Comment by muffinresearch** [comment]
Regression from https://github.com/mozilla/addons-server/pull/5893

**Comment by eviljeff** [comment]
fixed https://github.com/mozilla/addons-server/commit/378c4f37cce6916e4576b4c9ba4b3fdeea741e5f

**Comment by vcarciu** [comment]
@muffinresearch : 
The message is a bit different than the expected results:
![grammar](https://user-images.githubusercontent.com/1583842/28357608-bbab68d4-6c74-11e7-81fd-ed6b5d00d2b3.png)

![grammar2](https://user-images.githubusercontent.com/1583842/28357616-c0311610-6c74-11e7-979f-e5141b6ab43f.png)

**Comment by muffinresearch** [comment]
@eviljeff see @vcarciu's comment can you point out where to the see the modified string?

**Comment by vcarciu** [comment]
@muffinresearch , @eviljeff : nevermind I found the other message . Verified as fixed : 
![grammar3](https://user-images.githubusercontent.com/1583842/28358314-18dafbb2-6c77-11e7-980f-e65f972f7276.png)
