### ISSUE TITLE
Consume extension block list from other sources

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#444]
Some other stores might publish an extension blocklist in the same way that we do for AMO. If that's the case, we could use that in AMO by blocking those add-on ids. Whilst this doesn't stop authors changing those id's, it does give us just one more data point.

**Comment by muffinresearch** [comment]
@andymckay that's an interesting idea - do you know of any yet that are publicly available?

**Comment by jvillalobos** [comment]
We would need to have the ability to be selective, since policies can be different across vendors.

**Comment by fmarier** [comment]
The list of bad CRX IDs that Chrome uses for its blacklist is available today through the [Safe Browsing Update API](https://developers.google.com/safe-browsing/v4/update-api).

While [fetching the list](https://developers.google.com/safe-browsing/v4/update-api#http-post-request), you need to specify:

    "listUpdateRequests": [{
      "threatType":      "MALWARE",
      "platformType":    "CHROME",
      "threatEntryType": "CHROME_EXTENSION",
    ...

The "CHROME_EXTENSION" entry type is missing from the [official documentation](https://developers.google.com/safe-browsing/v4/reference/rest/v4/ThreatEntryType), but that's what [Chrome uses](https://cs.chromium.org/chromium/src/components/safe_browsing_db/v4_protocol_manager_util.cc?rcl=cc92f7aea52bd87500cab8538687da6e756aaed0&l=100).

This would require that we build a small service that downloads the list and keeps it up to date, but then we could do as many "local" lookups as we want on it. Assuming we keep track of the CRX IDs that were in the original uploads, we could check the entire AMO catalog every hour if we wanted.

**Comment by andymckay** [comment]
Thanks @fmarier. It seems like this wouldn't buy us much, since a developer could easily change the ID. But just accepting something that we know another store has had a problem with should be something that could get factored into the risk profile, if not an outright ban.

**Comment by jvillalobos** [comment]
I don't think we'll do this, given that ecosystems and IDs are so different.
