### ISSUE TITLE
Trim extension permissions 

### ISSUE THREAD

**Issue by gloomy-ghost** [mozilla/addons#446]
### Describe the problem and steps to reproduce it:
Go to https://addons.mozilla.org/zh-CN/firefox/addon/v2ex-plus9/
Click "Permissions"

### What happened?
![default](https://user-images.githubusercontent.com/13086421/28489175-b8d9381c-6eee-11e7-8a1f-1c68474397f9.png)

### What did you expect to happen?
`*://*.v2ex.com/*` should supersede all of the rest v2ex.com permissions.

### Anything else we should know?
This is a follow-up issue for #405

**Comment by eviljeff** [comment]
What's the behaviour within Firefox when you install it?

**Comment by gloomy-ghost** [comment]
Firefox doesn't do de-duplicating at the moment neither. There are some open bugs for that though, see [bug 1350277](https://bugzilla.mozilla.org/show_bug.cgi?id=1350277) and [bug 1373434](https://bugzilla.mozilla.org/show_bug.cgi?id=1373434)

**Comment by eviljeff** [comment]
I'm inclined to say we should keep AMO similar to how Firefox displays them, but it's an improvement so no harm.

**Comment by wagnerand** [comment]
It looks like has been fixed in the meantime.

<img width="369" alt="Screenshot 2020-07-09 at 12 27 58" src="https://user-images.githubusercontent.com/873258/87028921-a185f500-c1df-11ea-8dcb-2a10da10b763.png">
