### ISSUE TITLE
[Reviewer Tools] Consistency in Spelling

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#447]
Quite a minor issue .....
I noticed that under **Recent Points** it says:

```
Updated Add-on Review
Moderated Addon Review
```

**Comment by wagnerand** [comment]
To give a little bit of context here, there is a missing hyphen in "Moderated Addon Review".

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: me (@wagnerand)

**Comment by Divya063** [comment]
@wagnerand I would like to take this issue.Which files do I need to modify?

**Comment by wagnerand** [comment]
This should be in `src/olympia/constants/base.py#456`.

**Comment by madalincm** [comment]
Verified as fixed in FF55(Win7) in addons-dev.allizom.org
Postfix screencast:
![moderatedadd-onreview](https://user-images.githubusercontent.com/15685441/29617711-6ba6e852-881e-11e7-8e9c-19ec270a3f68.png)
