### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by AllworxAdvAppDev** [mozilla/addons#450]
## Problem report

I wrote and maintain an unlisted add-on for my employer, Allworx Corp. I am trying to upload a new version of the add-on that utilizes WebExtensions (basically just a port of the Chrome version of the add-on). 

I can load an unzipped version of the add-on via `about:debugging`, and everything seems to work just fine. I can't load an unsigned zipped version via `about:addons`, though.

I also can't submit it to AMO to be signed. I have tried to do both of the following:

1. Submit an update to the current add-on, with the proper UUID (`AllworxInteractSyncForFirefox@allworx.com`) in the `manifest.json`. Here is the update URL I am using:

https://addons.mozilla.org/en-US/developers/addon/allworx-interact-sync-for-fire/versions/submit/

2. Submit a new add-on without a UUID specified in the `manifest.json`. Here is the URL used for that:

https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted

Both of these fail with a similar error message. I have made multiple upload attempts today 2017-07-25, between the times 12:00 and 13:00 UTC.

## Extra info

If I load the version without an application ID, then Firefox refuses to load it because it "appears corrupt". I understand that this is expected behavior, as per [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID).

If I load the version with an application ID, then Firefox doesn't complain, but the add-on doesn't work correctly. It appears as if FF can't read all the files in the application. I get console errors like this:

```
Loading failed for the <script> with source “moz-extension://78e0ffa1-9758-46f4-8daf-953f06ac6a9a/common/ExtensionFactory.js”.
```

I can view some of the files in the extension. For example, `view-source:moz-extension://78e0ffa1-9758-46f4-8daf-953f06ac6a9a/background.js` displays the contents of the file, as expected. However, `view-source:moz-extension://78e0ffa1-9758-46f4-8daf-953f06ac6a9a/common/ExtensionFactory.js` complains with **File not found**.

If I navigate to `moz-extension://78e0ffa1-9758-46f4-8daf-953f06ac6a9a/`, I get a file listing for my extension, and `common\ExtensionFactory.js` is one of the files listed.

> Note the backslash, rather than a forward slash. I am running Firefox on a Windows PC. Not sure if this is significant.

## Attachments

I have attached two versions of the add-on, one with the UUID specified in the `manifest.json`, and one without the UUID.

[InteractSyncForFirefox.zip](https://github.com/mozilla/addons/files/1173219/InteractSyncForFirefox.zip)
[InteractSyncForFirefoxNoId.zip](https://github.com/mozilla/addons/files/1173220/InteractSyncForFirefoxNoId.zip)

**Comment by muffinresearch** [comment]
Unpacking that zip file locally shows that it looks like whatever is packaging the file is  not packaging with directories, instead the files contain paths with `\` e.g:  `common\icons\allworx_16.png`.

**Comment by wagnerand** [comment]
See https://github.com/mozilla/addons/issues/442.

**Comment by AllworxAdvAppDev** [comment]
I understand the issue now, however I dispute that it is not a bug. The file is zipped with the standard `System.IO.Compression.FileSystem` library in .NET. Here's the PowerShell commands:

```
Add-Type -AssemblyName "System.IO.Compression.FileSystem"
[System.IO.Compression.ZipFile]::CreateFromDirectory("$tempDir", "$destDir\$destFile")
```

The zip file can be unpacked by the Windows Explorer, byt 7-zip, and by the linux `unzip` command. Note that `unzip` gives the following warning:

```
warning:  InteractSyncForFirefox.zip appears to use backslashes as path separators
```

Also note that I use the exact same method to package up my Chrome extension and submit it to the Chrome Web Store, and I have never had a problem with it. I **strongly** recommend that you consider supporting files zipped in this fashion.

**Comment by wagnerand** [comment]
Since the native Mac extraction program cannot handle this file, I think you could argue either way.

**Comment by AllworxAdvAppDev** [comment]
I understand your argument, but maintain my position. As a user, it is a dissatisfier, and causes unnecessary confusion. Please consider this. Now I'm off to find an alternate way to zip files from PowerShell.

**Comment by wagnerand** [comment]
Reopening this for reconsideration...

**Comment by muffinresearch** [comment]
> Since the native Mac extraction program cannot handle this file as expected, I think you could argue either way.

Would be good to know how the yauzl lib used by the linter (node) and the python unzipping is handling this. I think they're likely to follow the [zip spec](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) which says:

>   4.4.17 file name: (Variable)
> 
>        4.4.17.1 The name of the file, with optional relative path.
>        The path stored MUST not contain a drive or
>        device letter, or a leading slash.  All slashes
>        MUST be forward slashes '/' as opposed to
>        backwards slashes '\' for compatibility with Amiga
>        and UNIX file systems etc.  If input came from standard
>        input, there is no file name field.

**Comment by muffinresearch** [comment]
Also looks like Microsoft have fixed this issue see https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator

**Comment by wagnerand** [comment]
> Would be good to know how the yauzl lib used by the linter (node) and the python unzipping is handling this.

Since validation fails, I think the linter cannot cope with it :)

**Comment by AllworxAdvAppDev** [comment]
> Also looks like Microsoft have fixed this issue

Yeah. I saw that. Thanks. I'm starting to agree that Mozilla shouldn't add any work to support backslash. In addition to being nonstandard, it would introduce a confusing compatibility issue for any add-on that was built in this fashion. However, I still think that it would be nice to proactively detect that this is the reason that validation fails, and give a meaningful error message. It shouldn't be too difficult, and it would save poor schmucks like me hours of headaches. :-)

Unfortunately, there is no version of PowerShell released yet that uses .NET 4.6.1, so I can't use it. As a workaround, I have removed directory structure from the add-on. After spending several hours trying to find a supportable way to script the zip file generation, I decided that keeping directory structure for such a simple add-on wasn't worth the effort.

**Comment by muffinresearch** [comment]
@wagnerand yep, I've guessed as much though the OP didn't detail the specific errors. 

Looks like the yauzl (run via the linter) currently throws:

```
Error: invalid characters in fileName: common\AnimatorFactory.js
```

However in the app you see:

<img width="1033" alt="upload_add-on____developer_hub____add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/28622233-b9f178a2-720b-11e7-8e2f-4bc7f17e255c.png">

If the linter caught the error correctly we can expose a message.

**Comment by muffinresearch** [comment]
I'll file an issue on the linter and we'll handle it there.

**Comment by muffinresearch** [comment]
Closing this issue in favour of the linter issue.
