### ISSUE TITLE
Add Webmaster tools/search console for Google

### ISSUE THREAD

**Issue by peterGerman** [mozilla/addons#452]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
In order to  control how amo pages appear and see how perform on Google results pages we need to initialize the Google Webmaster tools / search console. 

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Verifying Google Webmaster Tools / Search Console
Please add this inside of the <head> </head> tags
<meta name="google-site-verification" content="ueNbCgS4e1JIAgLGwufm-jHaIcLXFLtFMmR_65S1Ag0" />

**Comment by rctgamer3** [comment]
AMO is already verified and linked to Google, I believe. https://addons.mozilla.org/google1f3e37b7351799a5.html

**Comment by EnTeQuAk** [comment]
@muffinresearch or @bqbn is there anything that still needs to happen here? Otherwise let's close this issue.

**Comment by muffinresearch** [comment]
I don't think there's anything to do here - I'm checking with gcull to get access and verify it's all working as expected.

**Comment by peterGerman** [comment]
If it is already verified then it is just a matter of giving access to a few people. Does anyone know who the account admin is?

**Comment by peterGerman** [comment]
@deadsquid can you advise on who is the right contact for getting access to Google Search Console for AMO?

**Comment by garethcull** [comment]
@rctgamer3 would you have access to Google Search Console for AMO? Is there a bug for who instrumented and verified the original implementation?

**Comment by muffinresearch** [comment]
@garethcull can't an analytics admin grant access?

**Comment by garethcull** [comment]
@muffinresearch I would if I could. But Analytics is separate from Search Console, which is why i am requesting access. Does anyone on your team have access to this?

**Comment by muffinresearch** [comment]
@garethcull I thought it was possible to verify with GA - but it looks like that fails unless you're running the latest snippet. I think we'll need to re-verify - I'll set that up.

**Comment by hoosteeno** [comment]
Is there any update on this? I'd like to start looking at AMO in the search console. I would be glad to help -- ping on slack if I can.

**Comment by muffinresearch** [comment]
I'll be able to re-add people once rolls out on Thursday.

**Comment by muffinresearch** [comment]
I have access now I'm just awaiting a list of people to add.

**Comment by muffinresearch** [comment]
@garethcull now has access and can add others as necessary.
