### ISSUE TITLE
Improve Localizations docs

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons#453]
Following feedback here's a few items that need additional clarification.

* [x] Add link to the disco pane directly.
* [x] Add instructions or link to instructions as to how to create a new profile.
* [x] Add screenshots for the advanced configuration.
* [x] Add clarification re: potools and how to access an example of it.

**Comment by peiying2** [comment]
@muffinresearch , any updates on this?

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
