### ISSUE TITLE
Addons cannot be installed from an IPv6-only environment

### ISSUE THREAD

**Issue by nivex** [mozilla/addons#454]
```
$ host -t AAAA addons.mozilla.org
addons.mozilla.org is an alias for olympia.prod.mozaws.net.
$ host -t AAAA olympia.prod.mozaws.net
olympia.prod.mozaws.net has no AAAA record
```
This requires access to a legacy IP environment to install addons.
Please add IPv6 support to addons.mozilla.org to remedy this situation.

**Comment by EnTeQuAk** [comment]
cc @bqbn on this.

**Comment by rctgamer3** [comment]
Don't expect AMO to magically support IPv6 all of a sudden. I filed a bug months ago and there were still issues blocking IPv6 roll-out: [1354049 - AMO does not support IPv6 anymore, only IPv4](https://bugzilla.mozilla.org/show_bug.cgi?id=1354049)

**Comment by nivex** [comment]
Thank you for advising of the bug report in the other tracker. I initially reported this issue in https://discourse.mozilla.org/t/ipv6-support/17451 as it was the only place I had found for feedback at the time. From that thread I was directed here. I can imagine it's hard to keep track of these things when there are so many places to coordinate reports.

It was my understanding that AWS now supported IPv6 on all its offerings including ELBs in VPC, but I do not have access to AWS any longer to verify this. This is a relatively recent and very welcome change in their offerings. If cost is a significant factor, another CDN such as CloudFlare (who supports IPv6 by default) could be explored.

I don't expect anything to "magically" happen. I do hope that I will stop getting vague "in the future" replies to these issues when I raise them across various projects and instead start seeing some concrete timelines. It's even worse when I discover that IPv6 support has been *removed* (this is a regression, folks!) The technology has been made significantly easier in the six years I have been doing IPv6 advocacy work, so the excuses for not deploying are rapidly approaching zero.

--
Kevin Otte
Flying Penguin Technologies
www.flyingpenguintech.org

**Comment by muffinresearch** [comment]
Since there's an existing ops bug open I'm going to close this issue in favour of that one https://bugzilla.mozilla.org/show_bug.cgi?id=1354049
