### ISSUE TITLE
[Reviewer Tools] CSS Syntax Highlighting

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#455]
Recently, the CSS processing has become extremely slow and often result in script error for moderately large file (e.g. 40kb).

It feels that the script is processing far more that necessary. 
Is the same highlighting script used for all file types? e.g. JS, CSS, HTML etc

If that is so, I suggest a more modularised script to separate files types.

Example:
`https://addons.mozilla.org/en-US/firefox/files/browse/693555/file/styles/style.css#top`

PS. I recall posting a similar issue about JSON files and why they needed the most basic Syntax Highlight processing.
There is also #313

**Comment by muffinresearch** [comment]
I think we can close this in favour of #313 which covers the same issue. As mentioned there we are currently looking into what a good replacement for this might be.
