### ISSUE TITLE
Stop featuring addons that are not compatible with FF57

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/addons#457]
A bunch of the featured addons on https://addons.mozilla.org/en-US/firefox/ are not compatible with FF57. We probably shouldn't be advertising addons that won't work after November.

**Comment by devaneymoz** [comment]
Thanks for the note @jrmuizel. We're actually planning to prune the featured collection of non-compatible add-ons on 1 September.

**Comment by diox** [comment]
Looks like it was done.

**Comment by vcarciu** [comment]
All featured add-ons are compatible with 57 in https://addons.mozilla.org/en-US/firefox/ . Marking this as verified

**Comment by jrmuizel** [comment]
It looks like the Up & Coming extension list still include addons that aren't compatible with 57. It seems like it's probably worth removing incompatible addons from that list too.

**Comment by diox** [comment]
That's a different issue, https://github.com/mozilla/addons-server/issues/6181
