### ISSUE TITLE
Self-signed extension not found when trying to download

### ISSUE THREAD

**Issue by hach-que** [mozilla/addons#458]
### Describe the problem and steps to reproduce it:
- Uploaded a Web Extension for self distribution
- Extension was signed
- Tried to download, got 404 from AMO: https://addons.mozilla.org/firefox/downloads/file/697279/netcodeio_support-0.1.5-fx.xpi?src=devhub

### What happened?
AMO 404's when I try to download the signed package.

### What did you expect to happen?
I expected to be able to download the extension for self-distribution.

**Comment by diox** [comment]
Possible dupe of https://github.com/mozilla/addons/issues/324 ; if that's the case the problem will fix itself in a few minutes when the cron to fix affected files runs.

**Comment by muffinresearch** [comment]
@hach-que were you able to get your file after waiting a few minutes?

**Comment by hach-que** [comment]
Haven't had a chance to test it again

**Comment by hach-que** [comment]
Looks like it's working now.
