### ISSUE TITLE
Fix abbr Element Styling

### ISSUE THREAD

**Issue by patrickdark** [mozilla/addons#459]
### Describe the problem and steps to reproduce it:
`abbr` elements **without** a `title` attribute are underlined and `abbr` elements **with** a `title` attribute have two underlines (an underline and bottom border). There should be no underline in the former case and one underline in the latter case.

Reference Page: https://addons.mozilla.org/firefox/addon/ksftd/.

Ideally, the border should also be rendered with `text-decoration-*` properties because text-based underlines adapt to text (e.g., via the `text-decoration-ink` property supported by other browsers), not the `border` property except for browsers that don't support `text-decoration-*` properties such as Microsoft Edge. (CSS `supports` at-rules can be used to accommodate Microsoft Edge.)

**Comment by EnTeQuAk** [comment]
This may be a good first bug, on the other hand are we currently re-implementing this in addons-frontend relatively soon.

**Comment by jvillalobos** [comment]
Agreed. If we're going to fix this, it should be after the new front end is out (possibly in Q4).
