### ISSUE TITLE
In addons search, `tag=firefox57` and `appver=57.0` behave differently

### ISSUE THREAD

**Issue by genodeftest** [mozilla/addons#462]
### Describe the problem and steps to reproduce it:
1. go to addons.mozilla.org
2. search for anything
3. on the results page, AMO shows "works with Firefox 55"
4. change the URL part `appver=55.0` to `appver=57.0` and press enter
5. have a look at the addons listed

### What happened?
AMO also lists addons which are not compatible with Firefox 57.

### What did you expect to happen?
Only list addons compatible with Firefox 57.

### Additional info
Works fine if you add `&tag=firefox57` to the URL.

**Comment by diox** [comment]
There are a few reasons that explain that, combined together:
1. The most important is that mozilla/addons-server#5277 has not landed in prod yet, so legacy extensions are still marked as compatible, but they aren't really. It will land this week.
2. The tag is applied to all webextensions but only webextensions, not dictionaries or search engines. I'll double check if that's really what we want, but it makes sense to me to also tag those.
3. There are a couple edge cases with the tag itself: it's applied to all public webextensions, but some webextensions mistakenly apply a maximum version below 57. Some extensions also were not public when the tag was applied, and are now (we apply the tag when a reviewer approves an add-on, but don't do it if it was re-enabled from devhub). I'll look into this.

**Comment by genodeftest** [comment]
> 1. The most important is that mozilla/addons-server#5277 has not landed in prod yet, so legacy extensions are still marked as compatible, but they aren't really. It will land this week.

This is exactly what I'd like to see. As it is tracked somewhere else, I'll close this report. Thanks for the explanation!
