### ISSUE TITLE
Deleting/removing reviews of disabled/deleted/removed add-ons is impossible

### ISSUE THREAD

**Issue by ghost** [mozilla/addons#464]
### Describe the problem and steps to reproduce it:
Deleting/removing reviews of disabled/deleted/removed add-ons is impossible.

### What happened?
This warning error message:

"We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

If you typed in the address, please double check the spelling.
If you followed a link from somewhere, please let us know at webmaster@mozilla.com. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

Or you can just jump over to some of the popular pages on our website.

Are you interested in a list of featured add-ons?
Do you want to search for add-ons? You may go to the search page or just use the search field above.
If you prefer to start over, just go to the add-ons front page.".

### What did you expect to happen?
Review have to be deleted/removed.

### Anything else we should know?
No.

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file an issue. Could you re-file it in the repository for the site that runs this code? It's this one: https://github.com/mozilla/addons-server/issues/new

**Comment by Anonymous123456789012** [comment]
Done in https://github.com/mozilla/addons-server/issues/6378
but there is too much decentralization here.

**Comment by diox** [comment]
Closing since it was re-filed on addons-server.

**Comment by kumar303** [comment]
Thanks @ghost. Addons related things are spread out here and there but we keep the `addons` repo open so that other folks don't have to know exactly where everything fits.
