### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by relgin** [mozilla/addons#467]
Please attach a copy of your add-on, and fill in the following information:
[MagicCardSpotterMini.zip](https://github.com/mozilla/addons/files/1215362/MagicCardSpotterMini.zip)

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

Error occured during upload of a version.
"Your add-on failed validation with 1 error. Sorry, we couldn't load your WebExtension"

It is a new add-on. Slimmed down and emscriptened version of https://chrome.google.com/webstore/detail/cardspotter-magic-card-sp/doahjhcfgmfpebgljcnhjajkpbkjbndf (which uses pnacl).

Before I added --separate-asm for emscripten it failed to verify since the file was >4MB, now it comes in juuust under that.

It loads and works fine when I do it through about:debugging

* Whether your add-on is listed or unlisted.
Unlisted

* The URL where you submitted the add-on.
https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted

* The approximate time you submitted the add-on, with timezone.
17:05 CEST

**Comment by wagnerand** [comment]
Thank you for the report!

Running the attached file against a local instance results in:

```
$ addons-linter MagicCardSpotterMini.zip

<--- Last few GCs --->

[67719:0x104800000]    51520 ms: Mark-sweep 1405.1 (1459.6) -> 1405.0 (1437.1) MB, 3643.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 3644 ms) last resort
[67719:0x104800000]    55158 ms: Mark-sweep 1405.0 (1437.1) -> 1405.1 (1437.1) MB, 3637.2 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x27e70a79cca1 <JSObject>
    1: close [/usr/local/lib/node_modules/addons-linter/node_modules/escope/lib/referencer.js:~157] [pc=0x11d0ba0a8a33](this=0x137e9e025581 <Referencer map = 0x1974e679dcc1>,node=0x21b362f7b8b9 <Node map = 0x1974e67a0971>)
    2: BlockStatement [/usr/local/lib/node_modules/addons-linter/node_modules/escope/lib/referencer.js:~503] [pc=0x11d0ba0d57ee](this=0x137e9e025581 <Referencer map = 0x1974e6...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::TranslationBuffer::CreateByteArray(v8::internal::Factory*) [/usr/local/bin/node]
 7: v8::internal::compiler::CodeGenerator::PopulateDeoptimizationData(v8::internal::Handle<v8::internal::Code>) [/usr/local/bin/node]
 8: v8::internal::compiler::CodeGenerator::FinalizeCode() [/usr/local/bin/node]
 9: void v8::internal::compiler::PipelineImpl::Run<v8::internal::compiler::FinalizeCodePhase>() [/usr/local/bin/node]
10: v8::internal::compiler::PipelineImpl::FinalizeCode() [/usr/local/bin/node]
11: v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl() [/usr/local/bin/node]
12: v8::internal::CompilationJob::FinalizeJob() [/usr/local/bin/node]
13: v8::internal::Compiler::FinalizeCompilationJob(v8::internal::CompilationJob*) [/usr/local/bin/node]
14: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [/usr/local/bin/node]
15: v8::internal::StackGuard::HandleInterrupts() [/usr/local/bin/node]
16: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
17: 0x11d0b9e040dd
18: 0x11d0ba0a8a33
Abort trap: 6
```

**Comment by relgin** [comment]
Thank you for being so fast. The output doesn't make much sense to me
unfortunately. Do you know of a guide somewhere so I can address the issue?
Also, do you know why loading the addon with about:debugging doesn't warn
about this issue?

Best
Jonas Gillberg

**Comment by wagnerand** [comment]
I'm not sure there is much you can do at this point. We need to figure out
why this error happens. Thank you.

**Comment by EnTeQuAk** [comment]
I'm pretty sure `CSTest.asm.js` is breaking our parsing library, that amount of memory aquired during the process looks too much though. Not sure what to look for yet but I'll look into it once there's time.

**Comment by muffinresearch** [comment]
@EnTeQuAk did you get a chance to investigate this further?

**Comment by relgin** [comment]
Hi, I'm not sure if it matters but I have switched to webassembly so this
particular problem is probably not relevant to me any more. I currently
cannot work on this so I have not tried submitting that version.

Cheers
Jonas

**Comment by wagnerand** [comment]
Closing as this is a very old issue and many changes have happened since then. Please reopen if or create a new issue if it's still an problem.
