### ISSUE TITLE
Various extensions inexplicably not, or no longer, installable to Firefox on FreeBSD through the GUI to addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons#468]
## Primary example

Vertical Tabs Reloaded https://addons.mozilla.org/firefox/addon/vertical-tabs-reloaded/

Version 0.8.4-alpha can be installed to versions 54.0.1 and 55.0 of Firefox. 

Release 0.8.4 **can not be installed to 55.0 through the `addons.mozilla.org` GUI**: 

![2017-08-10 20 13 19 vertical tabs reloaded add-ons for firefox - mozilla firefox](https://user-images.githubusercontent.com/192271/29187695-9900a330-7e08-11e7-84af-7333f3b50080.png)

Discussed a few hours ago at https://matrix.to/#/!xAcrCyjpCWOtluwgSS:matrix.org/$15023547682741799LRwDQ:matrix.org where the developer @Croydon has no explanation. 

## Expected

An option to _install anyway_ (maybe with a choice between Linux, Mac or Windows). 

## Actual results: 

According to AMO: 

> Not available for your platform

– **and** the _Add to Firefox_ button is inexplicably greyed out; **no** option to _install anyway_. 

## Other examples

Font Contrast Fix https://addons.mozilla.org/firefox/addon/font-contrast-fix/ by Fushko

RevEye Reverse Image Search https://addons.mozilla.org/firefox/addon/reveye-ris/ by SuperFreakonomics

Sum Tabs https://addons.mozilla.org/firefox/addon/sum-tabs/ by @Timvde who – like @Croydon – can think of no reason for `addons.mozilla.org` treating the extension as uninstallable. 

Tab Counter https://addons.mozilla.org/firefox/addon/tab-counter-webext/ by @DaAwesomeP 

Vertigo Tabs https://addons.mozilla.org/firefox/addon/vertigo-tabs/ by @idlewan 

## Workaround

For the six examples above I booted a Linux machine, copied the URL of each of the installation buttons. Truncated slightly (for tidiness), in alphabetical order: 

- https://addons.mozilla.org/firefox/downloads/latest/font-contrast-fix/platform:2/addon-837937-latest.xpi
- https://addons.mozilla.org/firefox/downloads/latest/reveye-ris/platform:2/addon-770649-latest.xpi
- https://addons.mozilla.org/firefox/downloads/latest/sum-tabs/platform:2/addon-840959-latest.xpi
- https://addons.mozilla.org/firefox/downloads/latest/tab-counter-webext/platform:2/addon-794989-latest.xpi
- https://addons.mozilla.org/firefox/downloads/latest/vertical-tabs-reloaded/platform:2/addon-616590-latest.xpi
- https://addons.mozilla.org/firefox/downloads/latest/vertigo-tabs/platform:2/addon-835264-latest.xpi

With Firefox 55.0 on FreeBSD: 

- none of the six could be installed through the AMO GUI
- all six installed without difficulty
- RevEye Reverse Image Search, Sum Tabs, Tab Counter, Vertical Tabs Reloaded and Vertigo Tabs work as expected
- I have not had an opportunity to test Font Contrast Fix. 

## Additional concern

For some other extensions, I wonder whether AMO will fail to serve applicable updates.

**Comment by grahamperrin** [comment]
Additional information, from @Timvde in IRC for `#firefox`: 

> … an issue with AMO indeed. I wanted it not to be available for Android, but selecting anything but "All platforms" disables BSD... I'll change that next update and just allow Android.

I see #5647 … if an extension is explicitly compatible with Linux, then there remains the expectation that AMO should offer to install for Linux "anyway" (or words to that effect).

**Comment by diox** [comment]
The option to install add-ons deemed incompatible is gone because it could lead users to install completely broken add-ons (see mozilla/addons-server/issues/6028). That problem began to be a higher priority with the lead up to Firefox 57, both because of legacy add-ons that would not be compatible with 57 but also new webextensions using newly released APIs that would not necessarily work with 56 or lower.

Is there a problem with the install button and those add-ons and Linux, or is it just BSD?

> if an extension is explicitly compatible with Linux, then there remains the expectation that AMO should offer to install for Linux "anyway" (or words to that effect).

There is no guarantee that an add-on compatible with Linux, especially a legacy one, will work on BSD - such an add-on could make any kind of call to a linux-specific library or binary and be broken on BSD. Nevertheless, since it's not a supported platform anyway, I'd be willing to consider BSD as compatible with Linux if that's the only problem in this issue.

**Comment by grahamperrin** [comment]
Thanks, for the speedy response. I'm not seeking any thing like a guarantee of compatibility. 

It's weird to find that (if I understand correctly) when a developer wants to _properly_ not suggest that an extension is compatible with Android, the end result is _improper_ absolute prevention of installation on something completely unrelated to Android. 

Re: __Master Sites_ at http://www.freshports.org/www/firefox/ the port to FreeBSD is built from Mozilla's code for Linux e.g. `firefox-55.0.1.source.tar.xz` so :-) please continue to allow end users to make their own decisions about whether to risk installation of extensions that are explicitly compatible with Linux. 

----

Can developers foresee any situation in which a a release of 57 or greater will allow a WebExtensions-compatible extension to call upon a platform-specific binary? (I know next to nothing about WebExtensions, but I imagine that there is, or should be, a move away from such calls).

**Comment by diox** [comment]
> It's weird to find that (if I understand correctly) when a developer wants to properly not suggest that an extension is compatible with Android, the end result is improper absolute prevention of installation on something completely unrelated to Android.

It's weird, yes, and it's a bug (although a bigger one than just considering linux-compatible add-ons compatible with BSD). See mozilla/addons-server/issues/6067 for more discussion about that specific part.

> the port to FreeBSD is built from Mozilla's code for Linux e.g. firefox-55.0.1.source.tar.xz so :-) please continue to allow end users to make their own decisions about whether to risk installation of extensions that are explicitly compatible with Linux.

I'll implement the fix for BSD to be considered Linux-compatible, but keep in mind BSD is not a supported platform. I don't mind doing it now because it's relatively easy, but the code is old and fragile and I can't promise it won't break again in the future - I had no idea the recent compatibility changes I made would have this impact.

> Can developers foresee any situation in which a a release of 57 or greater will allow a WebExtensions-compatible extension to call upon a platform-specific binary? (I know next to nothing about WebExtensions, but I imagine that there is, or should be, a move away from such calls).

Through [`nativeMessaging`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging) a webextension could talk to a platform-specific binary. It's a fairly specific API, and most add-ons won't need that, but some might.

**Comment by diox** [comment]
Fix should land in production next Thursday.

**Comment by grahamperrin** [comment]
Thanks!

> … for BSD to be considered Linux-compatible, but keep in mind BSD is not a supported platform. …

Understood. 

For reference only, from `about:buildconfig` for 55.0.1 (64-bit): 

- target: x86_64-unknown-freebsd12.0
- `/usr/bin/cc -std=gnu99` | `5.0.0` | `-Qunused-arguments -Wall -Wempty-body -Wignored-qualifiers  -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code  -Wclass-varargs -Wloop-analysis -Wstring-conversion  -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wformat  -Wno-gnu-zero-variadic-macro-arguments -Wformat-security -O2 -pipe -O3  -DLIBICONV_PLUG -fstack-protector -isystem /usr/local/include  -fno-strict-aliasing -fno-strict-aliasing -ffunction-sections  -fdata-sections -fno-math-errno -pipe -I/usr/local/include`
- `/usr/bin/c++ -std=gnu++11` | `5.0.0` | `-Qunused-arguments -D_GLIBCXX_USE_C99  -D_GLIBCXX_USE_C99_MATH_TR1  -D_DECLARE_C99_LDBL_MATH -DLIBICONV_PLUG  -isystem /usr/local/include   -Qunused-arguments -Wall -Wc++11-compat  -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith  -Wsign-compare -Wtype-limits -Wunreachable-code -Wwrite-strings  -Wno-invalid-offsetof -Wclass-varargs -Wloop-analysis  -Wc++11-compat-pedantic -Wc++14-compat -Wc++14-compat-pedantic  -Wc++1z-compat -Wcomma -Wimplicit-fallthrough -Wstring-conversion  -Wno-inline-new-delete -Wno-error=deprecated-declarations  -Wno-error=array-bounds -Wformat -Wno-gnu-zero-variadic-macro-arguments  -Wformat-security -Wno-unknown-warning-option -Wno-return-type-c-linkage  -O2 -pipe -O3 -DLIBICONV_PLUG -fstack-protector -isystem  /usr/local/include -fno-strict-aliasing -DLIBICONV_PLUG -isystem  /usr/local/include -fno-exceptions -fno-strict-aliasing -fno-rtti  -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno  -pipe -I/usr/local/include  -O2 -O3 -fomit-frame-pointer   -D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH_TR1  -D_DECLARE_C99_LDBL_MATH  -DLIBICONV_PLUG -isystem /usr/local/include`
- configure options: `CONFIG_SHELL=/bin/sh --enable-application=browser --enable-update-channel=release --disable-tests PKG_CONFIG=pkgconf CC=cc CXX=c++ --disable-debug-symbols --enable-system-ffi --enable-default-toolkit=cairo-gtk3 --with-system-graphite2 --with-system-harfbuzz --enable-necko-protocols=default PERL=/usr/local/bin/perl MAKE=gmake --enable-system-hunspell --enable-alsa --enable-dtrace --enable-extensions=default --disable-gconf --disable-gold --disable-install-strip --disable-libproxy --enable-official-branding --enable-optimize --enable-pie --enable-pulseaudio --enable-release --enable-startup-notification --disable-strip --enable-system-pixman --enable-system-sqlite --prefix=/usr/local --with-intl-api --with-pthreads --with-system-bz2 --with-system-icu --with-system-jpeg=/usr/local --with-system-libevent --with-system-libvpx --with-system-nspr --with-system-nss --with-system-ogg --with-system-png=/usr/local --with-system-vorbis --with-system-zlib`

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by grahamperrin** [comment]
Fix confirmed, thanks: 

![2017-08-23 04 11 48](https://user-images.githubusercontent.com/192271/29679135-df528c2c-88f8-11e7-8692-6806daf37ddb.png)
