### ISSUE TITLE
discovery mechanism for add-ons/themes in Firefox

### ISSUE THREAD

**Issue by designakt** [mozilla/addons#47]
Build a way for people to discover add-ons in Firefox.
Currently add-ons are mostly discovered by learning about an add-on through other people or finding one as a solution to a problem one has. This leaves out all users that are not aware that something they do could be made easier with the use of an add-on.
This should help people see that add-ons exist, and that their browsing experience could be made better through the use of one. And maybe spark their interest to explore which other add-ons exist and understand the concept of customizing the browser & the web.

[Ideation and Concept Document (Add-on Discovery UX)](https://docs.google.com/document/d/1_vaOV3zRdFxlozcQrKoLNyKAT84fRXPnyRa-HJaTkJs/edit#)

[**possible ways to discover an add-on**, types of users, level of understanding](https://www.lucidchart.com/documents/edit/1a0c645e-4475-46e8-9aed-98828f7b7dda/1)

**Comment by designakt** [comment]
In issue #51 I added how Chrome handles Momentum changing the newTab page. Might be interesting to compare with your first concept on that.

**Comment by tsteuer** [comment]
## Existing Suggestions in Firefox


#### Improve search suggestions

![hello](https://cloud.githubusercontent.com/assets/18701233/15951795/c0ab3aaa-2ebb-11e6-9408-ddcddac3a2fe.PNG)
---
#### Set rules

![dialog](https://cloud.githubusercontent.com/assets/18701233/15951799/c0af4b7c-2ebb-11e6-89fb-bd9c61b51d9e.PNG)
---
#### Add search engine

![search](https://cloud.githubusercontent.com/assets/18701233/15951797/c0ad2ffe-2ebb-11e6-9cf0-6db353526f84.PNG)
---
#### Snippets

![snippet](https://cloud.githubusercontent.com/assets/18701233/15951796/c0abb304-2ebb-11e6-9f72-debac6ed2ba1.PNG)
---
#### Undo deleting Tiles

![undo](https://cloud.githubusercontent.com/assets/18701233/15951800/c0b3032a-2ebb-11e6-908a-8cb067ca8e1f.PNG)
---
#### Update Nightly

![update](https://cloud.githubusercontent.com/assets/18701233/15951798/c0ad80c6-2ebb-11e6-9b0f-656368aae2c4.PNG)

**Comment by tsteuer** [comment]
[![search suggestions](https://cloud.githubusercontent.com/assets/18701233/15951795/c0ab3aaa-2ebb-11e6-9408-ddcddac3a2fe.PNG)](https://invis.io/2E7635W56)

**Comment by tsteuer** [comment]
## Visual Brainstorming #1

##### Description
The following screens show different options to place one specific Add-on for discovery in Firefox.

---
### UI Tour
![ui_tour](https://cloud.githubusercontent.com/assets/18701233/15962726/6a529da4-2f0d-11e6-8192-675f7f230c29.png)
*Customize promoted service and message to users needs.*
---
### Snippet
![snippet](https://cloud.githubusercontent.com/assets/18701233/15962730/70740128-2f0d-11e6-958e-3f1a5dd796fe.png)

---
### Tile
![tile](https://cloud.githubusercontent.com/assets/18701233/15962728/7071a1d0-2f0d-11e6-9e7d-b75ec98c487a.png)
*Customize promoted service and message to users needs.*

---
#### Toolbar
![Toolbar](https://cloud.githubusercontent.com/assets/18701233/15962729/707294d2-2f0d-11e6-96c5-27b0359c0e69.png)
*Place new partners in the Toolbar.*

---
### Customization
![customization](https://cloud.githubusercontent.com/assets/18701233/15962727/704ca326-2f0d-11e6-9214-34823da59f38.png)
*Place suggestions in customization to add to Toolbar*

**Comment by tsteuer** [comment]
## Visual Brainstorming II

##### Description
The following screens show different ways to show the user the most fitting Add-ons in convenient places.

---
### History related
*Place new partners in the Toolbar.*
![Toolbar](https://cloud.githubusercontent.com/assets/18701233/15962729/707294d2-2f0d-11e6-96c5-27b0359c0e69.png)


### Connection fail related
*01. The user is reading an article on nytimes.com while several connection fails occur.*
![connection_fail_related_01](https://cloud.githubusercontent.com/assets/18701233/15967774/47717bea-2f29-11e6-95b1-c05c054b01bf.png)
![connection_fail_related_02](https://cloud.githubusercontent.com/assets/18701233/15967771/476f02d4-2f29-11e6-93ea-47acf4833dc0.png)
![connection_fail_related_03](https://cloud.githubusercontent.com/assets/18701233/15967769/476a81a0-2f29-11e6-8ecb-5f240920459e.png)

*02. The user is watching videos on youtube.com while several connection fails occur.*
![connection_fail_related_04](https://cloud.githubusercontent.com/assets/18701233/15967770/476e7ce2-2f29-11e6-85ce-c81574cd390d.png)
![connection_fail_related_05](https://cloud.githubusercontent.com/assets/18701233/15967772/476fdcfe-2f29-11e6-82fd-9725341bd7c3.png)


### New Tab related
*The user has lots of Tabs open. As he opens the Dropdown to change the current Tab, a Add-on suggestion appears.* 
![tab_related_01](https://cloud.githubusercontent.com/assets/18701233/15967777/478945fe-2f29-11e6-9b7e-184a139239f1.png)
![tab_related_02](https://cloud.githubusercontent.com/assets/18701233/15967776/4786a1a0-2f29-11e6-99bf-70ec88242cfc.png)


### Web page related
*The Site Information Panel offers Web Page related Add-on suggestions.*
![web_page_related_01](https://cloud.githubusercontent.com/assets/18701233/15967780/478c9858-2f29-11e6-930d-d0952cd84888.png)
![web_page_related_02](https://cloud.githubusercontent.com/assets/18701233/15967778/47898d52-2f29-11e6-8887-e65930df612b.png)


### Content related
*The user right clicks on the Play Button of a Soundcloud file.*
![content_related_01](https://cloud.githubusercontent.com/assets/18701233/15968013/7267e716-2f2a-11e6-9939-635ef75780dd.png)
![content_related_02](https://cloud.githubusercontent.com/assets/18701233/15968014/72683d92-2f2a-11e6-87e9-7a099b2e132c.png)


### Privacy related
*While changing the Privacy Settings an icon appears to give the user further information on privacy related Add-ons.*
![privacy_related_01](https://cloud.githubusercontent.com/assets/18701233/15967779/478b0484-2f29-11e6-9598-ac7f0ae95d0e.png)
![privacy_related_02](https://assets/18701233/15967775/47850d5e-2f29-11e6-84ee-97a178f0b600.png)

**Comment by tsteuer** [comment]
## Mockups

[![Mockup #1](
https://cloud.githubusercontent.com/assets/18701233/15969170/1d4a83e2-2f2f-11e6-81b3-daffd91dd9c0.png)](https://invis.io/2E7635W56)
*Hijacked Browser with an unnoticed change of the Start Page and the default search setting. Furthermore a suggestion for an Adblocker as the user enters Reddit.*

**Comment by tsteuer** [comment]
##Visual Brainstorming III

###Site related Add-on suggestions as Notifications
*Notifications that could 

![push_notifications](https://cloud.githubusercontent.com/assets/18701233/17017750/01084d24-4f35-11e6-9c04-01090bcc3487.png)
show up as the user visits certain web pages*

![push_notifications_toggle](https://cloud.githubusercontent.com/assets/18701233/17017756/059b7ac8-4f35-11e6-97de-0dc17bfc9821.png)

![push_notifications_toggle_more](https://cloud.githubusercontent.com/assets/18701233/17017761/09724e1a-4f35-11e6-9823-914f8ac18b60.png)

**Comment by tsteuer** [comment]
## Redesign
*Redesign of the current Contextual Feature Recommender refering to [this issue](https://github.com/raymak/contextualfeaturerecommender/issues/258)*.
[![Redesign of the Feature Recommender](
https://cloud.githubusercontent.com/assets/18701233/17435592/44620f68-5b12-11e6-99b1-380a575d467f.png)](https://invis.io/6V82YZFK7)

### Measurements

All Screendesigns refer to the [Styleguide for Panels](https://firefoxux.github.io/StyleGuide/#/panels "Firefox Styleguide for Panels").

*Shortcut Panel*

![redesign_fr_rules_shortcut_panel](https://cloud.githubusercontent.com/assets/18701233/17443218/b3bd102a-5b39-11e6-96c3-e17a61a23edc.png)


*Shortcut Panel with Details*

![redesign_fr_rules_shortcut_info_panel](https://cloud.githubusercontent.com/assets/18701233/17443242/d2916db6-5b39-11e6-9252-36cc21b4f449.png)


*Add-on Panel*

![redesign_fr_rules_add-on_panel](https://cloud.githubusercontent.com/assets/18701233/17443253/dfdb8600-5b39-11e6-8f96-4ccd3e5b8857.png)
