### ISSUE TITLE
Animated top bar on addons.mozilla.org

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/addons#470]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Visited addons.mozilla.org

A video defeated my animation blockers, so I need new animation blockers.

### What happened?

I got hit with pain/animation. addons.mozilla.org has an expanding top bar as it loads.

### What did you expect to happen?

... Frankly I expect to get hit with pain/animation, but it's not good.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

![screen shot 2017-08-13 at 8 48 29 pm](https://user-images.githubusercontent.com/12875862/29254819-d6f98528-8068-11e7-99b8-a39f0fa33442.png)

I also have a user style to block promos:

@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain(addons.mozilla.org){#promos{display:none}}

and to try to block the top bars:

@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain(support.mozilla.org){
 body.scroll-header{padding-top:45px!important}
 body.scroll-header>header{visibility:collapse!important; opacity:0;}
}

Disabling these doesn't keep the top bar from expanding. Fortunately, the top bar does scroll with the rest of the page, unlike many other top bars which change shape instead of scrolling with the rest of the page.

**Comment by tofumatt** [comment]
That animation will be going away in the new add-ons design coming soon. I can't quite tell what your actual issue was here other than the was an animation. It will go away in a redesign we're working on, for what it's worth.

If you could clarify your issue we can reopen it. Cheers.

**Comment by MarjaE2** [comment]
I was referring to the way the top bar animates as it loads.
