### ISSUE TITLE
Add Firefox footer links to AMO

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/addons#471]
We have a new set of footer links on www.mozilla.org. Since adding them we've seen:

* millions of downloads from visitors who used a footer link to navigate to a product they want to download
* improvements in SEO as a result of having these links on many pages

I've spoken with several members of the AMO team and all are supportive of adding links to the footer resembling the ones on www.mozilla.org. Here are specs for those -- they include utm parameters so we can attribute clicks to the AMO footer:

**[Firefox](https://www.mozilla.org/firefox/?utm_source=addons.mozilla.org&utm_campaign=footer&utm_medium=referral)**
[Download Firefox](https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&utm_campaign=footer&utm_medium=referral) 
[Android Browser](https://www.mozilla.org/firefox/android/?utm_source=addons.mozilla.org&utm_campaign=footer&utm_medium=referral) 
[iOS Browser](https://www.mozilla.org/firefox/ios/?utm_source=addons.mozilla.org&utm_campaign=footer&utm_medium=referral)
[Focus Browser ](https://www.mozilla.org/firefox/focus/?utm_source=addons.mozilla.org&utm_campaign=footer&utm_medium=referral)
[Desktop Browser](https://www.mozilla.org/firefox/desktop/?utm_source=addons.mozilla.org&utm_campaign=footer&utm_medium=referral) 
[Beta, Nightly, Developer Edition](https://www.mozilla.org/firefox/channel/desktop/?utm_source=addons.mozilla.org&utm_campaign=footer&utm_medium=referral) 

Localization for these is already underway and likely completed for many locales on www; it may be possible to reuse that work here.

-------

- [x] Add links to addons-server (https://github.com/mozilla/addons-server/issues/6167)
- [x] Add links to addons-frontend (https://github.com/mozilla/addons-frontend/issues/2935)

**Comment by hoosteeno** [comment]
This work will directly impact the number of Firefox downloads we get ...

* as referrals from AMO
* via organic search

That means it directly helps one of Mozilla's top 2017 objectives, and the sooner we implement the more it helps.

**Comment by tofumatt** [comment]
I've created two separate issues for this as we'll need to add the links in both addons-server and addons-frontend.

**Comment by muffinresearch** [comment]
We have this on both the old and new frontend now so this can be closed.

I'm going to file an issue separately to make the links on the legacy frontend be localized because they can't be at the moment.
