### ISSUE TITLE
"requires-restart" addons are not marked as legacy until after installation

### ISSUE THREAD

**Issue by hwine** [mozilla/addons#472]
### Describe the problem and steps to reproduce it:
1. goto https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/?src=search
2. note that you get a green install button (at least on Mac 55.0)
3. install addon
4. note "restart" message
5. restart Fx
6. now you get "legacy" message

### What happened?
addon installed fine

### What did you expect to happen?
have these labeled as "legacy" in amo

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by yfdyh000** [comment]
The Permissions have the "legacy" info.

**Comment by hwine** [comment]
my expectations are to have the "legacy" badge applied. Or somehow be actively warned before installation.

**Comment by yfdyh000** [comment]
I don't understand its purpose. If the user's Firefox installation does not support the legacy add-ons, it is labeled.

**Comment by hwine** [comment]
Not on AMO for me. Here's my view without the nice yellow "legacy" badge:
![screen shot 2017-08-14 at 11 34 16](https://user-images.githubusercontent.com/132412/29285807-a0407dda-80e4-11e7-80f6-9566f7d00767.png)

**Comment by muffinresearch** [comment]
@hwine hi - there was a conscious decision made to not use the same wording on AMO as used in Firefox see https://github.com/mozilla/addons-server/issues/4974 for the related discussion. 

The way it currently works is to show `Compatible with Firefox 57+` for web extensions.

**Comment by hwine** [comment]
Okay (although I think our wording has changed a bit since then). fwiw I do find it very confusing and frustrating. Which may be why I posted the wrong screenshot. 

Inside firefox, there is no indication of any compatibility status in the display:
![screen shot 2017-08-14 at 13 04 03](https://user-images.githubusercontent.com/132412/29289414-3ce72d26-80f1-11e7-8efd-25672cc1dcf1.png)

**Comment by yfdyh000** [comment]
@hwine This interface will be removed, https://bugzilla.mozilla.org/show_bug.cgi?id=1263313

**Comment by hwine** [comment]
Great -- good cookie crumbs if anyone else stumbles on the issue.
