### ISSUE TITLE
Places Maintenance doesn't work

### ISSUE THREAD

**Issue by AlkisPis** [mozilla/addons#473]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
See below.

### What happened?
I just installed "Places Maintenance" add-on for Firefox and it doesn't work - Also I can't see my Bookmarks anymore!

### What did you expect to happen?
I did as per the add-on instructions, You click "Options" in "Places Maintenance" in Add-ons list. It only displays "Fetching stats ..." and that's all.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
It is the author of the add-on (Mak, https://addons.mozilla.org/en-US/firefox/user/mak77/) who must have a link for support/contact!

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on.

If you're having an issue with an add-on please contact the developer directly; you can find a link to their contact details on the add-on page on https://addons.mozilla.org/

If there isn't any contact info available for that developer we're sorry about that, but we aren't able to offer support for add-one that weren't developed by Mozilla.
