### ISSUE TITLE
Add a global non-Fx download button in header

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/addons#474]
We recently added a global download button to the header of SUMO and saw a very large bump in referral downloads from that site (appx 400% increase from before, when SUMO had a more targeted button). 

AMO already has a strong referral download rate thanks to the inline links on individual addons. But there are still appx. 150,000 non-Firefox, non-Thunderbird visitors a week to AMO who might not see one of those calls to action. They're primarily using Chrome. They visit pages like...

* /thunderbird
* /android
* /seamonkey

If we added a non-Fx download button to the header, we might see an increase in referral downloads coming from AMO. See attached (ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1385087) for SUMO's treatment.

![screen shot 2017-08-24 at 1 53 05 pm](https://user-images.githubusercontent.com/94519/29686114-0367684a-88d5-11e7-8270-5b2195bffe92.png)

**Comment by tofumatt** [comment]
This will need some UX input. Timely, as I'm implementing the new AMO header right now 😅

**Comment by chrismore** [comment]
Also, to follow just what was put on SUMO, the UTM parameter for the button should be:

utm_source=addons.mozilla.org
utm_medium=referral
utm_campaign=non-fx-download-button

As in:

https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=non-fx-download-button

r? @hoosteeno and Gareth can confirm that is what they want.

**Comment by pwalm** [comment]
Something like this?
<img width="1318" alt="screen shot 2017-08-24 at 2 27 48 pm" src="https://user-images.githubusercontent.com/6797635/29689573-86976c08-88d8-11e7-9ec2-c49b1477cc91.png">

**Comment by pwalm** [comment]
I'm partial to the middle option, myself.

**Comment by tofumatt** [comment]
Yeah I definitely prefer the middle one too.

**Comment by hoosteeno** [comment]
Beautiful!

Middle option is the most pleasing to me, also, but I'm here to tell you that [big green buttons perform the best](https://bugzilla.mozilla.org/show_bug.cgi?id=1361873).  Difference might be 2%+ more clicks.

**Comment by tofumatt** [comment]
I guess at least most users won't be seeing it and it DOES grab one's attention a fair bit. 😄

**Comment by pwalm** [comment]
Number 3 it is then! It is quite "in your face", but I guess that's what we're going for, right? 😸

**Comment by muffinresearch** [comment]
This was already implemented on the new frontend so I'm closing this issue out.
