### ISSUE TITLE
Please sign domain addons.mozilla.org with DNSSEC

### ISSUE THREAD

**Issue by genodeftest** [mozilla/addons#478]
### Describe the problem and steps to reproduce it:
The server at addons.mozilla.org is not signed using DNSSEC.

Steps to reproduce:
With a dnssec-enabled dns server (such as unbound with dnssec-trigger), run `$ dig addons.mozilla.org`.

### What happened?
No dnssec

### What did you expect to happen?
Should have dnssec-enabled flags (RRSIG, …)

### Anything else we should know?
Same bug report for bugzilla.mozilla.org: https://bugzilla.mozilla.org/show_bug.cgi?id=1384613
www.mozilla.org is signed.

A look at https://www.dnssec-tools.org/ might help.

**Comment by muffinresearch** [comment]
I've re-filed this as https://bugzilla.mozilla.org/show_bug.cgi?id=1398164
