### ISSUE TITLE
Provide a UI for migrating users' add-ons to e10s

### ISSUE THREAD

**Issue by designakt** [mozilla/addons#48]
see https://bugzilla.mozilla.org/show_bug.cgi?id=1181835

**Comment by designakt** [comment]
@deadsquid I need your input on what it is we can do here and some background on the topic. If this is still uncertain, I am happy to just meet so that you can talk me through the current state, and we can come up with the questions together.

**Comment by designakt** [comment]
First draft of a flow to inform users about disabled add-ons and help them remove or replace add-ons.
![160425_disabled_addons](https://cloud.githubusercontent.com/assets/8145891/14789011/cdf4fafe-0b0a-11e6-9939-1d23e6a782b6.png)

**Comment by designakt** [comment]
[160425_Disabled_Addons.zip](https://github.com/mozilla/addons/files/235068/160425_Disabled_Addons.zip)
@pwalm here is the current source.

**Comment by designakt** [comment]
Considerations from discussion with @pwalm and Design Critique:

- Limit audience that will need to see this as good as we can as is not what they came to use Firefox for.
- Offer actions for user to take, not just inform them.
  - **Replace**
    - with known alternative ( if we know of one)
    - with add-on from AMO (one click search for keywords of disabled add-on) 
  - **Remove**
  - _**Wait** for add-on to be updated_ (engage with dev)
- What should “replace” do?
  - install replacement and remove disabled add-on?
  - install replacement but leave disabled add-on installed?
    - What happens when disabled add-ons becomes e10s compatible?
      - Enable disabled add-on?
      - Enable disabled add-on and disable replacement?
      - Inform user and help them take action?
      - Leave disabled even if it becomes e10s compatible?

-
- Rather text-heavy currently. - could use a visual explanation of what is happening...
- a lot of color (might reduce green, and yellow)
- weak hierarchy (not clear what is grouped together)
- group add-ons disabled for the same reason to reduced doubled information.
- make choices clear for each add-on (replace, remove) - what is it we recommend?
- collapse disabled add-ons by default in overview
- consider using another symbol for replace (to similar to sync)
- improve tone of texts (will check with Matej as soon as concept ready)

**Comment by pwalm** [comment]
![addons-pref pane](https://cloud.githubusercontent.com/assets/6797635/15031370/fe2cf466-120c-11e6-9e5e-35a5153ac6e6.png)

**Comment by pwalm** [comment]
![addons-second version 3 copy 2](https://cloud.githubusercontent.com/assets/6797635/15119385/8843e5b8-15c5-11e6-9bde-9d0ae16f6364.png)
Mild updates:
- Added the install switch. The button lables of "Enable/Disable" are problematic if we're also disabling add-ons by force.
- Changed button colours.
- Removed "More". The same info exists behind preferences.

**Comment by pwalm** [comment]
Should "Preferences" only appear on hover?

**Comment by brampitoyo** [comment]
I like hiding “Preferences” until you hover over it because it reduces everything down to a simple on/off switch. At the same time, this is a pattern that we don’t use in other in-content pages (e.g. about:preferences) and cannot be applied to Android.

What’s your thought on replacing the word “Preferences” with something like a gear icon? This way, it’s always shown, but it doesn’t clutter up the page so much.

**Comment by designakt** [comment]
Working on a model to relate all relevant aspects of e10s migration and add-ons.
https://www.lucidchart.com/documents/edit/a3519bf8-bf3b-45f9-9563-8484accd966f#
![e10s add-on migration - e10s migration flow](https://cloud.githubusercontent.com/assets/8145891/15259138/d58d685c-194f-11e6-8548-2a3affaf8aa6.png)
_I am not certain if this is an accurate reflection of current plans. Needs to be cofirmed by Shell or @deadsquid._

**Comment by pwalm** [comment]
all screens for redesigned add-on/theme pref panes:
https://github.com/mozilla/addons/issues/111

**Comment by designakt** [comment]
Updated model after meeting today.
![e10s add-on migration flow ux - e10s migration flow](https://cloud.githubusercontent.com/assets/8145891/15407842/6540cf18-1e0d-11e6-8f24-cb3d1e4f00fc.png)
Will need to discuss options with @deadsquid and barbara.

**Comment by designakt** [comment]
![](https://cloud.githubusercontent.com/assets/6797635/15341660/e29fddf2-1c44-11e6-8949-af825c74f102.png)
@pwalm this looks so much cleaner and structured, but I still have some questions when looking at the new disabled add-ons and replacement:
- Will users know what the add-on did without its description? (as it has been replaced with the problem description)
- Will we (be able to) provide multiple alternatives per add-on? @deadsquid 
- What will it look like if we do not suggest a replacement? (same as [above](https://github.com/mozilla/addons/issues/48#issuecomment-217910192)?)
- How can users get more information about the replacement before installing? (i.e. see details page on AMO, ratings, comments, etc.)

**Comment by pwalm** [comment]
@designakt 
- tried keeping the description, and the density of the page skyrockets. Maybe we can keep the description behind the Preference (or "info") button?
- this design can scale from 0-3 add-ons easily, so we don't have to have three for every disabled option.
- the add-on will look the same as above if no replacements are suggested (or we can default to the "Find a replacement" button that searches amo?)
- We could add a "learn more" button or link that jumps out to AMO if the user wants more info? We will need something, but I'm not sure what form that will take yet. Trying to keep this to the bare minimum of controls.

**Comment by andymckay** [comment]
I think we've basically decided that this isn't going to happen now? I think? Closing based on that, but please correct me if I'm wrong.

**Comment by pwalm** [comment]
@andymckay I wish it was happening! But prob not (for now
