### ISSUE TITLE
Subscribe to get a notification when the extension is approved

### ISSUE THREAD

**Issue by Mte90** [mozilla/addons#481]
### Describe the problem and steps to reproduce it:
I am opening tickets to many extension for chrome and asking for a Firefox release. 
I cannot open every day the page on amo for all the extension that I am waiting the approval for install it so I am thinking that add a box to leave the email to get a notification will be interesting to help in that.

### What happened?
Actually if you use add on Firefox of an extension not reviewed you get an error inFirefox because is not signed so you cannot install it.

**Comment by jvillalobos** [comment]
On the current site you can use the RSS feed of the versions page to keep track of changes in an add-on. See, [for example](https://addons.mozilla.org/firefox/addon/adblock-plus/versions/format:rss). I don't think we'll have an equivalent feature in the new AMO design. It's not something I expect a lot of people to need.

**Comment by Mte90** [comment]
Got it https://addons.mozilla.org/en-US/firefox/addon/kde_connect/versions/format:rss
But doesn't contain info about the status of the review so is not possible to know if I can install the extension also if it is on AMO.

**Comment by jvillalobos** [comment]
The review status of an add-on is not considered public information, and it's mostly going away when we move to post review very soon.

**Comment by Mte90** [comment]
Ok so actually there is nothing for that, I will wait like I am doing right now

**Comment by eviljeff** [comment]
@jvillalobos can we wontfix this or is there something you want to happen?

**Comment by Mte90** [comment]
I think that now that the auto approval is available this feature is not required anymore
