### ISSUE TITLE
Install Button

### ISSUE THREAD

**Issue by kingphantom** [mozilla/addons#482]
### Describe the problem and steps to reproduce it: 

Add-ons bug. Minor. Installing any add-on will form this bug. Firefox dev 56 64 bit.
(Please include as many details as possible.)

### What happened? 

After installing an add-on, the install button remains to install over and over. 

### What did you expect to happen? 

Expected the install button to no longer function after add-on was installed.

### Anything else we should know?

Tested this on other add-ons. All gave same result.
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
This is by design in the current front-end. However, the new frontend (click "view mobile site" in the footer) does allow for uninstall as well as install and this will supercede the current public pages in November.
