### ISSUE TITLE
Can't add "Release Notes" when submitting updated addons in zh-CN locale

### ISSUE THREAD

**Issue by lilydjwg** [mozilla/addons#483]
### Describe the problem and steps to reproduce it:
I'm uploading a new version of my addon.

### What happened?

![no-textarea](https://user-images.githubusercontent.com/440661/30314155-698526b0-97d2-11e7-932f-f67be98abb8a.png)

### What did you expect to happen?
A Chinese version of this:

![yes-textarea](https://user-images.githubusercontent.com/440661/30314191-8e8dc4b2-97d2-11e7-9138-95f16df217a6.png)

### Anything else we should know?

I'm using Firefox nightly.

**Comment by ValentinaPC** [comment]
Thanks you for reporting!
This was also tracked here: https://github.com/mozilla/addons-server/issues/4599
