### ISSUE TITLE
[Feature request?] Bucket implementation on AMO

### ISSUE THREAD

**Issue by Francoyy** [mozilla/addons#485]
Hi,
I hope this is the right place to ask, please redirect me if not.
On Chrome store, when an extension has a large amount of user (not sure what the number is, at least more than 50k), when pushing an update there is a bucket option.
It is a checkbox allowing the developer to decide to push the update only to X percent of the current users.
Any thoughts on having this feature implemented on AMO?
Thanks!

**Comment by jvillalobos** [comment]
It's been considered, but it's a fairly complex feature to implement and we don't have any immediate plans to do it.
