### ISSUE TITLE
Allow default locale to be set in the AMO profile

### ISSUE THREAD

**Issue by M-Reimer** [mozilla/addons#488]
### Describe the problem and steps to reproduce it:
As my browser sends "de-DE" as the primary language for pages to be displayed, the AMO website presets localization to "Deutsch" (German).
As English is most widely understand, I develop my Addons primary with English texts.
If I freshly open the AMO website, then I'm in the german view and if I log in to publish a new Addon, then all fields are set to german values initially. This often means that I have to delete my Addon again, set the page language to English and republish as it is way more work to switch everything to "default English"

### What happened?
AMO makes it difficult for me (as German native speaker) to have the website open with English language by default.

### What did you expect to happen?
It should be possible to set the preferred language in the profile settings, so every time I log in, the page language is changed to my preset value.

**Comment by jvillalobos** [comment]
You can just go to http://addons.mozilla.org/en-US/ for the English version of the site. It seems like it would be easier to fix this with a bookmark than having to implement a feature that few people will use.

**Comment by M-Reimer** [comment]
I don't use "Bookmarks" at all. I enter the first few characters (in this case "addon") and Firefox directly offers me to "auto-complete" this to be "addons.mozilla.org", so I just press "Enter".

In my opinion the default behaviour for entering "addons.mozilla.org" is broken. It only decides based on the "Accept-Language" header. If I switch to "en-US" manually, then re-entering the addons.mozilla.org site brings me back to the german version. So this manual choice isn't even stored in the session, which is connected to the (already existent) session cookie.

If you really don't want to fix this, please tell me. This problem bugs me that much, that I would create a small Firefox Addon in this case, which spoofs the "Accept-Language" header for just addons.mozilla.org to force my expected default. Including a language selector in the Addon options.

**Comment by eviljeff** [comment]
> If you really don't want to fix this, please tell me. 

We're very unlikely to fix this.
