### ISSUE TITLE
Incorrect application name for AMO in FxA app list

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/addons#489]
### Describe the problem and steps to reproduce it:
1. Sign in to AMO using an FxA
1. Check the FxA Devices & apps list

### What happened?
* AMO is called "Firefox Add-ons Frontend"

### What did you expect to happen?
* AMO called "Firefox Add-ons"

### Anything else we should know?
* https://accounts.firefox.com/settings/clients

**Comment by mstriemer** [comment]
This is specifically if you log in to the mobile site.

**Comment by ryanfeeley** [comment]
@mstriemer Ah ok. I don't remember signing in from mobile, but it's absolutely possible.

**Comment by muffinresearch** [comment]
@mstriemer do you have access to change this? Or can you provide info on where this change needs to be made?

**Comment by mstriemer** [comment]
We likely want to move addons-frontend to use the same FxA config as addons-server.

I think the reason they're using different configs is that it was needed at one point to support the admin site and then the mobile site didn't have a user edit page and users were being dropped onto the desktop site when they registered. Once there's a mobile user edit view we should be able to move the frontend to the regular FxA config.

**Comment by rfk** [comment]
FWIW if you'd prefer both sets of OAuth credentials just say "Firefox Add-ons" it should be pretty trivial for us to make that happen via config change on the FxA side, I don't think there's any requirement that each set of OAuth credentials have a unique display-name or anything like that.

**Comment by muffinresearch** [comment]
@rfk that sounds good. Do you need us to file any issues to make that happen?

**Comment by rfk** [comment]
I filed an ops bug to action the change here: https://bugzilla.mozilla.org/show_bug.cgi?id=1435653

**Comment by rfk** [comment]
This should be updated in prod now, can you please confirm whether it now looks as intended?

**Comment by wagnerand** [comment]
It's called 'Add-ons', which should be good enough.
