### ISSUE TITLE
average_daily_users is always 0 for lightweight themes

### ISSUE THREAD

**Issue by taoaoooo** [mozilla/addons#490]
移动版主题看不到有多少人用，一直显示0。

**Comment by jvillalobos** [comment]
Auto-translation:

> The mobile theme doesn't see how many people are using it, showing 0.

Can you share a screenshot of what you're seeing?

**Comment by yfdyh000** [comment]
https://addons.mozilla.org/en-US/firefox/themes/nature/
![screenshot](https://user-images.githubusercontent.com/1769875/30598831-6e7f928e-9d8d-11e7-9036-147e38260ac3.png)

**Comment by jvillalobos** [comment]
@tofumatt is this a known issue?

**Comment by tofumatt** [comment]
Not a known issue, and it seems that the daily users are shown on the classic site on both the details and search page. So it's possible we're using the wrong value from the API...

**Comment by diox** [comment]
Looks like for themes `average_daily_users` is wrong (always 0) and `weekly_downloads` is right. It makes sense, we have no way of knowing the actual number of users for a Persona once it's installed (since there is no identifier, no updates etc).

The API should hide this implementation detail from you, IMHO, and return the `weekly_downloads` value for `average_daily_users` in the case of lightweight themes.

**Comment by tofumatt** [comment]
> The API should hide this implementation detail from you, IMHO, and return the weekly_downloads value for average_daily_users in the case of lightweight themes.

👍 Works for me! 😄

**Comment by taoaoooo** [comment]
我现在在学编程，很遗憾英语不好，喜欢用firefox浏览器，做了几个简单的主题发现了这个问题。你的回信用有道翻译看了下，很专业😂，幸苦了😘

	Ps：可能你会用google翻译，希望不要翻的太烂：（

发送自 Windows 10 版邮件应用

发件人: tofumatt ☕️
发送时间: 2017年9月20日 6:56
收件人: mozilla/addons
抄送: taoaoooo; Author
主题: Re: [mozilla/addons] 移动版附加组件主题的用户数看不到 (#490)

The API should hide this implementation detail from you, IMHO, and return the weekly_downloads value for average_daily_users in the case of lightweight themes.
👍 Works for me! 😄

**Comment by tofumatt** [comment]
非常感谢您告诉我们有关错误！ 我们正在努力解决它。 不要担心你的英语; 我们不擅长说中文！ 好的东西Google翻译在这里帮助我们大家！😅

**Comment by diox** [comment]
It will be fixed in next week's push (we'll need a reindex)
