### ISSUE TITLE
Feature request: pls support HTML <pre> tag in Add-on Details section

### ISSUE THREAD

**Issue by odebroqueville** [mozilla/addons#491]
### Describe the problem and steps to reproduce it:
I wrapped the JSON data in the Add-on Details section between \<pre> and \</pre> HTML tags, but they just appeared as plain text and didn't have any action on the way the JSON data was presented.

### What happened?
The original white spaces of the JSON data were not preserved. The white spaces on the left were collapsed, pushing all the data against the left border of the window.

### What did you expect to happen?
I wanted to use the \<pre> HTML element in the add-on details for the extension Context Search to preserve the white spaces when publishing JSON data so that it would look nice.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Here is the link where the "Add-on Details" section (3rd section) may be found:
https://addons.mozilla.org/en-GB/developers/addon/contextual-search/edit

And this is what the JSON data looks like:
![screenshot 2017-09-20 at 18 01 39 pm](https://user-images.githubusercontent.com/4818315/30654372-f35407f6-9e2d-11e7-8e82-24cb0ee66f76.jpg)

**Comment by muffinresearch** [comment]
@jvillalobos What do you think? I suppose the only issue might be if we have `pre` then the next logical move would be a request to have syntax high-lighting.

**Comment by jvillalobos** [comment]
I'd say this falls on the same bucket as #460. I wouldn't be opposed to accepting a PR for this one, given that it has a clear scope and looks very useful, though.
