### ISSUE TITLE
Rejection canned responses doesn't show on "Reject Multiple Versions" actions.

### ISSUE THREAD

**Issue by spoji** [mozilla/addons#494]
### Describe the problem and steps to reproduce it:
Using a reviewer account with access to the "Auto-Approved Addons" queue :

1 - Go to any add-on review page, such as https://addons.mozilla.org/en-US/editors/review/reddit-enhancement-suite .

2 - Click on "Reject Multiple Versions".

3 - Try inserting a canned response from the drop-down list.

### What happened?
The "Reviewer reply" canned responses are shown, grayed out.

### What did you expect to happen?
The "Reject reply" canned responses should be shown and selectable by the reviewer.

### Anything else we should know?
Reproducible on Firefox 55 and Chrome 60. 

I have been told that @jvillalobos should take care of this :)

Here is a screenshot of the issue : https://imgur.com/a/ltbxt

**Comment by diox** [comment]
Yeah, the canned response field shows all responses for all available actions. It just so happens that in prod, there are canned responses available for the reviewer reply action, but not multiple versions rejection.

@jvillalobos can alter the sort group of existing canned responses to make them available for that action, or create new ones specific to the action. The sort group to use is `reject_multiple_versions`.

**Comment by jvillalobos** [comment]
Forwarding to @wagnerand, since this depends on policy decisions and he already has access.

**Comment by wagnerand** [comment]
I made some canned responses available when rejecting multiple versions. Note that we will revise all canned responses shortly as part of the new review policies.

**Comment by ValentinaPC** [comment]
@wagnerand : I cannot see any canned responses available from Reject Multiple Versions tab while checking on AMO-dev FF56(Win 7).
Please see screenshot:
![rej](https://user-images.githubusercontent.com/15685960/31601110-59a3bc30-b261-11e7-89f9-60b9943dee50.png)

**Comment by wagnerand** [comment]
@ValentinaPC yes, that is expected, I made these changes on prod only. No need to test this on -dev.
