### ISSUE TITLE
Missing a space between 'and' and 'CSS' on Addons Developer page

### ISSUE THREAD

**Issue by SCKelemen** [mozilla/addons#495]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
1) Navigate to https://addons.mozilla.org/en-US/developers/ 
2) Locate the sentence: 
```
"If you know HTML, JavaScript, andCSS, you already have all the necessary skills to make a great add-on."
```
3) Observe '`andCSS`' is not properly spaced. 
4) View Source Code Line 65.
5) Locate:
 ```html
, and<a href="https://developer.mozilla.org/en-US/docs/Web/CSS">CSS</a>,
```
6) Observe improper spacing in HTML.

### What happened?
Improper spacing.

### What did you expect to happen?
Proper spacing. 

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![image](https://user-images.githubusercontent.com/4325375/30818106-a628893e-a1e8-11e7-9337-af06ec528ab0.png)

**Comment by AlexandraMoga** [comment]
verified on AMO-dev in FF55 (Win10)
Postfix screenshot:

![fix_spacing_issue](https://user-images.githubusercontent.com/31961530/30861981-1dced6b8-a2d5-11e7-9b67-6371d04b0c65.png)

**Comment by SCKelemen** [comment]
Thanks!
