### ISSUE TITLE
CSP issue in converting Chrome extension to web extension

### ISSUE THREAD

**Issue by cr-nz** [mozilla/addons#497]
I'm in the middle of trying to convert our Chrome extension to a Web Extension for Firefox. I've almost got it loading in Firefox 56 finally, but I'm getting a CSP error that does not happen when using the extension in Chrome.

I can go to `about:config` and set `security.csp.enable` to `false` and the extension loads just fine. However this is not very secure as all sites would then have the CSP disabled. Also removing the rule from the manifest file means it defaults to stricter settings. I have tried tweaking it somewhat but no luck so far. Perhaps it is a compatibility bug if the rule works fine in Chrome but not in Firefox. I wondering if anyone here has any pointers to resolve the issue or loosen the restrictions some more? Sorry if this is not the right place to ask. 

I am loading the extension via `about:debugging` tab. The error in the console when visiting the extension URL `moz-extension://9273b6c1-d72c-4337-83fd-fe0cec761aaf/mega/secure.html` is:

> Loading failed for the <script> with source “blob:moz-extension://9273b6c1-d72c-4337-83fd-fe0cec761aaf/593d96e9-3fcd-4925-9025-aa07ccfa7728”.  secure.html:1
> 
> Content Security Policy: The page’s settings blocked the loading of a resource at blob:moz-extension://9273b6c1-d72c-4337-83fd-fe0cec761aaf/593d96e9-3fcd-4925-9025-aa07ccfa7728 (“script-src moz-extension://9273b6c1-d72c-4337-83fd-fe0cec761aaf 'unsafe-eval' https://*.mega.co.nz/ https://*.mega.nz/”).

Here's the full manifest.json file:

```
{
    "manifest_version": 2,
    "name": "MEGA",
    "description": "Secure Cloud Storage",
    "version": "3.16.1",
    "content_security_policy": "script-src 'self' 'unsafe-eval' https://*.mega.co.nz/ https://*.mega.nz/; object-src 'self' 'unsafe-eval' https://*.mega.co.nz/;",
    "permissions": ["webRequest", "webRequestBlocking", "https://mega.co.nz/", "https://mega.nz/", "http://mega.co.nz/", "http://mega.nz/", "unlimitedStorage", "clipboardWrite"],
    "web_accessible_resources": ["mega/secure.html"],
    "homepage_url": "https://mega.nz/",
    "background": {
        "scripts": ["mega.js"]
    },
    "icons": {
        "16": "images/icon_16.png",
        "48": "images/icon_48.png",
        "128": "images/icon_128.png"
    },
    "applications": {
        "gecko": {
            "id": "firefox@mega.co.nz"
        }
    }
}
```

If you're curious in testing the extension, the zip file can be downloaded from [here](https://mega.nz/#!XFVURAjJ!8jRnSA7NQgYCcqZ-eQiXvlwzQ773eRICF1ppFI5pvIA).

Many thanks.

**Comment by jvillalobos** [comment]
Please use these channels to get development help: https://developer.mozilla.org/en-US/Add-ons#Contact_us

Thanks.
