### ISSUE TITLE
Add-on page does not load correctly and i cannot download add-ons

### ISSUE THREAD

**Issue by sharkbala** [mozilla/addons#499]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
**This is **EXACTLY HOW THE PAGE DISPLAYS!** in blue text**

 Mozilla

    Register or Log in
    Other Applications
        Thunderbird
        Firefox for Android
        SeaMonkey

Firefox Add-ons

    Extensions
        Featured
        Most Popular
        Top Rated
        Alerts & Updates
        Appearance
        Bookmarks
        Download Management
        Feeds, News & Blogging
        Games & Entertainment
        Language Support
        Photos, Music & Videos
        Privacy & Security
        Search Tools
        Shopping
        Social & Communication
        Tabs
        Web Development
        Other
    Themes
        Most Popular
        Top Rated
        Newest
        Abstract
        Causes
        Fashion
        Film and TV
        Firefox
        Foxkeh
        Holiday
        Music
        Nature
        Other
        Scenery
        Seasonal
        Solid
        Sports
        Websites
    Want more customization? Try Complete Themes
    Collections
        Featured
        Most Followers
        Newest
        Collections I've Made
        Collections I'm Following
        My Favorite Add-ons
    More…
        Add-ons for Mobile
        Dictionaries & Language Packs
        Search Tools
        Developer Hub

    Magic 4 days
    by meriko
    157 Daily Users

gmk
by SERG
160 Daily Users
Tulip Persona
by Sinine
102 Daily Users
Sandylion
by Svaragon
135 Daily Users
Firefox Brushed Metal
by ponchopenguin
241 Daily Users
Owl v5 by CP
by Crazy Psychiatrist®
133 Daily Users
birds on a tree
by mina__chan
139 Daily Users
A koi design
by jyodesigns
154 Daily Users
Autumn Beauty
by SidhePrankster
350 Daily Users
Sparrow and mushrooms on stump
by rositza
290 Daily Users
Foxkeh Dark
by slasher12366
164 Daily Users
The Oregon Coast
by olylady
303 Daily Users
Kimonozero
by johnnyR
139 Daily Users
Summer Storm...animated
by LisaAtTheBeach
276 Daily Users
Cherry Blossom
by BobbyKat LittleCub
263 Daily Users
Themes

Over 300,000 designs to personalize your browser! Move your mouse over a Background Theme to try it on. Start exploring
Want more personalization?

Complete Themes transform the look of your browser with styles for the window frame, address bar, buttons, tabs, and menus. Start exploring
Featured Themes

    Cobalt Abstract
    by AllyM
    1 Daily User

Lever du jour
by Charlotteo_o
3 Daily Users
The Oregon Coast
by olylady
303 Daily Users
Tulip Persona
by Sinine
102 Daily Users
Owl v5 by CP
by Crazy Psychiatrist®
133 Daily Users
Eyes of Black Cat by M♥Donna
by MaDonna
164 Daily Users
Recently Added

    Windows_Theme by M♥Donna
    by MaDonna
    0 Daily Users

Rhapsody of Autumn by M♥Donna
by MaDonna
0 Daily Users
fon49 by levskaya
by levscaya16
0 Daily Users
fon48 by levskaya
by levscaya16
0 Daily Users
Light gray foxx
by Timmy Fox
0 Daily Users
Ella in White Vest
by Alberich Potter
0 Daily Users

View All Recently Added
Most Popular

    Dark Fox
    by randomaster
    247,930 Daily Users

little flowers
by bluszcz
71,964 Daily Users
Three Wolf Moon Shirt
by AurelTristen
53,262 Daily Users
Sunset Over Water by MaDonna
by MaDonna
44,144 Daily Users
Black by MaDonna
by MaDonna
36,195 Daily Users
Japanese Tattoo
by enguyen-1364597692.39
33,768 Daily Users

View All Most Popular
Top Rated

    Theotokos
    by amhalaba
    485 Daily Users

#FirefoxBatik
by Mozilla Indonesia
2,263 Daily Users
Yakuza Paint
by Songbird
13,848 Daily Users
Flag of Indonesia
by Mozilla
444 Daily Users
Eco theme
by McSimych
30,271 Daily Users
peacock tail
by candelora
1,888 Daily Users

View All Top Rated
Themes

    Up & Coming
    Most Popular
    Top Rated
    Recently Added

Categories

    Abstract
    Causes
    Fashion
    Film and TV
    Firefox
    Foxkeh
    Holiday
    Music
    Nature
    Other
    Scenery
    Seasonal
    Solid
    Sports
    Websites

Create Your Own Theme

Your browser, your style! Dress it up with a design of your own!

Submit a New Theme

Learn more

To create your own collections, you must have a Mozilla Add-ons account.

Create an Add-ons Account

or log in to your current account
Footer logo

    get to know add-ons
    About
    Blog
    Developer Hub
    FAQ
    Forum

    Firefox
    Download Firefox
    Android Browser
    iOS Browser
    Focus Browser
    Desktop Browser
    Beta, Nightly, Developer Edition

Other languages

Privacy Policy  |  Legal Notices  |  Report Trademark Abuse  | View Mobile Site  | Site Status  | Report a bug

Except where otherwise noted, content on this site is licensed under the
Creative Commons Attribution Share-Alike License v3.0 or any later version.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
**CONSOLE SHOWS THESE ERRORS:**

Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
Loading failed for the <script> with source “https://addons.cdn.mozilla.net/static/js/preload-min.js?build=4a6c1152-59ce85e2”.  themes:26
Loading failed for the <script> with source “https://addons.cdn.mozilla.net/en-US/firefox/jsi18n.js?b=4a6c1152-59ce85e2”.  themes:1324
Loading failed for the <script> with source “https://addons.cdn.mozilla.net/static/js/common-min.js?build=4a6c1152-59ce85e2”.  themes:1325
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
**Trying to download an add-on - I get server error:**
 Password Exporter 1.3.4
by Justin Scott (fligtar), Jorge Villalobos

This extension allows you to export your saved passwords and disabled login hosts using XML or CSV files that can be imported later.

Download Now Download Anywa
 **result:**
Server not found

Firefox can’t find the server at addons.cdn.mozilla.net.

    Check the address for typing errors such as ww.example.com instead of www.example.com
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Pages do display correctly in IE  and TOR**

**Comment by jvillalobos** [comment]
Sounds like your CSS / JS is being blocked from loading. Which version of Firefox are you using? Do you have any add-ons installed and have you tried disabling them? Can you include a screenshot of what you see?

**Comment by muffinresearch** [comment]
@sharkbala Closing for now since there's no additional info. If you have more information to add please feel free to re-open.
