### ISSUE TITLE
define simple add-on install flow

### ISSUE THREAD

**Issue by designakt** [mozilla/addons#50]
with the new add-on discovery we will introduce a one click install for add-ons that will also show the install-state of the add-on.
For that we will define all states of install and uninstall, confirmation, errors, and possible other edge cases.

**Comment by designakt** [comment]
How should it behave if multiple add-ons are turned on in quick succession?
Should we stack confirmations, or wait with fully activating the next until one confirmation is dismissed?

**Comment by pwalm** [comment]
If turned on in quick succession, the notifications for the toolbar should queue. Nothing should disappear or be overridden.
@muffinresearch @mstriemer Do the add-on installs queue up? Like, if i turn on two switches in quick succession, does the second switch stay in "progress" mode while the first downloads and installs?
