### ISSUE TITLE
Confusing Ukrainian translation of firefox57 tag

### ISSUE THREAD

**Issue by paiv** [mozilla/addons#500]
The tag `Compatible with Firefox 57+` is currently translated to Ukrainian as

    Сумісно починаючи з Firefox 57

Which could be read as

    Compatible starting from Firefox 57

(meaning that it cannot be installed on versions below 57)

Better translation would be just

    Сумісно з Firefox 57+

And for the tooltip

    Цей додаток створений за новими технологіями, сумісними з Firefox версії 57 і вище

As seen on https://addons.mozilla.org/uk/firefox/addon/adblock-for-firefox/

<img width="1010" alt="ff57" src="https://user-images.githubusercontent.com/196601/31056288-ea423e64-a6d7-11e7-9a17-f7e6f1aab842.png">

**Comment by muffinresearch** [comment]
The new frontend supercedes the old UI. On the basis that it's unlikely this will get fixed in the old UI I'm going to mark this as wontfix.
