### ISSUE TITLE
Blur UI Icons

### ISSUE THREAD

**Issue by Ak29shay** [mozilla/addons#503]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
Some icons in firefox is blur.
### What did you expect to happen?
It can be improve with sharp & fine edges.
![mozilla](https://user-images.githubusercontent.com/32372218/31158449-7ee18288-a8df-11e7-8b72-173055b0edc7.jpg)
![mozilla](https://user-images.githubusercontent.com/32372218/31158482-b6f8e1ac-a8df-11e7-9b91-89fa62eb5786.jpg)

I can give psd source files as a proof.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Ak29shay** [comment]
[mozilla.zip](https://github.com/mozilla/addons/files/1354526/mozilla.zip)

**Comment by Ak29shay** [comment]
You can see the source file in zip folder for proof.

**Comment by tofumatt** [comment]
We’ve replaced this page with a new front-end going live within a month, so this will get fixed by it launching. Gonna close this as we won’t have time to work on it before the new site replaces it.
