### ISSUE TITLE
Version for Fx57 and later is delivered to Fx56 (and cannot downgrade to older version)

### ISSUE THREAD

**Issue by piroor** [mozilla/addons#504]
### Describe the problem and steps to reproduce it:

After I uploaded my addon Tree Style Tab (aka TST) to an WebExtensions-based version 2.0.2 marked as `minVersion="57.0a1"`, it is unexpectedly delivered to people who don't use Fx57 but using Fx56 and older versions.
Moreover, after TST is updated to 2.0.2 (it is disabled due to incompatible Firefox version), I cannot downgrade it to a legacy version anymore from AMO because Firefox reports that the version 0.19.x is incompatible for the current Firefox version.

Steps to reproduce:

 1. (In past days) start Firefox 56 or older version. I saw this problem on Firefox 55 unbranded version (for addon developers) on Ubuntu.
 2. (In past days) go to about:config and set these prefs: xpinstall.signatures.required=false
 3. (In past days) install Tree Style Tab addon 0.19.2017090601. from its [version list](https://addons.mozilla.org/ja/firefox/addon/tree-style-tab/versions/).
 4. Wait for background update of addons.
 5. Restart Firefox.
 6. TST has been updated to the version 2.0.2 unexpectedly, and it is disabled by Firefox.
 7. Try to downgrade TST to a legacy version, from http://piro.sakura.ne.jp/xil/xpi/nightly/
    (Because I'm using unbranded version Firefox for testing of such development unsigned addons)

### What happened?

Firefox shows a popup with a message that the addon is incompatible with the current Firefox version.

### What did you expect to happen?

Firefox starts to install the old version of the addon.

### Anything else we should know?

Important points:

 * TST 2.0.2 is marked as "minVersion=57.0a", but updated in the background.
 * TST 0.19.2017090601 is marked as "maxVersion=56.*", but blocked to install after this problem happens.

Very oddly, I cannot reproduce this problem anymore for now.
So I've just described what was happened.

This problem is also reported at TST's issue tracker.
https://github.com/piroor/treestyletab/issues/1423

**Comment by diox** [comment]
This is worrying, but I can't reproduce step 6: even when forcing updates check, I'm still not presented with the upgrade to 2.0 or higher on Firefox 56.

**Comment by diox** [comment]
In https://github.com/piroor/treestyletab/issues/1423#issuecomment-334548847 @piroor mentions that he had `extensions.checkCompatibility` set to `false`, which *will* definitely cause AMO to send updates ignoring version compatibility.

@ned-martin's problem might be the same thing, depending on what was set on that profile originally. I don't think this can be caused by an upgrade to a different profile though, as profiles in Firefox are completely separated and don't interact with each other.

**Comment by piroor** [comment]
Finally I've found that my private auto-building system is broken and I unintentionally provided wrong update info on my website. I'm very sorry. I close this issue as invalid.
