### ISSUE TITLE
Legacy extensions with extended compatibility can not longer be installed after WE version is submitted

### ISSUE THREAD

**Issue by nico-nc** [mozilla/addons#506]
### Describe the problem and steps to reproduce it:
1. Install Firefox ESR (45.9.0 or 52.4.0)
2. Go to https://addons.mozilla.org/fr/firefox/addon/page-hacker/versions/
3. Click on the button to install version 1.2.1 (legacy extension, marked as compatible with Firefox 3.0 - 52.*)

### What happened?
4. Firefox gives the following error message: "Page Hacker could not be installed because it is not compatible with Firefox 45.9.0"

### What did you expect to happen?
4. The extension should install correctly, as it previously did.

### Anything else we should know?
This version of the extension was initially submitted on AMO as compatible with Firefox 3.0-3.1, and the compatibility was then "bumped" through AMO interface that changes the update.rdf file checked by Firefox.
Apparently, since a WebExtension version of the extension was uploaded (3.0), the check through the update.rdf file no longer works. Here is what I have in the console with extension.logging enabled:

```1507468668058	addons.xpi	DEBUG	Download started for https://addons.mozilla.org/firefox/downloads/file/40010/page_hacker-1.2-fx.xpi?src=version-history to file C:\Users\NTURCOT\AppData\Local\Temp\tmp-khn.xpi
1507468668066	addons.xpi	DEBUG	Download of https://addons.mozilla.org/firefox/downloads/file/40010/page_hacker-1.2-fx.xpi?src=version-history completed.
1507468668115	addons.update-checker	DEBUG	Requesting https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=pagehacker-nico@nc&version=1.2.1-signed.1-signed&maxAppVersion=3.1b2pre&status=userEnabled,incompatible&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=45.9.0&appOS=WINNT&appABI=x86-msvc&locale=fr&currentAppVersion=45.9.0&updateType=49&compatMode=normal
1507468668946	addons.update-checker	DEBUG	Found an update entry for pagehacker-nico@nc version 3.0
1507468668949	addons.xpi	DEBUG	Cancelling download of https://addons.mozilla.org/firefox/downloads/file/40010/page_hacker-1.2-fx.xpi?src=version-history
1507468668950	addons.xpi	DEBUG	removeTemporaryFile: https://addons.mozilla.org/firefox/downloads/file/40010/page_hacker-1.2-fx.xpi?src=version-history removing temp file C:\Users\NTURCOT\AppData\Local\Temp\tmp-khn.xpi
```

This compatibility should be ensured at least for the users of Firefox ESR versions.

**Comment by jvillalobos** [comment]
I can reproduce the issue. It could be related to #6425.

It's an odd case that I'm not sure we should cover, because there are two more recent versions: 3.0, compatible with ESR, and 3.1, not compatible with ESR. ESR users can install 3.0 instead of 1.2.1 (without any errors), or will get automatically updated to 3.0 unless they disable automatic updates.

**Comment by jvillalobos** [comment]
Legacy extensions are no longer supported.
