### ISSUE TITLE
AMO permissions don't show content scripts

### ISSUE THREAD

**Issue by aswan** [mozilla/addons#507]
### Describe the problem and steps to reproduce it:
When a webextension injects a content script, we display a permission prompt for it just as if the extension had a host/origin permission for whatever pattern of urls the script is injected into.  AMO doesn't though.  As a concrete example, this extension (https://addons.mozilla.org/en-US/firefox/addon/adblocker-tumblr/) injects a content script into *.tumblr.com and the browser shows a permission prompt for it, but there's no "Permissions" link next to the "Add to Firefox" button.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
AMO only lists permissions that are detected on the manifest and are shown on install. I think you're referring to permissions that are requested dynamically, which I'm not sure we want to show on AMO (and would also require to be extracted from the add-on code, which is difficult and wouldn't work reliably).

**Comment by aswan** [comment]
No, I'm talking about content scripts that are declared in the manifest.  Again, the browser prompts at install time for these, if the intention of the "Permissions" link is to match what the browser shows, then AMO should show these too.

**Comment by ValentinaPC** [comment]
@aswan : I've downloaded the extension you used above and I was not able to reproduce the issue - https://addons-dev.allizom.org/en-US/firefox/addon/adblocker-teeesting/

I've made the submission in both -dev |and -prod and each time the link to permissions was listed.
Used FF56 and FF58 under Windows 7.

Do you recall doing some extra things, at submission, to this extension?

**Comment by aswan** [comment]
I can't install the extension from the previous comment since it isn't signed and it doesn't include an id.  I'm also not very familiar with the layout of the new front end.  But I outlined the problem in the original bug report, there's no need to submit a new extension to reproduce it.

**Comment by diox** [comment]
It does make sense to submit a new extension to reproduce it, because it proves it's actually working... for new submissions. When we originally implemented the permission list and backfilled permissions data from existing add-ons we did not parse the hosts. It was implemented shortly after in https://github.com/mozilla/addons-server/issues/4916 but I guess when we re-ran the script we didn't overwrite existing data. @eviljeff might know more about this.

**Comment by eviljeff** [comment]
I looked back at https://public.etherpad-mozilla.org/p/amo-2017.04.06 and there was certainly the _intention_ to overwrite the existing data (`--force`).  We could run it again - it should be harmless - but it doesn't help explain _why_ we don't have the host permission.

**Comment by eviljeff** [comment]
fwiw, the permissions link isn't on the front-end anyway - it was [dropped from the MVP](https://github.com/mozilla/addons-frontend/issues/2757)

**Comment by muffinresearch** [comment]
> fwiw, the permissions link isn't on the new front-end anyway - it was dropped from the MVP

Correct, it's not yet on the new frontend. It will be added post-release. 

In the meantime it would be good to try and understand if this is just a data issue or there's a bug in how the permissions are retrieved and displayed.

**Comment by aswan** [comment]
lack of activity has not magically fixed this or made it irrelevant...

**Comment by eviljeff** [comment]
> lack of activity has not magically fixed this or made it irrelevant...

True, though keeping it open doesn't magically fix it, or make it less stale either.
