### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by luizperes** [mozilla/addons#509]
[linguist-unknown-v0.7.1-firefox.zip](https://github.com/mozilla/addons/files/1403896/linguist-unknown-v0.7.1-firefox.zip)

I have had problems on the validation of my __new__ addon __Linguist Unknown__. I attached the source code for review, and it keeps throwing me an annoying error: 
![screenshot_addon](https://user-images.githubusercontent.com/6173065/31849644-3f2135e4-b5fa-11e7-93c6-dd80e1888ab3.png)

Not sure about what that is... that works pretty fine on my Firefox local `56.0` on Elementary OS.

The url I used was [this one](https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed) and I submitted around 1am (Pacific Time)

_Extra detais:_
This [`extension`](https://chrome.google.com/webstore/detail/linguist-unknown/oohlobhfikieeeldgalkkkaojcaebclk) has been on `Google Chrome` for around one year and it is completely open source. You can find the code for the `firefox` branch [here](https://github.com/github-aux/linguist-unknown/tree/firefox)

Thanks!

**Comment by jvillalobos** [comment]
I can confirm this in the [standalone validator page](https://addons.mozilla.org/developers/addon/validate). @luizperes are the entire contents of the zip file necessary for the add-on to function? You mentioned this is the source code, so I wanted to make sure this is the final package you intend to distribute. If there's anything you can cut down from the file, the error might go away.

**Comment by luizperes** [comment]
Yes, this is indeed my final build for my version `v0.7.1`. There are some files I can cut down, I will try to do it and will post here the resolution, thanks @jvillalobos !

**Comment by muffinresearch** [comment]
@luizperes I'm going to close this issue since we haven't heard back from you. Please do reopen it if you're still having issues.

**Comment by luizperes** [comment]
Hi @muffinresearch, yeah, I haven't had the time to retry it yet. In case that it fails when I do, I will reopen this thread and give more info, thanks!
