### ISSUE TITLE
Download of addons impossible, I should download FF first

### ISSUE THREAD

**Issue by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [mozilla/addons#511]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
If I want to download an addon, I can just see the big button to download FF first.

### What happened?
No download link for the desired addon appears

### What did you expect to happen?
I want a download link

### Anything else we should know?
FF V.57.0b7 (64-Bit) on W7_64_Prof

(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/de/firefox/collections/mozilla/featured-add-ons/?src=find-replacement&page=3
I have a screenshot, but I get an error message when I attach it. Please provide a working method. That is probably the next issue. (Sonething went really wrong and we can*t process that file)

**Comment by diox** [comment]
If you see a message saying to download Firefox, and you're already using Firefox, it's probably that the user-agent you're exposing to AMO is not the original one.

A screenshot would really help... Can you upload one anywhere and paste a link here?

**Comment by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [comment]
Thanks for the quick answer. Here is the link to the uploaded screenshot.
https://mega.nz/#!EtdXHagR!3g6c3iTi8-WFapi12J2EMvWpm3JwiOZz1Ta2Z-DMba8

**Comment by diox** [comment]
Did you change your user-agent?

**Comment by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [comment]
Where could I have done it?

**Comment by diox** [comment]
Through an add-on that does it or by changing some `about:config` preference like `general.useragent.override`. Does it happen with a fresh Firefox profile?

**Comment by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [comment]
I'll test it in 30 minutes

**Comment by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [comment]
A clean profile works. It is not worth finding out where the problem is. Workaround is to start  the clean profile, download the extension, restart the original profile and load it from the file. This only occurs for new extensions/plugins; updates work. Thanks a lot.
