### ISSUE TITLE
A plugin's rating is not updated after deleting a user's rating

### ISSUE THREAD

**Issue by arnolem** [mozilla/addons#513]
### Describe the problem and steps to reproduce it:
1-Rate a tools (1/5)
2-Delete your rating
3-The plugin rating remains at 1/5

### Anything else we should know?
Eg: https://addons.mozilla.org/en-US/firefox/addon/nyan-cat-cursor/

![image](https://user-images.githubusercontent.com/2263103/32123586-2773a024-bb65-11e7-9d3d-0fe97d85a0f0.png)
![image](https://user-images.githubusercontent.com/2263103/32123589-2e1b1bf0-bb65-11e7-951a-74ac4f2c159a.png)

**Comment by muffinresearch** [comment]
@diox do we have this covered by any other existing issues? This seems similar to https://github.com/mozilla/addons-server/issues/1618 which is closed.

**Comment by diox** [comment]
It's actually another instance of https://github.com/mozilla/addons-server/issues/5999 ; mozilla/addons-server#1618 was fixed some time ago and the signal that triggers the task is correctly sent when a rating is deleted, it's just that the task fires too early. The fix we're deploying for the indexing issues as part of #5999 should also fix this.

**Comment by diox** [comment]
Closing as duplicate since #5999 tracks these kind of issues.
