### ISSUE TITLE
"New Look" add-ons site not catering to older Firefox versions

### ISSUE THREAD

**Issue by wolfbeast** [mozilla/addons#514]
### Describe the problem and steps to reproduce it:
The layout of the new look is broken on older Firefox versions. This is a problem because AMO should be catering to older versions of Firefox (it lists extensions for them).

1. Visit addons.mozilla.org with an older version of Firefox (<52).
2. When offered, select the "new look" link to switch to the new design

### What happened?
The "new look" lists everything vertically, as if it was made for a mobile phone.

### What did you expect to happen?
I expected the site to be properly laid-out as seen on Firefox 52 and above

### Anything else we should know?
The issue seems to be that your new layout uses CSS Grid. This isn't supported on older Firefox versions and as such breaks the layout. Because you offer extensions to older versions of the browser, the site should be usable by older browsers. This was never a problem before this "new look" design came around, even with the many revamps done.

Screenshot included FF51 left, FF52 right.
![a6cf2576-8c81-498c-8da6-728bc27382de](https://user-images.githubusercontent.com/3359132/32138581-34ae1dfc-bc35-11e7-8f8c-dc0e225b8686.jpg)

Full page capture in "bad" mode:
![fireshot pro screen capture 170 - add-ons for firefox - addons_mozilla_org_en-us_firefox](https://user-images.githubusercontent.com/3359132/32138593-742cac50-bc35-11e7-9972-7c9757621c48.png)

**Comment by tofumatt** [comment]
Our minimum supported version of Firefox is Firefox ESR, so in this case 52. We actually used css grids for desktop views and layout because the fallback of mobile view is still entirely usable for users of older browsers. We don’t have the resources to build a site with this layout that works with browser verioms older than ESR.

**Comment by wolfbeast** [comment]
Thanks for replying. I'll relay that "you don't have the resources".

**Comment by mattatobin** [comment]
Wow.. Can't support a tiny bit of feature detection and a minor bit of css override tweaking..

I searched and replaced `display: grid;` with `display: flex` and it is already quite a bit closer to the intended design on browsers that don't support grid.

So you can take my five seconds add about 20 minutes and have your self a working fallback..

![untitled](https://user-images.githubusercontent.com/3889475/32143271-3bbbbf58-bc7d-11e7-90cb-aaf6751d6a19.png)

But then again.. Why bother right? Not like there will be many add-ons left to browse for in the near future right?

**Comment by wolfbeast** [comment]
Put `@supports` to use to detect grid support, and fall back to flex. Really, it's not that difficult and won't take many "resources" to do this kind of design. Maybe it'll actually help retain a few more users.
