### ISSUE TITLE
Redundant (?) German Dictionaries on: https://addons.mozilla.org/en-US/firefox/language-tools/

### ISSUE THREAD

**Issue by nspiller** [mozilla/addons#515]
On [this website](https://addons.mozilla.org/en-US/firefox/language-tools/) you can browse the dictionaries and language packages for Firefox. For German there are three options:

- (neue Rechtschreibung)
- ((neue Rechtschreibung))
- (alte Rechtschreibung)

While the difference between _alte_ and _neue_ should be clear most, there is no information about the difference between the two _neue Rechtschreibung_. Why are there two options? This should be explained.

[This site](https://developer.mozilla.org/en-US/Add-ons#Contact_us) encouraged to file a bug report here for topics regarding [https://addons.mozilla.org/](https://addons.mozilla.org/)

**Comment by EnTeQuAk** [comment]
cc @wagnerand who might have a bit more insight here what's going on.

**Comment by wagnerand** [comment]
There are two German dictionaries maintained by two independent developers. Choose whatever you prefer.
