### ISSUE TITLE
thunderbird error 1001X

### ISSUE THREAD

**Issue by 0ebele** [mozilla/addons#519]
![thunderbird error 1001x](https://user-images.githubusercontent.com/33315823/32320942-cd2dda44-bfbf-11e7-81cb-95dd35f98834.jpg)

**Comment by 0ebele** [comment]
This has been going on for months to twice a day

**Comment by jvillalobos** [comment]
You can look for Thunderbird support here: https://support.mozilla.org/en-US/products/thunderbird
