### ISSUE TITLE
consider connecting about:addons with about:preferences

### ISSUE THREAD

**Issue by designakt** [mozilla/addons#52]
see [Android Browser Settings Research & Card Sort](https://docs.google.com/presentation/d/1KMqQJxEKKZC8d1TI6JtxSlTR6e9hJJ2S90dPeg18kLg/edit), [preferences re-org recommendation](https://www.dropbox.com/sh/udpuzw68ysybmve/AACqVD6VwLSS2HrTwWBvcg2Ra/Settings.pdf?dl=0), and other browsers relation of add-ons and preferences.

related: [Naming in Add-ons](https://docs.google.com/document/d/1PZlljYzlE-UvavXiCU3WI77Ofmy6t8T3O95URrsdiy8/edit#heading=h.95ehhf8mwyyp)

related: [integrate simple add-ons manager in about:preferences#addons (bug 1175262)](https://bugzilla.mozilla.org/show_bug.cgi?id=1175262), which was intended to be an experiment.

**Comment by muffinresearch** [comment]
@designakt Does this still need an issue here? I'm thinking this sounds more relevant as a firefox bug or is there action that needs to be taken wrt to AMO?

**Comment by designakt** [comment]
I was under the impression this repo is for anything related to addons.
If this repo is solely for AMO then no, this should not be here; but then we might want to change the description of the repo too.

**Comment by muffinresearch** [comment]
@designakt I'm just going through old issues and trying to make sure what's here is still relevant.  If it is then this can stay.

**Comment by wagnerand** [comment]
Since any potential code changes will land in Firefox (client), and review will go through bugzilla/reviewboard, maybe it makes more sense to move this to bugzilla?

**Comment by designakt** [comment]
I just reviewed this last week too... let me keep it for now as a reminder and I will update or remove when we move forward with it.

**Comment by wagnerand** [comment]
about:addons now has a link to about:preferences and vice-versa.
