### ISSUE TITLE
can't add extension to my collection by 1 click

### ISSUE THREAD

**Issue by f242** [mozilla/addons#520]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I don't see button "**Add to collection**"

### What happened?
1. I copy to clipboard extension name
2. I go to menu by mouse over my nickname in upper right corner
3. I choose View My collections
4. I click edit my collection (pencil icon)
5. I click Add-ons tab
6. In search field i paste extension name from clipboard
7. Find in search results right name and click
8. Press button Add to collection
9. Scroll down and press Save Changes

**9 steps** just for adding to my favourites!
Adding to local favourites in browser is more simple than on site!

### What did you expect to happen?
Just press button "Add to collection" on add-on page
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by yfdyh000** [comment]
Older interface removed: https://github.com/mozilla/addons-server/issues/2264
Response to new interface: https://discourse.mozilla.org/t/no-favorite-button-in-new-amo-design/8015/65

**Comment by muffinresearch** [comment]
FWIW: The full collections feature (including editing) is yet to be re-implemented in the new site and is covered by this tracker bug https://github.com/mozilla/addons-frontend/issues/2782

**Comment by muffinresearch** [comment]
Since the addition of collections is covered in the aforementioned tracker issue I'm closing this. Please follow the progress there. FWIW The collection interface is already in progress.
