### ISSUE TITLE
Description of add-ons doesn't respect new lines

### ISSUE THREAD

**Issue by marcoagpinto** [mozilla/addons#522]
### Describe the problem and steps to reproduce it:
I had the description of my add-on separated in different paragraphs.

### What happened?
The add-ons descriptions now appear all in one paragraph.

### What did you expect to happen?
Different paragraphs if we press RETURN at the end of the lines.

### Anything else we should know?
https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2

**Comment by muffinresearch** [comment]
@marcoagpinto I presume you're describing the summary e.g: 

In the old site you had this:

<img width="1118" alt="british_english_dictionary__marco_pinto_____add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32446573-4193e0ec-c301-11e7-8599-312db00aeba6.png">

And now it looks like this:

<img width="947" alt="british_english_dictionary__marco_pinto__-_add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32446599-58bc7946-c301-11e7-91e3-eeb428f2e397.png">

**Comment by tofumatt** [comment]
We could add these super easily and if that was the old expectation we should keep it. I'm on it.

**Comment by marcoagpinto** [comment]
@muffinresearch 

Yes, that is what I am referring to.

:-)

**Comment by vcarciu** [comment]
Verified as fixed : 
![descriptionoldnew](https://user-images.githubusercontent.com/1583842/32495050-a984b4c6-c3cc-11e7-90eb-80fb4c6d5034.gif)

**Comment by marcoagpinto** [comment]
@vcarciu 

I still see all in the same paragraph:
https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2/

:-(

**Comment by vcarciu** [comment]
@marcoagpinto : this is because the change is not in production yet. You will see the change on Thursday in production. I tested this on -dev.

**Comment by marcoagpinto** [comment]
@vcarciu 

Ahhh... thank you!
