### ISSUE TITLE
Spanish dictionaries not shown on Firefox 56 or higher, but can be installed if the addon page is visited

### ISSUE THREAD

**Issue by RickieES** [mozilla/addons#523]
### Describe the problem and steps to reproduce it:
Visit the Mozilla Add-ons Dictionaries and Language Packs page with Firefox 56 or higher (Desktop or Mobile), or Chrome 62:

https://addons.mozilla.org/en-US/firefox/language-tools/

### What happened?

None of the 5 Spanish dictionaries are listed. Many other languages are also missing (Acholi, Akan, Aragonese, Azerbaijani... just to mention a few of them).

In contrast, visit the same URL with SeaMonkey 2.48 (Gecko 51) or an equivalent version of Firefox or Chrome. More languages are listed, including five Spanish variants of the dictionary.

### What did you expect to happen?

The same languages should be listed regardless of the version of the web rendering / JavaScript engine, unless the addons were not compatible with the browser. If you visit the specific addon page with the browser hiding it, you can however install it without any trouble. For instance:

https://addons.mozilla.org/en-US/firefox/addon/spanish-spain-dictionary/

**Comment by tofumatt** [comment]
Thanks for filing this. We’re relying on our known `languages.json` list of locales for what to display and it looks like some locales aren’t matching up with the keys in that file. I’ll have a look into why that is.

**Comment by gaby2300** [comment]
The same happens with Spanish for Argentina. It can be found visiting the specific addon page, but not in the general dictionaries list. 
For anyone needing it visit: 

https://addons.mozilla.org/es/firefox/addon/diccionario-espa%C3%B1ol-argentina/

**Comment by muffinresearch** [comment]
This is likely related to, or the same issue as #528
