### ISSUE TITLE
Contribute button missing on new AMO design

### ISSUE THREAD

**Issue by Aris-t2** [mozilla/addons#524]
### Describe the problem and steps to reproduce it:
Visit any add-on page that offers a contribute button. Scroll down and chose "View classic desktop site".
Blue Donate button appears again.

### What happened?
No "Contribute" button on new design and the new design is now loaded by default.

### What did you expect to happen?
A "Contribute" button should be somewhere on the page.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Example page:
https://addons.mozilla.org/addon/new-tab-override/

New design misses "Contribute" button
![01](https://user-images.githubusercontent.com/6013569/32414523-5f090748-c229-11e7-98f7-0e8b8be45182.png)

Old design still offers it
![02](https://user-images.githubusercontent.com/6013569/32414528-78f51b38-c229-11e7-9345-da4afd27e77d.png)

**Comment by tofumatt** [comment]
Thanks for filing. We have an issue logged for this already at https://github.com/mozilla/addons-frontend/issues/3149; so I'm closing this as a duplicate but you can follow the feature's development at the issue link I posted 😄
