### ISSUE TITLE
Can't download web-extensions (add-ons) due to a connection failure caused by anti-virus root cert

### ISSUE THREAD

**Issue by K-no-Uta** [mozilla/addons#525]
### What happened?

I tried to download 3 add-ons to try them, but every time a Firefox pop-up window said it couldn't download it due to connection error. My internet is working perfectly though. Here links to two of the ones I tried to get

https://addons.mozilla.org/de/firefox/addon/enable-rightclick-and-copy/
https://addons.mozilla.org/de/firefox/addon/%E5%BF%AB%E4%B9%90%E5%8F%B3%E9%94%AE/

The pages looks entirely different from the last time I visited. So maybe there's an errror due to the change? The extensions also don't look like they should be incompatible. I'm using "Firefox Quantum 57.0b14 (64-Bit)"

I click on the blue button saying "add to firefox" or similar, since my version is in German. And then the pop up appears in the upper left corner saying it cannot connect to addons.mozilla.org

![unbenanntx](https://user-images.githubusercontent.com/33396438/32416486-1fedc014-c24a-11e7-8662-6352f54f1781.JPG)
![unbenanntx2](https://user-images.githubusercontent.com/33396438/32416487-200930d8-c24a-11e7-945d-d67f04efc6f4.JPG)

**Comment by muffinresearch** [comment]
@K-no-Uta I can't reproduce this using the same browser version. What platform are you running on? 

Could you try running the same download from a "Private window" or a new browser profile?

**Comment by K-no-Uta** [comment]
(x_X) Odd, because the problem is still there.

OK I tried:
- Run from private window
- Run with all add-ons disabled
- Restarted browser and computer
- Manually triggerd update of my router just to be sure, because it was cause to some problems before.

Nothing solved the problem.

My browser is unning on Windows 10 Home 64-Bit. I'm doing my best to keep everything updated. Software, pltform and drivers.

**Comment by muffinresearch** [comment]
@ValentinaPC @vcarciu have you seen anything like this running beta under windows?

@K-no-Uta can you see anything in the browser console (Tools -> Web Developer -> Browser console) related to the failed connection or in the devtools network panel (Tools -> Web Developer -> Network)?

**Comment by muffinresearch** [comment]
@K-no-Uta are you running any other software that might intercept/break network connections e.g. antivirus or security software? If so, could you check to see if indicates that the xpi download is being actively blocked?

**Comment by ValentinaPC** [comment]
@muffinresearch 
I've manage to reproduce the issue...I guess. Not sure if is actually an issue.

STR:
1. Load https://addons.mozilla.org/de/firefox/addon/enable-rightclick-and-copy/
2. Right click on the installation button and select "Open Link in new tab" option
3. A message block the user to install/download the extension
![newtab](https://user-images.githubusercontent.com/15685960/32496862-548bb4f4-c3d3-11e7-8cf2-6dbe5691d634.png)

Reproducing in any FF.
Maybe there is a Bugzilla issue for it.

**Comment by rhodwulf** [comment]
I have the same problem with https://addons.mozilla.org/es/firefox/addon/integrated-google-calendar/
![screenshot - 07_11_2017 07_56_23 a m](https://user-images.githubusercontent.com/2490963/32497217-732490ee-c391-11e7-9126-dee66d64bf0e.png)
I can not install any add-on.
I already deactivate my antivirus and the firewall and keeps giving the error.

**Comment by ValentinaPC** [comment]
Maybe adding the site to both exceptions, helps?
![2017-11-07_1601](https://user-images.githubusercontent.com/15685960/32497390-1487d534-c3d5-11e7-8716-cd0fb9ab7184.png)

**Comment by rhodwulf** [comment]
The problem persists even after adding the exceptions.

**Comment by ValentinaPC** [comment]
You may try:
1. Type about:config in your URL Firefox bar
2. Click "I'll be careful i promise"
3. Right click somewhere and choose: New>String and name it: `xpinstall.enabled` and set the value to `true`
4. Restart the browser and try to install the add-on

**Comment by muffinresearch** [comment]
@ValentinaPC I don't think that's the original issue described above. The string in the reporter's screenshot translates to "The add-on failed to download due to a connection failure".

**Comment by muffinresearch** [comment]
@K-no-Uta if you go to the bottom of the page and click "View classic desktop site" 

Here's a screenshot of where to find that link in the de locale:

<img width="1207" alt="enable_right_click_and_copy_ _add-ons_fur_firefox" src="https://user-images.githubusercontent.com/1514/32502534-e910f0a4-c3d2-11e7-9530-8e82d47bd6cb.png">

Does the install work from the old Addons site?

**Comment by rhodwulf** [comment]
Yeah!!! @muffinresearch 

> if you go to the bottom of the page and click "View classic desktop site"
> 
> Here's a screenshot of where to find that link in the de locale:
Thats is the solution !!!!
Thankyou Very Much!!!

**Comment by muffinresearch** [comment]
@rhodwulf can you confirm if the new site continues to give you the same error? I can see that the links are different, but that by itself may not be an issue. Can you also confirm what version and platform you're using?

Unfortunately without further information from someone that was experiencing the original problem it will be difficult to find out where the problem is.

**Comment by K-no-Uta** [comment]
@muffinresearch @ValentinaPC 

The following did NOT work:

- adding to exceptions on Firefox AND Kaspersky anti-virus
- creating the bootlean as described
- Updating firefox. Build-ID: 20171106194249


Switching to the classical page works :D 

I'll be gladly helping to track the issue however, even though I can now download and work extension X'D

I returned to the new add-on page and can confirm that the problem remains!

OK So the Browser Console says:

"1510156312761	addons.xpi	WARN	Download of https://addons.cdn.mozilla.net/user-media/addons/832020/addon-1.1.0-an+fx-windows.xpi?filehash=sha256%3A61bf622b2cac2749de8a43a3fada3597eda7863800fe146e20c04eafa2adacaa failed: [Exception... "Certificate issuer is not built-in."  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 169"  data: no] Stack trace: checkCert()@resource://gre/modules/CertUtils.jsm:169 < onStopRequest()@resource://gre/modules/addons/XPIInstall.jsm:2405"

Network analysis upon re-loading an add-on page:

![network](https://user-images.githubusercontent.com/33396438/32558884-32109d26-c4a6-11e7-984d-c2aa92a4ba2c.JPG)

Network analysis when I click on the buttom in order to install the add-on and it fails:

![network 2](https://user-images.githubusercontent.com/33396438/32559014-74bbceca-c4a6-11e7-95b7-4f151928c7af.JPG)

And here's the interesting analysis of the web-console(?) when I re-load the page:

![web konsole](https://user-images.githubusercontent.com/33396438/32559068-92f26778-c4a6-11e7-9fa6-4636a0a48468.JPG)

This console stays blank when I click on the button to install teh app and the error message appears.

I hope there's something useful in there? :'D Because this is the kind of computing that is beyond me!

**Comment by muffinresearch** [comment]
@K-no-Uta thanks for the details - this error message looks related - I'll see if I can get some input into possible causes for this to be the problem:

```
"1510156312761 addons.xpi WARN Download of https://addons.cdn.mozilla.net/user-media/addons/832020/addon-1.1.0-an+fx-windows.xpi?filehash=sha256%3A61bf622b2cac2749de8a43a3fada3597eda7863800fe146e20c04eafa2adacaa failed: [Exception... "Certificate issuer is not built-in." nsresult: "0x80004004 (NS_ERROR_ABORT)" location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 169" data: no] Stack trace: checkCert()@resource://gre/modules/CertUtils.jsm:169 < onStopRequest()@resource://gre/modules/addons/XPIInstall.jsm:2405"
```

**Comment by muffinresearch** [comment]
@K-no-Uta for changing the browser locale see the Preferences -> General -> Language.

<img width="979" alt="preferences" src="https://user-images.githubusercontent.com/1514/32560607-fa91e692-c4a1-11e7-830c-85193c709627.png">

**Comment by K-no-Uta** [comment]
@muffinresearch OK. Let me know if you find something. 

Regarding the language setting: in the "Preferences -> General -> Language" it just says: "fonts and colors" and then it says "language" but the description says this setting is to change preference for which language to display the websites in. It's not settings for the firefox interface language.

**Comment by muffinresearch** [comment]
> Regarding the language setting: in the "Preferences -> General -> Language" it just says: "fonts and colors" and then it says "language" but the description says this setting is to change preference for which language to display the websites in. It's not settings for the firefox interface language.

Ah, yes you're right. The UI localization requires a langpack install https://addons.mozilla.org/en-US/firefox/language-tools/

**Comment by K-no-Uta** [comment]
@muffinresearch *laughs hard* X'D

![language](https://user-images.githubusercontent.com/33396438/32564915-e3b9be68-c4b5-11e7-8a18-15d5b6c4456d.JPG)

Oops another problem! BUT don't worry about that now. I understood the principle and I don't need to change it right now. I'll just translate things for you if there's any more stuff that I'll pass on to you regarding the extensions issue! ;)

**Comment by muffinresearch** [comment]
@K-no-Uta can you try the following?

1. Go to https://addons.cdn.mozilla.net/user-media/ (it will show 403 Forbidden, but don't worry about that)
2. Click the green padlock in the address bar 
3. Click the Arrow ">"<img width="1220" alt="fullscreen_08_11_2017__17_51" src="https://user-images.githubusercontent.com/1514/32564948-9ba8fea2-c4ad-11e7-866b-697e73a916ab.png">
4. Click more information. This should show the certificate info. <img width="414" alt="fullscreen_08_11_2017__17_53" src="https://user-images.githubusercontent.com/1514/32565032-dbd46cbe-c4ad-11e7-922f-9b07b23e5552.png">
5. That should show something like this: <img width="600" alt="page_info_-_https___addons_cdn_mozilla_net_user-media__and_403_forbidden" src="https://user-images.githubusercontent.com/1514/32565089-fada5092-c4ad-11e7-8f55-77a47c40bb67.png"> you can click view certificate to see more information.

The cert message suggests you might have a different certificate that causes the install to be blocked. Sometimes you can have a certificate that is used to decrypt content on your local machine instead, examples of this would internet security software. If you have something like that it might be a reason for the error.

**Comment by K-no-Uta** [comment]
![certificate 1](https://user-images.githubusercontent.com/33396438/32566543-8b1db7ac-c4b8-11e7-9f37-ee973ec9166d.JPG)

This is what I see.

**Comment by muffinresearch** [comment]
@K-no-Uta OK - looks like Kaspersky AV has installed a Root cert. 

This will be the reason for the cert error. You'll need to look into how to turn that feature of your anti-virus software off to be able to not have it intercepting your browser traffic in that way.

Note: Disabling the anti-virus won't fix it if the certificate is left in place, and you probably don't want to do that in any case.

**Comment by muffinresearch** [comment]
Since there's no action we can take from this side I'm going to close this out.

**Comment by muffinresearch** [comment]
Since there's no action we can take from this side I'm going to close this out.

**Comment by K-no-Uta** [comment]
Hmm, so basically it makes sense to contact Kaspersky team about this. OK. Thank you very much :)

**Comment by kumar303** [comment]
Thanks for the cert information. It looks like the Kaspersky anti-virus software you have installed is causing a connection failure, perhaps because our new site has improved security measures.

This may provide you some clues on how to fix the problem if you wish to keep Kaspersky installed (or if you have no choice to uninstall it on that machine): https://forum.kaspersky.com/index.php?/topic/307761-this-connection-is-untrusted-certificate-error-in-firefox-in-yahoo-and-google/

If you would like to read more about how Kaspersky could be making your web browser less secure then this article points to some specific problems (for example, it could leave you vulnerable to [FREAK attacks](http://www.securityweek.com/freak-vulnerability-exposes-ssltls-security-hole) among others): http://www.securityweek.com/antivirus-software-has-negative-impact-https-security-researcher

**Comment by kumar303** [comment]
Thanks for the cert information. It looks like the Kaspersky anti-virus software you have installed is causing a connection failure, perhaps because our new site has improved security measures.

This may provide you some clues on how to fix the problem if you wish to keep Kaspersky installed (or if you have no choice to uninstall it on that machine): https://forum.kaspersky.com/index.php?/topic/307761-this-connection-is-untrusted-certificate-error-in-firefox-in-yahoo-and-google/

If you would like to read more about how Kaspersky could be making your web browser less secure then this article points to some specific problems (for example, it could leave you vulnerable to [FREAK attacks](http://www.securityweek.com/freak-vulnerability-exposes-ssltls-security-hole) among others): http://www.securityweek.com/antivirus-software-has-negative-impact-https-security-researcher

**Comment by digitalwhiteout** [comment]
@muffinresearch indeed you were right, avast this time. Sorry for the inconvenience.

**Comment by muffinresearch** [comment]
We're going to look at using a JS API for installs to prevent this problem occurring at our end. See https://github.com/mozilla/addons-frontend/issues/3867

**Comment by K-no-Uta** [comment]
@muffinresearch  Awesome! Apparently I had wanted to send you this message but the topic had already been closed XD

=================
@muffinresearch Hey there. I tried something. I removed all Kaspersky Certificates from my PC and firefoy and the issue was not resolved.  

I found this. The error message is comparable

https://forum.palemoon.org/viewtopic.php?t=8897

![cache](https://user-images.githubusercontent.com/33396438/32580036-c9ff3984-c4e3-11e7-95d8-1128706c4c70.JPG)

So I tried something. I emptied my cache. And then tried to get the add-on again. The add-on started downloading (which it didn't before) and then failed in the middle of it. 

After that I also found this:
https://support.mozilla.org/vi/questions/1183083

Maybe this information helps you a little and maybe other users add other information, too. If I find out anything else I'll let you know.
==========================

I'm currently in touch with the Kaspersky Support. Is there anything that I could ask them that would help you? On the other hand I am confused that the problem remained even after I had removed all Kaspersky root certificates. (x_X)

I tried looking through what's written in the other topic. It's so technical and I fear I don't understand it well. I am just a normal self-taught user, you see? 

So, if there's anything I can do (e.g. test or discuss with/ask Kaspersky staff), please let me know! Please with pictures and detailed instructions. :'D Let me know if I should move to the other topic, too. Thank you.

**Comment by muffinresearch** [comment]
@K-no-Uta the good news is the patch we have in the works looks to resolve the problem from our end. This will mean that users that want to use Anti-Virus software which needs to install such a certificate will no longer be impacted once we get this patch into production. 

We're looking to get this patch out onto the site as soon as possible, that will either be today (Friday) or Monday assuming the testing goes to plan and we are good to move forward with ops and QA support.

**Comment by K-no-Uta** [comment]
@muffinresearch :D Sounds awesome. I'll make sure to stay up to date until I can report this issue as closed by testing it over here, too :3 Thank you very much for sticking to it!

**Comment by muffinresearch** [comment]
@K-no-Uta the fix is live in production now - please give it a test and let us know how it goes.

**Comment by K-no-Uta** [comment]
@muffinresearch IT WOOORKS!!! \(^0^)/ Thank you very much! Good job!

**Comment by qality** [comment]
Same problem.

`Download failed. Please check your connection.` on every download.

**Comment by grahamperrin** [comment]
@qality consider recent #851

**Comment by EdibleScrunchie** [comment]
> 
> 
> You may try:
> 
>     1. Type about:config in your URL Firefox bar
> 
>     2. Click "I'll be careful I promise"
> 
>     3. Right click somewhere and choose: New>Boolean and name it: `xpinstall.enabled` and set the value to `true`
> 
>     4. Restart the browser and try to install the add-on

This worked like a charm for me thank you!
