### ISSUE TITLE
Unlisted developer cannot reply to add-on reviews

### ISSUE THREAD

**Issue by ghostwords** [mozilla/addons#526]
As a Privacy Badger developer (unlisted), I used to be able to reply to Privacy Badger's reviews, but I don't see a way to reply, only flag, in the new AMO design. Screenshot follows:

![screenshot from 2017-11-05 15 40 20](https://user-images.githubusercontent.com/794578/32418904-a7c32c28-c23f-11e7-9381-5bf3ebe9c6bf.png)

**Comment by diox** [comment]
It's possible they are not a "listed" author - the fact that they are an author is not divulged on the detail page etc, so the add-on detail API `authors` property won't contain that user, but they should still be able to post a reply.

**Comment by ghostwords** [comment]
That's probably it. To be clear, I was able to reply using the same account in the previous version of AMO.

**Comment by kumar303** [comment]
@diox is it possible to find out if a user has this permission through the API? Should I file an issue to expose that?

The Django site was doing it like this https://github.com/mozilla/addons-server/blob/c0d8e97cb7251d0702c0b8b4c18a5e9d9127680a/src/olympia/reviews/views.py#L82-L83

btw, I filed https://github.com/mozilla/addons-frontend/issues/3829 because we have the same problem for admins.

**Comment by diox** [comment]
Please file an issue. The main problem is going to be figuring out which API should return that info, IMHO.

**Comment by kumar303** [comment]
Issue for accessing this info in the API: https://github.com/mozilla/addons-server/issues/6863

**Comment by kumar303** [comment]
@ghostwords if you need a quick fix for this you could ask the add-on owner to sign into the [Developer Hub](https://addons.mozilla.org/en-US/developers/) and make you a listed developer.

**Comment by high666** [comment]
The modification of this policy to make the unlisted developers not touching the add-on reviews section is quite appreciable. Wonderful really that the changes are made in GitHub for the overall good. I have been using GitHub for 2 years now but after 2016 I was unavailable as I was working on my own website [Avast Customer Support](https://antivirussupports.info/avast-customer-supports/) which is currently in moderation with Avast's official website of support. It's great to back now. Cheers!

**Comment by kumar303** [comment]
We're bumping the priority on this because it's easier to run into now. See https://github.com/mozilla/addons-frontend/issues/6475

**Comment by diox** [comment]
API side has been implemented https://github.com/mozilla/addons-server/issues/9573

**Comment by kumar303** [comment]
This change will be available on the production site this Thursday after 10am Pacific Time.
