### ISSUE TITLE
No "Download Anyway" button on new AMO's addon description page

### ISSUE THREAD

**Issue by UserNaem** [mozilla/addons#527]
### Describe the problem and steps to reproduce it:
The only way to get to this button now is to view version history.
### What happened?
![image](https://user-images.githubusercontent.com/21028464/32423267-3c6bac6a-c2c7-11e7-8b69-77b83d06e8ea.png)
### What did you expect to happen?
![image](https://user-images.githubusercontent.com/21028464/32423288-6294becc-c2c7-11e7-84d7-d8b9d5f8499a.png)
### Anything else we should know?
Addon page: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

**Comment by rctgamer3** [comment]
Still works. Just right-click the grey button -> Copy Link Location. However, Firefox 51 and older versions are unsupported.

**Comment by tofumatt** [comment]
Because ESR users can still right click on the link to get the XPI I’m closing this as I think there’s still access to the XPI; I don’t think we need the extra link as before.

**Comment by UserNaem** [comment]
Having to right-click and click "Copy Link Location" is inconvenient and it's not apparent that this is even possible, normally you'd expect "blocked" controls to do nothing at all. The only semi-intuitive way to get the extension would be to open its version history (which is somewhat harder to find now that it's hidden among user-irrelevant links like homepage\legal\stats).

I think it should be explicitly pointed out that downloading the extension is still possible, right now it appears as if it wasn't.
