### ISSUE TITLE
Incorrect version detection when privacy.resistFingerprinting is set to TRUE

### ISSUE THREAD

**Issue by physkets** [mozilla/addons#529]
When I set the config: **privacy.resistFingerprinting** to _true_, the add-ons page thinks I'm using FF 50.0 and prevents me from installing otherwise compatible add-ons.

My current work-around is to set it to false, install add-on, and toggle it back to true.

**Comment by wagnerand** [comment]
This is by design. Setting that pref will change your user-agent, which AMO uses to determine whether an add-on is compatible to your Firefox or not.

**Comment by physkets** [comment]
@wagnerand I understand that; But what I'm saying, is that the add-on web-page can display a warning, but still allow one to download & install the extension. i.e., not grey-out the "+ Add to Firefox" button.
