### ISSUE TITLE
Mobile/tablet view?

### ISSUE THREAD

**Issue by Ferenn** [mozilla/addons#530]
### Describe the problem and steps to reproduce it:
It seems the addons website has changed to be a mobile/tablet view.
Visiting addons.mozilla.org displays some kind of strange layout with large boxes (and hardly any content) that looks to be purely catered to touch screens. In addition it has a link to the "classic desktop site" at the bottom, so I'm assuming this is a mobile view of sorts and not the intended site layout for desktop visitors.

### What happened?

I got presented with an unusable site layout

### What did you expect to happen?

I expected a desktop-friendly layout.

### Anything else we should know?

Even if I were to visit this on mobile, I'm missing things: I can't find anything I want anymore on the new site's layout. Where are the categories? What's with these huge boxes at the top? Why are all types of "themes" indicated with a blank green block?

**Comment by jvillalobos** [comment]
The site was recently redesigned: https://blog.mozilla.org/addons/2017/10/25/test-new-look-addons-mozilla-org/

The design you're currently looking at is intended for desktop, but also works on mobile devices when scaled down.

**Comment by Ferenn** [comment]
Really...? This is by design? 😡 🗯 
I don't see how this is in any way a desktop design. Please fire whomever came up with this.
