### ISSUE TITLE
Reviews that contain no text are hidden from listing page

### ISSUE THREAD

**Issue by Hainish** [mozilla/addons#531]
I'm the maintainer of HTTPS Everywhere.  I've noticed that we've been getting a number of reviews lately which aren't showing up on the list of reviews page: https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/reviews/

It seems like the distinguishing characteristic is that these are reviews that have no text in the body.  It would be preferable to show these reviews, as well.

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file a bug. We fixed the incorrect count in https://github.com/mozilla/addons-frontend/issues/2327 which was deployed today.

Also, it will be easier to visualize the effect of star ratings (reviews without text) after this is implemented: https://github.com/mozilla/addons-frontend/issues/3919
