### ISSUE TITLE
Broken link on "An author has been added to your add-on" email

### ISSUE THREAD

**Issue by bovine3dom** [mozilla/addons#532]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
When developers are added to an add-on, the email sent out has a link to the page on the AMO. The URL includes an extra bracket and colon, e.g.

https://addons.mozilla.org/en-GB/firefox/addon/tridactyl-vim/):

### What happened?
The link leads to a 404.

### What did you expect to happen?
The link should go to https://addons.mozilla.org/en-GB/firefox/addon/tridactyl-vim/

**Comment by wagnerand** [comment]
Mentor: @eviljeff 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by VishalCR7** [comment]
@eviljeff I would like to work on this issue. Can you please tell me which files I should try to look on for solving it?

**Comment by eviljeff** [comment]
The templates in users/templates/users/email/ need changing to add a space before the `):`- they're django template format

**Comment by VishalCR7** [comment]
@eviljeff  please review [#7237](https://github.com/mozilla/addons-server/pull/7237) regarding this issue. Thanks! :)

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, with FF57 (Win 10)

Before fix:
![image](https://user-images.githubusercontent.com/31961530/34936657-eb4d6db8-f9ea-11e7-80aa-df05733cc97e.png)
Post-fix
![image](https://user-images.githubusercontent.com/31961530/34936663-f1941352-f9ea-11e7-9f41-905c6332a9a7.png)
