### ISSUE TITLE
adding/installing an add-on bug on the new add-on website design.

### ISSUE THREAD

**Issue by digitalwhiteout** [mozilla/addons#533]
### Describe the problem and steps to reproduce it:

adding/installing an add-on crashes with the new add-on website design.

works when going to Classic Desktop Website and trying again.

### What happened?
After clicking the "ad to firefox button" for a random add-on
download dialogue opens
download progress bar finishes

error message appears
can't install due to connection error

this problem reproduces also 
when following the download link 
from a developer website, non add-on s/firefox website

works when going to Classic Desktop Website and trying again.

### What did you expect to happen?
After clicking the "ad to firefox button" for a random add-on
download dialogue opens
download progress bar finishes
I click add
 add-on is installed (dialogue closes)

### Anything else we should know?
I choose most simple use case, to describe.
continues also in the complex variations of add an add-on on dialogue. 

   Version 56.0.2    Update-channel  32 Active Add-ons

(https://addons.mozilla.org/de/firefox/addon/ublock-origin/
)
![bildschirmfoto 2017-11-09 um 12 35 32](https://user-images.githubusercontent.com/26189940/32603587-8c45c1d2-c54a-11e7-8587-9a8cb5c0e3e2.png)
![bildschirmfoto 2017-11-09 um 12 39 28](https://user-images.githubusercontent.com/26189940/32603740-2bfa2484-c54b-11e7-89e3-a14057762813.png)

**Comment by digitalwhiteout** [comment]
![bildschirmfoto 2017-11-09 um 12 07 09](https://user-images.githubusercontent.com/26189940/32603524-534d6d12-c54a-11e7-82a3-5fb325f9a93a.png)

**Comment by muffinresearch** [comment]
@digitalwhiteout what you're seeing sounds like the same issue seen in https://github.com/mozilla/addons/issues/525 

Can you try the same steps listed here ? https://github.com/mozilla/addons/issues/525#issuecomment-342902763 this will verify if you have some 3rd party software that has installed a MITM ssl certificate.

**Comment by muffinresearch** [comment]
Closing based on https://github.com/mozilla/addons/issues/525#issuecomment-343229816 - Thanks for the update @digitalwhiteout
