### ISSUE TITLE
add this addon to firefox button issue (FF56.0.2 x64)

### ISSUE THREAD

**Issue by difool2nice** [mozilla/addons#534]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
the problem is with the new addons page interface : when choosing the button add to firefox it doesn"t load inside firefox, it purpose to save the extension "xxx.xpi" on my hard disk as if it was a saving file ! it' s not loading as extensions as usual ! i tried to see if it was one of my extensions causing troubleshoot but nothing is wrong with them ! it only does it on the new (or future ) UI of the page ! it doesn't do it on the  previous one classical page (computer version link at the bottom of the page).....
![2017-11-10_12h54_23](https://user-images.githubusercontent.com/25643255/32657572-9492ad88-c616-11e7-851f-ee784e856249.png)

**Comment by andymckay** [comment]
This will be fixed by mozilla/addons-frontend#3872 and that should be deployed sometime soon.

**Comment by andymckay** [comment]
This is now live, if you have time to retry, and let us know how it goes, that would be awesome. Thanks.

**Comment by difool2nice** [comment]
nice ! it works ! good job !  thanks for the fast reply
