### ISSUE TITLE
Add-on size

### ISSUE THREAD

**Issue by almahmudbd** [mozilla/addons#535]
Where is the "add-ons size" details in new site?
New site looks well but I missing this data very badly, please. turn back this.

**Comment by muffinresearch** [comment]
By size I presume you mean the file-size? E.g:

<img width="693" alt="ublock_origin____add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32725509-4613b964-c86d-11e7-9d91-434562eb50ad.png">

**Comment by muffinresearch** [comment]
I've re-filed this here https://github.com/mozilla/addons-frontend/issues/3900

**Comment by almahmudbd** [comment]
yes, you got the point.

--------------
Abdullah Almahmud
facebook.com/thealmahmud

--------------------------------------------
On Mon, 11/13/17, Stuart Colville <notifications@github.com> wrote:

 Subject: Re: [mozilla/addons] Add-on size (#535)
 To: "mozilla/addons" <addons@noreply.github.com>
 Cc: "almahmudbd" <almahmudbd@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Monday, November 13, 2017, 6:22 PM
 
 By size I presume you mean the
 file-size? E.g:
 
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by almahmudbd** [comment]
thanks

--------------
Abdullah Almahmud
facebook.com/thealmahmud

--------------------------------------------
On Tue, 11/14/17, Stuart Colville <notifications@github.com> wrote:

 Subject: Re: [mozilla/addons] Add-on size (#535)
 To: "mozilla/addons" <addons@noreply.github.com>
 Cc: "almahmudbd" <almahmudbd@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, November 14, 2017, 3:44 PM
 
 I've re-filed this here mozilla/addons-frontend#3900
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
