### ISSUE TITLE
Pressing reply on a user review makes them seem flagged

### ISSUE THREAD

**Issue by bovine3dom** [mozilla/addons#537]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I am trying to reply to a user review to my addon. When I click reply, a text box appears as expected, but the "flag" text changes to "flagged".

### What did you expect to happen?
No change to the flag text.

### Anything else we should know?
Offending page: https://addons.mozilla.org/en-GB/firefox/addon/tridactyl-vim/reviews/

**Comment by muffinresearch** [comment]
@bovine3dom thanks for the report - it's a duplicate of https://github.com/mozilla/addons-frontend/issues/3736 - the fix should be out later this week.
