### ISSUE TITLE
User review notification email does not contain its text

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/addons#538]
Last few review notifications I have got into my mailbox contained "Review: None" despite the reviewer added some textual note. The last one was https://addons.mozilla.org/firefox/addon/rotate-and-zoom-image/reviews/953699/. I do not know whether the review author has decided to add it later, but as this never happened to me, I suspect the new UI.

**Comment by diox** [comment]
Hi,

Thanks for reporting this, this is already filed as https://github.com/mozilla/addons-server/issues/6817 (as you suspected, it's because of the new UI using a different pattern to post user reviews)
