### ISSUE TITLE
AMO website: Navigating back is not properly working

### ISSUE THREAD

**Issue by caugner** [mozilla/addons#539]
### Describe the problem and steps to reproduce it:

1. I'm using Nightly on Android.
2. Open the Menu > Add-ons (about:addons).
3. Click on "Browse all Firefox addons" (https://addons.mozilla.org/en-US/android/)
4. Open the detail page of any add-on.
5. Navigate back using the "back" button or key.

### What happened?

I'm back at "about:addons". 

### What did you expect to happen?

I would expect to navigate back exactly one page on the AMO site.

### Anything else we should know?

I noticed that the URL doesn't change, even though the links to the individual add-ons have an explicit href (for use with "Open in new tab").

**Comment by kumar303** [comment]
Hi. Thanks for filing an issue. I'm pretty sure this is the same root problem as https://github.com/mozilla/addons-frontend/issues/3972 which has been fixed but won't be deployed until 9am PST on Thursday (tomorrow).
