### ISSUE TITLE
Add-on user review notification emails no longer contain email text

### ISSUE THREAD

**Issue by ghostwords** [mozilla/addons#540]
User review notification emails used to include review text, but no longer do. Here is what every add-on user review notification email looks like:

![screenshot from 2017-11-13 20 12 43](https://user-images.githubusercontent.com/794578/32757765-2c990858-c8af-11e7-8979-4ae6c73c3e17.png)

The "Review" field is always "None", regardless of whether the actual review contains text or not.

**Comment by ghostwords** [comment]
This is possibly related to my user being an unlisted author of the add-on in question.

**Comment by diox** [comment]
Hi,

This is due to the workflow used on the new frontend, this has already been reported as https://github.com/mozilla/addons-server/issues/6817
