### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by icl7126** [mozilla/addons#541]
[firefox-prod.zip](https://github.com/mozilla/addons/files/1473135/firefox-prod.zip)
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
Update of existing add-on

* Whether your add-on is listed or unlisted.
Listed

* The URL where you submitted the add-on.
https://addons.mozilla.org/en-US/firefox/addon/groupspeeddial/

* The approximate time you submitted the add-on, with timezone.
Right now, 3:00 CET

**Comment by icl7126** [comment]
Never mind, seems like my npm zip tool `easy-zip2` cannot create correct zip file anymore (extracting zip and repackaging it using windows build in zip fixed the issue).

**Comment by ashclarke** [comment]
I also had the same issue with `cross-zip`. Can anyone on the addon team shed any light on what might cause this and if there is a way around it?

**Comment by wagnerand** [comment]
Are you running Windows? If so, this is usually https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator

**Comment by ashclarke** [comment]
Yes, I am. 

Cross-zip uses [System.IO.Compression via Powershell](https://github.com/feross/cross-zip/blob/master/index.js#L78), so I think you're right.

I think I'll change my output to remove directories.

**Comment by wagnerand** [comment]
Ok, so this would have to be fixed in `cross-zip`. Maybe file a bug there?

**Comment by ashclarke** [comment]
@wagnerand - Thanks, I have raised an issue. Hopefully there is a solution apart from manually recreating the zip files.
