### ISSUE TITLE
Search function won't show incompatible addons in search results regardless of how relevant they are

### ISSUE THREAD

**Issue by UserNaem** [mozilla/addons#542]
### STR:
Search AMO for any extension that your browser version doesn't support, i.e. FireGestures (which won't support Firefox 57+)
Example:
https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=FireGestures
### Actual results
Search results are completely irrelevant, as if my search request was ignored completely or the extension didn't exist.
### Expected results
[FireGestures](https://addons.mozilla.org/firefox/addon/firegestures) on top of the search results listing.
### Anything else we should know?
Reproduces on Nightly 59.0a1 (2017-11-14) (64-bit) and DevEdition 57.0b14 (64-bit)
![image](https://user-images.githubusercontent.com/21028464/32816452-88f31bee-c9da-11e7-9a63-331b43f1d96b.png)

**Comment by tofumatt** [comment]
This is by design as search no longer surfaces incompatible add-ons for users on 57+.
