### ISSUE TITLE
AMO site is empty

### ISSUE THREAD

**Issue by alice0775** [mozilla/addons#544]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

AMO site is empty. nothing is displayed.

STR:
1. open https://addons.mozilla.org/

### What happened?
AMO site is empty

### What did you expect to happen?
AMO site should be display properly

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by alice0775** [comment]
AMO returns just now

**Comment by rctgamer3** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1417451
