### ISSUE TITLE
"Find replacement" page for add-ons without replacements is the wrong page

### ISSUE THREAD

**Issue by gene1wood** [mozilla/addons#549]
### Describe the problem and steps to reproduce it:

In Firefox Quantum when you go to add-ons and click "Find Replacement" next to a non webextension add-on like the following addons, the experience is confusing and bad.

* https://addons.mozilla.org/find-replacement/?guid=s3menu@wizard
* https://addons.mozilla.org/find-replacement/?guid=tabcounter@morac
* https://addons.mozilla.org/find-replacement/?guid=jid1-Y3WfE7td45aWDw@jetpack
* https://addons.mozilla.org/find-replacement/?guid=tabletools2@mingyi.org
* https://addons.mozilla.org/find-replacement/?guid=rehostimage@engy.us
* https://addons.mozilla.org/find-replacement/?guid=move@tabs.net

### What happened?

The user is taken to the page

https://addons.mozilla.org/en-US/firefox/collections/mozilla/featured-add-ons/?src=find-replacement

Titled "Featured Add-ons"

With a list of popular add-ons and nothing related to finding a replacement add-on

### What did you expect to happen?

For add-ons like these that have no replacement, the user should be given some page that has anything to do with finding a replacement. There should be text saying something like "We're sorry but we weren't able to find a replacement add-on, blah blah, here's some text to make you less angry right now"

### Anything else we should know?

![selection_071](https://user-images.githubusercontent.com/1134034/32984485-40895830-cc5c-11e7-987d-a1070dcf6fc1.png)

**Comment by jvillalobos** [comment]
The Featured Add-ons page was an intentionally-chosen fallback. It's not great, but it seemed better than other possibilities, like the one you mention. The transition to 57 is well underway, and the response to the feature has been largely positive, so I don't think that we will be making any changes to it at this point.

**Comment by gene1wood** [comment]
@jvillalobos That's disappointing. This seems like a very poor user experience, and at least for myself, the the majority of add-ons in my installation take me to this confusing and poor user experience.

**Comment by kumar303** [comment]
If you can't find anything by searching, there was a spreadsheet going around with tons of replacements: https://docs.google.com/spreadsheets/d/1TFcEXMcKrwoIAECIVyBU0GPoSmRqZ7A0VBvqeKYVSww/edit#gid=0

**Comment by gene1wood** [comment]
@kumar303 could we just render these recommendations into the `find-replacement` endpoint on AMO?

**Comment by andymckay** [comment]
At this point the number of people using recommendations has dropped to close to zero. There was a week or two of frenetic activity around 57 and that was it. I don't think its worth doing anything now.
