### ISSUE TITLE
Redesign AMO add-on submission interface

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#55]
Latest flow (always updated):
![submission-flow](http://addons.readthedocs.org/en/latest/_images/ux-submission-flow.png)

Latest wireframes (always updated):
![submission-wireframes](http://addons.readthedocs.org/en/latest/_images/ux-submission-wireframes.png)

**Comment by brampitoyo** [comment]
Current state of proposal:

There are four stages to the add-on submission process
* Agreement
* Upload
* Distribution
* Review (not performed by developers)
* Add details, or reupload: happens on the management interface

#### Agreement

User must click agree in to proceed

#### Upload

Add-on file must pass validation to proceed

#### Distribution

* User may choose to list on AMO
    * If so, user must select whether to put the listing on the release or beta channel
* User may choose to self-host
    * If so, add-on is automatically signed and ready to download

#### Review (performed by AMMO Team)

* Listed add-ons must undergo review. Whether review is passed or not passed, proceed
* Self-hosted add-ons may undergo review. If review is **rejected**, proceed

Either way, both types of add-on receive a new entry on the management interface:

* Each entry is created under the appropriate channel
  * For listed add-ons, the channel is either release or beta
  * For self-hosted add-ons, the channel is always self-hosted
* Each entry is titled with its own version number
* Each entry is a place to have discussion and change add-on status. Think of it like GitHub issues.

#### Add details, or reupload

* Listed add-ons
  * If review is passed, proceed to add details, then proceed to publishing
  * If review is rejected, proceed to reupload add-on file, then go back to the **Review** stage
* Self-hosted add-on
  * If review is rejected, proceed to reupload add-on file, then go back to the **Review** stage

**Comment by brampitoyo** [comment]
Also paging @jvillalobos and @andymckay for feedback on this issue. I’m curious to see if there’s any improvements we can already make today, without waiting for a total redesign.

**Comment by andymckay** [comment]
I do not want to make any improvements that are not focused on a specific goal (eg: WebExtensions) without thinking about the total redesign.

**Comment by jvillalobos** [comment]
When/if we start working on the status redesign (H2), we can start working towards this. For now I think this needs to stay on hold.

**Comment by brampitoyo** [comment]
I’m beginning the work to rethink the submission interface based on all the work that the team’s done for the past few months.

We start with a slightly different flow than the one from last May, with no more partial review:
![amo developer ux - submission flow](https://cloud.githubusercontent.com/assets/51007/17917667/b0edc80c-6a12-11e6-9d6f-fd943a239dd8.png)

With that changed, the wireframes has been tweaked, as well:
![amo developer ux - submission wireframes](https://cloud.githubusercontent.com/assets/51007/17917694/dd4bb5d0-6a12-11e6-95ad-638fa8753018.png)

And now, knowing that we’ve got a flow and wireframe in place, I have started exploring what the actual pages could look and feel like:
https://mozilla.invisionapp.com/share/AZ665IEY2#/183450006_Home_-_Submission_-_Agreement-1x

**Comment by brampitoyo** [comment]
Instead of completely redesigning the submission flow as proposed in this issue, we’re making small tweaks to the new add-on, new version and new platform UIs instead. Closing this issue.
