### ISSUE TITLE
API does not permit uploading additional source archive (required for review)

### ISSUE THREAD

**Issue by cmcaine** [mozilla/addons#551]
If a webextension's source is obfuscated, the reviewing rules say that authors must upload a source archive for reviewers. Webpack and other ES6 transpilers count as obfuscation, so this will affect many addons.

### Describe the problem and steps to reproduce it:

I want to upload a source code archive as well as the bundled source via the API so that I can automatically deploy my addon to AMO.

### What happened?

The API has no such function.

**Comment by cmcaine** [comment]
I think this is still a legitimate issue and it has been triaged. It should stay open. OTOH, I'm not willing to do the work and it's your project so :man_shrugging:

**Comment by willdurand** [comment]
I suppose this is related to https://github.com/mozilla/sign-addon/issues/409 (there are server issues linked in this issue too)

**Comment by diox** [comment]
Going to forward-dupe this to https://github.com/mozilla/addons-server/issues/9913 which is already on the right repository for us.
