### ISSUE TITLE
AMO website: Navigating past page 1000 is not possible

### ISSUE THREAD

**Issue by rinayukina** [mozilla/addons#552]
### Describe the problem and steps to reproduce it:
When browsing the search results for add-ons, I can't go past page 1000 and if I click the '**Next**' button all I get is a page that says **'No results were found.'**
Here:
https://addons.mozilla.org/en-US/firefox/search/?page=1000&sort=updated&type=persona
To here:
https://addons.mozilla.org/en-US/firefox/search/?page=1001&sort=updated&type=persona

### What happened?
I get taken to a page that says '**No add-ons found**' but I am sure there are more.

### What did you expect to happen?
To get to the next page.

### Anything else we should know?
![capture1](https://user-images.githubusercontent.com/33796776/32987250-f3e24bca-cd20-11e7-8d2a-11cdf150febe.PNG)
leads to this:
![capture](https://user-images.githubusercontent.com/33796776/32987257-0efe1736-cd21-11e7-83fc-dc377af9228d.PNG)

**Comment by tofumatt** [comment]
There is an issue open for this but I’m on my phone and can’t find it. I think it’s related to the max number of add-ons the API returns or something.

- Matt (Sent from mobile)

**Comment by ValentinaPC** [comment]
Here's the issue: https://github.com/mozilla/addons-frontend/issues/3887

**Comment by muffinresearch** [comment]
Duping this one to mozilla/addons-frontend#3887
