### ISSUE TITLE
Add-on "new review" email does not contain review text

### ISSUE THREAD

**Issue by fwenzel** [mozilla/addons#553]
### Describe the problem and steps to reproduce it:
I am subscribed to email notifications when someone leaves a review on my add-on. The email used to contain the review text, it does not anymore.

### What happened?
Email text:
```
A user has left a review for your add-on, Copy ShortURL.

Rating:
5 out of 5 stars.

Review:
None

You can read the review and reply to it here:
https://addons.mozilla.org/addon/copy-shorturl/reviews/972367/reply



===================================================================
You received this email because you're subscribed to:
   * email me when someone writes a review of my add-on
```

### What did you expect to happen?
`Review: None` smells like a Python bug; at any rate these emails never contain the review text anymore, but they should.

### Anything else we should know?
I am not sure as to the exact regression window, but the last email I received *with* the review text was **October 13**, everything afterwards has `None`.

**Comment by diox** [comment]
Hi, this was already reported as https://github.com/mozilla/addons-server/issues/6817

**Comment by fwenzel** [comment]
oh lol, thanks! Clearly I didn't understand addons vs addons-server. Thanks!

**Comment by diox** [comment]
That's ok, it's meant as a generic place to file anything about AMO, as long as the bugs are filed somewhere we can direct the reporters to the right repos if needed afterwards :)
