### ISSUE TITLE
AMO Website: Daily Users # wrong (zero) for some days

### ISSUE THREAD

**Issue by zoliszabo** [mozilla/addons#556]
### Describe the problem and steps to reproduce it:
In the stats page of my addon (https://addons.mozilla.org/en-US/firefox/addon/MY_ADDON_HERE/statistics/?last=30), the number of users for some days is 0.

### Anything else we should know?
![statistics dashboard __ add-ons for firefox](https://user-images.githubusercontent.com/9949042/33031251-6398fac6-ce26-11e7-932d-faaea7c732f9.png)

**Comment by jvillalobos** [comment]
Tracked on https://github.com/mozilla/addons/issues/510
