### ISSUE TITLE
[Review Tools] Adding JSZip to allowed hashes

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#558]
A lot of developers are using `jszip.js`
It would be useful to add its hash to the allowed hashes.

`http://stuk.github.io/jszip/`

**Comment by wagnerand** [comment]
I am closing this for now. I agree that it's a good idea to expand the list, but the process is very manual currently and we don't have a good way (yet) to assess impact. There is some upcoming work planned around code search where we could hook into for this. I am planning to revise the known libraries list after that has been landed.
