### ISSUE TITLE
Redesign AMO add-on management interface

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#56]
Latest flow (always updated):
![management-flow](http://addons.readthedocs.org/en/latest/_images/ux-management-flow.png)

Latest wireframes (always updated):
![management-wireframes](http://addons.readthedocs.org/en/latest/_images/ux-management-wireframes.png)

**Comment by brampitoyo** [comment]
Current state of proposal:

The management interface has two basic functionalities:

1. Edit listing information (not relevant if add-on is unlisted)
2. Manage channels

---

#### Edit listing information

* This is where you edit your add-on’s title, description, screenshots, categories, etc.
* If add-on only exists on `self-hosted` channel, don’t show this fuctionality

---

#### Manage channels

![manage-channels](https://cloud.githubusercontent.com/assets/51007/13656700/119af512-e6ce-11e5-9754-44ac8190e994.png)

##### The channel paradigm

* If add-on is hosted on AMO, it can either be submitted to:
  * `release` channel, or
  * `beta` channel
* If add-on is self-hosted, the channel is eponymously named `self-hosted`
* Using this channel paradigm, the same add-on can be **both hosted on AMO and self-hosted**
  * Today, you can only submit an add-on with the same name as one or the other, but not both

##### Proposal: channel flagging

* If add-on is hosted on AMO and exists on both `release` and `beta` channels, developers can set the channel flag
  * `visible`: end user can see and search for it on AMO
  * `invisible`: end user cannot see and search for it, but if they have the URL, they can still access it

---

#### Manage version within channels

![manage-version](https://cloud.githubusercontent.com/assets/51007/13657327/3bee9dc8-e6d3-11e5-8685-af3ad9132fd8.png)

##### Proposal: canonical versioning

* Each time you submit a new add-on or a new version within an add-on, a new entry is created under the appropriate channel
* This entry is marked with your add-on’s version number
* Proposal: As long as your add-on status is not flagged as `approved`, you can submit a patch to it, and this will not modify its version

##### Proposal: version flagging

* Some flags can be set only by the AMMO Team
  * `approved`
    * Add-on hosted on AMO that has passed review
    * Self-hosted add-ons that has been auto-signed successfully
    * Self-hosted add-ons that has been re-reviewed after it’s been signed and passed it
  * `rejected`
    * Add-on hosted on AMO that has not passed review
    * Self-hosted add-ons that has not passed review
  * `under review`
    * Add-on hosted on AMO that has been submitted for review
    * Self-hosted add-on that is currently being re-reviewed
* Some flags can be set by developers, but only when it’s hosted on AMO and has been `approved`
  * `not published`: add-on doesn’t appear on listing page
  * `published`: add-on appears on listing page (but only if channel flag is `visible`)

**Comment by brampitoyo** [comment]
Paging @jvillalobos and @andymckay for feedback, even though we might not be ready to work on this just yet. This issue is especially related to Jorge’s work on refactoring add-on review status.

**Comment by andymckay** [comment]
I have so many questions I'm not sure if I can give sensible feedback, would much rather frame this in context of the overall redesign.

**Comment by jvillalobos** [comment]
> Proposal: As long as your add-on status is not flagged as approved, you can submit a patch to it, and this will not modify its version

This has proven problematic in the past, because of the way the server handles file uniqueness. To work around it new submissions need to have a higher version number.

> version flagging

Most of this is how add-on statuses already work. The `published` / `not published` flag would be new, and the same feature is included in the _Status refactoring_ section of the Status Redesign (look for _Developer disable listed version flag_).

**Comment by brampitoyo** [comment]
Since last May, we’ve broken this issue down into more manageable, bite-sized projects (starting with the dev hub front page and reviewer–developer communication). I’m closing this issue.
