### ISSUE TITLE
Installed Add-ons are not showing as Installed on the Add-ons web page

### ISSUE THREAD

**Issue by SabbirEP** [mozilla/addons#560]
### Describe the problem and steps to reproduce it:
Add-on page should have the sense of a particular add-on installment and change accordingly and should not allow the user to download it again. Why this not implemented yet

### What happened?
Installed Add-ons are not showing as installed and if I click "Add to Firefox" it downloads and installs itself again.

### What did you expect to happen?
Add-on page should have the sense of a particular add-on installment and change accordingly and should not allow the user to download it again.

### Anything else we should know?
https://bug1418932.bmoattachments.org/attachment.cgi?id=8930013

**Comment by muffinresearch** [comment]
Hi @SabbirEP  - thanks for the report. This is planned see https://github.com/mozilla/addons-frontend/issues/3954
