### ISSUE TITLE
Add tag:legacy to legacy-addons, as tag:Firefox57 added to "WebExtensions" only addons

### ISSUE THREAD

**Issue by TarekJor** [mozilla/addons#561]
This is a feature request for AMO, more than a "bug" itself, but it would be useful: * (1)

**Feature**:

Add tag:legacy or something similar to legacy-addons, as tag:Firefox57 added to WebExtensions-only addons

**Reason**:
This is a feature request, to "make easier" archiving or management of XUL  based legacy-addons before total deprecation, or removal from AMO (when Firefox-52-ESR ceases near 2018-Q2), and to tracking about "legacy addons migrated or not to WebExtensions"

**Similar to WebExtensions tagged with Firefox57**:

* (1) If WebExtensions-only addons which are ready to Firefox57 are tagged with tag:Firefox57, then this is useful as "addons NON-tagged with Firefox57" => legacy addons?

**Legacy-addons migration**:

Useful to archiving the legacy-addons and preserve them, and tracking migration process to WebExtensions-only based addons,

PD: Sorry if this is not the proper place or this issue is "badly formed" (related to addons-server & addons-frontend)

**Comment by jvillalobos** [comment]
If you mean a visual indicator on listing pages, we have that now. For example, [on this page](https://addons.mozilla.org/firefox/addon/flashgot/), you'll see a message `Not compatible with Firefox Quantum`.

Are you trying to get this data from the API, or somewhere else?

**Comment by TarekJor** [comment]
Thanks for fast answer @jvilalobos (sorry for my delay on response), I have a lot of work :D
Could I attach files with captures for clarify some things? (I ask because I am new here)

This issue involves backend and frontend fixes, new responsive AMO theme fixes, tags support among other things to improve navigation and UX addon discovery, and it is related to AMO search and AMO API, I am new here, and I don't want spam, or create "various issues", at least, for now.

**Comment by jvillalobos** [comment]
Feel free to add any information or screenshots that help clarify what you want.

**Comment by jvillalobos** [comment]
Legacy extensions are no longer supported.
