### ISSUE TITLE
[Reviewer Tools] Auto_Approved Queue WX no longer needed

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#562]
ref:
`<div class="app-icon ed-sprite-webextension" title="WebExtension"></div>`

The WebExtension icon/style is no longer relevant since that is the only type that should appear on this queue.

Not an important issue, but just a tidy-up suggestion.

**Comment by jvillalobos** [comment]
There's a big redesign coming up for reviewer tools, so I'm closing this for now. I agree that the icon isn't useful anymore.
