### ISSUE TITLE
NordVPN don't working or turn off

### ISSUE THREAD

**Issue by didierpineux** [mozilla/addons#565]
Since last update (began novembre) I NordVPN stop working or don't want to start.

I tried many times toi restart the program but without result.
I restart the computer and restart the program but without result
I erase the program from the computer and after reboot, I reinstall the program. But it does not want to work.

At the same time, my notebook work correctly and my smartphone (android) work to.

Then I think that my network is correctly working.
Do you have à solution for me (perhaps, can you send me the previous relaese ?)

Regards
DPx

**Comment by wagnerand** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on.

If you're having an issue with an add-on please contact the developer directly; you can find a link to their contact details on the add-on page on addons.mozilla.org
