### ISSUE TITLE
Can't see more than 25 search results on addons.mozilla.org

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/addons#566]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I went to addons.mozilla.org, to see whether some of my xul-based accessibility tools have webextension-based alternatives. If I search for one term, addons.mozilla.org may say it has hundreds of results. I can only access the 1st page, which may not have relevant results. I can't access the 2nd or subsequent pages.

### What happened?

I searched for "toggle javascript" looking for webextension equivalents of QuickJava or PrefBar. addons.mozilla.org claims 200 results. Of these 25 appear on the 1st page. The other 175 don't appear, and there is no sign of any way to reach a 2nd page.

### What did you expect to happen?

I expect some way to reach beyond 25 results.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

I am using Firefox 52 esr with a few dozen accessibility fixes.

**Comment by eviljeff** [comment]
There are buttons at the bottom of the page.  We could do with a screenshot

**Comment by MarjaE2** [comment]
There aren't any buttons visible after scrolling to the bottom of the list. I can now see that the bottom of the list is only about 1/9 of the way down the page. Depending on people's scrolling options, if they can't use the bar, and don't have page down buttons, it can be awkward to scroll several feet.

How should I add a screenshot?

**Comment by kumar303** [comment]
Hi. Thanks for filing an issue. This is what I see when I scroll to the bottom of those search results. Do you not see this? I haven't tried in your exact version of Firefox.

<img width="846" alt="screenshot 2017-11-29 11 51 50" src="https://user-images.githubusercontent.com/55398/33390529-ca9443c6-d4fb-11e7-8ef5-7f761d4e65b9.png">

**Comment by MarjaE2** [comment]
I eventually found that... after scrolling _several feet_ past the bottom of the search results. I reached the end of the search results after 4 page downs. I didn't reach those buttons until 70 page downs. 70!

It looks like a spacing issue of some kind.

**Comment by kumar303** [comment]
> It looks like a spacing issue of some kind.

Do you mean that the page had blank, empty space?

If you could use this add-on to create a screenshot of the entire page, it would be helpful. https://addons.mozilla.org/en-US/firefox/addon/screenshot-capture-annotate/

**Comment by MarjaE2** [comment]
Thanks, but I can't get it to work.

**Comment by kumar303** [comment]
Without a screenshot or a bit more detail I'm not sure what the issue is but if you are seeing blank space then my guess is it's a problem with Firefox ESR's css grid support, perhaps similar to https://github.com/mozilla/addons-frontend/issues/3015

**Comment by muffinresearch** [comment]
@MarjaE2 @kumar303 I can reproduce in Firefox ESR - I'll see if I can get a fix in for the tag.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52.0 (64-bit) under Win 7.
Postfix video:
![nav](https://user-images.githubusercontent.com/15685960/33655199-15d78c1a-da7b-11e7-954a-2fe047811ea5.gif)
