### ISSUE TITLE
Two search terms narrows the results; three search terms explodes them.

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/addons#567]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I went to addons.mozilla.org, to see whether some of my xul-based accessibility tools have webextension-based alternatives. If I search for 1 term, addons.mozilla.org may say it has hundreds of results. If I search for 2 terms, that narrows the results, but not enough. If I search for 3 or more terms, that successively widens the results.

I can't use Firefox or any browser without appropriate accessibility tools, so I am using 52 ESR for the forseeable future. But if 57+ will have appropriate accessibility tools, it would help to have some way to find these tools.

### What happened?

I searched for "toggle javascript animation images" looking for webextension equivalents of QuickJava or PrefBar, to block animation without breaking too many sites. addons.mozilla.org claims 474 results for toggle, 200 for toggle javascript, 3,248 for toggle javascript animation, and 3,876 for toggle javascript animation images. The narrower the search beyond 2 terms, the higher and deeper the pile of results.

I also can't examine more than the 1st 25 results, due to bug 566.

### What did you expect to happen?

Searches should yield results containing their search terms, and as a consequence, adding more search terms should yield fewer results. The narrower the search, the smaller the pile of results.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

I am using Firefox 52 esr with a few dozen accessibility fixes.

See also bug 566: https://github.com/mozilla/addons/issues/566

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, FF58 (Win10, Android 7.0)

I've searched for several examples but judging by the below results, I'm not sure if this was fixed:

`Sound On Click Ica Test` - "sound" -> 16,032 results; "sound on click" -> 15,932 results; "sound on click ica" ->16,274 results
`Secret Smiley Emoticons2`  - "secret" ->361 results; "secret smiley" -> 560 results
`Live Start Page - Living Wallpapers `- "live" ->1,463 results; "live start" -> 2,877 results; "live start page" -> 2,957 results

@EnTeQuAk  what's your opinion?

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk what's your opinion?

I think that's somehow expected but still not properly fixed. It's certainly much better than before.

I unassigned myself for now, this got a bit better after the latest search update, I might get back to it once I have more time for it.

**Comment by diox** [comment]
I think it's because we don't apply `"operator": "and"` to the fuzzy name matching, so that rule only needs a single term to match to return results. Will test this theory soon. As noted above it's much less of a problem now than it was before.

**Comment by diox** [comment]
I've added a rule to add a minimum number of terms matching the fuzzy query. Once this lands, the idea is that for queries with one or two words, both must be present, for queries of 3 words, 2 must be present, and for more, 25% can be absent (which is slightly different from a 75% should be present rule, because of the way we round odd numbers)

So, back to the queries above, two terms should limit the number of results, but 3 should open it up slightly (less than before where only the presence of a single word was necessary)

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF63, WIn10x64

I've tried again with my previous samples and a few new examples and search narrowing is much more relevant now. 

**Sound On Click Ica Test** - "sound" -> 16,041 results; "sound on click" ->  5 results; "sound on click ica" ->10 results  
**Secret Smiley Emoticons2**  - "secret" ->407 results; "secret smiley" -> 2 results
**Live Start Page - Living Wallpapers** - "live" ->3,224 results; "live start" -> 34 results; "live start page" -> 28 results
**Awesome Screenshot Plus - Capture, Annotate & More** - "awesome" -> 16,572 results; "awesome screenshot" -> 11 results; "awesome screenshot plus" -> 1 result (exact match)
**Stratiform** -> "customize" -> 1,489 results; "customize browser" -> 46 results; "customize browser look" -> 5 results
**Enhancer for YouTube** - "improve" -> 560 results; "improve experience" -> 8 results; "improve experience on youtube" -> 1 result
