### ISSUE TITLE
Static Theme preview thought-dump / discussion

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#568]
Static theme previews are problematic.  
In the wizard it's implemented as an SVG, which is stored in a django template for l10n of the text elements (File, etc); JavaScript is used to set the background image and the colours.  That's great for the wizard but we need previews in other areas of AMO - possibly in other parts of devhub (e.g. to differentiate your themes in my add-ons) and definitely in the reviewer tools for approval, and frontend for the detail and list pages.  So, how to best "preview" the theme in other places?

Option 1: rasterize the svg in devhub and save as a flat preview.  
Problems - rasterizing in the wizard only works for wizard submissions and themes can also be submitted as pre-built zips via devhub or via the API; so we have to rasterize in django (i.e. re-implement the JavaScript); we lose l10n at the point of rasterizing.
Advantages - once rasterized we can treat it like any other screenshot jpg/png add-ons have, no further special handling needed.

Option 2: generate the svg on demand.
Problems - impractical for situations where we need multiple previews at once (e.g. frontend search results); the header image will have to either be extracted and made available via CDN for inclusion via URL, or read as a data URI and served inline; to avoid transferring the entire zip file size we'll need to crop/scale the background image.
Advantages - we can update the SVG template later to something better looking; l10n of the text strings.

Further complication to mention at this point - _our_ flavour of static themes also supports [additional backgrounds](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme) - an unlimited number of them, which can be positioned in multiple different positions with different tiling.  (The wizard doesn't currently mozilla/addons-server#7019). This breaks the simplistic svg implemented as mentioned above as we can't just substitute a single data uri string into a set location - we need to add each additional background as a layer.  (Even supporting, say, 10 additional backgrounds is limiting as number 11 might substantially change the final render in Firefox).  While the wizard doesn't support the additional backgrounds it's not a problem for the wizard generated themes, but _is_ a problem for the zip file submissions if we expect to auto-generate a preview for those too.

Option 3: some sort of hybrid of 1 and 2...
Attempt to flatten the (potentially many) header images?  Something else?  Essentially the advantages of both options but most of the disadvantages too.

**Comment by eviljeff** [comment]
@muffinresearch @jvillalobos for any thoughts to narrow down the options.

**Comment by muffinresearch** [comment]
The problem with just generating an SVG or using HTML markup as the preview is going to mainly be around the performance issues with including large images as part of the SVG. 

Rasterizing an SVG seems like a good idea however to fix that performance issue. However, we'll need to think about what to do with the case of changing the template SVG. This would require lots of images to be updated. 

Another 3rd possibility is do we need to provide a preview at all? Instead, could the preview be provided by the author uploading images to their listing? This would move us away from doing something like we currently have for lightweight themes but does make this much simpler. We could then invest more time in make our image support better.

**Comment by jvillalobos** [comment]
> Instead, could the preview be provided by the author uploading images to their listing?

I'm opposed to this because it will make preview quality very inconsistent. That's a problem we have with extension screenshots now, where some images are really bad (even by our current low resolution standards). It's not that big of a problem for extensions because screenshots are a secondary feature, but for themes the preview is key to comparing themes and deciding whether you want to try it or not. 

It can also mean there being a mismatch between what's in the preview and what's in the actual theme. And it would make the jobs of theme reviewers harder, since they'll need to install the theme instead of just looking at the preview.

**Comment by muffinresearch** [comment]
I'm closing this since we've gone forward with rasterizing the SVG for now.
