### ISSUE TITLE
"Create a New Theme" page doesn't allow images at recommended sizes

### ISSUE THREAD

**Issue by Cybolic** [mozilla/addons#569]
### Describe the problem and steps to reproduce it:
The [guidelines](https://developer.mozilla.org/en-US/Add-ons/Themes/Lightweight_themes)  recommend the following:

_Ultrawide monitors can run to 3440px wide, to look good on these monitors, either increase the size of the image or ensure the left of the image fades to a solid colour._

However, an image of that width cannot be uploaded at https://addons.mozilla.org/en-GB/developers/theme/submit

### What happened?
When attempting to upload an image with a size of 3440x200, the following error is given:
_Image must be exactly 3000 pixels wide and 200 pixels tall._

### What did you expect to happen?
The image should upload as the size is according to recommendations.

### Anything else we should know?
Practically every theme on addons.mozilla.org currently looks broken on ultra-wide monitors, most likely due to this issue. While it's possible to create good looking fading themes as is, anything that uses vertical gradients or changes will currently look wrong, UI themes in particular.

**Comment by jvillalobos** [comment]
That tip is incorrect. As the article points out "Dimensions should be 3000px wide × 200px high". We're moving to a different theme format in the near future which should scale better to larger screens, so we're not changing the size requirements now.
