### ISSUE TITLE
Cannot Install Google Voice & Video Plugin

### ISSUE THREAD

**Issue by linfield12** [mozilla/addons#570]
### Describe the problem and steps to reproduce it:
Unable to join a Google Hangout on FireFox.  Downloaded FFESR.  Prompted to download/install plugin.  Followed prompts but plugin does not move past the verification stage.  Restarted browser and computer.  Problem persists.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by kumar303** [comment]
Hi. Sorry that you're having trouble but this is not something we can fix on https://addons.mozilla.org . It may be an issue with the ESR release but I'm not sure. You could try filing a bug here: https://bugzilla.mozilla.org/
