### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by Urhixidur** [mozilla/addons#571]
This is most likely NOT the right place to file this "bug", but I was unable to find another (more appropriate) communication channel. I have an issue with two French translation strings:

"Un peu de HTML supporté" should be "Un peu de HTML pris en charge"

and

"Signaler un bug" should be "Signaler un bogue"

Where are the translations? Babelzilla Babelwiki, BetaWiki (Nuka-Wiki/Translatewiki), elsewhere?

**Comment by kumar303** [comment]
Hi. Thanks for filing an issue. Can you attach a screenshot and provide a URL where you see the incorrect translations?

**Comment by yfdyh000** [comment]
https://pontoon.mozilla.org/fr/amo/all-resources/?status=translated&search=Un+peu+de+HTML+support%C3%A9&string=65293

See the https://wiki.mozilla.org/L10n:Teams:fr for contact maintainers.

**Comment by kumar303** [comment]
That is a string for the legacy AMO site. A URL and screenshot would be helpful to know where it's still visible on the new site.

**Comment by diox** [comment]
It's a string in devhub. The link to pontoon was provided by @yfdyh000 above, anyone interested should contact the french localization team.
