### ISSUE TITLE
Please add the ability to disable reviews

### ISSUE THREAD

**Issue by yoe** [mozilla/addons#572]
My addon is written for one purpose only: to allow people to easily enable their government-issued eID card in Firefox. It's a very thin layer, and simply loads the relevant PKCS#11 module into Firefox. This works if the user has properly installed the relevant OS-specific PKCS#11 module, and fails otherwise, but then the add-on will tell the user and guide her into doing what she needs to do to fix the issue.

Once the module has been installed, it may fail to work for any number of reasons, none of which are related to the purpose of installing the module in Firefox:

* The card reader's driver may not be properly installed, or be buggy
* The card reader is just a piece of hardware, which may fail
* The PKCS#11 module depends on services provided by the OS. The OS may have been updated to a more recent version since the user installed the PKCS#11 module, which may mean the APIs provided by the OS may have been updated, causing the PKCS#11 module to fail.
* The user may have failed to properly insert their card into their card reader (you'd be surprised how often this happens)
* ...

As such, the user experience related to the eID installation may not be 100% where it should be. Unfortunately, however, some users confuse the add-on review form with an "eID review form", to the extent that we expect that some of the reviewers don't even use Firefox as their browser when they post a "review" of the addon, abusing the addons.mozilla.org review form as a generic review form for the Belgian eID card to complain about how things don't work properly. We  flag the more egregrious ones of those as "inappropriate language" and/or "misplaced bug report/support request", but they're not very helpful for two reasons:

* While we added a link to our support request form on the addons.mozilla.org website, that link is hidden away below the fold, whereas the review results and submission form is more prominently visible. As a result many users don't see it who would be (much) better served by just entering a support request
* When the review score drops below a certain point, in the past at least some versions of Firefox would warn the user about a "possibly malicious" addon. Since all the addon really wants to do is help users with configuring their system so things run more smoothly, this is not really helpful.

As such, I'd like to request that some way be made available for addon developers to disable the review system for their specific addon.

**Comment by tofumatt** [comment]
Just weighing in as a developer and user of the site: I don't think this is a good idea because ratings and reviews act as social proof for an add-on and a malicious add-on could easily disable reviews (from the start) to avoid getting bad press on the site. If you don't want random users stumbling across the add-on from search results you could try uploading an unlisted add-on that would not appear in search results.

**Comment by yoe** [comment]
On Thu, Nov 30, 2017 at 04:30:41PM +0000, Matthew Riley MacPherson wrote:
> Just weighing in as a developer and user of the site: I don't think this is a
> good idea because ratings and reviews act as social proof for an add-on and a
> malicious add-on could easily disable reviews (from the start) to avoid getting
> bad press on the site.

There already is a button "Report this add-on for abuse" on the site
currently (even more below the fold than the "support site" link,
however). It could easily be made more prominent when reviews are
disabled.

In addition, it might make sense for a requirement that there be some
form of feedback to the developer (e.g., "the support link must exist
and point to a valid URL when reviews are disabled").

> If you don't want random users stumbling across the add-on from search
> results you could try uploading an unlisted add-on that would not
> appear in search results.

Unlisted add-ons aren't auto-updated, and the advantage of having an
auto-updated add-on has saved us a few times in the past.

(Yes, we could create an os-level auto-updater ourselves, but we'd
rather not)

-- 
Could you people please use IRC like normal people?!?

  -- Amaya Rodrigo Sastre, trying to quiet down the buzz in the DebConf 2008
     Hacklab

**Comment by wagnerand** [comment]
You don't need to create an os-level auto-updater. All you have to do is host a JSON update file and the actual add-on file. See https://developer.mozilla.org/en-US/Add-ons/Updates

**Comment by jvillalobos** [comment]
Reviews are valuable feedback for prospective users, and a signal we use to identify spam and malicious add-ons. Disabling them can potentially cause a lot of harm, so I don't think we should do this.

**Comment by jvillalobos** [comment]
I should also add that we have some plans for next year to make it easier for users to identify the different ways in which they can get in touch with add-on developers, so they will know better how to contact for support instead of posting negative reviews.
