### ISSUE TITLE
[Reviewer Tools] Top Review Stats are missing

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#573]
With the latest push yesterday the **Reviewer Tools** page has changed and no longer provides the monthly and overall review stats for top reviewers.

Some my find it trivial but I found it to be a great motivator (especially for those passed the regular incentive motivation)
`https://reviewers.addons.mozilla.org/en-US/reviewers/`

Please reinstate them as soon as possible.

**Comment by jvillalobos** [comment]
They're planned for the reviewer tools work in Q1.
