### ISSUE TITLE
searching for addons for 57+

### ISSUE THREAD

**Issue by Elmers-1st-son** [mozilla/addons#574]
When I search for addons, I would like to be able to see only new format ones. I am trying to figure out how to get "wired markers" functionality. Old form ones will not do. When I search, most every one is old format. I am having to waste a lot on time.

**Comment by jvillalobos** [comment]
If you use Firefox 57, you should only be getting results that are compatible with Firefox 57 and above. Please report back if you're seeing incompatible add-ons.
