### ISSUE TITLE
[Review Tools] Review attached to the wrong version

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#576]
Review for Version 2.0.28 (rejected) got attached to Version 2.0.27 (previously passed) resulting in the wrong version being rejected.

`https://reviewers.addons.mozilla.org/editors/review/425230/`

Additionally ....

`https://reviewers.addons.mozilla.org/editors/review/866013/`
**Reviewer reply** posted for Version 0.21.4 · Dec. 4, 2017 · is attached to Version 0.14.3 · Oct. 24, 2017 · Approved, which is not visible to the next reviewers and out of context for that version.

Even the **comment** was posted to the older version which is 3 pages behind the current page.

Steps To reproduce:

Post **Comment** or **Reviewer reply** to an add-on whose latest versions have been rejected and has a older approved version. The post gets posted to **the last approved version** instead of **the last uploaded version**.

**Comment by wagnerand** [comment]
Possibly a regression from #7017.

**Comment by muffinresearch** [comment]
@erosman thanks for the report - we're going to revert mozilla/addons-server#7017 since @evijeff's testing has shown that should fix the latter part of this bug (the part with the STR)

For the first part of the issue, please could you file a new issue with the full STR and we can look into it separately?

**Comment by erosman** [comment]
> For the first part of the issue, please could you file a new issue with the full STR and we can look into it separately?

TBH, I dont know what happened there. It is possible that the review and a new version upload happened at the same time but since I am not sure, I cant not post a STR. If it happens again, I will post a new bug.

**Comment by ValentinaPC** [comment]
Verified this on AMO-stage hopping that I could reproduce it.
Is this already fixed on stage?
AMO-stage example:
![2017-12-06_1534](https://user-images.githubusercontent.com/15685960/33664095-21b43be4-da9b-11e7-822f-1334af93336e.png)

**Comment by eviljeff** [comment]
@ValentinaPC it's "fixed" as in all reviews are attached to the latest version.

**Comment by ValentinaPC** [comment]
@eviljeff : in stage too?

**Comment by eviljeff** [comment]
it's in the tag so should be on stage, yes.

**Comment by ValentinaPC** [comment]
I've verified this in both dev and stage and seems fixed.
All reviews are added to last submitted version of an add-on, as it can be seen in above screenshots.
Marking this verified-fixed.

**Comment by erosman** [comment]
It seems to still happen in case of 'deleted" versions.

Example:
`https://reviewers.addons.mozilla.org/editors/review/899500/`

Replies are attached to the previous version.

**Comment by wagnerand** [comment]
Can you please file a new bug for this? Thank you!
