### ISSUE TITLE
Unnecessary sanitaization of addon summary.

### ISSUE THREAD

**Issue by musically-ut** [mozilla/addons#577]
### Describe the problem and steps to reproduce it:

On the addon-edit page, e.g. https://addons.mozilla.org/en-US/developers/addon/arxiv-title-fixer/edit for [arXiv-title-fixer](https://addons.mozilla.org/en-US/firefox/addon/arxiv-title-fixer/), the `Summary` field unnecessarily HTML-sanitizes the input.

### What happened?

Upon entering `Set titles of papers on arXiv as <title> of the pdf-tabs.`, the summary field gets rendered as: `Set titles of papers on arXiv as <title> of the pdf-tabs.</title>`.

The text seen in the field on editing is the former, though.

### What did you expect to happen?

The rendered summary should be: `Set titles of papers on arXiv as <title> of the pdf-tabs.`

**Comment by eviljeff** [comment]
The sanitizer we use is trying to fix your broken html :)
If you use `&gt;` and `&lt;` instead of `>` and `<` it won't be interpreted as html.
