### ISSUE TITLE
[Review Tools] No Option to Interact with addon

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#578]
**Note:** @eviljeff .... It could be a side-effect of  #576

I have come across a few add-ons with no "review-actions" except "Comment".

Example: `https://reviewers.addons.mozilla.org/editors/review/886233/`

Since all versions are rejected, reviewer is no longer able to reply to the developer. The only visible option is "Comment".

**Comment by wagnerand** [comment]
Yes, this is the same as #576. We recently reverted it and it should land in production this Thursday.
