### ISSUE TITLE
addons website restricts access to firefox 57+ only

### ISSUE THREAD

**Issue by andrixnet** [mozilla/addons#579]
User Agent: Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0
Build ID: 20171107091003

Steps to reproduce:

I am trying to install some addons on a fresh SeaMonkey installation on a new computer.
Addons that I have installed in the past and that I am still using with the same SeaMonkey 2.46 (on other computers).

I know Firefox has made changes to it's addons infrastructure, but this is valid only for Firefox 57+ and addons designed to work with this version.

The version history page for each addon allows access to previous versions of an addon, which may be very useful sometimes. (eg now)

For example I go to: 
https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/versions/?page=1#version-2.8.2 
I use this version on everal SeaMonkey installations. 
Description says :
Works with Firefox for Android 38.0 - 56.*, Firefox 38.0 - 56.*, SeaMonkey 2.35 - *, Thunderbird 38.0 - 54.0 
So this addon is effectively compatible with SeaMonkey 2.46, not just some hack.

Actual results:

When accessing that link with SeaMonkey, instead of the "install addon" button, I am presented with a "get firefox" button.

Expected results:

I do understand the promotional need for moving to Firefox 57+ (though feels more like how Microsoft pushes Windows 10).

But this addon should have been installable on my SeaMonkey.
Furthermore, it is visible only in the "firefox" section of addons website, and since version 2.8.2  is not the latest, it is not visible in the Seamonkey section of the addons website.

Effectively, addons website denies me access to working addons designed for my browser (with the push for FF57+)

I am fine with saying a specific addon version is not compatible with my browser. 
I am not ok with denying access to all versions, even compatbile ones. 

I request a way to access and install legacy addons from SeaMonkey and other compatible browsers. 

Note: I am unable to properly categorize this bugreport due to restrictions for the "component" field. This is a feature bugreport, not a security bugreport.

Initially reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1422339

**Comment by tofumatt** [comment]
Thanks for the report.

The *new* add-ons website does not support Seamonkey or Thunderbird; those browsers will be moving to their own website next year. For now, you can click the link in the footer that says "View Classic Desktop Site" and you can use the old site which includes support for Thunderbird and SeaMonkey.

Hope that helps!

**Comment by andrixnet** [comment]
It does not help. 
On the bottom I see a link "view the new site", while being denied access to those extensions.

![seamonkey1](https://user-images.githubusercontent.com/3382777/33758259-36f476ec-dc06-11e7-9ef2-1568a34c12cf.jpg)
![seamonkey2](https://user-images.githubusercontent.com/3382777/33758260-371d9f9a-dc06-11e7-9800-15100d9c9262.jpg)

**Comment by kumar303** [comment]
> When accessing that link with SeaMonkey, instead of the "install addon" button, I am presented with a "get firefox" button.

I can't reproduce this at https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/versions/?page=1#version-2.8.2 using a SeaMonkey user agent. I see a *download anyway* link which would allow me to install the extension.

What is your exact SeaMonkey user agent string?

This is what I see:

<img width="742" alt="screenshot 2017-12-08 09 10 06" src="https://user-images.githubusercontent.com/55398/33771806-0482b31c-dbf8-11e7-9d72-b81a377f0dd1.png">


Anyway, you can just change to a SeaMonkey URL like https://addons.mozilla.org/en-US/seamonkey/addon/adblock-plus/versions/?page=1#version-2.8.2 and you'll see an active install button:

<img width="735" alt="screenshot 2017-12-08 09 11 46" src="https://user-images.githubusercontent.com/55398/33771809-0885452e-dbf8-11e7-87a7-f252ab6f9b67.png">

**Comment by andrixnet** [comment]
My user agent is: `"Mozilla/5.0 (Windows NT 5.1; rv:49.0) Gecko/20100101 Firefox/49.0 SeaMonkey/2.46"`

My browser is actually SeaMonkey. Have you tested with SeaMonkey, or with Firefox and a UA changer add-on?

**Comment by andrixnet** [comment]
I will try the modified URL and get back to you

**Comment by andrixnet** [comment]
Confirmed: works with modified URL
