### ISSUE TITLE
 Statistics for Always on Top is empty

### ISSUE THREAD

**Issue by vm-devr** [mozilla/addons#580]
Hello guys,
I am developer of Always on Top addon (https://addons.mozilla.org/en-US/firefox/addon/always-on-top)
Lately firefox shows strange usage statistics: for some days it's valid (15-20 thousand users) and for some days it's completely empty. How can that happen?

Attached is a file with usage statistics screenshot
![untitled](https://user-images.githubusercontent.com/34302938/33702548-d03ac674-db2c-11e7-8bf7-7afdca8c094c.png)
 
Thank you!

**Comment by jvillalobos** [comment]
This is due to this bug: https://github.com/mozilla/addons/issues/510

It's an ongoing problem that hasn't been fully resolved yet.

**Comment by vm-devr** [comment]
Hello,

 

Thank you,

 

 

Best regards,

Vasyl Maherka
