### ISSUE TITLE
[Reviewer Tools] Is 'paste' blocked on Reviewers Domain?

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#582]
I have been stuck getting the `document.execCommand('paste')` to work.
I was trying to paste clipboard content to the textarea
`<textarea cols="40" id="id_comments" name="comments" rows="10"></textarea>`

The permission is there.

```
console.log(document.execCommand('copy')); // true
console.log(document.execCommand('paste')); // true
```

However .....

```
console.log(document.queryCommandEnabled('copy')); // true
console.log(document.queryCommandEnabled('paste')); // false
```

So, is 'paste' blocked on Reviewers Domain? Or am I missing something?

**Comment by muffinresearch** [comment]
I don't think there's anything special about the host. Can you do it elsewhere?

See also https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard for additional documentation.

**Comment by erosman** [comment]
I will do some more testing and report back.
