### ISSUE TITLE
"Oops! We had an error."

### ISSUE THREAD

**Issue by robinhood2014** [mozilla/addons#583]
### Describe the problem and steps to reproduce it:
When I attempt to submit an add-on to the Firefox Add-ons website after validation, the website always crashes.
### What happened?
"Oops! We had an error. We'll get to fixing that soon. You can try refreshing the page, or head back to the Add-ons homepage."
### What did you expect to happen?
After clicking "Continue", I expected the site to acknowledge that my add-on had been submitted and was pending review by Mozilla staff.
### Anything else we should know?
Link: https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed
![oops - nightly_001](https://user-images.githubusercontent.com/6971466/33808753-2242dde0-ddb1-11e7-9ea6-38fa8f794de7.png)
[musixmatch.zip](https://github.com/mozilla/addons/files/1546016/musixmatch.zip)

**Comment by jvillalobos** [comment]
I tried a few things with that file and it appeared to work okay for me. Do you still see this error? If so, can you specify the steps that you took for submitting it?

**Comment by muffinresearch** [comment]
Please re-open this issue if you have more info.

**Comment by robinhood2014** [comment]
Here is a ZIP file containing the steps I took to reproduce the error, created using the Windows Steps Recorder.
[steps.zip](https://github.com/mozilla/addons/files/1701513/steps.zip)
