### ISSUE TITLE
Sort by trending seems incorrect

### ISSUE THREAD

**Issue by Lusito** [mozilla/addons#584]
### Describe the problem and steps to reproduce it:
I wanted to see if my extension was trending here (without entering the name, just stepping through pages):
https://addons.mozilla.org/en-US/firefox/search/?sort=hotness&type=extension

So I stepped through a lot of pages, until I noticed something strange.

### What happened?

Some add-ons which only had 1 (one) or 0 users, where trending more than my add-on, which has over 200 users.

### What did you expect to happen?

I expected trending to be based on the growth of the add-ons user-count. Or download count or whatever, but it seems like a bug, that add-ons with very few users are trending more than add-ons that actually have users.

### Anything else we should know?
An example of a 1-user add-on which appeared on page 51: https://addons.mozilla.org/en-US/firefox/addon/kpd200_vk_stat/

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file an issue. We're currently looking into this already. You can subscribe to this issue for updates: https://github.com/mozilla/addons-server/issues/7088
