### ISSUE TITLE
Changing the case of an addon URL doesn't return an error page.

### ISSUE THREAD

**Issue by superk2001** [mozilla/addons#586]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Go to an addon location (https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/), but change the case of the name (https://addons.mozilla.org/en-US/firefox/addon/snapLinksplus/) and you don't get an error page, just a blank screen.

### What happened?

You don't get an error page, just a blank screen.

### What did you expect to happen?

Get an error page, like with (https://addons.mozilla.org/en-US/firefox/addon/sadmknmsadlksa/)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Working: https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/
Working: https://addons.mozilla.org/en-US/firefox/addon/sadmknmsadlksa/
Not working: https://addons.mozilla.org/en-US/firefox/addon/snapLinksplus/

**Comment by diox** [comment]
cc @kumar303 for input. It used to work on the legacy frontend - maybe a simple redirect would be enough.

**Comment by muffinresearch** [comment]
Moved to https://github.com/mozilla/addons-frontend/issues/4271
