### ISSUE TITLE
Addon support email shows in plain text - spammer's paradise!

### ISSUE THREAD

**Issue by vanowm** [mozilla/addons#588]
I don't know who's brilliant idea it was to remove the javascript requirement for accessing support email, but that person is responsible for all the spam we are hammering with because of that!

Before, when you open an addon page, the email address was some what hidden, the javascript would "reveal" it, but now it's just there in the link mailto:blah@example.com

We are almost in 2018 - this is totally unacceptable, a captcha is a must or at least bring back the javascript requirement, which seemed to work fine.

P.S.
I'm 100% the spam I'm getting is because of AMO, all my email addresses are unique per addon and the only places they are publicly accessible is via my addon's pages on AMO and from addons themselves, where they are "encrypted" and not visible from within source. It takes just couple of weeks for spammers get it after publishing it on AMO.

**Comment by tofumatt** [comment]
Captchas aren't the best experience and when a user is looking for support I dislike making them jump through hoops. That said we didn't think the old JS obfuscation was doing much to deter spammers–thanks for letting us know we were incorrect. If there was a spike in spam since early November when the new site launched it seems we should revisit the quite mild anti-spam measures we had before.

**Comment by tofumatt** [comment]
Gonna move this to the add-ons frontend repo: https://github.com/mozilla/addons-frontend/issues/4082

**Comment by tofumatt** [comment]
No worries, thanks for the apology though :-)

I think what we had before isn’t too hard to implement. Just so you know we aren’t planning on doing a lot of deploys over the holidays as a lot of ops aren’t around for the push, so even if we fix this issue soon it might not get into production for a few weeks–sorry about that. But keep an eye on this issue and we’ll try to get to it as soon as we can. 

- Matt (Sent from mobile)
