### ISSUE TITLE
Post-Review: Higher Weighting for Abuse Reported by Staff

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#589]
This is more of a suggestion but if it is possible, it should improve the Post-Review process.

Subsequent to Post-Review, AMO has been getting a lot of spam. Personally, I always make an Abuse Report marking the uploader as a Spam uploader.

I have gathered that such reports affect the weighting of the addon. I would suggest a higher rating for the staff/reviewer reports to make them stand out even more.

**Comment by diox** [comment]
@jvillalobos for input

**Comment by jvillalobos** [comment]
I look at abuse reports almost every day and clear all spam that I see reported (thanks for reporting, it's super useful). Content reviewers are also doing a good job cleaning stuff up quickly, so I don't think changing the weight will do much in accelerating spam processing. There are some other solutions coming down the pipeline to stop spam before it's posted, which should more effective.
