### ISSUE TITLE
addons.mozilla.org policy should deny extensions that serve as countdown timers to one-time events

### ISSUE THREAD

**Issue by jawz101** [mozilla/addons#592]
addons.mozilla.org policy should deny extensions that serve as countdown timers to one-time events.  There is no reason to clutter the store with them.

Ex: "New Year's Countdown 2017" only serves for one event.  "New Year's Countdown" repeats every year.

**Comment by jvillalobos** [comment]
Some users might want to have add-ons like this, and the add-on in your example makes it very clear what it's meant to do. As long as users aren't being mislead, it should be okay to have them on AMO.
