### ISSUE TITLE
Wrong link on Dictionaries and Language packs page

### ISSUE THREAD

**Issue by Luke-Baker** [mozilla/addons#594]
1. https://addons.mozilla.org/firefox/language-tools/
2. Scroll down to English (British). In the Language Packs column, you find [IE](https://addons.mozilla.org/firefox/addon/ie/), an obsolete add-on that has nothing to do with languages.
3. Scroll down to Telugu తెలుగు. In the Dictionaries column, there's a . after Telugu Spell Checker. There's no period after any other dictionary or language pack.

**Comment by jvillalobos** [comment]
I removed IE from the language tools page. The period is part of the name of the Telugu Spell Checker, so that's up to the developer to change if they choose to.

**Comment by vcarciu** [comment]
Verified as fixed : 
![ie](https://user-images.githubusercontent.com/1583842/34521014-238310da-f094-11e7-9090-2be6c87c8d9a.gif)
