### ISSUE TITLE
FormData iterators not iterable using `for ... of` in content scripts

### ISSUE THREAD

**Issue by md384** [mozilla/addons#595]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

In content scripts, iterator objects returned from FormData methods (such as `FormData.entries()`) throw a TypeError (in addon dev tools) when trying to iterate over them using `for ... of` (example in [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/FormData/entries)):

`TypeError: fd.entries(...) is not iterable`

However, you can iterate through the iterator using its `next()` method.

It is also not a problem in background scripts. The below snippet works as expected in a background script.

### Anything else we should know?

This script demonstrates the bug if put in a content script.

```
// Create a test FormData object
var formData = new FormData();
formData.append('key1', 'value1');
formData.append('key2', 'value2');

// Display the key/value pairs
console.log('Content script:');
for(var pair of formData.entries()) {
   console.log(pair[0], pair[1]);
}


// Using .next() method on the iterator works
console.log('Content script without iterators:');
const entries = formData.entries();
let entryObj = entries.next();

while (!entryObj.done) {
    const [key, value] = entryObj.value;
    console.log(key, value);
    entryObj = entries.next();
}
```

**Comment by andymckay** [comment]
Thank you for filing the bug. We normally track issues in Firefox in Bugzilla. This one sounds very similar to this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1414602. If you agree we can close and duplicate to that bug.

**Comment by md384** [comment]
@andymckay I believe that this is the same problem as the one you linked to.

**Comment by andymckay** [comment]
Thanks, closing this one then. If you want more info or to help out, please follow that bug.
