### ISSUE TITLE
Adobe Flash Error 

### ISSUE THREAD

**Issue by sonicbooming** [mozilla/addons#596]
### Describe the problem and steps to reproduce it:
Tried to load up a video on Crunchyroll. It gave me an adobe flash error message. I've reinstalled Flash and closed and re-opened the browser. Error continues to persist. 

I also unchecked the "block dangerous and intrusive flash content" box under the add-ons manager options for Shockwave Flash 28.0.0.126
### What happened?
It continues to give me an error saying it has failed. 
![error](https://user-images.githubusercontent.com/33769552/34228154-ad5b0ecc-e59d-11e7-919f-ad7f2a445fa3.png)

### What did you expect to happen?
For it to load properly and allow me to watch the video. 

### Anything else we should know?
http://www.crunchyroll.com/boruto-naruto-next-generations/episode-38-formation-of-the-three-man-squad-753509

**Comment by jvillalobos** [comment]
For general support, please go to https://support.mozilla.org

If you think you found a bug in Firefox, you can file it here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Untriaged
