### ISSUE TITLE
Trying to update Quantum Lights theme

### ISSUE THREAD

**Issue by mart3ll** [mozilla/addons#597]
### Describe the problem and steps to reproduce it:
Upon submission, AMO fails to parse manifest.json, says it isn't available, but it is.

### What happened?
AMO fails to parse manifest.json

### What did you expect to happen?
AMO approving new version of addon. I had previously submitted as 1.3, but that was rejected thanks to 1.25 being "larger" than 1.3 in versioning. This new update has been set to 2.0

### Anything else we should know?
[quantumlights.zip](https://github.com/mozilla/addons/files/1579398/quantumlights.zip)

**Comment by andymckay** [comment]
Thats not a great error message, but your JSON isn't valid. Running `web-ext lint`, I get:

```
JSON_INVALID   Your JSON   Line 12: Unexpected   manifest.j…                
               is not      token ILLEGAL         son                        
               valid.  
```

Which looks like:

```
  "version": “2.0”,
```
Those are some funky double quotes that won't work in JSON and not the standard ". Correct that and it should work ok.

**Comment by andymckay** [comment]
Oh and there's one on line 15 as well. `web-ext lint` is your friend.

**Comment by muffinresearch** [comment]
For reference wrt to improving the messaging here's what the validation looks like:

<img width="1003" alt="upload_add-on____developer_hub____add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/34581924-171b71ce-f18a-11e7-8e1e-afe6fe5fb0a4.png">

**Comment by andymckay** [comment]
I don't think there's much else we can do on this bug, unless @mart3ll reports that its something else.
