### ISSUE TITLE
incorrect word 

### ISSUE THREAD

**Issue by myporn** [mozilla/addons#598]
### Describe the problem and steps to reproduce it:
just a incorrect word..

### What happened?
Don´t exist "aloradas" in spanish. this is a incorrect word.

### What did you expect to happen?
show "Extensiones más valoradas"
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/es/firefox/extensions/

![imagen](https://user-images.githubusercontent.com/14077836/34307314-234432f6-e70d-11e7-818b-5f9504203f4c.png)

https://addons.mozilla.org/es/firefox/extensions/

![imagen](https://user-images.githubusercontent.com/14077836/34307460-d7206c7c-e70d-11e7-891d-fefe1372d01f.png)

see you ;)

**Comment by andymckay** [comment]
Duplicate of #601
