### ISSUE TITLE
Please provide a link explaining permissions

### ISSUE THREAD

**Issue by noloader** [mozilla/addons#599]
I'm trying to determine if I should install the [Firefox MathML](https://addons.mozilla.org/en-US/firefox/addon/native-mathml/) addon. The plugin is asking for **_"access your data for all websites"_**.

The request seems overly broad to me, but I want to ensure I understand what *"access your data for all websites"* means. For example, does it include form data like a username and password; and does it include outgoing data like found in a basicAuth request.

In the image below there is no way to click on a link and find out what **_"access your data for all websites"_** actually means. It would be nice of the text if **_"access your data for all websites"_** was a link, and clicking it took me to some information explaining the privilege.

And surprisingly, Google search for **_"access your data for all websites"_** (with the quotes) does ***not*** provide a Mozilla support page explaining the privilege. The first hit is a complaint on Reddit.

-----

![mozilla-data-access](https://user-images.githubusercontent.com/3538226/34311556-391a33a4-e72c-11e7-8268-313b3c9dd5d2.png)

**Comment by kumar303** [comment]
Hi. Sorry about the confusion. We are already working on this feature but it's not finished yet. You can follow this issue to keep up with the progress: https://github.com/mozilla/addons-frontend/issues/2757
