### ISSUE TITLE
Release Notes not always displayed entirely for addon

### ISSUE THREAD

**Issue by cedricium** [mozilla/addons#600]
### Describe the problem and steps to reproduce it:
When navigating to one of my addons from outside of AMO (say from Google or GitHub for example), the Release Notes section does not show the entirety of the note. However, when navigating from within AMO and returning to my addon, the entire Release Notes will be displayed.

**Steps to Reproduce:**
1. Click on the following link: https://addons.mozilla.org/en-US/firefox/addon/medium-bookmarklets/
2. Scroll down and locate the Release Notes section.
3. Note that only "New in v1.1.0:" is displayed and there is no button to "Read More".
4. Click on the "RapidTabOpener" addon below the Release Notes section.
5. Hit the back button to go back to the Medium Bookmarklets addon; locate the Release Notes section.
6. Note that more text is displayed and there is a "Read More" button.

### What happened?

Only some text appears on the initial visit to AMO:
![screen shot 2017-12-23 at 2 36 16 pm](https://user-images.githubusercontent.com/16343560/34323144-6f112b06-e7f0-11e7-8880-212f6ec0abce.png)

### What did you expect to happen?

Full text should appear all the time:
![screen shot 2017-12-23 at 2 44 35 pm](https://user-images.githubusercontent.com/16343560/34323145-74f1d368-e7f0-11e7-907d-9069d59db271.png)

**Comment by jvillalobos** [comment]
Possibly related to https://github.com/mozilla/addons-frontend/issues/4063

**Comment by muffinresearch** [comment]
The fix for this should be going out today.

**Comment by madalincm** [comment]
Verified as fixed in FF57(Win7) in amo-dev using this add-on: https://addons-dev.allizom.org/en-US/firefox/addon/test-of-today/
The release notes are displayed when accessing the add-on from a direct link.
Postfix screencast: 
![releasenotes](https://user-images.githubusercontent.com/15685441/35109238-75f094a0-fc7e-11e7-90ae-36eea9ce0525.gif)
