### ISSUE TITLE
CDN blocked by Norton

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#603]
We got a report that Norton blocks our CDN:

 https://safeweb.norton.com/report/show?url=addons.cdn.mozilla.net

"They are blocking the entire domain because of a single AddOn:"
https://addons.cdn.mozilla.net/user-media/addons/893812/open_with_adobe_pdf_reader-2.0.0-an+fx.xpi

**Comment by jvillalobos** [comment]
That version was taken down (due to a coin miner), but the add-on still exists.
