### ISSUE TITLE
https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

### ISSUE THREAD

**Issue by jfbourdeau** [mozilla/addons#604]
### Describe the problem and steps to reproduce it:
Just opening several tabs in FireFox on Linux mint 18.3 with the new MultiAccount Containers and use it 15 minutes

### What happened?
Browser is in a loop like trying to open the page I am clickng

### What did you expect to happen?
I restart firefox and everything is ok for a while

### Anything else we should know?
Was not having that problem without the MultiAccount Containes AddOn
https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

**Comment by wagnerand** [comment]
This bug tracker is related to the addons server component of addons.mozilla.org. If your issue relates to an add-on then please look for a way to request support from the add-on author.
