### ISSUE TITLE
Review Communication attached to the wrong version if version was deleted

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#605]
Transferred from: #576

The above issue which was fixed in case of the **rejected** version seems to still happen in case of **deleted** versions.

The reviewer reply is attached to the last undeleted version.

Example:
`https://reviewers.addons.mozilla.org/editors/review/899500/`

Replies are attached to the previous version.

An Example of the Situation:
Add-on dev uploads v1
Add-on dev uploads v2
Add-on dev uploads v3
Add-on dev uploads v4
Add-on dev uploads v5
Add-on dev uploads v6

Add-on dev deletes v4
Add-on dev deletes v5
Add-on dev deletes v6

Developer sends an email reply with some query. It is attached to v6 ie the last version.
Now, any Info request, Reviewer reply (or comment? have not tested comment) will be attach to the last undeleted version which would be v3 in this example.

While it is not a major issue, the continuity and order (question & answer) is lost.

**Comment by wagnerand** [comment]
Can you please edit your issue and provide a proper description along with steps to reproduce? Thank you!

The reason developers are asking to file new bugs is to declutter them and have one single item everyone (Product management, engineering, QA) needs to look at.
