### ISSUE TITLE
Make the add-on id optional

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#61]
...and put it in a separate file like mozilla.json. Overview: https://wiki.mozilla.org/WebExtensions/Applications.

**Comment by krupa** [comment]
Currently, uploading a Chrome extension without any alterations fails with an "unexpected error".

**Comment by EnTeQuAk** [comment]
Just a note once all this goes live: update https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications

**Comment by andymckay** [comment]
I think this is all done now and we can close it.
