### ISSUE TITLE
Firefox support for Trezor/myEtherWallet is an absolute neccessity .. please do it soon 

### ISSUE THREAD

**Issue by CoinEDD** [mozilla/addons#612]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by CoinEDD** [comment]
I absolutely refuse to use "Chrome". Unfortunately it's the ONLY way I can use my Trezor with MyEtherWallet as Firefox does not yet have this feature. I will wait until Firefox impliments it even though it will cost me bonus coin from the upcoming ETH fork.  See how LOYAL I am.  Please tend to this situation as soon as possible.  .. .. .. Thanks for your time Eddie T

**Comment by EnTeQuAk** [comment]
This bug tracker is not for Firefox but primarily for addons.mozilla.org - backend and frontend. Please use bugzilla.mozilla.org for Firefox related requests.

On a personal note, I don't see how Trezor is connecting exactly to MyEtherWallet so maybe it also makes sense to send them a note in case things don't work.
