### ISSUE TITLE
Support linking to individual user reviews

### ISSUE THREAD

**Issue by h3298** [mozilla/addons#614]
Currently you can only reference an extensions review page, i.e.

https://addons.mozilla.org/en-US/firefox/addon/ **{extension-name}** /reviews/

Should support linking to individual reviews ; its helpful when discussing feature requests in other forums.
(manual quoting is not sufficient because the review could be edited & updated with new information)

**Comment by jvillalobos** [comment]
Closing as duplicate of https://github.com/mozilla/addons-frontend/issues/2771
