### ISSUE TITLE
External source tracking is not working

### ISSUE THREAD

**Issue by xmcp** [mozilla/addons#615]
### Describe the problem and steps to reproduce it:
1. Open the add-on's details page with a tracking parameter, like: `https://addons.mozilla.org/en-US/firefox/addon/example?src=external-example`.
2. Open the "Downloads > by Source" statistics page (`https://addons.mozilla.org/en-US/firefox/addon/example/statistics/downloads/sources/`) and see the table.

### What happened?

The pageview in the first step is counted in "Detail Page" category.

### What did you expect to happen?

It should be counted in a column called `external-example`.

### Anything else we should know?
![image](https://user-images.githubusercontent.com/6646473/34776395-b3398cb4-f651-11e7-85b8-d6895bd49995.png)

**Comment by kumar303** [comment]
Thanks for reporting this issue.

@diox do you know how this worked on the old site? I can't seem to find any relevant code related to *external*. I'm suspecting that we broke this somehow in the frontend redesign.

**Comment by diox** [comment]
I'm suspecting the same thing. I don't know this code very well, but I suspect we just pass down any value from the `src` query parameter down to the download links. I'll investigate.

**Comment by diox** [comment]
Investigation results: we used to simply propagate *any* `src` query parameter down to the download links, escaping them to make sure they are URL safe (hence the warning about the restriction that you can see in that screenshot). So yeah, that should be done in addons-frontend as well.

**Comment by kumar303** [comment]
> The pageview in the first step is counted in "Detail Page" category.
> ...
> It should be counted in a column called external-example.

@xmcp upon re-reading your report, I'm confused by "page view." I don't see page views anywhere on our stats page, only daily users and downloads. Could you provide a screenshot of where you see page view stats?


@diox I'm not worried about downloads because we have been [passing `src` on to download URLs](https://github.com/mozilla/addons-frontend/blob/6447fa8b0fbea6c14ffdeb879e059b8ab3e0ce35/src/core/installAddon.js#L274) for a while now. It would be good to verify that `src` is propagated all the way through the app though.

**Comment by xmcp** [comment]
@kumar303 Sorry, it should be the DOWNLOAD count. My mistake.

But I do see a dramatical decline of the `external`-labeled counts since the website redisign.

Here is a part of the exported file.

![image](https://user-images.githubusercontent.com/6646473/34784513-6aefe2d8-f669-11e7-9486-bed6b2c207ef.png)

**Comment by kumar303** [comment]
> But I do see a dramatical decline of the external-labeled counts since the website redisign.

Hmm. Since there are *some* numbers it appears to be working. Maybe we aren't propagating `src` in enough components.

**Comment by muffinresearch** [comment]
@kumar303 if you visit a details page with a src query param e.g: https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/?src=external-test what is sent when installing the add-on is `src=dp-btn-primary` whereas I think the expectation is that it would be `src=external-test`. (You can see this when inspecting network in the browser console)

Looking into the code, as you noted it does look like the `src` param is extracted from the URL here: https://github.com/mozilla/addons-frontend/blob/6447fa8b0fbea6c14ffdeb879e059b8ab3e0ce35/src/core/installAddon.js#L274

However, it looks like the install function overrides that `src` here: https://github.com/mozilla/addons-frontend/blob/6c7cc717af0905f310c96f0d7b19eb0952a9dfbd/src/core/addonManager.js#L52

See this line for where this is called: https://github.com/mozilla/addons-frontend/blob/6c7cc717af0905f310c96f0d7b19eb0952a9dfbd/src/core/installAddon.js#L404 - as you can see we get the url via `findInstallURL` which will add a src, however the `_addonManager.install()` then overrides it.

**Comment by muffinresearch** [comment]
Moved to https://github.com/mozilla/addons-frontend/issues/4270
