### ISSUE TITLE
Allow upload of source code (and release/reviewer notes) using the API

### ISSUE THREAD

**Issue by ElectronicManuel** [mozilla/addons#6158]
When uploading an addon using the API (https://addons-server.readthedocs.io/en/latest/topics/api/signing.html) there is no way to upload the source files automatically.

Steps:
1. push new version of the addon to repo
2. automated deployment deploys version to the mozilla store using the api
3. I navigate to the developer hub and upload the sources manually

It would be nice to have an api for uploading the source files in order to reduce manual intervention.

**Comment by karlicoss** [comment]
Any chance we can get this reopened? I went through the docs, and doesn't look like source code or reviewer notes are supported?

**Comment by diox** [comment]
Both are supported in the API and documented (https://mozilla.github.io/addons-server/topics/api/addons.html#version-create). That being said you did well to file an issue to improve our docs around it.

**Comment by birtles** [comment]
@karlicoss There's a GitHub action for uploading to AMO with example code at: https://github.com/birchill/amo-upload/blob/ab657f9e64908ffda49bd3c4bfc1e8bc9fe6d243/index.js#L154-L162

**Comment by eviljeff** [comment]
@karlicoss I've not investigated but a common gotcha is declaring version level properties (metadata under version-create rather than addon-create) at the top add-on level instead.  i.e. it should be this: 
```json
{
  "version": {
    "approval_notes": "foo"
  }
}
```

**Comment by karlicoss** [comment]
Thanks, putting it under `version` worked!
Unfortunately, I am having a different issue -- `JSON.parse` doesn't support multiline strings (e.g. like this)
```
{
  "version": {
    "approval_notes": "
  line 1
  line 2
    "
  }
}
```

, so I'm getting an error here https://github.com/mozilla/web-ext/blob/3e4faa26d4f8ad95cbdf5da75ca9b88dbcc20d9d/src/cmd/sign.js#L96

I could inline `\n` in the string directly, but then editing approval notes would be super painful. I suppose I could generate the json file from code to prevent this, but wondering if there is something I'm missing.

**Comment by willdurand** [comment]
I think you'll have to inject a stringified representation of your approval notes.
