### ISSUE TITLE
[Reviewer Tools] Not Allowed on /review-content/ for Add-on Reviewers

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#617]
> Oops! Not allowed.
> 
> You tried to do something that you weren't allowed to.

Add-on Reviewers get **Not allowed** on `/review-content/` pages which means having to manually edit the URL to get to the review page.

Example:
```
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/30-%D0%BE%D1%82-aliexpress-%D0%BA%D1%8D%D1%88%D0%B1%D1%8D%D0%BA
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/assamese-fonts-package
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/bengali-fonts-package
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/daz-deals
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/devanagari-fonts-package
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/easy-google-translate
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/gurmukhi-fonts-package
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/kannada-fonts-package
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/malayalam-fonts-package
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/marathi-fonts-package
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/new-io-games
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/oriya-fonts-package
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/script-safe
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/tamil-fonts-package
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/telugu-fonts-package
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/tumblrvideodownloader
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/unblock-youku-firefox
```

**Comment by diox** [comment]
I don't understand. Where did you get the link to `/review-content/` ?

**Comment by erosman** [comment]
> I don't understand. Where did you get the link to /review-content/ ?

`https://reviewers.addons.mozilla.org/en-US/reviewers/reviewlog/`

**Comment by diox** [comment]
I don't see any link pointing to `/review-content/` on this page. There are link pointing to the individual content review pages, but they all work... If you are editing the URL in your url bar... don't.

**Comment by jvillalobos** [comment]
I think the issue is that the review log shows content events linking to content review pages, but some reviewers won't have access to those pages (content and code reviewers are separate groups). I can see a couple of solutions for this, but I don't think they are worth pursuing until we start working on the new reviewer pages.

**Comment by erosman** [comment]
> I don't see any link pointing to /review-content/ on this page. There are link pointing to the individual content review pages, but they all work... If you are editing the URL in your url bar... don't.


They may work for you but they don't work for Add-on Reviewers.
In order to get to the Review page, we have to change ` /review-content/`  to  `/review/` 

```
<td>
  <a href="/en-US/firefox/addon/new-tab-here/">New Tab Here</a>1.0.0
  <a href="/en-US/reviewers/review-content/new-tab-here">Content approved</a>
</td>
```

**Comment by rctgamer3** [comment]
Wouldn't it be easier to put a redirect to /review/ in place if it detects that a user isn't part of the content reviewrs group but is in the regular reviewers group? Had some review-content URLs sent to me, had to adjust them each time otherwise i would get the "Not Allowed" error.
