### ISSUE TITLE
Add-on "Added to Firefox" indicator missing after an add-on has been installed

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/addons#618]
### Describe the problem and steps to reproduce it:
1. Go to addons.mozilla.org
2. Install any add-on
3. Click on "Add to Firefox"
Once any Add-on is installed, the "Add to Firefox" button should change to "Added to Firefox" or some other message, to indicate the add-on is installed.

### What happened?
The "Add to Firefox" button remains unchanged, even after the add-on has been installed.

### What did you expect to happen?
The "Add to Firefox" button should change to indicate that the add-on has been installed.
And if the add-on is already installed, the button should reflect the same
The button should be disabled once the text is changed and 2 more buttons, "Remove add-on", "Reinstall Add-on" need to be added.

### Anything else we should know?
![screenshot 3](https://user-images.githubusercontent.com/8105936/34794136-b6431b56-f673-11e7-91f7-fd8e3ba4edbe.png)

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file an issue about this. We are aware of it but haven't had the time to fix it yet. You can track the progress in this issue: https://github.com/mozilla/addons-frontend/issues/3954
