### ISSUE TITLE
[Reviewer Tools] Occasional Re-Weighting is required

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#619]
Due to issues, Policy changes and updates, there are add-ons with low weights (e.g. 0-20) that should have had a much higher weighting.

A system to batch re-weight them while they are on the queue would improve the Post Review process and reduce the risk of undesired code getting overlooked.

**Comment by wagnerand** [comment]
Can you give a few examples of things you have seen that should have a higher weight? Thank you!

**Comment by erosman** [comment]
As a very recent issue #616

For older issues, 
#589 
https://github.com/mozilla/addons-server/issues/6821
https://github.com/mozilla/addons-server/issues/6930

**Comment by diox** [comment]
None of these issues are fixed at the moment. We'll definitely include a command to re-weight versions that have not been confirmed yet when we fix them.

**Comment by diox** [comment]
I'll add such a command in #616
