### ISSUE TITLE
Sort by "Name" in search

### ISSUE THREAD

**Issue by yoasif** [mozilla/addons#620]
### Describe the problem and steps to reproduce it:

I cannot sort by name when searching for things on addons.mozilla.org

### What happened?

1. I went to search for something, eg: https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=app
2. Click on "Sort by" dropdown

### What did you expect to happen?

I expected to see a "Name" entry so that I can sort by name. 

### Anything else we should know?

Seen on Twitter: https://twitter.com/niblick_iii/status/952540269139939328

**Comment by diox** [comment]
For some reason (it's probably my fault - I vaguely remember insisting that it wasn't super useful to sort search results by name) we never added sorting by name in the API, and therefore not in the frontend either, but it's easy to do. 

There will be one limitation though: the field we have in the index to sort uses a single translation (which should be the english one), so it might not be perfectly ordered depending on the language you're looking at and the translations for the add-ons in the results. Generally the name isn't translated, but sometimes it is...

**Comment by jvillalobos** [comment]
It's a bit of an odd sort option. If you're looking for something by name or partial name, you can type it in the search box to filter the results, so it seems unnecessary to have that  sort option. And going through a long list alphabetically seems as arbitrary as any other order.

Looking at the Twitter thread, it seems to have more to do with the type filters for atypical add-on types. That's a problem for sure, but we plan to remove those types eventually.

**Comment by diox** [comment]
We've addressed the use-case mentioned in the last comment by trying to fix exact name matching, so I'm closing this issue.
