### ISSUE TITLE
Fake information about add-ons on their AMO pages

### ISSUE THREAD

**Issue by amocorrect** [mozilla/addons#621]
Who is responsible for ensuring that correct information about add-ons is provided by authors on AMO?

The AMO page for Disconnect https://addons.mozilla.org/en-US/firefox/addon/disconnect/1 falsely states the software license as GNU GPL 3.0. It in fact also includes two proprietary third-party software products, as stated on the add-on’s github page (https://github.com/disconnectme/disconnect3). Claiming that the add-on is licensed exclusively under GNU GPL 3.0 is highly deceptive, dishonest and inaccurate.

I've now reported this to the authors, to amo-admins@mozilla.org, via the form on its AMO page and on https://discourse.mozilla.org/t/information-about-add-on-stated-incorrectly-by-authors-on-amo/23377. All with no effect, the mistake remains and this isn't just some obscure unknown add-on, but one of the most prominent ones, featured on the front page of AMO.  Can any add-on developer just claim anything they want about their add-ons, is there really such poor oversight and control? Is there anywhere at all where fake claims like this can be reported and subsequently also dealt with?

**Comment by muffinresearch** [comment]
I've checked with the review team here and licensing checks are not something that are carried out. The responsibility of correctly licensing the add-on is with the original developer. The best course of action is to file an issue with the developer along with the details of what you expect to be changed.
