### ISSUE TITLE
A lot of youtube videos say server not compatible

### ISSUE THREAD

**Issue by patoneal** [mozilla/addons#623]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
not compatible

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by tofumatt** [comment]
Closing due to lack of information.

Please add information to your issue including the error you encountered, a URL (if applicable), and steps to reproduce.

**Comment by patoneal** [comment]
a lot of news feeds have videos that wont play
