### ISSUE TITLE
Version info on update page

### ISSUE THREAD

**Issue by bdcomp** [mozilla/addons#624]
### Describe the problem and steps to reproduce it:
There is no version info on update page (Firefox -> "Check for Updates").
If the user is on beta channel and there is a new beta version, as well new release version, it's not clear that version is prompted as an update.

### What happened?
An update suggested without version info.

### What did you expect to happen?
An update suggested with version info.

### Anything else we should know?
A real example of this issue:
https://github.com/ssborbis/ContextSearch-web-ext/issues/12#issuecomment-358216219

**Comment by tofumatt** [comment]
I think this might be more of a browser issue than an issue with the add-ons site (which this issue tracker is for), but I think we can sort of solve it. I think there's a want to stop using the beta/development channel entirely, right @jvillalobos?

**Comment by bdcomp** [comment]
Just filled https://bugzilla.mozilla.org/show_bug.cgi?id=1431136

**Comment by tofumatt** [comment]
Cheers! I'll close this out then as I don't think there's anything to do on the website side of things for now.

**Comment by jvillalobos** [comment]
> I think there's a want to stop using the beta/development channel entirely, right @jvillalobos?

Yes, that's https://github.com/mozilla/addons-server/issues/7163
