### ISSUE TITLE
[Reviewer Tools] 403 Forbidden on Download ***.dat

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#625]
Example:
`https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/742449/file/data/assets/geoip-country.dat#top`

```
Download geoip-country.dat
File size is over the limit of 1.0 MB.
Version: 1.1.2 • Size: 1.4 MiB • SHA256 hash: c93745c9819fb522f36b84c7c30028351a9c39cdd78e6cfb19876ab0e6fc1559 • Mimetype: application/octet-stream
```

result of clicking` Download geoip-country.dat`

> 403 Forbidden

We can neither view it in the review tools, nor download it to view it.
It happens in case of some other file types as well (as previously mentioned #445)

**Comment by muffinresearch** [comment]
@erosman is there a workaround for this by downloading the full xpi? 

Please can you provide the full steps of to get to the file link?

**Comment by erosman** [comment]
> is there a workaround for this by downloading the full xpi?

Of course. Downloading the full XPI is always available, however, not optimal.

There are some really large add-ons with images etc and downloading the entire add-on just to view a single file doesn't seems to be the most efficient course of action.

**Comment by diox** [comment]
It's an ops issue I suppose? @philipcristiano any ideas?

**Comment by philipcristiano** [comment]
The nginx config seems to send these requests to addons-server to handle. I'm not familiar with the codebase enough without dedicating some time to track down the relevant handling of this. It could be that the filesystem permissions for the files propagate up through the app. Does the app have handling for specific files that only let the XPI through?

**Comment by diox** [comment]
Sorry I  thought it was a direct download link but it's done, it's inside the file viewer. And it has nothing to do with the extension, it's just that the file is too large to display inline. That's by design.

**Comment by erosman** [comment]
@diox @muffinresearch 

https://addons.cdn.mozilla.net/en-US/firefox/files/browse/982742/file-serve/data/cedict_ts.u8?token=3652c64c-64e0-4142-a510-178c5fbcc7c5
https://addons.cdn.mozilla.net/en-US/firefox/files/browse/982742/file-serve/data/cedict.idx?token=ba1c459b-5f4e-47d5-9006-bd9144a837ae

Why cant the data (which is text data) be accessed via browser eg. _Download cedict.idx_ & _Download cedict_ts.u8_?
Downloading the whole XPI every time is impractical just to view one file.

Note: These are NOT binary files

example of _edict.idx_
```
21三体综合症,1037
21三體綜合症,1037
502胶,1121
502膠,1121
PO文,1175
□,1232
○,1386
```

example of _cedict_ts.u8_
```
㐄 㐄 [kua4] /component in Chinese characters, mirror image of 夂[zhi3]/
㐅 㐅 [wu3] /archaic variant of 五[wu3]/
㐆 㐆 [yin3] /component in Chinese character 殷[yin1]/
㐌 㐌 [ta1] /variant of 它[ta1]/
㐖 㐖 [Ye4] /see 㐖毒[Ye4 du2]/
```
