### ISSUE TITLE
[Reviewer Tools] Wrong link for View Listing

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#626]
It is quite a minor issue but nonetheless the **View Listing** links points to the wrong location (domain)

Example:
`https://reviewers.addons.mozilla.org/editors/review/5890/`

```
<strong>Actions</strong>
<ul id="actions-addon">
  <li><a href="/en-US/firefox/addon/tree-style-tab/">View Listing</a></li>
</ul>
```

**Comment by diox** [comment]
It's intended, we can't fix all existing links, especially as some are in activity logs etc. It redirects to the right domain.
