### ISSUE TITLE
Paging on user's profile doesn't work

### ISSUE THREAD

**Issue by TheAdnan** [mozilla/addons#628]
When I open my profile page ([https://addons.mozilla.org/en-US/firefox/user/theadnan/)](https://addons.mozilla.org/en-US/firefox/user/theadnan/)), I have 11 addons listed on 3 pages, but there are only 10 addons showing (one addon that was showing on the second page was shown again on the last page).

Here are the screenshots: 

**_Second page_**
![screenshot-1](https://i.imgur.com/U3dyqWe.png)

**_Third page_**
![screenshot-2](https://i.imgur.com/l2RPk6C.png)

**Comment by jvillalobos** [comment]
User pages are being rewritten for the new front-end here: https://github.com/mozilla/addons-frontend/issues/2781. We won't be fixing bugs in the old front-end unless they are critical, so I suggest you follow the progress of the new pages and try to reproduce the problem when the new pages launch.
