### ISSUE TITLE
Update documentation on acceptable version format for addons

### ISSUE THREAD

**Issue by haqer1** [mozilla/addons#629]
### Describe the problem and steps to reproduce it:
Versions like 55.0.3t52.3.0 used to be acceptable.

### What happened?
Now they aren't.

### What did you expect to happen?
There's a need for updated documentation, perhaps on a page like the following:
https://developer.mozilla.org/en-US/docs/Mozilla/Toolkit_version_format

### Anything else we should know?
The closest i could get to the previous version format is:
58.0t52

**Comment by muffinresearch** [comment]
The documentation for versions in web extensions is here https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/version

This also references the doc you link above.

Can you add details on what you think is missing from that?

**Comment by haqer1** [comment]
What's missing is that the format now is more restrictive than what
https://developer.mozilla.org/en-US/docs/Mozilla/Toolkit_version_format
suggests.
E.g., versions like 55.0.3t52.3.0 used to be acceptable, but now they aren't. In particular, it seems after a alphabetic character(s) only digits are allowed (dots aren't). The sentences below don't reflect this reality:
"A version string consists of one or more version parts, separated with dots.

Each version part is itself parsed as a sequence of four parts: <number-a><string-b><number-c><string-d>. Each of the parts is optional. "

P.S.
Based on the fact i could only go as far as making version 58.0t52, there might also be a restriction on the number of parts allowed (but i haven't spent time on verifying that).

**Comment by freaktechnik** [comment]
The change here is, that previously you could use any character for the last bit, and it would just `3t52.3.0` as the trailing alphanumeric part of the version number, whereas now it is much more strict. See https://github.com/mozilla/addons-linter/blob/master/src/schema/formats.js#L10 for the enforced RegExp. As documented there, "a slightly restricted version of that format" is used.

**Comment by jvillalobos** [comment]
@caitmuenster is in charge of the docs now. Don't know if this is still relevant, though.

**Comment by caitmuenster** [comment]
If it's helpful, we can add some more guidance to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version. I don't really understand https://github.com/mozilla/addons-linter/blob/master/src/schema/formats.js#L10, though.

**Comment by jvillalobos** [comment]
Maybe we could add a note pointing to that github link indicating that's how we validate versions, in case someone needs the exact format.

**Comment by freaktechnik** [comment]
> I don't really understand https://github.com/mozilla/addons-linter/blob/master/src/schema/formats.js#L10, though.

Valid formats include (only last digit):
- .[numbers][letters]
- .[numbers][letters][numbers]
- .[numbers][letters]-[numbers]

Obviously just numbers also works, but that overlaps with valid chrome formats.

**Comment by caitmuenster** [comment]
I updated https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version to point to https://github.com/mozilla/addons-linter/blob/master/src/schema/formats.js#L10 if devs have any questions about valid version formats. Let me know if anything else is needed!
