### ISSUE TITLE
Build the Install Switch

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons#63]
<img width="1281" alt="switch-states" src="https://cloud.githubusercontent.com/assets/6797635/13712198/2acf7b4e-e777-11e5-97c5-f3394b5c48f2.png">

**Let's build the install switch!**
[Clickable prototype](https://invis.io/UA69XTT96)

To do
- [x] Finalize design with visual design team
- [x] Spec out states
- [ ] Spec out motion/animations
- [x] Finalize flows for all cases (success, failure, etc.)

**Comment by muffinresearch** [comment]
@pwalm here's a starting point (since it's friday) I thought I'd try it out as checkbox replacement:

http://jsbin.com/tamure/edit?html,css,output

When I have a moment I'll add more of the states. Do you think the diagonal backgrounds will move?

**Comment by pwalm** [comment]
Look at this! Nice start! Yes, the background will move. I'll have that all spec'd out for next week. :+1:

**Comment by pwalm** [comment]
Updated spec:
<img width="1118" alt="screen shot 2016-03-16 at 10 23 59 am" src="https://cloud.githubusercontent.com/assets/6797635/13822030/5e776cac-eb61-11e5-8d19-fc7bff95b68c.png">

**Comment by muffinresearch** [comment]
I've done some more work on the prototyping this. http://jsbin.com/tamure/edit?html,css,output The download progress needs to be finished along with improving the tick but it's getting closer to the recently added spec.
