### ISSUE TITLE
Google shows pages of the old design in the results

### ISSUE THREAD

**Issue by Djfe** [mozilla/addons#630]
Google still links to pages in the old design, like this one:
https://addons.mozilla.org/de/firefox/tag/download%20manager

Maybe you should port them to the new design or fix the links in-case that has been done already :)

**Comment by jvillalobos** [comment]
The pages haven't been ported already, but they should be eventually. It probably won't happen this quarter, though. This will be tracked in the [front-end repo](https://github.com/mozilla/addons-frontend) when it's ready to be worked on.
