### ISSUE TITLE
HOXX VPN Ext / Addon Bug - Mozilla Only

### ISSUE THREAD

**Issue by moniquerenecoates** [mozilla/addons#633]
Good Morning,
Long story short - I am not able to add the HOXX VPN **WebRTC Leak Shield** to Mozilla.  When I attempt to download the extension and add it, I get a pop up box that says "Add-on could not be downloaded due to a connection failure." However, this is after the green line quickly crosses this pop-up box, associated with a file downloading somewhere . . ?

I have downloaded a desktop Hoxx VPN version that also can NOT put the WebRTC shield ext on Mozilla. It could, however, upload it to Google.  I am thinking this is because Google owns Firefox anyway, and just wants one of its browsers to be net neutral by force.

Thank you. I hope this helps in some small way, or not . .  LOL

Kindest regards,
Ms. Coates

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on. If you're having trouble installing an add-on please link to it.

If you're having an issue with an add-on please contact the developer directly; you can find a link to their contact details on the add-on page on https://addons.mozilla.org/
