### ISSUE TITLE
"No reviews yet" despite two reviews listed under /addon/{addon_name}/reviews

### ISSUE THREAD

**Issue by cedricium** [mozilla/addons#636]
### Describe the problem and steps to reproduce it:
I'm the developer of RapidTabOpener (RTO) and I just noticed when visiting RTO's details page on AMO that it says "No reviews yet" in the"Rate your experience" card despite showing "2 reviews" in the top card and having two reviews listed at https://addons.mozilla.org/en-US/firefox/addon/rapidtabopener/reviews/. And on the Reviews page, it also says there are zero reviews despite showing two reviews on the page. See screenshots below for more information.

### What happened?
No hyperlink in the "Rate your experience" card despite addon having two addons.

### What did you expect to happen?
A hyperlink that says "Read 2 reviews" linkng to https://addons.mozilla.org/en-US/firefox/addon/rapidtabopener/reviews/.

### Anything else we should know?
**Detailed Page:**
![rto_homepage](https://user-images.githubusercontent.com/16343560/36056445-609ad04c-0db9-11e8-99b5-7c31d90cc588.png)

**Reviews Page:**
![rto_reviews](https://user-images.githubusercontent.com/16343560/36056456-75df7bce-0db9-11e8-8c7c-d49f9415cd1a.png)

**Comment by eviljeff** [comment]
@tofumatt ideas?

**Comment by tofumatt** [comment]
Hmm, that's super weird. Either we're checking the wrong property or the API data is stale. Not sure what it would be specifically.

**Comment by eviljeff** [comment]
it appears the latter https://addons.mozilla.org/api/v3/addons/addon/rapidtabopener/ shows `ratings.textcount` as `0` instead of `2`.  Not specifically _API data_ (detail responses aren't from ES), but the model value in `Addon.text_ratings_count` (textreviewscount in db) which is supposed to be up to date.

@diox who spent a lot of time looking at Ratings (though, iirc, I added text_ratings_count so could be to blame)

**Comment by diox** [comment]
What's weird is that it shows the correct `count`, not the correct `textcount`. We used to have issues with the task filling those fields not firing/firing too soon (before transaction was committed) and we'd have some desync, but here it managed to get the count properly... I would tend to blame cache-machine returning obsolete data when the task fired.

**Comment by vamshi9666** [comment]
i am facing this too . any updates
