### ISSUE TITLE
Review Tools: Moderated Reviews is extremely slow

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#637]
Deleting spam from Moderated Reviews is extremely slow and often results in "Oops! We had an error.".

It takes minutes to process a page after attempting to delete items.

It has always been like that but due to increased amount of spam, and the increased need to process/delete them, the slow operation has become really cumbersome.

There seems to be some sort of ordered numbers/IDs used which prevents processing multiple pages simultaneously (it results in "Oops! We had an error.").

`https://reviewers.addons.mozilla.org/en-US/reviewers/queue/reviews`

**Comment by diox** [comment]
Marking as p2 because perf matters :) We can probably investigate and speed it up.
