### ISSUE TITLE
Add-on rating - wrong number of stars

### ISSUE THREAD

**Issue by mentallurg** [mozilla/addons#638]
### The problem
FireFox displays rating 4 stars for add-on whereas actually it is 3.2 stars.

### Steps to reproduce
- In FireFox open Add-ons Manager
- Klick on "Extentions"
- In the field top right enter "KeePassHelper" and start search
- Result will return an entry for "KeePassHelper". In this entry, click on "More".
- As a result information about this add-on will be displayed.
- Scroll to the bottom of this description. There is field "Rating".
- This field displays 4 stars.

### What happened?
Add-on details page displays rating of 4 stars.

### What did you expect to happen?
**Expected result:** The rating of 3 stars (or maximum 3.2 stars) should be displayed.

Why 3 stars, not 4? Here is why. Look at the add-on review page:
https://addons.mozilla.org/en-US/firefox/addon/keepasshelper/reviews/?src=api
There are 17 reviews. The sum of their rating is 55 stars. The average is 55 / 17 = 3.2.
One could argue that reviews are new and not yet reflected in the add-on details page. But that is not the case. Reviews (except one) are one month or older
That is why the rating of 4 stars is wrong.

### Anything else we should know?
Add-on review page:
https://addons.mozilla.org/en-US/firefox/addon/keepasshelper/reviews/?src=api
I have reported another bug about rating, #639. May be they are related to each other.

**Comment by eviljeff** [comment]
It's the same cause as #639
