### ISSUE TITLE
Discovery Pane Design

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons#64]
<img width="1257" alt="disco-pane" src="https://cloud.githubusercontent.com/assets/6797635/13712623/88d1f2ba-e779-11e5-83dd-8281780c505d.png">

- [x] Spec out layout
- [x] Spec out typography styles (I think we just get this "for free" with browser styling?)
- [x] [Install switch](https://github.com/mozilla/addons/issues/63)
- [x] ["Play video" interaction](https://github.com/mozilla/addons/issues/83)
- [x] Intro copy from Scott
- [ ] Spec out sidebar design
- [x] [Answer QA questions](https://public.etherpad-mozilla.org/p/disco_pane_feedback)
- [x] Android! Revist

**Comment by pwalm** [comment]
Updated layout/spec:
![disco pane](https://cloud.githubusercontent.com/assets/6797635/13925204/b513b66a-ef44-11e5-8751-4a7ce6dd0aa7.png)

**Comment by pwalm** [comment]
Block spec:
![block spec](https://cloud.githubusercontent.com/assets/6797635/13925443/907f0650-ef45-11e5-8f5f-4b2694c23799.png)

**Comment by andymckay** [comment]
Can we turn this into a pull request?

**Comment by muffinresearch** [comment]
@pwalm do you we have a appropriately licensed source for using the SanFrancisco font as a webfont - I see it's an Apple font, so presumably we'll need a webfont to cover the cases where it's not locally installed.

**Comment by pwalm** [comment]
Ah, sorry about that. We should be pulling whatever typeface is the platform default.

**Comment by muffinresearch** [comment]
> Ah, sorry about that. We should be pulling whatever typeface is the platform default.

Ok - I think we can do that fairly easily.

**Comment by muffinresearch** [comment]
@pwalm can we get more spec detail for the header e.g. "Personalize your firefox". 

We're missing:

- Font info (colour/weight/letter spacing etc).
- Border colour + thickness under the header

**Comment by pwalm** [comment]
**Font info for header**:
font-family: [whatever the platform default is];
font-size: 20px;
color: #000000;
letter-spacing: 0px;

**Font info for copy**:
/* There are thousands : */
font-family: [whatever the platform default is];
font-size: 14px;
color: #414141;
letter-spacing: 0px;
line-height: 18px;

**Border/divider line info**:
border: 1px solid #B1B1B1;
