### ISSUE TITLE
Allow smooth transition from add-ons beta channel to developer-hosted beta distribution

### ISSUE THREAD

**Issue by mi-g** [mozilla/addons#640]
With the beta channel being removed, the solution proposed by Mozilla is for the developers to host self-signed beta versions on their site. From Firefox add-ons team email on 2/5/2018, users will be automatically updated to the latest non-beta version of the add-on.

This means that the beta users community we (add-on developers) have been growing for years will just vanish. Even with heavy communication telling users to reinstall the add-on from the developer site, we can expect a 90% loss in beta users which will definitely impact the quality of the public releases (most issues are reported by beta users before the official version is published).

A possible solution would be able to upload to _amo_ a last beta version with a `manifest.json` containing the developer's new `update_url`.

However, this is not allowed, as such an add-on fails validation with error message:
```
Your add-on failed validation with 1 error.
"update_url" is not allowed.
```
Can this be authorized ?

Alternatively, automatic update check requests from beta add-ons to mozilla.org could be redirected to a developer-configured URL (for instance in my own situation [https://www.downloadhelper.net/firefox/updates](https://www.downloadhelper.net/firefox/updates)).

**Comment by jvillalobos** [comment]
For security policy reasons, we won't automatically move users to an unlisted channel. We know it's not great that a significant chunk of beta users will be moved to the main channel, but we think that's better than to open a potential security hole.
