### ISSUE TITLE
YAHOO has hijacked my search fuction.

### ISSUE THREAD

**Issue by RStandal** [mozilla/addons#641]
### Describe the problem and steps to reproduce it:  YAHOO has hijacked my search function
It's no where in my system I can see
(Please include as many details as possible.)

### Anything else we should know? In safe mode when I do a search I get two tabs one for YAHOO and the other for BING.
(Please include a link to the page, screenshots and any relevant files.)

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on or for Firefox.

If you're having an issue with an add-on please contact the developer directly; you can find a link to their contact details on the add-on page on https://addons.mozilla.org/

**Comment by RStandal** [comment]
The problem only effects Firefox I have to assume its related to it. YAHOO is not a add on its one of the default search choices in Firefox, one I mite add I have chosen not to use.
