### ISSUE TITLE
"connected to internet" test fails if only a v6 connection 

### ISSUE THREAD

**Issue by CarlFK** [mozilla/addons#644]
ff 58.0.1 from ubuntu's xenial repos.  I am on a ip v6 only network.  "on" as in I can chat on IRC and connect to most hosts with a v6 ip.

When I go to FF, Tools, Add ons... Get Addons... "When you are connected to the internet, this pane will feature some of the best addons you can try out."

I checked a few MO hosts and couldn't find any with v6 ips.  
```
$ host addons.mozilla.org
addons.mozilla.org is an alias for olympia.prod.mozaws.net.
olympia.prod.mozaws.net has address 35.162.190.12
olympia.prod.mozaws.net has address 52.11.75.181
olympia.prod.mozaws.net has address 50.112.182.76
olympia.prod.mozaws.net mail is handled by 10 mx.socketlabs.com.
```

I see two problems:

1) FF's "check if on internet" test is a bit opinionated.   I suspect "can't connect to addons.mozilla.org" is more accurate.    I would suggest having a "show details" option that dumps a log of the test and results that came to the conclusion I am not on the net. 

2) MO doesn't have v6 IPs.    This isn't exactly a problem, but seems a little odd.

**Comment by kumar303** [comment]
Hi @CarlFK ! I saw someone else mention this the other day. @bqbn @philipcristiano is it a known issue that people are having trouble connecting to AMO with IPv6?

**Comment by rctgamer3** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1354049
https://bugzilla.mozilla.org/show_bug.cgi?id=1075388
https://bugzilla.mozilla.org/show_bug.cgi?id=975888

**Comment by kumar303** [comment]
Thanks @rctgamer3 . Since https://bugzilla.mozilla.org/show_bug.cgi?id=1354049 is open to track our limitations with AWS, I'm closing this one as a duplicate.
