### ISSUE TITLE
[Reviewer Tools] Top Review Stats

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#645]
Any development on issue #573 (Dec 1, 2017) which was due to be fixed in Q1?

> With the latest push yesterday the Reviewer Tools page has changed and no longer provides the monthly and overall review stats for top reviewers.
> 
> Some my find it trivial but I found it to be a great motivator (especially for those passed the regular incentive motivation)
> https://reviewers.addons.mozilla.org/en-US/reviewers/
> 
> Please reinstate them as soon as possible.

**Comment by jvillalobos** [comment]
It was bumped down to Q2. Please don't open more issues for this, it's no necessary to track it here for now.
