### ISSUE TITLE
Localize for Dutch redirects to Frysk

### ISSUE THREAD

**Issue by NoricoG** [mozilla/addons#646]
### Describe the problem and steps to reproduce it:
On the Edit Information page of a plugin with only English (US) localization, add new locale Nederlands nl.

### What happened?
Localization Frysk fy-nl gets added.

### What did you expect to happen?
Localization Nederlands nl gets added

### Anything else we should know?
Adding Frysk does add Frysk like expected.

**Comment by kumar303** [comment]
Thanks for taking the time to file an issue.

Could you provide a screenshot? I'm not sure what you mean by this part:

> Localization Frysk fy-nl gets added.

**Comment by NoricoG** [comment]
I  can provide a screenshot on Monday.
You can switch between locales by clicking on the current selected locale in the top right. In the menu that appears, you can choose between selected locales and new locales. When you click on a new locale, you switch to it and can provide the information for that locale. The bug is that it switches to the wrong locale.

**Comment by NoricoG** [comment]
![page](https://user-images.githubusercontent.com/9801994/36372375-275a542a-1565-11e8-8ed1-6a88d2c67490.png)
![steps](https://user-images.githubusercontent.com/9801994/36372376-2774622a-1565-11e8-9cfc-d210c11028c8.png)

**Comment by diox** [comment]
I can reproduce, that is weird and confusing! Wondering if the issue is entirely on the javascript side...

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF58 (Win10x64)

![image](https://user-images.githubusercontent.com/31961530/36659111-0bb99d76-1adc-11e8-9150-7d4068e4ddbe.png)
