### ISSUE TITLE
Armenian spellchecking add-on missing in the list of available dictionaries.

### ISSUE THREAD

**Issue by Xelgen** [mozilla/addons#648]
### The problem and steps to reproduce it:
Right click in any text input field in Firefox, to get a context menu. In menu, under "Check Spelling" choose "Languages > Add dictionaries...".

### What happened?
A new tab with [webpage displaying list of available spell checking dictionaries](https://addons.mozilla.org/en-US/firefox/language-tools/) will be opened [1].
In the list [dictionary for Armenian language](https://addons.mozilla.org/en-US/firefox/addon/armenian-spell-checker-diction/) [2] is NOT included. 

### What did you expect to happen?
I expect spell checking add-on for Armenian language [2], to be included in the list [1].
It was included in similar list in the period of 2011-2017. 

### Referenecs
[1] https://addons.mozilla.org/en-US/firefox/language-tools/
[2] https://addons.mozilla.org/en-US/firefox/addon/armenian-spell-checker-diction/

**Comment by jvillalobos** [comment]
It's fixed now. It looks like the language code was set incorrectly.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-prod, FF58 (Win10x64)

![image](https://user-images.githubusercontent.com/31961530/36411386-17a51aa6-161e-11e8-9a0d-a6b7acad5c8b.png)
