### ISSUE TITLE
LTR browser preview layout for RTL version of AMO

### ISSUE THREAD

**Issue by ItielMaN** [mozilla/addons#649]
STR:
1. Open [this link](https://addons-dev.allizom.org/he/developers/addon/submit/wizard-listed). If you're forwarded somehow to your locale version of AMO, change it to Hebrew, Arabic or Persian
2. Scroll down to the browser preview

AR:
LTR layout for the browser preview

ER:
RTL layout.

![default](https://user-images.githubusercontent.com/18016656/36394640-e9a73004-15bd-11e8-9b23-de593496ba16.png)

**Comment by EnTeQuAk** [comment]
cc @eviljeff to track this for his static-themes project.

**Comment by eviljeff** [comment]
I don't know what RTL Firefox looks like, but it's probably best the preview stick with it's generic, l10n neutral-ish style.  I.e. force the text in preview to render itself as LTR.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF58, Win10x64

![image](https://user-images.githubusercontent.com/31961530/36979090-18ee08c0-208f-11e8-98e2-3ce8efdaee3e.png)
