### ISSUE TITLE
"String name contains invalid characters" error should be more helpful

### ISSUE THREAD

**Issue by arantius** [mozilla/addons#650]
I just tried to upload a new version of my extension.  I got the error

> String name contains invalid characters
> Error: String name should only contain alpha-numeric characters, _ and @ (https://mzl.la/2Eztyi5).

140 times.  Each was tagged with the file it came from, but not which name triggered it.  It's a lot of effort for me to figure out which name it might be complaining about, to try and fix it.  It's a lot less effort for it to just TELL me which name it doesn't like.

(Also: WHY?  Why do you care which strings I use for my strings' names?  They definitely work, as is now, in my source...)

See also greasemonkey/greasemonkey#2862

**Comment by jvillalobos** [comment]
Please file this in the linter repository: https://github.com/mozilla/addons-linter/issues/

**Comment by tofumatt** [comment]
I've re-filed this at https://github.com/mozilla/addons-linter/issues/1872
