### ISSUE TITLE
javascript lint error "Error: There is a JavaScript syntax error in your code; validation cannot continue on this file."

### ISSUE THREAD

**Issue by lparnes1** [mozilla/addons#651]
### Describe the problem and steps to reproduce it:
When trying to upload a Firefox addon, I got the above error.  I downloaded the Javascript lint checker you use, and it got a lot of "Ambiguity whether two adjacent lines are part of the same statement".  Apparently, it didn't like "var filter" in the below representative Javascript file taking > 1 line.

### What happened?
My actual Javascript file has the var filter over > 41000 lines, which each line is like this:

            || details.url.indexOf(".xxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXXX.net/") != -1

So I concatenated them to make one line of over 2,100,000 characters and ran the lint checker on it, and it crashed hard.  Then  I decided to try and upload the Javascript with its 2,100,000 character line, and it came back with the same error as is in the title.  I'm guessing that the Mozilla lint checker is crashing too and giving me this generic error.

### What did you expect to happen?
Since the Javascript and the addon works fine with Firefox (as well as Chrome) with no Javascript errors at all, the last thing I would expect is a syntax error like this when the execution environments have no problem.  When I converted the 41000+ line statement into 1 line with 2,100,000+ chars, I would expect the lint checker to not crash and Mozilla's validation to pass or give me more than "Error: There is a JavaScript syntax error in your code...", like maybe a line number or something more specific.  It's damn hard to find a syntax error when the Firefox and Chrome browsers don't find any javascript errors, and they execute the addon properly.

### Anything else we should know?  Here is the file that broke it.  Just imagine "var filter" covering 41000+ lines instead of 2.

chrome.webRequest.onBeforeRequest.addListener(
    function(details) {
        var filter = details.url.indexOf(".xxxxxxxxxxxxxxxxxxxxxxxx.com/") != -1
    || details.url.indexOf(".xxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXXX.net/") != -1
    ;
    return { cancel: filter };
    },
    { urls: [ "<all_urls>" ] },
    [ "blocking" ]
);

function checkTime (i) {
    return (i < 10) ? "0" + i : i;
}

chrome.runtime.onMessage.addListener(
    function(request, sender, sendResponse) {
        var time = new Date();
        var timeString = checkTime(time.getHours()) + ":" + checkTime(time.getMinutes()) + ":" + checkTime(time.getSeconds());
        console.log(timeString + " - " + request.message);
    }
);

**Comment by jvillalobos** [comment]
Can you attach the XPI you tried to upload?

**Comment by lparnes1** [comment]
[AdAndStuffBlockerFirefox10.zip](https://github.com/mozilla/addons/files/1749953/AdAndStuffBlockerFirefox10.zip)

**Comment by lparnes1** [comment]
Got anything yet?

**Comment by tofumatt** [comment]
No, but we will update the issue when we have something available. Apologies but we have a large issue backlog so it can sometimes take us awhile to get to newer issues.

- Matt (Sent from mobile)

**Comment by EnTeQuAk** [comment]
Looking at this in more detail, the error message is a bit misleading. It's not a syntax error but `  message: 'Parsing error: Maximum call stack size exceeded',` is what we actually get.

Minimal example:

```javascript
var acorn = require("acorn");
var fs = require("fs");
fs.readFile("/home/chris/Downloads/adad/background.js", function(err, data) {
    if (err) throw err;
    acorn.parse(data);
});
```

And running that via `node test.js` fails with

And passing `--stack-size=10000` to node allows it to work. I was under the impression that we set something like that on our servers but this should actually be fixed in `acorn`.

I'll debug this a bit more and report something upstream in case I find something.
