### ISSUE TITLE
Identify compatible add-ons

### ISSUE THREAD

**Issue by MrLupner** [mozilla/addons#652]
Could you please, please, please, pretty please, add something to identify add-ons that are compatible with Quantum in the list of add-ons after doing a search. I know they are identified on the actual page for each add-on. But if there are 50 items matching the search for "delete cookies" it is a royal PITA to have to open each and every one to see if they are going to work. An icon. Some character. Italics or bold or ANYTHING so we don't have an inscrutable list of programs that ultimately won't work. Sorting the list by "Recently Updated" sort of helps, but pushes some of the best or most relevant items way down the list. 

Thanks!

**Comment by diox** [comment]
When searching using Firefox Quantum on AMO, you will only get add-ons that are compatible with the version of Firefox you're using (that was only an option on the legacy website, it has since been made mandatory for 57 or higher)
