### ISSUE TITLE
Filters on your Add-on section not filtering properly; need MORE FILTER OPTIONS

### ISSUE THREAD

**Issue by IDontWantAnotherStinkinAccount** [mozilla/addons#653]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I want to see see all the results for one category of your add-ons, sort on top rated and only show add-ons for macOS.

Functionally, I chose a Alerts and Updates. From drop down, selected sort by Top Rated; from drop down selected macOS.

link: https://addons.mozilla.org/en-US/firefox/search/?category=alerts-updates&platform=mac&sort=rating&type=extension

### What happened?
Got alot of 5-star rated apps, that is good.  I got MANY apps for iOS and Android, none of which I wanted to see.  I stopped looking at results after two pages due to the extensive number of hits in languages I could not read! 

### What did you expect to happen?
What I did NOT expect to happen was to get results for operating systems that were not selected, ie. I expected the filter to work.

I also didn't expect all the foreign language hits.  YOU NEED A FILTER FOR THAT!

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Other filters would also be nice, like most recent version only, etc.  I didn't bother to check to see if I got results for other sections besides the one I chose because this exercise qyickly became a waste of time

I'm sure you will be able to reproduce my results, but if you have a problem, I'll try a screen capture.  But I've wasted enough time already on your website as it is.

**Comment by tofumatt** [comment]
There aren't iOS add-ons (Firefox for iOS does not currently support add-ons), but I think you might have mistaken results like https://addons.mozilla.org/en-US/firefox/addon/android-desktop-notif/ for an Android add-on. I think the filters are working but the result set might have been unclear. I don't know what to do about that other than contact add-on developers and ask them to translate their descriptions and more clearly label their add-ons though.

The idea of a search filter to limit results to your language is an interesting one.

If you could point to results that are only for Android appearing in the MacOS filtered results that would be great.
