### ISSUE TITLE
Signed for self-distribution add-ons send an (incorrectly attributed) email

### ISSUE THREAD

**Issue by arantius** [mozilla/addons#656]
I just got an unlisted-for-self-distribution version of my addon to be correctly submitted through the API for the first time.  And I got an email about it (which I don't want).  But there's an apparent bug; the email says in it:

> You received this email because you're subscribed to:
>   * email me when my add-on is reviewed by a reviewer

But this was signed only, not reviewed by a reviewer.

**Comment by caitmuenster** [comment]
Thanks, @arantius! This is fixable -- I'll get some updates going.

**Comment by diox** [comment]
Forward-duping to the right repository https://github.com/mozilla/addons-server/issues/7724
