### ISSUE TITLE
Text fields unreadable with dark system (GTK) theme

### ISSUE THREAD

**Issue by futpib** [mozilla/addons#657]
### Describe the problem and steps to reproduce it:
When using a dark GTK theme, text fields on addons.mozilla.org are unreadable due to a light text (foreground) color (`-moz-fieldtext`) "inherited" from GTK theme and a light input backgroud color (`#fff`) being explicitly declared in CSS.

#### Steps to reproduce

1. On linux, install any dark gtk theme. I will use https://github.com/KDE/breeze-gtk as an example.
2. Start firefox with dark GTK theme:
`GTK_THEME="Breeze-dark-gtk" firefox --no-remote --new-instance --profile $(mktemp -d)`
3. Open https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/
4. Log in to AMO
5. Try to add a review (click on a star)
6. Observe white-on-white textarea styling (see screenshot below)

### What happened?
`input`s and `textarea`s were unreadable.

### What did you expect to happen?
I expected `input`s and `textarea`s being readable.

I expected AMO CSS either to explicitly set both input foreground and background colors or not to set either of those (to use system theme defaults, i.e. `-moz-field` and `-moz-fieldtext`).

### Anything else we should know?

Here is a approximate patch that could fix this (sorry, I could not find the real sources, had to look at sourcemaps and write this manually):

```patch
--- a/src/amo/components/App/styles.scss
+++ b/src/amo/components/App/styles.scss
input,
textarea {
   font-family: "Fira Sans", sans-serif;
   font-style: normal;
   font-weight: 400;
   background: #fff;
+  color: #000;
   border: 1px solid #737373;
   border-radius: 2px;
   -webkit-box-shadow: none;
           box-shadow: none;
   font-size: 14px;
   line-height: 1.4;
   padding: 4px;
 }
```

Screenshot below shows comparison of a firefox instance under `GTK_THEME="Breeze-dark-gtk"` (on the left) with one under `GTK_THEME="fallback"` (on the right):

![screenshot_20180305_063009](https://user-images.githubusercontent.com/4330357/36956753-19bf9c62-2041-11e8-8803-3401f0dfce79.png)

**Comment by DmitriK** [comment]
I'm the author of 'Text Contrast for Dark Themes', which is generally designed to fix issues like this automatically. However, due to the restriction of addons not being allowed to inject content scripts into AMO, it doesn't work there. In addition to the referenced issue above, I have quite a few reviews on AMO that mention the irony of the addon not working on the review page itself. I also have to deal with this when editing the addon information on AMO. It would be very helpful if this got fixed.

**Comment by diox** [comment]
The source repos is https://github.com/mozilla/addons-frontend/ @futpib do you want to make a pull request there with your fix?

**Comment by futpib** [comment]
@diox done.

**Comment by vcarciu** [comment]
@futpib : I was not able to reproduce the initial issue. Was this reproducible on Release , Beta and Nightly?
Can you see the changes now after the fix?

**Comment by futpib** [comment]
@vcarciu Mozilla Firefox 58.0.2, but issues like this are reproducible across firefox versions since forever, because they are due to purely written page CSS, not due to a firefox bug (if we consider native input styles to be a feature rather than a bug).
