### ISSUE TITLE
Site doesn't recognize newer version of Firefox and denies download

### ISSUE THREAD

**Issue by OderDochNicht** [mozilla/addons#658]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Trying to get Self Destroying Cookies. It states Firefox 54.0 is needed but I would run 51.0. Negativ, I run Firefox 57.

### What happened?
I'm denied to install Self Destroying Cookies

### What did you expect to happen?
My Firefox up and running with Self Destroying Cookies.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Do you have `privacy.resistFingerprinting` set ? If so, that's your problem: it changes your user agent and prevents AMO from detecting it properly, by design.

**Comment by kumar303** [comment]
Thanks for the bug report. If this is due to anti-fingerprinting settings, I think https://github.com/mozilla/addons-frontend/issues/3445 will address the issue.

**Comment by eviljeff** [comment]
duping to mozilla/addons-frontend#3445 (and the other near-dupes mentioned in that bug)
