### ISSUE TITLE
Increase max file size to 6 Mb

### ISSUE THREAD

**Issue by digitarald** [mozilla/addons#662]
### Describe the problem and steps to reproduce it:

Submit an extension with a 5.1 Mb JS file, like [Augury](https://github.com/rangle/augury/pull/1268).

### What happened?

Validation error, max file size is 4 Mb.

### What did you expect to happen?

Submission works without extra build step tweaking that doesn't benefit the product in any way.

---

I assume 6 Mb is the next logical increase after going from 2 to 4 Mb in #181.

Might be interesting to keep an eye on this, using instrumentation in the validation process to track how many extensions hit the issue (and possibly never come back).

**Comment by EnTeQuAk** [comment]
> Might be interesting to keep an eye on this, using instrumentation in the validation process to track how many extensions hit the issue (and possibly never come back).

Indeed, unfortunately, we don't have that right now but plan to do so at some point.

Increasing to 6Mb sounds logical but I'm uncertain what we gain with this. What files are that big, I can't see it in the PR you mentioned, is that a build-result? Are you sure you can't split that somehow, e.g with `webpack#import` or similar methods?

**Comment by EnTeQuAk** [comment]
> We could also turn it around to reason why the status quo is in place; asking developers to reduce file size. What is the benefit of keeping it at 4Mb?

Well, there is no benefit but we were running into various issues with too big files when parsing through eslint causing memory issues and nodejs abortions. 

Do you have an example file or preferably add-on that is currently failing so that we can start testing it?
