### ISSUE TITLE
AMO should serve language packs for Firefox 59

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/addons#663]
addons.mozilla.org still serves the language packs for Firefox 58, e.g. https://addons.mozilla.org/firefox/addon/deutsch-de-language-pack/
It should serve those for Firefox 59.

If a user upgrades to 59 at the moment with a language pack installed and active, Firefox's UI locale will change to the one of the Firefox executable.

**Comment by wagnerand** [comment]
I just triggered the import, they should be updated shortly.

**Comment by ioanarusiczki** [comment]
I installed with FF59 (Win10) several language packs from AMO prod, also checked a couple of dictionaries and it works as expected.  If some more testing is needed please let me know.
