### ISSUE TITLE
My Username has been changed!  WHY???

### ISSUE THREAD

**Issue by Cay-Lenz** [mozilla/addons#664]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
When I signed into my Mozilla account from a new computer, Mozilla CHANGED my username!  My username is "Calen", but now Mozilla will ONLY allow me to log into "Anonymous user 776dce".  

### What happened?
Mozilla, without notice or warning, CHANGED my username to "Anonymous user 776dce"!  

### What did you expect to happen?  
I expected to get logged into MY account!
So, HOW can I log into the correct account?  

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
Go to https://addons.mozilla.org/users/edit and see what your username and display name are set to. You can change those to "Calen", if it's available.

**Comment by EnTeQuAk** [comment]
Are you also sure that you signed in with the same email address? New accounts indeed get a default username like the one you mention but as @jvillalobos said you can change it.

This doesn't sound like a technical problem, so I'm closing this. If you have any more problems feel free to comment or open a new issue any time.
