### ISSUE TITLE
 [Reviewer Tools] Auto Approved Queue: Jetpack Icon not required

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#666]
Since Jetpack are not supported any more, there is no need to have a marking for it.
The same for flags on actual review page i.e.:

> Flags
> Jetpack Add-on

The tool picks up any add-on with `package.json` and marks it as Jetpack

`<div class="app-icon ed-sprite-jetpack" title="Jetpack Add-on"></div>`

Examples:
https://reviewers.addons.mozilla.org/editors/review/932600/
https://reviewers.addons.mozilla.org/editors/review/936317/

_PS. Off-topic: This is issue **666** so special care is needed ... lol_

**Comment by eviljeff** [comment]
agreed it's pretty useless - especially in the auto approved queue, when jetpack addons can't be auto-approved.
@wagnerand are jetpack addons not supported at all?  Should the icon be removed anyway?

**Comment by wagnerand** [comment]
Legacy add-ons (including Jetpack) are still supported, and will be until the end of ESR 52 (end of August). The won't show up in the auto-approved queue of course, but in the legacy queues.

If you'd like to get rid of this entirely, that's fine with me. We don't get that many legacy submissions these days.

**Comment by eviljeff** [comment]
We could just remove the flag in the reviewer tools - that's about 3 lines to change + some tests... but arguably we should remove all the supporting code that detects jetpack addons and treats them differently (e.g. repacks).

**Comment by diox** [comment]
Already fixed in https://github.com/mozilla/addons-server/commit/e9cb26f6ba8f1bef468e6f70c33b81238f4a9eca
