### ISSUE TITLE
Rounding of star ratings is an unhelpful simplification for addon consumers and an irritation to developers

### ISSUE THREAD

**Issue by halfmanhalffish** [mozilla/addons#668]
### Describe the problem and steps to reproduce it:
Search for addons on AMO
(for example https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=scroll )

### What happened?
The icons representing the addon user reviews show whole or half stars with scores rounded down to the nearest half.

No doubt AMO staff have taken a decision to keep things simple for addon consumers. That's fine. But
* The large majority of addons score 3 to 4.5 icon-stars, giving a range of just 4 grades. There's little information value for consumers
* Developers' hard work is rewarded by having fractions of stars tossed away and seeing themselves ranked level with other addons with lesser scores
* The higher an addon's rating, the more it is penalised
* Is it really a service to consumers if you give them inaccurate numbers ?

As far as cognitive load is concerned, the half-star idea seems poor to me. It is not immediately clear whether third-of-a-stars icons are being used or not - I have to squint, then I decide I need the tooltip and am forced to jockey for it and then wait longer than I want to. If cognitive load is the concern then AMO should have stuck with whole stars.

### What did you expect to happen?
Some suggestions:
* Rating 48
* 48 *
These could be combined with something graphical, eg a 'heat bar' which indicates rating by its width and by its colour (red hot, blue cold).

Or for those who just like punctuation marks:
* Rating 4.8
* 4.8 *
* 96 %

**Comment by jvillalobos** [comment]
You can hover over the star ratings to see a more accurate number. Casual users don't require that level of precision and it's much easier and familiar to visualize average ratings as stars and half-stars.

**Comment by halfmanhalffish** [comment]
Jorge,

I also made points relating to the developer's interests, which you have ignored. [Ditto this, which is as complacent an answer as anyone could possibly give.](https://github.com/mozilla/addons/issues/669#issuecomment-378756824)

People like me don't get paid for our contributions. The only satisfaction we get is having lots of users and the reviews that go with them.

You made no attempt to enter into a dialogue, and you clearly couldn't care less about developer interests.

Shame on you.

**Comment by jvillalobos** [comment]
I'm sorry you see it that way, but that wasn't my intention. While the response on this issue is very short, I did try to be more thorough in the other one, because I think it was warranted. This one has a shorter answer because I thought it was clearer why we chose to go the way we did.

Many design decisions on the site balance the needs of users and developers, and inevitably some of them won't be satisfied with what we choose. In this case I think power users who are interested in more precise measurements will be able to figure out the hover effect, or click through the listing to look for more details.

**Comment by halfmanhalffish** [comment]
Ok, so you don't not care about developer concerns.

So why *did* you ignore all four of my bulleted points then ?  User/developer tradeoff has little or nothing to do with this. By your own argument users don't care if you round up, down or nearest half.

You ignore the heatbar idea, which would address all concerns: rich info for users, accurate, minimal cognitive load, and easy to code and maintain since it's minimally interactive.

'Simple for users' doesn't cut it. Abacuses and cat gifs are simple for users. Stop repeating old cant, start thinking critically.

**Comment by jvillalobos** [comment]
> 'Simple for users' doesn't cut it. Abacuses and cat gifs are simple for users. Stop repeating old cant, start thinking critically.

First of all, comments like this makes me not want to take your proposals seriously. If you really want to continue having this discussion, you need to refrain from this kind of tone.

> So why did you ignore all four of my bulleted points then ?

Alright, here goes, point by point:

> The large majority of addons score 3 to 4.5 icon-stars, giving a range of just 4 grades. There's little information value for consumers

A rating is not only a point of comparison between different add-ons. It also serves on its own as a way to determine the perceived quality from other users. Having a 3-star rating tells users that something is probably not great, regardless of how other add-ons rate. If you see an add-on that may be useful for what you're looking for and it rates positively, then you might give it a try. In some cases you'll want to compare it with similar add-ons, and big differences in rating will make a difference, sure. But I don't think that a fractional difference (0.2 avg. stars, for instance) should be a determining factor, especially considering how the average is most likely calculated based on different rating amount (4.5 stars from 100 ratings vs. 4.3 stars from 500 ratings, for example).

> Developers' hard work is rewarded by having fractions of stars tossed away and seeing themselves ranked level with other addons with lesser scores

The same argument can be had for any level of precision we set for ratings. Half points is very common and accepted both by users and content creators.

> The higher an addon's rating, the more it is penalised

That's not really true. The round range will always be 0-2.5 stars, regardless of what score you have. You did bring up a valid bug, which is that the stars are being rounded down instead than to the closest half-star. That's being tracked on https://github.com/mozilla/addons-frontend/issues/4186 and should be fixed soon.

> Is it really a service to consumers if you give them inaccurate numbers ?

> You ignore the heatbar idea

Again, accuracy is relative, and ease of use and familiarity are other important factors to take into account when making product decisions. What you or me find better doesn't necessarily work for the large number of users visiting the site.
