### ISSUE TITLE
AMO addon rating algorithm inadvertently discriminates against new addons

### ISSUE THREAD

**Issue by halfmanhalffish** [mozilla/addons#669]
### Describe the problem and steps to reproduce it:
A new addon might have excellent user retention (and reviews) but nevertheless fail to catch up with established competing addons because of a heavy number-of-downloads disadvantage.

Established addons have a downloads advantage, most likely because AMO ranks them higher in search results.  User count appears to be the most important factor in the algorithm.
They gain users faster and _increase their lead despite poorer user retention_ and poorer reviews.

It is acknowledged that there are reasons for considering user count and threshold number of reviews in the algorithm.  See below for analysis.

### What happened?

A specific example:

Search for 'scroll':  https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=scroll

The second result is [Scroll Anywhere](https://addons.mozilla.org/en-US/firefox/addon/scroll_anywhere/?src=search) with review average 4.6 and 3212 users.

The fifth  result is [Logitech Smooth Scrolling](https://addons.mozilla.org/en-US/firefox/addon/logitechsmoothscrolling/?src=search) with review average 3.4 and 1298 users.

The ninth result is [Drag To Scroll](https://addons.mozilla.org/en-US/firefox/addon/drag_scroll/?src=search) with review average 4.9 and 372 users. It is not visible on a 1920x1080 monitor unless the user pages down.

(Scroll Anywhere and Drag To Scroll have almost identical feature sets.)

Looking at the stats page you can see that Scroll Anywhere has approximately 4 times as many downloads and gains users faster than Drag To Scroll despite worse user retention and a lower review average.

https://addons.mozilla.org/en-US/firefox/addon/drag_scroll/statistics/?last=90
https://addons.mozilla.org/en-US/firefox/addon/scroll_anywhere/statistics/?last=90

This example shows that _good reviews and user retention do not necessarily make it possible to catch incumbents._

### What did you expect to happen?
An addons initial release date should have as little as possible to do with average downloads per day.  Otherwise mediocre established addons benefit and complacency is encouraged.

The AMO search result ranking algorithm should  not disadvantage addons merely because they have not had the opportunity to build up a good user count.

This (probably) means attaching more weight to review averages and less to user numbers. It may potentially be useful to include some sort of user retention metric since that is indicative of quality even at very low user numbers (though there are still problems to work around).

### Anything else we should know?
You may wish to consider this bug together with [Rounding of star ratings is an unhelpful simplification for addon consumers and an irritation to developers](https://github.com/mozilla/addons/issues/668)

**Comment by jvillalobos** [comment]
It's natural for popular add-ons to gain more detractors and lose retention as they become more mainstream. Their audience widens, unusual use cases and bugs happen, and mistakes have larger impact. That doesn't mean those popular add-ons are less good than newer ones with good ratings. Conversely, a new add-on with good ratings isn't necessarily good. A high average rating based on only a handful of reviews shouldn't have more weight than one obtained from thousands of reviewers. The former is very easily gamed, and would make it easy for spammers or malicious developers to gain significant traction very quickly. 

Having newcomers be less notable provides time for the community to try them out and rate them more accurately. The good ones bubble up fairly quickly, in my experience. There are also other mechanisms to highlight not-yet-popular add-ons, like the Trending section in the homepage, and the featured add-ons, which are nominated and chosen by the community on a monthly basis.

I think this is currently working as expected.

**Comment by halfmanhalffish** [comment]
Drag To Scroll cannot be a Featured Addon because it doesn't meet your minimum 500 users requirement, maybe never will. Because it doesn't get enough downloads. It presumably won't ever be Trending either, for the same reason.

I don't want to be blunt, but I have no choice now: Drag to Scroll obsoletes Scroll Anywhere.

It is superior in every way.  Basic function, page compatibility, documentation (especially Settings documentation), feature set. Two of its features (choose scroll or text select/DnD depending on drag direction, obviating the need for mode switch, and also the option for scroll speed proportional to page size) are entirely original.

By its own admission SA's left button support is experimental. It does not appear to support iframes at all. It is not capable of precise scrolling (though if you fiddle with the settings you can make it less bad).

An example: while discussing workarounds for Firefox's 'scroll selection into view' feature with one of my users (DtS has two workarounds, one for window.top and another for other scrollable elements, both of which work) I thought I would have a look at SA and see how it handled it. It didn't, and the reason why it doesn't handle it is because it couldn't even manage to scroll the page we were looking at in the first place.

Yet SA still adds users while DtS is stuck.  That's on you.  Disagree with my suggested fixes if you like, fine, but don't deny there's a problem.
