### ISSUE TITLE
User reviews deleted via the reviews page should show up in the log

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons#67]
Currently, if a review is deleted directly from the reviews page of an add-on, the review does not show up in the logs and (apparently) aren't recoverable.

They should be in either the current moderated review log (or a separate once since they differ from reported/flagged reviews).

**Comment by tofumatt** [comment]
Unless there is a huge spam problem making storing "deleted" data impractical, I'd say we should store the actual deleted reviews as well.

**Comment by jvillalobos** [comment]
Users with sufficient permissions (like admins) can and do delete reviews without going through the moderation process, which I think is worthwhile to have in the log so they are reversible. I don't particularly care if self-deleted reviews show up there or not.
