### ISSUE TITLE
IBM Trusteer Rapport does not appear

### ISSUE THREAD

**Issue by johniparkin** [mozilla/addons#670]
When Firefox starts, I get a message telling me that IBM Trusteer Rapport has been installed, asking me to use the Add On manager to enable it. However when I try to do this , Rapport doesn't seem to be there to enable.
Anyone exeprinced this problem and can help me to solve it? 
IE doesnt sufer from the same problem and the Rapport Icon appears in the address bar

**Comment by EnTeQuAk** [comment]
Hey @johniparkin, this might not be the perfect place to ask this I think, this bug-tracker is primarily for technical issues with Addons, focusing on addons.mozilla.org and related projects.

You should be better off asking at https://support.mozilla.org/en-US/questions/firefox or directly contact your administrator (assuming that this could be a company-machine given that I doubt you use IBM Trusteer Rapport on your personal computer) or the IBM support.
