### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by reyronald** [mozilla/addons#672]
Getting an unexpected error when trying to upload a new version of an existing, listed Add-on. Is this a bug? There isn't any useful information in the error message.

Please attach a copy of your add-on, and fill in the following information:

* **Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.** New version of existing add-on.

* **Whether your add-on is listed or unlisted.** It is listed. https://addons.mozilla.org/en-US/firefox/addon/refined-bitbucket-

* **The URL where you submitted the add-on.** https://addons.mozilla.org/en-US/developers/addon/refined-bitbucket-/versions/submit/

* **The approximate time you submitted the add-on, with timezone**. 11:15 AM Eastern Time (ET) 

Through the API
```json
{
  "errors": 1,
  "success": true,
  "warnings": 0,
  "compatibility_summary": { "notices": 0, "errors": 0, "warnings": 0 },
  "ending_tier": 5,
  "messages": [
    {
      "description": [
        "Validation was unable to complete successfully due to an unexpected error.",
        "Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU"
      ],
      "tier": 1,
      "for_appversions": null,
      "message": "Sorry, we couldn't load your WebExtension.",
      "type": "error",
      "id": ["validator", "unexpected_exception"],
      "uid": "35432f419340461897aa8362398339c4"
    }
  ],
  "detected_type": "extension",
  "notices": 0,
  "message_tree": {},
  "metadata": {
    "requires_chrome": false,
    "listed": true,
    "is_webextension": true
  }
}
```

Through http://addons.mozilla.org/

![image](https://user-images.githubusercontent.com/7514993/37779400-af59f982-2dc2-11e8-8840-73cd145e3fdd.png)

**Comment by diox** [comment]
@reyronald have you tried multiple times? It looks like a deadlock, which should be pretty rare... let us know if that happens consistently or if it was just a fluke.

**Comment by reyronald** [comment]
Yeah, I just tried again now and the same result.

The code for the extension is open source and can be viewed [here ](http://www.github.com/refined-bitbucket/refined-bitbucket) if that's any help. [Here's the manifest](https://github.com/refined-bitbucket/refined-bitbucket/blob/dev/src/manifest.json). 

If there's nothing wrong upstream it's probably an issue with the extension code itself, but since the error is not showing any useful information I don't know where to start looking for the issue :S. Needless to say I've successfully uploaded previous versions myself. This is the manifest for the previous version: https://github.com/refined-bitbucket/refined-bitbucket/blob/v3.7.3/src/manifest.json.

<details>
  <summary>API response https://addons.mozilla.org/en-US/developers/upload/e54efc6e98114399b6107a63e7c20c76
</summary>

```json
{
  "errors": 1,
  "success": true,
  "warnings": 0,
  "compatibility_summary": { "notices": 0, "errors": 0, "warnings": 0 },
  "ending_tier": 5,
  "messages": [
    {
      "description": [
        "Validation was unable to complete successfully due to an unexpected error.",
        "Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU"
      ],
      "tier": 1,
      "for_appversions": null,
      "message": "Sorry, we couldn't load your WebExtension.",
      "type": "error",
      "id": ["validator", "unexpected_exception"],
      "uid": "35432f419340461897aa8362398339c4"
    }
  ],
  "detected_type": "extension",
  "notices": 0,
  "message_tree": {},
  "metadata": {
    "requires_chrome": false,
    "listed": true,
    "is_webextension": true
  }
}
```
</details>

**Comment by diox** [comment]
It's definitely something wrong on AMO side, nothing to do with your extension code.

Interestingly sentry shows 2 different errors for the different attempts:
- The first time, a deadlock in MySQL https://sentry.prod.mozaws.net/operations/olympia-prod/issues/3272326/
- The second time, the connection to Redis was lost when running a task https://sentry.prod.mozaws.net/operations/olympia-prod/issues/680248/ (which I'm not 100% sure comes from the same add-on, but the timestamp matches)

**Comment by reyronald** [comment]
I see! 

Well I'm assuming there's not much I can do but if there is let me know! Naturally I'm waiting for this to be resolved so that I can publish the new version.

**Comment by diox** [comment]
So far we have no idea what's going on. QA has been able to upload that add-on to their own account for testing without any issues... We haven't heard any other complaints but the sentry traceback for the deadlock shows it did happen more than a couple times, and that started after May 15th, which is interesting because it's a push day...

**Comment by reyronald** [comment]
I just tried again right now and got the same error, so whatever that's happening, it's happening consistently.

> We haven't heard any other complaints ...

So you mean it's only me and my extension failing to upload? You sure then it's not something wrong with the extension code then? Here's a diff/compare of the previous version that I uploaded successfully and the current version I'm trying to upload: https://github.com/refined-bitbucket/refined-bitbucket/compare/v3.7.3...v3.8.0, the only thing out of the usual changes that I do is the inclusion of the logos and icons.

>  ...and that started after May 15th...

My first attempt was the same day I opened this issue, just a few minutes earlier, so March 22.

I wish I could be of more help, let me know if there's anything I can do on my side!

**Comment by diox** [comment]
Couple things that could help us:
- Do you know roughly how many times you tried ? This is to compare with the number of tracebacks. I can't easily check who is affected because it's happening in a task so I don't see who was logged on etc. I do suspect you're not the only one affected, but at the same time there aren't that many occurrences and nobody else came to us with this issue.
- Can you attach/post somewhere the exact xpi file you're trying to upload ?

**Comment by reyronald** [comment]
Here it is [extension.zip](https://github.com/mozilla/addons/files/1856970/extension.zip)

On March 22 I'm not exactly sure, maybe around 5 times or so (could be a little more, but not above 10) between 10:30 AM and 12:00 PM Eastern Time (ET), I think I tried one more time the next day and that's it. Then today, I tried twice, right before posting my previous comment (15 minutes ago) and this one.

**Comment by reyronald** [comment]
By the way, that `extension.zip` file can be generated by yourselves by simply cloning the extension repo, and running...

```bash
npm install
npm build:min
npm run package
```

Just in case you guys want/need to play around with it.

**Comment by diox** [comment]
Ok, I'm not sure if it's related, but there is something weird about this zip:
- `unzip` on my linux laptop says `error:  invalid compressed data to inflate` when extracting
- `file-roller` shows all files in it as directories
- [our linter](https://github.com/mozilla/addons-linter), when processing it locally on my machine, returnst `Error: invalid code lengths set` and it fails to validate.

So that could explain the issue, maybe the deadlock we've seen in sentry is another issue, perhaps a byproduct of the unhandled exception here.

Please check how you generate your zip file. (The fact that it worked on previous versions is not necessarily an indication that nothing was wrong with them, the linter used to be more flexible with certain broken zip files)

**Comment by reyronald** [comment]
Well I guess that's it. I just zipped it manually using WinRAR and uploaded it and it shows no errors now. So far I've been using the [`adm-zip` npm package](https://www.npmjs.com/package/adm-zip) and this code to automatically generate it:

https://github.com/refined-bitbucket/refined-bitbucket/blob/ac5fb443501c35610cdffeb2f209b8994af73b96/scripts/package.js#L1-L10

So I'm assuming that whatever `adm-zip` is doing, is not doing it right. I'm gonna switch to use something else now then.

I apologize to have bothered the Mozilla team with this. Maybe the validation in the Add-Ons site could be improved to handle this case.

**Comment by diox** [comment]
Happy to see we found what was causing the issue! Don't worry about it, we should definitely handle that in a nicer way. I'll open a new issue on https://github.com/mozilla/addons-linter and close this one.

**Comment by diox** [comment]
Closing in favor of https://github.com/mozilla/addons-linter/issues/1938 thanks for helping pinpoint the core problem!

**Comment by reyronald** [comment]
Thank you for your assistance! I just opened https://github.com/refined-bitbucket/refined-bitbucket/issues/193 on my side as well and referenced these two issues.

Since the `adm-zip` **does not always** produce a broken ZIP file (evidenced by the fact that so far I've been using it successfully until now), feel free to use my project to test your solution in https://github.com/mozilla/addons-linter/issues/1938 if you need!
