### ISSUE TITLE
Extension system adds spaces in "MixedCaseTitles"

### ISSUE THREAD

**Issue by svArtist** [mozilla/addons#673]
I uploaded a webextension for Firefox, called "NaviGator". On the details page, the name was suggested as "Navi Gator", which I corrected back to "NaviGator": So far so good.
However, when installing the extension, and when hovering over its button, the name still shows as "Navi Gator"

### What happened?
The extension's name changes from its actual name to an "optimized" version in the installation dialog and the button's hover tooltip: _exampleName_ becomes _example Name_

### What did you expect to happen?
- "Optimized" version only as suggestion upon upload
- Actual name (as set in the extension's settings) used in the install dialog and the tooltip
- Any necessary changes transparently implemented as restrictions on the extension's settings page

### Anything else we should know?
Link to problem extension: https://addons.mozilla.org/en-US/firefox/addon/bp_navigator/

![ng](https://user-images.githubusercontent.com/13470026/37800207-63332654-2e22-11e8-8372-b57531243037.png)

**Comment by championshuttler** [comment]
Hi @svArtist , as i saw you mentioned "Navi Gator" in manifest.json of your add-on that's why it is showing like this. Hope it will clear your doubt

**Comment by eviljeff** [comment]
@championshuttler is correct - @svArtist the download/permission dialog in Firefox uses the details in the `manifest.json` file (rather than AMO's details) to show the user, and you have "Navi Gator" in there.  You'll need to upload a new version to AMO to correct it.

**Comment by svArtist** [comment]
I am so sorry, somehow I made the error of misnaming my project in the manifest file.
I'm mortified with embarrassment.
Could/Should this issue be deleted, as it rest upon a false premise?
