### ISSUE TITLE
Add To Collection - List not sorted by name

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons#676]
### Describe the problem and steps to reproduce it:
Click on list...collection names listed in random order... 
How can this 'new' Add To Collection feature be implemented without thinking about this?

### What did you expect to happen?
List of collections to be sorted.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
After many months of working on this very same issue under the old design, this was originally fixed...see https://bugzilla.mozilla.org/show_bug.cgi?id=593634

**Comment by smayer97** [comment]
What did you expect to happen?

Should say, List of collections to be sorted alphabetically by name.

**Comment by smayer97** [comment]
FYI, title of link above is "Sort collections in 'Add to Collection' dropdown alphabetically"

**Comment by smayer97** [comment]
Addtional related issues:
Add To Collection - Cannot search the list -- https://github.com/mozilla/addons/issues/677
Add To Collection - No indicator showing which collection(s) the add-on already belongs to -- https://github.com/mozilla/addons/issues/678
Add To Collection - There is no link to open collection from list of collections -- https://github.com/mozilla/addons/issues/679

NOTE: Without all these 4 changes to re-implement the original design, the 'new' Add To Collection has VERY LIMITED usefulness.

**Comment by tofumatt** [comment]
I don't think this really needs product, sorting the collections by name is pretty easy and a good idea. Filed an issue on the frontend.

@smayer97: You can follow https://github.com/mozilla/addons-frontend/issues/4755 for updates on this issue.
