### ISSUE TITLE
Add To Collection - No indicator showing which collection(s) the add-on already belongs to

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons#678]
### Describe the problem and steps to reproduce it:
When you click on the Add To Collection drop down menu, there is no indicator showing which collection(s) the add-on already belongs to. 
That is one KEY feature that was useful in the old design

### What happened?
Cannot tell if add-on already exists in a collection.

### What did you expect to happen?
To be able to see a checkmark or similar to identify which collection(s) add-on has already been added to, like the old design of this menu.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

With was a design that was working in the old design, though a bug crept in that caused it work only if forced a refresh...see 'Add to Collection' dropdown does not correctly list collections to which add-on is assigned -- https://bugzilla.mozilla.org/show_bug.cgi?id=1238303

See related issues:
Add To Collection - List not sorted by name -- https://github.com/mozilla/addons/issues/676
Add To Collection - Cannot search the list -- https://github.com/mozilla/addons/issues/677

**Comment by smayer97** [comment]
Addtional related issues:
Add To Collection - There is no link to open collection from list of collections -- https://github.com/mozilla/addons/issues/679

NOTE: Without all these 4 changes to re-implement the original design, the 'new' Add To Collection has VERY LIMITED usefulness.

**Comment by decembre** [comment]
I have filled too about that (with screnshot):
<a href="https://github.com/mozilla/addons-frontend/issues/4331">Improve Collection Function in the new design Addon pages #4331</a>

**Comment by smayer97** [comment]
BTW, you can review these discussions started 2 years ago about why this set of features is SO important.
https://discourse.mozilla.org/t/no-favorite-button-in-new-amo-design/8015/40
and
https://github.com/mozilla/addons-server/issues/2264

**Comment by jvillalobos** [comment]
@smayer97 Is the objective here to avoid adding an add-on to the same collection again? Or to be reminded that you've already added it to other collections?

**Comment by smayer97** [comment]
The latter primarily...basically to be able to identify all the collections to which the add-on already belongs when trying to add an add-on, just like the old design.

Never considered the former as the old design that was never possible, so therefore never an issue. And trying with new design, there is a notification that alerts that "This add-on already belongs to the collection" so the check is there and not an issue...but then, if the functionality is set up like the old design, where the user can see which collections have a the add-on already, this warning is not necessary.

To be clear, the way it worked in the old design that listed all the collections, if the add-on was not part of a collection, you could select each collection to add it to, but if the add-on already is there, you could uncheck the collection to remove it from the collection. 

This is actually the desired goal of this feature. As I write this I realize that may this feature has been unclearly recorded...the actual desired functionality should be:

- show all collections that Add-on belongs to
- be able to either add to or remove from a collection the add-on . Old design used user selectable Check Mark next to the name of the collections in the list.  This is very well captured in the second animated screen capture by decembre in this thread, showing how the old design worked https://github.com/mozilla/addons-frontend/issues/4331
(is there anyone that is familiar with the old design and functionality?)

(sorry, cannot find way to copy and paste link to direct entry in that thread)

HTH

**Comment by jvillalobos** [comment]
Duping this to https://github.com/mozilla/addons-frontend/issues/4331

**Comment by smayer97** [comment]
For any reading this, you may want to follow the conversation in this thread here: https://github.com/mozilla/addons-frontend/issues/4331 and especially here: https://github.com/mozilla/addons-frontend/issues/4331#issuecomment-381342181
