### ISSUE TITLE
Add To Collection - There is no link to open collection from list of collections

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons#679]
### Describe the problem and steps to reproduce it:
When you click the Add To Collection menu, there is no link to be able to open the collection directly, like in the old design.extremely useful to be able to then go add notes to the add-on in the collection.

### What happened?
No link next to collection names to click

### What did you expect to happen?
To have a link next to each name of the collections in the list to be able to open the collection.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

This was an extremely useful feature to be able to manage collections before or after adding an add-on, e.g. review and/or the contents of a collection before or after adding an add-on, like add a note to the newly added add-on, delete an old add-on in the same collection, etc.

Add To Collection - List not sorted by name -- https://github.com/mozilla/addons/issues/676
Add To Collection - Cannot search the list -- https://github.com/mozilla/addons/issues/677
Add To Collection - No indicator showing which collection(s) the add-on already belongs to   -- https://github.com/mozilla/addons/issues/678

NOTE: Without these changes to re-implement the original design, the 'new' Add To Collection has VERY LIMITED usefulness.

**Comment by jvillalobos** [comment]
Given the use case, it may make sense to linkify the collection name in the notification that appears after an add-on is added to it, or it could be a link next to it ("Edit", "Add Notes", or something like that).

**Comment by jvillalobos** [comment]
My argument is that the Add to Collection menu should be limited to what it's meant to do, instead of being a complete management tool. Having so many features crammed into a little popup makes it harder to use for most users. It optimizes usage for power users, at the expense of more casual ones.

The changes to collections are intended to make the feature simpler and easier to maintain, so some functionality will be lost. Providing a link in the confirmation message serves the purpose of giving the user a way to edit the collection after adding an add-on to it, without making changes to the popup itself. I think that's the way we should go.

**Comment by smayer97** [comment]
For any reading this, you may want to follow the conversation in this thread here: https://github.com/mozilla/addons-frontend/issues/4331 and especially here: https://github.com/mozilla/addons-frontend/issues/4331#issuecomment-381342181

**Comment by smayer97** [comment]
So is this being worked on please? That is, a way to get to the Collection an add-on was added to from that same page? 

At the moment, if you want to add a comment, or maybe even remove it because it was added to the wrong collection, you have to open the My Collection page, find the Collection, then open it, and find the add-on. 

As simple hyperlink to the Collection to which it was just added as part of the message "Add-on was added to xxx Collection" would be a nice way to do this.

**Comment by smayer97** [comment]
Any chance that at least "A simple hyperlink to the Collection to which it was just added as part of the message "Add-on was added to xxx Collection" " could be done?

**Comment by smayer97** [comment]
Also please consider applying the same solution to these 2 issues too:
https://github.com/mozilla/addons-frontend/issues/8998

https://github.com/mozilla/addons-frontend/issues/8997

**Comment by decembre** [comment]
"They" don't want revert to their old and useful "Ads to collection" function...
Many users explain  (with goods arguments) why it's an error to break it.
Noway.
And agree for some mini minimal change about it seems strangely out of their brain:
I don't understand why.
Like they don't understand why we continue to ask them.
;-)

**Comment by smayer97** [comment]
still needed.

**Comment by smayer97** [comment]
looking forward to this getting added

**Comment by decembre** [comment]
I always a problem on Addon page.
In the Collection area:
We don't see in which coll it was added before.
We can't delete it from a previous coll.
And  yes, we can't open it from here.

**Comment by smayer97** [comment]
Please keep this change request alive.

**Comment by decembre** [comment]
It should be simple to re-implement these functions:
Don't close this request, please.

**Comment by smayer97** [comment]
Why was this forced to be closed? Please re-open this!!!
