### ISSUE TITLE
Make all unlisted add-ons full by default

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#68]
With the removal of the distinction between preliminary and full add-ons in Firefox, we should reflect that in AMO by removing this checkbox:

https://www.dropbox.com/s/aqtyx2762ouhc32/Screenshot%202016-03-16%2016.18.09.png?dl=0

And marking all unlisted add-ons as fully reviewed as per in person chat with @wagnerand.

**Comment by jvillalobos** [comment]
> And marking all unlisted add-ons as fully reviewed as per in person chat with @wagnerand.
How will this work? Will the existing versions be signed with the full cert? Or is this just a status change?

**Comment by wagnerand** [comment]
In 46, Firefox accepts sideloading for both prelim. and fully reviewed
add-ons per https://bugzilla.mozilla.org/show_bug.cgi?id=1245956.

**Comment by andymckay** [comment]
That was just referring to new add-ons, I don't see a need to resign old add-ons.

**Comment by diox** [comment]
> And marking all unlisted add-ons as fully reviewed as per in person chat with @wagnerand.

Can you expand on that ? Currently if I'm reading the code right, when you submit an unlisted add-on its status ends up being either `Awaiting Preliminary Review` or `Awaiting Full Review` depending on whether it's using sideloading or not. You want, in addition to removing the sideloading distinction, making them `Fully Reviewed` directly ?

**Comment by andymckay** [comment]
@wagnerand spoke about this in Berlin and I think he said making them `Awaiting Full Review` so they become `Fully Reviewed` but I'd let @jvillalobos and @wagnerand make the call on that.

**Comment by diox** [comment]
Stepping through the code it turns out I misread it and that immediately after setting the status to `Awaiting Preliminary Review` or `Awaiting Full Review` we changed it to `Preliminary reviewed` or `Fully Reviewed` - because signing does that.

**Comment by jvillalobos** [comment]
The answer the question, yes, we want unlisted add-ons to get `Fully Reviewed` when signed.
