### ISSUE TITLE
Adbloc for Firefox

### ISSUE THREAD

**Issue by chrisburrow** [mozilla/addons#680]
#For some reason when I try to download adbloc for firefox from the add on manager page it looks like it is happening and asks the necessary permissions, but it doesn't actually happen

**Comment by muffinresearch** [comment]
@chrisburrow Can you provide screenshots or urls to show where you are when this appears to go wrong?

In this issue tracker you can upload a screenshot by dragging an image onto the comment form text field.

**Comment by chrisburrow** [comment]
Have sorted it now thanks, operator error !!!

Sent from Yahoo Mail on Android 
 
  On Thu, 29 Mar 2018 at 12:38, Stuart Colville<notifications@github.com> wrote:   
@chrisburrow Can you provide screenshots or urls to show where you are when this appears to go wrong?

In this issue tracker you can upload a screenshot by dragging an image onto the comment form text field.

**Comment by tofumatt** [comment]
Thanks for letting us know it's fixed! 😄
