### ISSUE TITLE
Twitter cards not rendered with AMO addon links

### ISSUE THREAD

**Issue by cedricium** [mozilla/addons#681]
### Describe the problem and steps to reproduce it:
Using an addon link (such as https://addons.mozilla.org/en-US/firefox/addon/honey/) on Twitter fails to render a [Twitter card](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup). Explicit use of the `twitter:` property in the `<head>` element may be necessary to fix this.

### What happened?
Using an addon link on Twitter (for both a tweet and a DM) fails to create a Twitter card.

### What did you expect to happen?
A Twitter card should be created, similar to a Chrome extension link being used in Twitter (see below).

### Anything else we should know?
**AMO link fails to create card:**
![screenshot-2018-3-29 card validator twitter developers](https://user-images.githubusercontent.com/16343560/38097507-6eff09dc-332a-11e8-863e-61b29c8e4be2.png)

**Chrome webstore link successfully creates card:**
![screenshot-2018-3-29 card validator twitter developers 1](https://user-images.githubusercontent.com/16343560/38097581-9d17e4e2-332a-11e8-9c4e-c71d00813157.png)

**Comment by diox** [comment]
It would be kinda cool. Maybe a good first bug with a frontend mentor? /cc @tofumatt for his opinion

**Comment by tofumatt** [comment]
Yes, this would be very cool actually. I'm totally for it and would happy to mentor the feature. 👍 

Any contributor looking to work on this should have a good sense of how Twitter cards are implemented (https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started).

**Comment by eviljeff** [comment]
Mentor is @tofumatt 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by championshuttler** [comment]
I would like to work on it

**Comment by championshuttler** [comment]
@tofumatt , I am confused where I have to add the meta tag of twitter card

**Comment by tofumatt** [comment]
You would need to add it to the head of the document. I believe that’s in a server html file, but I’ll have to find it later (I’m on my phone right now)

- Matt (Sent from mobile)

**Comment by cedricium** [comment]
I believe it would be added to this file:

https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/templates/addons/impala/details.html

**Comment by eviljeff** [comment]
that would be where to edit on addons-server, yes.  Though as we default to the new frontend for requests, I would have assumed it would be a page on addons-frontned (where we don't appear to serve any meta data currently)

**Comment by tofumatt** [comment]
Yeah, sorry, when I said "server HTML" I didn't explain myself well.

It's this file: https://github.com/mozilla/addons-frontend/blob/master/src/core/containers/ServerHtml.js that contains our `<head>` for the frontend.

Stuff would need to go in there… although actually using `<helmet>` in our own `amo/components/App` would be better because `ServerHtml.js` is used for all apps and this is only for AMO.

**Comment by championshuttler** [comment]
I am going with ServerHTML.js file @tofumatt

**Comment by muffinresearch** [comment]
This has been fixed:

<img width="1136" alt="card_validator___twitter_developers" src="https://user-images.githubusercontent.com/1514/49884757-797cb700-fe2d-11e8-9869-c49be89ebdff.png">
