### ISSUE TITLE
Facebook Container: doesn't open messenger.com in the container

### ISSUE THREAD

**Issue by davidgerard** [mozilla/addons#682]
### Describe the problem and steps to reproduce it:
messenger.com is the Facebook URL for the Facebook messenger. It should be included in the Facebook container.

### What happened?
I opened messenger.com and it appears it isn't in the container (no blue bar as on a facebook.com page).

### What did you expect to happen?
Blue bar as on a facebook.com page.

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on. The support site listed for that add-on is at: https://github.com/mozilla/contain-facebook, so it should just be a matter of filing this issue at that repo.

Sorry for the confusion and thanks for the bug report! 😄
