### ISSUE TITLE
Icon Bug

### ISSUE THREAD

**Issue by nycz42** [mozilla/addons#683]
### Describe the problem and steps to reproduce it:
Icon does not appear in tool bar.
### What happened?
After installing the icon does not show in toolbar.
### What did you expect to happen?
Icon to be visible.
### Anything else we should know?
Still clickable even though it is invisible.

**Comment by tofumatt** [comment]
What is the exact issue you'e experiencing and for add-on in particular are you experiencing it with? Links to add-ons and screenshots of your issue would really help because I'm not sure what issue you're having.

**Comment by nycz42** [comment]
The add-on with the issue is Turn Off the Lights and It does not show the
icon on the toolbar. It is there but invisible. In the screen shot it
should be next to the Ublock Origin icon.

**Comment by tofumatt** [comment]
You should contact the add-on author directly using https://www.turnoffthelights.com/support/

This is the issue tracker for the add-ons website itself and we can't provide support for individual add-ons. Sorry about that!
