### ISSUE TITLE
Odd behaviour using Firefox Multi-Account Containers

### ISSUE THREAD

**Issue by Velarier** [mozilla/addons#684]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I have some bookmark folders with 20+ pages which I open all at once (pages where I check for updates, new posts/content).
### What happened?
If there are 3 or more Firefox 59.0.2 windows open (separate Firefox tabs in windows 7 x64) and I order to open all tabs (belonging to an account different from default) in one window.
When I change window while the pages are loading, some will change from the window I ordered them to open, to the one I changed my view...
### What did you expect to happen?
I don't remember this happening before using the Multi-Account Container. It might be something in the variable that keeps the window or tab sequence info, since the pages take a bit longer to be added to the window while the correct container is selected.
I hope to be in the correct area to report this...

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on.

If you're having an issue with an add-on please contact the developer directly; you can find a link to their contact details on the add-on page on https://addons.mozilla.org/
