### ISSUE TITLE
"Works with" text and "forbidden" icon is confusing

### ISSUE THREAD

**Issue by madb1lly** [mozilla/addons#687]
### Describe the problem and steps to reproduce it:
1. Visit Mozilla add-on pages: https://addons.mozilla.org/en-US/firefox/user/mozilla/?page=2 (probably also other developer pages too)
2. See an add-on which has a "forbidden" icon and "Works with Firefox xyz" next to the download button.
Firefox on Windows:
![image](https://user-images.githubusercontent.com/25123631/38254897-af1b9eac-375a-11e8-8a4d-d535d56e0159.png)
Firefox beta on Android:
![image](https://user-images.githubusercontent.com/25123631/38254920-bf432b7e-375a-11e8-986a-7b2f451715e0.png)

### What happened?
The "forbidden" icon normally means that something can't be done, but in this case it looks like the add-on can be downloaded, which is confusing. What is this icon meant to mean? How does it help me?

### What did you expect to happen?
The text and icons should indicate if I can or cannot download the add-on for the browser I'm currently using.

**Comment by eviljeff** [comment]
We're in the process of completely rewriting the account profile pages so they won't look like this in a few weeks time, and will have different text and icons.  So closing this issue.
