### ISSUE TITLE
Feature request: extra filters to narrow down results

### ISSUE THREAD

**Issue by madb1lly** [mozilla/addons#688]
Hi Add-ons team!

Please can you consider adding additional filters to narrow down results, e.g. if I'm looking at add-ons made by Mozilla (https://addons.mozilla.org/en-US/firefox/user/mozilla/) and I don't want to see language packs, only functionality extensions.

Thanks :)

**Comment by tofumatt** [comment]
mozilla/addons-frontend#2749 might cover this one.

**Comment by madb1lly** [comment]
It's not clear to me that the description for the user profile page on the new website includes these filters.

**Comment by eviljeff** [comment]
@tofumatt wrong issue # ?

**Comment by tofumatt** [comment]
Hmm, yup. I think I misread the issue.

**Comment by jvillalobos** [comment]
I think this is a too-specific feature to be worth implementing. Also, language packs will eventually disappear as listed add-ons on AMO and will be exposed in Firefox differently, so that will remove a lot of the noise in the Mozilla account.

**Comment by madb1lly** [comment]
You mean that in general, filters for types of add-ons on the user profile page is too specific a feature?

I'll be honest, I don't use many add-ons so don't look at many user profile pages - maybe Mozilla user is an exception for the number of add-ons it has.
