### ISSUE TITLE
Include a link to source code repository

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/addons#689]
For example, given https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/ it's not clear to me how I could get the source code if I wanted to contribute or fork it.

**Comment by jrmuizel** [comment]
Ha, I've already filed this. https://github.com/mozilla/addons/issues/463

**Comment by jrmuizel** [comment]
Actually, going from https://github.com/mozilla/addons-server/issues/5135#issuecomment-302178477 it seems like it would still be valuable to provide a link to the upstream repo.

**Comment by jvillalobos** [comment]
We decided not to include it as part of the first version of the new front-end in https://github.com/mozilla/addons-frontend/issues/2762. Worth revisiting. There doesn't appear to be a standard manifest field for it, so it would be an AMO field.

**Comment by eviljeff** [comment]
@jvillalobos "worth revisiting" == we should implement it?  We can add it to devhub and the Addon model easy enough... if it's going to be exposed on addons-frontend sometime soon.

**Comment by jvillalobos** [comment]
We don't have any plans to tackle developer tools in Q2 or even Q3, and this is low priority anyway. While I agree with the proposal, I'd rather focus on other things.

**Comment by davidhedlund** [comment]
Repositories are useful to find out more about add-ons. Adblock Plus doesn't contain a license file in the add-on installation file at this writing (the .xpi file) like the repository.

**Comment by 532910** [comment]
Dear Moz://a!

I see a lot of addons with the open source license on AMO but sometimes it's extremely hard or totally impossible to find their sources. The link to the source must be mandatory. Like on F-Droid for example. Moreover these links should be automatically checked for availability.

**Comment by davidhedlund** [comment]
Current links that can be added:
> Homepage
> Support Site
> Support Email

I recommend a 4th resource:
> Repository

# Example
 This is how it would look like on the [Adblock Plus](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/) page:

> [Homepage](https://adblockplus.org/)
> [Support Site](https://adblockplus.org/forum/)
> [Repository](http://hg.adblockplus.org/)

Repositories are useful to find out more about add-ons. Adblock Plus doesn't contain a license file in the add-on installation file at this writing (the .xpi file) like the repository.

**Comment by 532910** [comment]
The link to the Issue Tracker also should be mandatory.

**Comment by helmo** [comment]
It seems that this option was discarded  because of a 'source-viewer i/o performance' issue in https://github.com/mozilla/addons-server/issues/5135

Shutting down such a crucial part of the of the free software world seems a shame. A link to the source is not only good for transparency, but an easy path to contribute.

I would be happy with a link to repo on GitHub or GitLab ... or even a url to a zipfile ;) So a text field that the add-on author is suggested to fill.

I was surprised that such a link is not just a requirement to get any add-on published.

**Comment by nekohayo** [comment]
I've often wondered, as a user, why this is not systematically included. There is no other way for me to judge the quality and trustworthiness of an extension but to look at the issue tracker and potentially the source code.

For me, this is a security issue. It's fun to see that such and such add-on is licensed under the GPL or X11/MIT, but if there is no link to an issue tracker, no way to email the developer, and no link to the source code repository, I have absolutely no way to tell whether an add-on has potentially malicious code or over-arching permissions in it. Please add this feature back as mandatory fields the developer must fill (and that can get validated by admins or something); the absence of such information—which would help some users ascertain whether a particular add-on is a potential attack vector or not, or simply to make suggestions and contributions in the proper place—is not acceptable for a browser that presents itself as the champion of security, privacy and free/open-source software.

**Comment by davidhedlund** [comment]
This issue is still relevant to fix.

**Comment by diox** [comment]
This was marked stale because nobody is working on it. If you freel strongly about this feature, I encourage you to work on implementing it and submitting a pull request.

**Comment by helmo** [comment]
Building a PR for this is slightly out of my skillset ... but the frontend code seems to be:

- https://github.com/mozilla/addons-frontend/blob/673d575284042e4d51b4db59ab574fc8e4f4bcf6/src/amo/components/AddonMoreInfo/index.js#L69

- https://github.com/mozilla/addons-frontend/blob/master/src/core/types/addons.js#L96

And [addons-server component](https://github.com/mozilla/addons-server/search?q=support_url&unscoped_q=support_url) will also need a field for it.

**Comment by davidhedlund** [comment]
> Building a PR for this is slightly out of my skillset ... but the frontend code seems to be:
> 
>     * https://github.com/mozilla/addons-frontend/blob/673d575284042e4d51b4db59ab574fc8e4f4bcf6/src/amo/components/AddonMoreInfo/index.js#L69
> 
>     * https://github.com/mozilla/addons-frontend/blob/master/src/core/types/addons.js#L96
> 
> 
> And [addons-server component](https://github.com/mozilla/addons-server/search?q=support_url&unscoped_q=support_url) will also need a field for it.

Thanks.

**Comment by jvillalobos** [comment]
Broke this down into https://github.com/mozilla/addons-server/issues/15174 and https://github.com/mozilla/addons-frontend/issues/9568, so I'm closing this issue now.
