### ISSUE TITLE
Uploading via jpm failed with a max version of "48.*" when that version existed.

### ISSUE THREAD

**Issue by Standard8** [mozilla/addons#69]
I just tried uploading an add-on via jpm, it said:

```
JPM [info] Signing XPI: ./dist/loop@mozilla.org.xpi
Validating add-on [....................................................................................................]JPM [info] Validation results: https://addons.mozilla.org/en-US/developers/upload/68abd90609874e02be78fa3113ae0f35
JPM [info] Your add-on failed validation and could not be signed
JPM [info] FAIL
```

When I looked at the validation report it said:

```
Error: The maximum version that was specified is not an acceptable version number for the Mozilla product that it corresponds with.

Version "48.*" isn't compatible with "firefox".
```

The web page at https://addons.mozilla.org/en-US/firefox/pages/appversions/ lists 48.\* as a valid version number.

If I change the max version to "48.0", then it uploads correctly.

**Comment by andymckay** [comment]
@diox and @EnTeQuAk, presumably this is a version problem addons-server? Not sure why this would happen.

**Comment by diox** [comment]
Erm, I somehow missed that notification... a year ago. Yeah. Sorry about that... @Standard8 do you still have this issue? I assume with the switch to WebExtensions this is going to be less relevant...

**Comment by Standard8** [comment]
Yeah, I suspect this is probably not an issue now, I don't know if it stopped happening or not - we stopped developing Hello.
