### ISSUE TITLE
Add Liberapay as a donation platform

### ISSUE THREAD

**Issue by jorgesumle** [mozilla/addons#691]
### Describe the problem and steps to reproduce it:

We cannot choose Liberapay as a donation platform.

### What happened?

We got an error and couldn't go on.

### What did you expect to happen?

I expect to be able to use a Liberapay URL.

### Anything else we should know?

Contact us by [email](mailto:support@liberapay.com), [Gitter](https://gitter.im/liberapay), IRC (#liberapay on Freenode) or through one our our [issue trackers](https://github.com/liberapay/salon/issues/) if you want to know more about Liberapay and how it works. It's a [legal](https://liberapay.com/about/legal) donation platform registered in France. We registered this issue https://github.com/liberapay/salon/issues/221 and jorgev pointed us here from the IRC channel #amo

**Comment by jvillalobos** [comment]
Looks legit. Moving over to https://github.com/mozilla/addons-server/issues/8004
