### ISSUE TITLE
Docs on ReadTheDocs aren't updating - builds are failing

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#693]
Might be the same underlying mozilla/addons-server#7809 but we last updated requirements (or any code) 3 years ago so that's odd.

http://readthedocs.org/projects/addons/builds/ shows builds for the past 3 months have been failing (luckily we only make minor occasional changes to these docs)

**Comment by muffinresearch** [comment]
Fixed by changing this setting:

![33148218-fb06aec6-cf98-11e7-945a-97d1a95cc114](https://user-images.githubusercontent.com/1514/39247492-d8e5104c-4899-11e8-94aa-4c75eb8cb441.png)
