### ISSUE TITLE
https://addons.mozilla.org/en-US/firefox/addon/a-bible-verse-toolbar/

### ISSUE THREAD

**Issue by rezwarlord** [mozilla/addons#694]
I have used this addon for a few years and now my Firefox updated to Firefox Quantum and now the addon is gone and when I attempted to re-add it, the window say's: Not compatible with Firefox Quantum

What can I do or what can be done so I can use this addon again?

This add-on is not compatible with your version of Firefox.
A Bible Verse Toolbar by CarvedArt
Restart RequiredRestart Required
Not compatible with Firefox Quantum Not compatible with Firefox Quantum

A Firefox toolbar made to display bible verses.
Add to Firefox

https://addons.mozilla.org/en-US/firefox/addon/a-bible-verse-toolbar/

**Comment by jvillalobos** [comment]
As explained in the previous comment, developers are responsible for keeping their add-ons working* and there isn't anything we can do on our side. You can try contacting the developer or looking for an alternative.

\* Note: the change to Quantum was massive, so porting some add-ons was hard and even impossible in some cases.
