### ISSUE TITLE
Image uploads in devhub stuck on "Image changes being processed"

### ISSUE THREAD

**Issue by elisaceze** [mozilla/addons#697]
### Describe the problem and steps to reproduce it:

When I wanted to upload a new logo and new pictures to change the Hello Talent app. I deleted the old content and upload the new one. But it just perpetually charging ... And it doesn't upload. 
![hello talent app no pictures](https://user-images.githubusercontent.com/34246030/38669288-7e96bbcc-3e35-11e8-9710-f69fb99a0974.PNG)
![icon charging](https://user-images.githubusercontent.com/34246030/38669296-8599a858-3e35-11e8-9e7b-31dcf46d882a.PNG)

**Comment by jvillalobos** [comment]
@elisaceze Can you attach the images you tried to upload?

/cc @diox who I think was working on the image processing code recently.

**Comment by muffinresearch** [comment]
@diox looking at this it appears to be editing the FR locale - do you know if there's any locale related issues wrt image uploads / processing?

**Comment by diox** [comment]
The locale shouldn't have any impact on the image processing/upload itself - the only thing it impacts is the default locale for the caption, so I don't think that's it.

Something must be wrong with the images or maybe the upload itself, on the client-side. Not sure if the ones attached to github will be enough to reproduce it since github might do their own processing on them, but I'll take a closer look.

**Comment by diox** [comment]
I can reproduce locally with those specific images. Everything looks ok in the logs but somehow the thumbnail and resized versions end up as 0-bytes files. It's possible there is something wrong with the optimization step, or maybe it's related to the Python Imaging Library. I'll continue digging.

**Comment by diox** [comment]
Well, this is interesting. Running the images through `pngcrush` with the same arguments we use works... on the original image. If used on the thumbnail we generate through `PIL` first, then it fails with:
```
  pngcrush caught libpng error:
   profile 'ICC Profile': 0h: PCS illuminant is not D50
```

And generates an empty file. Sadly, it returns 0 as it does when everything goes right, so we don't notice the error and keep the broken image.

**Comment by diox** [comment]
@elisaceze we fixed the root of the issue and if everything goes right, the fix should go into production next Thursday around noon pacific time. Note that you'll need to delete and re-upload your screenshots.

QA:
- Please try uploading various images as previews or icons and see if anything goes wrong. In particular try to get images with color profiles built-in the image. The 2 attached to this issue above do contain one, but please try others if you have access to an image editing software that does this.

**Comment by AlexandraMoga** [comment]
I have uploaded different images and icons via Dev Hub, including the samples provided above  and I haven't experienced upload/processing issues.

I'm going to mark this issue as verified fixed, on AMO stage with FF59, Win10x64

**Comment by gulux** [comment]
NO ACTION REQUIRED, just for further information/investigation.
I experienced exactly this issue with screenshots from Linux' Spectacle exported directly to Gwenview and stored as png from there.
After opening the files in GIMP and re-exporting them to png with -selected- options:
Interlacing (Adam7), resolution, creation time, values for transparent pixels, 8bpc RGB, preview
it worked.
Examples:   withfilter.png(before)   withfilter0.png(after GIMP manipulation)
![withfilter](https://user-images.githubusercontent.com/49115449/55286864-d0d57180-53a1-11e9-81f0-1971c68a7a76.png)
![withfilter0](https://user-images.githubusercontent.com/49115449/55286865-d6cb5280-53a1-11e9-90d4-2c2af33b53a4.png)
My Add-on site:
https://addons.mozilla.org/de/firefox/addon/dudle-name-filter/

**Comment by GChristensen** [comment]
Having the same issue:
![being processed](https://user-images.githubusercontent.com/170405/175241259-5b170a21-4741-4649-bf8c-29efd6966c31.png)

Tried to save image with different editors and formats, nothing helps.
The add-on: https://addons.mozilla.org/en-US/firefox/addon/add-torrent-to/

**Comment by diox** [comment]
@GChristensen could you open a new issue and provide a zip with the images you tried to upload ? (inside a zip to ensure nothing on GitHub's side changes them)
