### ISSUE TITLE
Please include English United States (en-US-large) Dictionary on Language tools page

### ISSUE THREAD

**Issue by jorgk3** [mozilla/addons#70]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1257464:

Please include English United States (en-US-large) Dictionary
https://addons.mozilla.org/en-US/firefox/addon/us-english-dictionary/

on the Language tools page
https://addons.mozilla.org/en-US/firefox/language-tools/.

The current language tools page only contains a link to this add-on:
https://addons.mozilla.org/en-US/firefox/addon/united-states-english-spellche/

It would be good to show an alternative.

Also, the second add-on is poorly maintained, see bug 1236375 )https://bugzilla.mozilla.org/show_bug.cgi?id=1236375). After being out of date for year, the author, Giuliano Masseroni, has fallen behind once again.

Note that providing an English dictionary to users of localised versions of Firefox and other Mozilla products is important. A dictionary of poor quality reflects badly on the overall quality of Mozilla products.

It would be good to resolve this situation for the benefit of Mozilla users worldwide.

In some discussion on dev-platform someone had the opinion that Mozilla should look better after the "official" US English dictionary:
https://groups.google.com/d/msg/mozilla.dev.platform/3q7AATMNrsQ/knY1CmV5BQAJ

That
https://addons.mozilla.org/en-US/firefox/addon/united-states-english-spellche/
is not actively maintained and that
https://addons.mozilla.org/en-US/firefox/addon/us-english-dictionary/
is not included on
https://addons.mozilla.org/en-US/firefox/language-tools/
is particularly frustrating.

I have worked with the maintainer of SCOWL, the upstream source of the dictionary data, on the following issues:
https://github.com/kevina/wordlist/issues/135
https://github.com/kevina/wordlist/issues/136
https://github.com/kevina/wordlist/issues/137
https://github.com/kevina/wordlist/issues/138
https://github.com/kevina/wordlist/issues/141
https://github.com/kevina/wordlist/issues/143
https://github.com/kevina/wordlist/issues/145

Some of the work went into the new SCOWL release of January 2016, yet Mozilla users of localised version don't get any benefit, since Giuliano Masseroni does not update his add-on.

I have also worked on bug 1235506 (https://bugzilla.mozilla.org/show_bug.cgi?id=1235506), bug 301712 (https://bugzilla.mozilla.org/show_bug.cgi?id=301712), bug 1238031 (https://bugzilla.mozilla.org/show_bug.cgi?id=1238031) and bug 1240916 (https://bugzilla.mozilla.org/show_bug.cgi?id=1240916) to improve the en-US dictionary that ships with Mozilla products. Users of FF 45 or TB 45 have the full benefit of the changes. However, Mozilla users of localised version don't get any benefit, since Giuliano Masseroni distributes some other dictionary and is promoted on the official language tools page. How sad.

The only thing that I could do to promote a better dictionary was to create my own add-on and post reviews to the outdated original add-on. These reviews regularly get removed although they adhere to the review rules. How sad again.

**Comment by jvillalobos** [comment]
Added to Language Tools page.
