### ISSUE TITLE
Problems with installing some addons

### ISSUE THREAD

**Issue by M00dyB45t4rd** [mozilla/addons#701]
Hi,

I've been trying to install some addons from the official Mozilla page (Facebook Container, Multi-account Containers, DuckDuckGo Privacy Essentials). For each of these addons the corresponding page said they cannot be installed, because they require FF v57, and I'm using FF v52. The thing is, I'm using the latest Firefox - 59.0.2. So, I have two questions:

1, How can I install these addons?
2, What makes the addon page incorrectly identify my Firefox version and how can it be fixed? Erm... that's actually three questions, let me start again. ;-)

Thanks a lot in advance.

**Comment by wagnerand** [comment]
Can you check whether you have `privacy.resistFingerprinting` set in `about:config`?

**Comment by M00dyB45t4rd** [comment]
Yes I have! I'd disabled it and managed to install the required addons, then I enabled it back - is that ok? Why does this option block installation of only some of the addons?

Thanks a lot for your help. :-)

**Comment by wagnerand** [comment]
That is what the option does. It changes your user agent, among other things. For more information, see https://www.torproject.org/projects/torbrowser/design/#fingerprinting-linkability
