### ISSUE TITLE
Editing comments doesn't update

### ISSUE THREAD

**Issue by marcoagpinto** [mozilla/addons#704]
### Describe the problem and steps to reproduce it:
I tried a second editing in a comment to a user of my speller and it didn't update my comment.

### What happened?
The text remains the same, my edit takes no effect.

### What did you expect to happen?
It should appear my edited comment.

### Anything else we should know?
https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2

**Comment by muffinresearch** [comment]
@marcoagpinto Is this the edit or was there another edit that didn't make it? 

<img width="880" alt="reviews_for_british_english_dictionary__marco_pinto__ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/39047813-3422af92-4493-11e8-8992-39143308a150.png">

**Comment by marcoagpinto** [comment]
Yes, @muffinresearch 

That edit didn't make it, and the same happened with the one before.

**Comment by muffinresearch** [comment]
> That edit didn't make it, and the same happened with the one before.

@marcoagpinto can you see it now? Is it just the case that you didn't see the update immediately?

**Comment by marcoagpinto** [comment]
No, it isn't still there :-(

**Comment by muffinresearch** [comment]
@marcoagpinto some changes are coming soon to the way caching works. This looks like it could be related. Once this issue is fixed https://github.com/mozilla/addons-server/issues/7743 is fixed and in production this should fix your issue.
