### ISSUE TITLE
Weird wacko login

### ISSUE THREAD

**Issue by TimBrengle** [mozilla/addons#706]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Normal login at https://addons.mozilla.org/en-US/android/ to user brengles@comcast.net (using correct password). Ended up logged in ok -- as user anonymous-7ba2c7d7d32f80e1802d6f552b024

### What happened?
I looked at my tablet's add-ons to see if my tablet had one which I often use on my phone. An add-on which I didn't know I had, Google Search Link Fix, had a green upward-pointing arrow at the right end of the listing. I like to keep everything updated, so I clicked on the arrow.
I was taken to a page which told me to log in to see the add-ons. I typed "brengles@comcast.net" into the text field and clicked Continue. As expected, I was taken to a password entry page. I entered the correct password for that email and clicked to sign-in. I was taken to https://addons.mozilla.org/en-US/android/
where I saw, in the upper right of the screen in tiny letters, that I was logged in as the anonymous user shown above. Of course, none of the things I expected to see were correct.

![screenshot_2018-04-25-00-05-31](https://user-images.githubusercontent.com/12003728/39231192-1991661c-481e-11e8-80fb-ee2af513f96e.png)

### What did you expect to happen?
A normal login : a page asking for my user name, a page asking for my password, and then access to the add-ons page using those credentials.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
This happens every time I attempt going to the add-on page.
The device being used is a Samsung Galaxy Tab 4 8.1 running android [5.1.1[](url)](`url`)

**Comment by diox** [comment]
No info from reporter and it just looks like an account with no display name set.
