### ISSUE TITLE
Don't error on invalid platform for search

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#708]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1457707

A search such as https://addons.mozilla.org/en-US/firefox/search/?q=blah&platform=OpenFoo&appver=59.0.2 gives an error on new frontend because the API rejects "OpenFoo" as an invalid platform; on the legacy frontend the invalid platform is silently ignored and it falls back to All Platforms.

The fix is either:
a) Don't error in the addons-server API; interpret an unsupported platform parameter as 'All'
b) addons-frontend catches the API error and does something - e.g. redirects to https://addons.mozilla.org/en-US/firefox/search/?q=blah&appver=59.0.2
( c) wonfix )

**Comment by landryb** [comment]
'OpenFoo' is invalid, 'OpenBSD' is a valid platform, it's just that AMO only supports/cares about Tier1. I would be fine with fallbacking to All for non-tier1.

c) wontfix ? really ?

**Comment by jvillalobos** [comment]
Given the direction we're moving towards with WebExtensions, I think we should drop the platform parameter from the Add-ons Manager search (cc @ddurst). That doesn't address this issue for all existing clients, though.

I would favor (b), since I think the API should do the "right" thing as much as possible.

**Comment by diox** [comment]
I'm not sure how much that helps us yet, but we're moving towards dropping platform and just using applications - which would be `firefox` or `android`, and already in the URL (that's the part after the locale at the beginning).

**Comment by landryb** [comment]
merge with mozilla/addons-frontend#4610 ?

**Comment by landryb** [comment]
@stale: issue still stands.

**Comment by jbeich** [comment]
Can someone tag this issue? I can still reproduce on `DragonFly` (BSD).
https://github.com/mozilla/addons/blob/cc943597a1d8d4e45189afa378b7222b3e7c4633/.github/stale.yml#L14-L22

**Comment by eviljeff** [comment]
The issue is stale, regardless of the tags or status of it - no-one is working on it and it won't suddenly start being worked on anytime soon.  If someone is willing to step up and contribute a fix then we can look at it, otherwise it may as well stay closed.  

https://github.com/mozilla/addons/issues/708#issuecomment-386100003 pointed to the fix being b) so probably best to dupe this issue with https://github.com/mozilla/addons-frontend/issues/4610 anyway and work on it there.
