### ISSUE TITLE
Enable ability to distribute multiple langpack versions for different channels at the same time

### ISSUE THREAD

**Issue by zbraniecki** [mozilla/addons#709]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1429610 we're pursuing the ability to dynamically fetch the list of available langpacks into Firefox at runtime and then install langpacks on fly.

This will fundamentally reshape how we handle language selection in the product and I expect that once we enable it people will start asking for the same for beta and dev edition channels.

If I understand correctly, AMO at the moment does not provide a way to offer different version of the langpack for different channels.

Filing this issue to track this project.

**Comment by zbraniecki** [comment]
Andrew pointed out that due to beta/dev-ed, we will need to work on the discovery. Filled bug https://bugzilla.mozilla.org/show_bug.cgi?id=1459056

**Comment by jvillalobos** [comment]
What are your expectations in terms of timing?

**Comment by zbraniecki** [comment]
No expectations yet. We plan to get the release channel enabled in 63 and I expect people to start asking for beta/dev-ed by then, but until then I wanted to get it on your radar to give you to time to fit it into our timeline and align any other work that may be related to it :)

**Comment by aswan** [comment]
See also https://github.com/mozilla/addons-server/issues/8180
