### ISSUE TITLE
en-US dictionary distributed by Giuliano Masseroni is out of date

### ISSUE THREAD

**Issue by jorgk3** [mozilla/addons#71]
The "official" en-US dictionary promoted by Mozilla at https://addons.mozilla.org/en-US/firefox/language-tools/ is out of date.

I have repeatedly asked the author to update it and I have posted reviews stating the fact that this is out of date, but all that happened was that my reviews got removed.

I am of the opinion that Mozilla should ensure that an up-to-date English US dictionary is distributed. It would be best to withdraw that add-on altogether and instead distribute the officially Mozilla-maintained en-US dictionary that ships with Firefox and Thunderbird, see discussion here: https://groups.google.com/d/msg/mozilla.dev.platform/3q7AATMNrsQ/knY1CmV5BQAJ

The Mozilla-maintained en-US dictionary that ships with Firefox and Thunderbird is better than the "normal" SCOWL size used by the add-on author and should be officially distributed (see previous paragraph). If you want to read about the differences, they are explained here: https://addons.mozilla.org/en-US/firefox/addon/us-english-dictionary/ (my add-on).

As to the severity of the faults in the out-of-date dictionary:
In the outdated SCOWL data of August 2015 the following was correct spelling:
He get's his food in the cafeteria and then he give's it to his friend.
The child is her's.
The following was incorrect spelling:
His children's teacher is a nice guy (children's was flagged as wrong).

Consider one of the 500.000 users of the add-on, some guy or girl who doesn't speak English well, they download the "officially" promoted dictionary, the follow its suggestions, they post bad English into an online job application page and don't get the job. And they won't even know why. Sorry, Mozilla has let them down, because they protect one negligent add-on contributor.

**Comment by wagnerand** [comment]
https://addons.mozilla.org/en-US/firefox/addon/united-states-english-spellche/ has just been updated.

**Comment by jorgk3** [comment]
OK, and Giuliano is now using the "large" SCOWL size. That's a good move. I can therefore retire my add-on. I will request removal from https://addons.mozilla.org/en-US/firefox/language-tools/ in another bug.

**Comment by jorgk3** [comment]
Changed my mind. Since my add-on is already on https://addons.mozilla.org/en-US/firefox/language-tools/ I've now switched my dictionary to distributing the Mozilla dictionary. Now the user has the choice of two excellent dictionaries. That's the best solution.

**Comment by jorgk3** [comment]
On 18/03/2016 11:10, Andreas Wagner
      wrote:
    
    
      https://addons.mozilla.org/en-US/firefox/addon/united-states-english-spellche/
        has just been updated.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub
      
        
          
          
        
        
      
    
    If you could approve my change to
      https://addons.mozilla.org/en-US/firefox/addon/us-english-dictionary/
      then we can get out of this quickly with the greatest benefit to
      the user.
    Jörg.
