### ISSUE TITLE
Add option to supress version check

### ISSUE THREAD

**Issue by graywolf** [mozilla/addons#713]
### Describe the problem and steps to reproduce it:

There is currently no way to supress version check when trying to install from addons.mozilla.com.

### What happened?

addons.mozilla.com complained that my browser is old (52) and did not allow me to install addon.

### What did you expect to happen?

Having option to supress the check since I have up-to-date firefox (59), but with `resistFingerprinting = true`. So the extension work without any problems, I just could not install it without disabling fingerprinting resistance first.

Some checkbock along the lines of "Yes I know what I'm doing install anyway" would be nice to have.

### Anything else we should know?

It works in firefox (60) since it has `Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0` useragent even when resistfingerprinting on but I have no idea if it will break again in the next version.

**Comment by diox** [comment]
Hi,

This issue has already been reported, see https://github.com/mozilla/addons-frontend/issues/3445 for more information (including a workaround)

**Comment by graywolf** [comment]
Great to hear there is a workaround! But still, I think it would be nice is user could find said workaround without having to scour the github issues to find it...

The error message could say something like `(If you believe your FF version was detected incorrectly, you can try forcing the installation by right clickinkg the + Add to Firefox button and opening in a new tab.)`.
