### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by cedk** [mozilla/addons#715]
### Describe the problem and steps to reproduce it:
I can not login any more with my account to addons.mozilla.org

### What happened?
When clicking on "signin" button on accounts.firefox.org, the answer is a JSON containing:
{"detail":"Internal Server Error"}

### What did you expect to happen?
I expected to be redirected to addons.mozilla.org, logged with my user.

### Anything else we should know?
I can log to accounts.firefox.org with the same account (and I'm logged on it).
I can also log with another account.

**Comment by muffinresearch** [comment]
@cedk hi sorry to hear you're having issues, what site is showing the JSON error? Is it https://addons.mozilla.org or https://accounts.firefox.com ?

**Comment by cedk** [comment]
It is https://addons.mozilla.org/api/v3/accounts/authenticate/

**Comment by EnTeQuAk** [comment]
Interesting, looking at our sentry - https://sentry.prod.mozaws.net/operations/olympia-prod/?query=is%3Aunresolved+authenticate - doesn't show any internal server errors directly on that endpoint. Can you share maybe the email that you used to autheticate privately with me via cgrebs@mozilla.com so that I can look through our logs a bit better.

**Comment by cedk** [comment]
@EnTeQuAk did you receive my email? Because I still get the error when trying to login.

**Comment by EnTeQuAk** [comment]
Yes, I received it. I was on PTO and on a conference the last 2 weeks. I'll look into this shortly.

**Comment by cedk** [comment]
I still get the issue. Please tell me if you need more information?

**Comment by EnTeQuAk** [comment]
Hard to say tbh, I started looking into this. For now I can't find anything specifically to your email address or username.

Does it help (although I'm sure you already tried) to logout completely from accounts.firefox.com and login again?

**Comment by cedk** [comment]
Yes I tried. I also tried to login from another computer but the same happens.
But I can login with a different account.

**Comment by diox** [comment]
@EnTeQuAk is this an error on our side or FxA's? Did you end up finding a stacktrace ?

**Comment by cedk** [comment]
FYI, I still get the issue. I just made a login request on Tue Jul  3 21:44:46 UTC 2018

**Comment by cedk** [comment]
I wanted to publish a new version of my addons but I still can not login with my personal account.

**Comment by wagnerand** [comment]
@cedk Sorry for the delay here. Could you please email amo-admins AT mozilla DOT org and include your email address you're trying log in with, as well as your previous email addresses you used on Firefox Accounts or AMO, if any? We'll get it sorted there.

Thank you.

**Comment by wagnerand** [comment]
Assinging myself so I don't forget to close this.

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk is this an error on our side or FxA's? Did you end up finding a stacktrace ?

I didn't end up finding anything so far, neither in sentry nor in kibana. There are some that seem related but none that actually describes the issue we see here.
