### ISSUE TITLE
Cannot install addons when using privacy.resistfingerprinting

### ISSUE THREAD

**Issue by chunacatsunflower** [mozilla/addons#716]
### Describe the problem and steps to reproduce it:
set privacy.resistfingerprinting to TRUE.  Go to firefox add ons site (e.g., https://addons.mozilla.org/en-US/firefox/addon/noscript/)  The add ons site reports that I am using firefox version 52 (actually version 59) and refuses to let me install the add on.

### What happened?
Could not install add on due to incorrect browser user-agent string detection.

### What did you expect to happen?
the firefox site should be using the user-agent string as submitted.  I even installed a user-agent modification add-on, but got the same results.

**Comment by jvillalobos** [comment]
The `resistfingerprinting` preference changes the user agent string, which is why you're getting the compatibility error. 

This issue tracks fixing the install button so it will work even if the client appears to be incompatible: https://github.com/mozilla/addons-frontend/issues/4910
