### ISSUE TITLE
Add to Firefox button appears even if addon is installed

### ISSUE THREAD

**Issue by nisargshah95** [mozilla/addons#717]
### Describe the problem and steps to reproduce it:
While browsing a specific add-on page at addons.mozilla.org, the _Add to Firefox_ button appears on the page even if the add-on is already installed. Clicking on it still downloads the add-on and asks me if I want to _Add/Cancel_ the operation

### What happened?
1) _Add to Firefox_ button appears even if the add-on is installed
2) Clicking on it downloads the add-on again and asks if I want to _Add/Cancel_

### What did you expect to happen?
The add-on page should notify that the add-on has already been installed

### Anything else we should know?
Firefox 60.0 (64-bit) on Ubuntu 17.10

**Comment by muffinresearch** [comment]
This is planned for the future see https://github.com/mozilla/addons-frontend/issues/3954
