### ISSUE TITLE
Updated review is only showing old text 

### ISSUE THREAD

**Issue by fatso83** [mozilla/addons#719]
### Describe the problem and steps to reproduce it:
I supplied a review for 1Password X and then later chose to edit and change its content. To me, it looked like everything was fine, until I saw the review section as a non-logged in user: it still showed my old text! The star rating had been changed, but not the text. After logging in, I could see my new text. Really weird. 

Steps:
1. submit a review for an addon
2. edit it - changing both stars and content
3. log out and view it as a non logged in user. it should show the original text from step 1

### What happened?
The old text was showing

### What did you expect to happen?
I expected to see the new text as a non-logged in user

### Anything else we should know?
Addon url: https://addons.mozilla.org/en-GB/firefox/addon/1password-x-password-manager/reviews/
My review is the 3 star review by fatso83

**Comment by bobsilverberg** [comment]
@fatso83 Could you post the links here for both views? I notice that the link you posted above points to the `en-GB` locale, and if the other link you've used to view the review is for a different locale, that would explain the issue.

**Comment by fatso83** [comment]
The locale thing is unrelated. I am still able to reproduce it and variations of it. Also, I have seen it seems to be some network sync/caching issue going on, with IndexedDB caching messing it further up.

I tried editing the review above, adding "edit 1", "edit 2", etc.

On submit, everything seems fine, but the text hasn't actually changed. On editing again _one of two things happen_. Either:
1. I get to edit the previous edited text
2. The non-edited text is presented for me to edit.

Also, sometimes when submitting the new review, after successfully submitting and reloading the page, the newly submitted version is not showing, only the old. In the few cases I do see a new version after submitting, it seems to be dynamically fetched from a cache in IndexedDB.
