### ISSUE TITLE
"Resize by dragging with the right mouse button." This caption pops up whenever I hold my cursor over *any image* in FF 60.0.1, Win7 x64, while I awaited a 2x zoom from the 'Hover Zoom 1.0.129' add-on (I disabled HZ, restarted FF; problem remains). The effect is so annoying, since it makes browsing *much* more difficult, rather than less so, that I must wonder: Is this a hack? Can I only get rid of "Resize by dragging with the right mouse button." by getting rid of FF completely? I've been using FF happily since its early days; this is the first time I've thought seriously of having to ditch it.

### ISSUE THREAD

**Issue by Joenewnew** [mozilla/addons#720]
"Resize by dragging with the right mouse button." This caption pops up whenever I hold my cursor over *any image* in FF 60.0.1, Win7 x64, while I await(ed) a 2x zoom from the 'Hover Zoom 1.0.129' add-on (I disabled HZ, restarted FF; problem remains). The effect is so annoying, since it makes browsing *much* more difficult, rather than less so, that I must wonder: Is this a hack? Can I get rid of "Resize by dragging with the right mouse button." only by getting rid of FF completely? I've been using FF happily since its early days; this is the first time I've thought seriously of having to ditch it.

**Comment by jvillalobos** [comment]
Sounds like you're having a problem with the Hover Zoom+ extension. This is not the right place to report this. You can contact the developer here: https://github.com/extesy/hoverzoom/issues
