### ISSUE TITLE
The caption, "Resize by dragging with the right mouse button," pops up whenever I hold my cursor over *any image* in FF 60.0.1, Win7 x64.

### ISSUE THREAD

**Issue by Joenewnew** [mozilla/addons#721]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
The caption, "Resize by dragging with the right mouse button," pops up whenever I hold my cursor over *any image* in FF 60.0.1, Win7 x64. The effect is so annoying, since it makes browsing *much* more difficult, rather than less so, that I must wonder: Is this a hack? Can I get rid of "Resize by dragging with the right mouse button." only by getting rid of FF completely? I've been using FF happily since its early days; this is the first time I've thought seriously of having to ditch it.

### What happened?
The caption, "Resize by dragging with the right mouse button." pops up whenever I hold my cursor over *any image* in FF 60.0.1, Win7 x64. The option apparently can't be bypassed; it convolves all further operations on the page.

### What did you expect to happen?
I expected a 2x zoom from the 'Hover Zoom 1.0.129' add-on. I've since disabled HZ, restarted FF,  DELETED HZ, re-restarted FF. No joy.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
I suspect this resizing pop-up is a new default-feature of FF, because it appeared right after a recent auto-update. However, Mozilla's jvillalobos said it sounded like a problem w/ the Hover Zoom add-on, despite my statement: "I disabled HZ, restarted FF; problem remained." I then DELETED the HZ add-on and restarted FF, but the problem persists. 

jvillalobos' offhand guess was wrong. He shut down my inquiry without checking or verifying anything. Was it necessary for him to discard my concern without even a thought? 

Here's a screenshot:  ![my firefox inquiry 2018-05-21 - firefox_screenshot_2018-05-22t02-35-24 648z](https://user-images.githubusercontent.com/36387541/40339958-8143cdfe-5d31-11e8-8562-94af996b5fa8.png)

Must I drop FF altogether, just to get rid of this new annoyance? (The resizing pop-up, that is... not jvillalobos. I'm afraid you'll have to get rid of him on your own, yuk yuk yuk.)

Many thanks!

**Comment by jvillalobos** [comment]
Guess I missed that bit in your issue. Regardless, this repo is for issues with the add-ons website and not Firefox. You can report the Firefox bug here: https://bugzilla.mozilla.org
