### ISSUE TITLE
Cannot list collections in desired formats

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons#722]
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/collections/mozilla/featured-personas/format:json will list all add-ons in the collection in JSON format

https://addons.mozilla.org/collections/mozilla/format:json didn't list all **collections** in JSON format

https://addons-server.readthedocs.io/en/latest/topics/api/collections.html#list cannot be used to solve the issue [said](https://github.com/mozilla/addons-server/issues/5510#issuecomment-390995214) Diox:
> you can't list collections belonging to somebody else than you (and that to access you own you need auth). I don't think there is a way around this though.

**Comment by davidhedlund** [comment]
@diox Thank you for pointing out that I should submit it here.

**Comment by diox** [comment]
@jvillalobos should we have the possibility of listing all collections belonging to someone else other than yourself through the API?

**Comment by davidhedlund** [comment]
@diox This is a primitive feature needed to get collection names which then can be used to get add-ons from them. I would be very happy if you would like to add this so we could finish our script that will sync data to the Free Software Directory. I have to parse the HTML documents served for the collections otherwise and that will require extra maintenance since it require me to update the code each time you change the HTML output.

**Comment by eviljeff** [comment]
The limitation to only list your own collections is by design.  Collections are not supposed to be discoverable via AMO - only if the user chooses to publicise the url to the collection externally.

**Comment by davidhedlund** [comment]
@eviljeff 
> The limitation to only list your own collections is by design. Collections are not supposed to be discoverable via AMO

How useless isn't that?

**Comment by jvillalobos** [comment]
The long answer is in [this doc](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit). The short version is that we don't want to expose user-created collections on the site, but want to keep supporting collections for personal use, and public collections where the creator shares the collection on their own.

**Comment by davidhedlund** [comment]
@jvillalobos Thank you for the documentation, that explains it.

**Comment by smayer97** [comment]
@davidhedlund You may want to follow the conversation in this thread here: https://github.com/mozilla/addons-frontend/issues/4331 and especially here: https://github.com/mozilla/addons-frontend/issues/4331#issuecomment-381342181

If you have anything to add, add your comments.

**Comment by davidhedlund** [comment]
@smayer97 Thanks.

**Comment by no-identd** [comment]
@jvillalobos that doc is non-public. Please could you share an appropriate excerpt? Thanks.
