### ISSUE TITLE
[Reviewer Tools] Content Review breaks down and does not show all the files

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#726]
Content Review does not show all the files

https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/959337/
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/965525/

This is all it shows

```
    META-INF
    __MACOSX
    css
    fonts
    img
      option.html
      whitelist.html
```

Please Note: @wagnerand

**Comment by wagnerand** [comment]
Thank you for the report!

@diox @EnTeQuAk is this related to https://github.com/mozilla/addons-server/issues/8220 ?

@erosman do you remember what time that happened for you?

**Comment by erosman** [comment]
> do you remember what time that happened for you?
A couple of minutes before posting here.

**Comment by EnTeQuAk** [comment]
This could easily be related to mozilla/addons-server#8220 but I do not see anything reasonable in Kibana or Sentry and we already added code to toggle errors more publicly. Obviously this now works :(

**Comment by EnTeQuAk** [comment]
Yeah, I'm closing this in favor of https://github.com/mozilla/addons-server/issues/8220 to keep information bundled there.

**Comment by erosman** [comment]
Older versions are still broken (tested now)

https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/769466/


```
    META-INF
    css
    fonts
    img
      option.html
```
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/906898/
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/931009/
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/868955/

**Comment by erosman** [comment]
@wagnerand  I noticed another broken one today (1 minutes ago) which affects compare

https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/964089/

It only shows 1 file

```
Files:
    domain-fronter.js
```
It also affects compare:
https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/978699...964089/

**Comment by erosman** [comment]
@EnTeQuAk Please reopen this issue
Another example: Both Contents & Compare are broken (tested 2 minutes ago)
https://reviewers.addons.mozilla.org/editors/review/10229/
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/982717/
https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/982717...930859/

Shows as:
```

    _locales
    images
        icons
        icon_32.png
    apps.json

```

**Comment by erosman** [comment]
Another example (2 minutes ago)

https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/974694/


```
    META-INF
    content
    help
    images
    .extension.bund...deps
    extension.bundl...js
    extension.bundl...map
    settings-data.js
```

**Comment by erosman** [comment]
More examples:
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/972222/

```
background
```
