### ISSUE TITLE
[Reviewer Tools] Compare is Broken

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#728]
Issue is introduced in yesterday's push. 

Example: https://reviewers.addons.mozilla.org/editors/review/545420/
Compare: https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/974497...965277/

All links on the left side panel load a /browse/ version without the diffs instead of /compare/
e.g.: https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/974497/file/install.rdf

```
<li>
    <a class=" file selected diff" data-delay="0" href="/en-US/firefox/files/browse/974497/file/install.rdf" data-short="install.rdf"><span>install.rdf</span></a>
</li>
```

Let me know if more examples are needed.

**Comment by EnTeQuAk** [comment]
The fix is now in production. Please give this a look and let me know if you find any more issues.

**Comment by erosman** [comment]
@EnTeQuAk It seems fine now
