### ISSUE TITLE
Add-on search page erroneously escapes spaces

### ISSUE THREAD

**Issue by ZeroUnderscoreOu** [mozilla/addons#73]
If search request contains a space then after narrowing of results by tags "+" (which replaces spaces) is escaped as "%2B". After another tag click "%" is esaped with "%25", which is repeated with each click. This leads to parameters like "q=Hide%25252Btoolbar" instead of "q=Hide+toolbar" in URL after 4 tag clicks.
As far as I can tell escaping is made by the server, as it's already present in GET responce.

**Comment by muffinresearch** [comment]
Hi ZeroUnderscoreOu

Thanks for the bug report. 

Could you provide more detailed steps to reproduce? I don't seem to be able to reproduce the same behaviour via https://addons.mozilla.org/en-US/firefox/search/?q=hide+toolbar and clicking tags in the sidebar.

Please include as much detail as possible e.g:

* Browser version + platform
* URL that you're starting from.
* Add details each and every step you're taking to reproduce the problem you're seeing.
* Add screenshots if they help pin down the details.

The goal being anyone can reproduce the same behaviour you're seeing given the same starting point.

**Comment by ZeroUnderscoreOu** [comment]
It's pretty hard to describe it better 'cause it's that simple.
1. I open https://addons.mozilla.org/en-US/firefox/search/?q=hide+toolbar
2. I click "All Tags"
3. I click tags from top down one after another, single click for each tag
The result is the same for both /ru/ & /en-US/, in FF, Opera & Chrome, on desktop & phone. So it doesn't seem to be language-, browser- or even OS-specific.
Win7 x64, Android 4.4.2.

**Comment by muffinresearch** [comment]
Thanks - that did clear it up, the bit I was missing from the initial description was that it takes multiple tag clicks to see the issue.

**Comment by EnTeQuAk** [comment]
It appears that there might be a `|safe` missing in search/results.html like 42, I'm looking into it.
