### ISSUE TITLE
spellcheckers/dictionaries are almost invisible in Thunderbird (too hard to reach)

### ISSUE THREAD

**Issue by Djfe** [mozilla/addons#733]
### Describe the problem and steps to reproduce it:

I opened Thunderbird > Add-ons > Explore Addons > addons.mozilla.org (over one of the links there) -> search "english" or "deutsch"

### What happened?
The search returned no result or just normal add-ons

### What did you expect to happen?
I clicked in the navigation on
more -> Dictionaries & Language Packs -> The language(s) I wanted.
Now suddenly german/english dictionaries appear in the search.
Before they didn't for some reason.

I don't have the issue in Firefox, when I open the addon domain. (dictionaries are always part of the search results, when the search term fits)
But everytime I open the Page in Thunderbird (until I visited more -> language packs)

They are also way too hidden, considering how useful they are when writing mails.
It would be nice to see them listed next to themes and apps on the local "explore add-ons" page.

Also there are no backwards/forwards buttons when browsing on addons.mozilla.org in Thunderbird.

Regards,
Djfe

### Anything else we should know?

I know these are partly Thunderbird bugs, but they are all related to addons.mozilla.org , so you and the Thunderbird team probably have to join efforts anyways, so I would rather report it here :)

**Comment by jvillalobos** [comment]
Thunderbird and SeaMonkey add-ons are going to be moved to a separate site very soon, so I don't think there's anything we can do about this now. This should be filed against the new site. @Sancus, is there a repo to point people for filing issues?

**Comment by Sancus** [comment]
Yep bugs related to Thunderbird Add-ons can be filed here: https://github.com/thundernest/addons-server/issues
