### ISSUE TITLE
ALL Add-on's cannot be installed nor downloaded.

### ISSUE THREAD

**Issue by cromanillos** [mozilla/addons#734]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I'm trying to install the Spanish (Mexico) language pack but I keep getting an error: "The add-on could not be downloaded due to a connection failure" same for any add-on I am trying to install.

### What happened?

Tried to install an add-on and realized of the error.

### What did you expect to happen?
To download and install with no problems.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
I am getting this message:
Your connection is not secure

The owner of addons.cdn.mozilla.net has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

--------------------

When I click on "advanced" I get:
addons.cdn.mozilla.net uses an invalid security certificate. The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported. The certificate is only valid for search.dnsadvantage.com The certificate expired on Sunday, September 17, 2017, 11:03 PM. The current time is Wednesday, June 6, 2018, 7:18 PM.
---------------------
And on the error I get:

https://addons.cdn.mozilla.net/user-media/addons/_attachments/608412/dictionary_googletm_translate_anywhere-0.3.6-an+fx.xpi?filehash=sha256%3A740fed2a3adb6626e080aa8a32b36f2fcedd282cedc7ec52ae602b566e8801ad

Peer’s Certificate issuer is not recognized.

HTTP Strict Transport Security: true
HTTP Public Key Pinning: true

Certificate chain:

-----BEGIN CERTIFICATE-----
MIIFsTCCBJmgAwIBAgIDBv3gMA0GCSqGSIb3DQEBCwUAMEcxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMSAwHgYDVQQDExdSYXBpZFNTTCBTSEEy
NTYgQ0EgLSBHMzAeFw0xNTA5MTYwMDMzMDJaFw0xNzA5MTgwNDAzNDVaMIGbMRMw
EQYDVQQLEwpHVDU4MDczMzAyMTEwLwYDVQQLEyhTZWUgd3d3LnJhcGlkc3NsLmNv
bS9yZXNvdXJjZXMvY3BzIChjKTE1MS8wLQYDVQQLEyZEb21haW4gQ29udHJvbCBW
YWxpZGF0ZWQgLSBSYXBpZFNTTChSKTEgMB4GA1UEAxMXc2VhcmNoLmRuc2FkdmFu
dGFnZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCwktbK5LPl
uxgTMNXpsrnP/FeT474yEim1KqdD/jsQFYIAZKVSbxU2oMqRqWqTSWVGbrOfNGcO
Wm8wt8ZsW74RBDPnmta7TSCmXqMKWYSUOrBSCz9+WKZhubLjLKmfm89sxeoH793b
OABGhdc/DK+fbZC2wnINx7oSV3WrVrq6QlcenOlqlLOiO/ec5CKWy7SEk0ahm0Xj
xwrj2iY/Z3hhcMe7M0g0i7Vy+y6tEak+sMmfCZaq0VYlmQbbCaMjltgXLkJvNYPI
rt/K8ttC5EZuTeVWTeWnY02LIUZT4qsvZQmgwnCQzlumY3gXabH5qgEUGy6NuB2/
lDD9wm+OAO8FH72DwNggfiJWtPnqd8R4oqNrXhoHzl7RPpr6s4siQv7ql4PbCSbY
N/iraMPqJksl+Zi6gjnk1u2MGa6c93lhiea8tTeZgDZV3vpw+IuQC5YW+/ZYlz8V
Np1kkUIl4kp/HptDUTsrA83xNXQ6WuYEzJ/fSHwTg33i559tMIVVwJx5OBRkXC9k
+kvUiWzyEuhUXO6l9tECebrV5YT2wPMc1RZvcxbyWlxqal7KKIzsxKtKYF0FqZ/c
IF2amCHTbS3k+8Rdwl0SOGfFeSdSO4N7MoyGlBAg5GSjC9F96pxkLNZR1BYJauZD
pm/OsouqSYOez1BlMwF//dzyDI/gu3+JXwIDAQABo4IBTzCCAUswHwYDVR0jBBgw
FoAUw5zz/NNGCDS7zkZ/oHxb8+IIy1kwVwYIKwYBBQUHAQEESzBJMB8GCCsGAQUF
BzABhhNodHRwOi8vZ3Yuc3ltY2QuY29tMCYGCCsGAQUFBzAChhpodHRwOi8vZ3Yu
c3ltY2IuY29tL2d2LmNydDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
BQUHAwEGCCsGAQUFBwMCMCIGA1UdEQQbMBmCF3NlYXJjaC5kbnNhZHZhbnRhZ2Uu
Y29tMCsGA1UdHwQkMCIwIKAeoByGGmh0dHA6Ly9ndi5zeW1jYi5jb20vZ3YuY3Js
MAwGA1UdEwEB/wQCMAAwQQYDVR0gBDowODA2BgZngQwBAgEwLDAqBggrBgEFBQcC
ARYeaHR0cHM6Ly93d3cucmFwaWRzc2wuY29tL2xlZ2FsMA0GCSqGSIb3DQEBCwUA
A4IBAQCsluwg3oAwyL6opH9Hjopmc1Ufb12ByI+DG+TglevvvDn/UNa5oxjTo87V
EWqCKrYvzB9AUT62KVtlu8B+J01eo4vLunhZLGxxQW25VMrwmWPF03rAwDNPsP0L
/S5+VmxeCvvXUu/2Hy/K36/xjsezALgKZgigPeyb2gTciXl7PlybDIpM2vDtklBr
nW4JB8j9jb+L8S6sK9JHPv6V++wFvWCR/b82wdaBakgqXmu4Pw/NzolckM9Zkd2f
vD2XalV31iAWQ3hLtBHv/b9zI4C/Y1N3zvp6E1FGCBG2DTWqbS+7iyrlipQ7Ly6U
bER4APY1wPEt+CQcRF/AMyCN/bmS
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIID1TCCAr2gAwIBAgIDAjbRMA0GCSqGSIb3DQEBBQUAMEIxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9i
YWwgQ0EwHhcNMTAwMjE5MjI0NTA1WhcNMjAwMjE4MjI0NTA1WjA8MQswCQYDVQQG
EwJVUzEXMBUGA1UEChMOR2VvVHJ1c3QsIEluYy4xFDASBgNVBAMTC1JhcGlkU1NM
IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx3H4Vsce2cy1rfa0
l6P7oeYLUF9QqjraD/w9KSRDxhApwfxVQHLuverfn7ZB9EhLyG7+T1cSi1v6kt1e
6K3z8Buxe037z/3R5fjj3Of1c3/fAUnPjFbBvTfjW761T4uL8NpPx+PdVUdp3/Jb
ewdPPeWsIcHIHXro5/YPoar1b96oZU8QiZwD84l6pV4BcjPtqelaHnnzh8jfyMX8
N8iamte4dsywPuf95lTq319SQXhZV63xEtZ/vNWfcNMFbPqjfWdY3SZiHTGSDHl5
HI7PynvBZq+odEj7joLCniyZXHstXZu8W1eefDp6E63yoxhbK1kPzVw662gzxigd
gtFQiwIDAQABo4HZMIHWMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUa2k9ahhC
St2PAmU5/TUkhniRFjAwHwYDVR0jBBgwFoAUwHqYaI2J+6sFZAwRfap9ZbjKzE4w
EgYDVR0TAQH/BAgwBgEB/wIBADA6BgNVHR8EMzAxMC+gLaArhilodHRwOi8vY3Js
Lmdlb3RydXN0LmNvbS9jcmxzL2d0Z2xvYmFsLmNybDA0BggrBgEFBQcBAQQoMCYw
JAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmdlb3RydXN0LmNvbTANBgkqhkiG9w0B
AQUFAAOCAQEAq7y8Cl0YlOPBscOoTFXWvrSY8e48HM3P8yQkXJYDJ1j8Nq6iL4/x
/torAsMzvcjdSCIrYA+lAxD9d/jQ7ZZnT/3qRyBwVNypDFV+4ZYlitm12ldKvo2O
SUNjpWxOJ4cl61tt/qJ/OCjgNqutOaWlYsS3XFgsql0BYKZiZ6PAx2Ij9OdsRu61
04BqIhPSLT90T+qvjF+0OJzbrs6vhB6m9jRRWXnT43XcvNfzc9+S7NIgWW+c+5X4
knYYCnwPLKbK3opie9jzzl9ovY8+wXS7FXI6FoOpC+ZNmZzYV+yoAVHHb1c0XqtK
LEL2TxyJeN4mTvVvk0wVaydWTQBUbHq3tw==
-----END CERTIFICATE-----

**Comment by diox** [comment]
No info from reporter.

**Comment by cromanillos** [comment]
yeah, sorry about this I hadn't seen my gmail... in any case Firefox got updated and now I can Install add-ons no problems. Current ver is Quanbtum 62.0b4 (64bit). Cheers!
