### ISSUE TITLE
Firefox sets extension icon to default from manifest randomly 

### ISSUE THREAD

**Issue by ayoseturru** [mozilla/addons#736]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
1. Install extension
2. Open a random page like www.amazon.com
3. Set an extension icon different from the one on manifest file with browserAction.setIcon() after 
tabs.onUpdated event.

### What happened?
Firefox sets icon to default randomly.

### What did you expect to happen?
Keep icon or after page reloads set default icon before tabs.onUpdated is being fired.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
Issues with the WebExtensions API should be filed at https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=WebExtensions:%20Untriaged
