### ISSUE TITLE
5OpMWwqZl5IErqdh

### ISSUE THREAD

**Issue by Angel419** [mozilla/addons#737]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Angel419** [comment]
added this Firefox extension Chrome Store Foxified  because I needed one extension from the Chrome Store but try as I may the ChromeStore extension still doesn't download it altho the message keeps telling me it has been downloaded.. What's wrong ? The extension is for twitter & a bummer without it I was able to download the extension in Opera

**Comment by jvillalobos** [comment]
Please contact the developer of the extension for help. This issue tracker is for the add-ons website.
