### ISSUE TITLE
Add '*' as a valid SeaMonkey application version

### ISSUE THREAD

**Issue by musically-ut** [mozilla/addons#74]
This would allow extensions to not specify an upper bound on the browser version if they rely on a Stable API and would prevent problems like https://github.com/mozilla-jetpack/jpm/issues/518

Relevant page: https://addons.mozilla.org/en-US/firefox/pages/appversions/

**Comment by kumar303** [comment]
@wagnerand could you take a look at this?

**Comment by wagnerand** [comment]
I am not sure we want this. @jvillalobos do you have an opinion on this?

**Comment by jvillalobos** [comment]
I don't feel strongly either way, so I'm okay adding it.

**Comment by musically-ut** [comment]
Are there any cons to adding it?

**Comment by jvillalobos** [comment]
Developers get lazy and just set * as maxVersion without testing regularly, potentially causing stability problems for users, which we need to chase. This is a very minor problem for SeaMonkey, so I'm not concerned about it.

**Comment by eviljeff** [comment]
done :)

**Comment by jvillalobos** [comment]
Fine, but I get all the credit.

**Comment by eviljeff** [comment]
> Fine, but I get all the credit.

I was channelling your spirit while pressing those buttons and keys.
