### ISSUE TITLE
How to add permanent redirect from old AMO listing URL to new URL?

### ISSUE THREAD

**Issue by ghostwords** [mozilla/addons#743]
I would like to update the listing URL for Privacy Badger from https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/ to https://addons.mozilla.org/en-US/firefox/addon/privacy-badger/.

I can update the URL using the listing management UI:

![screenshot from 2018-06-25 12 09 49](https://user-images.githubusercontent.com/794578/41862025-d912a0f0-7870-11e8-8ff9-9ae3fb6aaec9.png)

How do I set up a permanent redirect from the old URL to the new? I don't want to break every direct link to the Privacy Badger AMO add-on listing out there.

**Comment by jvillalobos** [comment]
It's not possible to set a redirect. You can either stick to the current slug or risk breaking links pointing to it.

**Comment by smayer97** [comment]
Or maybe simply add a link to the new location in the description.

**Comment by ghostwords** [comment]
>Or maybe simply add a link to the new location in the description.

I am not sure I understand. I don't want to publish a new extension ... I just want to move the URL for an existing extension (Privacy Badger).

**Comment by ghostwords** [comment]
>It's not possible to set a redirect.

Should it be possible? I don't know Privacy Badger ended up with a URL like "privacy-badger17" but it would be nice to fix it.

**Comment by jvillalobos** [comment]
> I don't know how Privacy Badger ended up with a URL like "privacy-badger17" 

I think it dates back to when we introduced signing and Privacy Badger wasn't being distributed on AMO. Long story short, there's still an unlisted entry under your account that uses the slug `privacy-badger`.

> Should it be possible?

While clearly the `privacy-badger` slug only makes sense for a single extension (yours), some are less specific and are good to free in case others want to use them. It doesn't help that we don't restrict slug use or slug updates, so they don't need to be related to the name of the add-on or anything else.

Having said that, I think it'd be nice to set up a redirect when a slug changes (GitHub does that for projects, which is handy). However, that's not a top priority nor currently planned.

**Comment by ghostwords** [comment]
OK, thanks for the explanation.
