### ISSUE TITLE
https://dadrz7o8a3etj.cloudfront.net/HybridExtensions/Converter/converter_webext3.xpi seems to violate add-on policies

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/addons#745]
This add-on has a description of "Extension Name" and "Extension Description". It hijacks the newtab page replacing it with convert.mysearches.co/.

These things seem like they violate the "No Surprises" section of the add-ons policy.

**Comment by jrmuizel** [comment]
This add-on also asks for the following permissions:
     "tabs",
    "storage",
    "webRequest",
    "webRequestBlocking",
    "cookies",
    "management",
    "webNavigation",
    "<all_urls>",
    "alarms"

and the top link for "convert.mysearches.co" is:
http://www.myantispyware.com/2018/06/21/how-to-remove-converter-mysearches-co-chrome-firefox-ie-edge/

**Comment by wagnerand** [comment]
Thank you for the report. The add-on has already been disabled. Can you tell us what pages links to that cloudfront url?

**Comment by jrmuizel** [comment]
Was it blocked before or only after I filled the bug report? I found the
add-on on my parents computer. They're not sure how it got there.

**Comment by wagnerand** [comment]
It was disabled before. If we can't find the origin, there's not much we can do otherwise. Closing...

**Comment by jrmuizel** [comment]
The add-on was still active on my parent's computer. (I needed to disabled
it manually) How long ago was it blocked? Should the blocking already have
been in affect?
