### ISSUE TITLE
Localized screenshots for add-on listings

### ISSUE THREAD

**Issue by tscheepers** [mozilla/addons#746]
### Describe the problem and steps to reproduce it:

When uploading screenshots for the store listing, it would be nice if they could be localized.

I have screenshots containing both Dutch and English examples. It is not really nice to show my Dutch customers an English screenshot and vice versa. I can now only change the caption.

### What happened?

Now when I upload screenshots for different store listing localizations they all show up on all localizations.

### What did you expect to happen?

I expect the store listing to work similair to App Store Connect or the Google Play Developer Console, where the developer has the option to upload localized screenshots or fallback to the screenshots of the default locale.

<img width="1196" alt="schermafbeelding 2018-07-02 om 20 08 53" src="https://user-images.githubusercontent.com/44893/42179373-012b62e8-7e34-11e8-9610-8a539e4b2a48.png">

**Comment by tscheepers** [comment]
Nvmnd wrong repo

**Comment by diox** [comment]
Hi,

Thanks for filing this. It's a good idea, and in fact has already been reported in the past: https://github.com/mozilla/addons-server/issues/5662 - sadly we never found the time to do it...

**Comment by tscheepers** [comment]
Thanks @diox
