### ISSUE TITLE
Missing list of add-on types

### ISSUE THREAD

**Issue by vincens2005** [mozilla/addons#747]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
on the page [https://developer.mozilla.org/en-US/Add-ons](https://developer.mozilla.org/en-US/Add-ons) It said under "Other types of add-ons" that "In addition to extensions, there are a few other add-on types that allow users to customize Firefox. Those add-ons include:"
but underneath that was a line across the screen and then the "Contact us" section.
### What happened?
There was no list saying what other types of add-ons Firefox has.
### What did you expect to happen?
That underneath "Those add-ons include:" there would be a list of them
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![screen shot 2018-07-07 at 7 59 05 pm](https://user-images.githubusercontent.com/26677493/42416316-f4a7c45a-825a-11e8-9a28-bf5bf65fc81c.png)

**Comment by caitmuenster** [comment]
Thanks for the heads up, @vincens2005! Other types must have gotten deleted by mistake. :) We'll get this updated this week.

**Comment by caitmuenster** [comment]
The list is back on the page, but there are other weird formatting issues on the page that need investigation.

**Comment by jvillalobos** [comment]
I fixed the formatting issue.
