### ISSUE TITLE
Is this correct: "The users \"%(users)s\" have been banned.users, "?

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons#749]
### Describe the problem and steps to reproduce it:
This string doesn't seem to make sense: 
https://github.com/mozilla/addons-server/blob/master/locale/en_US/LC_MESSAGES/django.po#L6965

### What happened?
check screenshot: http://mozillaIRCBot.mautematico.com/media/RjwNiQhbRn6b8jnE/file_3850.jpg

### What did you expect to happen?
Re-word it.

**Comment by peiying2** [comment]
A few more examples:
https://github.com/mozilla/addons-server/blob/master/locale/en_US/LC_MESSAGES/django.po#L6957
https://github.com/mozilla/addons-server/blob/master/locale/en_US/LC_MESSAGES/django.po#L6961

**Comment by diox** [comment]
This is a problem with the extraction process. Closing in favor of #8889.
