### ISSUE TITLE
Review issue.

### ISSUE THREAD

**Issue by brain8891** [mozilla/addons#750]
Let us be able to respond to the developer response.

Some developers don't understand the review, and reply back with something not related to the review that I gave, I can't clarify to them, unless if I edited the review

and I think other users should be able to respond to my review, maybe I said something that I don't understand, i saw so many reviews that are bad because they did not go into the add-ons settings, hence, other users see that review and not install the add-on. Don't restrict our freedom. It never is good.

**Comment by jvillalobos** [comment]
Reviews aren't meant to be conversations. Developers can respond, but it should generally be to clarify misunderstandings or point users to the appropriate support channels. You can look for a support site or support email address in the add-on's listing page if you need to have a discussion with the developer. Worst case, you can edit your existing review to try to respond.

There's work going on this quarter to make it easier for users to use the right feedback channels.

**Comment by brain8891** [comment]
"There's work going on this quarter to make it easier for users to use the right feedback channels." If you don't mind, explain in details?

I understand what the Reviews are meant to be, and I also know about support email/site. My reasons: Is for future reference and to attract more users or detract in cases where the add-on is suspicious specially those which asks for permissions that are not needed. For example, I see users ranting about permissions when they should not, and when the developer replies, the review get changed and it gets confusing to me as  a decider. It should be chronological and a filter to make it hierarchical, meaning other users should be able to vote-up/down a review/comment. That is the idea of open collaboration. 

It is not a conversation, and the emphasis should be on the review and the developer reply, but each should have a tree of comment, as a decider I would know  and that is what a review is for to help you decide.

You can close this, and please kindly explain in details about your last sentence.

**Comment by jvillalobos** [comment]
Sorry, I should have included more information. The project we're tracking for this quarter is here: https://github.com/orgs/mozilla/projects/29 (let me know if the link doesn't work). The main idea is that the review flow will show users ways to get in touch with the developer in case they want to get in touch, since reviews are not the right place for that. Reviews aren't and won't be a two way communication channel, so it's best for everyone if users are directed to the right place for that kind of discussion.
