### ISSUE TITLE
Legacy website login form causing infine UX loop

### ISSUE THREAD

**Issue by chrismore** [mozilla/addons#753]
### Describe the problem and steps to reproduce it:

I happen to come across this URL on Zemmate's support website:

https://addons.mozilla.org/en-US/firefox/users/login?to=/en-US/firefox/addon/zenmate-vpn/reviews/

It looks like it is a direct link to an AMO login form that is supposed to redirect after authenticating to the /reviews/ page.

### What happened?

I authenticated with FxA. It returned me back to the same page, said I was logged in (via the header) and said again login with FxA to continue. This infinite loop in the user experience doesn't ever end. It looks to be an issue with the old AMO template and the FxA login form.

### What did you expect to happen?

I expected to be redirected to:

https://addons.mozilla.org/en-US/firefox/addon/zenmate-vpn/reviews/

but that never happened.

### Anything else we should know?

I checked Google Analytics, to see if I could estimate how many other people have this same issue.

It looks like 150-200 people are day are hitting this URL "firefox/users/login" and mostly from organic search.

So it doesn't look like a massive issue, but it looks like some users and non-users could be getting stuck.

**Comment by kumar303** [comment]
Thanks for the report. I can verify this same behavior in a new Firefox profile.

**Comment by muffinresearch** [comment]
@diox do you know if we have a way to replace this URL with the right call to FXA? 

Presumably we can generate the same login URL a user would get if they press the login button on url in the `to` param and redirect to that?

**Comment by diox** [comment]
Yeah, we can. Still, we should try to figure out where the loop is coming from - this is an old-style login URL from before the switch to FxA, but it shouldn't have been broken...

**Comment by diox** [comment]
So the loop is coming from the fact that this view is rather dumb - it just shows the button to log in through FxA no matter what. It should be replaced with a `if` / `else` redirecting to the target path (making sure it's valid / not external /etc - there is a function for this) if the user is authenticated, or to FxA otherwise.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

User is successfully logged in when starting on an old login URL and will land on the requested page:

https://addons-dev.allizom.org/en-US/firefox/users/login?to=/en-US/firefox/addon/read-later/reviews/

![fxa login loop](https://user-images.githubusercontent.com/31961530/44026017-5c283d6a-9efa-11e8-8a7f-b320a5854f08.gif)
