### ISSUE TITLE
semver versioning scheme not accepted by 'web-ext sign'

### ISSUE THREAD

**Issue by tomquas** [mozilla/addons#755]
### Describe the problem and steps to reproduce it:
my extension version follows the semver scheme. in manifest.json, version is set to:

  "version": "4.2.2-beta.1",

linting manifest.json in visual code reveals zero errors.

### What happened?
 - i can load and run the extension w/o issues in firefox developer edition
 - when trying to sign with 'web-ext sign' i get the following result:

Validating add-on [.....................................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/479a04b7acb84d2d85734911409f4b30
Your add-on failed validation and could not be signed
FAIL

### What did you expect to happen?
validation should pass – at least it did the last months when using the scheme.

### Anything else we should know?
the problems started this morning; i successfully validated a version 4.2.1-beta.3 last night.

**Comment by kumar303** [comment]
Thanks for filing an issue.

Error from validation results:

> "/version" should match format "versionString"

This comes from `addons-linter` when it fails [this check](https://github.com/mozilla/addons-linter/blob/36ede88be40b4b810c6b1a0aa8834a13ae87af70/src/schema/formats.js#L12-L42). The error message isn't great (sorry about that) and I agree that it's probably a bug. I don't see why `semver` can't be supported here. Can you re-file it as a linter bug? https://github.com/mozilla/addons-linter/issues/new

**Comment by tomquas** [comment]
thx @kumar303. i would file it there if github or some policy would allow me to. ticket submission button stays in ghost mode for me.

**Comment by wagnerand** [comment]
This is basically https://github.com/mozilla/addons-linter/issues/1439
