### ISSUE TITLE
Cannot see preferences for an installed addon

### ISSUE THREAD

**Issue by birdsarah** [mozilla/addons#758]
When installing an addon I am asked for permissions.

However, after installing that addon, if I am in about:addons and looking at the detail page for that addon I cannot see any information about the permissions that addon requested.

This information is available on the detail page on addons.mozilla.org. However, there is not link from an installed addon to the AMO page. Not there necessarily would be, but in the case where an addon has been installed via AMO a link back to the detail page would be helpful.

cc @samastur who asked me about this.

**Comment by jvillalobos** [comment]
Bugs in the Add-ons Manager should be filed [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Add-ons%20Manager). We can't do anything about that on the AMO end. I know there is some work planned to show permissions there, but I don't know the exact bugs.

**Comment by birdsarah** [comment]
Thanks @jvillalobos I couldn't find the right place when I looked on bugzilla before. Sorry for the noise.
