### ISSUE TITLE
Page Display Bug on Mozilla Survey from Add-Ons Main Page.

### ISSUE THREAD

**Issue by JK98062** [mozilla/addons#759]
I recently encountered a Bug when displaying the Mozilla Add-ons Survey that appears occasionally on the Add-Ons Main Page. The Bug appears to only occur while uBlock Origin is Enabled.
I clicked the Survey Link as Circled in the Screenshot below.
[Add-On Main Page Screenshot](https://ibb.co/bEzKwy)
While uBlock Origin is Enabled the Survey Page displays incorrectly (see screenshot below).
[Mozilla Survey Page Display Bug](https://ibb.co/jkOewy)
With uBlock Origin Disabled the Survey Page displays correctly (see screenshot below).
[Mozilla Survey Page Correctly Displayed](https://ibb.co/hqnWby)

Add-Ons Main Page URL:
https://addons.mozilla.org/en-US/firefox/
Mozilla Add-ons Survey Page URL:
https://qsurvey.mozilla.com/s3/addons-mozilla-org-survey?source=firefox%2F

**Comment by TylerDowner** [comment]
I don't see that when I use Firefox and uBlock Origin, do you have any weird filters (non-default)?

We do control this site, so please re-open

**Comment by muffinresearch** [comment]
> We do control this site, so please re-open

@TylerDowner do you have a bug tracker you can re-file this on?

**Comment by TylerDowner** [comment]
No, we don't have a bug tracker. I would like to hear more from the OP however on their setup, as i can't reproduce this bug.
