### ISSUE TITLE
Android Discovery Pane Design

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons#76]
Still needs to be reviewed with the Fennec team, but is close to being completed.
![disco pane-android-mar29](https://cloud.githubusercontent.com/assets/6797635/14115871/d1d500c6-f591-11e5-8228-999b00d1c5f3.png)

**Comment by andymckay** [comment]
Could we turn this into a pull request on the docs?

**Comment by mstriemer** [comment]
I don't think Android supports themes so we shouldn't need to set those up. Where does "more info" go? I don't see a similar link in the desktop mocks.

@andymckay is there a timeline that we'd like to get this done? We can update the styles to support mobile but I think we'll need to update the API to filter the response based on platform as well.

**Comment by andymckay** [comment]
We aren't sure if Android are actually going to use this at this time. So
it's not a blocker for 48. I would really like it if we could make sure our
designs are always responsive though.

>

**Comment by muffinresearch** [comment]
@andymckay fear not, the plan has always been that we would aim to implement the mobile UX as part of the first release. 

Clarifying the priority was so we know when to fit it in. Given it's not a blocker will move it down the backlog so we can continue to focus on the core priorities first. 

Doing the mobile stuff with the main desktop experience will help minimise what we need to do for a future mobile release + make sure everything works together nicely.

**Comment by pwalm** [comment]
Some rumblings of aligning from the mobile team: https://bugzilla.mozilla.org/show_bug.cgi?id=1079504
