### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Micaelfurtado** [mozilla/addons#762]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know? No more. My link: 	https://addons.mozilla.org/…/4adfc8f191b448009204
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
The link you provided isn't working (it has a '...' in it). Guessing this was taken from the developer hub, it look like you didn't choose to distribute the add-on on AMO, and chose to self-host instead. That's the reason the listing page isn't working. There's some additional info about it [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution#Distributing_your_add-on).
