### ISSUE TITLE
Improve feed discovery on "versions" pages

### ISSUE THREAD

**Issue by Fanolian** [mozilla/addons#763]
### Describe the problem and steps to reproduce it:
For now I subscribe/discover RSS feeds in versions pages (https://addons.mozilla.org/{some extensions}/versions/) via Firefox's subscribe button to view update notes of various extensions. Unfortunately, feed support, including feed detection and the subscribe button, is going to be removed[1] soon in Firefox.

I can restore feed detection function with an extension ([Awesome RSS](https://addons.mozilla.org/firefox/addon/awesome-rss/) for example) on other sites but not AMO due to Webextensions restriction on certain Mozilla/Firefox sites (as defined by `extensions.webextensions.restrictedDomains`).

### What happened?
There is no way to discover RSS feeds in AMO UI. With both detection methods unavailable, I may have to revert to manually type a RSS feed location in my RSS reader to subscribe one.

### What did you expect to happen?
A RSS icon in versions page linking to the RSS feed would be nice.

### Anything else we should know?
[1]: [Bug 1477667 - [meta] Remove feed reader and live bookmarks support from Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1477667#c44)

**Comment by jvillalobos** [comment]
We don't intend to continue supporting RSS feeds on the site. The [AMO API](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#versions-list) can be used to track updates dynamically, but the format is not RSS.
