### ISSUE TITLE
<url> in custom license badly rendered

### ISSUE THREAD

**Issue by mart-e** [mozilla/addons#765]
### Describe the problem and steps to reproduce it:
The AGPL license starts with

```
                    GNU AFFERO GENERAL PUBLIC LICENSE
                       Version 3, 19 November 2007

Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
```
If you create an extension with this license and put the above text in the license text input.

![license-1](https://user-images.githubusercontent.com/564822/43575429-1d80f400-9647-11e8-8204-669cf82add4b.png)
 and try to access the license text from the addon page:
![license-1 5](https://user-images.githubusercontent.com/564822/43575519-474d0c38-9647-11e8-9472-6e8b557dcf37.png)

### What happened?

On the page `https://addons.mozilla.org/en-US/firefox/addon/<module-name>/license/<version>` you get the following result:

![license-2](https://user-images.githubusercontent.com/564822/43575565-69080f08-9647-11e8-8a58-83e71c141a2a.png)

### What did you expect to happen?

Correct rendering of the `<http://fsf.org/>` text

### Anything else we should know?

- [example addon](https://addons.mozilla.org/en-US/firefox/addon/odoo-debug/)
- [example license](https://addons.mozilla.org/en-US/firefox/addon/odoo-debug/license/3.4)

**Comment by EnTeQuAk** [comment]
Closing in favour of https://github.com/mozilla/addons-frontend/issues/3697

This is part of our legacy views which we won't update unless necessary. A new version will be available in the shiny new design hopefully soon :)
