### ISSUE TITLE
Firefox recognition on Add-On website

### ISSUE THREAD

**Issue by plambert2** [mozilla/addons#767]
### Describe the problem and steps to reproduce it:
We are adding some values to the useragent string of Firefox. This was working for a long time now, but currently our users are asked to download Firefox if they visit an add-on website.

### What happened?
Probably the method to identify Firefox was changed.
### What did you expect to happen?
Rework the recognition, so even if there are additional values in the useragent, Firefox should be recognized as Firefox.

**Comment by diox** [comment]
hi,

We need more details to help you. What users are you talking about? What exact modifications to the UA string are you making? Why?

**Comment by plambert2** [comment]
All user in our company. We have instructions from our security department to add specific values. It looks like this Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.1.0) Gecko/20100101 Firefox/60.1.0**; Firefox 60.1.0 - 111712-1500630434-1.46** 
But anyway, if you add just a single letter to the default UA, the website is not able to recognize Firefox anymore e.g. Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0**;**

**Comment by plambert2** [comment]
Just saw today that if i click on "Show all versions" the recognition is correct and the "Add to Firefox" button is shown. So the recognition is just not working on the main Add-On page.

**Comment by plambert2** [comment]
Anyone who can take care about this?

**Comment by jvillalobos** [comment]
The All versions page hasn't been ported from the old front end, which is why still works for you. However, that's changing soon.

I don't know what kind of UA detection we do, but maybe we can change it to a "starts with" check, so we can allow people who append text to it. I don't know if that could have a performance or functional impact, however.

**Comment by eviljeff** [comment]
The detection is front-end side, so calling @willdurand / @kumar303 / @bobsilverberg

**Comment by diox** [comment]
No reply, closing.
