### ISSUE TITLE
Contribute/donate function fails due to PayPal x-frame policy

### ISSUE THREAD

**Issue by penguins55** [mozilla/addons#77]
I was unable to contribute/donate to an add-on developer because PayPal never shows up after clicking Make Contribution.  

Error that appears to be causing this:
Load denied by X-Frame-Options: https://www.paypal.com/us/cgi-bin/webscr?cmd=_dispatch-failed does not permit cross-origin framing.

I was eventually able to get to PayPal and donate by copying the URL that failed to open in the iframe and opening it in a new tab.  Looks like the PayPal code might just need updated.  

![1](https://cloud.githubusercontent.com/assets/3169335/14131597/8c382310-f602-11e5-8069-951d60fe910b.png)

**Comment by andymckay-limited-access** [comment]
We have had intermittent reports of this going back to https://bugzilla.mozilla.org/show_bug.cgi?id=896653, at this point I'm not sure what to do other than move to something not Paypal.
