### ISSUE TITLE
Unable to edit add-on

### ISSUE THREAD

**Issue by Altalina** [mozilla/addons#771]
### Describe the problem and steps to reproduce it:
Unable to edit Add-on Details section. Please see attached. We have tried on multiple devices and on different wi-fi networks. 
<img width="1191" alt="screen shot 2018-08-17 at 13 59 56" src="https://user-images.githubusercontent.com/39909911/44265470-f5237a00-a226-11e8-8ecf-0fa8622e3273.png">

### Anything else we should know?
Attached

**Comment by diox** [comment]
Hi,

Definitely a problem on our own with this add-on. Sentry traceback: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4498299/

**Comment by diox** [comment]
Found the cause of the bug, we'll push a fix next week.

**Comment by diox** [comment]
QA:
- Try editing details in devhub for a purely unlisted add-on.

**Comment by Altalina** [comment]
I have just cleared my cache and used the Firefox browser, and I still have the same issue:
![ezgif-5-db04d0fddc](https://user-images.githubusercontent.com/39909911/44335375-8d626e80-a474-11e8-8a02-d7fab89ab3e1.gif)

**Comment by diox** [comment]
@Altalina as mentioned in a previous comment, it will be fixed *next week*. The fix is on our dev environment, but it will be pushed to production next Thursday, around 19:00 CEST.

**Comment by Altalina** [comment]
@diox Is this a global issue? So nobody is able to edit their add-ons? 
Is it possible to list an incomplete add-on?

**Comment by diox** [comment]
It only affects purely unlisted add-ons (add-ons that only have unlisted versions). Editing the details section for those is not very important as they don't have a listing on AMO anyway.

To list such add-ons on AMO, you need to publish a new version, selecting the option to list it on the website instead of hosting it yourself.
