### ISSUE TITLE
Issue when trying to upload an add-on

### ISSUE THREAD

**Issue by tbigueres** [mozilla/addons#774]
### Describe the problem and steps to reproduce it:
Hi, 
I'm trying to suggest a firefox add-on. But when I click on "submit the version" I land on an error that kind of says : "Sorry an error has come up, try to refresh your page"
You'll find the add-on enclosed

### What happened?
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/2139076/44411373-a4818900-a566-11e8-8a92-b97be1ea2745.png">

### What did you expect to happen?
I guess I would expect the add-on to be submitted :) 

### Anything else we should know?
You can find the add-on enclosed 
[Archive.zip](https://github.com/mozilla/addons/files/2306979/Archive.zip)

**Comment by jvillalobos** [comment]
I tried it myself in the development server and it worked okay.

Can you consistently replicate this error? At what point during the submission process did you run into the error page?

**Comment by EnTeQuAk** [comment]
This is actually the same issue as https://github.com/mozilla/addons-server/issues/9203 - I found the same error in sentry.

It'll be fixed Thursday some time after 8pm UTC (or earlier, we start pushing at 4pm UTC)

**Comment by tbigueres** [comment]
Ok thx will retry on friday then !
