### ISSUE TITLE
dictionnaire

### ISSUE THREAD

**Issue by agasthene** [mozilla/addons#775]
Hello

in the earlybird version, it is not possible to add a word to the dictionary,

Whenever I try to add a word when I write a message, every time I get sent to the addition of the dictionary, and even if I add the dictionary in question, that I then want to add a word, despite a reboot, the problem persists, I am returned to the complementary modules page.

Another bug one may minor, but when have navigates on page complementary modules, for adding to the dictionary, and that offer complementary grammalecte as a module, it is not for us returned to the add-on for the browser which should be done, but to the module for Messaging.

**Comment by jvillalobos** [comment]
It seems like you're reporting a bug in the way dictionary code works. In that case, you should file it on [Bugzilla](https://bugzilla.mozilla.org/). It also sounds like it's a bug in Thunderbird you're reporting, so please make sure you choose the right component so the Thunderbird people see it.
