### ISSUE TITLE
Add-on Submition is not working

### ISSUE THREAD

**Issue by bene2386** [mozilla/addons#776]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
I am trying to submit a new add-on but when a click on button submit version gthe next page show me the message Ops! We had a problem.
![image](https://user-images.githubusercontent.com/8397312/44527386-06ec9d80-a6bd-11e8-9284-3289ceb2674e.png)

### What did you expect to happen?
I need to submit my add-on.

**Comment by diox** [comment]
Hi,

Sorry about that. You're hitting https://github.com/mozilla/addons-server/issues/9180 which we have produced a fix for, it will go live in production in 5 hours or so.
