### ISSUE TITLE
about:addons does not seem to return TAAR generated results

### ISSUE THREAD

**Issue by crankycoder** [mozilla/addons#777]
### Describe the problem and steps to reproduce it:

When I look at about:addons - I expect that I should see TAARv3 generated recommendations, but I only see what I believe to be default recommendations.

![add-ons_manager](https://user-images.githubusercontent.com/4829/44607812-a003dd00-a7bf-11e8-9de7-8b4274e079b7.jpg)

The TAAR URLs that should be getting hit are:

- https://taar.prod.mozaws.net/api/recommendations/b0a9e5ae-df53-2649-b47d-f01f055eac51/?branch=intervention-a 

- https://taar.prod.mozaws.net/api/recommendations/b0a9e5ae-df53-2649-b47d-f01f055eac51/?branch=intervention-b

### What happened?

I got default recommendations.

### What did you expect to happen?

I expected at least some of the addons returned by TAAR to show up in my recommendation list.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by kumar303** [comment]
I get the default recommendations (shown here) as well.

@diox any ideas?

**Comment by crankycoder** [comment]
@kumar303 @diox when I query the disco pane directly, I don't see queries passing over to TAAR when I look at redash.

I'm testing by hitting this URL directly:

https://discovery.addons.mozilla.org/en-US/firefox/discovery/pane/61.02/Darwin/normal&branch=intervention-a&clientId=b0a9e5ae-df53-2649-b47d-f01f055eac51&study=taarexpv3

**Comment by willdurand** [comment]
> discovery.addons.mozilla.org/en-US/firefox/discovery/pane/61.02/Darwin/normal&branch=intervention-a&clientId=b0a9e5ae-df53-2649-b47d-f01f055eac51&study=taarexpv3

you mean https://discovery.addons.mozilla.org/en-US/firefox/discovery/pane/61.02/Darwin/normal?branch=intervention-a&clientId=b0a9e5ae-df53-2649-b47d-f01f055eac51&study=taarexpv3?

**Comment by crankycoder** [comment]
Thanks @willdurand  - that link works perfectly.  So somewhere along the line - the discopane URL isn't being generated properly then.

**Comment by crankycoder** [comment]
Or I've got some pref flipped incorrectly and about:addons isn't putting me in the right branch.  I'll dig through the SHIELD code tonight.

**Comment by willdurand** [comment]
> Thanks @willdurand - that link works perfectly. So somewhere along the line - the discopane URL isn't being generated properly then.

Yup, as mentioned on IRC, I don't see those query parameters in the discovery URL pref (`extensions.webservice.discoverURL`).

**Comment by crankycoder** [comment]
I figured out the problem.

PBKM.

![image](https://user-images.githubusercontent.com/4829/44633369-60bcc400-a958-11e8-8693-cc25220921e0.png)

I forced the branch in the SHIELD study addon code to use intervention-a and it's all working for me in nightly.

Sorry for the distraction everyone.
