### ISSUE TITLE
Must use Chrome to view addons.mozilla.org

### ISSUE THREAD

**Issue by philgoetz** [mozilla/addons#778]
The website addons.mozilla.org is only partly functional for me in the latest Firefox (61.0.2 Windows 64-bit), and rendering is screwed up terribly.  See photos.

On Chrome 68:
![180825 addons mozilla org on chrome 68 0 3440 106 official build 64-bit](https://user-images.githubusercontent.com/2772868/44619167-16e8b680-a850-11e8-9df1-572b055d5dee.jpg)

On Firefox 61:
![180825 addons mozilla org on firefox 61 0 2 64-bit](https://user-images.githubusercontent.com/2772868/44619168-16e8b680-a850-11e8-8e1c-bd8b8d8627ad.jpg)

**Comment by EnTeQuAk** [comment]
This is interesting, it works perfectly for me. Does a force-refresh (ctrl+shift+r) help maybe?

**Comment by muffinresearch** [comment]
@philgoetz please can you try running this in a fresh profile [1] if a force refresh doesn't help? I don't see this issue running on windows 10, Firefox 61.0.2 (32-bit). 

[1] https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by eviljeff** [comment]
Closing as no reply from the reporter after two weeks.  We can re-open if it's still a problem.

**Comment by philgoetz** [comment]
Hi, sorry for not replying. I went on vacation shortly after reporting this, & haven't used Firefox much since.  Now, using Firefox 63.0.3 (64-bit), in the same profile, that site appears the same in Firefox as in Chrome.  So something, probably a Firefox update, solved my problem.
