### ISSUE TITLE
Can't view Review history

### ISSUE THREAD

**Issue by jeremybmerrill** [mozilla/addons#782]
### Describe the problem and steps to reproduce it:

0. Be an add-on owner/admin.
1. Go to version list. (e.g.: https://addons.mozilla.org/en-US/developers/addon/facebook-ad-collector/versions )
2. Click Review History on any version.

### What happened?

Got an error message, `e.g. We had a problem retrieving review notes
https://addons.mozilla.org/api/v4/addons/addon/123456/versions/1234567/reviewnotes/, Unauthorized, {"code":"ERROR_INVALID_HEADER","detail":"Invalid Authorization header. No credentials provided."}` (sub'ed out the IDs there)

### What did you expect to happen?

See the review history. To be clear, I'm logged in and have just done admin-related tasks without a problem.

### Anything else we should know?

nope. You can reach me at the email on my Github profile or the email associated with my account that administers https://addons.mozilla.org/en-US/developers/addon/facebook-ad-collector/versions.

**Comment by wagnerand** [comment]
Could you try logging out and logging back in again, please?

**Comment by jeremybmerrill** [comment]
@wagnerand Haha, yes, that did it and it works now. Sorry, should've thought of that first. Thanks!
