### ISSUE TITLE
Exact text search not available

### ISSUE THREAD

**Issue by drawson1** [mozilla/addons#783]
### Describe the problem and steps to reproduce it:
If I want to search for an extension related to HTML tables (for example), I can't limit the search to that text!!  Searching for "table" (in quotes) ALSO returns 40 pages of "tab" extensions (NOT what I needed).  Putting a phrase like "copy table to text" in quotes ALSO fails

### What happened?
Irrelevant results returned

### What did you expect to happen?
I should only see the results that exactly match the quoted text.

### Anything else we should know?
If there's help for the search function, I was not able to find it.

**Comment by muffinresearch** [comment]
Search saw a lot of improvements since this bug was filed, trying the STR I get better results today.
