### ISSUE TITLE
'Versions' URL for 'SoundCloud Downloader - SoundGrab' 404s

### ISSUE THREAD

**Issue by Fironet** [mozilla/addons#784]
### Describe the problem and steps to reproduce it:
Visiting the [Versions](https://addons.mozilla.org/en-US/firefox/addon/soundgrab/versions/) URL for [this addon](https://addons.mozilla.org/en-US/firefox/addon/soundgrab/) 404s. The URL is correct, though. 

### What happened?

The versions page listing all versions of the addon downloads isn't taking the user to the correct page.

### What did you expect to happen?

The versions page to be returned.

**Comment by jvillalobos** [comment]
If you can see the add-on page, then you must be the developer. Regular users shouldn't have access to it. It doesn't appear like that add-on has any versions that are meant for publication. If you want the page to be publicly visible, you need to upload a new version with the option to be hosted on AMO, per [this documentation](https://developer.mozilla.org/en-US/Add-ons/Distribution).

**Comment by Fironet** [comment]
@jvillalobos I'm not actually the dev, I was going through my existing addons and archiving past versions of them.

The main addon page was visible until I brought it up in the addons IRC channel and one of the admin there hid the main page in what I'm not sure may have been an accident. Prior to that the versions page was visible to the admin however. There was a discussion about the fact the past versions had been reviewed as well but it was unclear why the versions URL wasn't showing publicly.
