### ISSUE TITLE
Add publishing feature for controlling update delivery to percentage of users

### ISSUE THREAD

**Issue by MJPWork** [mozilla/addons#786]
Google has ability to release a controlled percentage of add-on updates:

https://developer.chrome.com/webstore/publish#control-how-fast-your-app-reaches-users

This publishing feature is handy to "go slow" with new releases and gauge issue feedback before increasing how many users receive an update.  

I'd like AMO to have this same ability.

(I could not find this request with a quick visual search of open Issues on Github here).

**Comment by diox** [comment]
cc @jvillalobos

**Comment by jvillalobos** [comment]
It has come up before, more than once. Not sure if there's a dupe, but I also couldn't find one.

At the end of the day, it's something we (Product) would like to do, but is not a high priority and it's a fairly complex thing to implement. It's probably not something we would include in the current pipeline, which is pretty full for the next couple of quarters.
