### ISSUE TITLE
error installing extension from a website

### ISSUE THREAD

**Issue by anktsngh** [mozilla/addons#787]
Cannot install an addon called Buyhatke (Indian equivalent to 'Honey' extension) due to the error: 'the addon could not be downloaded due to a connection error'. The issue has been prevalent at least since FF Quantum release. To reproduce, visit: https://compare.buyhatke.com/extension.php and click on 'Get this tool now'.

**Comment by jvillalobos** [comment]
You should contact the developers of the extension about that problem.
