### ISSUE TITLE
Can't reach add-ons beyond 25000 (= the 1000th page with page_size 25) via the search API (/api/v3/addons/search/) 

### ISSUE THREAD

**Issue by motin** [mozilla/addons#788]
### Describe the problem and steps to reproduce it:

Goal: We need a full list of the add-ons published on AMO, but requesting any results set from the API beyond the 25000th add-on yields `{"detail":"Invalid page."}`

**Details:**
Requesting the first page of results from https://addons.mozilla.org/api/v3/addons/search/?app=firefox&type=extension&page=1 gives the following metadata:

     "page_size":25,"page_count":1000,"count":26556

Since the max page_count is 1000 and 25*1000, I can't list the add-ons beyond 25000. [Attempting to reach page 1001 yields](https://addons.mozilla.org/api/v3/addons/search/?app=firefox&type=extension&page=1001) `{"detail":"Invalid page."}`

### What happened?

1. page_count is 1000
2. `{"detail":"Invalid page."}` upon navigation to the pages requires to list the add-ons beyond 25000

### What did you expect to happen?

1. I expect the page_count to be equal to Math.ceil(count/page_size), in this case 1063 (Since 26556/25 = 1062,24)
2. I expect navigation to the pages requires to list the add-ons beyond 25000 to list the add-ons

### Anything else we should know?

Seems to be related to "AMO website: Navigating past page 1000 is not possible #552 ", but not directly related to the one that https://github.com/mozilla/addons/issues/552 is marked a duplicate of ([New AMO pages don't return correct number of pages after empty search #3887](https://github.com/mozilla/addons-frontend/issues/3887)), since there is no empty search involved.

**Comment by willdurand** [comment]
There is a hard limitation on the API side (https://github.com/mozilla/addons-server) if I remember correctly.

**Comment by motin** [comment]
@willdurand Got it, will close this one and report it there instead.
