### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by rjhansen** [mozilla/addons#789]
Please attach a copy of your add-on, and fill in the following information:

* First it occurred while updating the source code for an add-on under review.  Problem recurred when attempting to upload it as a new add-on.

* Unlisted (has not yet been approved by Moz).

* https://addons.thunderbird.net/en-US/developers/addon/submit/upload-listed

* 3:35am US Eastern time on September 12, 2018

* The validation system simply said there was an "unexpected error" with no guidance as to how to resolve it

Note: the attached file is an XPI, but your submission system refuses to accept them.

[ses_tb-v1.0.zip](https://github.com/mozilla/addons/files/2374020/ses_tb-v1.0.zip)

**Comment by eviljeff** [comment]
Issues relating to the Thunderbird/Seamonkey addons website need to be filed in their repository:
https://github.com/thundernest/addons-server/issues

**Comment by rjhansen** [comment]
I uploaded it to the Thunderbird add-on system, it gave me an unexpected error, and told me to submit a bug report here.  If here isn't the right place, I'd suggest telling Thunderbird to correct their error message.
