### ISSUE TITLE
Firefox Add-Ons - Add-On Type: Search Tool dropdown sort criteria is BOGUS JUNK

### ISSUE THREAD

**Issue by bobwho** [mozilla/addons#792]
### Describe the problem and steps to reproduce it:
THE SEARCH TOOL SORT CRITERIA on FIREFOX EXTENSION ADD-ONS is USELESS GARBAGE.  FIX OR NIX.

GOTO
https://addons.mozilla.org/en-US/firefox/search/?q=search&platform=WINNT&appver=62.0

(Please include as many details as possible.)

It JUST SUCKS and has never made any sense at all.  The output is retarded and useless and has been for years.  Does anyone notice this bogus output or even care?

### What happened?

Select: Search Tool from Add-On Type drop-down menu.
Select: ANY SORT CRITERIA

### What did you expect to happen?

I expected SORTING BY CRITERIA - What I get is steamy heaps of dung EVERY TIME for MANY YEARS!

### Anything else we should know?

A LITTLE USER EXPERIENCE QA IS NEEDED AT LEAST ONCE A CENTURY.

Does anyone notice when your search and help information is BROKEN, STALE, or BOGUS?  

Well after many years of seeing this BROKEN P.O.S. I guess I need to SHOUT that if you can't perform an index SORT output of the 4,000 "Search Tool Add-Ons" in a MEANINGFUL AND ACCURATE WAY then please just REMOVE THE BROKEN FEATURE.  Why FAKE SORT this redundant spyware?

THE OUTPUT SUCKS, AND IT NEVER IMPROVES SO ELIMINATE IT.  Or FIX IT.  BOGUS SORT OUTPUT SUCKS AND IT NEVER CHANGES.  PLEASE PAY ATTENTION AND REPAIR.  THANK YOU.

**Comment by EnTeQuAk** [comment]
We are improving search over time, more specifically via https://github.com/orgs/mozilla/projects/38 and https://github.com/orgs/mozilla/projects/17 and are happy to help with specific requests and are looking forward to users reporting specific problems they are having with search to better understand their needs and work on that in the future.

The link you mentioned does contain a lot of add-ons related to the "search" term which looks fine to me, they are ranked by relevance and you have the chance to change that sorting order appropriately.

Given that you did not include any explicit problem and are shouting and insulting I'm going to close this issue and lock the conversation.

If you have a specific problem to report in the future we're happy to help.
