### ISSUE TITLE
blocksite

### ISSUE THREAD

**Issue by gji2163** [mozilla/addons#794]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
[..txt](https://github.com/mozilla/addons/files/2396932/default.txt)

I am not able to edit my settings in block site ... also i think block site should block sites so that nobody can access the sites but because mozilla has kept an option of "remove addons", anybody can easily unblock the sites without even knowing the password.

**Comment by jvillalobos** [comment]
Please contact the add-on developer about this problem. This issue tracker is only for the add-ons website.

**Comment by gji2163** [comment]
Thanks for the quick reply. But one of my problems also stated that Mozilla
Firefox also has an option of remove add on which is creating a problem

**Comment by jvillalobos** [comment]
Bugs in Firefox can be reported on [Bugzilla](https://bugzilla.mozilla.org/), but I'm fairly sure that the context menu item will not be removable.
