### ISSUE TITLE
Thunderbird Add Theme links broken

### ISSUE THREAD

**Issue by adrienne77** [mozilla/addons#795]
### Describe the problem and steps to reproduce it:
All of the "Add Theme" links on the Thunderbird website (https://addons.thunderbird.net/en-US/thunderbird/themes/) are broken.  Every time I click on the "Add Theme", the website redirects to the "We're sorry, but we can't find what you're looking for" page.
### What happened?
Went to download a new theme for Thunderbird, cannot find a single "Add Theme" link that works.
### What did you expect to happen?
The theme to download, especially for the recently added themes.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by caitmuenster** [comment]
Thanks, @adrienne77! The Thunderbird folks can help out with this.  Can you file this issue over at https://github.com/thundernest/addons-server?
