### ISSUE TITLE
Google.com Cookie does not destruct

### ISSUE THREAD

**Issue by James32111** [mozilla/addons#796]
After logging into Google account then logging out and opening a new window, the Google.com cookie has not destructed and remains in the Firefox Cookies Folder.

All other cookies appear to destruct apart from this one.

The default search engine I use is DuckDuckGo and not Google.

**Comment by jvillalobos** [comment]
For Firefox help, please go to https://support.mozilla.org/. If you want to file a Firefox bug, you can do it on https://bugzilla.mozilla.org/

**Comment by James32111** [comment]
Jorge Villalobos,

I was attempting to raise an issue with Self-Destructing Cookies not deleting a Google.com cookie,

Regards,

Greg Alexander

&nbsp;


On Mon, 24 Sep 2018 21:02:56 +0000 (UTC), Jorge Villalobos  wrote:
&nbsp;
For Firefox help, please go to https://support.mozilla.org/. If you want to file a Firefox bug, you can do it on https://bugzilla.mozilla.org/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mozilla/addons/issues/796#issuecomment-424123923",
"url": "https://github.com/mozilla/addons/issues/796#issuecomment-424123923",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mozilla/addons] Google.com Cookie does not destruct (#796)",
"sections": [
{
"text": "",
"activityTitle": "**Jorge Villalobos**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jvillalobos",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mozilla/addons\",\n\"issueId\": 796,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mozilla/addons/issues/796#issuecomment-424123923"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 383530988\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by jvillalobos** [comment]
In that case you should try contacting the add-on developer.
