### ISSUE TITLE
Could not establish connection error in browser console with Awesome Screenshot plus addon installed

### ISSUE THREAD

**Issue by c-fogel** [mozilla/addons#801]
STR:

1. Install Awesome Screenshot Plus 
https://addons.mozilla.org/en-US/firefox/addon/screenshot-capture-annotate/?src=cb-dl-users
2. Open a new tab with any other addon;
3. Click on the tabs;
4. Repeat the previous step after refreshing each page

Actual result:
Error messages displayed in the Browser Console
"Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist."

Expected result:
No error message should be displayed

Notes:
- reproducible on 63.0b11, latest nightly (64.0a1);
- affected OS: win10x64, Ubuntu 16.04LTS, macOS 10.12
- happened on the new_tab page as well;
- in some cases refreshing the page was enough to cause the issue;
- clicking on the nested link opens an empty new tab;

**Comment by diox** [comment]
Hi,

This github project is to track issues with addons.mozilla.org and it looks like you're reporting an issue with an add-on and not the AMO website. Please contact the add-on developer instead, thanks.
