### ISSUE TITLE
[feature request] filtering by webExtension themes on addons.mozilla.org

### ISSUE THREAD

**Issue by Dani3lNL** [mozilla/addons#802]
Please allow filtering for webExtension themes on https://addons.mozilla.org/en-US/firefox/, so users can search for either basic themes or webExtension themes (as webExt. themes are way more customizable).
Currently filter only shows "theme" and "extension", not "webExtension theme".

**Comment by wagnerand** [comment]
As per the [blog post](https://blog.mozilla.org/addons/2018/09/20/future-themes-here/) we will migrate lightweight themes later this year, so all of them will have the same format.

**Comment by Dani3lNL** [comment]
Ok thanks! I didn't know "migrate" meant same format. @wagnerand
