### ISSUE TITLE
Bad Request on Theme Generator when using Firefox or Mozilla on theme name

### ISSUE THREAD

**Issue by snoopy3476** [mozilla/addons#804]
### Describe the problem and steps to reproduce it:

1. Go to the theme generator on AMO

[Submit a New Add-on > Theme generator] on [Add-on Developer Hub]
or
https://addons.mozilla.org/developers/addon/submit/wizard-unlisted

2. Type 'Mozilla' or 'Firefox' inside the 'Theme name'.

3. Press 'Finish Theme' button.

### What happened?
It only says 'Bad Request', and no other information about what is the problem.

### What did you expect to happen?
Displaying some error messages like "A theme name including the words 'Mozilla' or 'Firefox' is not allowed", instead of 'Bad Request'.
People will be confused at this point if it says nothing about the exact problem.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
Can you reproduce this consistently? I tried to do this a couple of times and didn't have any problems.

**Comment by AlexandraMoga** [comment]
I can also reproduce this consistently if I'm logged in with a regular account.
It won't be reproduced when logged in with a Mozilla account.


![image](https://user-images.githubusercontent.com/31961530/46457894-a0c76000-c7bc-11e8-8ebd-096408ac9f70.png)

**Comment by jvillalobos** [comment]
Ah, good catch.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/47662083-ef410200-dba2-11e8-84b5-a60e0c2f2b03.png)
