### ISSUE TITLE
Dragon Web Extension

### ISSUE THREAD

**Issue by easton3** [mozilla/addons#806]
After telling me to do so, and prompting me, to restore the connection to Dragon web extension by installing it. And then it tells me it can't download it because the lack of a connection! My connection is secure, why wouldn't it download? More importantly, why couldn't I find it on your support site for add-ons, plug-ins, and extensions. Numerous searches turned up nothing relating to a Dragon web extension. 

Please advise as to what to do.
Edward Easton
![screenshot 250](https://user-images.githubusercontent.com/41224010/46515207-08ff5b80-c828-11e8-968c-4520f663cec7.png)
![screenshot 251](https://user-images.githubusercontent.com/41224010/46515208-08ff5b80-c828-11e8-93b9-a38df1a6dfc7.png)
![screenshot 252](https://user-images.githubusercontent.com/41224010/46515209-08ff5b80-c828-11e8-8fcd-ddbf501462a4.png)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
This is most likely a configuration problem on the website where you tried to install the extension. Please look for support or help links on that website to contact the developers.
