### ISSUE TITLE
I can't comment on a review.

### ISSUE THREAD

**Issue by datermine** [mozilla/addons#813]
### Describe the problem and steps to reproduce it:
I try to comment on a review, can't. Showing 500's in the console.

### What happened?
Internal server error

<img width="1440" alt="screen shot 2018-10-15 at 1 13 59 pm" src="https://user-images.githubusercontent.com/286251/46967099-8ffcd100-d07d-11e8-8fc1-4b55118c0285.png">

https://addons.mozilla.org/en-US/firefox/addon/table-to-excel/reviews/1211653/

**Comment by datermine** [comment]
Removed emoji, it "worked" https://addons.mozilla.org/en-US/firefox/addon/table-to-excel/reviews/1211653/

- <table> and <div> text is being removed. Kind of annoying. It's 2018, I should be able to .
- Not sure why emoji are causing the 500s, but better error messaging would be 🔥 

Could close this. Could keep it open. Up to you.

**Comment by willdurand** [comment]
We are working on Emoji support 🌈

**Comment by willdurand** [comment]
See: https://github.com/mozilla/addons-server/issues/8923
