### ISSUE TITLE
Feeds hosted on addons.mozilla.org can't be accessed by web extensions due to security policy

### ISSUE THREAD

**Issue by ali1234** [mozilla/addons#816]
When Firefox [removes build-in feed support](https://bugzilla.mozilla.org/show_bug.cgi?id=1477667) the only way to access feeds will be through web extensions. But web extensions can't access addons.mozilla.org for security reasons. This means Firefox won't be able to display feeds from AMO at all.

One solution would be to simply move or proxy the feeds onto a different domain name.

An example of a feed on AMO: https://addons.mozilla.org/en/firefox/extensions/format:rss?sort=updated

**Comment by jvillalobos** [comment]
Feeds on AMO are also going away. The new site doesn't expose them, and the old site will soon go away. To get to AMO data, the new supported way to go is to use the [API](https://addons-server.readthedocs.io/en/latest/topics/api/overview.html).
