### ISSUE TITLE
Firefox Color's 1 MB limitation is too restrictive

### ISSUE THREAD

**Issue by thomasseymour18901** [mozilla/addons#817]
I can't resize the images I've taken of places like New York, New Jersey, Pennsylvania and New England I want to be able to contribute to Firefox Themes under a creative commons license one at a time.

**Comment by eviljeff** [comment]
Hi, addons.mozilla.org theme wizard (and xpi upload) has a limit of 7MB rather than 1MB, so if you want you can use that directly.  https://addons.mozilla.org/developers/theme/submit

Problems with Firefox Color should be logged @ https://github.com/mozilla/FirefoxColor
