### ISSUE TITLE
Searching for "scrolljacking" also yields false results

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/addons#818]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I'm looking for tools to protect against scrolljacking, because certain types of scrolling trigger my migraines. (smart scroll, autoscroll, pages imposing autoscroll, fixed backgrounds, fixed sidebars, fixed headers, etc.)

I searched for "scrolljacking"...

### What happened?

I got inundated with tools which don't address scrolljacking.

### What did you expect to happen?

I hoped to find tools to protect against scrolljacking.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
You'll always going to get add-ons that don't match exactly what you are searching for, in an attempt to fix typos, potential missing whitespace, etc - both in what the user is searching for but also in add-on info entered by developers.

I don't think there are any add-ons that truly address scrolljacking on AMO - if you do know of any, and they don't appear at the top of the results for that query, let us know and we'll re-open this issue to try to fix that.

**Comment by MarjaE2** [comment]
Is it so much to let people search for search terms? Instead of returning results which lack these terms, in the name of "correcting spelling"?

**Comment by diox** [comment]
This is not just about correcting spelling. It's also correcting word separators - we want people searching for "FooBar" to find an add-on named "Foo Bar", or with "Foo Something Bar" in the description. There is an ongoing effort this quarter to improve search relevancy, and you'll be able to see the results improving each week starting at the end of this week, but ultimately we can't please everyone. There are issues filed about people expecting synonyms, common misspellings, prefixes, fuzzy matches to work as well.
