### ISSUE TITLE
Count is missing

### ISSUE THREAD

**Issue by iamVP7** [mozilla/addons#819]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Visit  https://addons.mozilla.org/en-US/firefox/addon/youtube-10423/?src=search 
Check the count of install and reviews

### What happened?
install count is 0, and there are some review counts

### What did you expect to happen?
I expected count to be greater than 0.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![count](https://user-images.githubusercontent.com/3106852/47309599-7bf33980-d652-11e8-859a-5ed6abd95e23.png)

cc @willdurand

**Comment by EnTeQuAk** [comment]
That is very interesting, it looks like we're not tracking installs for search-tools, looking at https://addons.mozilla.org/en-US/firefox/search-tools/ that's actually the case for all search tools.

**Comment by willdurand** [comment]
> That is very interesting, it looks like we're not tracking installs for search-tools, looking at [addons.mozilla.org/en-US/firefox/search-tools](https://addons.mozilla.org/en-US/firefox/search-tools/) that's actually the case for all search tools.

This looks like a server issue to me, should we re-open this issue in addons-server?

**Comment by diox** [comment]
I think it's actually a frontend issue. We don't have user stats for search tools, because they don't ping us for updates. The legacy pages worked around this issue by never displaying a user count for search tools in the search or detail pages, displaying weekly downloads instead.

**Comment by willdurand** [comment]
> I think it's actually a frontend issue. We don't have user stats for search tools, because they don't ping us for updates. The legacy pages worked around this issue by never displaying a user count for search tools in the search or detail pages, displaying weekly downloads instead.

I would have expected some server support to get stats for search tools, but providing a slightly different UI for those add-ons sounds good too.

I filed a frontend issue to hide the install count: https://github.com/mozilla/addons-frontend/issues/7316.
