### ISSUE TITLE
A sudden spike of weekly downloads in October 15-19

### ISSUE THREAD

**Issue by fluks** [mozilla/addons#820]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?

I noticed that weekly downloads of all my addons had risen dramatically. There were spikes on statistics page from 15th to 19th of October. Maybe 10 times more weekly downloads than usually. I wasn't advertising my addons to anyone. Here are all my addons:

https://addons.mozilla.org/en-US/firefox/addon/download-plenty/ 
https://addons.mozilla.org/en-US/firefox/addon/finnish-spellchecker-dict/ 
https://addons.mozilla.org/en-US/firefox/addon/redirect-link/ 
https://addons.mozilla.org/en-US/firefox/addon/mark-location/

### What did you expect to happen?

Somewhat stable number of weekly downloads.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

I asked about this on IRC channel and I was asked to report about it here.

**Comment by EnTeQuAk** [comment]
As I don't necessarily see any other, current spikes and many other add-ons are affected I'm going to close this until it happens again which may make investigation easier when it's fresh.
