### ISSUE TITLE
Broken link in the self loading TB 60 tutorial

### ISSUE THREAD

**Issue by josephj11** [mozilla/addons#823]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
https://addons.mozilla.org/en-US/firefox/thunderbird/addon/theme-font-size-changer/
link is broken in the doc that loads when you first start TB 60 (accessibility)
### What happened?
I expected that add-on page to open so I could install it
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
You provide a very nice web page that opens up the first time you launch TB 60.
That site should have a prominent self link in it so it can be copied and bookmarked in a browser.
Without it, you end up at the top of all Mozilla help with no easy way back to all the specific help pages it references.

**Comment by jvillalobos** [comment]
If this is a link you found on Thunderbird, then you should file a bug so they update that page. We recently moved Thunderbird add-ons to their own website, addons.thunderbird.net. It looks like [you have a couple of options](https://addons.thunderbird.net/thunderbird/search/?q=Theme+Font+%26+Size+Changer) you can install for Thunderbird.

This is not an AMO bug.
