### ISSUE TITLE
Firefox addon page incompatibility

### ISSUE THREAD

**Issue by DanUber** [mozilla/addons#826]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I m gonna try to be as brief as possible. 
https://addons.mozilla.org/
The new style of web page is not working.  Does not load images , icons and stylessheets correctly. 
Does not allow to see any image or even download a addon or theme. 
Pay attention before answer  (a stolen automatic response) from yahoo answers. This is not a cookie related problem. This is not a client side bug. This is a server side bug . Ok?  
The page in their root has programming flaws has a lot of bugs and no matter if you use the last Chrome browser or firefox o another navigator, A clean install under Windows 7 / 8 produce the same results. The behavior is  the same. 

### What happened?

This are the scripts in Ffrefox eeb console
*************Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:18196
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:19077
Unknown property ‘grid-auto-flow’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:19096
Unknown property ‘grid-gap’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:19118
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:19147
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:19226
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:19237
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:19909
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:21192
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:32622
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:41187
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:50785
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:58384
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:70473
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:78002
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:83414
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:93465
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:102652
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:117106
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:132202
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:142168
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:151456
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:161036
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:169425
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:178073
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:184683
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:195380
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:203853
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:209468
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:217376
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:223919
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:231980
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:238947
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:244958
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:253026
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:267185
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:279277
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:288752
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:298660
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:307147
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:313502
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:320380
Expected end of value but found ‘no-repeat’.  Error in parsing value for ‘mask’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:330149
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:334206
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:335145
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:335246
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:340759
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:340785
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:341154
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:341431
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:341674
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:342087
Unknown property ‘grid-area’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:345187
Unknown property ‘grid-area’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:345255
Unknown property ‘grid-area’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:345324
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:345726
Unknown property ‘grid-gap’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:345739
Unknown property ‘grid-template’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:345758
Unknown property ‘grid-template-areas’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:345782
Unknown property ‘grid-template’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:345897
Unknown property ‘grid-template-areas’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:345933
Unknown property ‘grid-gap’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:346060
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:346680
Unknown property ‘grid-gap’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:346693
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:346722
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:347559
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:348012
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:348206
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:349021
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:349948
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:367904
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:368161
Unknown property ‘grid-auto-flow’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:368180
Unknown property ‘grid-gap’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:368202
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:368231
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:368321
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:368373
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:368667
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:369064
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:370099
Unknown property ‘grid-auto-flow’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:370118
Unknown property ‘grid-gap’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:370140
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:370169
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:370372
Unknown property ‘grid-auto-flow’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:370391
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:370417
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:370621
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:373173
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:374528
Unknown property ‘grid-auto-flow’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:374547
Unknown property ‘grid-gap’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:374569
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:374596
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:374810
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:374823
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:374899
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:374913
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:374988
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:374999
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:375740
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:375939
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:375965
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:376606
Unknown property ‘user-select’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:377704
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:380282
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:381571
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:383880
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:384989
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:385882
Unknown property ‘grid-template-areas’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:385906
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:386028
Unknown property ‘grid-area’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:386111
Unknown property ‘grid-area’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:386153
Unknown property ‘grid-area’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:386721
Unknown property ‘grid-area’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:387042
Unknown property ‘grid-area’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:387266
Unknown property ‘grid-area’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:387429
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:388893
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:390574
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:392348
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:392374
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:392431
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:392545
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:392641
Unknown property ‘grid-template-columns’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:392691
Unknown property ‘grid-template-rows’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:392730
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:392848
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:392866
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:393044
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:393206
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:393217
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:393865
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:393876
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:394023
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:394037
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:394111
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:394125
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:395180
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:395198
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:395482
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:395495
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:395702
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:395860
Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:395878
Unknown property ‘grid-column’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:395983

Unknown property ‘grid-row’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:395996
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:396491
Error in parsing value for ‘display’.  Declaration dropped.amo-15ced14c03758c822edc5fe13587b435.css:3:396995

        

### What did you expect to happen?

I expect the addons page working correctly. And I expect it could be download any addon from any browser. I expect better compatibility. So I expect you redesign the whole site or go back to the old style. This is not happening with  thunderbird addon page that works flawslessly.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

![untitled](https://user-images.githubusercontent.com/35860793/47895321-7c57b580-de46-11e8-86e0-6c5e7fcdbd5c.jpg)
![untitled2](https://user-images.githubusercontent.com/35860793/47895350-a90bcd00-de46-11e8-82b0-0aebdcb91e9e.jpg)
![thunderbird](https://user-images.githubusercontent.com/35860793/47895461-233c5180-de47-11e8-9398-0f0be3bb0869.jpg)
*********************************************
As you can see, Thunderbird addons page is working perfect

**Comment by DanUber** [comment]
As you can see, thunderbird addon page is working flawlessly

**Comment by kumar303** [comment]
> The page in their root has programming flaws has a lot of bugs and no matter if you use the last Chrome browser or firefox o another navigator

Hello, thanks for taking the time report a bug. Everything is working for us in the latest Chrome and Firefox on Windows. Can you provide the exact user agent for your version of Firefox where you are seeing this broken layout?

**Comment by DanUber** [comment]
Another example. I cant download anything. ANYTHING. 

![firefox1](https://user-images.githubusercontent.com/35860793/48110233-b4397100-e229-11e8-87b7-becd036f2de8.jpg)

and after I do click on tre button

![firefox2](https://user-images.githubusercontent.com/35860793/48110265-da5f1100-e229-11e8-91c1-788ba89ba0a9.jpg)

And the same thing with Chrome 69

![404](https://user-images.githubusercontent.com/35860793/48110281-eea30e00-e229-11e8-94a8-ce155ece4983.png)

The page was working perfect with the old style and was compatible with any almost browser 
What the heck they did ?

**Comment by DanUber** [comment]
![firefox3](https://user-images.githubusercontent.com/35860793/48180560-c509e580-e302-11e8-8cbc-2c0a3217ca4d.jpg)

**Comment by kumar303** [comment]
Thanks for following up with details and screenshots.

I'm a little confused. Is this the URL you were on? https://addons.mozilla.org/en-US/firefox/addon/adkiller-adblocker/ It is a 404 for me.

Can you download any add-ons at all?

We don't support Firefox 57.0.1 because it's older than [ESR](https://www.mozilla.org/en-US/firefox/organizations/), the oldest we support. However, installation should work.

> Another point is why I cant download an extension or theme with Chrome or another browser ?

That is an open issue that we would like to fix: https://github.com/mozilla/addons-frontend/issues/3445

**Comment by DanUber** [comment]
Hello Kumar 
I´ve tried  download different add ons in different categories with both browsers.  I could guess is a javascript  related thing, like a filter. Getting  404 is ever  more weird

**Comment by kumar303** [comment]
Is there any reason why you can't use a newer version of Firefox?

**Comment by DanUber** [comment]
An old pc. but is too much work to make an universal front end page ?
Ive tried a portable version  of firefox  I guess  60.xx  or something and the same thing. 
 Btw why I can´t download extensions If I´m using Internet explorer Edge  or Chrome. 
What´s the reason to do that, to block it ?


Antoher example trying to download an extension 

[social_fixer-23.0.0-fx.zip](https://github.com/mozilla/addons/files/2579474/social_fixer-23.0.0-fx.zip)
download it Youll see it´s empty. Why  they are blocking any extension from download ?
What´s the purpose ?
Why block that. ? 
Is not the NSA.  I´m confused
