### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by rovf** [mozilla/addons#827]
### Describe the problem and steps to reproduce it:
I can not access my Mozilla account anymore. I have created in 2008 an account with user name 

    GLP

and the email address is since 2014
  
    ynnor@mm.st

I still can see, that the account exists, because I can see it using the link

    https://addons.mozilla.org/en-US/firefox/user/glp/

However, I can not login using the email address (Error message: "Unknown Account"). Even if I go to "Forgot password?", I get this error message.

The last time it worked, was early this year. I didn't use my account during summer.

**Comment by jvillalobos** [comment]
We recently changed the authentication system for the site, so old accounts lost access. You can regain access by creating a new account using the same email address. That will give you access to the original account and its contents.

If you need more help, please email amo-admins AT mozilla DOT org
