### ISSUE TITLE
Statistic dashboard for Thunderbird add-ons is not working since split from AMO

### ISSUE THREAD

**Issue by Aris-t2** [mozilla/addons#828]
### Describe the problem and steps to reproduce it:
Visit statistic dashboard of any Thunderbird add-on, e.g. https://addons.thunderbird.net/en-us/thunderbird/addon/customizemybird/statistics/?last=30
Page is not displayed correctly.

### What happened?
Infinite loading screens, stats not updated for month.

### What did you expect to happen?
Visual appearance of statistics like present before Thunderbird add-ons moved from https://addons.mozilla.org/ to https://addons.thunderbird.net/

### Anything else we should know?
This issue is present for month. Strange nobody has reported anything yet.
![1](https://user-images.githubusercontent.com/6013569/48013886-b3b7b200-e125-11e8-9501-65176bb973f7.png)

**Comment by diox** [comment]
Hi,

Since Thunderbird add-ons have split from AMO, this needs to be reported over https://github.com/thundernest/addons-server , not here. Thanks!
