### ISSUE TITLE
Video Interaction

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons#83]
In a nutshell: Click small video thumbnail, copy to the left fades away, video window grows down and to the left, and pushes all the content down. Clicking "Close video" reverses the flow.
Normal:
![disco pane-video](https://cloud.githubusercontent.com/assets/6797635/14297607/ba324cbe-fb4d-11e5-9f33-b5ddaf11f5e2.png)

Expanded:
![video - expanded](https://cloud.githubusercontent.com/assets/6797635/14287051/559ce21a-fb1f-11e5-9545-01e1d43a30ef.png)

**Comment by mstriemer** [comment]
What's the colour/font-weight on that "Close video" text?

**Comment by pwalm** [comment]
/* Close video: */
font-family: [platform default];
font-weight: regular;
font-size: 12px;
color: #0996F8;

underline on hover!

**Comment by andymckay** [comment]
@mstriemer and @pwalm, this is done and we can close I think?

**Comment by pwalm** [comment]
Close it!
