### ISSUE TITLE
The ability for extensions to tamper with cross-origin resource sharing (CORS) headers disables the Same Origin Policy (SOP)

### ISSUE THREAD

**Issue by mesolido** [mozilla/addons#830]
### Describe the problem and steps to reproduce it:
We created the CORSER extension - https://github.com/mesolido/corser - that manipulates CORS headers to allow unauthorized cross-origin requests
We submitted it for review 
We also analyze AMO to find extensions that tamper with CORS headers like done by CORSER

### What happened?
CORSER was approved as a benign extension and get published on AMO -  https://addons.mozilla.org/en-US/firefox/addon/corser-addon/ 

We found on AMO extensions that behave like CORSER. Additionally, some extensions were modifying CORS headers in a way that break legitimate CORS requests. In other words, installing such extensions prevent the user from using some legitimate applications, such as playing youtube videos, etc.

### What did you expect to happen?
Installating an extension that tampers with CORS headers, any script running in the user browser can make successful CORS requests to any application (Gmail, Twitter, Facebook, etc.) and therefore access user sensitive data on those applications. This is a bypass of the SOP. 
We expected that CORSER would have been blocked

### Anything else we should know?
Such extension (and some that we found on AMO), by manipulating CORS headers, allows any cross-origin request. This disables the Same Origin Policy in browser

This is a part of a study we are doing on the ability for extensions to tamper with CORS headers and other security-critical headers. The extension does not collect any information, or leak us information to us.

We think that manipulating such headers must not be allowed (as is the case for some request headers such as cache) or to do so, extensions would have to request dedicated permissions.

**Comment by jvillalobos** [comment]
There are two parts to this. First, whether Firefox should do anything to block this kind of activity. That should be [filed as a bug in Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=WebExtensions).

The AMO side has more to do with the linter and review policy, which I'll defer to @wagnerand 

I suspect the answer you'll get in both cases is that it's not possible to allow benign uses of this API without also allowing malicious ones.

**Comment by mesolido** [comment]
I already filed a bug but it get closed for the reason that what I am reporting is an AMO issue, and that it should be discussed here on Github. Here is the link to the bug  https://bugzilla.mozilla.org/show_bug.cgi?id=1500345

**Comment by wagnerand** [comment]
I agree with @jvillalobos. We will certainly take action when we see malicious behavior during review.

**Comment by mesolido** [comment]
Thanks @jvillalobos and @wagnerand for provided more feedback and considering such extensions during review process. 
So from what I can read, you think that the ability for extensions to tamper with security headers must be allowed in a first place, then during review, you will try to block malicious ones.

Nonetheless, there are some headers that cannot be modified by extensions. This includes Cache-Control, If-Modified-Since, If-None-Match. Why not extending this to sensitive security headers like CORS ones, which in our opinion, pose more security threats.

Otherwise, make it mandatory for extensions developers to request dedicated permissions before manipulating security headers. Hence for instance, in addition to the traditional "webRequest" and "webRequestBlocking" permissions, one would have to also declare "Access-Control-Allow-Origin" as a permission in order to be able to manipulate the "Access-Control-Allow-Origin" header. 
This would help in 2 situations: - first you can directly identify extensions that potentially manipulate security headers (by looking at their permissions) and focus more carefully on them during review. Moreover, you can precisely warn users that extensions they install manipulate security headers such as CORS, with the consequence that this could introduce security holes in their  browser.

**Comment by wagnerand** [comment]
> Why not extending this to sensitive security headers like CORS ones, which in our opinion, pose more security threats.
> Otherwise, make it mandatory for extensions developers to request dedicated permissions before manipulating security headers. Hence for instance, in addition to the traditional "webRequest" and "webRequestBlocking" permissions, one would have to also declare "Access-Control-Allow-Origin" as a permission in order to be able to manipulate the "Access-Control-Allow-Origin" header.

Both approaches would probably break cross-browser compatibility.
I also don't know the reason for restricting some headers but not others. Either way, change-requests to the API or the permissions model need to be [filed in Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=WebExtensions).

**Comment by mesolido** [comment]
Thanks @wagnerand  for the comment. I will file a bug

**Comment by jvillalobos** [comment]
Alright, sounds like there isn't anything to do for this issue, so I'm closing it.
