### ISSUE TITLE
Unable to access Firefox addons website after login

### ISSUE THREAD

**Issue by cenon415** [mozilla/addons#831]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I recently changed my Firefox account's email address and had already verified/confirmed the change. 
Step 1 - I go to https://addons.mozilla.org/en-US/firefox/#login
Step 2 - I log in with the correct email and password.

### What happened?
After login, it takes me to a blank white page with an error code {"detail":"Internal Server Error"}
### What did you expect to happen?
I expected to be on the Firefox Add-on website like normal with no issues.
### Anything else we should know?
The link below is a screenshot of the results after login.
[Screenshot1](https://i.redd.it/tzdhrxyub6x11.png)
I have tested this on 4 different browsers and the problem persists. It seems that my account is the only one affected by this problem.

**Comment by diox** [comment]
Hi,

Thanks for reporting this. It looks like you now have 2 accounts on AMO, and that's what's causing the issue. I'm not sure exactly how that happened though, maybe we never got the notification from FxA that your email changed or something along those lines.

@jvillalobos is this something you can fix with admin powers ?

**Comment by jvillalobos** [comment]
@cenon415 Please email amo-admins AT mozilla DOT org with the details. We'll look into this. I'm not sure we can fix it from the admin side, but we start there.

**Comment by diox** [comment]
FWIW it's https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4448986/

**Comment by cenon415** [comment]
I had emailed amo-admins and the problem was solved. Thank you.
