### ISSUE TITLE
Statistics for Add-on not updating from long on Firefox 

### ISSUE THREAD

**Issue by selenium-makeiteasy** [mozilla/addons#832]
### Describe the problem and steps to reproduce it:
Statistics for Add-on not updating from long on Firefox 
This is my add-on for which stats is not updated from 15days.
https://addons.mozilla.org/en-US/firefox/addon/chropath-for-firefox/statistics/?last=30

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/8011888/48345981-9a6fb200-e69f-11e8-853f-cee6ab18fbdc.png">

**Comment by diox** [comment]
Hi,

This is a global recurring issue that's being tracked in https://github.com/mozilla/addons/issues/510

**Comment by sanjayautonomiq** [comment]
Thank you for the quick update.
