### ISSUE TITLE
Web page displayed fake error and locked up the browser 64.0b8 Qunantum

### ISSUE THREAD

**Issue by mountainhiker7** [mozilla/addons#833]
### Anything else we should know?
sku7gynqepz8ugmpmlmy.services/en
![fake error-v2](https://user-images.githubusercontent.com/21106092/48379575-97c28c00-e6a2-11e8-8e9f-998a8aa26370.jpg)
![fake error-v3](https://user-images.githubusercontent.com/21106092/48380508-05bc8280-e6a6-11e8-8b60-9512f1a95b9e.jpg)

**Comment by jvillalobos** [comment]
For Firefox support, please visit https://support.mozilla.org/

This repository is for the add-ons website only.
