### ISSUE TITLE
Will Junquilla add-on ever be updated to work with Thunderbird 60+?

### ISSUE THREAD

**Issue by chaspear** [mozilla/addons#835]
Just wondering whether Junquilla filtering add-on will be updated to work with Thunderbird version 60 or later?
I found this filtering software to be GREAT at helping weed out the junk that just keeps coming and coming.
If this is in the works, that's great, if it's not I'd like to know so I can seek some alternative filtering add-on

Thanks
Chaspear

**Comment by jvillalobos** [comment]
This repository is for the Firefox add-ons site. You can contact the developer of Junquilla for that question.
