### ISSUE TITLE
Text to Speech (TTS) preventing Copy and Paste on many sites

### ISSUE THREAD

**Issue by Modifyinc** [mozilla/addons#837]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Most sites I can select text and then right click the selected text, and are then giving the option to Copy, Paste, etc. Yet, since about Firefox 63 I believe, when the add-on Text to Speech (TTS) is enabled, most of the sites that I could right click on and select Copy & Paste are missing or replaced with the generic context menu consisting of Save Page As, Save Page to Pocket, Send Page to Device, Select All, Inspect Element, etc. It's as if I right clicked something other than the text. This only happens when I have Text to Speech (TTS) enabled. If I disable it, Copy & Paste are listed again in the context menu for those sites. I can even re-enable Text to Speech (TTS) while in the same session and the Copy & Paste are still available. But if I restart Firefox, the same issue persists, forcing me to disable the Text to Speech (TTS) again.

**Note**: Fortunately, even when the Copy & Paste are not listed when they should be, I can still use the Window's shortcut, Ctrl+C, but it's still very annoying not knowing which sites are affected.

### What happened?
Right clicking known text fields that usually give me the option to copy or paste are missing/replaced with the generic context menu consisting of Save Page As, Save Page to Pocket, Send Page to Device, Select All, Inspect Element, etc. It's as if I right clicked something other than the text. 

### What did you expect to happen?
Copy & Paste listed in the context menu for known text fields that allow this option and I have confirmed working when this add-on Text to Speech (TTS) is disabled.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
After highlighting a word or text on a site that fails to list the copy & paste options, I've noticed a pattern. When I right click the selection, the text is immediately deselected, as if I didn't select anything, which explains why I get the generic context menu. It thinks I didn't select any text. On the sites that work normally, the text remains selected when right clicking, thus showing the copy & paste options.

**Comment by jvillalobos** [comment]
Extensions are maintained by their developers. Please contact the developer of Text to Speech with this issue.
