### ISSUE TITLE
Dictionaries and Language Packs visualization problem

### ISSUE THREAD

**Issue by mtrevisan** [mozilla/addons#839]
### Describe the problem and steps to reproduce it:
If you visit the link https://addons.mozilla.org/en-US/firefox/language-tools/

### What happened?
you can see the line for Venda Tshivenḓa and Venetan Vèneto merged together

### What did you expect to happen?
see two separated lines, one for Venda Tshivenḓa and one for Venetan Vèneto, each one with its own link to the addon.

![addons problem](https://user-images.githubusercontent.com/851903/48920639-48e2d680-ee9a-11e8-89a3-9e79c66b01c2.jpg)

**Comment by willdurand** [comment]
> see two separated lines, one for Venda Tshivenḓa and one for Venetan Vèneto, each one with its own link to the addon.

We do not have the locale for `Venetan Vèneto`, so that's why it is merged with the locale `ve`, which is (for us) `Venda Tshivenḓa`.

**Comment by willdurand** [comment]
@mtrevisan thanks!

What would be the best name for US? `Venetian`?

**Comment by mtrevisan** [comment]
For me, Venetian is the "language of the province of Venice (variante veneziana della lingua veneta)", Venetan, on the other side, is "language of the Veneto region (lingua veneta)". The Veneto region has many variants of the main language spoken there, namely veneziano, trevigiano, padovano, vicentino, etc.

**Comment by willdurand** [comment]
I see. According to this https://en.wikipedia.org/wiki/Venetian_language, `Venetian` would be a good name in English but I can maybe use `Venetan` as you suggested? And I'll use `Vèneto` for the "native" name.

@mtrevisan does that work for you?

**Comment by willdurand** [comment]
<img width="1209" alt="screen shot 2018-11-22 at 21 45 15" src="https://user-images.githubusercontent.com/217628/48921411-eb518880-ee9f-11e8-96ef-1b3c6ff8a4e4.png">

**Comment by mtrevisan** [comment]
For me it is ok!
I don't know who decided to call it with that name...
Thank you again.

**Comment by willdurand** [comment]
@mtrevisan this change will be live next Thursday evening :)

**Comment by AlexandraMoga** [comment]
This is verified fixed in -prod:

![image](https://user-images.githubusercontent.com/31961530/49361149-f304fe80-f6e3-11e8-8ebe-8b1b464919f2.png)
