### ISSUE TITLE
Statistic for daily user doesn't match with the "by add-on version" numbers

### ISSUE THREAD

**Issue by Moustachauve** [mozilla/addons#840]
If I compare the normal [daily user statistics of my add-on](https://addons.mozilla.org/en-US/firefox/addon/cookie-editor/statistics/usage/?last=30), it shows that on november 21st I had 4,912 users. 

If I compare it with the information on the "[by add-on version](https://addons.mozilla.org/en-US/firefox/addon/cookie-editor/statistics/usage/versions/?last=30)" page, it shows that I have 5,086 users on version 1.7.0 on the same date and some other users on other versions. 

It doesn't make sense that I have more users with a specific version than the total amount of users using the add-on.

**Comment by jvillalobos** [comment]
The daily user number only counts enabled installs. The version breakdown includes enabled and disabled ones. If you look at the [enabled / disabled breakdown](https://addons.mozilla.org/firefox/addon/cookie-editor/statistics/usage/status/?last=30), you'll see why there's that discrepancy.

**Comment by Moustachauve** [comment]
Thanks, I understand now. I was confused because I thought that all those sub-menus were subset data of the top menu, but now I can see that all of them except the top menu includes disabled ones.
