### ISSUE TITLE
I created an account so I could leave review on an add-on, but there's no way to leave the review.  

### ISSUE THREAD

**Issue by markfleener** [mozilla/addons#845]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
https://addons.mozilla.org/en-US/firefox/addon/facebook-ad-blocker/reviews/
Can't leave a review even after creating an account.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
Can you leave a review on this page? https://addons.mozilla.org/addon/facebook-ad-blocker/

There's a "Rate Your Experience" box.

**Comment by markfleener** [comment]
yes thanks
