### ISSUE TITLE
Display addon license in search/browse results on addons.mozilla.org

### ISSUE THREAD

**Issue by grajkiran** [mozilla/addons#848]
Currently, the addon license is displayed only in the respective addon page.

Please consider displaying the addon license directly in the search results or when hovering over the addon name (in the details box that appears). This would be a great convenience to those of us wishing to install only FLOSS addons. 

An option to filter addons by license type would be awesome.

**Comment by diox** [comment]
Hi,

Such a feature is unlikely to be implemented in AMO - we don't even store that information in our search index at the moment. If you're looking for FLOSS only add-ons, the FSF maintains a [page listing FLOSS WebExtensions](https://directory.fsf.org/wiki/Collection:IceCat_WebExtensions_(proposed)).
