### ISSUE TITLE
External link verification

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons#850]
Currently a developer can set any website as their personal homepage, the add-on's website or the support page. There is no way for the user to actually know if those are indeed accurate apart from the contents of what the AMO listing claims and what the linked resource visibly says.

It would be nice - especially for support links if there was an optional machine based verification. Traditionally this is done by checking for `rel="me"` links back to the linking page (in this case AMO).

There are a couple of issues with that however, as @kewisch pointed out on IRC, especially that the content of websites may change and whenever you say "we think this is really their website" you have to ensure that is correct at all times. Of course it's not reasonable to think that AMO would crawl sites every couple minutes to check if they still have a rel="me" link pointing to AMO.

I think the terminology "verification" may be too strong, however more importantly, like with all things related to citing something you read elsewhere on the internet, it should include a timestamp, so "we think this is indeed a website related to this as of [date and time here]".

For example Mastodon does such link verification: https://github.com/tootsuite/mastodon/commit/f4d549d30081478b1fe2bde9d340262e132bb891
As far as I understand the actual crawl schedule is up to the owner of the instance.

I do think this would extend manual review of add-on and developer profiles well by adding additional information and potentially some trust for the end-user that the support link will actually lead them to a place that should help and not just a search engine to type their problem into. However the amount of trust that is conveyed to the user should be well balanced, since for example linking to a discourse thread as a support link probably wouldn't allow you to add this automated trust.

**Comment by tsl143** [comment]
What if the home page is a github repo URL?
For most of my extensions, I use github repo as homepage, where users can create issues or read info.

**Comment by eviljeff** [comment]
It's an interesting idea, but I comparing the burden on developers with the potential benefit to users it's not worth adding - as @tsl143 mentions it could be any webpage and requiring developers to add special markup is a pain.

**Comment by freaktechnik** [comment]
I think all additional "verification" should be come with some form of pain (also known as time/resource investment) from the developer side.
