### ISSUE TITLE
Addon download broken

### ISSUE THREAD

**Issue by emsisoftchristian** [mozilla/addons#855]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Installation of addon is impossible:
https://addons.mozilla.org/en-US/firefox/addon/emsisoft-browser-protection/

### What happened?

When trying to download the following addon, the site says: 
"Download failed. Please check your connection."
However, the addon showed no errors in addon verifier.

### What did you expect to happen?

Successful installation of addon.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
Have you tested the file? Trying to load it on `about:debugging` says the file is invalid, and there's a syntax error in the Browser Console about the French locale file in the extension.

**Comment by emsisoftchristian** [comment]
Thanks for hinting the french file! Turns out the translator changed the locale file from UTF8 to ANSI which triggered the error. 

Problem solved.
