### ISSUE TITLE
Setting description deleted privacy policy

### ISSUE THREAD

**Issue by danielnaber** [mozilla/addons#856]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

- I edit the English and German description of my add-on and save it (https://addons.mozilla.org/de/firefox/addon/languagetool/)
- The privacy policy, which I had added (and saved) before in English and German is suddenly gone. Actually, the "Authors and Licenses" had a German version, and that's completely gone.

### What happened?

Privacy policy gets removed despite being saved before.

### What did you expect to happen?

Editing add-on description shouldn't have any effect on the information on the "Authors and Licenses" page.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

https://addons.mozilla.org/firefox/addon/languagetool/

**Comment by diox** [comment]
Hi,

Thanks for reporting this. It has already been reported earlier in https://github.com/mozilla/addons-server/issues/10229 so I'm closing this as a duplicate.
