### ISSUE TITLE
The actual version of FF is not detected correctly

### ISSUE THREAD

**Issue by quoidautre** [mozilla/addons#857]
### Describe the problem and steps to reproduce it:
I want to add an add-on, but I could'nt 'cause the version of the browser is not correctly detected (see link of screenshot below)

### What happened?
I can't add the add-on

### What did you expect to happen?
Add the add-on

### Anything else we should know?
https://framapic.org/Dod6unWcYWCf/Z38OYEWYS1Zs.jpg

Thanks :)
Fabrice

**Comment by jvillalobos** [comment]
I just tested it on my browser and it works correctly. Did you change the settings to resist fingerprinting, or do you have an extension installed that does that or changes the user agent string?

**Comment by willdurand** [comment]
@quoidautre can you still reproduce this issue by chance? thanks!

**Comment by doublah** [comment]
reproducible with resistfingerprinting on nightly

**Comment by diox** [comment]
Note that this will always happen with `resistFingerPrinting`. It's kind of the point: if you enable this, websites, including AMO, won't be able to detect your browser version anymore. It's an expected trade-off when using that feature.

**Comment by diox** [comment]
Closing per lack of reply of the original poster.

**Comment by quoidautre** [comment]
Hi,
Sorry for my late response :(. 
But yes, the `resistFingerPrinting` was set to 'True'. If 'False', it's work.

Thanks :)

**Comment by franciszekzak** [comment]
@diox 	I came here to also report this bug - yes, this only happens with `resistFingerPrinting`, but I think it might be a good idea to add some way to override the user-agent based detection, and force installing (attempting to install) addons for the wrong version. I know bugs are generally expected with that flag on, but maybe this case is worth fixing? 

Not to get too philosophical, but if we want the feature to be effective, it needs to be used, and for it to be used it must be usable.

**Comment by diox** [comment]
There is a bug on Firefox about this https://bugzilla.mozilla.org/show_bug.cgi?id=1394448

**Comment by quoidautre** [comment]
Hi,
Ok. I'll check the `resistFingerPrinting`. 

Thanks a lot.
F.

**Comment by HattinGokbori87** [comment]
Firefox add-on site will report older version of browser even if you turn off Enhanced Tracking Protection. I really like the function of the "privacy.resistfingerprinting" key. It is now in Firefox for several years and a lot of people uses it. I couldn't  find a way to add addons.mozilla.org to any whitelist that'll prevent this behaviour. The add-on site is a core part of a modern browser. I hope this problem will "soon" be fixed.
Current Workaround:- Right click the "+ Add to Firefox" button and open in a new tab.
