### ISSUE TITLE
Can not save some site to PDF

### ISSUE THREAD

**Issue by geekbanana** [mozilla/addons#858]
My Environment: ubuntu 18.04 Firefox 64.0

This [site](https://yangbingdong.com/2017/use-vps-cross-wall-by-shadowsocks-under-ubuntu/?spm=a2c4e.11153940.blogcont633955.3.1dfd2678sb9moz) cannot be saved as PDF.  It's total blank!

**Comment by jvillalobos** [comment]
This repository is for the add-ons website. If you need help using Firefox, you can [go here](https://support.mozilla.org/). If one of your add-ons isn't working, please try contacting the developer of the add-on.
