### ISSUE TITLE
Allow users to 'fault' their own review by indicating it is a non-review

### ISSUE THREAD

**Issue by eyalroz** [mozilla/addons#859]
Every few weeks I get a "review" of my add-on (Remove Duplicate Messages (Alternate)), which is either:

> I tried searching for dupes and it didn't work

or

> The extension tells me it's not compatible with my version of Thunderbird

or something to that effect. I need to mark these as misplaced bug reports / support requests - which they are. This means useless work for me and for moderators who have to check my flags.

Now, the thing is, these people would not write this "review" if they realized it wasn't a review. I suggest that:

* The [UI for writing a review](http://i.imgur.com/kAjsW2i.png) will have a list box above the text box.
* The list box options will be "Bug report", "Support request" and "Review" (perhaps other options).
* That when the user clicks the submit button - if they wrote a non-review, something happens which is different from a "non-review" getting published. This could be:
    * A mail message is sent to the author
    * A message of some sort explaining to the user that bug reports are to be filed at website XYZ and not as reviews; or just telling them "please proceed to XYZ to file this"
    * An automated filing of a bug report with the specified text
    * An message/dialog regarding how to get support
    * A frequently-reported problems dialog/blurb being displayed
  ... or any combination of the above.

This doesn't tackle the challenge of low scores due to a bug that's not caused by the extension, but it would definitely help and make our lives better (!)

**Comment by eviljeff** [comment]
I'm pretty sure UX have gone over this before but @jvillalobos to add his input, etc.

**Comment by eyalroz** [comment]
I should say I'm not "married" to my specific UI suggestion; see edit.

**Comment by jvillalobos** [comment]
The review UX is very different now than compared to the screenshot you posted. While it doesn't provide a shortcut for requesting support, it was designed to give users a better idea of what they're doing. We did consider adding that option but ended up not adding it because the UI is fairly crowded right now. We might in the future, if the review problem persists.

I don't think we have an issue filed for it, so we can keep this open to track the problem.

**Comment by eyalroz** [comment]
@jvillalobos : Can you link to the new UI, or a mock/sketch of it? And - do you think it will address my specific concern, of people who are confused between reporting a bug and reviewing?

**Comment by jvillalobos** [comment]
I don't think we have any public mocks for it, especially not adapted to the inline reviewing UI we have now. It comes down to showing something like a Support button and telling users that's what they should use to report a problem. It's not going to work for everyone, as you can imagine, but it should help mitigate some of it.

**Comment by eyalroz** [comment]
Ok, then - is there a timeline of either those changes being implemented or a mock being available, so I could get an idea of what it's going to be like?

**Comment by eyalroz** [comment]
No action by devs recently - not sure why this was closed.

... oh, auto-closing? Hmm. Please reopen.

**Comment by diox** [comment]
See https://github.com/mozilla/addons/issues/1115#issuecomment-544877651

**Comment by eyalroz** [comment]
@diox : I didn't get any notification about the stale labeling, So I had no chance to comment. I had asked a question and didn't get an answer. Have a look at the earlier comments. As an add-on author (albeit for Thunderbird) I believe it is unfair of you guys to effectively, at the end of the day, ignore this (as opposed to deciding that it's not a good idea.)
