### ISSUE TITLE
error on most recent thmes page 2

### ISSUE THREAD

**Issue by thaliel** [mozilla/addons#861]
### Describe the problem and steps to reproduce it:
going to https://addons.mozilla.org/de/firefox/search/?page=2&sort=created&type=statictheme%2Cpersona

### What happened?
the page claims an "internale server error" has occured and does not show any results

### What did you expect to happen?
the same as on pages 1, 3 and forward, only page 2 is hiccupping

**Comment by diox** [comment]
There is something terribly wrong with one of the themes in there, even the detail endpoint fails for that add-on. Tracebacks:
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5075504/
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5075503/

**Comment by thaliel** [comment]
I cannot even see any themes lon the second page

**Comment by AlexandraMoga** [comment]
I've also reproduced the issue, with one note that the "corrputed" theme is now on page 5 (and will probably be on a different page when this issue is checked again):

![image](https://user-images.githubusercontent.com/31961530/50558572-28f3cd80-0cf8-11e9-996e-6169352b1b39.png)

**Comment by diox** [comment]
The add-on version has been disabled, the root cause will be handled in mozilla/addons-server#10284

**Comment by AlexandraMoga** [comment]
Confirming that the broken theme is no longer available and the above issues are gone.
