### ISSUE TITLE
i was find the addons named "Pan"

### ISSUE THREAD

**Issue by hxcc** [mozilla/addons#863]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by hxcc** [comment]
now, I can't use find it, https://addons.mozilla.org/zh-CN/firefox/addon/pan/?src=api

**Comment by willdurand** [comment]
Hi, I believe this add-on has been removed or hidden by their author. There is nothing we can do about it unfortunately.

**Comment by hxcc** [comment]
Didn't you delete it?

**Comment by willdurand** [comment]
> Didn't you delete it?

No, we don't do this.
