### ISSUE TITLE
Description not updating locally

### ISSUE THREAD

**Issue by RoiEXLab** [mozilla/addons#865]
I'm not quite sure if this issue belongs here, and if this isn't rather a problem with Firefox itself.
I recently updated the description of my extension on the site, and there it updated successfully.

However in my local extension description, the old description is still there, even after updating the extension, or re-installing it.

**Comment by jvillalobos** [comment]
Firefox first uses the description that's in the manifest file of the extension, and then it updates it with the content on the site, about once per day. If the description is never updating, then there's possibly a bug either in Firefox or AMO. Can you confirm that the description is never updating? Which add-on are you talking about?

**Comment by RoiEXLab** [comment]
https://addons.mozilla.org/de/android/addon/java-redirector/
This is my addon, on the website the updated description is displayed, but locally the outdated one is displayed.
IIRC this is the case on both, my Laptop and my desktop machine.

**Comment by muffinresearch** [comment]
Hi @RoiEXLab so we know can look into this further could you provide details of the text you're seeing that's out of date vs the text that is correct. If possible provide screenshots as that will help us to debug what's going on.

**Comment by RoiEXLab** [comment]
Ah, I already forgot about this.
Looks like the browser is just updating the description in too slow intervals. When I looked a week later it got updated properly.
Thanks anyways for your kind support 👍
