### ISSUE TITLE
Privacy Policy is removed every time I change description of add-on!

### ISSUE THREAD

**Issue by icl7126** [mozilla/addons#868]
### Describe the problem and steps to reproduce it:

1) Write some "Privacy Policy" text in the "Manage Authors & License" window.
1) In the window "Edit Product Page" click the first "Edit" button (next to "Describe Add-on" label)
1) Click "Save changes"
### What happened?
Privacy Policy is GONE!
### What did you expect to happen?
The Privacy Policy should not be cleared when editing add-on description.

**Comment by diox** [comment]
Hi,

Thanks for reporting this. It has already been reported earlier in mozilla/addons-server#10229 so I'm closing this as a duplicate. The fix will go into production next Thursday around 18:00 CET.
