### ISSUE TITLE
__MSG_description__ for Add-on on danish site.

### ISSUE THREAD

**Issue by sebftw** [mozilla/addons#869]
### Describe the problem and steps to reproduce it:
Visit:
https://addons.mozilla.org/da/firefox/addon/checker-plus-gmail/

### What happened?
The description for the add-on says:

> __MSG_description__

### What did you expect to happen?
It should say:

> Get desktop notifications, read, listen or delete emails without opening Gmail or Inbox by Gmail & easily manage multiple accounts.

### Anything else we should know?
I almost didn't install the add-on, because I couldn't believe it existed for Firefox when is called "Checker Plus for Gmail™". Turns out it was just the danish version of your site. Note that I did not intend to write the "MSG_description" in bold.

![billede](https://user-images.githubusercontent.com/5397919/50864661-09693e80-13a3-11e9-81d8-9c30208ec9d0.png)

**Comment by willdurand** [comment]
The API indeed returns `__MSG_description__` for the summary of this add-on in some locales as seen in the API response here: https://addons.mozilla.org/api/v4/addons/addon/checker-plus-gmail/.

I am not sure if this is a regression or if that has always been like that. I suppose we should fallback to `en` and I thought that was the case already 🤔

**Comment by willdurand** [comment]
`__MSG_description__` looks like a placeholder value for the `manifest.json` file: https://blog.chromium.org/2010/01/google-chrome-extension.html, so maybe this was the value found in the manifest that AMO added for all locales by default, and then some localized strings have been updated but not all of them. I don't know..

**Comment by EnTeQuAk** [comment]
The linked add-on doesn't have a translation defined for the `description` key for a few locales, among them `da` (as mentioned by @sebftw). AMO doesn't fall back to the default locale, I don't remember why but I'd guess Firefox doesn't either so we just follow that behaviour.

Looking through the docs though… https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Localized_string_selection seems like we should return an empty string instead :thinking:

**Comment by eviljeff** [comment]
I'm not sure if this is a bug in the code that does the webext translation extraction - I noticed it before when working on another issue.  Perhaps addons-server should not be creating the translation in that locale for that particular string if it doesn't exist rather than using the `__MSG_description__` placeholder 🤔

**Comment by EnTeQuAk** [comment]
> I'm not sure if this is a bug in the code that does the webext translation extraction

Yes, that's the part that doesn't fall back but simply returns the original string (`__Msg_description__`).

> Perhaps addons-server should not be creating the translation in that locale for that particular string if it doesn't exist rather than using the __MSG_description__ placeholder thinking

That's what I meant by linking to the docs, they clearly state that we (Firefox / AMO) return an empty string if a translation isn't found.

**Comment by icl7126** [comment]
I had a same issue - I'm not sure why it happened but somehow server created those translations.

**You can fix it on your Edit page:**
https://addons.mozilla.org/firefox/addon/checker-plus-gmail/edit
Click the "Localize for: ", select Danish and delete the bad description (it will then fill it with default langugae).
