### ISSUE TITLE
browserAction.openPopup() doesn't work when extension icon in menu

### ISSUE THREAD

**Issue by SailorMax** [mozilla/addons#870]
### Describe the problem and steps to reproduce it:
When resize Firefox window to smaller size, it start to hide icons from address bar to ">>"-menu.
If call `browserAction.openPopup()` when extension icon was moved to this ">>"-menu, nothing happens.
Steps:
1. install few addons with icons in address bar
2. install Translator extension: https://addons.mozilla.org/en-US/firefox/addon/translator_extension/
3. resize the firefox window to size, when Translator icon moved to ">>"-menu
4. open "firefox.com"
5. select any word ("Firefox" for example), right mouse click on selection and choose menu item "Translate It"

### What happened?
Nothing.

### What did you expect to happen?
Firefox shows popup of "Translator" with selected word.

### Anything else we should know?
When extension icon shows on address bar `browserAction.openPopup()` work as expected.

**Comment by kumar303** [comment]
Hi. Sorry you are running into trouble. For security reasons, add-ons do not work on mozilla.org (which is where firefox.com redirects). Try it on another domain. If you are still having a problem that you think is a bug, file it at https://bugzilla.mozilla.org/enter_bug.cgi?product=WebExtensions . The place you originally filed it (here) is a tracker for non-platform issues.

**Comment by SailorMax** [comment]
Ok.
https://bugzilla.mozilla.org/show_bug.cgi?id=1416414
https://bugzilla.mozilla.org/show_bug.cgi?id=1459046
