### ISSUE TITLE
Restore "Add to Firefox" buttons to the "See all versions" page

### ISSUE THREAD

**Issue by imcraymond** [mozilla/addons#871]
Problem: Working behind a firewall at work where the "Update" feature in Add-Ons does not work, probably because it can't access whatever servers are necessary.

To work around that I have been using the AMO page with "Recently Updated" and "Extensions" and browsing through the list manually to see which of the add-ons I use has been updated and updating them manually.  Recently when going to the particular Add-On page, the "Add to Firefox" button got replaced with a "Remove" button.  However, going the the "See all versions" page allowed me to upgrade to the latest version,

That is no longer possible, the "See all versions" page shows each and every version with a "Remove" button.

I can understand the main page for an add-on displaying a "Remove" button, but not the "See all versions" page.  To upgrade an add-on now, I have to remove that add-on, the reinstall it.

I am currently at Firefox 65.0b9 (64 bit) Windows 10.

**Comment by bobsilverberg** [comment]
@jvillalobos This somewhat relates to the discussion we had at https://github.com/mozilla/addons-frontend/issues/7332#issuecomment-452426176. Could you please comment on this issue about if and/or how we want to address this use case?

**Comment by imcraymond** [comment]
I've read through the linked issue.  A few thoughts went through my mind.  Most of which I discarded.

As this is a fringe case, keeping it simple would be best.  Perhaps some sort of "Install Latest Version" button, on the page or perhaps on the latest version would be the easiest to implement?

Would it be difficult to see if the latest version is installed, and only show the button if it isn't installed?

**Comment by jvillalobos** [comment]
Afterthought: there's also the case where someone wants to download an old version while having some other version installed. Fixing #834 won't address that, but it should still be possible to open the page on another profile or another browser to accomplish the same thing.

**Comment by kumar303** [comment]
Adding a link to the add-on source like in https://github.com/mozilla/addons-frontend/issues/3445 would probably address this.
