### ISSUE TITLE
Malicious add-on served here: http://www.atozmanuals.com/index.jhtml

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/addons#872]
### Describe the problem and steps to reproduce it:
http://www.atozmanuals.com/index.jhtml prompts you to install a malicious add-on that hijacks the home page.

### What did you expect to happen?
This add-on should not have been approved by Mozilla.

**Comment by willdurand** [comment]
Hi, I am sorry but I don't think we have approved anything if it is not listed on addons.mozilla.org.

**Comment by willdurand** [comment]
> Hi, I am sorry but I don't think we have approved anything if it is not listed on addons.mozilla.org.

I was actually wrong 😞 We might have approved it.

**Comment by wagnerand** [comment]
@jrmuizel Hi. Could you please file a blocklist bug according to https://wiki.mozilla.org/Blocklisting#How_to_request_a_block and add more details on how this add-on meets our blocklisting criteria (i.e. the reason it should be blocked)? Thank you!
