### ISSUE TITLE
Login to Mozilla Add Ons page fails

### ISSUE THREAD

**Issue by ClassicUA** [mozilla/addons#875]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
Login to Mozilla Add Ons page fails

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://discourse.mozilla.org/t/login-to-mozilla-add-ons-page-fails/35119

**Comment by wagnerand** [comment]
Did you recently change your email address in Firefox Accounts?

**Comment by ClassicUA** [comment]
The address was changed about six months ago.

**Comment by wagnerand** [comment]
Alright, could you please send us an email to amo-admins AT mozilla DOT org and tell us both your previous and your current email address? Closing here since we'll sort it out over email.
