### ISSUE TITLE
Add Addons search engine offer

### ISSUE THREAD

**Issue by maverick74** [mozilla/addons#876]
### Describe the problem and steps to reproduce it:
Open addons.mozilla.org (or any addon page).
Go to Page Actions button menu 

### What happened?
There is no offer to add addons.mozilla.org as a search engine option

### What did you expect to happen?
there should be an option to add addons.mozilla.org search engine to firefox

### Anything else we should know?
I used to go to the addon versions page that allowed me to add the search engine. But now, with the new site, i no longer have this option

**Comment by willdurand** [comment]
Hi, thanks for this issue. This is going to be implemented in https://github.com/mozilla/addons-frontend/issues/3836, which should be fixed in the coming weeks.

**Comment by maverick74** [comment]
That's great news!!!
 It's an important tool for me :) 
(it should be default in Firefox, if you ask me...)

Thank you!!!

**Comment by willdurand** [comment]
@maverick74 quick update, the patch for https://github.com/mozilla/addons-frontend/issues/3836 has been merged today, and it will be deployed next Thursday (not today).

**Comment by maverick74** [comment]
@willdurand GREAT!!! 
Thanks for letting me know :D
