### ISSUE TITLE
"Manage My Submissions" button not linking to new Mozilla Developers Hub

### ISSUE THREAD

**Issue by JamesRDouglas** [mozilla/addons#878]
I see that the Developers Hub has been updated quite recently, but a link to it is outdated on the main site (https://addons.mozilla.org/en-GB/)

If you click "Manage My Submissions" in the dropdown menu, it takes you to the address "https://addons.mozilla.org/en-GB/firefox/en-GB/developers/addons/", which is not found.

Steps to reproduce: 
  1) Login with Firefox account
  2) Click on username at top right of screen
  3) Click on "Manage My Submissions"

I expected to find a page showing my themes/add-ons to edit them like I normally do.

![screenshot 2019-01-17 at 19 44 13](https://user-images.githubusercontent.com/29376341/51344342-55497100-1a90-11e9-8135-02c474dcde54.png)

Also still links to the above address from the new page when you click "View All Submissions" (https://addons.mozilla.org/en-GB/developers/).

![screenshot 2019-01-17 at 19 48 58](https://user-images.githubusercontent.com/29376341/51344628-fc2e0d00-1a90-11e9-8a40-a92da077f5b8.png)

**Comment by EnTeQuAk** [comment]
We ran into some issues with the latest deployments which are now fixed though. Unfortunately you'll have to clear your browser's cache / force reload those pages.

Mind trying that?

**Comment by wagnerand** [comment]
> If you click "Manage My Submissions" in the dropdown menu, it takes you to the address "[addons.mozilla.org/en-GB/firefox/en-GB/developers/addons](https://addons.mozilla.org/en-GB/firefox/en-GB/developers/addons/)", which is not found.

That link was broken indeed, and it was fixed in the meantime. The correct link is:
https://addons.mozilla.org/en-GB/developers/addons
