### ISSUE TITLE
Tab switches site

### ISSUE THREAD

**Issue by Epicoss** [mozilla/addons#879]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I create a new tab and click on one of the pinned websites. If I switch to another tab quickly ( as I tend to do) then the tab switched to will go to that site I clicked on (I am 99% sure I am not dragging it) and the new tab will remain empty

### What happened?
Wrong tab switched website
### What did you expect to happen?
The other tab to switch to the website and the other one to stay at the current website
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
This repository is for the addons.mozilla.org website only. Please file bugs for Firefox at https://bugzilla.mozilla.org
