### ISSUE TITLE
Firefox developer hub 404's

### ISSUE THREAD

**Issue by kayakyakr** [mozilla/addons#880]
### Describe the problem and steps to reproduce it:

Trying to manage my extension, but Firefox developer hub seems to be missing. 

Direct via google, or via "tools" in the upper right, or via "more" in the main nav under "Add-ons" all take me to a 404 page.

### What happened?

![firefox-developer-missing](https://user-images.githubusercontent.com/328628/51396819-7a2bfb80-1b05-11e9-8355-c73948f79691.jpg)

### What did you expect to happen?

To be able to manage my extensions

### Anything else we should know?

Happens on a shared account, a personal account, and logged out

**Comment by wagnerand** [comment]
There was an intermediate error, which has been fixed in the meantime. Unfortunately, if you are affected, you need to clear your browser cache. See https://support.mozilla.org/en-US/kb/how-clear-firefox-cache for information on how to do that. Sorry for the inconvenience.

**Comment by kayakyakr** [comment]
Thanks, good to know and now google should know the answer to this question too :)
