### ISSUE TITLE
Remove option to be notified on Add-on SDK upgrades

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons#884]
### Describe the problem and steps to reproduce it:
There's still a toggle to enable/disable notification mails when the add-on SDK version of an extension is upgraded automatically by AMO (the last panel on https://addons.mozilla.org/en-US/firefox/users/edit):
![image](https://user-images.githubusercontent.com/640949/51760447-b85b8900-20ca-11e9-852a-736b50644feb.png)

However, to my understanding this should no longer happen, since no extensions using the SDK should be on AMO anymore.

**Comment by wagnerand** [comment]
This needs a separate addons-server issue to remove the backend part as well.

**Comment by championshuttler** [comment]
@wagnerand here it is for amo backend https://github.com/mozilla/addons-server/issues/10567
