### ISSUE TITLE
https ajax rest call fails from react frontend only in firefox

### ISSUE THREAD

**Issue by deepikathimmegowda** [mozilla/addons#889]
I have a react front end application. Making AJAX post call to rest api.
This rest API is a https service. And this server allows cross browser request.

I have added client.p12 to certificate list. When i directly hit the rest api url, there is an alert that is shown to select the client certificate.
Now from my client app when i click submit btn, an ajax post call is made to this https service. 

In other browser like chrome, a pop up appears to select client certificate.

But same app when i run in Firefox after adding same client.p12 for certificate list it gives ssl_bad_cert_error

**Comment by wagnerand** [comment]
What add-on or API is this about?

**Comment by wagnerand** [comment]
Closing as this seems unrelated to add-ons. You might want to try a general web development forum.
