### ISSUE TITLE
video downloadhelper 6.3.1

### ISSUE THREAD

**Issue by Navy-Brat** [mozilla/addons#892]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Navy-Brat** [comment]
I have an Apple MacBook Pro with OS X 10.6 and FireFox 45.9.0 ESR and I am looking for MIG's Video DownloadHelper 6.3.1. It's no longer there at https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/versions/6.3.1 Do you have a copy of it? Thanks

**Comment by wagnerand** [comment]
Please contact the author of the add-on for inquiries about the availability of specific versions.
