### ISSUE TITLE
Popup menu Bug

### ISSUE THREAD

**Issue by Achille-Grs** [mozilla/addons#893]
Hi!  Just a small bug when I put the add-on Ghostery inside popup menu in Firefox 65!
Outside the popup menu like an extra button it's ok.
But... as you see the error pic inside popup menu, the bug is cutting the add-on popup box
(sorry for my poor english)
I hope the pics help the problem.
![9](https://user-images.githubusercontent.com/32937226/52299467-1d966080-298e-11e9-9a7e-0becc1ba4390.png)

**Comment by jvillalobos** [comment]
Please contact the Ghostery developers for help. This repository is for the add-ons website.
