### ISSUE TITLE
Unable to submit version

### ISSUE THREAD

**Issue by coinplus-sa** [mozilla/addons#894]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Uploaded .zip, ok,
enter all the required info

### What happened?
Step: Submit a New Add-on / Describe Add-on
refresh of the page web clicking on "Submit Version", without info (red label) on what went wrong.

### What did you expect to happen?
follow up next step

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/en-US/developers/addon/metamask-coinplus-version/submit/details

**Comment by jvillalobos** [comment]
Did you select categories and license? This fields are required and show a red text message if you submit without completing them.

**Comment by coinplus-sa** [comment]
Yes, no red message, but same behaviour. Its only i do not know what is the problem.
![screenshot_2019-02-08 describe add-on metamask coinplus version add-ons for firefox](https://user-images.githubusercontent.com/39584818/52468775-fe642280-2b89-11e9-9a91-246b91c0a453.png)

**Comment by jvillalobos** [comment]
@eviljeff maybe a localization error? The name isn't localized, but the description is.

**Comment by coinplus-sa** [comment]
What do you mean by localization error?
you mean region/country specific?

**Comment by eviljeff** [comment]
yeah, a localisation problem is the most likely.  First thing I'd look at is if the default_locale in the manifest is not `en-US` (the submitting locale in the url).  Can you attach the xpi file to this issue so we can reproduce?

**Comment by coinplus-sa** [comment]
the default_locale is "en"
[metamask-firefox-5.3.1.zip](https://github.com/mozilla/addons/files/2845824/metamask-firefox-5.3.1.zip)

could be good to have some kind of warning for the locale.

**Comment by AlexandraMoga** [comment]
I've downloaded the the addon posted above and, without making any modifications to the `.zip` , I've uploaded it on https://addons.allizom.org/en-US/developers/addon/submit/distribution.
The submission went trough successfully for me.

**Comment by eviljeff** [comment]
I can't even replicate this on addons.mozilla.org (I renamed the id from the zip and submitted it myself).  @coinplus-sa Can you try again?

**Comment by coinplus-sa** [comment]
I did that too, rename the ID, create a new account. Same problem, no error, just refreshing the page. May be I'm missing something for my account?

**Comment by diox** [comment]
@coinplus-sa do you have any errors in the devtools console when you submit ?

**Comment by muffinresearch** [comment]
@coinplus-sa hi - were you able to find any errors following https://github.com/mozilla/addons/issues/894#issuecomment-467378608 ?

**Comment by muffinresearch** [comment]
Closing this on the basis that we don't have further information to go on. @coinplus-sa if you have further information please feel free to re-open this issue and we'll investigate further.

**Comment by coinplus-sa** [comment]
Sorry, I was on another project.
I managed to submit the extension today after reboot. I did the same procedure. I do not know what changed.
I guess I had some cache problem.
Thanks
