### ISSUE TITLE
mobile website taking over my pc - youtube automatically takes the mobile website version on PC

### ISSUE THREAD

**Issue by ejbytes** [mozilla/addons#898]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
For support, please visit support.mozilla.org

**Comment by ejbytes** [comment]
1 Start PC. Personal computer, not mobile device!
2 Open Firefox.
3 Go to Youtube.
4 Firefox, always chooses mobile version of youtube. 
 4a - Youtube missing controls (e.g. no gearbox settings as in "view mode", nor settings as in Quality or pixel quality (e.g. HD, 720p, 1080p, 480p...))

Resut:
My Firefox was fine up until a couple months ago, but the new updates really made my Firfox usage frustrating and awful. Why is firefox bending over so far for mobile devices and making everything seem to be an iPad or Smart Phone of some sort? Professionals will and always will choose PC over those "devices".
