### ISSUE TITLE
We allow access to an add-on you can't install

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#90]
![screenshot 2016-04-14 09 42 06](https://cloud.githubusercontent.com/assets/74699/14536002/3ec04976-0225-11e6-9b5c-b8ed56dc5753.png)

In this scenario the add-on hasn't been reviewed. It's the first version of the add-on. It hasn't been signed.

The little dialog says that you can't use it in a release version past 43 because of signing. And you can't install unless signing is turned off. A permission we don't have access to on AMO (yet?).

... but it still seems a bit odd. I know @bwinton was talking about this the other day. 

Not sure what we should be doing here. Perhaps its nothing and we should move on.

**Comment by bwinton** [comment]
Maybe don't show the page until the add-on is reviewed?  Or just disable the button?  If the author wants people to try installing an unsigned add-on, they can always distribute the unsigned add-on they submitted…  :wink:

**Comment by tofumatt** [comment]
It's partially messaging here confuses things; it reads like it's "incompatible" with Firefox > 43. But really they just require signing. This page shouldn't appear in search results as it's not reviewed, so only people explicitly entering the URL (clicking on a direct link) should see it.

Changing the messaging to "This add-on is new and has not yet been signed by Mozilla. It can't be installed yet." would be clearer. And yeah, disable the button.

**Comment by designakt** [comment]
I agree with @tofumatt, this should not show up in search, the copy should be clearer we don't need the blue button. (At least not in release versions.)
@devaneymoz can you please help with copy. What do you think about this proposal:
>  "This add-on is new and has not yet been signed by Mozilla. It can't be installed yet."

**Comment by jvillalobos** [comment]
https://github.com/mozilla/addons-server/issues/3348 was filed to not show pages for add-ons pending review. They don't show up in search, though, they should only be accessible if you have the full URL.

**Comment by jvillalobos** [comment]
Another suggestion: aligning it with the language used in Firefox.
![install](https://cloud.githubusercontent.com/assets/62568/20408251/430c20da-acda-11e6-98ea-b8385d373fbc.png)

**Comment by devaneymoz** [comment]
After a side chat with @jvillalobos this may be the clearest messaging, if it's still needed:

"This add-on has not been verified by Mozilla. Installation is restricted to Firefox Developer Edition and Firefox Nightly."

**Comment by andymckay** [comment]
"...only if you have turned off signing in Firefox Developer Edition and Firefox Nightly".

**Comment by diox** [comment]
We no longer have unsigned add-ons on the site.
