### ISSUE TITLE
Unable to Update my Themes to Firefox  through color.firefox.com via developer hub.

### ISSUE THREAD

**Issue by Fuzzqt** [mozilla/addons#901]
PK^C^D                                                                                                                      ^@^@^@^@v�IN�זe^L^B^@^@^L^B^@^@^M^@^@^@manifest.json{                                                                                
       "manifest_version": 2,                                                                                                       
       "version": "1.0",                                                                                                                
       "name": "AWS",                                                                                                                  
       "theme": {                                                                                                                       
          "images": {},                                                                                                                   
          "properties": {},                                                                                                                
          "colors": {                                                                                                                       
             "toolbar": "rgb(7, 7, 7)",                                                                                                                  
             "toolbar_text": "rgb(6, 247, 58)",                                                                                                   
             "accentcolor": "rgb(0, 0, 0)",                                                                                                   
             "textcolor": "rgb(0, 255, 48)",                                                                                                     
             "toolbar_field": "rgb(0, 0, 0)",                                                                                                     
             "toolbar_field_text": "rgb(252, 175, 24)",                                                                                         
             "tab_line": "rgb(0, 0, 0)",                                                                                                      
             "popup": "rgb(7, 11, 46)",                                                                                                         
             "popup_text": "rgb(247, 115, 3)",                                                                                                  
             "tab_loading": "rgb(0, 0, 0)"                                                                                                  
          }                                                                                                                             
   }                                                                                                                              
}PK^A^B^T^@                                                                                                            ^@^@^@^@^@v�IN�זe^L^B^@^@^L^B^@^@^M^@^@^@^@^@^@^@^@^@^@^@^@^  @^@^@^@manifest.jsonPK^E^F^@^@^@^@^A^@^A^@;^@^@^@7^B^@^@^@^@

Thing is I even went through your wiki and followed the instructions to change it to 2.1 and all that jazz, still can't even update my own theme that's passed your vetting process. Not sure what's up or i'm just clueless, probably the latter seeing as 92% of errors are human. Just figured you guys could streamline this process a bit better.

Just trying to update my theme posted on your listings.

Listed

https://addons.mozilla.org/en-US/firefox/addon/aws/?src=search

Idk, I've tried numerous times throughout the past few days editing and modifying the json file to fit your specific requests that somehow isn't streamlined.
[AWS.zip](https://github.com/mozilla/addons/files/2848104/AWS.zip)

**Comment by AlexandraMoga** [comment]
@Fuzzqt did you by any chance run into the following error?

![image](https://user-images.githubusercontent.com/31961530/52551211-1f27b480-2de4-11e9-863b-c8994a4ab42a.png)

If this is the case, you will have to modify the `"version"` filed in your manifest.json to `1.1` Please do not change the `"manifest_version"` field. 

If you run into a different kind of error, then please include some more specific steps and possibly a screenshot of the error you're getting.

**Comment by Fuzzqt** [comment]
Yeah, I tried that. It just keeps giving me these errors.

[https://i.imgur.com/n0QRjAF.png](url)

**Comment by Fuzzqt** [comment]
I just figured it out, I was trying to use a linux terminal to edit it when I just needed to edit it in notepad instead. I must of been breaking the ZIP format when I was doing that. Anyways, my apologies. the 1.1 does indeed work if I go straight to the json and edit that line through notepad. Closing this ticket, thank you.
