### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by dmoneyballer** [mozilla/addons#902]
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
This error occurred when initially submitting my add-on.
* Whether your add-on is listed or unlisted.
I would say unlisted because it threw the error but I'm not 100% sure what the above question is asking.
* The URL where you submitted the add-on.
https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed 
* The approximate time you submitted the add-on, with timezone.
4:23 PM Mountain Standard Time US

**Comment by dmoneyballer** [comment]
here's a copy of what I submitted: [wikipedia-ext-firefox.zip](https://github.com/mozilla/addons/files/2848370/wikipedia-ext-firefox.zip)

**Comment by AlexandraMoga** [comment]
@dmoneyballer  I think you have run in the same issue described in https://github.com/mozilla/addons/issues/896 .
You can try using the packaging instructions mentioned in the linked issue.
There is also an ongoing work to make these kind of validation errors more evident - see https://github.com/mozilla/addons-server/issues/10635
