### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by siefkenj** [mozilla/addons#907]
[mailmergep@example.net-1.0.0.zip](https://github.com/mozilla/addons/files/2858664/mailmergep%40example.net-1.0.0.zip)

This is a new addon submitted Feb 13, 2019 at 3:15GMT
The validation report is at https://addons.thunderbird.net/en-US/developers/upload/a31623cb41114d688641345fdb359631

I believe the error occurred because of too many warnings produced by the automated review. The addon has a component compiled with wepback and react. The full source can be found at
https://github.com/siefkenj/MailMerge

**Comment by wagnerand** [comment]
Please report issues for thunderbird at https://github.com/thundernest/addons-server/
