### ISSUE TITLE
Add-on approved but not signed

### ISSUE THREAD

**Issue by derenrich** [mozilla/addons#909]
### Describe the problem and steps to reproduce it:
I wrote a new add-on (https://addons.mozilla.org/en-US/firefox/addon/ao3-history/) and uploaded it to AMO. The add-on isn't user installable.

### What happened?
Installation fails across multiple different computers on different internet connections. The error is "Download failed. Please check your connection.". If you force the download via save-as and then try to install the xpi then you get a different error: "The add-on could not be installed because it isn't verified."

### What did you expect to happen?
The add-on should just install. If you inspect the XPI by unzipping it you will notice it isn't signed.

### Anything else we should know?
https://addons.mozilla.org/en-US/firefox/addon/ao3-history/

**Comment by wagnerand** [comment]
This add-on was auto-approved but not signed. @diox or @eviljeff Would one of you have time to look into what happened here?

**Comment by derenrich** [comment]
(I also opened a bugzilla ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1527496 for this)

**Comment by diox** [comment]
A couple things we noticed:
- The manifest uses `browser_specific_settings`
- We were able to reproduce on dev & stage. At submission time, it looks like no category is offered. Still, the add-on does end up in awaiting review state, and then in approved state after `auto_approve` processes it. Both the fact that categories were missing and that it didn't prevent the add-on from reaching awaiting review status are weird.

**Comment by derenrich** [comment]
is there anything i could change about the add-on to avoid this? it's not clear to me what I'm doing that's "weird".

**Comment by wagnerand** [comment]
@derenrich this is still under investigation. We'll update the issue as we find out more.

**Comment by EnTeQuAk** [comment]
So, we found the problem on our end and it's a mixture of various smaller bugs and behaviours that lead to this.

@diox mentioned most of that in https://github.com/mozilla/addons-server/issues/10693 

Generally, there is a workaround for this in the short-term: Either replace the key `browser_specific_settings` with `applications` or, if that's something you'd be able/willing to do, bump the `strict_min_version` to `48.0`. Both will result in a correctly signed version.

**Comment by derenrich** [comment]
brilliant! i just bumped the version and now it works

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/10693 and https://github.com/mozilla/addons-server/issues/10697 should prevent this from happening in the future.
