### ISSUE TITLE
Recognize Firefox Nightly and Dev Edition as Firefox for the Download button

### ISSUE THREAD

**Issue by MoOx** [mozilla/addons#91]
When navigating on addons.mozilla.org, I am always annoyed by seeing this

![screen shot 2016-04-15 at 08 06 17](https://cloud.githubusercontent.com/assets/157534/14552706/f5fccfd6-02e0-11e6-9f79-e3caa4e7e251.png)

Ok, there is a "Download anyway" but I think it should not be that hard to recognized nightly and dev edition as Firefox.

I always click on the big green button (because I don't install addons everyday) and do not understand what's next (Download firefox page).

**Comment by andymckay** [comment]
I can't reproduce this, it works fine for me in Nightly, Dev Edition and Beta. Do you know what user agent you are sending?

**Comment by MoOx** [comment]
```
> navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 /"
```

For example, I am getting the issue here https://addons.mozilla.org/en-US/firefox/addon/simplewhitex/

![screen shot 2016-04-18 at 11 28 06](https://cloud.githubusercontent.com/assets/157534/14599621/ac248e88-0558-11e6-9161-51b1d56b0fed.png)

**Comment by MoOx** [comment]
The addons I am using

![screen shot 2016-04-18 at 11 29 18](https://cloud.githubusercontent.com/assets/157534/14599652/dffef13a-0558-11e6-96dc-1da496e916f3.png)

**Comment by andymckay** [comment]
Your user agent doesn't identify itself as Firefox. For example:

```
navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:47.0) Gecko/20100101 Firefox/47.0"
``` 

I'm not sure if this is one of your add-ons or something else in the way, but I don't think this is an AMO bug.
