### ISSUE TITLE
report bug

### ISSUE THREAD

**Issue by Reysefyn** [mozilla/addons#910]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Reysefyn** [comment]
Problem loading , crashing, slowness, error messages, freezing , unresponsive, changing passwords in apps on its own.ect

**Comment by Reysefyn** [comment]
Problems loading,  it crashes, its very slow, message error's, unresponsive, it was changing my passwords, freezing,  etc

**Comment by jvillalobos** [comment]
If you're experiencing issues with Firefox, please visit https://support.mozilla.org/. If this is a problem with a particular add-on, try contacting the developer about it.
