### ISSUE TITLE
Can't Login to Developer Hub

### ISSUE THREAD

**Issue by gsomoza** [mozilla/addons#925]
As someone who already has a plugin published and was already able to login to the Developer Hub not long ago
When visiting https://addons.mozilla.org/en-US/developers/ and attempting to login
And after I'm redirected back to the Developer Hub
Then it appears as if I'm not logged in
And there are no cookies for .addons.mozilla.org except for the "messages" cookie.

Trying again leads to the exact same result.

I'm able to login to the account successfully with Firefox itself.

**Comment by wagnerand** [comment]
AMO is currently in read-only mode due to a planned server migration.
