### ISSUE TITLE
Showing Release Notes in Firefox is broken (404)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons#931]
### Describe the problem and steps to reproduce it:

See https://bugzilla.mozilla.org/show_bug.cgi?id=1531649 for the steps to reproduce

### What happened?

Instead of seeing release notes, you see an error

### What did you expect to happen?

Firefox should show release notes.

### Anything else we should know?

Firefox is requesting a URL like this, which is a 404 because of https://github.com/mozilla/addons-server/issues/10428

https://addons.mozilla.org/en-US/firefox/versions/updateInfo/3146161/en-US/

This used to be handled by `addons-server` in https://github.com/mozilla/addons-server/blob/549e5257a419358883c0b1eecbcaefdad5155634/src/olympia/urls.py#L126-L127

As a quick fix, we probably need an nginx rule to serve the legacy site for the URL, similar to https://github.com/mozilla/addons/issues/930

**Comment by eviljeff** [comment]
Short term, an nginx rule sounds good.  Long term I don't see why Firefox can't just get the release notes directly from AMO's API and wrap it in html itself.  

Medium term though... should this be in addons-frontend (as a user facing page) or remain in addons-server (as it's only used internally by Firefox and contains no other UI)?

**Comment by kumar303** [comment]
@bqbn this is the type of URL we want to temporarily serve from `addons-server` as a quick fix: 
https://addons.mozilla.org/en-US/firefox/versions/updateInfo/3146161/en-US/

Here is the old regex we were using: https://github.com/mozilla/addons-server/blob/549e5257a419358883c0b1eecbcaefdad5155634/src/olympia/urls.py#L126-L127 (take note of how it allows extra URL parts on the end)

**Comment by diox** [comment]
This was supposed to be covered by https://github.com/mozilla/addons-server/issues/10428#issuecomment-457209484 and https://github.com/mozilla/addons-server/issues/10428#issuecomment-460566418 already, so I suspect we already have the rule but it's missing something.

**Comment by bqbn** [comment]
I think it is the `<app>/` part that is missing in the Nginx regex matching rule. We've added that and deployed the change to -dev and -stage environment.

Please test it.

**Comment by willdurand** [comment]
I tried the following URLs in -dev:

- https://addons-dev.allizom.org/en-US/firefox/versions/updateInfo/1536609/en-US/
- https://addons-dev.allizom.org/en-US/firefox/versions/updateInfo/1536609/

Both redirect to https://addons-dev.allizom.org/en-US/firefox/addon/lastpass-password-manager/versions/4.18.1.2/updateinfo/, which means the issue seems fixed in -dev.

**Comment by willdurand** [comment]
Upgraded to `p1` as it is a link in FF. A fix has been deployed in all envs and the issue has been fixed.

**Comment by AlexandraMoga** [comment]
Confirmed for prod too:

https://addons.mozilla.org/en-US/firefox/versions/updateInfo/3166483/
