### ISSUE TITLE
what happened to the rss feed?

### ISSUE THREAD

**Issue by atomGit** [mozilla/addons#935]
what happened to the rss feed for amo?

**Comment by willdurand** [comment]
Hi, RSS have been sunsetted unfortunately. See: https://github.com/mozilla/addons-server/issues/7182.

**Comment by caitmuenster** [comment]
Hey @atomGit, you can use the API to obtain this information: https://addons-server.readthedocs.io/en/latest/topics/api/addons.html

[This extension](https://addons.mozilla.org/en-US/firefox/addon/latest-on-amo/) exemplifies how to use the API to display the latest extensions and can also be used to see a list of newly published extensions on AMO.
