### ISSUE TITLE
Self hosted signed AMO addon will not install.  Says addon is corrupt 

### ISSUE THREAD

**Issue by daveyknits** [mozilla/addons#940]
### Describe the problem and steps to reproduce it:
I updated our addon which looks up a page_id value and returns it for editing in our in-house CMS. 
It has been working locally while developing it. 

Signed it through AMO without any issues (some jQuery warnings came up regarding inner-html calls) and the addon passed the AMO signing.  

### What happened?
The xpi generated as it should, but when attempting to install the Firefox reports the addon is corrupt. 

![screen shot 2019-03-05 at 9 13 28 am](https://user-images.githubusercontent.com/6126498/53811335-28112f00-3f27-11e9-8746-471d03c2461c.png)

### What did you expect to happen?
For the addon to install normally. 

### Anything else we should know?
Developer Hub addon link - https://addons.mozilla.org/en-US/developers/addon/1a0381537eb04db8aeef/edit

**Comment by wagnerand** [comment]
In your `manifest.json`

```
    "applications": {
        "gizmo": {
            "update_url": "..."
        }
    },
```

is invalid. Specifically, `gizmo` can't be a property of `applications`. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings (`browser_specific_settings` is an alias for `applications`).
