### ISSUE TITLE
Development images on docker hub are outdated

### ISSUE THREAD

**Issue by diox** [mozilla/addons#941]
At the moment, we have 2 separate sets of docker images for AMO:
- [https://hub.docker.com/r/addons/addons-server](https://hub.docker.com/r/addons/addons-server) + [https://hub.docker.com/r/addons/addons-frontend](https://hub.docker.com/r/addons/addons-frontend)
- [https://hub.docker.com/r/mozilla/addons-server](https://hub.docker.com/r/mozilla/addons-server) + [https://hub.docker.com/r/mozilla/addons-frontend](https://hub.docker.com/r/mozilla/addons-frontend)

The former is used for development, the latter for dev/stage/prod. The reasons are mostly historical, the development image existed long before we started using docker for deployments, and merging those together is a (non-trivial - the configuration differs enough to be annoying) goal for the future, but at the moment that's where we are.

The development images are supposed to be built automatically by docker hub by pulling our repos. Unfortunately this has been broken since Feb 12, we suspect because Docker Hub rolled out a new version of their site and changed the way it pulled from the repos, now using a different app over on Github.

We need to figure out a way to get the builds updated again on Docker Hub.

**Comment by diox** [comment]
Trying to fix Docker Hub has been frustrating as it seems that we need to[ give our automation user the permission to read private repos on the organization](https://bugzilla.mozilla.org/show_bug.cgi?id=1530779) to unblock the repos in the docker hub settings, even though the repos are public (This is probably a limitation of Docker Hub and/or Github). This was initially blocked by security and re-requesting the authorization doesn't seem to be possible, so we're currently stuck at this point.

An alternate solution would be to build and push the images ourselves using CircleCI or other. This is what is currently being done for the "production" images we deploy to dev/stage/prod. This might be a little confusing to set up since the Docker Hub repos are different.

**Comment by diox** [comment]
Side note: this might block some people from setting their envs, especially now that addons-server depends on addons-frontend as [we are removing the legacy frontend](https://github.com/mozilla/addons-server/issues/10428) and [changing the local routing to match that](https://github.com/mozilla/addons-server/issues/9080). We intend to manually push new images to unblock them, but in the meantime, anyone affected can build the images locally. For instance for addons-frontend (which matters the most as its not possible to update a running container like it is with addons-server):
```bash
cd addons-frontend
docker build . -t addons/addons-frontend:latest
```

Then to use it with addons-server:
```bash
cd addons-server
docker-compose stop addons-frontend
docker-compose up -d addons-frontend
```

**Comment by EnTeQuAk** [comment]
I'm pushing some updated builds for addons-server and addons-frontend in the meantime.

**Comment by EnTeQuAk** [comment]
addons-server:latest, addons-server:latest-py3 and addons-frontend:latest are up-to-date for now (but won't be autobuild, this is a manual build).

**Comment by diox** [comment]
Will be fixed in https://github.com/mozilla/addons-server/issues/12490
