### ISSUE TITLE
Can't change addon icon

### ISSUE THREAD

**Issue by wooque** [mozilla/addons#942]
### Describe the problem and steps to reproduce it:
Went to https://addons.mozilla.org/en-US/developers/addon/site-bleacher/edit
Clicked `Edit` in `Images` section
Clicked `Upload custom icon...`
Selected this icon (128x128 png) ![icon128](https://user-images.githubusercontent.com/1936195/53895583-a7d7f000-4032-11e9-9167-d92da23d7bc0.png)
All 3 previews are generated on the side
Click `Save Changes`
Old icons are shown and `Image changes being processed` is shown indefinitely (several weeks, probably a week since last time I tried)

### What happened?
Addon icon was not changed

### What did you expect to happen?
Addon icon to be changed

### Anything else we should know?
In network inspector I see 404 for 128x128 icon
https://addons.cdn.mozilla.net/user-media/addon_icons/1018/1018322-128.png?modified=63c31c60
64x64 and 32x32 return old icon
https://addons.cdn.mozilla.net/user-media/addon_icons/1018/1018322-64.png?modified=63c31c60
https://addons.cdn.mozilla.net/user-media/addon_icons/1018/1018322-32.png?modified=63c31c60

**Comment by eviljeff** [comment]
The error was 
> Error saving addon icon (/mnt/efs/addons.mozilla.org/shared_storage/uploads/addon_icons/1018/1018322-32.png): 'PngStream' object has no attribute 'chunk_eXIf'
 
From a quick search we might be hitting a bug with the image resizing lib used for resizing (Pillow) - https://github.com/python-pillow/Pillow/issues/3557 mentions it - which will be fixed in their next release in April.

**Comment by wooque** [comment]
Thanks, I uploaded png with exif stripped and it worked

**Comment by hugovk** [comment]
https://github.com/python-pillow/Pillow/issues/3557 has just been released in Pillow 6.0.0.

**Comment by eviljeff** [comment]
updated with https://github.com/mozilla/addons-server/pull/11098
