### ISSUE TITLE
"Find more search engines" link leads to BAD INFORMATION.  IT'S A BUG !

### ISSUE THREAD

**Issue by bobwho** [mozilla/addons#943]
### Describe the problem and steps to reproduce it: 

The "Find more search engines link" in the SEARCH OPTIONS leads to consistently erroneous, irrelevant, unhelpful, and STUPID OUTPUT for many YEARS!

### Anything else we should know? THE SCREENSHOT:
(Please include a link to the page, screenshots and any relevant files.)
![image](https://user-images.githubusercontent.com/43323767/53927968-5c770f00-403d-11e9-92bd-c440d1783a9e.png)

![screenshot_2019-03-07 search tools add-ons for firefox en-us](https://user-images.githubusercontent.com/43323767/53928030-84667280-403d-11e9-9761-a6d55ae4d078.png)

**Comment by bobwho** [comment]
### **Correction:  Relevant to whom?**

**Comment by jvillalobos** [comment]
Refiled as https://github.com/mozilla/addons-frontend/issues/7682

In the future, please keep the tone and formatting civil, thank you.
