### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by phts** [mozilla/addons#944]
* Addon sources

https://github.com/phts/firefox-web-skype

* There is no any errors locally:

```
$ addons-linter dist/web-skype-com-support-for-firefox-0.1.0.xpi
Validation Summary:
errors          0
notices         0
warnings        0
--
```

* Error after upload:

```
Sorry, we couldn't load your WebExtension.

Error: Validation was unable to complete successfully due to an unexpected error.
```

* Links to report

For example:
https://addons.mozilla.org/en-US/developers/upload/20bbc68ca7fe465cbcb2406b1a617d5c
https://addons.mozilla.org/en-US/developers/upload/84f64885836749ecb965073000bdb13e

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

New addon

* Whether your add-on is listed or unlisted.

Listed

* The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed

* The approximate time you submitted the add-on, with timezone.

21:27 CET

**Comment by wagnerand** [comment]
Can you please attach the exact file you were trying to upload to this issue? Thanks!

**Comment by phts** [comment]
@wagnerand Please find zip attached.

Actually uploaded `.xpi` file but needed to rename it to `.zip` to be able to upload this file here.

[firefox-web-skype@phts-0.1.0.zip](https://github.com/mozilla/addons/files/2953364/firefox-web-skype%40phts-0.1.0.zip)

**Comment by wagnerand** [comment]
Hm, 3 out of 5 unzip programs say this archive is corrupt. My guess is that you're using some way of zipping that AMO doesn't understand either. Can you try using a standard zip program?

**Comment by phts** [comment]
@wagnerand Yes, you are right. I tried to zip another tool ad it's working.

Thank you very much!
