### ISSUE TITLE
Impossible to add new Authors 

### ISSUE THREAD

**Issue by luciancor** [mozilla/addons#946]
### Describe the problem and steps to reproduce it:
go to "Manage Authors & License"

### What happened?
No way to add new Authors

### What did you expect to happen?
Have a way to add new Authors :) 

### Anything else we should know?

![Screen Shot 2019-03-11 at 14 55 27](https://user-images.githubusercontent.com/5583036/54129226-14c20000-440e-11e9-88be-b76ea8a0deb2.png)

**Comment by diox** [comment]
Bisected it down to https://github.com/mozilla/addons-server/commit/74794d9db5203ed05e8997645ba0edf1c302bc6d (https://github.com/mozilla/addons-server/issues/10830)

**Comment by diox** [comment]
The problem in that commit is the removal of this method:
```python
    def widget_attrs(self, widget):
        lazy_reverse = lazy(reverse, str)
        return {'class': 'email-autocomplete',
                'data-src': lazy_reverse('users.ajax')}
```

That somehow causes the form to not show the extra blank field used to add new developers. Note that this method depends on `users.ajax` view that was removed as well as part of https://github.com/mozilla/addons-server/issues/10827. As mentioned in that issue we probably don't want autocomplete here (We'll have to reveal whether or not the user exists when the form is submitted anyway though...) so we'll have to tweak the code a bit...

**Comment by eviljeff** [comment]
Ah.  The javascript that handles the new blank fields (among other things to do with that form) relies on the element having the class `.email-autocomplete` so it all breaks without it.  The fix may just be adding back in the class (and leaving out the `data-src`).

**Comment by diox** [comment]
Ah, that's it. I tested locally and it seemed to be working with an empty `data-src` and I was wondering if I had missed something... I guess we should just add and rename that class then, yeah.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage with FF65, Win10x64

![image](https://user-images.githubusercontent.com/31961530/54274605-2849a400-4591-11e9-9db6-e88f2a04990b.png)
