### ISSUE TITLE
List all available categories for browsing on the front page [Design]

### ISSUE THREAD

**Issue by jcklpe** [mozilla/addons#953]
This is a design crit that I wanted to post in order to help improve the addons website UX. I originally posted a single large bug on Bugzilla and was told to post here and to separate my concerns by individual tickets. [[Original bugzilla ticket here]](https://bugzilla.mozilla.org/show_bug.cgi?id=1530568)

## The Problem
There's categories shown on the front page, stuff like password managers, bookmarks etc. Where are these categories? How can I browse them all? I see like 5 but I'm assuming that's not all of them. Why is there no drop down to scroll through or an expanding grid?

**Comment by jvillalobos** [comment]
They aren't categories, they are curated collections. If you want to see the categories, first you need to click on the type in the main nav (Extensions, Themes) and then you'll see a list of categories for that type.
