### ISSUE TITLE
Make semantic differences between categories and "bundles(?)" more explicit [Design]

### ISSUE THREAD

**Issue by jcklpe** [mozilla/addons#954]
This is a design crit that I wanted to post in order to help improve the addons website UX. I originally posted a single large bug on Bugzilla and was told to post here and to separate my concerns by individual tickets. [[Original bugzilla ticket here]](https://bugzilla.mozilla.org/show_bug.cgi?id=1530568)

## The Problem
The front page, besides having weird demonstration of categories, doesn't seem to explicate the difference between categories, and what appear to be "bundles" of some kind. By bundles I'm referring to the buttons for clicking on stuff like "Stay safe online" or "enhance your media experience". They aren't categories, they seem to be more like a curated selection of extensions. So shouldn't that be said someplace? I can infer from the categories that they're general categories, but it's confusing to see right above that something which isn't a category but looks kinda like it but not really sure what it is. Is it a collection? You can add extensions to your collections so is this that but an official collection?

**Comment by jvillalobos** [comment]
Per my reply on https://github.com/mozilla/addons/issues/953, those aren't categories. They're curated content. The guide pages (I think that's what you're calling "bundles") are just a more narrative way to show curated content. I don't think users need to be told explicitly the type of recommendation they're being given.

**Comment by jcklpe** [comment]
Perhaps, I mean that's up to you guys, but I personally found it pretty confusing.
