### ISSUE TITLE
Weird block organization on extension pages. [Design]

### ISSUE THREAD

**Issue by jcklpe** [mozilla/addons#955]
This is a design crit that I wanted to post in order to help improve the addons website UX. I originally posted a single large bug on Bugzilla and was told to post here and to separate my concerns by individual tickets. [[Original bugzilla ticket here]](https://bugzilla.mozilla.org/show_bug.cgi?id=1530568)

## The Problem
Shouldn't the "rate this extension" block be under the block on the right hand side showing the break down of how the extension has already been rated?

Shouldn't the description of the app be up next to the small blurb of it? Why is it catty-corner and much further down? Overall the details page for the add ons look mega weird, as if someone made a bunch of blocks and then sort of tossed them into a grid. Just because they're each their own individual component doesn't mean that they can be composed interchangeably. There's still importance in how the different blocks spatially relate to each other and this just seems disorganized.

**Comment by jvillalobos** [comment]
There was a major product page redesign underway, but it was put on hold due to changes in priorities. I'd dupe this issue, but we haven't filed anything for the new product page (yet). Keeping it open as a reminder.
