### ISSUE TITLE
Peg "featured extensions" category to top of the pile [Design]

### ISSUE THREAD

**Issue by jcklpe** [mozilla/addons#957]
This is a design crit that I wanted to post in order to help improve the addons website UX. I originally posted a single large bug on Bugzilla and was told to post here and to separate my concerns by individual tickets. [[Original bugzilla ticket here]](https://bugzilla.mozilla.org/show_bug.cgi?id=1530568)

## The Problem
The order seems kind of random the way the other crossections are displayed. You see "featured extensions" but that'sunder "note taking extensions"? Shouldn't featured always be first? After all it's "featured". That's the normal behavior on most other "app store" experiences as least.

**Comment by jvillalobos** [comment]
Homepage content is curated and shuffled around on a regular basis.
