### ISSUE TITLE
Modernize add-on search page [Design

### ISSUE THREAD

**Issue by jcklpe** [mozilla/addons#958]
This is a design crit that I wanted to post in order to help improve the addons website UX. I originally posted a single large bug on Bugzilla and was told to post here and to separate my concerns by individual tickets. [[Original bugzilla ticket here]](https://bugzilla.mozilla.org/show_bug.cgi?id=1530568)

## The Problem
the search page is kinda annoying to use because half the width of the search results is taken up by the filter column. That seems like that could be a great deal smaller, allowing the actual search results to take center stage and maybe show bigger pictures, perhaps with actual screenshots so you can see if the ui for the product is any good or not, and if it's even worth clicking.

Currently the extension pages are not very media rich and as a result it's hard to really get a sense of the extension without installing it, and he firefox extensions page is not nearly as popular as it once was so this is kind of important because one can't simply go by install numbers for a lot of these extensions

**Comment by willdurand** [comment]
Thanks for your input. /cc @jvillalobos @pwalm
