### ISSUE TITLE
Move Search Engines out of Addons website

### ISSUE THREAD

**Issue by jcklpe** [mozilla/addons#959]
This is a design crit that I wanted to post in order to help improve the addons website UX. I originally posted a single large bug on Bugzilla and was told to post here and to separate my concerns by individual tickets. [[Original bugzilla ticket here]](https://bugzilla.mozilla.org/show_bug.cgi?id=1530568)

## The Problem
Search engines still regularly come up along side extensions which is extremely confusing. It would be better to handle search engine package download on an entirely separate site as search engines aren't even listed under the add-ons menu anymore anyway.

**Comment by willdurand** [comment]
Thanks for your input. /cc @jvillalobos @pwalm

**Comment by jvillalobos** [comment]
We intend to move them out, but some changes need to happen in Firefox before we can do that.

**Comment by muffinresearch** [comment]
This will be handled by this upcoming project. https://github.com/orgs/mozilla/projects/100
