### ISSUE TITLE
Malicious User Review Spam

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#962]
There has been a few discussions about the anonymous and no-comment user review policy.

I came across another instance which is worth considering.

As an add-on reviewer, I reviewed and rejected the following add-on:
```
https://addons.mozilla.org/en-US/firefox/addon/smartadblock/
https://reviewers.addons.mozilla.org/reviewers/review/1015097/
```

Few minutes later, the developer of the above rejected add-on left a 1 star review for one of my add-on.
`https://addons.mozilla.org/en-US/firefox/addon/firemonkey/reviews/1305692/`

Developers are using the user-review system to retaliate against addon-reviewers.

@wagnerand @caitmuenster 

PS. Dev also used my addon support page to communicate:
`https://github.com/erosman/support/issues/51#issuecomment-475884254`

**Update:**
Subsequently, a single anonymous user (Firefox user 14714611) has suddenly decided to spam many of my addons with 1 star rating in a row
```
https://addons.mozilla.org/en-US/firefox/addon/copy-plaintext/reviews/1306037/
https://addons.mozilla.org/en-US/firefox/addon/foxytab/reviews/1306040/
https://addons.mozilla.org/en-US/firefox/addon/firemonkey/reviews/1306042/
https://addons.mozilla.org/en-US/firefox/addon/foxypac/reviews/1306047/
```

Also spamming other support topics
`https://github.com/erosman/support/issues/47`

**Comment by smartadblock** [comment]
well there is no other way to contact the reviewer who MALICIOUSLY rejected our extension in the first place. The addon review policy clearly states that jquery version change should trigger an info request and NOT A FULL ON REJECTION.

**Comment by smartadblock** [comment]
Then I take the opportunity to raise the opposite issur: What can we do if a malicious reviewer rejects other extensions to help a competitor??

**Comment by smartadblock** [comment]
The reviewer who abusively rejected now supposedly does not know why it is in a queue and he claims he cannot validate it???

**Comment by smartadblock** [comment]
by the way I actually tried your extension monkey and I really wanted to give it one star.

**Comment by rubaboo** [comment]
> PS. Dev also used my addon support page to communicate:
> `https://github.com/erosman/support/issues/51#issuecomment-475884254`

I reported this behavior to GitHub.

**Comment by caitmuenster** [comment]
Hey @erosman, I'll follow up with you by email; Github isn't the best place to address this. I'll be closing and locking this thread.
