### ISSUE TITLE
RSS Feed Diese Seite wurde leider nicht gefunden.

### ISSUE THREAD

**Issue by JPRuehmann** [mozilla/addons#964]
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/de/firefox/extensions/format:rss?sort=created
Diese Seite wurde leider nicht gefunden. für alle Artikel.
z.B. https://addons.mozilla.org/de/firefox/addon/iitc-button/versions/0.9.0
Thunderbird 60.6.1 Kubuntu 18.04 LTE (32Bit)
### What happened?
Diese Seite wurde leider nicht gefunden. Seite wird angezeigt
### What did you expect to happen?
Erweiterungsseite wird Angezeigt
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by JPRuehmann** [comment]
Und der Firefox geht garnicht. Wird nicht angezeigt soll laut Thunderbird aber aboniert sein.

**Comment by willdurand** [comment]
Hi, sorry but the RSS feeds have been removed recently.
