### ISSUE TITLE
Pack Espanish Colombia no support

### ISSUE THREAD

**Issue by gersongosm** [mozilla/addons#965]
I want to report that the latest version of mozilla does not bring the packete of Spanish Colombia, and the operation of a sofwtare that works with the browser is being affected. How could I get to install the packete of Spanish colombia or what version the latest lot brings.

Thank you.

**Comment by jvillalobos** [comment]
Firefox only supports the languages and variants listed on this page: https://www.mozilla.org/firefox/all/

I'll add that the differences between the different variants of Spanish are fairly minimal.

Also, this repo is for the add-ons website. It's not intended for Firefox issues or add-ons that may or may not be missing from the site.
