### ISSUE TITLE
Thunderbird and Seamonkey clients are not being served redirects to addons.thunderbird.net

### ISSUE THREAD

**Issue by diox** [mozilla/addons#969]
Per https://github.com/mozilla/addons-server/issues/6390 we should be redirecting some Thunderbird and Seamonkey URLs to https://addons.thunderbird.net/

However, when the `User-Agent` of the request is `Thunderbird` or `Seamonkey`, instead we serve it with addons-server and it's 500ing for some URLs that we've removed from addons-server.

The rewrite is visible here:
https://github.com/mozilla-services/cloudops-deployment/blob/b7dde84a0cad09b1d71efc651604b99acd7f18fe/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L216-L219

However, a few lines above, to handle https://github.com/mozilla/addons-frontend/issues/3719 there is another bit of config that directly calls addons-server if the *User Agent* header is Thunderbird or Seamonkey: https://github.com/mozilla-services/cloudops-deployment/blob/b7dde84a0cad09b1d71efc651604b99acd7f18fe/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L205-L210

**That** bit with the User-Agent detection should be removed.

Sentry traceback that helped us figure out that the requests were erroneously going to addons-server: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5328593/

**Comment by diox** [comment]
**STR in simple commands:**
`curl -s https://addons.mozilla.org/es/thunderbird/ --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.5.1" -I | fgrep -i Location`

**Expected results:**
`Location: https://addons.thunderbird.net/es/thunderbird/`

**Actual results:**
`Location: /es/firefox/thunderbird/`

**Comment by bqbn** [comment]
The fix for this is deployed to -dev and -stage. Please test it.

**Comment by AlexandraMoga** [comment]
I've used a pref to override my current user agent - `general.useragent.override` set to `"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Thunderbird/60.6.1"`

https://addons.allizom.org/es/thunderbird/ redirects now to https://addons.thunderbird.net/es/thunderbird/

I've repeated the test for Seamonkey and that worked as well.

![2019-04-03_10-26-25](https://user-images.githubusercontent.com/31961530/55461284-c662e400-55fc-11e9-874b-a41c7690eb64.gif)

**Comment by diox** [comment]
Looks good to me.

**Comment by bqbn** [comment]
The fix is deployed to -prod as well.
