### ISSUE TITLE
External Api v4

### ISSUE THREAD

**Issue by Zitronella** [mozilla/addons#970]
### What happened? 
For example following link shows me no data
https://addons.mozilla.org/api/v4/addons/search/?guid=jid1-BoFifL9Vbdl2zQ@jetpack
(it is guid from Webextension https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/ )

### What did you expect to happen?
that it schows me data

### Anything else we should know?
following link works as expected
https://addons.mozilla.org/api/v4/addons/search/?guid=jid1-XX0TcCGBa7GVGw@jetpack 
(it is guid from Webextension https://addons.mozilla.org/de/firefox/addon/anchors-reveal/ )

i tested it on a fresh firefox profile 66.0.2 (64bit)

**Comment by jvillalobos** [comment]
I see data for both. Can you check again?

**Comment by diox** [comment]
Working for me as well. @Zitronella can you give more info and/or check again ?

**Comment by Zitronella** [comment]
Oh, my goodness. 
I overlooked that everything in this link https://addons.mozilla.org/api/v4/addons/search/?guid=jid1-BoFifL9Vbdl2zQ@jetpack is collapsed by default. It is missing the Butten for folding out. 


![folded](https://user-images.githubusercontent.com/14326582/55506271-4ae15100-5655-11e9-892e-82059b85d9a9.png)
In this link https://addons.mozilla.org/api/v4/addons/search/?guid=jid1-XX0TcCGBa7GVGw@jetpack everything is folded out. (by default)
![unfolded](https://user-images.githubusercontent.com/14326582/55506335-69dfe300-5655-11e9-8110-310a887f5b85.png)

**Comment by diox** [comment]
You might want to file a bug in Firefox itself for that. Closing this one as there is no bug on the API side.

**Comment by jvillalobos** [comment]
I bet that Firefox auto-collapses nodes if they have more than a certain amount of data. The localization text makes one API result much larger than the other.
