### ISSUE TITLE
Unable to use Chrome addons

### ISSUE THREAD

**Issue by SRGOM** [mozilla/addons#972]
### Describe the problem and steps to reproduce it:
It seems that addons from chrome have trouble operating in firefox. 

### What happened?
I downloaded 3 .crx files and uploaded them to AMO. 

* WordWiz - errors. Resolution- unzip, remove optional permission, zip back
* Flipword- no errors
* Flewent- No errors

I installed the signed addons but they don't seem to be able to remember anything I tell them.

### What did you expect to happen?
I expect them to work! 

### Anything else we should know?
I love firefox and I love you guys but I guess this is why they say love hurts?

**Comment by jvillalobos** [comment]
Add-ons ported from Chrome to Firefox may require _some_ coding changes in order to work. You can find documentation about it here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions

This repository is for the add-ons website, so we can't help you with these issues.
