### ISSUE TITLE
Ezusy addon

### ISSUE THREAD

**Issue by sf10105** [mozilla/addons#973]
### Describe the problem and steps to reproduce it:
https://www.ezusy.com/ -> log in -> dashboard -> search -> type and press search -> red popup 'you did not set Ezusy extension. Do you want to do it?'
If yes was clicked -> https://addons.mozilla.org/firefox/downloads/file/1096804/import_aliexpress_products-1.4.9-fx.xpi?src=devhub
If no was clicked, nothing happened.

### What happened?
Addon not found, but is required to use website

### What did you expect to happen?
Link to addon install, then follow install process

### Anything else we should know?
 https://addons.mozilla.org/firefox/downloads/file/1096804/import_aliexpress_products-1.4.9-fx.xpi?src=devhub

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
