### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by Avstes** [mozilla/addons#975]
(function () {
	"use strict";

	var MutationObserver = window.MutationObserver || window.WebKitMutationObserver || window.MozMutationObserver;

	var page = {
		logBook: 'logBook',
		myLogBook: 'myLogBook',
		carsFollowing: 'carsFollowing'
	};

	var BadDriveApp = {

		debug: false,
		data: {},
		$obj: [],
		windowHeight: 0,

		drive: {
			selector: {
				body: 'body',
				bodyToScroll: 'html, body',
				cars: '.c-nav .c-nav-block:nth-child(2) .c-nav-block__link--truncated',
				// like: '.js-like-button:not([disabled])',
				like: '.c-like__button:not([disabled])',
				pages: '.c-pager',
				pageButton: '.c-pager__link',
				pageAttr: 'title'
			}
		},

		logBook: {
			template: {
				menu: '' +
				'<div class="badDrive-like-menu badDrive-like-menu_logbook">' +
				'	<div title="Пролайкать БЖ" class="{like} icons icons_hide icons__like badDrive-like-menu__icon"></div>' +
				'	<div title="Остановить лайки" class="{stop} icons icons_hide icons__stop badDrive-like-menu__icon"></div>' +
				'	<div title="Переход на другу страницу" class="{wait} icons icons__wait badDrive-like-menu__icon badDrive-like-menu__icon_no-hover"></div>' +
				'</div>'
			},
			selector: {
				rightMenu: '.badDrive-like-menu_logbook',
				like: '.js-like-logbook',
				stop: '.js-stop-like-logbook',
				wait: '.js-wait-logbook',
				iconsHide: '.icons_hide',
				anchor: 'like_continue'
			},
			status: {
				like: false
			}
		},

		carsFollowing: {

			text: {
				title: 'BadDrive',
				atPage: 'На странице показано',
				from: 'из',
				showMore: 'Показать ещё',
				stop: 'Остановить',
				checkTitle: 'Проверить машины',
				checked: 'Проверенно машин',
				checkButton: 'Проверить подписки',
				AutoScrollDown: 'Автоскролл'
			},

			template: {
				rightMenu: '' +
				'<nav class="{classNames} badDrive-right-menu badDrive-right-menu_sticky">' +
				'	<h3 class="c-header-side">{text-title}</h3>' +
				'	<ul class="c-side-nav">' +
				'		<li class="badDrive-right-menu__counts">{text-atPage} <span class="js-badDrive-count">{count_at_page}</span> {text-from} <span class="js-badDrive-total">{count_total}</span></li>' +
				'		<li class="badDrive-right-menu__item badDrive-right-menu__moreButton"><button class="c-button js-badDrive-more-button">{text-showMore}</button></li>' +
				'	</ul>' +

				'	<h3 class="c-header-side badDrive-right-menu-padding-top">{text-checkTitle}</h3>' +
				'	<ul class="c-side-nav">' +
				'		<li class="badDrive-right-menu__counts">{text-checked} <span class="js-badDrive-count-checked">0</span> {text-from} <span class="js-badDrive-count">{count_at_page}</span></li>' +
				'		<li class="badDrive-right-menu__item badDrive-right-menu__moreButton"><button class="c-button js-badDrive-check-button">{text-checkButton}</button></li>' +
				'	</ul>' +
				'	<div class="badDrive-right-menu__autoScroll"><label><input type="checkbox" class="js-badDrive-autoScroll-checkbox">{text-AutoScrollDown}</label></div>' +

				'</nav>'
			},

			selector: {
				rightMenu: '.js-page nav',
				followClass: '.c-hover-card__following',
				userCardClass: '.c-hover-card',
				stockMoreButton: '[data-action="subscribe.more"]',
				moreButton: '.js-badDrive-more-button',
				checkButton: '.js-badDrive-check-button',
				count: '.js-badDrive-count',
				autoScrollCheckbox: '.js-badDrive-autoScroll-checkbox',
				autoScrollDiv: '.badDrive-right-menu__autoScroll',
				countChecked: '.js-badDrive-count-checked',
				memberList: '.js-page .g-column-mid .o-spacing',
				memberCounter: '.l-container .counter',
				memberItem: '.c-car-card-side',
				memberChecking: '.checking',
				memberChecked: '.checked',
				memberUnSubscribed: '.unsubscribed',
				memberUserDiv: '.c-username',
				memberUserData: 'ihc-id',
				memberSubscribes: '.c-hover-card__following',
				memberCarName: '.c-car-title',
				temporaryDiv: '.js-following-temporary'
			},

			url: {
				getUserInfo: '/ajax/info/?type=u&id={id}'
			},

			status: {
				subs: false,
				check: false
			},

			allFollow: 'Подписан на вас и все ваши машины',
			yourFollow: 'Подписан на вас'

		},

		location: {
			host: null,
			protocol: null,
			url: false,
			name: false,
			parts: false,
			anchor: false,
			page: 0,
			GET: []
		},

		padLeft: function (nr, n, str) {
			return Array(n - String(nr).length + 1).join(str || '0') + nr;
		},

		writeLog: function (txt) {
			if (this.debug) {
				console.log(txt);
			}
		},

		getWindowHeight: function () {
			this.windowHeight = $(window).height();
		},

		getLocation: function () {
			var self = this;

			this.writeLog('Get location');

			var url = window.location.pathname;
			var parts = (url.slice(-1) == '/') ? url.slice(1, -1).split('/') : url.slice(1).split('/');
			var GET = (window.location.search.length > 0) ? window.location.search.slice(1).split('&') : false;

			this.location['host'] = window.location.host;
			this.location['protocol'] = window.location.protocol.slice(0, -1);
			this.location['url'] = url;
			this.location['parts'] = parts;
			this.location['anchor'] = (window.location.hash.length > 0) ? window.location.hash.slice(1) : false;

			if (GET) {
				GET.forEach(function (item) {
					item = item.split('=');
					self.location.GET[item[0]] = (item[1] !== undefined) ? item[1] : null;
				});
			}

			this.location.page = (this.location.GET['page']) ? this.location.GET['page'] : 0;

			// logbook
			if (parts.length >= 4) {
				if (parts[0] === "r" && parts[4] === "logbook") {
					for (var car in self.data) {
						if (self.data[car].id === parts[2]) {
							self.location['name'] = page.myLogBook;
							break;
						}
					}
					if (self.location['name'] !== page.myLogBook) {
						self.location['name'] = page.logBook;
					}
				}
			}

			// Following
			if (parts.length === 3) {
				if (parts[0] === "users" && parts[2] === "carsfollowing") {
					self.location['name'] = page.carsFollowing;
				}
			}

			this.writeLog(self.location);
			this.writeLog('---');
		},

		getMyCars: function () {
			var self = this;
			this.writeLog('Get my cars');
			$(this.drive.selector.cars).each(
				function () {
					var name = $(this).text();
					var link = $(this).attr('href');
					var id = link.slice(0, -1).split('/').pop();
					var model = link.split('/')[2];
					self.data[name] = {
						id: id,
						model: model,
						link: link
					};
				}
			);
			self.writeLog(self.data);
			self.writeLog('---');
		},

		unrepeatableDelay: function (callback, delay) {
			var timer, self = this;
			clearTimeout(timer);
			timer = setTimeout(function () {
				callback.call(self);
			}, delay);
		},

		scrollTo: function (scroll, time) {
			if (!time) {
				var time = 100;
			}
			this.$obj['bodyToScroll'].stop().animate({
				scrollTop: scroll
			}, time);
		},

		init: function () {

			var self = this;

			if (this.debug) {
				console.clear();
			}

			this.writeLog('BadDrive was init');
			this.writeLog('---');
			this.getMyCars();
			this.getLocation();

			this.$obj['body'] = $(this.drive.selector.body);
			this.$obj['bodyToScroll'] = $(this.drive.selector.bodyToScroll);

			this.getWindowHeight();

			$(window).on('resize', function () {
				self.unrepeatableDelay(self.getWindowHeight, 300);
			});

			if (this.location.name === page.logBook) {
				this.logBookStart();
			}
			if (this.location.name === page.carsFollowing) {
				this.carsFollowingStart();
			}

			//this.fuckingShit();
		},

		logBookStart: function () {
			var self = this;
			var $likes = null;
			self.writeLog('Log book started');

			var rightMenu = this.logBook.template.menu
				.replace('{like}', this.logBook.selector.like.slice(1))
				.replace('{stop}', this.logBook.selector.stop.slice(1))
				.replace('{wait}', this.logBook.selector.wait.slice(1));

			// Find not clicked like buttons at page
			var $buttons = $(self.drive.selector.like);
			var count = $buttons.length;

			// Get pages
			var countPages = $(this.drive.selector.pages).first().find(this.drive.selector.pageButton).last().attr(this.drive.selector.pageAttr);

			countPages = (typeof countPages === 'undefined') ? this.location.page : countPages - 1;

			var nextPage = this.location.protocol + '://' + this.location.host + this.location.url + '?page=' + (parseInt(this.location.page) + 1) + '#' + this.logBook.selector.anchor;
			self.writeLog('this page - ' + this.location.page);
			self.writeLog('total pages - ' + countPages);
			self.writeLog('next page - ' + nextPage);
			self.writeLog('Buttons found - ' + count);

			// Skip if empty
			if (count < 1 && this.location.page >= countPages) return;

			// Make right menu
			this.$obj['body'].append(rightMenu);

			var $rightMenu = $(self.logBook.selector.rightMenu);

			// Find objects
			var $likeBtn = $(this.logBook.selector.like);
			var $stopBtn = $(this.logBook.selector.stop);
			var $waitIcon = $(this.logBook.selector.wait);

			// Hide wait status
			$waitIcon.toggleClass(self.logBook.selector.iconsHide.slice(1));

			// Set current status
			if (this.location.anchor === this.logBook.selector.anchor) {
				self.writeLog('Auto');
				$stopBtn.toggleClass(self.logBook.selector.iconsHide.slice(1));
				self.logBook.status.like = true;
				GoGoLike();
			} else {
				$likeBtn.toggleClass(self.logBook.selector.iconsHide.slice(1));
			}

			// Like button
			var toggleButtons = function () {
				self.logBook.status.like = (!$likeBtn.hasClass(self.logBook.selector.iconsHide.slice(1)));
				$likeBtn.toggleClass(self.logBook.selector.iconsHide.slice(1));
				$stopBtn.toggleClass(self.logBook.selector.iconsHide.slice(1));

				if (self.logBook.status.like) {
					$likes = $(self.drive.selector.like);
					return GoGoLike();
				}

				self.writeLog('Likes was stopped');

			};

			$likeBtn.on('click', function () {
				toggleButtons();
			});
			$stopBtn.on('click', function () {
				toggleButtons();
			});

			// Like function
			function GoGoLike() {
				self.writeLog('Start likes');

				$buttons = $(self.drive.selector.like);
				count = $buttons.length;

				self.writeLog('Buttons found - ' + count);

				var goToNext = function () {
					self.writeLog('Redirect to next page');
					$waitIcon.toggleClass(self.logBook.selector.iconsHide.slice(1));
					$stopBtn.toggleClass(self.logBook.selector.iconsHide.slice(1));
					window.location.href = nextPage;
				};

				function setLike(num) {
					var number = num + 1;
					if (num < count && self.logBook.status.like) {
						var $btn = $($buttons[num]);
						var topScroll = $btn.offset().top - self.windowHeight / 2;

						self.scrollTo(topScroll);

						var observer = new MutationObserver(function (mutations) {

							// А то слишком быстро клацает :)
							setTimeout(function () {
								setLike(num);
							}, 200);
							observer.disconnect();
						});

						observer.observe($btn[0], {attributes: true});
						$btn.trigger('click');
						self.writeLog(number + ' of ' + count + ' - has been clicked');
						num++;
					}

					// Go to next page
					if ((self.logBook.status.like && number === count || count === 0) && (self.location.page < countPages)) {
						goToNext();
					}

					// End likes
					if (self.location.page === countPages && number === count) {
						self.writeLog('This is end');
						$rightMenu.fadeOut(function () {
							$rightMenu.remove();
						});
					}
				}

				setLike(0);
			}
		},

		carsFollowingStart: function () {
			var self = this;
			var count = 0;
			var countChecked = 0;
			var cf_ajax = false;
			var tail = false;

			this.writeLog('Cars following start');

			var countMembers = parseInt($(this.carsFollowing.selector.memberCounter).text());
			var $items = 0;

			function iCountChecked() {

			}

			function iCount(action) {
				var iAction = (action) ? action : 'get';

				if (iAction == 'get') {
					$items = $memberList.find(self.carsFollowing.selector.memberItem);
					count = $items.length;
					return count;
				}
				if (iAction == 'update') {
					$countPlace.text(iCount('get'));
				}
			}

			var $memberList = $(this.carsFollowing.selector.memberList);

			var $stockRightMenu = $(this.carsFollowing.selector.rightMenu);
			console.log($stockRightMenu);

			var $stockButton = $(self.carsFollowing.selector.stockMoreButton);
			tail = $stockButton.data('id');

			var rightMenu = this.carsFollowing.template.rightMenu
				.replace(new RegExp('{count_at_page}', 'g'), iCount())
				.replace('{classNames}', $stockRightMenu.attr('class'))
				.replace('{count_total}', countMembers)
				.replace('{text-title}', self.carsFollowing.text.title)
				.replace(new RegExp('{text-showMore}', 'g'), self.carsFollowing.text.showMore)
				.replace('{text-atPage}', self.carsFollowing.text.atPage)
				.replace(new RegExp('{text-from}', 'g'), self.carsFollowing.text.from)
				.replace('{text-checkTitle}', self.carsFollowing.text.checkTitle)
				.replace('{text-checked}', self.carsFollowing.text.checked)
				.replace('{text-checkButton}', self.carsFollowing.text.checkButton)
				.replace('{text-AutoScrollDown}', self.carsFollowing.text.AutoScrollDown);

			$stockRightMenu.after(rightMenu);

			this.$obj['body'].append('<div class="' + self.carsFollowing.selector.temporaryDiv.slice(1) + '"></div>');
			var $temp = $(self.carsFollowing.selector.temporaryDiv);

			var $countPlace = $(this.carsFollowing.selector.count);
			var $countCheckedPlace = $(this.carsFollowing.selector.countChecked);
			var $moreButton = $(this.carsFollowing.selector.moreButton);
			var $checkButton = $(this.carsFollowing.selector.checkButton);

			var $autoScrollCheckbox = $(this.carsFollowing.selector.autoScrollCheckbox);
			var $autoScrollDiv = $(this.carsFollowing.selector.autoScrollDiv);
			var countTry = 0;

			$moreButton.on('click', function () {
				clickMoreButton();
			});

			$checkButton.on('click', function () {
				clickCheckButton();
			});

			var checked = (localStorage['carsFollowingAutoScrollCheckbox']) ? localStorage['carsFollowingAutoScrollCheckbox'] : true;
			$autoScrollCheckbox.prop('checked', (checked == 'true'));
			$autoScrollCheckbox.on('click', function () {
				localStorage['carsFollowingAutoScrollCheckbox'] = $autoScrollCheckbox.prop('checked');
			});

			//var MutationObserver = window.MutationObserver || window.WebKitMutationObserver || window.MozMutationObserver;
			var observer = new MutationObserver(function (mutations) {
				iCount('update');

				if (!self.carsFollowing.status.subs) {
					$checkButton.prop('disabled', false);
				}

				setTimeout(function () {
					autoLoad();
				}, 300);
			});

			observer.observe($memberList[0], {attributes: false, childList: true});

			function autoLoad() {
				if (self.carsFollowing.status.subs && count < countMembers) {
					var $stockButton = $(self.carsFollowing.selector.stockMoreButton);
					//tail = $stockButton.data('id');
					$stockButton.trigger('click');
					self.writeLog('Click by "Show more"');
				}

				if ($autoScrollCheckbox.prop('checked')) {
					self.writeLog('Auto scrolling to end of the list');
					self.scrollTo($memberList.offset().top + $memberList.height() - self.windowHeight / 2);
					// self.scrollTo($('.l-footer').offset().top - 450);
				} else {
					self.writeLog('Auto scrolling is off');
				}

				if (count >= countMembers) {
					observer.disconnect();
					$moreButton.hide();
					//$autoScrollDiv.hide();
					$checkButton.prop('disabled', false);
					self.writeLog('All items already displayed');
				}
			}

			function autoCheck() {
				countTry++;

				if (self.carsFollowing.status.check && countChecked < count) {

					var $item = $($items[countChecked]);
					var userID = $item.find(self.carsFollowing.selector.memberUserDiv).data(self.carsFollowing.selector.memberUserData);
					var ajaxUrl = self.carsFollowing.url.getUserInfo.replace('{id}', userID + '&tail=' + tail);

					$item.addClass(self.carsFollowing.selector.memberChecking.slice(1));

					self.writeLog('check ' + (countChecked + 1) + ' of ' + count + ' (id - ' + userID + ')');
					$item.addClass('checking');

					if ($autoScrollCheckbox.prop('checked')) {
						self.scrollTo($item.offset().top - self.windowHeight / 2, 0);
					}

					var next = function () {
						countTry = 0;
						setTimeout(function () {
							countChecked++;
							$countCheckedPlace.text(countChecked);

							if (countChecked < count) {
								autoCheck();
							} else {
								if (countChecked < countMembers) {
									$checkButton.trigger('click');
									$checkButton.prop('disabled', true);
									$moreButton.prop('disabled', false);
								} else {
									$checkButton.hide();
								}
								self.writeLog('stop - ' + count + ' of ' + countMembers);
							}

						}, 100);
					};

					var check = function (data) {

						$item.removeClass(self.carsFollowing.selector.memberChecking.slice(1));
						$item.addClass(self.carsFollowing.selector.memberChecked.slice(1));

						$temp.html(data);
						var $carName = $item.find(self.carsFollowing.selector.memberCarName);

						if (countTry == 1) {
							$carName.prepend('[' + (countChecked + 1) + '] ');
						}

						var checkCard = $temp.find(self.carsFollowing.selector.userCardClass);

						if (checkCard.length) {

							var follow = $temp.find(self.carsFollowing.selector.followClass);

							if (follow.length) {

								// todo parse follow & taging $item

								$item.append('<div class="' + self.carsFollowing.selector.followClass.slice(1) + '">' + follow.html() + '</div>');
							} else {
								$item.addClass(self.carsFollowing.selector.memberUnSubscribed.slice(1));
							}
							next();
						} else {
							if (countTry <= 5) {
								self.writeLog('try - ' + countTry);
								autoCheck();
							} else {
								self.writeLog("can't get user card");
								$item.addClass('bad');
								next();
							}
						}
					};

					cf_ajax = $.ajax({
						dataType: "json",
						url: ajaxUrl,
						data: '',
						type: 'GET',
						success: function (data) {
							check(data.html);
						}
					});

				}
			}

			function clickCheckButton() {
				$items.removeClass(self.carsFollowing.selector.memberChecking.slice(1));
				if (cf_ajax) {
					cf_ajax.abort();
				}
				self.carsFollowing.status.check = !(self.carsFollowing.status.check);
				if (self.carsFollowing.status.check) {
					$checkButton.text(self.carsFollowing.text.stop);
					autoCheck();
				} else {
					$checkButton.text(self.carsFollowing.text.checkButton);
				}
				$moreButton.prop('disabled', self.carsFollowing.status.check);
			}

			function clickMoreButton() {
				self.carsFollowing.status.subs = (!self.carsFollowing.status.subs);
				if (self.carsFollowing.status.subs) {
					$moreButton.text(self.carsFollowing.text.stop);
					autoLoad();
				} else {
					$moreButton.text(self.carsFollowing.text.showMore);
				}
				$checkButton.prop('disabled', self.carsFollowing.status.subs);
			}
		},

		//fuckingShit: function () {
		//	console.log(window.__d2_env);
		//	$.ajax({
		//		url: '//www.drive2.ru/ajax/drive',
		//		type: 'POST',
		//		//data: '_=di&car=1739438&.FCTX=_wfqzlwoyisSAAQQQnJ1LldlYi4xOjMxOTQwNAnCma9ml5FVWwScN7IzbZhAJZf_',
		//		data: '_=di&car=487948692951662747&.FCTX=_wfqzlwoyisSAAQQQnJ1LldlYi4xOjMxOTQwNAnCma9ml5FVWwScN7IzbZhAJZf_',
		//		success: function (data) {
		//			console.log(data);
		//		}
		//	});
		//}

	};

	$(document).ready(function () {
		BadDriveApp.init();
	});

})();

**Comment by muffinresearch** [comment]
From the description it's unclear what the issue is. Please can you provide as much information as possible so that we can understand what the issue is?

Please include screenshots and URLs so we know where on the website the problem is occurring.
