### ISSUE TITLE
cannot give star ratings

### ISSUE THREAD

**Issue by thaliel** [mozilla/addons#976]
### Describe the problem and steps to reproduce it:
Trying to give a star rating to an addon

### What happened?
It said "saving star rating", then "There has been an error"

### What did you expect to happen?
Star rating being saved

### Anything else we should know?
I cannot give a star rating to any addon listed in the AMO page, same error everytime I try

**Comment by eviljeff** [comment]
is this still reproducible?  It sounds like something that might be due to an invalid cookie/login state (which should have fixed itself since April)

**Comment by muffinresearch** [comment]
I'm going to close this since we don't have any further info. Please let us know if you're still experiencing the same issue.
