### ISSUE TITLE
Add-ons and Themes

### ISSUE THREAD

**Issue by DogSharkie** [mozilla/addons#979]
This may or may not be a bug, but I wanted to say something about it. 
What has happened is that my theme and ad blocker are "no longer verified for Firefox". However, both of these things caused me no problems (like more bugs or anything). Again, might not be a bug but it messed up my themes and ad blocker and I cant use any of these things anymore (not even new ones that I'm looking for). Also, every time I try to get a new one, it says to "check your connection". I'm assuming this means internet, but I am fully connected. If someone could look into this/help me out it would be greatly appreciated. 
Thank you

**Comment by martinm1000** [comment]
You might want to close this issue, as the previous one is the same. See https://github.com/mozilla/addons/issues/978
