### ISSUE TITLE
Not being able to run or install Add-ons (appears to be corrupt issue)

### ISSUE THREAD

**Issue by StxGitHub** [mozilla/addons#980]
"the add-on downloaded from this site could not be installed because it appears to be corrupt" & "could not download this add-on" issues.

------
We're aware of the issue (which is actually not related to the original problem described here, it's just the same message so that's confusing) and are working on a fix.

_Originally posted by @diox in https://github.com/mozilla/addons/issues/851#issuecomment-489281773_
-------

Is there any known work-around to be able to run add-ons for now? I literally cannot visit specific sites without addblock and noscript, making firefox for me as user pretty much useless. 

"xpinstall.signatures.required" to "false" does not offer me a viable work-around (it doesn't work).

**Comment by jscher2000** [comment]
> Is there any known work-around to be able to run add-ons for now?

It looks like a certificate used to sign many popular extensions expired. (The verification process checks that certificate.) Some people have reported the verification will pass if they roll back their system clock several hours (before midnight GMT), but that could create other issues.

**Comment by StxGitHub** [comment]
> > Is there any known work-around to be able to run add-ons for now?
> 
> It looks like a certificate used to sign many popular extensions expired. (The verification process checks that certificate.) Some people have reported the verification will pass if they roll back their system clock several hours (before midnight GMT), but that could create other issues.

Setting the Date back a day did do the trick. Quite a big issue I'd say, certifications expiring without there being a process in place that re-certificates. Especially considering some of the most crucial add-ons (uBlock, AddBlock, NoScript) seemingly all using the same provider.

**Comment by grahamperrin** [comment]
Please follow Mozilla bug [1548973 - (armagadd-on-2.0) All extensions disabled due to expiration of intermediate signing cert](https://bugzilla.mozilla.org/show_bug.cgi?id=1548973).

**Comment by nenaAdoctrinada** [comment]
[https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047](url)

**Comment by smayer97** [comment]
Link is no good.

**Comment by willdurand** [comment]
This is being handled right now, sorry for the inconvenience. Please see: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
