### ISSUE TITLE
Unable to install addons - Dont spam

### ISSUE THREAD

**Issue by DiamondMiner88** [mozilla/addons#981]
### Unable to install add-ons - Download failed. Please check your connection.
Any new info that was NOT included in #851 please post here for devs to see, DON'T SPAM with things like 
> That happened to me too, my add-ons got unsupported!

Lets not let this post get locked.
Any thing new please post!

I tried switching `DNS` servers on my router, got the `Corrupted addon` error, refreshed firefox and it went back to `Download failed. Please check your connection.`

**Comment by Fsu0413** [comment]
Installing old versions of addons(before 2018.1) works for me, I didn't change the system time nor change xpinstall.signatures.required in about:config.

**Comment by grahamperrin** [comment]
Please follow Mozilla bug [1548973 - (armagadd-on-2.0) All extensions disabled due to expiration of intermediate signing cert](https://bugzilla.mozilla.org/show_bug.cgi?id=1548973).

**Comment by kolorowalyzka** [comment]
whats the ETA for the fix?

**Comment by kolorowalyzka** [comment]
@grahamperrin whats the ETA for the fix?

**Comment by caitmuenster** [comment]
Hey folks, no ETA yet. We'll be providing updates on the forum when we have more information: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by grahamperrin** [comment]
<https://github.com/mozilla/addons/issues/983#issuecomment-489318497>:

> disabled by default so this fix is useless?

I think not. 

@reloxx13 maybe look more broadly, beyond the one preference in your screenshot. 

A default, with Firefox on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/57178518-4cc34d80-6e69-11e9-8b8a-fa71827bf0b4.png)

>> ☑ Allow Firefox to install and run studies

**Comment by willdurand** [comment]
We published a hotfix. More info at: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
