### ISSUE TITLE
Fire Fox 66.0 Hacked!?! Did FireFox team decide to close MOST Add-on in 66.0? or is it morning of 4th May 2019 Judgement Day? 

### ISSUE THREAD

**Issue by achalmoudgal** [mozilla/addons#982]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Suddenly on the morning of 4th May 2019 Most of my FireFox Add-ons were disabled for example the Mozilla run "Firefox DevTools ADB Extension" has also been disabled!?!
Something very fishy!!?? 

### What happened?
regularly used Add-on (even those maintained my renowned companies) were found disabled this morning.

### What did you expect to happen?
Expect a mail or announcement from Mozilla team to give heads up on the matter if it was a planned activity

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
if the Add-ons are uninstalled and when reinstall is attempted the following message is shown
Download failed. Please check your connection.

<img width="540" alt="Wappalyzer" src="https://user-images.githubusercontent.com/13310495/57172767-1c1bed80-6e42-11e9-93da-f397ce5633b9.PNG">

**Comment by Zen-io** [comment]
The same exact thing happened to me, and I mean I have no idea what to do!!

**Comment by grahamperrin** [comment]
Please follow Mozilla bug [1548973 - (armagadd-on-2.0) All extensions disabled due to expiration of intermediate signing cert](https://bugzilla.mozilla.org/show_bug.cgi?id=1548973).

**Comment by KittKatt1229** [comment]
Ditto. I was just watching youtube and at midnight, BOOM! Even my theme was disabled! I was so confused. Tried to reinstall new different theme and extensions, Got the same "Please check your connection" message.

**Comment by nenaAdoctrinada** [comment]
[https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047](url)

**Comment by biziclop** [comment]
But whose idiotic nazi idea was to make it possible to just turn off MY addons remotely without any fucking explanation or an option to manually turn them on?  
What if each remotely-turned-off addons got a nice custom message WHY it was turned off, maybe with a link to a more detailed explanation AND the option of being able to manually enable them?  
You Mozilla are going to a very wrong direction. :(

**Comment by grahamperrin** [comment]
11:12 p.m. PST: The team is currently testing a fix for this issue. In the meantime, signing of new extensions is disabled until the fix is in place.

![Certificate issue causing add-ons to be disabled or fail to install](https://user-images.githubusercontent.com/192271/57176469-6efca180-6e50-11e9-99c3-4ad4b3f8b0d8.png)

**Comment by willdurand** [comment]
This is being handled right now, sorry for the inconvenience. Please see: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by KittKatt1229** [comment]
> 
> 
> But whose idiotic nazi idea was to make it possible to just turn off MY addons remotely without any fucking explanation or an option to manually turn them on?
> What if each remotely-turned-off addons got a nice custom message WHY it was turned off, maybe with a link to a more detailed explanation AND the option of being able to manually enable them?
> Also, you could make a big diary with all important dates in it, like cert expiration dates.
> 
> You Mozilla are going to a very wrong direction. :(

Who said anything about N@zi's? I think you need to relax a bit. It's just a major error that actually could have been a lot worse from what I know. N@zi's aren't everywhere you know? This is just a company having issues with renewing add on verifications that basically shutdown the whole add on and theme page. It may not be such a good company, but I doubt this was intentional. And they could give out an error message, but I'm not sure even they fully know what happened.

**Comment by achalmoudgal** [comment]
Dear Mozilla Team, 
Thanks a Ton for the triage patch. Appreciate your response. One humble request - in future when there are short blackouts of this kind, request you to post a Banner right with in the Browser, for Patches are all in you control.
Regards, 
Achal.
