### ISSUE TITLE
Add-on meltdown

### ISSUE THREAD

**Issue by ilacc1** [mozilla/addons#984]
Follow https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 for updates

<hr />

### Describe the problem and steps to reproduce it:
All add-ons disabled as invalid mid-browsing session. Tried offered remedies (more information, find similar add-ons), but both these link to generic and unhelpful adverts for google data harvesting add-ons.

Then tried fresh install, now can't install any add-ons with  error "Download failed. Please check your connection."

Connection is, of course, fine. Nothing on addons.mozzila.org to suggest maintenance / known issue.   

### What happened?
See above

### What did you expect to happen?
Expected add-ons to not disappear without a reason.

**Comment by ethanhines** [comment]
Workaround: Turn your Pc's date back two days and they magically come back

**Comment by ilacc1** [comment]
:) Thanks Ethan - wild guess: certificate expiration issue?

**Comment by ethanhines** [comment]
Yup. Reddit's on fire right now! Thousands effected! https://www.reddit.com/r/firefox/comments/bkfg00/also_had_all_my_addons_disabled_and_cant/?sort=new

**Comment by Extarys** [comment]
Where can I monitor the progress of this issue on Mozilla's and dev's side? Here?

**Comment by Wilkolicious** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by ilacc1** [comment]
Seems like disabling signature check (xpinstall.signatures.required) works for most add-ons, arguably this is a workaround...

**Comment by Extarys** [comment]
@ilacc1 You are my angel. As soon as I turned it off all add-ons reappeared (20+ of them)

**Comment by benibishi** [comment]
my addons have dissapeared. what is going on. when i try to go and install them in the addon section, it says cannot add adons check the interne connection. my connection is fine. it is working with other browsers. Download failed. Please check your connection.

**Comment by NickLaMuro** [comment]
@benibishi Please read a few comments up before posting:

https://github.com/mozilla/addons/issues/984#issuecomment-489287777

There is info in those tickets and the team seems to be actively looking into the issue.

**Comment by benibishi** [comment]
Ok

**Comment by kodeart** [comment]
You can still see your addons in preferences (Ctrl + Shift+ A) under "Unsupported" tab.

**Comment by willdurand** [comment]
This is being handled right now, sorry for the inconvenience. Please see: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
