### ISSUE TITLE
cannot install addons

### ISSUE THREAD

**Issue by kolorowalyzka** [mozilla/addons#985]
### Describe the problem and steps to reproduce it:
firefox 66
addons do not work

### What happened?
was browsing the internet, when new tab displayed the message that all addons were disabled
tried to reinstall, for every addon it shows "download failed, check your connection"

### What did you expect to happen?
I expected such things not to happen

### Anything else we should know?
no

**Comment by flamber** [comment]
Did you look at one of the 6 other issues created the past two hours?
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973
https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by caitmuenster** [comment]
Yep, I'm going to close this issue. Best place for tracking updates is https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
