### ISSUE TITLE
Unable to install add-ons: Download failed, check your connection

### ISSUE THREAD

**Issue by BrianHare** [mozilla/addons#986]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Firefox 66.0.3 64 bit running on Windows 10 Education. 
Informed that previously-installed LastPass password manager plugin (lastpass.com) was no longer supported, new version required. Removed previous extension, went to page to get new add-on. 

Got message: Download failed, check your connection. (I've got fiber, everything else, including Firefox, seems able to go anywhere on the net w/ no problem.) 

Went to lastpass.com, logged on there, went through the link on that site to get the browser add-on; it redirected back to https://addons.mozilla.org/en-US/firefox/addon/lastpass-password-manager/. 

Again, "Download failed, check your connection." 

Closed firefox, restarted. Same result. 
### What happened?
Unable to install LastPass add-on
### What did you expect to happen?
Installing the LastPass add-on.  Failing that, some hint about possible workarounds or indication of what the problem is. As near as I can tell, everything about my connection BUT downloading that add-on is working fine. 
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Addendum: Same behavior, with same error message, for other add-ons. It appears to be a general issue with installation of add-ons, not just LastPass. (Also affecting Adblock Plus, DuckDuckGo Privacy Essentials). 

Addendum II: Rebooted computer. Now download proceeds, & there's another error message: Unable to install this add-on because it appears to be corrupt. 
Attempting re-download returns to the "download failed" message.

**Comment by caitmuenster** [comment]
This is due to a certificate issue. Our team is currently working on a fix and we'll be providing updates on this thread: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/4

**Comment by Joel60H** [comment]
caitmunster, Thank-you for your diligence in this matter, and please add me to the voluminous "Me Too" file :-)

**Comment by BrianHare** [comment]
Thanks for the prompt response!
