### ISSUE TITLE
Ublock is being called unverified and therefore automatically uninstalled from Firefox 

### ISSUE THREAD

**Issue by gnr2bernstein** [mozilla/addons#987]
### Describe the problem and steps to reproduce it:
Can no longer use the Ublock add on in Firefox only because Firefox is saying it is unsafe and can't be verified. 

### Anything else we should know?

Ublock is a top add on and a staff pick. Others are having this issue with other addons as well.

**Comment by AdrianoCahete** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by caitmuenster** [comment]
Hi there! This is due to a security issue. Our team is currently working on a fix. You can follow this thread for updates: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
