### ISSUE TITLE
Adding an addon

### ISSUE THREAD

**Issue by Wnxsparkman** [mozilla/addons#988]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What did you expect to happen?
To be able to download the add-on. 
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by caitmuenster** [comment]
Hi there! This is due to a security issue. Our team is currently working on a fix. You can follow this thread for updates: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
