### ISSUE TITLE
themes firefox

### ISSUE THREAD

**Issue by negroenvidioso** [mozilla/addons#989]
### Describe the problem and steps to reproduce it:
Can't install themes, indicates an internet connection error

### What happened?
can't install themes and in turn doesn't let you use old themes
### What did you expect to happen?
I don't know
### Anything else we should know?
no

**Comment by caitmuenster** [comment]
Hi there! This is due to a security issue. Our team is currently working on a fix. You can follow this thread for updates: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
