### ISSUE TITLE
oops we had an error when uploading plugin

### ISSUE THREAD

**Issue by alainrobert** [mozilla/addons#991]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?

Uploading an extension zip generated with web-ext the validation works properly but when I press sign add-on , I get the Oops we had an error message. 

When I try to sign the file using web-ext  sign the process ends in timeout. I can see a plugin created with no version in the server

Error: Validation took too long to complete; last status: {"guid":"{d04a2ad2-ede1-41df-86e4-ad36ac518de6}","active":false,"automated_signing":true,"url":"https://addons.m
ozilla.org/api/v3/addons/%7Bd04a2ad2-ede1-41df-86e4-ad36ac518de6%7D/versions/2.1/uploads/3f0d218f37534f57ab7bc1caf00b7eee/","files":[],"passed_review":false,"pk":"3f0d218
f37534f57ab7bc1caf00b7eee","processed":true,"reviewed":false,"valid":true,"validation_results":{"success":true,"compatibility_summary":{"warnings":0,"errors":0,"notices":
0},"notices":0,"warnings":0,"errors":0,"messages...
    at Timeout._onTimeout (C:\Users\ALAINRobert\AppData\Roaming\npm\node_modules\web-ext\node_modules\sign-addon\dist\webpack:\src\amo-client.js:232:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
### What did you expect to happen?

should have create a version of the plugin

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
[case_for_l3-2.2.zip](https://github.com/mozilla/addons/files/3144050/case_for_l3-2.2.zip)

**Comment by caitmuenster** [comment]
Hi there! This is due to a a certificate issue. Our team is currently working on it and we'll be providing updates on this thread:  https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
