### ISSUE TITLE
Problem in downloading firefox extensions 

### ISSUE THREAD

**Issue by GabrieleFabrizio** [mozilla/addons#993]
### Describe the problem and steps to reproduce it:
I accessed any extension page (for example Facebook Container), but when I tried to download and install the extension a message appeared, saying the download wasn't possible due to the absence of internet connection. Of course my internet connection was working fine

I am using Firefox Quantum 66.0.3 (64bit) italian version on win 10 pro 64bit italian

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Spangler16** [comment]
Try this -- it's a workaround I'm using while Mozilla fixes the bug:  https://github.com/mozilla/addons/issues/994#issuecomment-489302311

**Comment by nenaAdoctrinada** [comment]
[https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047](url)

**Comment by grahamperrin** [comment]
This is a known issue. You'll find updates from Mozilla at: 

- [Certificate issue causing add-ons to be disabled or fail to install - Add-ons / Announcements - Mozilla Discourse](https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047)

**Comment by smayer97** [comment]
@nenaAdoctrinada link is no good.

**Comment by willdurand** [comment]
This is being handled right now, sorry for the inconvenience. Please see: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by grahamperrin** [comment]
@willdurand thanks

For those of us who currently can not read the announcement, here's a screenshot (including an update re: testing a fix): 

https://s.put.re/ApdK8Qz2.png
