### ISSUE TITLE
can't install addons

### ISSUE THREAD

**Issue by hacker104** [mozilla/addons#995]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
i click on the add to firefox button and it gives this error
### What happened?
![afbeelding](https://user-images.githubusercontent.com/15986802/57175458-a2d5c800-6e4c-11e9-8ac4-9320a0cf4dd5.png)
my addons where legisy but i need a adblocker so bad and i can't install dem
### What did you expect to happen?
thad the addon installed it self
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
not thad i know

**Comment by Spangler16** [comment]
Try this -- it's a workaround I'm using while Mozilla fixes the bug:  https://github.com/mozilla/addons/issues/994#issuecomment-489302311

**Comment by nenaAdoctrinada** [comment]
[https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047](url)

**Comment by alex24033** [comment]
I just got this error after Windows installed KB4495667 (OS Build 17763.475) update

**Comment by willdurand** [comment]
This is being handled right now, sorry for the inconvenience. Please see: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
