### ISSUE TITLE
Addon downloads fail

### ISSUE THREAD

**Issue by kstenerud** [mozilla/addons#996]
### Describe the problem and steps to reproduce it:

Go to https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/?src=search
Click "Add to Firefox"

### What happened?

"Download failed. Please check your connection."

### What did you expect to happen?

I expected it to download.

### Anything else we should know?

Other addons, such as https://addons.mozilla.org/en-US/firefox/addon/video-downloader-profession/?src=find-replacement work fine.

**Comment by nenaAdoctrinada** [comment]
[https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047](url)

**Comment by stuart-little** [comment]
Affected by this too, on: 

- Linux x86_64, Firefox 66.0.3
-Android 9, Firefox Beta 66.0.2
-Android 9, Firefox Beta 67.0
-Android 9, [Fennec 66.0.2](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/)

As reported [earlier](https://github.com/mozilla/addons/issues/978#issuecomment-489280450), [Privacy Pass](https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/) is installable on all of these platforms. Nothing else I've tried is though.  

Also, GNU's [IceCatMobile](https://f-droid.org/en/packages/org.gnu.icecat/) 60.5.1 isn't exhibiting the issue.

**Comment by willdurand** [comment]
This is being handled right now, sorry for the inconvenience. Please see: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
