### ISSUE TITLE
Video DownloadHelper app will not download to Firefox

### ISSUE THREAD

**Issue by Mvanw** [mozilla/addons#998]
### Describe the problem and steps to reproduce it:
Attempted to add Video DownloadHelper to Firefox.
Clicked on <Add to Firefox> and received this message:
"Download failed. Please check your connection"

After repeated attempts with the same failure message, I uninstalled Firefox and then re installed it.

With no other apps running in Firefox, I once again attempted to add Video DownloadHelper.
Same result.

![image](https://user-images.githubusercontent.com/50262203/57177014-a9087c00-6e2d-11e9-9e1e-4c194023c92b.png)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by willdurand** [comment]
Sorry, this is due to a certificate issue. Our team is currently working on a fix and we'll be providing updates on this thread: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/4.
