### ISSUE TITLE
Firefox just killed almost all add-ons

### ISSUE THREAD

**Issue by SteenG** [mozilla/addons#999]
### Describe the problem and steps to reproduce it:
Well Firefox did this, not the user.

### What happened?
Firefox killed most add ons

### What did you expect to happen?
Nothing - just leave the add-ons working

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by willdurand** [comment]
Hi, sorry we're having a cert issue. We're working on fixing this, more info at: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by SteenG** [comment]
But there is at one thing that still seem strange DR TV1 can't fetch the video files from the page.




Få Outlook til Android







On Sat, May 4, 2019 at 11:51 AM +0200, "William Durand" <notifications@github.com> wrote:












Closed #999.
